### PR TITLE
fix(core): add globPatternforDependencies support nx:run-commands wi…

### LINKED ISSUE #12721: Nx tailwind util (globPatternforDependencies) behavior changed after Nx 14.6.2
Sorry if this is a duplicate issue, I've looked around and found some similar issues but not sure if any matched this in particular.

## Current Behavior

I started noticing `...createGlobPatternsForDependencies(__dirname)` returns an empty list. It stopped working as I expected with NX 14.6.2. I used to use 14.5.7 and upgraded to the latest version and discovered there was an issue.

It only started working again after the project-specific commands (with the `nx:run-commands` executor and the `cwd` option for that executor) that relied on tailwind were modified to run from the root of the NX monorepo, instead of from the project directory itself (i.e. removing the `cwd` option in the executor). Is this expected behavior going forward? I opened this issue because I wasn't sure if that's the expected behavior going forward (although ideally it could work without being dependent on being run from the root).

## Expected Behavior
I expect it to resolve our project graph and the libraries, instead of returning no results.

It works fine from within a specific app directory in 14.6.1 and below.

I noticed in this release that there's a PR related to tailwind; not sure if this broke the expected behavior.

https://github.com/nrwl/nx/releases/tag/14.6.2 (specific [PR](https://github.com/nrwl/nx/issues/11747))

## Steps to Reproduce

The app-specific tailwind config looks like this, and I run tailwind CLI in that specific app's directory to generate the styles for one of our projects. For another vite-based project, I have a postcss.config.js and our vite config is executed within that project directory.

```

const { join } = require("path");

// available since Nx v 12.5
const { createGlobPatternsForDependencies } = require("@nrwl/react/tailwind");

/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require("../../tailwind-workspace-preset.js")],
  content: [
    join(__dirname, "app/**/*.{ts,tsx}"),
    ...createGlobPatternsForDependencies(__dirname)
  ]
};

```

### Failure Logs
I noticed it started showing this error with no changes having been made.

```
[createGlobPatternsForDependencies] WARNING: There was no ProjectGraph available to read from, returning an empty array of glob patterns
```

### Environment

This is the version that it stops working in.

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : linux x64
   yarn : 3.2.4
   
   nx : 14.6.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.6.2
   @nrwl/detox : 14.6.2
   @nrwl/devkit : 14.6.2
   @nrwl/eslint-plugin-nx : 14.6.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.6.2
   @nrwl/js : 14.6.2
   @nrwl/linter : 14.6.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.6.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 14.6.2
   @nrwl/react : 14.6.2
   @nrwl/react-native : 14.6.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.6.2
   @nrwl/web : 14.6.2
   @nrwl/workspace : 14.6.2
   typescript : 4.8.4
   ---------------------------------------
   Community plugins:
   	@nrwl/remix: 14.7.0
   	@trumbitta/nx-plugin-unused-deps: 1.12.1
   	nx-plugin-vite: 2.2.1
```

### PR DESCRIPTION
**Pull request by vitld**
…th cwd option

As globPatternforDependencies expects cwd to be in workspaceRoot, it will fail if it's used in a script that is called via `nx:run-commands` with `cwd` option pointing to project. This \"fix\" resolves paths to allow the script to run even from project dir.

Closes issues: #12721

## Current Behavior

When running a script that utilises `globPatternforDependencies` from workspace package in a target that uses `nx:run-commands` executor together with `cwd` option pointing to project root then that script will fail because it can not resolve the paths correctly.
An example would be a migrated CRA application that should run `craco start` from project root and contains a tailwind config per documentation.

## Expected Behavior

Running target with `nx:run-commands` with `cwd` option should not break `globPatternforDependencies`.

## Related Issue(s)

Fixes #12721

EDIT(26/10/2022): Edited due to changed fix implementation

### CODE REVIEW

File: packages/workspace/src/utilities/generate-globs.ts [hunk 1]
```diff
@@ -52,6 +52,10 @@ export function createGlobPatternsForDependencies(
       projectGraph
     );
 
+    // change cwd to support scripts running from project folder, mainly nx:run-commands with cwd option
+    const initialCwd = process.cwd();
+    if (initialCwd !== workspaceRoot) process.chdir(workspaceRoot);
```
Comment (AgentEnder) [inline packages/workspace/src/utilities/generate-globs.ts:57]: Rather than changing `process.cwd`, we should be able to resolve the paths relative to workspaceRoot. The changeset would probably be a bit larger, but I think it would be preferred.

**Review by AgentEnder — CHANGES_REQUESTED** [review]

File: packages/workspace/src/utilities/generate-globs.ts (hunk 1 above)
Comment (ViktorPontinen) [reply packages/workspace/src/utilities/generate-globs.ts:57]: I would agree. I initially went on that track but stumbled across issues that seemed to go deeper than the scope of `globPatternforDependencies`, possibly in the `ignore` library. But i'll revisit!

Comment (AgentEnder) [reply packages/workspace/src/utilities/generate-globs.ts:57]: IIRC `ignore` requires that the paths are relative. Might need to resolve, and then make relative rather than just going w/ the fully resolved paths.

Comment (ViktorPontinen) [reply packages/workspace/src/utilities/generate-globs.ts]: Changed implementation as suggested.
I was able to solve my original issue with the `ignore` lib which stemmed from the 5.0.0 update to the library.
See: https://github.com/kaelzhang/node-ignore/issues/20 for context.
I was trying to pass relative paths as `../foo/bar` which it does not accept and the thrown error that was a bit misguiding:
`path should be a path.relative()d string, but got "../foo/bar"` and in my world `../foo/bar` is a "relative()d" string :)

**Review by AgentEnder — APPROVED** [review]
