### PR TITLE
fix(core): format global config files modified by nx migrate

### LINKED ISSUE #8928: nx migrate doesn't respect configured indent_size
## Current Behavior

The `nx migrate` command doesn't respect the configured `indent_size` in `.editorconfig` or `tabWidth` in `.prettierrc`.

When running the `nx migrate` command, the tab spacing `package.json` is set to `2`, regardless of configured tab spacing.

## Expected Behavior

The `nx migrate` command should respect the configured tab spacing.

## Steps to Reproduce

1. Create an empty workspace with an older version of Nx.
2. Set the `indent_size` in `.editorconfig` to `4`.
3. Run `nx format:write` to update the tab spacing of the workspace.
4. Run `nx migrate latest`.
5. Check `package.json`, notice that `nx migrate` has reverted the tab spacing to `2`.

### Failure Logs

N/A

### Environment

```
Node : 16.13.2
OS   : darwin x64
npm  : 8.1.2

nx : 13.8.0
@nrwl/angular : undefined
@nrwl/cli : 13.8.0
@nrwl/cypress : undefined
@nrwl/detox : undefined
@nrwl/devkit : 13.8.1
@nrwl/eslint-plugin-nx : 13.8.0
@nrwl/express : undefined
@nrwl/jest : 13.8.0
@nrwl/js : 13.8.1
@nrwl/linter : 13.8.0
@nrwl/nest : undefined
@nrwl/next : undefined
@nrwl/node : undefined
@nrwl/nx-cloud : undefined
@nrwl/react : undefined
@nrwl/react-native : undefined
@nrwl/schematics : undefined
@nrwl/storybook : undefined
@nrwl/tao : 13.8.0
@nrwl/web : undefined
@nrwl/workspace : 13.8.0
typescript : 4.5.5
rxjs : 6.6.7
---------------------------------------
Community plugins:
```

### PR DESCRIPTION
**Pull request by leosvelperez**
## Related Issue(s)

Fixes #8928

### CODE REVIEW

File: packages/nx/src/command-line/migrate/migrate.ts [hunk 1]
```diff
@@ -1318,6 +1320,54 @@ async function generateMigrationsJsonAndUpdatePackageJson(
   }
 }
 
+async function writeFormattedJsonFile(
+  filePath: string,
+  content: any,
+  options?: JsonWriteOptions
+): Promise<void> {
+  let prettier: typeof Prettier;
```
Comment (FrozenPandaz) [inline packages/nx/src/command-line/migrate/migrate.ts:1328]: Can we reuse this logic from the generator util?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Comment by FrozenPandaz** [comment]
Is this issue related? https://github.com/nrwl/nx/issues/25122

**Comment by leosvelperez** [comment]
> Is this issue related? #25122

That one is due to some migration generators not formatting files at the end. I created a separate PR for it: https://github.com/nrwl/nx/pull/27082.

**Review by FrozenPandaz — APPROVED** [review]
