### PR TITLE
fix(core): file-utils workspaceFileName now returns proper file name

### LINKED ISSUE #2253: workspaceFileName() failed to give the correct filename when whe have @angular/cli as a dependency but using the workspace.json configuration file
# Prerequisites

## Expected Behavior

workspaceFileName() should return  *workspace.json* 

## Current Behavior

workspaceFileName() returns  *angular.json* 

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create an nx project without angular
2. npm install @angular/cli package
3. `nx dep-graph`
3. It will throw 'no such file or directory, open '.../angular.json'

### Context

Please provide any relevant information about your setup:

```
nx --version 
8.9.0
```

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

1. create an nx project without angular
2. `npm install @angular/cli`
3. `nx dep-graph`
   
### Failure Logs

Error: ENOENT: no such file or directory, open '.../angular.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.readJsonFile (...\node_modules\@nrwl\workspace\src\utils\fileutils.js:60:44)
    at Object.readWorkspaceJson (...\node_modules\@nrwl\workspace\src\command-line\shared.js:256:24)
    at Object.generateGraph (...\node_modules\@nrwl\workspace\src\command-line\dep-graph.js:29:36)
    at Object.exports.commandsObject.yargs.usage.command.command.command.command.command.command.command.command.command.command.command.command.command.args [as handler]

### PR DESCRIPTION
**Pull request by NathanWalker**
This PR picks up where https://github.com/nrwl/nx/pull/2594 left off and fixed all unit tests - thanks to @scallacs original efforts - this one had plagued us for awhile.

## Current Behavior

workspaceFileName() returns 'angular.json' when @angular/cli is in package.json devDependencies even if workspace.json is used.

## Expected Behavior

workspaceFileName() should return `workspace.json` if Nx was configured that way or `angular.json` if it's configured using angular cli.

## Issue

closes https://github.com/nrwl/nx/issues/2253

### CODE REVIEW

**Review by juristr — APPROVED** [review]
LGTM 👍

File: packages/workspace/src/core/file-utils.ts [hunk 1]
```diff
@@ -172,11 +172,7 @@ export function cliCommand() {
 }
 
 export function workspaceFileName() {
-  const packageJson = readPackageJson();
-  if (
-    packageJson.devDependencies['@angular/cli'] ||
-    packageJson.dependencies['@angular/cli']
-  ) {
+  if (fileExists('angular.json')) {
```
Comment (FrozenPandaz) [inline packages/workspace/src/core/file-utils.ts:175]: Use `appRootPath` to make sure this works when executing from somewhere other than the root of a workspace.
```suggestion
  if (fileExists(`${appRootPath}/package.json`)) {
```

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Comment by FrozenPandaz** [comment]
Looks good, just one minor fix :+1:

**Comment by NathanWalker** [comment]
@FrozenPandaz great catch - updated now 👍

**Comment by juristr** [comment]
Cool, thx @NathanWalker 👍
