### PR TITLE
fix(rspack): ensure nest applications generated correctly #31204

### LINKED ISSUE #31204: @nx/rspack:application fails with "--framework=nest"
### Current Behavior

Attempt to generate a new NestJS application using the @nx/rspack:application generator fails with "NX   The project server cannot be converted to use the @nx/rspack executors."

Image

### Expected Behavior

I expect a new NestJS backend application to be generated under "apps/server". The application should be configured to use rspack, and explicitly define an executor in project.json.

### GitHub Repo

https://github.com/rujorgensen/nx-rspack-app-generator-issue

### Steps to Reproduce

1. Create new workspace
`npx create-nx-workspace nx-workspace --preset=nest --no-interactive`

2. Enter the directory and install nx/rspack
`cd nx-workspace && pnpm exec nx add @nx/rspack`

<*** THIS IS WHERE THE GITHUB REPO IS AT  ***>

3. Generate a NestJS application
`pnpm exec nx generate @nx/rspack:application --directory=apps/server --framework=nest --e2eTestRunner=none --name=backend-server --no-interactive`

🛑 Observe that the generator fails with "NX  The project server cannot be converted to use the @nx/rspack executors." 🛑

### Nx Report

```shell
Your repository uses a higher version of Nx (21.0.3) than your global CLI version (20.7.1)
For more information, see https://nx.dev/more-concepts/global-nx


 NX   Report complete - copy this into the issue template

Node           : 20.11.1
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 9.10.0

nx (global)        : 20.7.1
nx                 : 21.0.3
@nx/js             : 21.0.3
@nx/jest           : 21.0.3
@nx/eslint         : 21.0.3
@nx/workspace      : 21.0.3
@nx/devkit         : 21.0.3
@nx/eslint-plugin  : 21.0.3
@nx/nest           : 21.0.3
@nx/node           : 21.0.3
@nx/rspack         : 21.0.3
@nx/web            : 21.0.3
@nx/webpack        : 21.0.3
typescript         : 5.7.3
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
---------------------------------------
Cache Usage: 0.00 B / 100.69 GB
```

### Failure Logs

```shell
NX  Generating @nx/rspack:application


 NX   The project backend-server cannot be converted to use the @nx/rspack executors.

Pass --verbose to see the stacktrace.
```

### Package Manager Version

❯ pnpm -v 9.10.0

### Operating System

- [ ] macOS
- [x] Linux
- [x] Windows
- [x] Other (Please specify)

### Additional Information

Using WSL2.

The rspack configuration **has been broken for our team since NX v. 20.1.4**. Related issues:
https://github.com/nrwl/nx/issues/30292
https://github.com/nrwl/nx/issues/29482
https://github.com/nrwl/nx/issues/29388

### PR DESCRIPTION
**Pull request by Coly010**
- fix(rspack): choosing nest as framework should not result in error #31204
- fix(rspack): add deprecation message for application generator
- fix(rspack): ensure application generated projects are added to excludes

## Current Behavior
Running the `@nx/rspack:application` generator with `--framework=nest` results in an error due to mix of inferred and executor usage throughout the generation process.

## Expected Behavior
Running the generator should pass without failure and create a working project.
Deprecate the generator in favour of using project specific packages (@nx/react etc)

## Related Issue(s)

Fixes #31204

### CODE REVIEW

File: packages/rspack/src/generators/application/application.ts [hunk 1]
```diff
@@ -1,14 +1,81 @@
...
 
 export default async function (
   tree: Tree,
   _options: ApplicationGeneratorSchema
 ) {
+  // Add deprecation warning with alternatives based on framework
+  const framework = _options.framework || 'react'; // Default is react
+
+  logger.warn(
+    `The @nx/rspack:application generator is deprecated and will be removed in Nx 22. ` +
```
Comment (jaysoo) [inline packages/rspack/src/generators/application/application.ts:74]: Add a `TODO(v22)` so we can find it later

**Review by jaysoo — APPROVED** [review]

File: packages/rspack/src/generators/application/application.ts (hunk 1 above)
Comment (Coly010) [reply packages/rspack/src/generators/application/application.ts:74]: @claude can you add a `// TODO(v22) - remove this generator` to ensure it does not get missed in the next major
