### PR TITLE
fix(nextjs): fix Next.js schematics to support dynamic routes and remove unnecessary next plugins (as of 9.5)

### LINKED ISSUE #2478: Next with SCSS and customServerPath option are failing to serve on production mode.
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Next + Scss project should successfully serve production build when `customServerPath` is used.

On: `nx serve {next project name} --configuration=production` Nx should build and serve production build of that project.

## Current Behavior

After a successful build, any next page visited that imports .scss file throws an error!

## Failure Information (for bugs)

```
[ error ] ./pages/index.scss
TypeError: this[MODULE_TYPE] is not a function
Could not find files for /index in .next/build-manifest.json
ModuleBuildError: Module build failed (from /Users/vkrizic/tmp/happynrwl/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[MODULE_TYPE] is not a function
    at /Users/vkrizic/tmp/happynrwl/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js:141:24
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:343:11
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1414:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/vkrizic/tmp/happynrwl/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/vkrizic/tmp/happynrwl/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (/Users/vkrizic/tmp/happynrwl/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/vkrizic/tmp/happynrwl/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js:143:14
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:343:11
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1414:32
ModuleBuildError: Module build failed (from /Users/vkrizic/tmp/happynrwl/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[MODULE_TYPE] is not a function
    at /Users/vkrizic/tmp/happynrwl/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js:141:24
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:343:11
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1414:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/vkrizic/tmp/happynrwl/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/vkrizic/tmp/happynrwl/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (/Users/vkrizic/tmp/happynrwl/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/vkrizic/tmp/happynrwl/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js:143:14
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:343:11
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1414:32
```

### Steps to Reproduce

1. pull my repository which sets up basic scenario to reproduce this issue. `https://github.com/krizic/nx-next-scss-prod-error`
2. run `npm install`
3. run `nx serve app-next --configuration=production`

### Context

```  
  @nrwl/angular : Not Found
  @nrwl/cli : 9.0.0
  @nrwl/cypress : 9.0.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.0
  @nrwl/linter : 9.0.0
  @nrwl/nest : Not Found
  @nrwl/next : 9.0.0
  @nrwl/node : Not Found
  @nrwl/react : 9.0.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.0
  @nrwl/web : 9.0.0
  @nrwl/workspace : 9.0.0
  typescript : 3.7.5
```

Observe that `server.js` is wired up as `customServerPath` project build property as described in the documentation

### PR DESCRIPTION
**Pull request by jaysoo**
Cleaning up schematics because now that we're on Next.js 9.5, some plugins are unnecessary. Also changes the page schematic to support dynamic routes better.

Closes #2478, #2490

### CODE REVIEW

File: packages/workspace/src/utils/name-utils.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ export function names(
  * hypenated to UpperCamelCase
  */
 export function toClassName(str: string): string {
-  return toCapitalCase(toPropertyName(str));
+  return toCapitalCase(toPropertyName(str.replace(/[^a-zA-Z\d]/g, '')));
```
Comment (jaysoo) [inline packages/workspace/src/utils/name-utils.ts:26]: Because Next.js files can contain `[]` characters, we need to strip these off for class name.

Comment (BigAB) [reply packages/workspace/src/utils/name-utils.ts:26]: could the `[` and `]` characters just get added to the `toPropertyName` regex replace?

Comment (jaysoo) [reply packages/workspace/src/utils/name-utils.ts:26]: Hmm, yeah that would be good.

**Review by BigAB — APPROVED** [review]
