### PR TITLE
fix(core): read project name from package json if not set in project json

### LINKED ISSUE #26347: package name is not inferred from scope without project.json file
### Current Behavior

I have my root package.json name to be `orbitkit` and every package in the workspace has the `@orbitkit` scope name so for example, `@orbitkit/utils`.

Whenever I try to run a comman like `nx build utils` it throws out an error saying the project does not exist, works if i do `nx build @orbitkit/utils`.

However, the moment I create a `project.json` file in the package, even if it's empty, I can do `nx build utils`.

### Expected Behavior

I expect the naming of the packages without the scope to be realised by nx without needing to create empty project.json files.

### GitHub Repo

https://github.com/ixahmedxi/orbitkit/tree/nx

### Steps to Reproduce

1. Clone the repo
2. Run `bun install`
3. Run `bun nx build utils`, observe the error
4. Add an empty `project.json` file to `packages/utils`
5. Run `bun nx build utils`, observe that it now behaves as expected.

### Nx Report

```shell
Node   : 20.12.2
OS     : linux-x64
bun    : 1.1.10

nx          : 19.1.2
@nrwl/tao   : 19.1.2
typescript  : 5.4.5
```

### Failure Logs

_No response_

### Package Manager Version

bun 1.1.10

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
If `project.json` exists without a name, we infer one based on the root path. This can be confusing when there exists a `package.json` alongside it that contains a name which doesn't match our inferred name.

## Expected Behavior
If `project.json` and `package.json` both exist, the name from `package.json` will be used if `project.json` contains no name.

## Related Issue(s)

Fixes #26347

### CODE REVIEW

File: packages/nx/src/plugins/project-json/build-nodes/project-json.ts [hunk 1]
```diff
@@ -30,9 +33,21 @@ export function buildProjectFromProjectJson(
...
+      name ?? readNameFromPackageJson(packageJsonPath) ?? toProjectName(path),
+    root: root ?? dirname(path),
+    ...rest,
   };
 }
+
+export function readNameFromPackageJson(path: string): string {
+  try {
+    const json = readJsonFile<PackageJson>(path);
+    return buildProjectConfigurationFromPackageJson(json, path, {}).name;
```
Comment (FrozenPandaz) [inline packages/nx/src/plugins/project-json/build-nodes/project-json.ts:49]: Do not reuse this function. Just read the correct properties.

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/nx/migrations.json [hunk 2]
```diff
@@ -83,6 +83,12 @@
       "version": "19.2.2-beta.0",
       "description": "Updates the nx wrapper.",
       "implementation": "./src/migrations/update-17-3-0/update-nxw"
+    },
+    "19-2-3-set-project-name": {
+      "version": "19.2.3-beta.0",
```
Comment (FrozenPandaz) [inline packages/nx/migrations.json:88]: You'll have to update the version

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
