### PR TITLE
fix(core): create multi-glob function

### LINKED ISSUE #29473: Incorrect Handling of Negation in Glob Pattern in Nx Plugin - createNodesV2
### Current Behavior

Reproduction repository: https://github.com/antoinepairet/nx-crystal-glob-pattern-issue

When a plugin includes a glob pattern with negation (e.g., !(*-e2e)), projects matching the negated pattern are removed from the project graph entirely. This issue occurs regardless of the actual logic of the plugin. Merely defining such a pattern is enough to trigger the problem.

````ts
import { CreateNodesV2 } from '@nx/devkit';

export const createNodesV2: CreateNodesV2 = [
  `apps/**/!(*-e2e)/project.json`,
  async () => {
    return [];
  },
];
````

`npx nx show projects -t e2e` will not show any project if the plugin is loaded.

- The issue occurs even if the plugin’s return value is empty (async () => { return []; }).
- Removing the negation from the glob pattern resolves the issue.
- Tested on both Nx `19.8.14` and `20.3.0`

### Expected Behavior

Projects should appear correctly in the output of `npx nx show projects -t e2e` when the plugin is loaded.

### GitHub Repo

https://github.com/antoinepairet/nx-crystal-glob-pattern-issue

### Steps to Reproduce

1. create a new workspace, `npx create-nx-workspace@latest react-monorepo-crystal-plugin-bug --preset=react-monorepo`
2. create a simple plugin with a glob pattern with a negation
3. load the plugin in `nx.json`
4. `npx nx show projects -t e2e` returns an empty list

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.18.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 8.19.2

nx                     : 20.3.0
@nx/js                 : 20.3.0
@nx/jest               : 20.3.0
@nx/eslint             : 20.3.0
@nx/workspace          : 20.3.0
@nx/devkit             : 20.3.0
@nx/eslint-plugin      : 20.3.0
@nx/module-federation  : 20.3.0
@nx/playwright         : 20.3.0
@nx/react              : 20.3.0
@nx/rspack             : 20.3.0
@nx/vite               : 20.3.0
@nx/web                : 20.3.0
@nx/webpack            : 20.3.0
typescript             : 5.6.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/playwright/plugin
@nx/jest/plugin
./plugin-with-bad-glob-pattern.ts
```

### Failure Logs

```shell

```

### Package Manager Version

_No response_

### Operating System

- [x] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Cammisuli**
## Current Behavior

Whenever there are multiple plugins using in a workspace, all the configuration paths are collected and used as 1 giant glob to test against the workspace context files. 

## Expected Behavior

Each plugin configuration glob is now handled separately and are not joined together into one giant one. This allows each glob pattern to have separate files for each plugin. 

## Related Issue(s)

Fixes #29473

### CODE REVIEW

File: packages/nx/src/project-graph/utils/retrieve-workspace-files.ts [hunk 1]
```diff
@@ -155,6 +156,9 @@ export function configurationGlobs(plugins: Array<LoadedNxPlugin>): string[] {
   for (const plugin of plugins) {
     if ('createNodes' in plugin && plugin.createNodes) {
       globPatterns.push(plugin.createNodes[0]);
+    } else {
+      // if there is no glob in the plugin, add an empty glob so that we can still map the globs by index to the plugin
+      globPatterns.push('');
```
Comment (Cammisuli) [inline packages/nx/src/project-graph/utils/retrieve-workspace-files.ts:161]: before going into here, we should filter out the plugins that do not have createNodes already. Since they are not going to be used for creating the project grap

**Review by FrozenPandaz — APPROVED** [review]

**Comment by antoinepairet** [comment]
Thank you @FrozenPandaz @Cammisuli and @AgentEnder 🙌🏻 🙇🏻
