### PR TITLE
fix(storybook): fix webpack5 check

### LINKED ISSUE #7640: Nrwl React Storybook Preset: Cannot read property 'includes' of undefined
## Current Behavior
Currently when following [this](https://nx.dev/l/r/storybook/migrate-webpack-final) to upgrade my Storybook configuration I get the following error after adding the new `@nrwl/react/plugins/storybook` preset to the addons:

```
It looks like you use Webpack 5 but your Storybook setup is not configured to leverage that
and thus falls back to Webpack 4.
Make sure you upgrade your Storybook config to use Webpack 5.

  - https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#upgrade


info => Loading presets
info => Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"
TypeError: Cannot read property 'includes' of undefined


          Broken build, fix the error above.
          You may need to refresh the browser.
```

It is also strange I am getting the warning about Webpack 4, since I have set the builder to Webpack 5 in each `main.js` file.

## Expected Behavior

It should load the preset properly and Storybook should run fine.

## Steps to Reproduce

https://github.com/amosbastian/boilerplate/tree/chore/nrwl-13

```
nx serve shared-storybook:storybook
```

### Environment

```
  Node : 14.16.1
  OS   : darwin x64
  npm  : 7.20.5

  nx : 13.1.3
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.3
  @nrwl/cypress : 13.1.3
  @nrwl/devkit : 13.1.3
  @nrwl/eslint-plugin-nx : 13.1.3
  @nrwl/express : 13.1.3
  @nrwl/jest : 13.1.3
  @nrwl/linter : 13.1.3
  @nrwl/nest : Not Found
  @nrwl/next : 13.1.3
  @nrwl/node : 13.1.3
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 13.1.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.3
  @nrwl/web : 13.1.3
  @nrwl/workspace : 13.1.3
  @nrwl/storybook : 13.1.3
  @nrwl/gatsby : Not Found
  typescript : 4.4.4
  ```

### PR DESCRIPTION
**Pull request by mandarini**
ISSUES CLOSED: #7640

Fixing the babel plugins check, and also the webpack5 check.
## Related Issue(s)

Fixes #7640

### CODE REVIEW

**Review by juristr — APPROVED** [review]

File: packages/storybook/src/executors/utils.ts [hunk 1]
```diff
@@ -108,7 +108,9 @@ function reactWebpack5Check(options: CommonNxStorybookConfig) {
       encoding: 'utf8',
     });
 
-    if (!storybookConfig.includes(`builder: 'webpack5'`)) {
+    if (
+      !storybookConfig.match(/builder: ('webpack5'|"webpack5"|`webpack5`)/g)
```
Comment (jaysoo) [inline packages/storybook/src/executors/utils.ts:112]: Could be `/builder: ['"`]webpack5['"`]/g` if you want to make it shorter.

**Review by jaysoo — APPROVED** [review]

File: packages/storybook/src/executors/utils.ts (hunk 1 above)
Comment (mandarini) [reply packages/storybook/src/executors/utils.ts:112]: Yes, I thought about that, but then `"webpack5'` would be valid :/
