### PR TITLE
fix(core): run-many doesn't strip quotes surrounding target names

### LINKED ISSUE #16203: run-many does not recognize targets with a colon
### Current Behavior

`run-many` does not recognize targets with a colon in the name, even when wrapped with escaped quotes like so:

```
% yarn nx run-many --target=\"build:prod\"
```

### Expected Behavior

`run-many` should recognize targets wrapped in double quotes.

### GitHub Repo

https://github.com/dlqqq/nx-colon-issue

### Steps to Reproduce

1. Run `nx run --target=build` and run `nx run --target=\"build:prod\"`.
2. Verify you see the following output:

```
% yarn nx run-many --target=build
yarn run v1.22.19
$ /workplace/dlq/nx-colon-issue/node_modules/.bin/nx run-many --target=build

    ✔  nx run test:build  [local cache]

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project test (61ms)

   Nx read the output from the cache instead of running the command for 1 out of 1 tasks.

Done in 0.34s.
(jai)
(23-04-10 17:54:53) <0> [/workplace/dlq/nx-colon-issue]
dev-dsk-dlq-2b-55651109 % yarn nx run-many --target=\"build:prod\"
yarn run v1.22.19
$ /workplace/dlq/nx-colon-issue/node_modules/.bin/nx run-many '--target="build:prod"'
 >  NX   Successfully ran target "build:prod" for 0 projects (5ms)

Done in 0.28s.
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : linux x64
   yarn : 1.22.19

   nx            : 15.9.2
   lerna         : 6.6.1
   @nrwl/cli     : 15.9.2
   @nrwl/devkit  : 15.9.2
   @nrwl/tao     : 15.9.2
   typescript    : 4.1.6
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
run-many doesn't strip quotes surrounding its targets, which can cause unexpected behavior

## Expected Behavior
run-many strips quotes

## Related Issue(s)

Fixes #16203

### CODE REVIEW

File: packages/nx/src/command-line/nx-commands.ts [hunk 1]
```diff
@@ -1093,7 +1093,10 @@ function parseCSV(args: string[] | string) {
   if (Array.isArray(args)) {
     return args;
   }
-  return args.split(',');
+  const items = args.split(',');
+  return items.map((i) =>
+    i.startsWith('"') && i.endsWith('"') ? i.slice(1, -1) : i
```
Comment (FrozenPandaz) [inline packages/nx/src/command-line/nx-commands.ts:1098]: Should we handle single quotes?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/nx/src/command-line/nx-commands.ts (hunk 1 above)
Comment (AgentEnder) [reply packages/nx/src/command-line/nx-commands.ts:1098]: Nope - double checked and we only handle double quotes for `nx run` as well - one could probably argue that this should change, but I digress. Lets fix this first, can attack single quotes more holistically later.

**Review by FrozenPandaz — APPROVED** [review]
