### PR TITLE
fix(core): run command is swallowing errors from angular builders

### LINKED ISSUE #8456: No build error logs with @angular-devkit/build-angular:ng-packagr
## Current Behavior
No build error logs are shown when building an angular library with @angular-devkit/build-angular:ng-packagr. The build error looks like the following no matter if the --verbose flag is passed or not.

Capture d’écran 2022-01-10 à 12 09 35

## Expected Behavior
The build error should display the error (location, error type, ...).

## Steps to Reproduce
Use this repo to reproduce the error: https://github.com/tmo207/nx-ng-build
The errors is produced here: https://github.com/tmo207/nx-ng-build/blob/master/libs/ng-lib/src/lib/ng-lib.module.ts

Run `nx build` and `nx build --verbose` to see the buggy behaviour.

### Environment
```
Node : 14.15.5
  OS   : darwin x64
  npm  : 7.13.0
  
  nx : 12.10.1
  @nrwl/angular : 12.10.1
  @nrwl/cli : 12.10.1
  @nrwl/cypress : 12.10.1
  @nrwl/devkit : 12.10.1
  @nrwl/eslint-plugin-nx : 12.10.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.1
  @nrwl/linter : 12.10.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.1
  @nrwl/storybook : 12.10.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

Currently, when we `nx run` a target with an Angular builder, we do not output any error logs that the Angular Devkit collects.

This happens because we map the output from the Executor to a status code of `0` or `1`.
We do this within a `handleErrors` function which should catch any thrown `Error` and print the log accordingly.

However, the Angular Devkit does not throw when it encounters an Error. Instead, it builds up an Error string in the `BuilderOutput`. 

As no Error is thrown, we do not print any logs. We do however map correctly to an erroring status code, so at the end of execution, we still tell the user that the command failed, we just don't inform them of why.

## Expected Behavior

We should handle scenarios from Angular Devkit where there is no Error thrown, and still print the error logs correctly.

## Additional Information
I do not like how I've solved this. It feels brittle and as though it is being handled in the incorrect place.
However, given the current structure of the `run` command, I cannot think of anywhere else to do it without drastically changing the command, which may have an unintended knock-on effect. 

## Related Issue(s)

Fixes #8456

### CODE REVIEW

**Comment by Coly010** [comment]
Looking at the ng-packagr builder I can see they use a catchError to collect the error and transform it to a new observable of an object.
catchError((err) => of({ success: false, error: err.message }))
In that case, I don't think we should even attempt to support it. It opens the possibility of too many divergences for each builder angular provides

File: packages/tao/src/commands/run.ts [hunk 1]
```diff
@@ -263,19 +263,32 @@ async function runExecutorInternal<T extends { success: boolean }>(
...
-        target,
-        configuration,
-        runOptions: combinedOptions,
-        executor: targetConfig.executor,
-      },
-      isVerbose
+    const observable = (
+      await (
+        await import('./ngcli-adapter')
+      ).scheduleTarget(
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/run.ts:272]: These changes can be moved into `scheduleTarget` itself.

File: packages/tao/src/commands/run.ts [hunk 2]
```diff
@@ -263,19 +263,32 @@ async function runExecutorInternal<T extends { success: boolean }>(
       );
     }
   } else {
+    let errors = [];
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/run.ts:266]: I think this can be undefined to begin. We don't need to collect any errors in an array. We only need to print the last error (if it's there).

File: packages/tao/src/commands/run.ts [hunk 3]
```diff
@@ -263,19 +263,32 @@ async function runExecutorInternal<T extends { success: boolean }>(
...
+          project,
+          target,
+          configuration,
+          runOptions: combinedOptions,
+          executor: targetConfig.executor,
+        },
+        isVerbose
+      )
+    ).pipe(
+      (await import('rxjs/operators')).tap(
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/run.ts:284]: Once you move this into `scheduleTarget`, you don't need the lazy import.

File: packages/tao/src/commands/run.ts [hunk 4]
```diff
@@ -263,19 +263,32 @@ async function runExecutorInternal<T extends { success: boolean }>(
...
+        ({ success, error }) => (!success && error ? errors.push(error) : 0),
+        (error) => (error.message ? errors.push(error.message) : 0),
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/run.ts:286]: I don't think we need an error handler at all here. Those will be handled properly already.

File: packages/tao/src/commands/run.ts [hunk 5]
```diff
@@ -263,19 +263,32 @@ async function runExecutorInternal<T extends { success: boolean }>(
...
+          target,
+          configuration,
+          runOptions: combinedOptions,
+          executor: targetConfig.executor,
+        },
+        isVerbose
+      )
+    ).pipe(
+      (await import('rxjs/operators')).tap(
+        ({ success, error }) => (!success && error ? errors.push(error) : 0),
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/run.ts:285]: This only needs to set the local variable to the `error` given that condition.

File: packages/tao/src/commands/run.ts [hunk 6]
```diff
@@ -263,19 +263,32 @@ async function runExecutorInternal<T extends { success: boolean }>(
...
+        (error) => (error.message ? errors.push(error.message) : 0),
+        () => {
+          logger.log(errors.join('\n'));
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/run.ts:288]: You don't need to `join` the errors.

Comment (FrozenPandaz) [inline packages/tao/src/commands/run.ts:288]: Use `logger.error` instead.

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/tao/src/commands/ngcli-adapter.ts [hunk 7]
```diff
@@ -74,7 +74,16 @@ export async function scheduleTarget(
...
   );
 
-  return run.output;
+  let lastOutputError: string;
+  return run.output.pipe(
+    tap(
+      (output) => (lastOutputError = output.error),
+      (error) => 0, // do nothing, this could be an intentional error
+      () => {
+        lastOutputError ? nxLogger.error(lastOutputError) : 0;
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/ngcli-adapter.ts:83]: You can use the `logger` in this function right?

File: packages/tao/src/commands/ngcli-adapter.ts [hunk 8]
```diff
@@ -74,7 +74,16 @@ export async function scheduleTarget(
     { logger }
   );
 
-  return run.output;
+  let lastOutputError: string;
+  return run.output.pipe(
+    tap(
+      (output) => (lastOutputError = output.error),
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/ngcli-adapter.ts:80]: It should only = `output.error` if `output.success` is falsy.

File: packages/tao/src/commands/ngcli-adapter.ts [hunk 9]
```diff
@@ -74,7 +74,16 @@ export async function scheduleTarget(
...
+      (error) => 0, // do nothing, this could be an intentional error
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/ngcli-adapter.ts:81]: This could be a true `noop`. `() => {}`

File: packages/tao/src/commands/ngcli-adapter.ts [hunk 10]
```diff
@@ -29,10 +29,10 @@ import {
 } from '../shared/workspace';
 import { dirname, extname, resolve, join, basename } from 'path';
 import { FileBuffer } from '@angular-devkit/core/src/virtual-fs/host/interface';
-import type { Architect } from '@angular-devkit/architect';
+import type { Architect, BuilderOutput } from '@angular-devkit/architect';
 import { Observable, of, merge, forkJoin, NEVER, from } from 'rxjs';
-import { catchError, map, switchMap, toArray } from 'rxjs/operators';
-import { NX_ERROR, NX_PREFIX } from '../shared/logger';
+import { catchError, map, switchMap, toArray, tap } from 'rxjs/operators';
+import { NX_ERROR, NX_PREFIX, logger as nxLogger } from '../shared/logger';
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/ngcli-adapter.ts:35]: No need to import this logger.

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
