### PR TITLE
fix(release): replace local dependency protocols of unchanged dependencies #30995

### LINKED ISSUE #30995: versioning bug - file refs for dependencies not updated - npm
### Current Behavior

Setup:
An Nx repo using npm, conventional commits, projectRelationship is independent, preserveLocalDependencyProtocols is false, built to a dist folder

Has projects A, B and C where A depends on B and B depends on C using file references

Make a patch change to project A and commit. No changes have been made to B and C since the last git tags for these projects were committed

Run `nx release version`

The version in package.json of project A is changed correctly, but the version of it's dependency on project B is left as a file reference.

### Expected Behavior

The version of the dependency on project B is updated to the current version based on the latest git-tag for project B

### GitHub Repo

https://github.com/brogueady/nx-test

### Steps to Reproduce

1. npm install
2. nx release version

### Nx Report

```shell
Node           : 22.12.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.0

nx                 : 20.8.1
@nx/js             : 20.8.1
@nx/eslint         : 20.8.1
@nx/workspace      : 20.8.1
@nx/devkit         : 20.8.1
@nx/eslint-plugin  : 20.8.1
typescript         : 5.7.3
```

### Failure Logs

```shell
UPDATE dist/packages/wp-renovate-mono-lib-a/package.json

    "name": "@at/wp-renovate-mono-lib-a",
-   "version": "5.3.13",
+   "version": "5.5.0",
    "dependencies": {

  }
+
```

### Package Manager Version

_No response_

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I have also tried using the new versioning code (i.e. setting "useLegacyVersioning": false) which has the same issue

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior
When independent versioning with conventional commits, and only one project in a release group needs bumped, but it depends on another project via local dependency protocols such as `file://` or `workspace:` protocol, the local protocol dependency is not replaced.

## Expected Behavior
local protocol is replaced with the current version of the dependency.

## Related Issue(s)

Fixes #30995

### CODE REVIEW

File: packages/nx/src/command-line/release/version/release-group-processor.ts [hunk 1]
```diff
@@ -22,6 +22,7 @@ import {
   SemverBumpType,
   VersionActions,
 } from './version-actions';
+import { resolveCurrentVersion } from './resolve-current-version';
```
Comment (JamesHenry) [inline packages/nx/src/command-line/release/version/release-group-processor.ts]: Unused

File: packages/nx/src/command-line/release/version/release-group-processor.ts [hunk 2]
```diff
@@ -790,11 +788,18 @@ export class ReleaseGroupProcessor {
...
+          let newVersion: string;
+          if (targetVersionData.newVersion === null) {
+            newVersion =
+              this.releaseGraph.cachedCurrentVersions.get(dep.target) ||
+              currentDependencyVersion;
+          } else {
+            newVersion =
+              targetVersionData.newVersion || currentDependencyVersion;
+          }
+
```
Comment (JamesHenry) [inline packages/nx/src/command-line/release/version/release-group-processor.ts]: I think we can simplify this:

```
const newVersion = 
  targetVersionData.newVersion ?? 
  this.releaseGraph.cachedCurrentVersions.get(dep.target) ?? 
  currentDependencyVersion;
```

Comment (Coly010) [reply packages/nx/src/command-line/release/version/release-group-processor.ts]: yes we can

**Review by JamesHenry — APPROVED** [review]
