### PR TITLE
fix(testing): use es2016 for jest-preset-angular projects

### LINKED ISSUE #15577: 'ProxyZone' not found after migration from 15.1.1 to 15.8.5
### Current Behavior

After running the migration to 15.8.5, a lot of our unit tests are failing with the error message: "Expected to be running in 'ProxyZone', but it was not found." It points to the loader function on TestbedHarnessEnvironment, but looking into it, the issue seems to be tied to @testing-library/angular. It seemed best to file the issue here since there are multiple libraries are involved.

There are two tests in the demo repo below to illustrate the problem. The test were run with two versions of @testing-library/angular: 10.11.0 and 13.3.0 (current latest).

### Expected Behavior

We expected our tests to continue to pass without error.

### GitHub Repo

https://github.com/smithpb/proxyzone-error

### Steps to Reproduce

1. running `nx test test-app` will return the error we've seen

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.14.0
   OS   : darwin x64
   npm  : 9.3.1
   
   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/angular           : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/cypress           : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/webpack           : 15.8.5
   @nrwl/nx-cloud          : 15.1.1
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @testing-library/angular : 13.3.0
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by barbados-clemens**
## Current Behavior

jest preset angular v13 projects failing when testing async behavior

## Expected Behavior

jest preset angular v13 projects work like they did in v12

## Related Issue(s)

Fixes #15577

### CODE REVIEW

File: packages/angular/src/migrations/update-15-9-0/update-testing-tsconfig.ts [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+        'tsconfig.spec.json'
+      );
+
+      if (tree.exists(tsconfigPath)) {
+        updateJson<TsConfig>(
+          tree,
+          tsconfigPath,
+          (json) => {
+            json.compilerOptions ??= {};
+            json.compilerOptions.target ??= 'es2016';
```
Comment (Coly010) [inline packages/angular/src/migrations/update-15-9-0/update-testing-tsconfig.ts:35]: Is there a reason we're using es2016 and not es2022 which Angular apps were migrated to in Version 15?

Comment (barbados-clemens) [reply packages/angular/src/migrations/update-15-9-0/update-testing-tsconfig.ts:35]: > Angular doesn't support native async/await in testing with target higher than ES2016, see https://github.com/angular/components/issues/21632#issuecomment-764975917

https://github.com/thymikee/jest-preset-angular#migration-from-angular--13

**Review by Coly010 — APPROVED** [review]

File: packages/angular/src/migrations/update-15-9-0/update-testing-tsconfig.ts
Comment (FrozenPandaz) [inline packages/angular/src/migrations/update-15-9-0/update-testing-tsconfig.ts:1]: Don't we need to include this file in the `migrations.json`?

Comment (barbados-clemens) [reply packages/angular/src/migrations/update-15-9-0/update-testing-tsconfig.ts:1]: 🤦 updated.

**Review by FrozenPandaz — APPROVED** [review]
