### PR TITLE
fix(core): addPlugin should not conflict on project.json targets

### LINKED ISSUE #22476: Angular Dynamic Module Federation SSR error after add @nx/nest
### Current Behavior

I created a project then added an angular app using dynamic remote module federation with ssr. The target serve, serve ssr (including adding devRemotes) work well with angular host app

But after I tried to add an app using nestjs. The target serve, serve ssr (including devRemotes) of the angular host app cannot load remote modules

### Expected Behavior

It should have worked fine like before I added nestjs app

### GitHub Repo

_No response_

### Steps to Reproduce

The first i have create project with bellow steps
```sh
npx create-nx-workspace --name=project --preset=apps --nxCloud=skip --packageManager=pnpm && cd project 
npx nx add @nx/angular
npx nx g @nx/angular:host apps/host --dynamic --ssr --standalone --style=scss --addTailwind --e2eTestRunner=playwright --projectNameAndRootFormat=as-provided --prefix=host
npx nx g @nx/angular:remote apps/remote-a --host=host --ssr --standalone --style=scss --addTailwind --e2eTestRunner=playwright --projectNameAndRootFormat=as-provided --prefix=remote-a
npx nx g @nx/angular:remote apps/remote-b --host=host --ssr --standalone --style=scss --addTailwind --e2eTestRunner=playwright --projectNameAndRootFormat=as-provided --prefix=remote-b
npx nx serve host --devRemotes=remote-a,remote-b
```

For now it's still work as expected. But after add @nx/nest it's ocure error

``` sh
npx nx add @nx/nest
npx nx g @nx/nest:application server/gateways/api-gateway  --projectNameAndRootFormat=as-provided 
npx nx serve host --devRemotes=remote-a,remote-b
```

Here is browser console log error
Capture

### Nx Report

```shell
Node   : 20.11.1
OS     : linux-x64
pnpm   : 8.15.5

nx (global)        : 18.1.2
nx                 : 18.1.2
@nx/js             : 18.1.2
@nx/jest           : 18.1.2
@nx/eslint         : 18.1.2
@nx/workspace      : 18.1.2
@nx/angular        : 18.1.2
@nx/devkit         : 18.1.2
@nx/eslint-plugin  : 18.1.2
@nx/nest           : 18.1.2
@nx/node           : 18.1.2
@nx/playwright     : 18.1.2
@nx/web            : 18.1.2
@nx/webpack        : 18.1.2
typescript         : 5.3.3
```

### Failure Logs

_No response_

### Package Manager Version

pnpm 8.15.5

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

Calculating conflicts in target names does not consider if the project.json defined targets will actually be impacted by the plugin that wants to be added creating false negatives

## Expected Behavior

Calculating conflicts should be more accurate

## Related Issue(s)

Fixes #22476

### CODE REVIEW

File: packages/devkit/src/utils/add-plugin.ts [hunk 1]
```diff
@@ -71,27 +86,42 @@ export async function addPlugin<PluginOptions>(
...
+              corePluginsCreatedTarget,
+              projConfig.targets[targetName]
+            ) &&
+            !deepEquals(
+              corePluginsCreatedTarget,
+              mergeTargetConfigurations(
+                corePluginsCreatedTarget,
+                projConfig.targets[targetName]
+              )
+            ))
```
Comment (AgentEnder) [inline packages/devkit/src/utils/add-plugin.ts:123]: You don't have to check isCompatible separately from the deep equals imho

```suggestion
          (corePluginsCreatedTarget &&
            !deepEquals(
              corePluginsCreatedTarget,
              mergeTargetConfigurations(
                corePluginsCreatedTarget,
                projConfig.targets[targetName]
              )
            )
```

File: packages/nx/src/internal-testing-utils/mock-load-nx-plugin.ts [hunk 2]
```diff
@@ -0,0 +1,14 @@
+jest.mock('nx/src/project-graph/plugins/loader', () => ({
+  ...jest.requireActual('nx/src/project-graph/plugins/loader'),
+  loadNxPlugin: jest.fn().mockImplementation(() => {
+    return [
+      Promise.resolve({
+        createNodes: ['', () => {}],
+        createDependencies: () => [],
+        include: [],
+        exclude: [],
```
Comment (AgentEnder) [inline packages/nx/src/internal-testing-utils/mock-load-nx-plugin.ts:9]: These are all optional fields right? We could just have this return an empty object.

File: packages/nx/src/project-graph/plugins/internal-api.ts [hunk 3]
```diff
@@ -107,8 +108,9 @@ export async function loadNxPlugins(
       ? loadNxPluginInIsolation
       : loadNxPlugin;
 
-  plugins = await normalizePlugins(plugins, root);
-
+  if (!skipDefaultPlugins) {
+    plugins = await normalizePlugins(plugins, root);
+  }
```
Comment (AgentEnder) [inline packages/nx/src/project-graph/plugins/internal-api.ts:113]: We still need to normalize to an empty array at minimum, that could either be done in a ternary here or by passing the flag through to normalize plugins, either way.
```suggestion
    plugins =  skipDefaultPlugins ? (plugins ?? []) : await normalizePlugins(plugins, root);
```

File: packages/nx/src/project-graph/utils/retrieve-workspace-files.ts [hunk 4]
```diff
@@ -76,6 +77,29 @@ export function retrieveProjectConfigurations(
...
+    // Errors are okay for this because we're only running 1 plugin
+    if (e instanceof ProjectConfigurationsError) {
+      projConfigs = e.partialProjectConfigurationsResult;
+    } else {
+      throw e;
+    }
+  }
+  return projConfigs;
+}
+
```
Comment (AgentEnder) [inline packages/nx/src/project-graph/utils/retrieve-workspace-files.ts:102]: Can we keep this in add-plugin, or a similar file next to it in devkit? We shouldn't be using this inside `nx`, so I don't want to put it here.

**Review by AgentEnder — CHANGES_REQUESTED** [review]

**Review by AgentEnder — APPROVED** [review]

**Review by jaysoo — APPROVED** [review]
