### PR TITLE
fix(vite): ensure cache is created correctly for separate vite and vitest config files #22244

### LINKED ISSUE #22244: Available tasks for a project missing after vite.config.ts
### Current Behavior

Available tasks for a fresh react app installed in a monorepo are only `lint` after editing `./apps/react-monorepo/vite.config.ts`

### Expected Behavior

They should be: `build`, `serve`, `preview`, `serve-static`, `test` and `lint`

### GitHub Repo

_No response_

### Steps to Reproduce

1. `npx create-nx-workspace@latest react-monorepo --preset=react-monorepo`
2. choose the following
```
✔ Application name · react-monorepo
✔ Which bundler would you like to use? · vite
✔ Test runner to use for end to end (E2E) tests · cypress
✔ Default stylesheet format · css
✔ Do you want Nx Cloud to make your CI fast? · github
```
3. `nx show project react-monorepo` give the following:
```
{"root":"apps/react-monorepo","targets":{"build":{"options":{"cwd":"apps/react-monorepo","command":"vite build"},"cache":true,"dependsOn":["^build"],"inputs":["production","^production",{"externalDependencies":["vite"]}],"outputs":["{workspaceRoot}/dist/apps/react-monorepo"],"executor":"nx:run-commands","configurations":{}},"serve":{"options":{"cwd":"apps/react-monorepo","command":"vite serve"},"executor":"nx:run-commands","configurations":{}},"preview":{"options":{"cwd":"apps/react-monorepo","command":"vite preview"},"executor":"nx:run-commands","configurations":{}},"serve-static":{"executor":"@nx/web:file-server","options":{"buildTarget":"build"},"configurations":{}},"test":{"options":{"cwd":"apps/react-monorepo","command":"vitest run"},"cache":true,"inputs":["default","^production",{"externalDependencies":["vitest"]}],"outputs":["{workspaceRoot}/coverage/apps/react-monorepo"],"executor":"nx:run-commands","configurations":{}},"lint":{"cache":true,"options":{"cwd":"apps/react-monorepo","command":"eslint ."},"inputs":["default","{workspaceRoot}/.eslintrc.json","{workspaceRoot}/apps/react-monorepo/.eslintrc.json","{workspaceRoot}/tools/eslint-rules/**/*",{"externalDependencies":["eslint"]}],"executor":"nx:run-commands","configurations":{}}},"name":"react-monorepo","$schema":"../../node_modules/nx/schemas/project-schema.json","sourceRoot":"apps/react-monorepo/src","projectType":"application","tags":[],"implicitDependencies":[]}
```
4. edit `./apps/react-monorepo/vite.config.ts`
```
-   outDir: '../../dist/apps/react-monorepo',
+   outDir: './build/react-store',
```
5. save
6. `nx show project react-monorepo` gives:
```
{"root":"apps/react-monorepo","targets":{"lint":{"cache":true,"options":{"cwd":"apps/react-monorepo","command":"eslint ."},"inputs":["default","{workspaceRoot}/.eslintrc.json","{workspaceRoot}/apps/react-monorepo/.eslintrc.json","{workspaceRoot}/tools/eslint-rules/**/*",{"externalDependencies":["eslint"]}],"executor":"nx:run-commands","configurations":{}}},"name":"react-monorepo","$schema":"../../node_modules/nx/schemas/project-schema.json","sourceRoot":"apps/react-monorepo/src","projectType":"application","tags":[],"implicitDependencies":[]}
```

### Nx Report

```shell
Node   : 18.13.0
OS     : linux-x64
npm    : 9.2.0

nx (global)        : 18.0.7
nx                 : 18.0.7
@nx/js             : 18.0.7
@nx/linter         : 18.0.7
@nx/eslint         : 18.0.7
@nx/workspace      : 18.0.7
@nx/cypress        : 18.0.7
@nx/devkit         : 18.0.7
@nx/eslint-plugin  : 18.0.7
@nx/react          : 18.0.7
@nrwl/tao          : 18.0.7
@nx/vite           : 18.0.7
@nx/web            : 18.0.7
typescript         : 5.3.3
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

However, if we delete `nx` cache: `rm -r .nx/cache`, the correct target list is seen.

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

When both a Vite config file and Vitest config file exist for a single project, the hash that is calculated when creating the targets is the same, and therefore one operation overwrites the other.
This leads to invalid store of targets available for the project.

## Expected Behavior

Both sets of targets should produce a different hash allowing for a separate cache for each which gets merged correctly when targets are inferred.

## Related Issue(s)

Fixes #22244

### CODE REVIEW

**Review by jaysoo — APPROVED** [review]

File: packages/vite/src/plugins/plugin.ts [hunk 1]
```diff
@@ -66,9 +66,10 @@ export const createNodes: CreateNodes<VitePluginOptions> = [
 
     options = normalizeOptions(options);
 
-    const hash = calculateHashForCreateNodes(projectRoot, options, context, [
-      getLockFileName(detectPackageManager(context.workspaceRoot)),
-    ]);
+    const hash =
+      calculateHashForCreateNodes(projectRoot, options, context, [
+        getLockFileName(detectPackageManager(context.workspaceRoot)),
+      ]) + configFilePath;
```
Comment (jaysoo) [inline packages/vite/src/plugins/plugin.ts:72]: Rather than appending the config file, can we include them in the `additionalGlobs` array or `options` object to be hashed?

Comment (Coly010) [reply packages/vite/src/plugins/plugin.ts:72]: I asked @AgentEnder about this and he felt it was better to append the configFilePath

Comment (Coly010) [reply packages/vite/src/plugins/plugin.ts:72]: Will add a comment about this
