### PR TITLE
fix(core): use fork to execute nx generate workspace:preset

### LINKED ISSUE #20222: Nx angular create workspace is not working with pnpm and yarn (only npm works)
### Current Behavior

i am getting the same issue with nx angular workspace setup, i was simply trying to create a test app with [getting-started](https://nx.dev/getting-started/why-nx) documentation. this happened with whenever i tried to use `pnpm` & `yarn` (only npm succeeded), my node version in v18.17.1.

### Expected Behavior

must succeed with yarn and pnpm similar to npm using 
`npx create-nx-workspace --pm yarn` or `npx create-nx-workspace --pm pnpm`

### GitHub Repo

_No response_

### Steps to Reproduce

1. npx create-nx-workspace --pm yarn or npx create-nx-workspace --pm pnpm and follow getting started of nx documentation.
select monorepo with prompts as they come with following options:

 npx create-nx-workspace@latest org1 --pm yarn

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

√ Which stack do you want to use? · angular
√ Integrated monorepo, or standalone project? · integrated
√ Application name · shell
√ Which bundler would you like to use? · webpack
√ Default stylesheet format · scss
√ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
√ Test runner to use for end to end (E2E) tests · playwright
√ Enable distributed caching to make your CI faster · No

### Nx Report

```shell
nx report

 >  NX   Could not find Nx modules in this workspace.

   Have you run npm/yarn install?
```

### Failure Logs

```shell
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 3, reused 3, downloaded 0, added 0
Progress: resolved 4, reused 4, downloaded 0, added 0
Progress: resolved 37, reused 13, downloaded 0, added 0
Progress: resolved 147, reused 138, downloaded 0, added 0
Progress: resolved 156, reused 147, downloaded 0, added 0
Progress: resolved 157, reused 147, downloaded 0, added 0
Progress: resolved 200, reused 147, downloaded 0, added 0
Progress: resolved 207, reused 147, downloaded 0, added 0
Progress: resolved 208, reused 147, downloaded 0, added 0
Progress: resolved 284, reused 275, downloaded 0, added 0
Progress: resolved 375, reused 349, downloaded 0, added 0
Progress: resolved 468, reused 450, downloaded 0, added 0
Progress: resolved 591, reused 562, downloaded 0, added 0
Progress: resolved 715, reused 703, downloaded 0, added 0
Progress: resolved 846, reused 776, downloaded 0, added 0
Progress: resolved 862, reused 776, downloaded 0, added 0
Progress: resolved 863, reused 776, downloaded 0, added 0
Progress: resolved 863, reused 777, downloaded 0, added 0
Progress: resolved 892, reused 882, downloaded 0, added 0
Progress: resolved 894, reused 884, downloaded 0, added 0
Progress: resolved 895, reused 884, downloaded 0, added 0
Progress: resolved 1056, reused 1003, downloaded 0, added 0
Progress: resolved 1079, reused 1026, downloaded 0, added 0
Progress: resolved 1097, reused 1044, downloaded 0, added 0
Progress: resolved 1098, reused 1045, downloaded 0, added 0
Progress: resolved 1100, reused 1047, downloaded 0, added 0
Packages: +1132
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1103, reused 1049, downloaded 0, added 0
Progress: resolved 1103, reused 1050, downloaded 0, added 0
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: E:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1103, reused 1050, downloaded 0, added 29
Progress: resolved 1103, reused 1050, downloaded 0, added 49
Progress: resolved 1103, reused 1050, downloaded 0, added 56
Progress: resolved 1103, reused 1050, downloaded 0, added 72
Progress: resolved 1103, reused 1050, downloaded 0, added 73
Progress: resolved 1103, reused 1050, downloaded 0, added 127
Progress: resolved 1103, reused 1050, downloaded 0, added 131
Progress: resolved 1103, reused 1050, downloaded 0, added 132
Progress: resolved 1103, reused 1050, downloaded 0, added 147
Progress: resolved 1103, reused 1050, downloaded 0, added 243
Progress: resolved 1103, reused 1050, downloaded 0, added 247
Progress: resolved 1103, reused 1050, downloaded 0, added 248
Progress: resolved 1103, reused 1050, downloaded 0, added 274
Progress: resolved 1103, reused 1050, downloaded 0, added 384
Progress: resolved 1103, reused 1050, downloaded 0, added 385
Progress: resolved 1103, reused 1050, downloaded 0, added 564
Progress: resolved 1103, reused 1050, downloaded 0, added 569
Progress: resolved 1103, reused 1050, downloaded 0, added 570
Progress: resolved 1103, reused 1050, downloaded 0, added 719
Progress: resolved 1103, reused 1050, downloaded 0, added 743
Progress: resolved 1103, reused 1050, downloaded 0, added 744
Progress: resolved 1103, reused 1050, downloaded 0, added 828
Progress: resolved 1103, reused 1050, downloaded 0, added 906
Progress: resolved 1103, reused 1050, downloaded 0, added 1018
Progress: resolved 1103, reused 1050, downloaded 0, added 1019
Progress: resolved 1103, reused 1050, downloaded 0, added 1042
Progress: resolved 1103, reused 1050, downloaded 0, added 1046
Progress: resolved 1103, reused 1050, downloaded 0, added 1052
Progress: resolved 1103, reused 1050, downloaded 0, added 1054
Progress: resolved 1103, reused 1050, downloaded 0, added 1055
Progress: resolved 1103, reused 1050, downloaded 0, added 1062
Progress: resolved 1103, reused 1050, downloaded 0, added 1064
Progress: resolved 1103, reused 1050, downloaded 0, added 1065
Progress: resolved 1103, reused 1050, downloaded 0, added 1068
Progress: resolved 1103, reused 1050, downloaded 0, added 1069
Progress: resolved 1103, reused 1050, downloaded 0, added 1075
Progress: resolved 1103, reused 1050, downloaded 0, added 1076
Progress: resolved 1103, reused 1050, downloaded 0, added 1082
Progress: resolved 1103, reused 1050, downloaded 0, added 1083
Progress: resolved 1103, reused 1050, downloaded 0, added 1095
Progress: resolved 1103, reused 1050, downloaded 0, added 1099
Progress: resolved 1103, reused 1050, downloaded 0, added 1128
Progress: resolved 1103, reused 1050, downloaded 0, added 1129
Progress: resolved 1103, reused 1050, downloaded 0, added 1132, done
.../esbuild@0.18.20/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.19.5/node_modules/esbuild postinstall$ node install.js
.../.pnpm/nx@17.1.1/node_modules/nx postinstall$ node ./bin/post-install
.../esbuild@0.19.5/node_modules/esbuild postinstall: Done
.../esbuild@0.18.20/node_modules/esbuild postinstall: Done
.../.pnpm/nx@17.1.1/node_modules/nx postinstall: Done

dependencies:
+ @nx/angular 17.1.1

devDependencies:
+ @angular-devkit/core 17.0.0
+ @nx/workspace 17.1.1
+ nx 17.1.1
+ typescript 5.2.2

Done in 2m 18.5s

>  NX  Generating @nx/workspace:preset

Fetching prettier...
Fetching @nx/playwright...
UPDATE nx.json
CREATE tsconfig.base.json
CREATE .prettierrc
CREATE .prettierignore
UPDATE .vscode/extensions.json
UPDATE package.json
CREATE jest.preset.js
CREATE jest.config.ts
UPDATE .gitignore
CREATE apps/shell/project.json
CREATE apps/shell/src/assets/.gitkeep
CREATE apps/shell/src/favicon.ico
CREATE apps/shell/src/index.html
CREATE apps/shell/src/styles.scss
CREATE apps/shell/tsconfig.app.json
CREATE apps/shell/tsconfig.editor.json
CREATE apps/shell/tsconfig.json
CREATE apps/shell/src/app/app.component.html
CREATE apps/shell/src/app/app.component.spec.ts
CREATE apps/shell/src/app/app.component.ts
CREATE apps/shell/src/app/app.component.scss
CREATE apps/shell/src/app/app.config.ts
CREATE apps/shell/src/app/app.routes.ts
CREATE apps/shell/src/app/nx-welcome.component.ts
CREATE apps/shell/src/main.ts
CREATE .eslintrc.json
CREATE .eslintignore
CREATE apps/shell/.eslintrc.json
CREATE apps/shell/jest.config.ts
CREATE apps/shell/src/test-setup.ts
CREATE apps/shell/tsconfig.spec.json
CREATE apps/shell-e2e/project.json
CREATE apps/shell-e2e/playwright.config.ts
CREATE apps/shell-e2e/src/example.spec.ts
CREATE apps/shell-e2e/.eslintrc.json
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 26, reused 24, downloaded 0, added 0
Progress: resolved 43, reused 43, downloaded 0, added 0
Progress: resolved 45, reused 45, downloaded 0, added 0
Progress: resolved 47, reused 47, downloaded 0, added 0
Progress: resolved 182, reused 181, downloaded 0, added 0
Progress: resolved 232, reused 222, downloaded 0, added 0
Progress: resolved 289, reused 267, downloaded 0, added 0
Progress: resolved 396, reused 330, downloaded 0, added 0
Progress: resolved 519, reused 398, downloaded 0, added 0
Progress: resolved 632, reused 437, downloaded 0, added 0
Progress: resolved 687, reused 511, downloaded 0, added 0
Progress: resolved 760, reused 706, downloaded 0, added 0
Progress: resolved 878, reused 834, downloaded 0, added 0
Progress: resolved 1012, reused 949, downloaded 0, added 0
Progress: resolved 1094, reused 1030, downloaded 0, added 0
Progress: resolved 1181, reused 1118, downloaded 0, added 0
Progress: resolved 1252, reused 1189, downloaded 0, added 0
Progress: resolved 1270, reused 1207, downloaded 0, added 0
Progress: resolved 1288, reused 1225, downloaded 0, added 0
Progress: resolved 1289, reused 1225, downloaded 0, added 0
Packages: +214 -32
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------
Progress: resolved 1289, reused 1226, downloaded 0, added 0
Progress: resolved 1289, reused 1226, downloaded 0, added 17
Progress: resolved 1289, reused 1226, downloaded 0, added 23
Progress: resolved 1289, reused 1226, downloaded 0, added 35
Progress: resolved 1289, reused 1226, downloaded 0, added 43
Progress: resolved 1289, reused 1226, downloaded 0, added 53
Progress: resolved 1289, reused 1226, downloaded 0, added 54
Progress: resolved 1289, reused 1226, downloaded 0, added 55
Progress: resolved 1289, reused 1226, downloaded 0, added 62
Progress: resolved 1289, reused 1226, downloaded 0, added 63
Progress: resolved 1289, reused 1226, downloaded 0, added 199
Progress: resolved 1289, reused 1226, downloaded 0, added 205
Progress: resolved 1289, reused 1226, downloaded 0, added 209
Progress: resolved 1289, reused 1226, downloaded 0, added 210
Progress: resolved 1289, reused 1226, downloaded 0, added 211
Progress: resolved 1289, reused 1226, downloaded 0, added 214, done
.../node_modules/nx postinstall$ node ./bin/post-install
.../node_modules/nx postinstall: Done

dependencies:
+ @angular/animations 17.0.2
+ @angular/common 17.0.2
+ @angular/compiler 17.0.2
+ @angular/core 17.0.2
+ @angular/forms 17.0.2
+ @angular/platform-browser 17.0.2
+ @angular/platform-browser-dynamic 17.0.2
+ @angular/router 17.0.2
+ rxjs 7.8.1
+ tslib 2.6.2
+ zone.js 0.14.2

devDependencies:
+ @angular-devkit/build-angular 17.0.0
+ @angular-devkit/schematics 17.0.0
+ @angular-eslint/eslint-plugin 17.0.1
+ @angular-eslint/eslint-plugin-template 17.0.1
+ @angular-eslint/template-parser 17.0.1
+ @angular/cli 17.0.0
+ @angular/compiler-cli 17.0.2
+ @angular/language-service 17.0.2
+ @nx/devkit 17.1.1
+ @nx/eslint 17.1.1
+ @nx/eslint-plugin 17.1.1
+ @nx/jest 17.1.1
+ @nx/js 17.1.1
+ @nx/playwright 17.1.1
+ @playwright/test 1.39.0
+ @schematics/angular 17.0.0
+ @swc-node/register 1.6.8
+ @swc/core 1.3.96
+ @types/jest 29.5.8
+ @types/node 16.11.7 (20.9.0 is available)
+ @typescript-eslint/eslint-plugin 6.10.0
+ @typescript-eslint/parser 6.10.0
+ eslint 8.46.0 (8.53.0 is available)
+ eslint-config-prettier 9.0.0
+ eslint-plugin-playwright 0.15.3 (0.18.0 is available)
+ jest 29.7.0
+ jest-environment-jsdom 29.7.0
+ jest-preset-angular 13.1.4
+ jsonc-eslint-parser 2.4.0
+ prettier 2.8.8 (3.0.3 is available)
+ ts-jest 29.1.1
+ ts-node 10.9.1

Done in 56.8s

>  NX  Generating @nx/workspace:preset


 >  NX   Cannot create a new project shell at apps/shell. It already exists.

   Pass --verbose to see the stacktrace.


 >  NX   Workspace creation failed, see above.


Error: Workspace creation failed, see above.
    at ChildProcess.<anonymous> (C:\Users\Alok\AppData\Local\Temp\tmp-43728-RTv9gWiHItzm\node_modules\.pnpm\@nx+workspace@17.1.1\node_modules\@nx\workspace\src\generators\new\generate-preset.js:38:24)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

### Package Manager Version

1.22.19 yarn 7.30.0 pnpm 8.15.0 npm

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### LINKED ISSUE #20270: create-nx-workspace stuck in "Creating your workspace" step
### Current Behavior

```
❯ npx create-nx-workspace@latest testwslatest
Need to install the following packages:
  create-nx-workspace@17.1.2
Ok to proceed? (y)

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Which stack do you want to use? · angular
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · testwslatest
✔ Which bundler would you like to use? · webpack
✔ Default stylesheet format · css
✔ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · Yes
✔ Test runner to use for end to end (E2E) tests · cypress
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v17.1.2 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
⠸ Creating your workspace in testwslatest
```

Stuck in this state, no progress.

Is there some way to get more logs?

### Expected Behavior

Should finish creating the workspace.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Run  npx create-nx-workspace@latest testwslatest
2. Tested with those options:
✔ Which stack do you want to use? · angular
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · testwslatest
✔ Which bundler would you like to use? · webpack
✔ Default stylesheet format · css
✔ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · Yes
✔ Test runner to use for end to end (E2E) tests · cypress
✔ Enable distributed caching to make your CI faster · No

But also failed with 17.0.2 and 17.0.3 and with other options (e.g. NestJs app, even with type "None")

### Nx Report

```shell
Nx workspace not created, yet.
```

### Failure Logs

```shell
There are no logs.
```

### Package Manager Version

npm 9.5.1

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [X] Other (Please specify)

### Additional Information

Operating System: WSL2 under Windows

### LINKED ISSUE #21742: Error: 'les' is not recognized as an internal or external command, operable program or batch file.
### Current Behavior

When I run this command on windows command prompt : 
`npx create-nx-workspace --pm pnpm`

it's giving me this error : 
` NX   Failed to create a workspace.

   Error: 'les' is not recognized as an internal or external command,
operable program or batch file.

I try also the second time now the error is : 

` NX   Failed to create a workspace.

   Error: 'odules' is not recognized as an internal or external command,
operable program or batch file.`

I'm using pnpm version 8.15.1, nodejs version 20.11.0 and windows 11 without wsl

maybe there is something broken command or text in the windows environment ?
Screenshot 2024-02-09 135210

### Expected Behavior

it suppose to generate the workspace successfully

### GitHub Repo

_No response_

### Steps to Reproduce

1.
`npx create-nx-workspace --pm pnpm`

### Nx Report

```shell
>  NX   Failed to create a workspace.

   Error: 'les' is not recognized as an internal or external command,
operable program or batch file.
```

### Failure Logs

```shell
>  NX   Failed to create a workspace.

   Error: 'les' is not recognized as an internal or external command,
operable program or batch file.
```

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### LINKED ISSUE #22312: create-nx-workspace fails creating the react-native preset when using pnpm
### Current Behavior

**OS:** Windows 11 / Ubuntu 20.04.4 LTS
**pnpm**: 8.15.4

Using this command `pnpx create-nx-workspace pnpm-nrwl --preset=react-native --appName=mobile --nxCloud=skip`
I eventually get a `Failed to create a workspace error`.

When looking at the error log, this is the command that fails

`NX   Command failed: pnpm add -D @nx/detox@18.0.8`

I've opened the workspace folder and attempted to install the dependency manually, but it fails with the following error

```
Progress: resolved 774, reused 765, downloaded 0, added 68, done
node_modules/.pnpm/detox@20.19.1/node_modules/detox: Running postinstall script, failed in 71ms
.../detox@20.19.1/node_modules/detox postinstall$ node scripts/postinstall.js
│ node:internal/modules/cjs/loader:1080
│   throw err;
│   ^
│ Error: Cannot find module 'react-native/package.json'
│ Require stack:
│ - /home/vehnet/source/pnpm-nrwl/node_modules/.pnpm/detox@20.19.1/node_modules/detox/src/utils/rn-consts/rn-consts.js
│ - /home/vehnet/source/pnpm-nrwl/node_modules/.pnpm/detox@20.19.1/node_modules/detox/scripts/updateGradle.js
│ - /home/vehnet/source/pnpm-nrwl/node_modules/.pnpm/detox@20.19.1/node_modules/detox/scripts/postinstall.js
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
│     at Module._load (node:internal/modules/cjs/loader:922:27)
│     at Module.require (node:internal/modules/cjs/loader:1143:19)
│     at require (node:internal/modules/cjs/helpers:110:18)
│     at parseRNVersion (/home/vehnet/source/pnpm-nrwl/node_modules/.pnpm/detox@20.19.1/node_modules/detox/src/utils/rn-consts/rn-consts.js:2:23)
│     at Object.<anonymous> (/home/vehnet/source/pnpm-nrwl/node_modules/.pnpm/detox@20.19.1/node_modules/detox/src/utils/rn-consts/rn-consts.js:11:3)
│     at Module._compile (node:internal/modules/cjs/loader:1256:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
│     at Module.load (node:internal/modules/cjs/loader:1119:32)
│     at Module._load (node:internal/modules/cjs/loader:960:12) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     '/home/vehnet/source/pnpm-nrwl/node_modules/.pnpm/detox@20.19.1/node_modules/detox/src/utils/rn-consts/rn-consts.js',
│     '/home/vehnet/source/pnpm-nrwl/node_modules/.pnpm/detox@20.19.1/node_modules/detox/scripts/updateGradle.js',
│     '/home/vehnet/source/pnpm-nrwl/node_modules/.pnpm/detox@20.19.1/node_modules/detox/scripts/postinstall.js'
│   ]
│ }
│ Node.js v18.17.0
└─ Failed in 71ms at /home/vehnet/source/pnpm-nrwl/node_modules/.pnpm/detox@20.19.1/node_modules/detox
```

This issue happens on both Windows 11 and Ubuntu 20.04.4 LTS when using the latest version of pnpm `8.15.4`
The workspace creation works as expected when using npm.

### Expected Behavior

The create-nx-workspace should complete when using it with `pnpx` so that pnpm can be used as package manager.

### GitHub Repo

_No response_

### Steps to Reproduce

1. `pnpx create-nx-workspace pnpm-nrwl --preset=react-native --appName=mobile --nxCloud=skip`
2. open the workspace folder and run `pnpm add -D @nx/detox@18.0.8`
3. package installation will fail with the following error

```
.../detox@20.19.1/node_modules/detox postinstall$ node scripts/postinstall.js
│ node:internal/modules/cjs/loader:1080
│   throw err;
│   ^
│ Error: Cannot find module 'react-native/package.json'
```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.17.0
OS     : win32-x64
pnpm   : 8.15.3

nx                : 18.0.8
@nx/js            : 18.0.8
@nx/jest          : 18.0.8
@nx/linter        : 18.0.8
@nx/eslint        : 18.0.8
@nx/workspace     : 18.0.8
@nx/detox         : 18.0.8
@nx/devkit        : 18.0.8
@nx/react         : 18.0.8
@nx/react-native  : 18.0.8
@nrwl/tao         : 18.0.8
@nx/web           : 18.0.8
typescript        : 5.3.3
```

### Failure Logs

```shell
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 2, reused 2, downloaded 0, added 0
Progress: resolved 57, reused 40, downloaded 0, added 0
Progress: resolved 105, reused 89, downloaded 2, added 0
Progress: resolved 209, reused 189, downloaded 5, added 0
Progress: resolved 385, reused 359, downloaded 13, added 0
Progress: resolved 639, reused 600, downloaded 14, added 0
Progress: resolved 703, reused 674, downloaded 19, added 0
Packages: +701
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 707, reused 677, downloaded 19, added 106
Progress: resolved 707, reused 677, downloaded 20, added 304
Progress: resolved 707, reused 677, downloaded 20, added 536
Progress: resolved 707, reused 677, downloaded 20, added 695
Progress: resolved 707, reused 677, downloaded 20, added 701, done
.../.pnpm/nx@18.0.8/node_modules/nx postinstall$ node ./bin/post-install
.../.pnpm/nx@18.0.8/node_modules/nx postinstall: Done

devDependencies:
+ @nx/react-native 18.0.8
+ @nx/workspace 18.0.8
+ nx 18.0.8

Done in 16.9s

 NX  Generating @nx/workspace:preset

Fetching prettier...
Fetching @nx/webpack...
Fetching @nx/detox...

 NX   Command failed: pnpm add -D @nx/detox@18.0.8

Pass --verbose to see the stacktrace.


 NX   Workspace creation failed, see above.

Pass --verbose to see the stacktrace.
```

### Package Manager Version

pnpm 8.15.4

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### LINKED ISSUE #22383: Nx create workspace (React Standalone App) is not working in Windows while using --pm=yarn
##### I am creating this in D drive of my computer (in C drive its working properly)
```npx create-nx-workspace@latest myreactapp --preset=react-standalone --packageManager=yarn```
#### This command results into the following : 
1.  Which bundler would you like to use? => Vite
2. Test runner to use for end to end (E2E) tests => None
3. Default stylesheet format => SASS
4. Do you want Nx Cloud to make your CI fast? => Skip for now

- [x] Installing dependencies with yarn
- [ ] Creating your workspace in myreactapp ( not completed )   

### GitHub Repo

_No response_

### Steps to Reproduce

1. Go to any drive of your computer (Other than C Drive).
2. open terminal and select node version
```nvm use 18```
3. run the command
```npx create-nx-workspace@latest myreactapp --preset=react-standalone --packageManager=yarn```
4. It will result into Error.

### Nx Report

```shell
NX   Failed to create a workspace.

Error: error Command failed with exit code 1.
```

### Failure Logs

```shell
There is no logs created for this, I have tried to access error logs but it's not creating any error logs.
```

### Package Manager Version

yarn - 1.22.19 

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

1. when creating workspace using older version (eg. 16) instead of @latest then it's working properly. 
2. While using package manager as npm its working properly.

### LINKED ISSUE #22917: npx create-nx-workspace --pm yarn fails on Windows 11 Home 23H2
### Current Behavior

 When running ```npx create-nx-workspace --pm yarn``` it fails
 but when using npm or pnpm its working fine 
 also it is working fine in WSL 

### Expected Behavior

It should work when package manger is yarn

### GitHub Repo

_No response_

### Steps to Reproduce

1. run npx create-nx-workspace@latest --pm yarn on windows 11 with node lts v20.12.2 or v18.18.0 or v20.10.0

### Nx Report

```shell
Not able to run
```

### Failure Logs

```shell
PS D:\Projects\Ankish> npx create-nx-workspace@latest --pm yarn

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

√ Where would you like to create your workspace? · psi
√ Which stack do you want to use? · react
√ What framework would you like to use? · nextjs
√ Integrated monorepo, or standalone project? · integrated
√ Would you like to use the App Router (recommended)? · Yes
√ Would you like to use the src/ directory? · Yes
√ Test runner to use for end to end (E2E) tests · cypress
√ Default stylesheet format · tailwind
√ Do you want Nx Cloud to make your CI fast? · github

 NX   Creating your v18.3.2 workspace.

✔ Installing dependencies with yarn
✖ Creating your workspace in psi

 NX   Failed to create a workspace.

Error: error Command failed with exit code 1.
```

### Package Manager Version

yarn 1.22.19

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### LINKED ISSUE #27270: Nx failed to create new workspace
### Current Behavior

Create work space with yarn
npx create-nx-workspace test-nx-expo --pm yarn

```
yarn create nx-workspace --verbose
➤ YN0000: · Yarn 4.3.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + create-nx-workspace@npm:19.5.6, ansi-colors@npm:4.1.3, ansi-regex@npm:5.0.1, ansi-styles@npm:4.3.0, asynckit@npm:0.4.0, axios@npm:1.7.3, base64-js@npm:1.5.1, bl@npm:4.1.0, and 48 more.
➤ YN0000: └ Completed in 0s 466ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 56 packages were added to the project (+ 4.07 MiB).
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed in 0s 470ms
➤ YN0000: · Done with warnings in 1s 32ms


 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

√ Where would you like to create your workspace? · org
√ Which stack do you want to use? · angular
√ Integrated monorepo, or standalone project? · integrated
√ Application name · org
√ Which bundler would you like to use? · esbuild
√ Default stylesheet format · scss
√ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
√ Test runner to use for end to end (E2E) tests · playwright
√ Which CI provider would you like to use? · github

 NX   Creating your v19.5.6 workspace.

✔ Installing dependencies with yarn
✖ Creating your workspace in org

 NX   Failed to create a workspace.

Exit code: 1
Log file: C:\Users\chien\AppData\Local\Temp\tmp-8876-UP6RO6Te6NWk\error.log
```

### Expected Behavior

I should be creating an Nx workspace successfully. 

### GitHub Repo

_No response_

### Steps to Reproduce

run   yarn create nx-workspace --verbose

### Nx Report

```shell
I cant create proj to run nx report
```

### Failure Logs

```shell
NX   spawnSync C:\Windows\system32\cmd.exe ENOENT


Error: spawnSync C:\Windows\system32\cmd.exe ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:876:24)
    at execSync (node:child_process:957:15)
    at C:\Users\chien\AppData\Local\Temp\tmp-2876-OdDrTz3Lo5Ax\node_modules\@nx\workspace\src\generators\new\new.js:19:46
    at C:\Users\chien\AppData\Local\Temp\tmp-2876-OdDrTz3Lo5Ax\node_modules\nx\src\command-line\new\new.js:26:19
    at async handleErrors (C:\Users\chien\AppData\Local\Temp\tmp-2876-OdDrTz3Lo5Ax\node_modules\nx\src\utils\params.js:22:24)
    at async Object.handler (C:\Users\chien\AppData\Local\Temp\tmp-2876-OdDrTz3Lo5Ax\node_modules\nx\src\command-line\new\command-object.js:10:22)
```

### Package Manager Version

yarn  4.3.1

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

 NX   spawnSync C:\Windows\system32\cmd.exe ENOENT

Error: spawnSync C:\Windows\system32\cmd.exe ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:876:24)
    at execSync (node:child_process:957:15)
    at C:\Users\chien\AppData\Local\Temp\tmp-8876-UP6RO6Te6NWk\node_modules\@nx\workspace\src\generators\new\new.js:19:46
    at C:\Users\chien\AppData\Local\Temp\tmp-8876-UP6RO6Te6NWk\node_modules\nx\src\command-line\new\new.js:26:19
    at async handleErrors (C:\Users\chien\AppData\Local\Temp\tmp-8876-UP6RO6Te6NWk\node_modules\nx\src\utils\params.js:22:24)
    at async Object.handler (C:\Users\chien\AppData\Local\Temp\tmp-8876-UP6RO6Te6NWk\node_modules\nx\src\command-line\new\command-object.js:10:22)

### LINKED ISSUE #28235: Failed to create a workspace
### Current Behavior

Failed to create a brand new workspace 

### Expected Behavior

The CLI shall create a new workspace as expected.

### GitHub Repo

_No response_

### Steps to Reproduce

1. In terminal, run `npx create-nx-workspace@latest project-name --verbose`
2. After confirming all the options, the CLI returns the following:

```
 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Which stack do you want to use? · react
✔ What framework would you like to use? · nextjs
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · project-name
✔ Would you like to use the App Router (recommended)? · Yes
✔ Would you like to use the src/ directory? · Yes
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Default stylesheet format · tailwind
✔ Which CI provider would you like to use? · github

 NX   Creating your v19.8.3 workspace.

✔ Installing dependencies with npm
✖ Creating your workspace in project-name

 NX   Failed to create a workspace.

Exit code: 1
Log file: /var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/error.log
```

### Nx Report

```shell
The project is not even created, so the `nx report` is not available at this time.
```

### Failure Logs

```shell
NX   protocol mismatch
   3   │
   4   │ AssertionError [ERR_ASSERTION]: protocol mismatch
   5   │     at Object.request (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/follow-redirects/index.js:541:14)
   6   │     at dispatchHttpRequest (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/axios/dist/node/axios.cjs:3000:21)
   7   │     at /private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/axios/dist/node/axios.cjs:2690:5
   8   │     at new Promise (<anonymous>)
   9   │     at wrapAsync (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/axios/dist/node/axios.cjs:2670:10)
  10   │     at http (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/axios/dist/node/axios.cjs:2708:10)
  11   │     at Axios.dispatchRequest (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/axios/dist/node/axios.cjs:4135:10)
  12   │     at Axios._request (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/axios/dist/node/axios.cjs:4415:33)
  13   │     at Axios.request (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/axios/dist/node/axios.cjs:4282:25)
  14   │     at Axios.httpMethod [as post] (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/axios/dist/node/axios.cjs:4454:19)
  15   │     at Axios.request (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/axios/dist/node/axios.cjs:4287:41)
  16   │     at async createNxCloudWorkspaceV2 (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/nx/src/nx-cloud/generators/connect-to-nx-cloud/connect-to-nx-cloud.js:
       │ 47:22)
  17   │     at async connectToNxCloud (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/nx/src/nx-cloud/generators/connect-to-nx-cloud/connect-to-nx-cloud.js:101:44)
  18   │     at async generateWorkspaceFiles (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/@nx/workspace/src/generators/new/generate-workspace-files.js:138:11)
  19   │     at async newGenerator (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/@nx/workspace/src/generators/new/new.js:13:28)
  20   │     at async /private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/nx/src/command-line/new/new.js:23:22
  21   │     at async handleErrors (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/nx/src/utils/handle-errors.js:9:24)
  22   │     at async Object.handler (/private/var/folders/bh/4z9jyg6d1bvgvjb4pp49gpdc0000gn/T/tmp-35801-uHmrFYYxnH0y/node_modules/nx/src/command-line/new/command-object.js:10:22)
```
```


### Package Manager Version

10.7.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

My machine is under a socks5 proxy environment.

### LINKED ISSUE #28289: Unable to create a new workspace using yarn/npm
> Error creating a workspace using yarn.
> 
> 
> ```
> npx create-nx-workspace --pm yarn
> NX   Let's create a new workspace [https://nx.dev/getting-started/intro]
> 
> ✔ Where would you like to create your workspace? · Org
> ✔ Which stack do you want to use? · react
> ✔ What framework would you like to use? · react-native
> ✔ Application name · mobile
> ✔ Test runner to use for end to end (E2E) tests · playwright
> ✔ Which CI provider would you like to use? · skip
> ✔ Would you like remote caching to make your build faster? · yes
> ✔ Will you be using GitHub as your git hosting provider? · Yes
> 
>  NX   Creating your v19.8.3 workspace.
> 
> ✔ Installing dependencies with yarn
> ✖ Creating your workspace in Org
> 
>  NX   Failed to create a workspace.
> 
> Exit code: 1
> Log file: /var/folders/1m/sv50vh4s6l5fkn_hq_9g_xn00000gp/T/tmp-79467-08gEWEIyk7Si/error.log
> ```
> 
> And my error log looks like this
> ```
> yarn run v1.22.22
> $ /private/var/folders/1m/sv50vh4s6l5fkn_hq_9g_xn00000gp/T/tmp-79467-08gEWEIyk7Si/node_modules/.bin/nx new --pm=yarn --packageManager=yarn --interactive --standaloneApi --routing --no-skipGit --no-g '--commit.message=Initial commit' --no-allPrompts --no-a --useGitHub --/bin/sh=/Users/n.vinay/.npm/_npx/d2207cf76adb22dc/node_modules/.bin/create-nx-workspace --name=Org --stack=react --preset=react-native --appName=mobile --no-nextAppDir --no-nextSrcDir --e2eTestRunner=playwright --nxCloud=yes --defaultBase=main --nxWorkspaceRoot=/Users/n.vinay/Work/Monorepo
> Resolving 1.22.22 to a url...
> Downloading https://github.com/yarnpkg/yarn/releases/download/v1.22.22/yarn-1.22.22.js...
> Saving it into /Users/n.vinay/Work/Monorepo/Org/.yarn/releases/yarn-1.22.22.cjs...
> Updating /Users/n.vinay/Work/Monorepo/Org/.yarnrc...
> Done!
> info No lockfile found.
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> success Saved lockfile.
> $ /Users/n.vinay/Work/Monorepo/Org/node_modules/.bin/nx g @nx/workspace:preset --name=mobile --style=css --linter=eslint --preset=react-native --nextAppDir=false --nextSrcDir=false --packageManager=yarn --standaloneApi=true --interactive=true --routing=true --e2eTestRunner=playwright --nxCloudToken=66ff7c5b6e46622bb2fb2b37
> 
>  NX  Generating @nx/workspace:preset
> 
> Fetching prettier...
> Fetching @nx/webpack...
> 
>  NX   Unable to read the target configuration for the provided build target, mobile:build
> 
> Are you sure this target exists?
> Pass --verbose to see the stacktrace.
> 
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
>  NX   Workspace creation failed, see above.
> 
> Pass --verbose to see the stacktrace.
> 
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> warning @nx/react-native > glob@7.1.4: Glob versions prior to v9 are no longer supported
> warning @nx/react-native > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
> warning @nx/react-native > @nx/jest > @jest/reporters > glob@7.2.3: Glob versions prior to v9 are no longer supported
> warning @nx/react-native > @nx/jest > @jest/reporters > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
> warning @nx/react-native > @nx/jest > jest-config > glob@7.2.3: Glob versions prior to v9 are no longer supported
> warning @nx/react-native > @nx/jest > jest-config > jest-runner > jest-runtime > glob@7.2.3: Glob versions prior to v9 are no longer supported
> warning @nx/react-native > @nx/jest > @jest/reporters > @jest/transform > babel-plugin-istanbul > test-exclude > glob@7.2.3: Glob versions prior to v9 are no longer supported
> warning "@nx/react-native > @nx/js > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
> warning "@nx/react-native > @nx/js > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".
> warning "@nx/react-native > @nx/jest > @phenomnomnominal/tsquery@5.0.1" has unmet peer dependency "typescript@^3 || ^4 || ^5".
> warning "@nx/react-native > @nx/react > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
> warning "@nx/react-native > @nx/eslint@19.8.3" has unmet peer dependency "eslint@^8.0.0 || ^9.0.0".
> warning "@nx/react-native > @nx/react > @module-federation/enhanced > @module-federation/dts-plugin@0.6.9" has unmet peer dependency "typescript@^4.9.0 || ^5.0.0".
> warning "@nx/react-native > @nx/react > @module-federation/enhanced > @module-federation/data-prefetch@0.6.9" has unmet peer dependency "react@>=16.9.0".
> warning "@nx/react-native > @nx/react > @module-federation/enhanced > @module-federation/data-prefetch@0.6.9" has unmet peer dependency "react-dom@>=16.9.0".
> error Command failed with exit code 1.
> error Command failed with exit code 1.
> 
> ```
>  

 _Originally posted by @nvinay-litmus7 in [#28235](https://github.com/nrwl/nx/issues/28235#issuecomment-2392900324)_

### LINKED ISSUE #28710: Workspace Creation Fails Due to License Field Warning with Yarn
### Current Behavior

Error: warning ../../../../package.json: No license field
error Command failed with exit code 1

### Expected Behavior

The Nx workspace should be successfully created without errors.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Run npx create-nx-workspace --pm yarn.
2. Choose:
-Directory for workspace: vvvv
-Stack: none
-Prettier: No
-CI provider: GitHub
3. Nx begins creating the workspace but fails with an error.

### Nx Report

>  NX  Report complete - copy this into the issue template

  Node : x.x.x
  OS   : Your Operating System Info
  yarn : x.x.x

  nx : x.x.x
  @nrwl/angular : Not Found
  @nrwl/cypress : Not Found
  @nrwl/detox : Not Found
  @nrwl/devkit : x.x.x
  @nrwl/eslint-plugin-nx : x.x.x
  @nrwl/express : Not Found
  @nrwl/jest : Not Found
  @nrwl/js : x.x.x
  @nrwl/linter : x.x.x
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : x.x.x
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/react-native : Not Found
  @nrwl/rollup : x.x.x
  @nrwl/storybook : Not Found
  @nrwl/web : Not Found
  @nrwl/workspace : x.x.x
  typescript : x.x.x

### Failure Logs

_No response_

### Package Manager Version

yarn: 1.22.19

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

This issue appears to be related to a warning about the missing license field in package.json. Ensuring the workspace creation process handles this warning or providing guidance on how to avoid this error would be helpful.

Thank you for looking into this!

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior
On Windows, when packageManager=pnpm, `create-nx-workspace` fails due to an issue with `child_process.spawn`.
Using `spawn`, the `@nx/workspace:preset` generator is executed twice when `packageManager=pnpm`, causing the overall create-nx-workspace flow to fail, even though most things have been set up correctly to that point.

Using `fork` has shown success.

## Expected Behavior
Running `create-nx-workspace --packageManager=pnpm` should work on Windows

## Fixes
Fixes #20222 
Fixes #27270 
Fixes #22917 
Fixes #22312 
Fixes #28710 
Fixes #28289 
Fixes #28235 
Fixes #22383 
Fixes #21742 
Fixes #20270

### CODE REVIEW

File: packages/workspace/src/generators/new/generate-preset.ts [hunk 1]
```diff
@@ -32,25 +32,33 @@ export function generatePreset(host: Tree, opts: NormalizedSchema) {
...
-    shell: true,
-    cwd: join(host.root, opts.directory),
-    windowsHide: false,
+    cwd: newWorkspaceRoot,
   };
   const pmc = getPackageManagerCommand();
-  const executable = `${pmc.exec} nx`;
+  const nxBinForNewWorkspaceRoot = require.resolve('nx/bin/nx', {
+    paths: [join(newWorkspaceRoot, 'node_modules')],
+  });
```
Comment (FrozenPandaz) [inline packages/workspace/src/generators/new/generate-preset.ts:44]: There should be another method which handles the `.nx` installation as well where this won't work.

File: packages/workspace/src/generators/new/generate-preset.ts [hunk 2]
```diff
@@ -32,25 +32,33 @@ export function generatePreset(host: Tree, opts: NormalizedSchema) {
       interactive: true,
     },
   });
-  const spawnOptions: SpawnOptions = {
+
+  const newWorkspaceRoot = join(host.root, opts.directory);
+  const spawnOptions: ForkOptions = {
```
Comment (FrozenPandaz) [inline packages/workspace/src/generators/new/generate-preset.ts:37]: Change the name of this

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
