### PR TITLE
fix(js): avoid duplicate `@nx/js/typescript` plugin entries for non-buildable libs

### LINKED ISSUE #33981: In my ts project adding a new js library always creates a duplicate @nx/js/typescript plugin entry
### Current Behavior

Given this `nx.json`:

```json
  "plugins": [
    {
      "plugin": "@nx/js/typescript",
      "options": {
        "typecheck": {
          "targetName": "typecheck"
        },
        "build": {
          "targetName": "build",
          "configName": "tsconfig.lib.json",
          "buildDepsName": "build-deps",
          "watchDepsName": "watch-deps"
        }
      }
    },
```

After running `npx nx g @nx/js:lib packages/job-handler` I end up with:

```json
  "plugins": [
    {
      "plugin": "@nx/js/typescript",
      "options": {
        "typecheck": {
          "targetName": "typecheck"
        },
        "build": {
          "targetName": "build",
          "configName": "tsconfig.lib.json",
          "buildDepsName": "build-deps",
          "watchDepsName": "watch-deps"
        }
      },
      "exclude": ["packages/job-handler/*"]
    },
    {
      "plugin": "@nx/js/typescript",
      "include": ["packages/job-handler/*"],
      "options": {
        "typecheck": {
          "targetName": "typecheck"
        }
      }
    }
```

This doesn't make any sense to me. Possibly this "build" target override?

### Expected Behavior

I expect no duplicate entries ever to be created.

### GitHub Repo

_No response_

### Steps to Reproduce

1. See above.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 24.11.1
OS             : linux-x64
Native Target  : x86_64-linux
bun            : 1.3.4

nx                 : 22.3.3
@nx/js             : 22.3.3
@nx/eslint         : 22.2.0
@nx/devkit         : 22.3.3
@nx/esbuild        : 22.3.3
@nx/eslint-plugin  : 22.2.0
@nx/next           : 22.3.3
@nx/node           : 22.3.3
@nx/playwright     : 22.3.3
@nx/vite           : 22.3.3
@nx/vitest         : 22.3.3
@nx/web            : 22.3.3
typescript         : 5.9.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/next/plugin
@nx/playwright/plugin
@nx/vite/plugin
@berenddeboer/nx-aws-cdk/plugin
@nx/vitest
@berenddeboer/nx-biome
---------------------------------------
Community plugins:
@berenddeboer/nx-aws-cdk : 3.0.3
@berenddeboer/nx-biome   : 1.0.1
---------------------------------------
Cache Usage: 59.68 MB / 40.39 GB
---------------------------------------
The following packages should match the installed version of nx
  - @nx/eslint@22.2.0
  - @nx/eslint-plugin@22.2.0

To fix this, run `nx migrate nx@22.3.3`
---------------------------------------
⚠️ Multiple Nx versions detected

Your workspace uses nx@22.3.3, but other packages depend on a different version:
  - nx@22.2.3

These packages should not have nx as a dependency. Please report this issue to the package maintainers.
Run `bun why nx@22.2.3` for more details.
```

### Failure Logs

```shell

```

### Package Manager Version

Bun 1.3.4

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leosvelperez**
## Current Behavior

When adding a non-buildable JS library (`bundler: 'none'`) to a workspace with an existing `@nx/js/typescript` plugin registration that has build options configured, a duplicate plugin entry is unnecessarily created in `nx.json`.

## Expected Behavior

Non-buildable libraries reuse the existing plugin registration when `skipBuildCheck: true` is not specified, thereby avoiding duplicate entries in `nx.json`. The `@nx/js/typescript` plugin will infer the project as non-buildable because the library's `package.json` will have entry points pointing to source files, so there's no need for a separate plugin registration.

## Related Issue(s)

Fixes #33981

### CODE REVIEW

File: packages/js/src/utils/typescript/plugin.ts [hunk 1]
```diff
@@ -110,52 +110,6 @@ export function ensureProjectIsIncludedInPluginRegistrations(
   }
 }
 
-export function ensureProjectIsExcludedFromPluginRegistrations(
```
Comment (leosvelperez) [inline packages/js/src/utils/typescript/plugin.ts:113]: This function was unused.

**Review by Coly010 — APPROVED** [review]
