### PR TITLE
fix(schematics): support migrating projects with root != name from 1.7

### LINKED ISSUE #512: Migration from 1.x - 6.0 errors when project name does not match project root
### Current Behavior
This migration is using the name of the project to locate the files to move.

### Expected Behavior
This should use the root of the project

### Steps to Reproduce
Repo: https://github.com/merlosy/ngx-material-file-input/tree/ng6

```sh
npm i @nrwl/schematics@latest -D
npm run update
```

### PR DESCRIPTION
**Pull request by FrozenPandaz**
## Current Behavior

The Migration for 1.7 workspaces which contain projects where the name is different from the root fail

## Expected Behavior

The Migration for 1.7 workspaces which contain projects where the name is different from the root succeed and the root is preserved.

Fixes https://github.com/nrwl/nx/issues/512

### CODE REVIEW

File: packages/schematics/migrations/legacy-migrations/20180515-switch-to-nx6.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ export default {
     }
 
     updateJsonFile('package.json', json => {
-      json.devDependencies['@angular/cli'] = '6.0.1';
+      json.devDependencies['@angular/cli'] = '6.1.2';
```
Comment (vsavkin) [inline packages/schematics/migrations/legacy-migrations/20180515-switch-to-nx6.ts]: Why is this required? Shouldn't the latest migration (nx 6.1 => nx 6.2) do it for us?

**Review by vsavkin — CHANGES_REQUESTED** [review]

File: packages/schematics/migrations/legacy-migrations/20180515-switch-to-nx6.ts (hunk 1 above)
Comment (FrozenPandaz) [reply packages/schematics/migrations/legacy-migrations/20180515-switch-to-nx6.ts]: The CLI _had_ static values for this in their initial 6.0 migration.
* This got rid of the original `root` and `sourceRoot` information so we had no choice but to rely on the key/name of the project.
* It has been fixed in `6.1.2` though so the root is preserved.
  * https://github.com/angular/devkit/pull/985

Now, we can use their new version of the migration to 6.0 in our migration to 6.0 and not overwrite the `root` and `sourceRoot` ourselves.
