### PR TITLE
fix(format.ts): add filtering of deleted files

### LINKED ISSUE #1036: Formatting affected files throws if only files are deleted
## Current Behavior

`nx format:write --uncommited` throws an error when _only_ files are deleted in the diff

```
Jasons-MacBook-Pro:nesttest jason$ yarn format:write --uncommitted
yarn run v1.13.0
$ ./node_modules/.bin/nx format:write --uncommitted
[error] No matching files. Patterns tried: apps/app2/src/app/app.module.ts !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
/Users/jason/projects/temp/temp/nesttest/node_modules/@nrwl/schematics/node_modules/yargs/yargs.js:1133
      else throw err
```

## Expected Behavior

`nx format:write --uncommited` should not throw an error because it is fine in our case to not format anything.

## Related Code

https://github.com/nrwl/nx/blob/master/packages/schematics/src/command-line/format.ts#L44

### PR DESCRIPTION
**Pull request by ZachJW34**
Formatting of uncommitted files errors when the only change is the deletion of files. Checking if
the file exists before writing solves this issue.

Fixes #1036

### CODE REVIEW

**Comment by ZachJW34** [comment]
I also considered adding the paramater `--diff-filter=d` to the git command `getUncommittedFiles()` (`packages/schematics/src/command-line/shared.ts`) but I didn't want to cause issues if their was a need to obtain deleted files from the diff. A flag could be created to choose between obtaining all file changes or only non-deleted file changes, so let me know if this is a solution that would be cleaner rather than manually checking if `fileExists()`.

File: packages/schematics/src/command-line/format.ts [hunk 1]
```diff
@@ -41,7 +42,8 @@ function getPatterns(args: YargsAffectedOptions) {
     }
 
     const p = parseFiles(args);
-    let patterns = p.files.filter(f =>
+    const files = p.files.filter(f => fileExists(f));
+    let patterns = files.filter(f =>
```
Comment (FrozenPandaz) [inline packages/schematics/src/command-line/format.ts]: You can chain the `filter`s instead of creating an otherwise unused variable.

**Review by FrozenPandaz — COMMENTED** [review]
Can you also change your commit to something like:

`fix(nx): filter non-existing files during format`

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
Thanks for the contribution!

Only have some minor changes to request

**Comment by ZachJW34** [comment]
@FrozenPandaz Updated!

**Comment by FrozenPandaz** [comment]
Thank you!

LGTM!
