### PR TITLE
fix(core): allow parsing dot notation cli args

### LINKED ISSUE #9764: v13.10.0 - Cypress does not respect env cli params (regression)
## Current Behavior
Seems like a regression of https://github.com/nrwl/nx/issues/8723

```sh
   Node : 16.13.0
   OS   : darwin x64
   yarn : 3.2.0
   
   nx : 13.10.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.1
   @nrwl/eslint-plugin-nx : 13.10.1
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.1
   @nrwl/js : 13.10.1
   @nrwl/linter : 13.10.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.10.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.1
   @nrwl/web : 13.10.1
   @nrwl/workspace : 13.10.1
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         nx-stylelint: 13.3.0

```

### PR DESCRIPTION
**Pull request by barbados-clemens**
parse dot notation cli args for env args passed to cypress executor to override cypress.env.json
values.
i.e. `nx e2e project --env.API_URL=localhost:1234`
will now correctly give cypress e2e args to
override the cypress.env.json values

## Current Behavior
`nx e2e project --env.API_URL=localhost:1234` does not parse the correct env args for cypress

## Expected Behavior
`nx e2e project --env.API_URL=localhost:1234` correctly is parsed for cypress

## Related Issue(s)

Fixes #9764

### CODE REVIEW

File: packages/nx/src/command-line/nx-commands.ts [hunk 1]
```diff
@@ -25,7 +25,8 @@ yargs.wrap(yargs.terminalWidth());
 export const commandsObject = yargs
   .parserConfiguration({
     'strip-dashed': true,
-    'dot-notation': false,
+    // allow parsing --env.SOME_ARG for cypress cli env args
+    'dot-notation': true,
```
Comment (FrozenPandaz) [inline packages/nx/src/command-line/nx-commands.ts:29]: This keeps breaking. Could you please add an unit test for it here?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
