### PR TITLE
fix(testing): walk all project deps to check if CT project is used in buildTarget

### LINKED ISSUE #14881: Cypress Component Testing - styles excluded from build target if not a direct dependency
### Current Behavior

Styles get excluded from the component test unless the ct project is a direct dependency of the build target project.
Component Test in `shared-ui`.   `app` is the build target.

image

@barbados-clemens indicated the [following code block](https://github.com/nrwl/nx/blob/master/packages/angular/plugins/component-testing.ts#L196-L200) in #12758.   Does the implementation account for transitive dependencies?

### Expected Behavior

Styles should be present.

### GitHub Repo

https://github.com/Tungsten78/nx-integrated-angular

### Steps to Reproduce

1. `nx component-test shared-ui --watch`

expected: black div from tailwind
actual: black div is absent, styles are missing

Workarounds:
- [add an import](https://github.com/Tungsten78/nx-integrated-angular/blob/84591107c0e44f28c87a8c17f181e1267aa4846d/apps/app/src/app/app.module.ts#L13)
- add `"implicitDependencies": ["shared-ui"]` to app's project.json

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 19.5.0
   OS   : darwin arm64
   npm  : 9.3.1
   
   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by barbados-clemens**
## Current Behavior

being more than 1 node away from the defined 'buildTarget' would not allows assets/scripts/styles to be included in the dynamic project config that angular CT creates for cypress.

## Expected Behavior

The CT plugin walks all the deps from the buildTarget project to check if the CT project is being used instead of direct dependencies of buildTarget.

## TODO
- [x] add e2e tests
## Related Issue(s)

Fixes #14881

### CODE REVIEW

File: packages/cypress/src/utils/ct-helpers.ts [hunk 1]
```diff
@@ -39,20 +39,37 @@ export function getTempTailwindPath(context: ExecutorContext) {
...
+  );
+  if (isProjectDirectDep) {
+    return true;
+  }
+
+  const maybeItermediateProjects = graph.dependencies[parentProjectName].filter(
+    (p) => !graph.externalNodes[p.target]
   );
+
+  for (const maybeIntermediateProject of maybeItermediateProjects) {
```
Comment (leosvelperez) [inline packages/cypress/src/utils/ct-helpers.ts:61]:
```suggestion
  const maybeIntermediateProjects = graph.dependencies[parentProjectName].filter(
    (p) => !graph.externalNodes[p.target]
  );

  for (const maybeIntermediateProject of maybeIntermediateProjects) {
```

**Review by leosvelperez — APPROVED** [review]

**Review by FrozenPandaz — APPROVED** [review]
