### PR TITLE
fix(core): update yarn-parser to handle yarn v4 syntax

### LINKED ISSUE #19881: yarn.lock not generated correctly with yarn v4
### Current Behavior

When using Yarn v4 and executing a build using @nx/webpack with `"generateLockfile": true`, the generated yarn.lock file is not generated correctly.

The first item in the yarn.lock file is generated without a name as seen below

```
"":
  version: 1.22.8
  resolution: "resolve@patch:resolve@npm%3A1.22.8#optional!builtin<compat/resolve>::version=1.22.8&hash=c3c19d"
  dependencies:
    is-core-module: "npm:^2.13.0"
    path-parse: "npm:^1.0.7"
    supports-preserve-symlinks-flag: "npm:^1.0.0"
  bin:
    resolve: bin/resolve
  checksum: 0446f024439cd2e50c6c8fa8ba77eaa8370b4180f401a96abf3d1ebc770ac51c1955e12764cde449fde3fff480a61f84388e3505ecdbab778f4bef5f8212c729
  languageName: node
  linkType: hard
``` 

However, this is the corresponding entry from the root yarn.lock file
```
"resolve@patch:resolve@npm%3A^1.1.7#optional!builtin<compat/resolve>, resolve@patch:resolve@npm%3A^1.10.0#optional!builtin<compat/resolve>, resolve@patch:resolve@npm%3A^1.12.0#optional!builtin<compat/resolve>, resolve@patch:resolve@npm%3A^1.14.2#optional!builtin<compat/resolve>, resolve@patch:resolve@npm%3A^1.19.0#optional!builtin<compat/resolve>, resolve@patch:resolve@npm%3A^1.20.0#optional!builtin<compat/resolve>, resolve@patch:resolve@npm%3A^1.22.1#optional!builtin<compat/resolve>, resolve@patch:resolve@npm%3A^1.22.4#optional!builtin<compat/resolve>":
  version: 1.22.8
  resolution: "resolve@patch:resolve@npm%3A1.22.8#optional!builtin<compat/resolve>::version=1.22.8&hash=c3c19d"
  dependencies:
    is-core-module: "npm:^2.13.0"
    path-parse: "npm:^1.0.7"
    supports-preserve-symlinks-flag: "npm:^1.0.0"
  bin:
    resolve: bin/resolve
  checksum: 0446f024439cd2e50c6c8fa8ba77eaa8370b4180f401a96abf3d1ebc770ac51c1955e12764cde449fde3fff480a61f84388e3505ecdbab778f4bef5f8212c729
  languageName: node
  linkType: hard
```

As a result, `yarn install` will fail with the following error
```
Internal Error: Invalid descriptor ()
```

### Expected Behavior

The yarn.lock file should include the name of the matching entry from the root yarn.lock so that `yarn install` runs correctly

### GitHub Repo

_No response_

### Steps to Reproduce

1.  Set up a new nx repo with Yarn v4
2. Create a new node application that uses webpack and set `"generateLockfile": true`
3. Build the app
4. Try to install the app dependencies with `yarn install`

### Nx Report

```shell
Node   : 20.9.0
   OS     : darwin-arm64
   yarn   : 4.0.0
   
   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nrwl/linter       : 15.9.2
   @nx/workspace      : 17.0.2
   @nx/cypress        : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/esbuild        : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/node           : 17.0.2
   @nx/react          : 17.0.2
   @nx/storybook      : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/web            : 17.0.2
   @nx/webpack        : 17.0.2
   typescript         : 5.2.2
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by a88zach**
Update the yarn-parser so that yarn.lock file generation works with yarn v4

## Current Behavior
yarn.lock is not correctly created when using yarn v4

```
"":
  version: 1.22.8
  resolution: "resolve@patch:resolve@npm%3A1.22.8#optional!builtin<compat/resolve>::version=1.22.8&hash=c3c19d"
  dependencies:
    is-core-module: "npm:^2.13.0"
    path-parse: "npm:^1.0.7"
    supports-preserve-symlinks-flag: "npm:^1.0.0"
  bin:
    resolve: bin/resolve
  checksum: 0446f024439cd2e50c6c8fa8ba77eaa8370b4180f401a96abf3d1ebc770ac51c1955e12764cde449fde3fff480a61f84388e3505ecdbab778f4bef5f8212c729
  languageName: node
  linkType: hard
```

## Expected Behavior
yarn.lock should be created correctly with no missing keys

## Related Issue(s)

Fixes #19881

### CODE REVIEW

File: packages/nx/src/plugins/js/lock-file/yarn-parser.ts [hunk 1]
```diff
@@ -474,9 +474,10 @@ function mapSnapshots(
       const packageName = key.slice(0, key.indexOf('@', 1));
       let normalizedKey = key;
       if (isBerry && key.includes('@patch:') && key.includes('#')) {
+        const regEx = new RegExp(`@patch:${packageName}@(npm%3A)?(.*)$`);
         normalizedKey = key
           .slice(0, key.indexOf('#'))
-          .replace(`@patch:${packageName}@`, '@npm:');
+          .replace(regEx, '@npm:$2');
```
Comment (a88zach) [inline packages/nx/src/plugins/js/lock-file/yarn-parser.ts:480]: The entries for yarn 3 follow this syntax:
`resolve@patch:resolve@1.22.8#~builtin<compat/resolve>`

The entries for yarn 4 follow this syntax:
`resolve@patch:resolve@npm%3A1.22.8#optional!builtin<compat/resolve>`

**Comment by a88zach** [comment]
@leosvelperez any thoughts on this one?

**Review by AgentEnder — APPROVED** [review]
