### PR TITLE
fix(storybook): path on Win for tsconfig location in angular.json

### LINKED ISSUE #3956: Nx 10.3.1 migrations produce wrong angular.json paths on Windows
## Current Behavior

Running migrations on Windows creates wrong paths in `angular.json`:

screen4

## Expected Behavior

It should use the normal `../..` path separator for the new paths.

## Steps to Reproduce

When migrating from an Nx `10.1` workspace, on a Windows prompt (not WSL etc.):

```bash
nx migrate 10.3.1
yarn
nx migrate --run-migrations=migrations.json`
```

### PR DESCRIPTION
**Pull request by juristr**
## Related Issue(s)

Fixes #3956

### CODE REVIEW

File: packages/storybook/src/migrations/update-10-3-0/update-10-3-0.ts [hunk 1]
```diff
@@ -53,11 +54,12 @@ function updateLintTarget(
   const architect = options.projectConfig.architect;
 
   const paths = {
-    tsConfig: path.join(options.projectConfig.root, 'tsconfig.json'),
-    tsConfigLib: path.join(options.projectConfig.root, 'tsconfig.lib.json'),
-    tsConfigStorybook: path.join(
-      options.projectConfig.root,
-      '.storybook/tsconfig.json'
+    tsConfig: normalize(path.join(options.projectConfig.root, 'tsconfig.json')),
```
Comment (vsavkin) [inline packages/storybook/src/migrations/update-10-3-0/update-10-3-0.ts:57]: This is required because the project root has `\\` in its path?

Comment (juristr) [reply packages/storybook/src/migrations/update-10-3-0/update-10-3-0.ts:57]: no, there was an issue that Rares mentioned related to these paths on Windows. I'm working on a fix just now

Comment (juristr) [reply packages/storybook/src/migrations/update-10-3-0/update-10-3-0.ts:57]: but to be precise, that specific line wouldn't probably need the normalize, I'm gonna remove it there

**Review by rarmatei — APPROVED** [review]
