### PR TITLE
fix(core): project json angular devkit wrapper

### LINKED ISSUE #6271: Generating a new project after converting all projects brings config back into workspace.json/angular.json
## Steps to Reproduce

image

- Change `"version": 2,`
- `npx nx format`
- `npx ng g @nrwl/workspace:convert-to-nx-project --all`
- `npx ng generate @nrwl/angular:application --name=apptwo --no-interactive`

At this point you will see that the config from `project.json` has been put back into `workspace.json`/`angular.json` (I've verified it happens with both), but the `project.json` also sticks around, and `nx.json` _isn't_ updated.

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
Running any devkit generator that uses a wrapped angular schematic inlines project.json files into workspace / angular.json

## Expected Behavior
Running devkit generators should not inline configurations.

## Related Issue(s)

Fixes #6271 #6272

### CODE REVIEW

File: packages/tao/src/commands/ngcli-adapter.ts [hunk 1]
```diff
@@ -858,6 +858,12 @@ export function wrapAngularDevkitSchematic(
 
       if (event.kind === 'error') {
       } else if (event.kind === 'update') {
+        if (
+          r.eventPath === '/angular.json' ||
```
Comment (Coly010) [inline packages/tao/src/commands/ngcli-adapter.ts:862]: Is the `/` significant here? Why does `angular.json` have it, but `workspace.json` not?

**Review by Coly010 — APPROVED** [review]
LGTM! One comment just for clarification :)

File: packages/tao/src/commands/ngcli-adapter.ts (hunk 1 above)
Comment (AgentEnder) [reply packages/tao/src/commands/ngcli-adapter.ts:862]: Good catch, neither should have 👍

File: packages/tao/src/commands/ngcli-adapter.ts [hunk 2]
```diff
@@ -1003,3 +1009,23 @@ const getTargetLogger = (
...
   return tslintExecutorLogger;
 };
+
+function splitProjectFileUpdatesFromWorkspaceUpdate(
+  host: Tree,
+  r: { eventPath: string; content: Buffer }
+) {
+  const workspace: {
+    projects: { [key: string]: string | { configFilePath?: string } };
+  } = JSON.parse(r.content.toString());
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/ngcli-adapter.ts:1019]: Use `import { parseJson } from '../../utils/json';`

File: packages/tao/src/commands/ngcli-adapter.ts [hunk 3]
```diff
@@ -1003,3 +1009,23 @@ const getTargetLogger = (
   );
   return tslintExecutorLogger;
 };
+
+function splitProjectFileUpdatesFromWorkspaceUpdate(
+  host: Tree,
+  r: { eventPath: string; content: Buffer }
+) {
+  const workspace: {
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/ngcli-adapter.ts:1017]: We have a type for `WorkspaceJsonConfiguration`

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/tao/src/commands/ngcli-adapter.ts (hunk 2 above)
Comment (AgentEnder) [reply packages/tao/src/commands/ngcli-adapter.ts]: 👍

File: packages/tao/src/commands/ngcli-adapter.ts (hunk 3 above)
Comment (AgentEnder) [reply packages/tao/src/commands/ngcli-adapter.ts:1017]: Not applicable here since we are using the `configFilePath` property.

**Review by FrozenPandaz — APPROVED** [review]
