### PR TITLE
fix(storybook): revert to previous defaults for Storybook CLI options

### LINKED ISSUE #14462: Storybook React Webpack does not process .mdx files after update to 15.5.2
### Current Behavior

Storybook can not be build if project has MDX stories:
```
ERR! => Failed to build the preview
ERR! Module parse failed: Unexpected token (16:0)
ERR! You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

The same setup was working on older Nx `15.4.1`.

### Expected Behavior

NX Storybook plugin should process .mdx files with no issues.

### Github Repo

_No response_

### Steps to Reproduce

1. Update to the latest NX
2. Try building a repo with a MDX stories

### Nx Report

```shell
Node : 16.14.0
   OS   : darwin x64
   npm  : 9.3.1
   
   nx : 15.5.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.2
   @nrwl/js : 15.5.2
   @nrwl/linter : 15.5.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.5.2
   @nrwl/web : 15.5.2
   @nrwl/webpack : 15.5.2
   @nrwl/workspace : 15.5.2
   @nrwl/vite : Not Found
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

_No response_

### Additional Information

Root Storybook config:
```
module.exports = {
  staticDirs: [],
  stories: [],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/addon-links',
    'storybook-addon-designs',
  ],
  features: {
    // https://storybook.js.org/docs/react/writing-docs/docs-page#inline-stories-vs-iframe-stories
    inlineStories: true,
    // https://storybook.js.org/docs/html/builders/webpack#code-splitting
    // https://storybook.js.org/docs/react/configure/overview#feature-flags
    storyStoreV7: true,
    emotionAlias: false,
  },
};
```

App Storybook config:
```
const rootMain = require('../../../.storybook/main');

module.exports = {
  ...rootMain,
  core: {
    ...rootMain.core,
    // https://storybook.js.org/docs/html/builders/webpack#webpack-5
    builder: {
      name: 'webpack5',
      options: {
        lazyCompilation: true,
      },
    },
    channelOptions: {
      allowFunction: false,
    },
  },
  stories: [...rootMain.stories, '../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [...rootMain.addons, '@nrwl/react/plugins/storybook'],
  webpackFinal: async (config, { configType }) => {
    // apply any global webpack configs that might have been specified in .storybook/main.js
    if (rootMain.webpackFinal) {
      // eslint-disable-next-line no-param-reassign
      config = await rootMain.webpackFinal(config, { configType });
    }
    // add your own webpack tweaks if needed
    return config;
  },
};
```

Storybook tsconfig:
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "outDir": ""
  },
  "files": [
    "../../../node_modules/@nrwl/react/typings/styled-jsx.d.ts",
    "../../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
    "../../../node_modules/@nrwl/react/typings/image.d.ts"
  ],
  "include": [
    "../src/**/*.stories.ts",
    "../src/**/*.stories.js",
    "../src/**/*.stories.jsx",
    "../src/**/*.stories.tsx",
    "../src/**/*.stories.mdx",
    "*.js"
  ],
  "exclude": ["../**/*.spec.ts", "../**/*.spec.js", "../**/*.spec.tsx", "../**/*.spec.jsx"]
}
```

### PR DESCRIPTION
**Pull request by mandarini**
Keep the rules and extensions.

Fixes #14462

### CODE REVIEW

File: packages/webpack/src/utils/with-nx.ts [hunk 1]
```diff
@@ -164,7 +164,7 @@ export function withNx(opts?: { skipTypeChecking?: boolean }) {
       profile: options.statsJson,
       resolve: {
         ...config.resolve,
-        extensions,
+        extensions: [...extensions, ...config.resolve.extensions],
```
Comment (jaysoo) [inline packages/webpack/src/utils/with-nx.ts:167]: Because of fun JS reasons, this will error out if `config.resolve.extensions` is undefined.

needs to be `[...extensions, ...(config.resolve.extensions || [])]`

**Comment by mandarini** [comment]
Same error even after change :(

**Review by mthines — APPROVED** [review]
Looks good to me.

Shouldn't make much of a difference, but the nullish coalescing operator `??` shouldn't make a difference in this case so I would just have had used the `||`. :)

**Comment by mandarini** [comment]
@mthines it does not seem to solve the issue, unfortunately!

**Comment by mthines** [comment]
> @mthines it does not seem to solve the issue, unfortunately!

@mandarini 

I will investigate the matter myself tomorrow ☺️

**Comment by jaysoo** [comment]
Taking a look

**Comment by jaysoo** [comment]
Updated `docs` option in our schema to be `undefined` by default so Storybook can apply its own defaults (which is `docs: true`).

**Review by jaysoo — APPROVED** [review]
