### PR TITLE
fix(core): fix invalid yarn parser dependencies grouping key

### LINKED ISSUE #15603: findOriginalKeys is not a function or its return value is not iterable
### Current Behavior

After update (have tried most builds ^15.8) most recently tried 15.8.7

```
 nx run star:build:local


 >  NX   findOriginalKeys is not a function or its return value is not iterable


HookWebpackError: findOriginalKeys is not a function or its return value is not iterable
    at makeWebpackError (/Users/jaybell/WebstormProjects/shinkansen/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/jaybell/WebstormProjects/shinkansen/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/Users/jaybell/WebstormProjects/shinkansen/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at fn (/Users/jaybell/WebstormProjects/shinkansen/node_modules/webpack/lib/Compilation.js:480:17)
    at _next0 (eval at create (/Users/jaybell/WebstormProjects/shinkansen/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/Users/jaybell/WebstormProjects/shinkansen/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (/Users/jaybell/WebstormProjects/shinkansen/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/jaybell/WebstormProjects/shinkansen/node_modules/webpack/lib/Compilation.js:502:10
    at Hook.eval [as callAsync] (eval at create (/Users/jaybell/WebstormProjects/shinkansen/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/jaybell/WebstormProjects/shinkansen/node_modules/tapable/lib/Hook.js:18:14)
-- inner error --
TypeError: findOriginalKeys is not a function or its return value is not iterable
    at /Users/jaybell/WebstormProjects/shinkansen/node_modules/nx/src/lock-file/yarn-parser.js:193:41
    at Array.forEach (<anonymous>)
    at mapSnapshots (/Users/jaybell/WebstormProjects/shinkansen/node_modules/nx/src/lock-file/yarn-parser.js:192:26)
    at stringifyYarnLockfile (/Users/jaybell/WebstormProjects/shinkansen/node_modules/nx/src/lock-file/yarn-parser.js:134:23)
    at createLockFile (/Users/jaybell/WebstormProjects/shinkansen/node_modules/nx/src/lock-file/lock-file.js:113:56)
    at /Users/jaybell/WebstormProjects/shinkansen/node_modules/@nrwl/webpack/src/plugins/generate-package-json-plugin.js:42:131
    at fn (/Users/jaybell/WebstormProjects/shinkansen/node_modules/webpack/lib/Compilation.js:478:10)
    at _next0 (eval at create (/Users/jaybell/WebstormProjects/shinkansen/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/Users/jaybell/WebstormProjects/shinkansen/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (/Users/jaybell/WebstormProjects/shinkansen/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target build for project star failed

   Failed tasks:
   
   - star:build:local
   
   Hint: run the command with --verbose for more details.
```

### Expected Behavior

Builds work

### GitHub Repo

_No response_

### Steps to Reproduce

I am not able to create a repro it seems, I am on the newest version now and findOriginalKeys returns undefined. I logged the output at the end of that function and log dependencies and node and got a bunch of logs with actual return results but then theres one last one thats undefined at this node

```
undefined {
  type: 'npm',
  name: 'npm:string_decoder@1.2.0',
  data: {
    version: '1.2.0',
    packageName: 'string_decoder',
    hash: '47ae1adbf6a620c7d3a92813c7c9053f755f67873bbace870412b98e29cdde4e'
  }
}
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.14.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/angular           : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/cypress           : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/express           : 15.8.5
   @nrwl/nest              : 15.8.5
   @nrwl/node              : 15.8.5
   @nrwl/nx-plugin         : 15.8.5
   @nrwl/rollup            : 15.8.5
   @nrwl/storybook         : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/web               : 15.8.5
   @nrwl/webpack           : 15.8.5
   @nrwl/nx-cloud          : 15.2.0
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngneat/spectator           : 14.0.0
   @ngrx/component             : 15.3.0
   @ngrx/component-store       : 15.3.0
   @ngrx/data                  : 15.3.0
   @ngrx/effects               : 15.3.0
   @ngrx/entity                : 15.3.0
   @ngrx/router-store          : 15.3.0
   @ngrx/store                 : 15.3.0
   @ngrx/store-devtools        : 15.3.0
   @nguniversal/builders       : 15.2.0
   @nguniversal/express-engine : 15.2.0
   @testing-library/angular    : 13.1.0
   angular-calendar            : 0.30.1
   apollo-angular              : 4.1.1
   @storybook/angular          : 6.5.16
   ---------------------------------------
   Local workspace plugins:
         @trellis/plugins/apollo-graphql
         @trellis/plugins/nest-graphql
         @trellis/plugins/aws-deploy
         @trellis/plugins/repository
         @trellis/plugins/serverless
         @trellis/plugins/common
         @trellis/plugins/docker
         @trellis/plugins/node
```

### Additional Information

https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1677717333068159

Using yarn (so i have a yarn.lock)

### PR DESCRIPTION
**Pull request by meeroslav**
The yarn parser uses an invalid key for grouping dependencies causing different snapshots to be grouped together.

Reported by @yharaskrik on Slack: https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1677717333068159

## Related Issue(s)

Related to https://github.com/nrwl/nx/pull/15364
Fixes #15603

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204166876602367

### CODE REVIEW

**Comment by yharaskrik** [comment]
Closes: https://github.com/nrwl/nx/issues/15603

File: packages/nx/src/lock-file/yarn-parser.ts [hunk 1]
```diff
@@ -227,7 +227,7 @@ function groupDependencies(
   const resolutionMap = new Map<string, YarnDependency>();
   const snapshotMap = new Map<YarnDependency, Set<string>>();
   Object.entries(dependencies).forEach(([key, snapshot]) => {
-    const resolutionKey = `${snapshot.resolution}${snapshot.integrity}`;
```
Comment (meeroslav) [inline packages/nx/src/lock-file/yarn-parser.ts:230]: This was a typo - grouping is only created for Yarn Classic, which has `resolved`, not for Yarn Berry which has a `resolution` field

**Review by FrozenPandaz — APPROVED** [review]
