### PR TITLE
fix(module-federation): ensure the static remotes env var is used for task hashing #21390

### LINKED ISSUE #21390: Module Federation Dev Server uses env variables to pass data, this breaks caching
### Current Behavior

If I build a module, and then run a federation dev server that uses that module as a static remote, the static remote does not work.

### Expected Behavior

If I build a module, and then run a federation dev server that uses that module as a static remote, the static remote works.

### GitHub Repo

_No response_

### Steps to Reproduce

See above

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : darwin-arm64
   pnpm   : 8.14.3

   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/node           : 17.2.8
   @nx/plugin         : 17.2.8
   @nx/react          : 17.2.8
   @nx/rollup         : 17.2.8
   @nx/storybook      : 17.2.8
   @nx/vite           : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @openadp/tools-plugin : 24.5.0
   @storybook/angular    : 7.6.10
   ---------------------------------------
   Local workspace plugins:
   	 @openadp/tools-plugin
```

### Failure Logs

_No response_

### Package Manager Version

pnpm  8.14.3

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This is the bad code - https://github.com/nrwl/nx/blob/master/packages/react/src/executors/module-federation-dev-server/module-federation-dev-server.impl.ts#L162

Basically env variables are ignored by the nx cache, so building the static remote will pull from cache even if the cached build did not include that env variable.

### PR DESCRIPTION
**Pull request by Coly010**
- fix(react): ensure the static remotes env var is used for task hashing
- fix(angular): ensure the static remotes env var is used for task hashing

## Current Behavior

When a remote is built and served via the `module-federation-dev-server` an env var is used point to a single file server, allowing for increased performance benefits locally.
However, this env var isn't taken into consideration when the task hash is calculated, leading to false positives.

## Expected Behavior

Ensure the env var is added to the executor inputs in target defaults in nx.json. 

## Related Issue(s)

Fixes #21390

### CODE REVIEW

File: packages/angular/src/generators/utils/add-mf-env-to-inputs.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+        inputs: [],
+      },
+    };
+  }
+
+  if (!mfEnvVarExists) {
+    nxJson.targetDefaults[webpackExecutor].inputs.push({ env: mfEnvVar });
+  }
+
+  updateNxJson(tree, nxJson);
```
Comment (leosvelperez) [inline packages/angular/src/generators/utils/add-mf-env-to-inputs.ts:45]: nit: this could be simplified to improve legibility and only write back to `nx.json` if a change was made:
```suggestion
  nxJson.targetDefaults ??= {}
  nxJson.targetDefaults[webpackExecutor] ??= {};
  nxJson.targetDefaults[webpackExecutor].inputs ??= [];

  let mfEnvVarExists = false;
  for (const input of webpackExecutorTargetDefaults.inputs) {
    if (typeof input === 'object' && input['env'] === mfEnvVar) {
      mfEnvVarExists = true;
      break;
    }
  }

  if (!mfEnvVarExists) {
    nxJson.targetDefaults[webpackExecutor].inputs.push({ env: mfEnvVar });
    updateNxJson(tree, nxJson);
  }
```

**Review by leosvelperez — APPROVED** [review]
LGTM, just left a non-blocking suggestion.

File: packages/angular/src/generators/utils/add-mf-env-to-inputs.ts (hunk 1 above)
Comment (Coly010) [reply packages/angular/src/generators/utils/add-mf-env-to-inputs.ts:45]: I like it

File: packages/angular/migrations.json [hunk 2]
```diff
@@ -356,6 +356,12 @@
       },
       "description": "Add 'autoprefixer' as dev dependency when '@nx/angular:ng-packagr-lite' or '@nx/angular:package` is used.",
       "factory": "./src/migrations/update-17-3-0/add-autoprefixer-dependency"
+    },
+    "add-module-federation-env-var-to-target-defaults": {
+      "cli": "nx",
+      "version": "17.8.0-beta.0",
```
Comment (leosvelperez) [inline packages/angular/migrations.json:362]:
```suggestion
      "version": "18.0.0-beta.1",
```

File: packages/angular/src/migrations/update-18-0-0/add-mf-env-var-to-target-defaults.ts [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+  type ProjectConfiguration,
+  joinPathFragments,
+} from '@nx/devkit';
+import { addMfEnvToTargetDefaultInputs } from '../../generators/utils/add-mf-env-to-inputs';
+
+export default async function (tree: Tree) {
+  if (!isWebpackBrowserUsed(tree)) {
+    return;
+  }
+  addMfEnvToTargetDefaultInputs(tree);
```
Comment (leosvelperez) [inline packages/angular/src/migrations/update-18-0-0/add-mf-env-var-to-target-defaults.ts:13]: Let's format files at the end.

**Review by jaysoo — APPROVED** [review]
