### PR TITLE
fix(angular): use jasmine-marbles 0.9.1 for rxjs7

### LINKED ISSUE #8060: jasmine-marbles 0.9.x is required for RxJS 7+
## Current Behavior
Tests for @ngrx/effects are failed

## Expected Behavior
No tests failed

## Steps to Reproduce
Run @ngrx/effects tests

### Failure Logs
```
    Expected: -a-|,
    Received: -?-|,
        
    Expected:
        [{"frame":10,"notification":{"kind":"N","value":{"error":"places error","type":"[places] getPlaces: Failure"}}},{"frame":30,"notification":{"kind":"C"}}]
        
    Received:
        [{"frame":10,"notification":{"kind":"N","value":{"error":"places error","type":"[places] getPlaces: Failure"},"hasValue":true}},{"frame":30,"notification":{"kind":"C","hasValue":false}}],
  138 |
  139 |     afterEach(() => {
> 140 |       expect(effects.getPlaces$).toBeObservable(expected);
      |                                  ^
  141 |     });
```

### Environment
```
  Node : 14.17.4
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : 13.2.4
  @nrwl/angular : 13.2.4
  @nrwl/cli : 13.2.4
  @nrwl/cypress : 13.2.4
  @nrwl/devkit : 13.2.4
  @nrwl/eslint-plugin-nx : 13.2.4
  @nrwl/express : undefined
  @nrwl/jest : 13.2.4
  @nrwl/linter : 13.2.4
  @nrwl/nest : 13.2.4
  @nrwl/next : undefined
  @nrwl/node : 13.2.4
  @nrwl/nx-cloud : 13.0.0
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.4
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.4
  @nrwl/storybook : 13.2.4
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular-architects/module-federation: 12.4.1
         @angular/animations: 13.0.3
         @angular/cdk: 13.0.3
         @angular/common: 13.0.3
         @angular/compiler: 13.0.3
         @angular/core: 13.0.3
         @angular/elements: 13.0.3
         @angular/forms: 13.0.3
         @angular/material: 13.0.3
         @angular/platform-browser: 13.0.3
         @angular/platform-browser-dynamic: 13.0.3
         @angular/router: 13.0.3
         @ngrx/effects: 13.0.2
         @ngrx/entity: 13.0.2
         @ngrx/router-store: 13.0.2
         @ngrx/store: 13.0.2
         @ngrx/store-devtools: 13.0.2
         ngx-build-plus: 13.0.1
         @angular-devkit/build-angular: 13.0.4
         @angular/cli: 13.0.4
         @angular/compiler-cli: 13.0.3
         @angular/language-service: 13.0.3
         @ngrx/schematics: 13.0.2
         eslint-plugin-ngrx: 1.34.0
```

### PR DESCRIPTION
**Pull request by ApplY3D**
## Current Behavior
Tests for @ngrx/effects are fail:
```
    Expected: -a-|,
    Received: -?-|,
        
    Expected:
        [{"frame":10,"notification":{"kind":"N","value":{"error":"places error","type":"[places] getPlaces: Failure"}}},{"frame":30,"notification":{"kind":"C"}}]
        
    Received:
        [{"frame":10,"notification":{"kind":"N","value":{"error":"places error","type":"[places] getPlaces: Failure"},"hasValue":true}},{"frame":30,"notification":{"kind":"C","hasValue":false}}],
  138 |
  139 |     afterEach(() => {
> 140 |       expect(effects.getPlaces$).toBeObservable(expected);
      |                                  ^
  141 |     });
```

## Expected Behavior
No tests failed

## Related Issue(s)

Fixes #8060

### CODE REVIEW

File: packages/angular/src/migrations/update-13-2-0/update-testing-imports.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ export default async function (tree: Tree) {
       tree,
       {},
       {
-        'jasmine-marbles': '~0.8.3',
+        'jasmine-marbles': '~0.9.1',
```
Comment (AgentEnder) [inline packages/angular/src/migrations/update-13-2-0/update-testing-imports.ts:42]: jasmine-marbles should only be bumped to 0.9.1 for workspaces with RxJS 7. Since Angular doesn't force this, the migration should check the version of RxJS 7 before bumping from 0.8.x to 0.9.x.

File: packages/angular/migrations.json [hunk 2]
```diff
@@ -957,6 +957,10 @@
     "13.2.0": {
       "version": "13.2.0-beta.1",
       "packages": {
+        "jasmine-marbles": {
```
Comment (AgentEnder) [inline packages/angular/migrations.json:960]: This kind of update doesn't support dynamically determined versions which are reequired for jasmine-marbles since its version will be determined on the presence of RxJS 6 or 7. See the comment on the migration file.

**Review by AgentEnder — CHANGES_REQUESTED** [review]

**Review by Coly010 — APPROVED** [review]
LGTM

**Review by AgentEnder — APPROVED** [review]
