### PR TITLE
fix(core): handle .nxignore properly for the native hasher

### LINKED ISSUE #15377: 15.8.1-3: .nxignore not respected in native hasher
### Current Behavior

folder in .nxignore doesn't excludes deps referenced in folder

### Expected Behavior

folder in .nxignore excludes deps referenced in folder

### GitHub Repo

_No response_

### Steps to Reproduce

exclude a folder in a project, which is not part of the source-code for the project (I have a test folder...). When using nx graph you can se the deps are included anyways. This worked in 15.7.2...

### Nx Report

```shell
Node : 18.14.2
   OS   : win32 x64
   yarn : 4.0.0-rc.39

   nx                      : 15.8.1
   @nrwl/js                : 15.8.1
   @nrwl/jest              : 15.8.1
   @nrwl/linter            : 15.8.1
   @nrwl/workspace         : 15.8.1
   @nrwl/angular           : 15.8.1
   @nrwl/cli               : 15.8.1
   @nrwl/cypress           : 15.8.1
   @nrwl/devkit            : 15.8.1
   @nrwl/esbuild           : 15.8.1
   @nrwl/eslint-plugin-nx  : 15.8.1
   @nrwl/tao               : 15.8.1
   @nrwl/webpack           : 15.8.1
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/component       : 15.3.0
   @ngrx/component-store : 15.3.0
   angular-calendar      : 0.31.0
```

### Additional Information

I have a workspace with client and server side code, and use esbuild to bundle functions for firebase. As of release 15.8, the esbuild executor adds all dependencies from the root/workspace package.json to the server side functions bundle... But I can now see this is due to .nxignore not being respected as before, it also shows up in via nx grapch...

### PR DESCRIPTION
**Pull request by Cammisuli**
## Current Behavior

Currently the native hasher only uses the first line of the .nxignore file, thus missing the rest of the ignores

## Expected Behavior
The .nxignore file should be read entirely and all contents should be handled

## Related Issue(s)

Fixes #15377

### CODE REVIEW

File: packages/nx/src/native/native_hasher.rs [hunk 1]
```diff
@@ -28,25 +28,25 @@ fn hash_file(file: String) -> Option<FileData> {
 
 #[napi]
 fn hash_files(workspace_root: String) -> HashMap<String, String> {
-    let mut walker = WalkBuilder::new(&workspace_root);
     let workspace_root = Path::new(&workspace_root);
-    walker.add_ignore(workspace_root.join(".nxignore"));
```
Comment (Cammisuli) [inline packages/nx/src/native/native_hasher.rs:33]: For some reason, the `add_ignore` here only used the first item in the ignore file 🤨

**Review by FrozenPandaz — APPROVED** [review]
