### PR TITLE
fix(angular): throw error when no parent module found

### LINKED ISSUE #16689: Cannot read properties of null (reading 'replace') when genering component for app/lib created with standalone option for components
### Current Behavior

`nx generate component wrapper --project ang-app --verbose --dry-run`
✔ Which generator would you like to use? · @nrwl/angular:component

>  NX  Generating @nrwl/angular:component

 >  NX   Cannot read properties of null (reading 'replace')

```
TypeError: Cannot read properties of null (reading 'replace')
    at removeWindowsDriveLetter (/home/user/code/nx-examples/node_modules/nx/src/utils/path.js:6:27)
    at normalizePath (/home/user/code/nx-examples/node_modules/nx/src/utils/path.js:12:12)
    at findModuleFromOptions (/home/user/code/nx-examples/node_modules/@nrwl/angular/src/generators/component/lib/module.js:14:43)
    at /home/user/code/nx-examples/node_modules/@nrwl/angular/src/generators/component/component.js:59:67
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/code/nx-examples/node_modules/tslib/tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

### Expected Behavior

`nx generate component wrapper --project ang-app2 --verbose --dry-run`
✔ Which generator would you like to use? · @nrwl/angular:component

>  NX  Generating @nrwl/angular:component

```
CREATE apps/ang-app2/src/app/wrapper/wrapper.component.css
CREATE apps/ang-app2/src/app/wrapper/wrapper.component.html
CREATE apps/ang-app2/src/app/wrapper/wrapper.component.spec.ts
CREATE apps/ang-app2/src/app/wrapper/wrapper.component.ts
UPDATE apps/ang-app2/src/app/app.module.ts

NOTE: The "dryRun" flag means no changes were made.

```

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. `nx generate app ang-app-with-standalone`
2. `? Would you like to use Standalone Components?`: Yes
3. `nx generate component wrapper --project ang-app-with-standalone --verbose --dry-run`

### Nx Report

```shell
nx report
/bin/sh: 1: yarn: not found
nx report

Reports useful version numbers to copy into the Nx issue template

Options:
  --help     Show help                                                                               [boolean]
  --version  Show version number                                                                     [boolean]

Error: Command failed: yarn --version
/bin/sh: 1: yarn: not found
```

### Failure Logs

```shell
>  NX   Cannot read properties of null (reading 'replace')


TypeError: Cannot read properties of null (reading 'replace')
    at removeWindowsDriveLetter (/home/user/code/nx-examples/node_modules/nx/src/utils/path.js:6:27)
    at normalizePath (/home/user/code/nx-examples/node_modules/nx/src/utils/path.js:12:12)
    at findModuleFromOptions (/home/user/code/nx-examples/node_modules/@nrwl/angular/src/generators/component/lib/module.js:14:43)
    at /home/user/code/nx-examples/node_modules/@nrwl/angular/src/generators/component/component.js:59:67
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/code/nx-examples/node_modules/tslib/tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Additional Information

https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/utility/find-module.ts#L29
iiuc you don't have to look for the module when creating standalone components

_No response_

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

When there are no parent modules to add a component to, the generator fails with a cryptic error.

## Expected Behavior

We should throw a better when a parent module cannot be found

## Related Issue(s)

Fixes #16689

### CODE REVIEW

**Review by leosvelperez — APPROVED** [review]

File: packages/angular/src/generators/component/lib/module.ts [hunk 1]
```diff
@@ -80,5 +80,7 @@ function findModule(
     dir = dirname(dir);
   }
 
-  return null;
+  throw new Error(
+    "Could not find a candidate module to add the component to. Please specify which module the component should be added to by using the '--module' option."
+  );
```
Comment (AgentEnder) [inline packages/angular/src/generators/component/lib/module.ts:85]: @Coly010 do you think we should tune this to also mention `--standalone`? Something like: 

```suggestion
  throw new Error(
    "Could not find a candidate module to add the component to. Please specify which module the component should be added to by using the '--module' option, or pass '--standalone' to use Angular's standalone API"
  );
```

Comment (Coly010) [reply packages/angular/src/generators/component/lib/module.ts:85]: yes that might make sense
