### PR TITLE
fix(nest): fixing resource generator options issue

### LINKED ISSUE #8243: Incorrect generation of nestjs resource when using other than rest API type
## Current Behavior

When I run the command `nx g @nrwl/nest:resource tenants --project apis-admin-api --type=graphql-code-first --crud`, Nx generates a Nest module with a REST API Controller, instead of a GraphQL Resolver.

## Expected Behavior

I expected that the command `nx g @nrwl/nest:resource tenants --project apis-admin-api --type=graphql-code-first --crud` would generates a `NestJS resource` using GraphQL API

I don't know if this is a regression.

## Steps to Reproduce

The steps I followed are pretty simple:

```bash
> yarn create nx-workspace samplenx --preset=ts --nx-cloud=false --packageManager=yarn
yarn create v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-nx-workspace@13.3.11" with binaries:
      - create-nx-workspace

>  NX  Nx is creating your v13.3.11 workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "yarn install" several times. Please wait.

✔ Installing dependencies with yarn
✔ Nx has successfully created the workspace.

———————————————————————————————————————————————


>  NX   NOTE  First time using Nx? Check out this interactive Nx tutorial.

  https://nx.dev/getting-started/nx-core

Done in 33.89s.

> cd samplenx

> yarn add -D @nrwl/nest
yarn add v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 82 new dependencies.
Done in 8.29s.

> nx g @nrwl/nest:app admin-api --directory apis
UPDATE nx.json
CREATE jest.config.js
CREATE jest.preset.js
UPDATE package.json
UPDATE .vscode/extensions.json
CREATE packages/apis/admin-api/src/app/.gitkeep
CREATE packages/apis/admin-api/src/assets/.gitkeep
CREATE packages/apis/admin-api/src/environments/environment.prod.ts
CREATE packages/apis/admin-api/src/environments/environment.ts
CREATE packages/apis/admin-api/src/main.ts
CREATE packages/apis/admin-api/tsconfig.app.json
CREATE packages/apis/admin-api/tsconfig.json
CREATE packages/apis/admin-api/project.json
UPDATE workspace.json
CREATE .eslintrc.json
CREATE packages/apis/admin-api/jest.config.js
CREATE packages/apis/admin-api/tsconfig.spec.json
CREATE packages/apis/admin-api/src/app/app.controller.spec.ts
CREATE packages/apis/admin-api/src/app/app.controller.ts
CREATE packages/apis/admin-api/src/app/app.module.ts
CREATE packages/apis/admin-api/src/app/app.service.spec.ts
CREATE packages/apis/admin-api/src/app/app.service.ts
yarn install v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 27.73s.
```

Up to here, everything is working fine, the problem arise with the following command:

```bash
> nx g @nrwl/nest:resource tenants --project apis-admin-api --type=graphql-code-first --crud
CREATE packages/apis/admin-api/src/tenants/tenants.controller.spec.ts
CREATE packages/apis/admin-api/src/tenants/tenants.controller.ts
CREATE packages/apis/admin-api/src/tenants/tenants.module.ts
CREATE packages/apis/admin-api/src/tenants/tenants.service.spec.ts
CREATE packages/apis/admin-api/src/tenants/tenants.service.ts
CREATE packages/apis/admin-api/src/tenants/dto/create-tenant.dto.ts
CREATE packages/apis/admin-api/src/tenants/dto/update-tenant.dto.ts
CREATE packages/apis/admin-api/src/tenants/entities/tenant.entity.ts
UPDATE package.json
```

As you can see, it generates a controller instead of a resolver, and in the `package.json` file it does not add the required packages.

I also tried the `@nestjs/schematics:resource` generator, and in this case the result were more aligned with the expected one:

```bash
> nx g @nestjs/schematics:resource tenants --project apis-admin-api --type=graphql-code-first --crud
CREATE src/tenants/tenants.module.ts
CREATE src/tenants/tenants.resolver.spec.ts
CREATE src/tenants/tenants.resolver.ts
CREATE src/tenants/tenants.service.spec.ts
CREATE src/tenants/tenants.service.ts
CREATE src/tenants/dto/create-tenant.input.ts
CREATE src/tenants/dto/update-tenant.input.ts
CREATE src/tenants/entities/tenant.entity.ts
```

But this plugin seems to be more like an intermediary tool, because:

* It does not respect the target project, and generates directly at `src`
* It does not install the required packages `@nestjs/graphql graphql@^15 apollo-server-express` on `package.json`
* It does not integrate the generated module into app.module.ts like the nest generator does (the `rest` API option doesn't do it either)

I'm using Windows 11 / Powershell but it should be reproducible in Linux/MacOS too.

### Failure Logs
There were no failures, just incorrect generator output.

### Environment

```bash
>  NX  Report complete - copy this into the issue template

  Node : 16.13.1
  OS   : win32 x64
  yarn : 1.22.15

  nx : 13.3.11
  @nrwl/angular : undefined
  @nrwl/cli : 13.3.11
  @nrwl/cypress : undefined
  @nrwl/devkit : 13.3.11
  @nrwl/eslint-plugin-nx : 13.3.11
  @nrwl/express : undefined
  @nrwl/jest : 13.3.11
  @nrwl/linter : 13.3.11
  @nrwl/nest : 13.3.11
  @nrwl/next : undefined
  @nrwl/node : 13.3.11
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.11
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.11
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @nrwl/js: 13.3.11

(node:12776) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\iskan\dev\samples\samplenx\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

### PR DESCRIPTION
**Pull request by ashley-hunter**
The normalize options function was excluding some important properties such as type causing the generated files not to match the output if it was run using the Nest schematic directly

ISSUES CLOSED: #8243

## Current Behavior

Running `nx g @nrwl/nest:resource tenants --project apis-admin-api --type=graphql-code-first --crud` generates REST files rather than GraphQL files.

This is due to some options not being forwarded to the Nest schematics correctly.

## Expected Behavior

Options should not be removed unintentionally.

## Related Issue(s)

Fixes #8243

### CODE REVIEW

File: packages/nest/src/generators/resource/resource.ts [hunk 1]
```diff
@@ -32,6 +32,7 @@ function normalizeResourceOptions(
   options: ResourceGeneratorOptions
 ): NormalizedOptions {
   return {
+    ...options,
```
Comment (FrozenPandaz) [inline packages/nest/src/generators/resource/resource.ts:35]: Thank you, can you please make this change in the util instead so that all of the generators are fixed?

Comment (ashley-hunter) [reply packages/nest/src/generators/resource/resource.ts]: Good suggestion, I have made the changes. Thank you!

**Review by FrozenPandaz — APPROVED** [review]
Thank you for your contribution and making the changes. This LGTM 🎉
