### PR TITLE
fix(core): handle undefined when package.json changes are not in node modules

### LINKED ISSUE #13668: TypeError: Cannot read properties of undefined (reading 'name') when running nx affected
### Current Behavior

Running into an error when running `nx affected` because the resulting `undefined` returned by an `[].find()` isn't handled.

image

### Expected Behavior

No error, undefined is handled.

### Github Repo

https://github.com/jericopingul/nx-affected-issue

### Steps to Reproduce

1. Clone the project linked
2. Checkout [this PR branch](https://github.com/jericopingul/nx-affected-issue/pull/1) with `git checkout test`
3. Run `pnpm i` and then `pnpm nx affected --target=lint`

### Nx Report

```shell
pnpm nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   pnpm : 7.14.0
   
   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
TypeError: Cannot read properties of undefined (reading 'name')
    at getTouchedNpmPackages (/Users/jericopingul/projects/nx-affected-issue/node_modules/.pnpm/nx@15.3.0/node_modules/nx/src/project-graph/affected/locators/npm-packages.js:24:41)
    at /Users/jericopingul/projects/nx-affected-issue/node_modules/.pnpm/nx@15.3.0/node_modules/nx/src/project-graph/affected/affected-project-graph.js:31:27
    at Array.reduce (<anonymous>)
    at filterAffected (/Users/jericopingul/projects/nx-affected-issue/node_modules/.pnpm/nx@15.3.0/node_modules/nx/src/project-graph/affected/affected-project-graph.js:30:52)
    at projectsToRun (/Users/jericopingul/projects/nx-affected-issue/node_modules/.pnpm/nx@15.3.0/node_modules/nx/src/command-line/affected.js:100:55)
    at Object.<anonymous> (/Users/jericopingul/projects/nx-affected-issue/node_modules/.pnpm/nx@15.3.0/node_modules/nx/src/command-line/affected.js:29:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jericopingul/projects/nx-affected-issue/node_modules/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {stack: 'TypeError: Cannot read properties of undefine…ions (node:internal/process/task_queues:96:5)', message: 'Cannot read properties of undefined (reading 'name')'}
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jericolp**
ISSUES CLOSED: #13668

## Current Behavior
`nx affected` fails with error

## Expected Behavior
`nx affected` does not fail with error

## Related Issue(s)

Fixes https://github.com/nrwl/nx/issues/13668

### CODE REVIEW

**Review by giveerr — APPROVED** [review]
solves the problem

File: packages/nx/src/project-graph/affected/locators/npm-packages.ts [hunk 1]
```diff
@@ -31,6 +31,7 @@ export const getTouchedNpmPackages: TouchedProjectLocator<
         const npmPackage = npmPackages.find(
           (pkg) => pkg.data.packageName === c.path[1]
         );
+        if (!npmPackage) continue;
```
Comment (FrozenPandaz) [inline packages/nx/src/project-graph/affected/locators/npm-packages.ts:34]: This shouldn't happen. All packages should be found here. Every change  to `package.json#dependencies`  and `package.json#devDependencies` should cause a project to be touched.

But throwing an error might be too extreme.

Let's print a warning instead.
1. Let's only print 1 warning for this whole process though (so we don't get a warning for each package that wasn't found.)
2. The warning should include the packages that weren't found.
3. The warning should tell the user to open an issue in Github including the `package.json` file.  

This way people can still run `affected` but we can identify cases we haven't handled and fix them.

cc @meeroslav

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
Thank you for your contribution!

Please show a warning in these cases so we can identify which cases weren't handle.

File: packages/nx/src/project-graph/affected/locators/npm-packages.ts (hunk 1 above)
Comment (jericopingul) [reply packages/nx/src/project-graph/affected/locators/npm-packages.ts]: Thanks for taking the time to review this @FrozenPandaz and for the suggestions.

> This shouldn't happen. All packages should be found here.

To give context as to how this happened to my project. A new workspace project (with a package.json that was intended to be published to a registry) was created and is used within the existing `nx` workspace that already is using `affected`. The new workspace project was then added in the workspace as a pnpm `workspace:*` dependency.

I have made the suggested changes, do let me know if there is anything I didn't capture in the last commit https://github.com/nrwl/nx/pull/13681/commits/221fb6635623587f81e7ded34b7d631ca0ec057d

Comment (meeroslav) [reply packages/nx/src/project-graph/affected/locators/npm-packages.ts]: This issue should not be hidden under the carpet. The problem is that we are expecting a workspace project to exist in the `externalNodes` but it does not. It used to, though, since previously we didn't parse lock files so everything in the `package.json` dependencies block was treated as an external dependency.

Instead, if the package is not found, we need to check `projectGraph.nodes` if it can be found there.

Having a fallback with a warning is fine, but let's exhaust all the possibilities first.

Comment (meeroslav) [reply packages/nx/src/project-graph/affected/locators/npm-packages.ts]: I believe this is the correct way to fix it: https://github.com/nrwl/nx/pull/13728

@FrozenPandaz do you think we should still keep this fallback? I guess this can easily happen when the lock file (install has not been run) or file system (dependency does not match the workspace project name) and package.json are not in sync.

**Review by meeroslav — APPROVED** [review]

**Review by FrozenPandaz — APPROVED** [review]
