### PR TITLE
fix(core): delete project from root jest config when running remove command

### LINKED ISSUE #4192: Jest config do not get update when lib or app is deleted by remove schematic
## Current Behavior
When lib or app is deleted by remove schematic the root level **jest.config.js**  is not updated by removing the entry of deleted project. I have to manually delete the entry from this file.

`yarn nx generate remove <lib-name>`

## Expected Behavior

**jest.config.js**  need to automatically update by deleting the entry of deleted project

## Steps to Reproduce

**Step 1:**  Create new lib with below command

`yarn nx g @nrwl/node:library <lib-name> `

**Step 2:**  Check root level **jest.config.js** for entry of newly created lib as result of **Step 1**

**Step 3:**  Delete lib created in **Step 1** by below command

`yarn nx generate remove <lib-name>`

**Step 4:**  Check root level **jest.config.js** again the entry of newly created lib as result of **Step 1** is still there

### Environment

**Note:** nx is shown as not found below because as i did not installed nx globally

`  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 10.3.0
  @nrwl/eslint-plugin-nx : 10.3.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.0
  @nrwl/linter : 10.3.0
  @nrwl/nest : Not Found
  @nrwl/next : 10.3.0
  @nrwl/node : 10.3.0
  @nrwl/react : 10.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.0
  @nrwl/web : 10.3.0
  @nrwl/workspace : 10.3.0
  typescript : 4.0.3`

### PR DESCRIPTION
**Pull request by mehrad-rafigh**
ISSUES CLOSED: #4192

## Fixes 
#4192

### CODE REVIEW

**Comment by etkachev** [comment]
I already added a comment on the original [issue](https://github.com/nrwl/nx/issues/4192), but wanted to comment here as well. Wasn't sure if we wanted to take care of the `move` schematic in this same PR?

**Comment by mehrad-rafigh** [comment]
@suwigyarathore sure can change that tonight

File: packages/workspace/src/schematics/remove/lib/update-root-jest-config.ts [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+ * @param schema The options provided to the schematic
+ */
+export function updateRootJestConfig(schema) {
+  return (tree: Tree, _context: SchematicContext): Observable<Tree> => {
+    return from(getWorkspace(tree)).pipe(
+      map((_) => {
+        const projectToRemove = schema.projectName;
+
+        if (!tree.exists('jest.config.js')) {
+          throw new SchematicsException('Root jest.config.js not found');
```
Comment (vsavkin) [inline packages/workspace/src/schematics/remove/lib/update-root-jest-config.ts:24]: Could we just exit instead of throwing? There might be workspace without the root config or where the root config is named differently.

Comment (suwigyarathore) [reply packages/workspace/src/schematics/remove/lib/update-root-jest-config.ts:24]: agree

Comment (mehrad-rafigh) [reply packages/workspace/src/schematics/remove/lib/update-root-jest-config.ts:24]: @vsavkin Of course. I will change this tonight

Comment (mehrad-rafigh) [reply packages/workspace/src/schematics/remove/lib/update-root-jest-config.ts]: @vsavkin Should a warning be displayed if the jest config file could not be found?

**Comment by vsavkin** [comment]
Thank you!

**Comment by mehrad-rafigh** [comment]
My pleasure
