### PR TITLE
fix(angular): license-webpack-plugin should not scan root package.json #27989

### LINKED ISSUE #27989: NX MF build failing with ENOENT: no such file or directory, scandir ''
### Current Behavior

Creating vanilla workspace in version 19.7.4 adding MF Angular host application and doing production build leads into error -> **ENOENT: no such file or directory, scandir ''** and there is no **"dist"** directory created.

Commands I'm running:
npx create-nx-workspace@latest my-workspace10
npm install --save-dev @nx/angular
npx nx g @nx/angular:host host
npx nx build host

It was working before. I reproduced those commands using version 18.3.1 and it works. 
Same behavior was observed on another 2 windows machines (I asked colleagues to try).

### Expected Behavior

Build should be successful and **"dist"** folder should be created with bundles.

### GitHub Repo

_No response_

### Steps to Reproduce

1, npx create-nx-workspace@latest my-workspace10
image

2, npm install --save-dev @nx/angular

3, npx nx g @nx/angular:host host
image

4, npx nx build host

### Nx Report

```shell
Node           : 22.8.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.3

nx                 : 19.7.4
@nx/js             : 19.7.4
@nx/jest           : 19.7.4
@nx/linter         : 19.7.4
@nx/eslint         : 19.7.4
@nx/workspace      : 19.7.4
@nx/angular        : 19.7.4
@nx/devkit         : 19.7.4
@nx/eslint-plugin  : 19.7.4
@nrwl/tao          : 19.7.4
@nx/web            : 19.7.4
@nx/webpack        : 19.7.4
typescript         : 5.5.4
```

### Failure Logs

```shell
(node:16064) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
- Generating browser application bundles (phase: setup)...
    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browserslist configuration. For more information, see https://angular.dev/tools/cli/build#configuring-browser-compatibility
    NOTE: You can set the "target" to "ES2022" in the project's tsconfig to remove this warning.
(node:12672) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
[ Module Federation Manifest Plugin ]: Manifest will use absolute path resolution via its host at runtime, reason: publicPath='auto'
    [webpack.cache.PackFileCacheStrategy] No pack exists at C:\Projects\nx\my-workspace10\.angular\cache\18.2.5\angular-webpack\17fb4e93c23199c6209d45f0039415bbd2a3f2a0.pack: Error: ENOENT: no such file or directory, stat 'C:\Projects\nx\my-workspace10\.angular\cache\18.2.5\angular-webpack\17fb4e93c23199c6209d45f0039415bbd2a3f2a0\index.pack'
<t> [webpack.cache.PackFileCacheStrategy] restore cache container: 8.0331 ms
    [IdleFileCachePlugin] Initial cache was generated and cache will be persisted in 5s.
✔ Browser application bundle generation complete.
 NX   ENOENT: no such file or directory, scandir ''
HookWebpackError: ENOENT: no such file or directory, scandir ''
    at makeWebpackError (C:\Projects\nx\my-workspace10\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at C:\Projects\nx\my-workspace10\node_modules\webpack\lib\Compilation.js:3204:12
    at eval (eval at create (C:\Projects\nx\my-workspace10\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
    at fn (C:\Projects\nx\my-workspace10\node_modules\webpack\lib\Compilation.js:493:17)
    at _next6 (eval at create (C:\Projects\nx\my-workspace10\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:28:1)
    at eval (eval at create (C:\Projects\nx\my-workspace10\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:46:1)
    at fn (C:\Projects\nx\my-workspace10\node_modules\webpack\lib\Compilation.js:505:9)
    at _next5 (eval at create (C:\Projects\nx\my-workspace10\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
    at eval (eval at create (C:\Projects\nx\my-workspace10\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:60:1)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
-- inner error --
Error: ENOENT: no such file or directory, scandir ''
    at Object.readdirSync (node:fs:1502:26)
    at CacheBackend.provideSync (C:\Projects\nx\my-workspace10\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:332:58)
    at WebpackFileSystem.listPaths (C:\Projects\nx\my-workspace10\node_modules\license-webpack-plugin\dist\WebpackFileSystem.js:78:24)
    at LicenseTextReader.readLicense (C:\Projects\nx\my-workspace10\node_modules\license-webpack-plugin\dist\LicenseTextReader.js:37:54)
    at PluginChunkReadHandler.processModule (C:\Projects\nx\my-workspace10\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:71:62)
    at C:\Projects\nx\my-workspace10\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:24:27
    at WebpackInnerModuleIterator.internalCallback (C:\Projects\nx\my-workspace10\node_modules\license-webpack-plugin\dist\WebpackInnerModuleIterator.js:39:13)
    at WebpackInnerModuleIterator.iterateModules (C:\Projects\nx\my-workspace10\node_modules\license-webpack-plugin\dist\WebpackInnerModuleIterator.js:21:9)
    at C:\Projects\nx\my-workspace10\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:20:39
    at WebpackChunkModuleIterator.iterateModules (C:\Projects\nx\my-workspace10\node_modules\license-webpack-plugin\dist\WebpackChunkModuleIterator.js:42:21)
    at PluginChunkReadHandler.processChunk (C:\Projects\nx\my-workspace10\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:19:29)
    at _loop_1 (C:\Projects\nx\my-workspace10\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:135:37)
    at WebpackCompilerHandler.iterateChunks (C:\Projects\nx\my-workspace10\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:160:17)
    at C:\Projects\nx\my-workspace10\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:50:31
    at fn (C:\Projects\nx\my-workspace10\node_modules\webpack\lib\Compilation.js:491:10)
    at _next6 (eval at create (C:\Projects\nx\my-workspace10\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:28:1)
    at eval (eval at create (C:\Projects\nx\my-workspace10\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:46:1)
    at fn (C:\Projects\nx\my-workspace10\node_modules\webpack\lib\Compilation.js:505:9)
    at _next5 (eval at create (C:\Projects\nx\my-workspace10\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
    at eval (eval at create (C:\Projects\nx\my-workspace10\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:60:1)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

### Package Manager Version

npm version 10.8.3

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Exactly same steps repeated for nx version 18.3.1 works.

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

The `license-webpack-plugin` is trying to scan the root package.json on windows, resulting in an error.

## Expected Behavior

Patch the `license-webpack-plugin` to prevent it from scanning the root package.json. A similar fix was needed for rspack.

## Related Issue(s)

Fixes #27989

### CODE REVIEW

File: packages/angular/src/builders/utilities/webpack.ts [hunk 1]
```diff
@@ -22,11 +23,44 @@ export async function mergeCustomWebpackConfig(
...
+      'package.json'
+    );
+    if (existsSync(pathToRootPackageJson)) {
+      try {
+        const rootPackageJson = JSON.parse(
+          readFileSync(pathToRootPackageJson, 'utf-8')
+        );
+        rootPackageJsonName = rootPackageJson.name;
+        licensePlugin.pluginOptions.excludedPackageTest = (pkgName: string) => {
+          if (!rootPackageJsonName) {
```
Comment (jaysoo) [inline packages/angular/src/builders/utilities/webpack.ts:52]: In the case where the root `package.json` does not contain `name`, then this error could still happen?

Comment (Coly010) [reply packages/angular/src/builders/utilities/webpack.ts:52]: If someone runs into this and doesn't have a name in the package.json, we can suggest they set one

**Review by jaysoo — APPROVED** [review]
