### PR TITLE
fix(core): move generator should respect non-relative extends parts

### LINKED ISSUE #6314: Workspace Move generator modifies library .eslintrc.json
## Current Behavior
Using the workspace:move generator to move a react library modifes the library's .eslintrc.json which results in the line
`"extends": ["plugin:@nrwl/nx/react", "../../../../.eslintrc.json"],`
turning into
`"extends": "../../../../.eslintrc.json",`
which results into eslint errors

## Expected Behavior
The .eslintrc.json should not be modified

## Steps to Reproduce
* use react workspace generator to create a library
* use workspace:move generator to move the library

### Environment
Node : 12.14.1
OS : darwin x64
npm : 6.14.11

nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 12.5.7
@nrwl/cypress : 12.5.7
@nrwl/devkit : 12.5.7
@nrwl/eslint-plugin-nx : 12.5.7
@nrwl/express : Not Found
@nrwl/jest : 12.5.7
@nrwl/linter : 12.5.7
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/react : 12.5.7
@nrwl/schematics : Not Found
@nrwl/tao : 12.5.7
@nrwl/web : 12.5.7
@nrwl/workspace : 12.5.7
@nrwl/storybook : 12.5.7
@nrwl/gatsby : Not Found
typescript : 4.1.4

### PR DESCRIPTION
**Pull request by meeroslav**
## Current Behavior
Move generator expects `.eslintrc.json` `extends` to be equal `../../.eslintrc.json` and ignores:
- extends being an array
- extends pointing to a different relative path

## Expected Behavior
Move generator expects `.eslintrc.json` should support both `string` and `string[]` as a valid `extends` value and recalculate new path based on the actual extends segments without assuming the content.

## Related Issue(s)
https://github.com/nrwl/nx/issues/6314

Fixes #6314

### CODE REVIEW

File: packages/workspace/src/generators/move/lib/update-eslintrc-json.ts [hunk 1]
```diff
@@ -16,10 +16,23 @@ interface PartialEsLintrcOverride {
...
+  extends: string | string[];
   overrides?: PartialEsLintrcOverride[];
 }
 
+function offsetFilePath(
+  project: ProjectConfiguration,
+  pathToFile: string,
+  offset: string
+): string {
+  if (!pathToFile.startsWith('..')) {
```
Comment (FrozenPandaz) [inline packages/workspace/src/generators/move/lib/update-eslintrc-json.ts:28]: This should probably handle `./.eslintrc-base` or something where the extension starts with `./`

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/workspace/src/generators/move/lib/update-eslintrc-json.ts (hunk 1 above)
Comment (meeroslav) [reply packages/workspace/src/generators/move/lib/update-eslintrc-json.ts:28]: Perhaps the comment is misleading, but in reality `./something.ext` points to the same folder so there is nothing that should be changed. The only change needed is with `../../../path/outside/of/project`. The unit test covers this scenario.

Comment (FrozenPandaz) [reply packages/workspace/src/generators/move/lib/update-eslintrc-json.ts:28]: Ah yes, of course :facepalm:
