### PR TITLE
docs(misc): fix link to edit page

### LINKED ISSUE #17544: outdated doc: wrong links and sample values
### Documentation issue

* currently nx suggests org instead of myorg
image

* and the links to edit this file is not working
image

https://nx.dev/core-tutorial/01-create-blog

### PR DESCRIPTION
**Pull request by mandarini**
## Current Behavior

"Edit this page" link sends you here: https://github.com/nrwl/nx/blob/master/public/documentation/shared/core-tutorial/01-create-blog.md -> `https://github.com/nrwl/nx/blob/master/public/documentation/---`

example: https://nx.dev/core-tutorial/01-create-blog

## Expected Behavior

"Edit this page" link should send you here: https://github.com/nrwl/nx/blob/master/docs/shared/core-tutorial/01-create-blog.md -> `https://github.com/nrwl/nx/blob/master/docs/---`

## Related Issue(s)

Fixes #17544

### CODE REVIEW

**Review by isaacplmann — APPROVED** [review]
Looks good to me, but @bcabanes should double check

File: nx-dev/feature-doc-viewer/src/lib/doc-viewer.tsx [hunk 1]
```diff
@@ -140,10 +140,9 @@ export function DocViewer({
                   aria-hidden="true"
                   href={[
                     'https://github.com/nrwl/nx/blob/master',
-                    document.filePath.replace(
-                      'nx-dev/nx-dev/public/documentation',
-                      'docs'
-                    ),
+                    document.filePath
+                      .replace('nx-dev/nx-dev/public/documentation', 'docs')
```
Comment (mandarini) [inline nx-dev/feature-doc-viewer/src/lib/doc-viewer.tsx:144]: I'm not sure if both are needed, tbh, but I just wanted to make sure I don't remove existing behaviour, but also catch this new thing.

**Review by bcabanes — APPROVED** [review]
