### PR TITLE
fix(core): normalize paths in ng cli adapter when finding matching files

### LINKED ISSUE #10009: angular - Generate pages: Error: Specified module 'home/home.module.ts' does not exist.
## Offending command

    ng g module home --module app --route home

## Current Behavior

I'm getting an error when generating a page inside an application:

    Specified module 'home/home.module.ts' does not exist.

## Steps to Reproduce

Create the application
-------------------------

```
npx create-nx-workspace
> pages-test
> angular
> pages-demo
> scss
> No
code pages-test
```

Create the AppRoutingModule (app-routing.module.ts)
---------------------------------

```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

const routes: Routes = [];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

Import the `AppRoutingModule` in the `AppModule`

Generate a page
------------------

```
cd apps/pages-demo/src/app
ng g module home --module app --route home
```

Result:

```
Error: Specified module 'home/home.module.ts' does not exist.
Looked in the following directories:
    /apps/pages-demo/src/app/home/home.module.ts
    /apps/pages-demo/src/app/home
    /apps/pages-demo/src/app
    /apps/pages-demo/src
    /apps/pages-demo
    /apps
    at findModuleFromOptions (C:\repos\pages-test\node_modules\@schematics\angular\utility\find-module.js:48:15)
    at C:\repos\pages-test\node_modules\@schematics\angular\component\index.js:109:66        
Error: Specified module 'home/home.module.ts' does not exist.
    /apps/pages-demo/src/app/home/home.module.ts
    /apps/pages-demo/src/app/home
    /apps/pages-demo/src/app
    /apps/pages-demo/src
    /apps/pages-demo
    /apps
    at findModuleFromOptions (C:\repos\pages-test\node_modules\@schematics\angular\utility\find-module.js:48:15)
    at C:\repos\pages-test\node_modules\@schematics\angular\component\index.js:109:66
Specified module 'home/home.module.ts' does not exist.
Looked in the following directories:
    /apps/pages-demo/src/app/home/home.module.ts
    /apps/pages-demo/src/app/home
    /apps/pages-demo/src/app
    /apps/pages-demo/src
    /apps/pages-demo
    /apps
```

### Environment

- NX: 14.0.3

```
Angular CLI: 13.3.3
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.3 (cli-only)
@angular-devkit/core         13.2.3
@angular-devkit/schematics   13.2.3
@schematics/angular          13.2.3
```

### Debug NX schematics

[Here's what I did to be able to debug nx commands](https://www.youtube.com/watch?v=OGV4R0cPRPc)

### PR DESCRIPTION
**Pull request by leosvelperez**
## Current Behavior

Running an Angular Schematic on Windows might fail due to mismatching path formats when trying to find a matching file change.

## Expected Behavior

The Ng CLI adapter layer should make sure paths being compared are normalized so their formats are the same and they can match as expected.

## Related Issue(s)

Fixes #10009

### CODE REVIEW

File: packages/nx/src/adapter/ngcli-adapter.ts [hunk 1]
```diff
@@ -750,10 +750,12 @@ function findDeletedProjects(host: Tree): FileChange[] {
...
 
 function findMatchingFileChange(host: Tree, path: Path) {
-  const targetPath = path.startsWith('/') ? path.substring(1) : path.toString();
+  const targetPath = normalize(
+    path.startsWith('/') ? path.substring(1) : path.toString()
+  );
   return host
     .listChanges()
-    .find((f) => f.path === targetPath && f.type !== 'DELETE');
+    .find((f) => normalize(f.path) === targetPath && f.type !== 'DELETE');
```
Comment (sorin-davidoi) [inline packages/nx/src/adapter/ngcli-adapter.ts:758]: Can we invert the checks (to avoid normalizing paths when `f.type === 'DELETE'`)?

**Review by AgentEnder — APPROVED** [review]
