### PR TITLE
fix(core): keep version for third party preset

### LINKED ISSUE #23174: create-nx-workspace strips version from preset option
### Current Behavior

right now `npx create-nx-workspace my-workspace --preset=@org/package@1.1.1` does not respect the version and defaults to latest

### Expected Behavior

this command would respect the version passed to it

### GitHub Repo

_No response_

### Steps to Reproduce

This is just an example that mirrors my situation:
(have go installed locally)
1. run `npx create-nx-workspace go-workspace --preset=@nx-go/nx-go@2.7.0`
2. `cd go-workspace`
3. run `nx report `

you will see it installed the latest nx-go rather than the version you specified 
https://github.com/nx-go/nx-go/releases

### Nx Report

```shell
Node   : 18.18.2
OS     : darwin-arm64
npm    : 9.8.1

nx             : 18.3.4
@nx/workspace  : 18.3.4
@nx/devkit     : 18.3.4
@nrwl/tao      : 18.3.4
---------------------------------------
Registered Plugins:
@nx-go/nx-go
---------------------------------------
Community plugins:
@nx-go/nx-go : 3.0.0
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by xiongemi**
## Related Issue(s)

Fixes https://github.com/nrwl/nx/issues/23174

### CODE REVIEW

File: packages/create-nx-workspace/src/utils/preset/get-third-party-preset.ts [hunk 1]
```diff
@@ -5,32 +5,33 @@ import { isKnownPreset } from './preset';
...
-      //! Error here
-      output.error({
-        title: 'Invalid preset npm package',
-        bodyLines: [
-          `There was an error with the preset npm package you provided:`,
-          '',
-          ...(validateResult.errors ?? []),
-        ],
-      });
-      throw new Error('Invalid preset npm package');
```
Comment (FrozenPandaz) [inline packages/create-nx-workspace/src/utils/preset/get-third-party-preset.ts:31]: Make this function throw an error again. but only print the error once.

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/create-nx-workspace/src/utils/preset/get-third-party-preset.ts (hunk 1 above)
Comment (xiongemi) [reply packages/create-nx-workspace/src/utils/preset/get-third-party-preset.ts:31]: changed

**Review by FrozenPandaz — APPROVED** [review]
