### PR TITLE
fix(js): .swcrc path should be customizable

### LINKED ISSUE #10058: Custom swcrc path
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Pass a custom swcrc path to the @nrwl/js:swc executor.

## Motivation
I am attempting to keep my tooling config in a config folder. I find it a bit annoying that for each package folder I open, I see exactly the same files. I think it would be great if nx could enable some config housekeeping. 

I was able to configure some tools with custom config paths, but cannot provide a config path for SWC. 

Screenshot 2022-04-29 at 11 18 40

## Suggested Implementation
Add an optional `swcrcPath` option. Pass it here, defaulting to current behaviour if not present. 

https://github.com/nrwl/nx/blob/71bd3e13ada518412477eb78b3a7e8f206ea747a/packages/js/src/executors/swc/swc.impl.ts#L53

## Alternate Implementations
Not familiar with the codebase, but this looks like the only entrypoint to change that option. 

If nx wanted to get on board with the config files in a folder movement, it'd be good to enforce some consistency for executors to provide this option, as well an option in generators.

### PR DESCRIPTION
**Pull request by djgrant**
## Current Behavior
It is currently not possible to provide a custom path to an swcrc path. Instead, JS projects using SWC must have a `.lib.swcrc` file in the project root directory.

## Expected Behavior
With these changes, the `@nrwl/js:swc` executor can optionally be be passed an `swcrcPath`. 

In `project.json`:

```json
{
  "targets": {
    "build": {
      "executor": "@nrwl/js:swc",
      "options": {
        ...
        "swcrcPath": "path/to/swcrc"
      }
    }
  }
}
```

## Related Issue(s)

Fixes #10058

### CODE REVIEW

File: packages/js/src/utils/schema.d.ts [hunk 1]
```diff
@@ -35,6 +35,7 @@ export interface ExecutorOptions {
   main: string;
   outputPath: string;
   tsConfig: string;
+  swcrcPath?: string;
```
Comment (AgentEnder) [inline packages/js/src/utils/schema.d.ts:38]: This prop should be required since it has a default value, and the function would not work correctly if its null.

**Review by AgentEnder — CHANGES_REQUESTED** [review]
Looks great, one small nit that will likely require updating a few unit tests.
