### PR TITLE
fix(release): support forwarding the --access flag to npm publish

### LINKED ISSUE #27754: Can't generate provenance for new or private package, you must set `access` to public.
### Current Behavior

I'm trying to publish a new package via `nx release` command. I have a following error message in the log:
```
npm publish error:
Can't generate provenance for new or private package, you must set `access` to public.
```

When I check [documentation ](https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions)it's mentioned that we need to call publish like this:
```
npm publish --provenance --access public
```

However in this code we do not consider those flags:
```
}
    /**
     * NOTE: If this is ever changed away from running the command at the workspace root and pointing at the package root (e.g. back
     * to running from the package root directly), then special attention should be paid to the fact that npm publish will nest its
     * JSON output under the name of the package in that case (and it would need to be handled below).
     */
    const npmPublishCommandSegments = [
        `npm publish "${packageRoot}" --json --"${registryConfigKey}=${registry}" --tag=${tag}`,
    ];
    if (options.otp) {
        npmPublishCommandSegments.push(`--otp=${options.otp}`);
    }
    if (isDryRun) {
        npmPublishCommandSegments.push(`--dry-run`);
    }
```

Therefore do you think is it possible to introduce a new access parameter for release-publish plugin where we can declare public access? Thanks!

### Expected Behavior

nx release should properly care of publishing new public packages from CI/CD

### GitHub Repo

_No response_

### Steps to Reproduce

1. Publish a new public package using nx release CI/CD 

### Nx Report

```shell
ode           : 20.16.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.8.1

nx (global)        : 19.6.4
nx                 : 19.6.3
@nx/js             : 19.6.3
@nx/jest           : 19.6.3
@nx/linter         : 19.6.3
@nx/eslint         : 19.6.3
@nx/workspace      : 19.6.3
@nx/devkit         : 19.6.3
@nx/eslint-plugin  : 19.6.3
@nx/plugin         : 19.6.3
@nx/rollup         : 19.6.3
@nrwl/tao          : 19.6.3
@nx/vite           : 19.6.3
@nx/web            : 19.6.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
---------------------------------------
Local workspace plugins:
         workspace-plugin
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by JamesHenry**
## Current Behavior

The `access` option of `npm publish` is configurable via `package.json` `publishConfig` or environment variable.

## Expected Behavior

The `access` option of `npm publish` is configurable via `package.json` `publishConfig`, environment variable, or a `--access` option on `nx release publish`.

## Related Issue(s)

Fixes #27754

---

Additionally, when generating the docs for the new flag, I realized I never went back and exposed `release plan` and `release plan:check` in the docs, so I did that here too.

### CODE REVIEW

**Review by isaacplmann — APPROVED** [review]

**Review by jaysoo — APPROVED** [review]

File: packages/nx/src/command-line/release/command-object.ts [hunk 1]
```diff
@@ -349,10 +356,8 @@ const publishCommand: CommandModule<NxReleaseArgs, PublishOptions> = {
 const planCommand: CommandModule<NxReleaseArgs, PlanOptions> = {
   command: 'plan [bump]',
   aliases: ['pl'],
-  // TODO: Remove this when docs are added
-  // Create a plan to pick a new version and generate a changelog entry.
-  // Hidden for now until the feature is more stable
-  describe: false,
+  describe:
+    'Create a version plan file to specify the desired semver bump for one or more projects or groups, as well as the relevant changelog entry',
```
Comment (jaysoo) [inline packages/nx/src/command-line/release/command-object.ts:360]: Minor: descriptions should end with a `.`.

File: packages/nx/src/command-line/release/command-object.ts [hunk 2]
```diff
@@ -392,10 +397,8 @@ const planCommand: CommandModule<NxReleaseArgs, PlanOptions> = {
 
 const planCheckCommand: CommandModule<NxReleaseArgs, PlanCheckOptions> = {
   command: 'plan:check',
-  // TODO: Remove this when docs are added
-  // Create a plan to pick a new version and generate a changelog entry.
-  // Hidden for now until the feature is more stable
-  describe: false,
+  describe:
```
Comment (jaysoo) [inline packages/nx/src/command-line/release/command-object.ts:400]: Same here, add `/` at the end.

File: packages/nx/src/command-line/release/command-object.ts (hunk 1 above)
Comment (JamesHenry) [reply packages/nx/src/command-line/release/command-object.ts:360]: I was matching the existing commands in there, looks like we are pretty inconsistent in general. We should add a custom lint rule for this like we did for schema descriptions.
