### PR TITLE
fix(core): fix creating workspace on Windows for npm@7

### LINKED ISSUE #4922: EINVAL: invalid argument, mkdir
## Current Behavior

When I create empty repo, nx cli throw error: `EINVAL: invalid argument, mkdir`.
see error log below.

## Expected Behavior

nx should create an empty repo.

## Steps to Reproduce

Run the command:  `npx create-nx-workspace`  with the following inputs:
```
? Workspace name (e.g., org name)     myorg
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building apps]
? Use Nx Cloud? (It's free and doesn't require registration.) No
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
λ npx create-nx-workspace
? Workspace name (e.g., org name)     myorg
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building apps]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
new myorg --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace
CREATE myorg/nx.json
CREATE myorg/package.json
CREATE myorg/README.md
CREATE myorg/tools/generators/.gitkeep
CREATE myorg/tools/tsconfig.tools.json
CREATE myorg/tsconfig.base.json
CREATE myorg/.editorconfig
CREATE myorg/.gitignore
CREATE myorg/.prettierignore
CREATE myorg/.vscode/extensions.json
CREATE myorg/workspace.json
CREATE myorg/.prettierrc
CREATE myorg/apps/.gitkeep
CREATE myorg/libs/.gitkeep
EINVAL: invalid argument, mkdir 'C:\C:\sandbox\myorg'
node:child_process:636
    err = new Error(msg);
          ^

Error: Command failed: npx tao new myorg --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\"C:/sandbox\"
    at checkExecSyncError (node:child_process:636:11)
    at Object.execSync (node:child_process:672:15)
    at createApp (C:\Users\wizar\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:385:21)
    at C:\Users\wizar\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:98:29
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 15228,
  stdout: null,
  stderr: null
}
```

### Environment

nx - latest.
windows 10
node version: v15.0.1
npm version: 7.6.0

### PR DESCRIPTION
**Pull request by bekos**
Closes #4922

### CODE REVIEW

File: packages/create-nx-workspace/bin/create-nx-workspace.ts [hunk 1]
```diff
@@ -434,11 +437,19 @@ function createApp(tmpDir: string, name: string, parsedArgs: WorkspaceArgs) {
...
-    nxWorkspaceRoot = `\\"${nxWorkspaceRoot}\\"`;
-  } else {
-    nxWorkspaceRoot = `"${nxWorkspaceRoot}"`;
+  let nxWorkspaceRoot = `"${process.cwd().replace(/\\/g, '/')}"`;
+
+  // If path contains spaces there is a problem in Windows for npm@6.
+  // In this case we have to escape the wrapping quotes.
+  if (
+    process.platform === 'win32' &&
+    /\s/.test(nxWorkspaceRoot) &&
```
Comment (FrozenPandaz) [inline packages/create-nx-workspace/bin/create-nx-workspace.ts:446]: If It's npm 7 and there are no spaces...

Is there still an issue with the non-escaped quotes?

Comment (bekos) [reply packages/create-nx-workspace/bin/create-nx-workspace.ts:446]: No, NPM 7 works even with spaces.
