### PR TITLE
fix(expo): update package.json eas build scripts to fix eas build

### LINKED ISSUE #13242: EXPO - EAS build failing
### Current Behavior

Hi, 
I'm currently migrating two repos to an NX mono repository (React.JS + Expo). 

Everything was going well until yesterday. All my EAS builds are failing and I can't understand why (they worked perfectly fine when I used a standalone repo)

### Expected Behavior

The EAS build should be succeeded when using @nrwl/expo:build. 

### Github Repo

_No response_

### Steps to Reproduce

https://github.com/yonitou/example

1. Go to the GitHub repo above
2. Run npm install
3. nx build native-app --configuration=simulator
4. Wait 

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : darwin arm64
   npm  : 8.3.0
   
   nx : 15.0.13
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.13
   @nrwl/detox : 15.1.1
   @nrwl/devkit : 15.0.13
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.13
   @nrwl/expo : 15.1.1
   @nrwl/express : Not Found
   @nrwl/jest : 15.1.1
   @nrwl/js : 15.0.13
   @nrwl/linter : 15.0.13
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.13
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.1.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.13
   @nrwl/web : 15.1.1
   @nrwl/webpack : 15.1.1
   @nrwl/workspace : 15.0.13
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```
```


### Failure Logs

```shell
The failure logs provided by EXPO are : 


 FAILURE: Build failed with an exception.
49
[stderr] * Where:
50
[stderr] Script '/home/expo/workingdir/build/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 250
51
[stderr] * What went wrong:
52
[stderr] A problem occurred evaluating script.
53
[stderr] > Calling `[node, /home/expo/workingdir/build/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
54
[stderr]   
55
[stderr]   The current character read is 'i' with an int value of 105
56
[stderr]   Unable to determine the current character, it is not a string, number, array, or object
57
[stderr]   line number 1
58
[stderr]   index number 0
59
[stderr]   info Run CLI with --verbose flag for more details.
60
[stderr]   ^. Output: info Run CLI with --verbose flag for more details.
```
```


### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by xiongemi**
## Related Issue(s)

Fixes https://github.com/nrwl/nx/issues/13242

### CODE REVIEW

File: packages/expo/src/migrations/update-16-1-0/update-eas-scripts.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+          const offset = offsetFromRoot(config.root);
+          packageJson.scripts = {
+            ...packageJson.scripts,
+            'eas-build-pre-install': `cd ${offset} && node tools/scripts/eas-build-pre-install.mjs . ${config.root} && cp ${packageLockFile} ${config.root}`,
+            'eas-build-post-install': `cd ${offset} && node tools/scripts/eas-build-post-install.mjs . ${config.root}`,
+          };
+          return packageJson;
+        });
+      } catch {
+        console.log(`Unable to update package.json for project ${name}.`);
```
Comment (jaysoo) [inline packages/expo/src/migrations/update-16-1-0/update-eas-scripts.ts:42]: `logge.error(...)` from devkit?

Comment (xiongemi) [reply packages/expo/src/migrations/update-16-1-0/update-eas-scripts.ts]: changed

File: packages/expo/migrations.json [hunk 2]
```diff
@@ -53,6 +53,12 @@
       "version": "16.0.0-beta.1",
       "description": "Replace @nrwl/expo with @nx/expo",
       "implementation": "./src/migrations/update-16-0-0-add-nx-packages/update-16-0-0-add-nx-packages"
+    },
+    "update-eas-scripts": {
+      "cli": "nx",
+      "version": "16.1.0-beta.0",
```
Comment (jaysoo) [inline packages/expo/migrations.json:59]: Let's bump to 16.1.2-beta.0 since 16.1.1 is being released today.

**Review by jaysoo — APPROVED** [review]

**Review by jaysoo — APPROVED** [review]
