### PR TITLE
fix(devkit): add missing parameter to prettier getFileInfo

### LINKED ISSUE #9576: Nx formatFiles does not call prettier getFileInfo with FileInfoOptions
When using Nx generators with a call to formatFiles(tree), this function calls 

prettier.getFileInfo(systemPath)

instead of calling with the second parameter of type FileInfoOptions

prettier.getFileInfo(systemPath, options.fileInfoOptions)

interface FileInfoOptions {
    withNodeModules?: boolean;
    ignorePath?: string;
}

Then, FileInfoOptions in undefined in all nested functions under prettier.getFileInfo.
This cause support.ignored to be always false.

So, we need to have the second parameters called and retrieved from prettierrc, in which option can be defined like this :
"fileInfoOptions": {
    "withNodeModules": false,
    "ignorePath": "./.prettierignore"
  },

https://github.com/nrwl/nx/blob/70492f3939cfab6eae48fcb62f98eecfc9eed117/packages/devkit/src/generators/format-files.ts#L50

### PR DESCRIPTION
**Pull request by danjor**
## Current Behavior
When settings "ignorePath": "./.prettierignore" inside .prettierrc file, this is ignored when running nx generator as the second parameter of prettier.getFileInfo is missing, so formatFiles always format all the files and ignore is always false.

## Expected Behavior
When setting "ignorePath": "./.prettierignore" inside .prettierrc file, this configuration should be taken into account when running nx generator as the second parameter of prettier.getFileInfo, so formatFiles formatFiles that are not ignored based on the config.

## Related Issue(s)
Fixes #9576

### CODE REVIEW

File: packages/devkit/src/generators/format-files.ts [hunk 1]
```diff
@@ -32,7 +32,7 @@ export async function formatFiles(tree: Tree): Promise<void> {
   await Promise.all(
     Array.from(files).map(async (file) => {
       const systemPath = path.join(tree.root, file.path);
-      let options: Prettier.Options = {
+      let options: any = {
```
Comment (AgentEnder) [inline packages/devkit/src/generators/format-files.ts:35]: There's probably a different type we can use here. Can you try Prettier.FileInfoOptions?

Comment (danjor) [reply packages/devkit/src/generators/format-files.ts]:
```
Error: packages/devkit/src/generators/format-files.ts:36:9 - error TS2322: Type '{ filepath: string; }' is not assignable to type 'FileInfoOptions'.
  Object literal may only specify known properties, and 'filepath' does not exist in type 'FileInfoOptions'.

36         filepath: systemPath,
```

Comment (AgentEnder) [reply packages/devkit/src/generators/format-files.ts]: Ah, yes. Try `Prettier.Options & Prettier.FileInfoOptions`
