### PR TITLE
fix(misc): disallow path segments and allow scoped package name in --newProjectName option of move generator

### LINKED ISSUE #20756: Bypass nx generate @nx/angular:library "You can't specify both a directory and a name with a directory path"
### Current Behavior

I am trying to create an Angular library named `service/auth` in directory `libs/service/auth`.

image

This gives me the following error
```
You can't specify both a directory (libs/service/auth) and a name with a
directory path (service/auth).
Please specify either a directory or a name with a directory path.
```
image

I then change the name of the library to `service-auth` as well as the directory to `libs/service-auth`. And that works with no problem.

image

But then I can bypass the initial validation error above by moving the newly created library. Using both the directory and name that I wanted originally. And I get no errors.

image

image

I end up with this in the tsconfig.base.json
```typescript
"@lf/service/auth": ["libs/service/auth/src/index.ts"],
```

### Expected Behavior

I would expect the validation error to be consistent between creating a library and moving it.

### GitHub Repo

_No response_

### Steps to Reproduce

See above

### Nx Report

```shell
Node   : 18.17.1
   OS     : win32-x64
   npm    : 8.11.0
   
   nx (global)        : 17.1.3
   nx                 : 17.2.0
   @nx/js             : 17.2.0
   @nx/jest           : 17.2.0
   @nx/linter         : 17.2.0
   @nx/eslint         : 17.2.0
   @nx/workspace      : 17.2.0
   @nx/angular        : 17.2.0
   @nx/cypress        : 17.2.0
   @nx/devkit         : 17.2.0
   @nx/eslint-plugin  : 17.2.0
   @nrwl/tao          : 17.2.0
   @nx/web            : 17.2.0
   @nx/webpack        : 17.2.0
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.14.0
   @ngrx/component-store            : 17.0.1
   @ngrx/signals                    : 17.0.1
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leosvelperez**
This PR aligns the `move` generator handling for project names with the changes made to the project generators in https://github.com/nrwl/nx/pull/20274.

## Related Issue(s)

Fixes #20756

### CODE REVIEW

File: packages/workspace/src/generators/move/lib/normalize-schema.ts [hunk 1]
```diff
@@ -119,84 +128,75 @@ function validateName(
...
-          schema.importPath ??
-          // keep the existing import path if the name didn't change
-          (normalizedNewProjectName &&
-          schema.projectName !== normalizedNewProjectName
-            ? asProvidedProjectName
-            : undefined),
-        newProjectName: asProvidedProjectName,
-      },
+      'as-provided': asProvidedOptions,
+      derived: undefined,
```
Comment (jaysoo) [inline packages/workspace/src/generators/move/lib/normalize-schema.ts:156]: If derived is undefined, what will the prompt show for the user?

Comment (leosvelperez) [reply packages/workspace/src/generators/move/lib/normalize-schema.ts:156]: It won't prompt and `as-provided` will be used.

This particular return statement happens when the `projectNameAndRootFormat` is `as-provided`. The other one below would have a warning explaining why it's using `as-provided` without prompting.

**Review by jaysoo — APPROVED** [review]

**Review by AgentEnder — APPROVED** [review]
