### PR TITLE
fix(node): assets should be copied when building with --watch

### LINKED ISSUE #5724: Running build in watch mode for buildable node libraries does not generate a `package.json` as part of the output.
## Current Behavior
Running build in watch mode for buildable node libraries does not generate a `package.json` as part of the output.
This breaks incremental building as dependents of this library keep telling me that it is not built.

## Expected Behavior
`package.json` should be generated in watch mode. 
This was the behavior up to @nrwl/node v11.4.0. 
After v11.4.0, watch mode was broken (#5208), which was fixed in v12.3.4

## Workarounds
I wrote a `watch` target for the library:
I had to deliberately skip-nx-cache to avoid race condition, too
```json
"watch": {
    "executor": "@nrwl/workspace:run-commands",
    "options": {
        "parallel": true,
        "commands": [
            {
                "command": "npx nx build models --watch"
            },
            {
                "command": "npx nx build models --skip-nx-cache"
            }
        ]
    }
},
```
## Additonal info:
In @nrwl/node v11.4.0, the output for `npx nx build project --watch` would be
```
9:35:57 am - Starting compilation in watch mode...


9:35:59 am - Found 0 errors. Watching for file changes.
Copying asset files...   
Done copying asset files. 
```

In v12.3.4, the output is
```
1:19:33 pm - Starting compilation in watch mode...


1:19:34 pm - Found 0 errors. Watching for file changes.
```
This seems to suggest that in the v12.3.4 once it enters watch mode, no further additional processing is done, which was being done in v11.4.0

### Environment

  Node : 14.17.0
  OS   : win32 x64
  npm  : 7.13.0

  nx : Not Found
  @nrwl/angular : 12.3.4
  @nrwl/cli : 12.3.4
  @nrwl/cypress : 12.3.4
  @nrwl/devkit : 12.3.4
  @nrwl/eslint-plugin-nx : 12.3.4
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.4
  @nrwl/linter : 12.3.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.3.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.4
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.4
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
Assets are not copied to dist when running `nx build my-node-lib --watch`.

## Expected Behavior
Assets, including package.json, should be present in dist. 

## Caveats
This change does not add the assets to the watcher, since it is using the typescript compiler's watch program. As such, if assets change it does not retrigger the compiler.

## Related Issue(s)

Fixes #5724

### CODE REVIEW

File: packages/workspace/src/utilities/typescript/compilation.ts [hunk 1]
```diff
@@ -13,9 +14,16 @@ export interface TypeScriptCompilationOptions {
...
+  diagnostic: ts.Diagnostic;
+  newLine: string;
+  options: ts.CompilerOptions;
+  errorCount: number;
+}
+
 export function compileTypeScript(
   options: TypeScriptCompilationOptions
-): { success: boolean } | Promise<any> {
+): { success: boolean } | Observable<TypescriptWatchChangeEvent> {
```
Comment (FrozenPandaz) [inline packages/workspace/src/utilities/typescript/compilation.ts:26]: I think it would be better to split this into 2 different methods.

1. For watch mode that always returns an observable (or an async generator if possible)
2. For not watch mode that returns synchronously. (Assuming there's no async version)

File: packages/node/src/executors/package/package.impl.ts [hunk 2]
```diff
@@ -43,9 +44,53 @@ export async function packageExecutor(
...
+        lock = true;
+        await updatePackageAndCopyAssets(
+          normalizedOptions,
+          context,
+          target,
+          dependencies
+        );
+        lock = false;
+      });
+    await new Promise<any>(() => {});
```
Comment (FrozenPandaz) [inline packages/node/src/executors/package/package.impl.ts:65]: You could return the observable `.toPromise()` with a `tap`

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/node/src/executors/package/package.impl.ts (hunk 2 above)
Comment (AgentEnder) [reply packages/node/src/executors/package/package.impl.ts]: No more observables. Uses callback now.
