### PR TITLE
fix(core): project graph should be read from executor context

### LINKED ISSUE #11210: ERROR: No cached ProjectGraph is available.
## Current Behavior
Random `nx` crash in our Github CI during a build

## Expected Behavior
`nx` can build our projects without failing 

## Steps to Reproduce
I guess new messages at the end of #10730 are kinda similar. Looks related to the latest release.

### Failure Logs
```
> nx run generic-dynamodb-orm:build 
Error reading '/home/ubuntu/actions-runner/_work/monorepo/monorepo/node_modules/.cache/nx/nxdeps.json'. Continue the process without the cache.
Error: ValueExpected in /home/ubuntu/actions-runner/_work/monorepo/monorepo/node_modules/.cache/nx/nxdeps.json at position 0
    at parseJson (/home/ubuntu/actions-runner/_work/monorepo/monorepo/node_modules/.pnpm/nx@14.4.3_@swc+core@1.2.215/node_modules/nx/src/utils/json.js:23:15)
    at readJsonFile (/home/ubuntu/actions-runner/_work/monorepo/monorepo/node_modules/.pnpm/nx@14.4.3_@swc+core@1.2.215/node_modules/nx/src/utils/fileutils.js:23:37)
    at readCache (/home/ubuntu/actions-runner/_work/monorepo/monorepo/node_modules/.pnpm/nx@14.4.3_@swc+core@1.2.215/node_modules/nx/src/project-graph/nx-deps-cache.js:41:49)
    at readCachedProjectGraph (/home/ubuntu/actions-runner/_work/monorepo/monorepo/node_modules/.pnpm/nx@14.4.3_@swc+core@1.2.215/node_modules/nx/src/project-graph/project-graph.js:20:61)
    at checkDependencies (/home/ubuntu/actions-runner/_work/monorepo/monorepo/node_modules/.pnpm/@nrwl+js@14.4.3_2ufozsgst4bthv2r67rno347d4/node_modules/@nrwl/js/src/utils/check-dependencies.js:7:62)
    at tscExecutor_1 (/home/ubuntu/actions-runner/_work/monorepo/monorepo/node_modules/.pnpm/@nrwl+js@14.4.3_2ufozsgst4bthv2r67rno347d4/node_modules/@nrwl/js/src/executors/tsc/tsc.impl.js:29:111)
    at tscExecutor_1.next (<anonymous>)
    at resume (/home/ubuntu/actions-runner/_work/monorepo/monorepo/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:230:48)
    at /home/ubuntu/actions-runner/_work/monorepo/monorepo/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:229:[125](https://github.com/hublo/monorepo/runs/7410177714?check_suite_focus=true#step:11:126)
    at new Promise (<anonymous>)
 >  NX   [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.
   If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
   the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.
   If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx
   Pass --verbose to see the stacktrace.
```
### Environment
```
❯ pnx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin arm64
   pnpm : 7.5.0

   nx : 14.4.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/eslint-plugin-nx : 14.4.3
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.3
   @nrwl/js : 14.4.3
   @nrwl/linter : 14.4.3
   @nrwl/nest : 14.4.3
   @nrwl/next : 14.4.2
   @nrwl/node : 14.4.3
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.3
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.3
   @nrwl/web : 14.4.3
   @nrwl/workspace : 14.4.3
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
Several executors use a mish-mash  of `createProjectGraphAsync `as well as `readCachedProjectGraph `to access project graph data. This is not necessarily incorrect, but combined with the call to `createProjectGraphAsync` in `run`, some places may attempt to read the cache while it is actively being written. This results in malformed JSON and presents as a crash.

This currently surfaces most frequently in @nrwl/js:tsc and @nrwl/angular:package, but its possible that other executors would be affected as well.
## Expected Behavior
Executors only use `readCachedProjectGraph`, but also make use of the project graph as provided in the executor context when possible.

## Related Issue(s)

Fixes #11210

### CODE REVIEW

File: packages/js/src/utils/compiler-helper-dependency.ts [hunk 1]
```diff
@@ -31,21 +32,49 @@ const jsExecutors = {
...
+  helperDependency: HelperDependency,
+  configPath: string,
+  dependencies: DependentBuildableProjectNode[],
+  options: GetHelperDependencyOptions = { returnDependencyIfFound: false }
+): Promise<DependentBuildableProjectNode | null> {
+  return getHelperDependencySync(
+    helperDependency,
+    configPath,
+    dependencies,
+    options.projectGraph ?? (await createProjectGraphAsync()),
```
Comment (wSedlacek) [inline packages/js/src/utils/compiler-helper-dependency.ts:66]: I noticed that the `createProjectGraphAsync()` ALWAYS writes a `nxdeps.json` cache whenever it is called. So when you have many executors running in parallel (tested in my workspace with 137 projects) there will be teams where one task will be reading and another will be writing at the same time resulting in a read error of something like this.

```
Error: CloseBraceExpected in /home/runner/work/shipyard/shipyard/node_modules/.cache/nx/nxdeps.json at position 2138112
```

So perhaps calling the create graph function isn't the right solution?
Or maybe the issue is that the create graph should not be rewriting to that file so often?

File: packages/js/src/utils/compiler-helper-dependency.ts [hunk 2]
```diff
@@ -89,12 +117,23 @@ export function getHelperDependency(
   };
 }
 
-export function getHelperDependenciesFromProjectGraph(
+export async function getHelperDependenciesFromProjectGraph(
```
Comment (nartc) [inline packages/js/src/utils/compiler-helper-dependency.ts:120]: suggestion: since this function is only used in `generate-package-json-webpack-plugin`, and the plugin seems to have access to the `ProjectGraph` already, I'd make this one accept a `projectGraph` instead of breaking it up and use `createProjectGraphAsync`.

**Review by nartc — COMMENTED** [review]
The error from the linked issue seems to point to `check-dependencies`. Should we do something with the `projectGraph` in `checkDependencies` instead?

**Review by nartc — CHANGES_REQUESTED** [review]
prevent accidental merge

File: packages/js/src/utils/compiler-helper-dependency.ts (hunk 1 above)
Comment (AgentEnder) [reply packages/js/src/utils/compiler-helper-dependency.ts:66]: This was a bit more of a band-aid fix than I'd have liked anyways, I'm spending some more time on this now.
