### PR TITLE
fix(core): update jest config correctly when using move schematic

### LINKED ISSUE #4500: workspace:move produces malformed jest.config.js files
## Current Behavior

The `@nrwl/workspace:move` schematic breaks `jest.config.js` by swallowing the quotes around string literals:
image

## Expected Behavior

The quotes should not be removed.
This bug was introduced in cf7f1c89dae5947392ca88ccf572379b9ca84f5a.
This exact problem is trivial to fix simply by adding the quotes in line 60 of `update-jest-config.ts`, but I chose not to submit a PR like that because it's not hard to see that the general approach won't work at all if `jest.config.js` happens to use double quotes for string literals, etc. So perhaps a more robust solution should be employed instead.

## Steps to Reproduce

```sh
yarn create nx-workspace foo --preset=react --appName=bar --style css --nx-cloud=false
cd foo
yarn nx g mv --project=bar baz
```

### Environment

```
Node : 14.15.4
OS   : win32 x64
npm  : 6.14.10

nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 11.1.1
@nrwl/cypress : 11.1.1
@nrwl/devkit : 11.1.1
@nrwl/eslint-plugin-nx : 11.1.1
@nrwl/express : Not Found
@nrwl/jest : 11.1.1
@nrwl/linter : 11.1.1
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/react : 11.1.1
@nrwl/schematics : Not Found
@nrwl/tao : 11.1.1
@nrwl/web : 11.1.1
@nrwl/workspace : 11.1.1
typescript : 4.0.5
```

### PR DESCRIPTION
**Pull request by mehrad-rafigh**
## Current Behavior
move schematic produces malformed jest.config

## Expected Behavior
move schematic updates jest config correctly

## Related Issue(s)
ISSUES CLOSED: #4500

### CODE REVIEW

File: packages/workspace/src/schematics/move/lib/update-jest-config.ts [hunk 1]
```diff
@@ -57,7 +57,7 @@ export function updateJestConfig(schema: Schema): Rule {
 
         const newRootJestConfigContent = oldRootJestConfigContent.replace(
           findProject,
-          `<rootDir>/${destination}`
+          `'<rootDir>/${destination}'`
```
Comment (Cammisuli) [inline packages/workspace/src/schematics/move/lib/update-jest-config.ts:60]: You could probably change the regex on line 54 to be this:
```
const { libsDir, appsDir } = getWorkspaceLayout(tree);
const findProject = new RegExp(
  `<rootDir>\/(${libsDir}|${appsDir})\/${schema.projectName}`,
  'g'
);
```

> The `getWorkspaceLayout` is imported from `./utils`. This is important for users who changed their default layout. 

If you remove the quotes from the regex, you'll still be able to find the string if users are using `'` or `"`. Then you don't have to run a format, because the string between the quotes will be replaced. 

Preferably, using AST would've been better, but the [jest config update function](https://github.com/nrwl/nx/blob/3ea76b78dec98e6758343063ebc9bff43a7fe5ac/packages/jest/src/migrations/utils/config/legacy/update-config.ts#L4) is bound to the `@nrwl/jest` package and we can't import that here easily.

Comment (mehrad-rafigh) [reply packages/workspace/src/schematics/move/lib/update-jest-config.ts:60]: For the time being, I can change the implementation tonight like you mentioned

File: packages/workspace/src/schematics/move/lib/update-jest-config.ts [hunk 2]
```diff
@@ -50,14 +50,15 @@ export function updateJestConfig(schema: Schema): Rule {
...
         const findProject = new RegExp(
-          `'<rootDir>\/(libs|apps)\/${schema.projectName}'`,
+          `<rootDir>\/(${libsDir}|${appsDir})\/${schema.projectName}`,
           'g'
         );
 
         const newRootJestConfigContent = oldRootJestConfigContent.replace(
           findProject,
-          `<rootDir>/${destination}`
+          `'<rootDir>/${destination}'`
```
Comment (Cammisuli) [inline packages/workspace/src/schematics/move/lib/update-jest-config.ts:61]: You should remove the single quotes from here too. The final config would have double single quotes 😅

**Review by Cammisuli — CHANGES_REQUESTED** [review]
