### PR TITLE
fix(linter): support eslint v9

### LINKED ISSUE #22769: `@nx/eslint-pluggin` throws an error in Eslint 9
### Current Behavior

With Eslint 9 we get two errors: 

image
image

### Expected Behavior

I believe no errors should be shown

### GitHub Repo

_No response_

### Steps to Reproduce

1. Update eslint to 9
2. Run lint in a package with uses `@nx/dependency-checks` rule

### Nx Report

```shell
Node   : 20.6.1
OS     : darwin-arm64
pnpm   : 8.6.10

nx                 : 18.2.2
@nx/js             : 18.2.2
@nx/linter         : 18.2.2
@nx/eslint         : 18.2.2
@nx/workspace      : 18.2.2
@nx/devkit         : 18.2.2
@nx/eslint-plugin  : 18.2.2
@nx/playwright     : 18.2.2
@nrwl/tao          : 18.2.2
typescript         : 4.7.4
```

### Failure Logs

```shell
✖  nx run @cld/npm-scripts:lint
      > @cld/npm-scripts@2.10.100 lint /Users/olaf/Repositories/cld-web/libs/dev/npm-scripts
      > eslint .


      Oops! Something went wrong! :(

      ESLint: 8.57.0

      Error: Key "plugins": Cannot redefine plugin "@typescript-eslint".
          at /Users/olaf/Repositories/cld-web/node_modules/.pnpm/@humanwhocodes+object-schema@2.0.2/node_modules/@humanwhocodes/object-schema/src/object-schema.js:250:27
          at Array.reduce (<anonymous>)
          at ObjectSchema.merge (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/@humanwhocodes+object-schema@2.0.2/node_modules/@humanwhocodes/object-schema/src/object-schema.js:237:24)
          at /Users/olaf/Repositories/cld-web/node_modules/.pnpm/@humanwhocodes+config-array@0.11.14/node_modules/@humanwhocodes/config-array/api.js:935:42
          at Array.reduce (<anonymous>)
          at FlatConfigArray.getConfig (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/@humanwhocodes+config-array@0.11.14/node_modules/@humanwhocodes/config-array/api.js:934:39)
          at FlatConfigArray.isFileIgnored (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/@humanwhocodes+config-array@0.11.14/node_modules/@humanwhocodes/config-array/api.js:962:15)
          at entryFilter (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/eslint/eslint-helpers.js:320:47)
          at Object.isAppliedFilter (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/@nodelib+fs.walk@1.2.8/node_modules/@nodelib/fs.walk/out/readers/common.js:12:31)
          at AsyncReader._handleEntry (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/@nodelib+fs.walk@1.2.8/node_modules/@nodelib/fs.walk/out/readers/async.js:86:20)
       ELIFECYCLE  Command failed with exit code 2.



——————————————————————————————————————————————————————————————————————————————————————————————————————
   ✖  nx run @cld/build-utils:lint
      > @cld/build-utils@1.2.89 lint /Users/olaf/Repositories/cld-web/libs/dev/build-utils
      > eslint .


      Oops! Something went wrong! :(

      ESLint: 9.0.0

      TypeError: Error while loading rule '@nx/dependency-checks': Cannot read properties of undefined (reading 'isJSON')
      Occurred while linting /Users/olaf/Repositories/cld-web/libs/dev/build-utils/src/index.js
          at create (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/@nx+eslint-plugin@18.2.2_@types+node@20.6.1_@typescript-eslint+parser@7.5.0_eslint@9.0.0_nx@18.2.2_typescript@4.7.4/node_modules/@nx/eslint-plugin/src/rules/dependency-checks.js:58:37)
          at Object.create (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/@typescript-eslint+utils@7.5.0_eslint@9.0.0_typescript@4.7.4/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:38:20)
          at createRuleListeners (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/linter.js:1003:21)
          at /Users/olaf/Repositories/cld-web/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/linter.js:1129:84
          at Array.forEach (<anonymous>)
          at runRules (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/linter.js:1061:34)
          at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/linter.js:1910:31)
          at Linter._verifyWithFlatConfigArray (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/linter.js:2046:21)
          at Linter.verify (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/linter.js:1535:61)
          at Linter.verifyAndFix (/Users/olaf/Repositories/cld-web/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/linter.js:2283:29)
       ELIFECYCLE  Command failed with exit code 2.
```

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This seems to be related to changed described here: https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/

And mostly to the parts:
> All of this is to say that we are deprecating all of the code-related methods on context and moving them to SourceCode

> As we look towards the API we’d like rules for other languages to have, we decided to convert some methods on context to properties

It requires changes in `packages/eslint-plugin/src/rules/dependency-checks.ts`

```js
    if (!(context.sourceCode.parserServices as any).isJSON) {
      return {};
    }
    const fileName = normalizePath(context.filename ?? context.getFilename());
```

More changes might be necessary for Eslint 9 to work, but this is what I uncovered

### PR DESCRIPTION
**Pull request by JamesHenry**
## Current Behavior

- Nx's built in ESLint rules use deprecated APIs which have been removed in v9
- The Nx crystal plugin for ESLint doesn't work with eslintrc config by default (the user would need to set an env var manually)

## Expected Behavior

The built in Nx rules work with ESLint v8 and v9, the crystal plugin works with eslintrc and flat config on both ESLint v8 and v9.

## Related Issue(s)

Fixes #22769

### CODE REVIEW

File: tools/eslint-rules/rules/valid-schema-description.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ export const rule = ESLintUtils.RuleCreator(() => __filename)({
   defaultOptions: [],
   create(context) {
     // jsonc-eslint-parser adds this property to parserServices where appropriate
-    if (!(context.parserServices as any).isJSON) {
+    if (!(context.sourceCode.parserServices as any).isJSON) {
```
Comment (JamesHenry) [inline tools/eslint-rules/rules/valid-schema-description.ts:27]: We don't need to wrap this here, it is not a shared rule, so we just migrate the usage

**Review by FrozenPandaz — APPROVED** [review]
