### PR TITLE
fix(core): hide no file server process json log

### LINKED ISSUE #27617: ENOENT: no such file or directory server-process.json
### Current Behavior

After updating from 18.3.4 to 19.6.2, each time I run `nx reset` after building something cachable, I see:

```
Resetting the Nx cache and stopping the daemon.
ENOENT: no such file or directory, open 'C:\Users\edoardo.luppi\...\.nx\workspace-data\d\server-process.json'
Successfully reset the Nx workspace.
```

image

### Expected Behavior

`nx reset` runs without issues.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Execute a cachable task
2. Run `nx reset`

### Nx Report

```shell
Node           : 20.14.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.7.0

nx                 : 19.6.2
@nx/js             : 19.6.2
@nx/jest           : 19.6.2
@nx/linter         : 19.6.2
@nx/eslint         : 19.6.2
@nx/workspace      : 19.6.2
@nx/angular        : 19.6.2
@nx/cypress        : 19.6.2
@nx/devkit         : 19.6.2
@nx/esbuild        : 19.6.2
@nx/eslint-plugin  : 19.6.2
@nx/plugin         : 19.6.2
@nx/storybook      : 19.6.2
@nrwl/tao          : 19.6.2
@nx/web            : 19.6.2
@nx/webpack        : 19.6.2
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/js
@nx/eslint/plugin
---------------------------------------
Community plugins:
@storybook/angular : 8.2.8
ng-zorro-antd      : 18.1.1
---------------------------------------
Local workspace plugins:
         @hcl/nx-extester
         @hcl/nx-appscan
         @hcl/nx-assets
         @hcl/nx-mend
         @hcl/nx-vsce
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AgentEnder**
## Related Issue(s)

Fixes #27617

### CODE REVIEW

File: packages/nx/src/daemon/client/client.ts [hunk 1]
```diff
@@ -603,16 +603,18 @@ export class DaemonClient {
...
     try {
       await this.sendMessageToDaemon({ type: FORCE_SHUTDOWN });
       await waitForDaemonToExitAndCleanupProcessJson();
     } catch (err) {
-      output.error({
-        title:
-          err?.message ||
-          'Something unexpected went wrong when stopping the server',
-      });
+      if (!silent) {
```
Comment (FrozenPandaz) [inline packages/nx/src/daemon/client/client.ts:611]: Expect the ENOENT

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/nx/src/daemon/client/client.ts [hunk 2]
```diff
@@ -608,6 +608,10 @@ export class DaemonClient {
       await this.sendMessageToDaemon({ type: FORCE_SHUTDOWN });
       await waitForDaemonToExitAndCleanupProcessJson();
     } catch (err) {
+      if (err.code === 'ENOENT') {
```
Comment (FrozenPandaz) [inline packages/nx/src/daemon/client/client.ts:611]: This seems like the wrong kind of error to be expecting in this function. sending a message to a daemon which does not exist, should throw a special error... which we can catch here.

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
