### PR TITLE
fix(core): adjust how findMatchingProjects works when provided additive patterns after an exclusion to be more intuitive

### LINKED ISSUE #19210: Exclude flag for affected and run-many commands doesn't work as expected
### Current Behavior

The following doesn't work:
Given projects that have a `example` tag, `package` tag and some projects with a `package` tag have a `database` tag, I want to exclude them all except for projects with a `package` tag that don't have a `database` tag.

The following command still packages with a `database` tag:
`nx run affected:test --exclude='*,!tag:package,tag:database'`

### Expected Behavior

To exclude packages with a `database` tag.

### GitHub Repo

_No response_

### Steps to Reproduce

1.
L

### Nx Report

```shell
L
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
A list of patterns such as `['*', '!packages/*', 'my-package']` will not include `'my-package'` as a result. This behavior feels weird though, as intuitively the patterns are parsed as:

- Select everything
- Remove anything under packages directory
- Add my-package

However, mechanically, we currently handle exclusions at the very end of processing patterns. This means we parse it as:
- Select everything
- Add my-package
- Remove everything under packages directory

## Expected Behavior
Pattern parsing is intuitive.

## Related Issue(s)

Fixes #19210

### CODE REVIEW

File: packages/nx/src/utils/find-matching-projects.ts [hunk 1]
```diff
@@ -181,14 +177,18 @@ function addMatchingProjectsByTag(
...
-  excludedProjects: Set<string>,
-  selectedProjects: Set<string>
+  matchedProjects: Set<string>
 ) {
   for (const projectName of projectNames) {
     const tags = projects[projectName].data.tags || [];
 
     if (tags.includes(pattern.value)) {
-      (pattern.exclude ? excludedProjects : selectedProjects).add(projectName);
+      console.log('Processed', pattern, projectName);
```
Comment (FrozenPandaz) [inline packages/nx/src/utils/find-matching-projects.ts:186]: rm

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
