### PR TITLE
fix(misc)!: only provide default value for object properties if object already has value

### LINKED ISSUE #23153: Inconsistent executors' schema validation
### Current Behavior

With the given schema for a custom executor:

```json
{
  "$schema": "http://json-schema.org/schema",
  "type": "object",
  "properties": {
    "config": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["development", "staging", "production"]
      },
      "default": ["development"]
    },
    "org": {
      "type": "string",
      "example": "my-org"
    },
    "variables": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "example": {
        "SERVER_URL": "value",
        "DB_URL": "value"
      }
    },
    "webhook": {
      "type": "object",
      "properties": {
        "url": {
          "description": "The target server ",
          "type": "string",
          "format": "uri",
          "example": "http://webhook.test"
        },
        "secret": {
          "type": "string"
        }
      },
      "required": ["url"]
    }
  },
  "required": ["config"]
}

```

And the following project configuration, where `deploy` is the target using the above executor

```json
{
  "name": "test-app",
  "$schema": "./node_modules/nx/schemas/project-schema.json",
  "projectType": "application",
  "targets": {
    "deploy": {
      "executor": "my-executor",
      "options": {}
    }
  },
  "tags": []
}
```

When running `nx run test:app:deploy --config=development`, the validator will throw the error 
```
Required property 'url' is missing
```

The `url` property is a required property of `webhook`; however, `webhook` is not a required property of the executor's options. And `webhook` should be undefined since it is neither passed to the CLI arguments nor declared in the target's options. 
Did I miss something? Is it a design choice?

### Expected Behavior

 I would expect the schema validation to pass when a non-required object is undefined, even if its schema contains required properties.

### GitHub Repo

https://github.com/getlarge/nx-heroku/blob/20-required-property-url-is-missing/e2e/nx-heroku-e2e/tests/nx-heroku.spec.ts#L65

### Steps to Reproduce

1. Install dependencies with NPM
2. run `nx run nx-heroku-e2e:e2e`

### Nx Report

```shell
Node   : 20.11.0
OS     : darwin-arm64
npm    : 10.2.4

nx                 : 18.0.8
@nx/js             : 18.0.8
@nx/jest           : 18.0.8
@nx/linter         : 18.0.8
@nx/eslint         : 18.0.8
@nx/workspace      : 18.0.8
@nx/devkit         : 18.0.8
@nx/eslint-plugin  : 18.0.8
@nx/node           : 18.0.8
@nx/plugin         : 18.0.8
@nrwl/tao          : 18.0.8
typescript         : 5.3.3
---------------------------------------
Community plugins:
@jscutlery/semver : 5.2.0
ngx-deploy-npm    : 8.0.1
---------------------------------------
Local workspace plugins:
	 @getlarge/nx-heroku
```

### Failure Logs

```shell
NX   Required property 'url' is missing
```

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Maybe related to #9208

### PR DESCRIPTION
**Pull request by AgentEnder**
Defaults causing an object to be defined causes some confusing behavior when a schema has defaults and required properties for a given object prop. If the required prop doesn't have a default value, and another property does, it becomes invalid to not pass the object when it would be valid had that default not been specified.

BREAKING CHANGE: Currently if an executor's schema provides some default values for an object's properties, those defaults cause the object to be defined. This changes that, such that the defaults are only applied if the object exists in the first place.

Fixes #23153

### CODE REVIEW

File: packages/nx/src/utils/params.ts [hunk 1]
```diff
@@ -555,20 +553,33 @@ function setPropertyDefault(
...
 
-    // If the property was initially undefined but no properties were added, we remove it again instead of having an {}
-    if (wasUndefined && Object.keys(opts[propName]).length === 0) {
-      delete opts[propName];
+  if (defaultValueToSet !== undefined) {
+    try {
+      validateProperty(propName, defaultValueToSet, schema, definitions);
+      opts[propName] = defaultValueToSet;
+    } catch (e) {
+      // If the default value is invalid, we don't set it...
```
Comment (FrozenPandaz) [inline packages/nx/src/utils/params.ts:580]: future: add a warning saying that the property was not applied because it was invalid and why it was invalid.

**Review by FrozenPandaz — APPROVED** [review]
