### PR TITLE
fix(misc): fix moving projects with standalone configuration

### LINKED ISSUE #6512: @nrwl/workspace:move resets standaloneConfig project, deletes project.json
## Current Behavior
When I rename a standaloneConfig package using `@nrwl/workspace:move`, it deletes the `project.json` file and moves the configuration back to `workspace.json`, resetting the standaloneConfig:
```
npm run nx -- g @nrwl/workspace:move --projectName nx-debug --destination nx-debug-app
```

## Expected Behavior
When I run the above command, I would expect the project.json file to be updated, not to be deleted, and I would expect the package to remain a standalone project.

While I have larger workspaces that are _not_ exhibiting this behavior (`move` works for them), they use the same version of nx (`12.6.2`); however, they were created with earlier versions of nx and migrated to latest, so it is unclear whether or not this is a regression.

## Steps to Reproduce
This repo is the result of creating a new workspace, converting to standalongConfig, and running the above command:
https://github.com/JoshuaCWebDeveloper/deubg-nx-move-standalone-001

You can use the commit history to view the state of the repo after each step. In short, to reproduce:
```
npx create-nx-workspace (nest)
npm run nx -- g @nrwl/workspace:convert-to-nx-project --all
npm run nx -- g @nrwl/workspace:move --projectName nx-debug --destination nx-debug-app
```

### Environment
```
> nx-debug@0.0.0 nx /home/joshua/WebDev/sandbox/nx-move-standalone-build-taret/nx-debug
> nx "report"


>  NX  Report complete - copy this into the issue template

  Node : 12.22.1
  OS   : linux x64
  npm  : 6.14.12
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.6.2
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.6.2
  @nrwl/eslint-plugin-nx : 12.6.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.2
  @nrwl/linter : 12.6.2
  @nrwl/nest : 12.6.2
  @nrwl/next : Not Found
  @nrwl/node : 12.6.2
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.2
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.2
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

### PR DESCRIPTION
**Pull request by leosvelperez**
## Current Behavior

Moving a project with a standalone configuration adds the updated configuration to workspace.json instead of updating the corresponding project.json. This happens when not all the projects are using standalone configuration or when the project being moved is the only project in the workspace.

## Expected Behavior

Moving a project with a standalone configuration should update the standalone configuration correctly.

## Related Issue(s)

Fixes #6512

### CODE REVIEW

File: packages/devkit/src/generators/project-configuration.ts [hunk 1]
```diff
@@ -205,6 +205,22 @@ export function readProjectConfiguration(
   return getProjectConfiguration(host, projectName, workspace, nxJson);
 }
 
+/**
+ * Returns if a project has a standalone configuration (project.json).
+ *
+ * @param host - the file system tree
+ * @param project - the project name
+ */
+export function isStandaloneProject(host: Tree, project: string): boolean {
```
Comment (FrozenPandaz) [inline packages/devkit/src/generators/project-configuration.ts:214]: Can we remove this and use `getWorkspaceLayout(host).standaloneAsDefault` instead?

File: packages/workspace/src/generators/move/lib/move-project-configuration.ts [hunk 2]
```diff
@@ -12,6 +13,7 @@ export function moveProjectConfiguration(
   schema: NormalizedSchema,
   projectConfig: ProjectConfiguration & NxJsonProjectConfiguration
 ) {
+  const isStandalone = isStandaloneProject(tree, schema.projectName);
```
Comment (FrozenPandaz) [inline packages/workspace/src/generators/move/lib/move-project-configuration.ts:16]: Can we use `getWorkspaceLayout(host).standaloneAsDefault` so we don't have to add the new function?

It should work in this case because the current move logic already moves the `project.json` file appropriately.

From what I saw, this could also be solved somewhat hackily by moving `addProjectConfiguration` after `removeProjectConfiguration`. But I think reading whether it should be standalone or not and then explicitly saying to add a standalone is a better option.

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/workspace/src/generators/move/lib/move-project-configuration.ts (hunk 2 above)
Comment (leosvelperez) [reply packages/workspace/src/generators/move/lib/move-project-configuration.ts:16]: That wouldn't be right for a couple of reasons:

- `getWorkspaceLayout(host).standaloneAsDefault` will only be `true` if all projects in the workspace are configured as standalone, you'd expect that to normally be the case, either all or none, but that's an assumption, not a fact. Even our generator to convert projects into standalone config offers the ability to specify a project, it's not mandatory to convert the whole workspace.
- It can't be solved by having `addProjectConfiguration` before `removeProjectConfiguration`, because there are cases where the project name for the destination is the same as the old destination (e.g. moving `domain-project` to `domain/project`, both results in the name `domain-project`). A couple of issues have been created because of that, and I previously worked on solving those. In that scenario, if you try to add the project first, you get an error because it already exists.

The need here is to know if the project being moved is configured as standalone or not, that doesn't match what `getWorkspaceLayout(host).standaloneAsDefault` returns (whether all projects in the workspace are configured as standalone).

Comment (FrozenPandaz) [reply packages/workspace/src/generators/move/lib/move-project-configuration.ts:16]: Ah okay, I see

**Review by FrozenPandaz — APPROVED** [review]
