### PR TITLE
fix(command-line): add ng command test on affected parallel

### LINKED ISSUE #700: Error when running affected:test with --parallel
Hi,
Apologies if this has been mentioned before or if I'm doing something stupid but I'm getting a "Cannot read property 'forEach' of undefined" when I try to run any of the affected commands with --parallel.
This is with version 6.2.0 but doesn't work with earlier versions.
Windows, Node v9.11.1

For example.

$ ./node_modules/.bin/nx affected:test a1d95f6dda5fd1a20f3ae3135255018d5cd825b1 f93c998bd93921b0cf4b639cea410a7a16a31b13 --parallel Testing a, b, c, d, e with flags: --no-watch
(node:15732) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at C:\Projects\blah\node_modules\@nrwl\schematics\src\command-line\affected.js:237:33
    at step (C:\Projects\blah\node_modules\@nrwl\schematics\src\command-line\affected.js:40:23)
    at Object.throw (C:\Projects\blah\node_modules\@nrwl\schematics\src\command-line\affected.js:21:53)
    at rejected (C:\Projects\blah\node_modules\@nrwl\schematics\src\command-line\affected.js:13:65)
    at <anonymous>
(node:15732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
not handled will terminate the Node.js process with a non-zero exit code.
Done in 8.67s.

Without trying to run in parallel everything works fine.

If anyone could point me in the right direction to either fix or diagnose the problem I would be very grateful.

Thanks.

### PR DESCRIPTION
**Pull request by bcabanes**
## Description
When running the affected command with the `--parallel` option, `npm-run-all` is used to achieve the parallel execution of the desired tasks. Because of the use of `npm-run-all`, the `ng` command should be visible and declared as script command in the `package.json` of your project.

This adds a verification before running the command with the `--parallel` option to make sure the `package.json` has the `ng: "ng"` command in the `scripts` section.
If not, it errors before trying with a specific message.

## Issue
close #700

### CODE REVIEW

File: packages/schematics/src/command-line/affected.ts [hunk 1]
```diff
@@ -277,6 +277,14 @@ async function runCommand(
   errorMessage: string
 ) {
   if (parsedArgs.parallel) {
+    // Make sure the `package.json` has the `ng: "ng"` command needed by `npm-run-all`
+    const packageJson = fs.readFileSync('./package.json').toString('utf-8');
+    if (!JSON.parse(packageJson).scripts.ng) {
+      console.log(
```
Comment (vsavkin) [inline packages/schematics/src/command-line/affected.ts]: change it to console.error

File: packages/schematics/src/command-line/affected.ts [hunk 2]
```diff
@@ -277,6 +277,14 @@ async function runCommand(
   errorMessage: string
 ) {
   if (parsedArgs.parallel) {
+    // Make sure the `package.json` has the `ng: "ng"` command needed by `npm-run-all`
+    const packageJson = fs.readFileSync('./package.json').toString('utf-8');
+    if (!JSON.parse(packageJson).scripts.ng) {
```
Comment (vsavkin) [inline packages/schematics/src/command-line/affected.ts]: check that the scripts property is there. You might have a package.json file without having any scripts.

Even though it isn't easy to invoke the affected command without npm scripts, it's possible

**Review by vsavkin — CHANGES_REQUESTED** [review]
Looks good. A few minor changes.

File: package.json [hunk 3]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "@nrwl/nx-source",
-  "version": "6.2.0",
+  "version": "6.2.1-beta.1",
```
Comment (vsavkin) [inline package.json]: Remove this
