### PR TITLE
fix(schematics): set lib npmScope when publishable

### LINKED ISSUE #677: Creating a publishable library doesn't set the npm scope
Creating a new publishable library, I expected that the created `package.json` in the libs/_newLib_ directory would reflect the npmScope set in `nx.json`. However, it does not. Is this desired behavior?

### Example:

*nx.json*
```
{
  "npmScope": "example",
  // ...
}

```

Running ``ng g lib test --publishable`` results in the creation of the follwing `libs/test/package.json`:
```
{
  "name": "test",
  // .....
}
```

#### Desired output:
```
{
  "name": "@example/test",
  // .....
}
```

### PR DESCRIPTION
**Pull request by bcabanes**
## Description
Update the lib's `package.json` name with the right prefix, when generating a lib with the `publishable` option set to `true`.

### Before
Running `ng g lib test --publishable` inside an "_example_" project:
```javascript
// libs/test/package.json
{
  "name": "test",
  // ...
}
```

### After
Running `ng g lib test --publishable` inside an "_example_" project:
```javascript
// libs/test/package.json
{
  "name": "@example/test",
  // ...
}
```

## Issue
close #677

### CODE REVIEW

File: packages/schematics/src/collection/library/index.ts [hunk 1]
```diff
@@ -369,6 +369,17 @@ function updateTsConfig(options: NormalizedSchema): Rule {
   ]);
 }
 
+function updateLibPackageNpmScope(options: NormalizedSchema): Rule {
+  return chain([
```
Comment (FrozenPandaz) [inline packages/schematics/src/collection/library/index.ts]: It would be easier to return this instead of a chain since it already returns a rule:
```ts
return updateJsonInTree('package.json', json => {
        json.name = `@${options.prefix}/${options.name}`;
        return json;
      });
```

**Review by FrozenPandaz — COMMENTED** [review]
Looks good, just one little change

**Review by FrozenPandaz — APPROVED** [review]
