### PR TITLE
fix(core): run-one should not log undefined as target name on failure

### LINKED ISSUE #14158: NX   Ran target undefined for project
### Current Behavior

From a new repo, if there are any failing tests in a Jest test suite, Nx outputs an error as in the title:

```
 >  NX   Ran target undefined for project todos (5s)

    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

### Expected Behavior

I would expect Nx to pick up the target correctly, i.e.

```
 >  NX   Ran target test for project todos (5s)

    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

### Github Repo

_No response_

### Steps to Reproduce

1. npx create-nx-workspace@latest --name=todos --preset=angular-monorepo --cli=nx --appName=todos --style=scss --nxCloud=false
2. echo "describe('AppComponent', () => { it('should fail here', () => { expect(false).toBe(true); }); });" > ./todos/apps/todos/src/app/app.component.spec.ts
3. cd todos && npx nx run todos:test

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   npm  : 8.11.0

   nx : 15.4.4
   @nrwl/angular : 15.4.4
   @nrwl/cypress : 15.4.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.4
   @nrwl/js : 15.4.4
   @nrwl/linter : 15.4.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.4
   @nrwl/workspace : 15.4.4
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AgentEnder**
## Related Issue(s)

Fixes #14158

### CODE REVIEW

File: packages/nx/src/utils/command-line-utils.ts [hunk 1]
```diff
@@ -11,7 +11,6 @@ export interface RawNxArgs extends NxArgs {
 }
 
 export interface NxArgs {
-  target?: string;
```
Comment (AgentEnder) [inline packages/nx/src/utils/command-line-utils.ts:14]: This property is explicitly deleted in `splitArgsIntoNxArgsAndOverrides`, it shouldn't exist anymore and removing it would have caused a build error and prevented this bug from occurring:

```typescript
  if (args['target'] && !args['targets']) {
    args['targets'] = [args['target']];
  }
  delete args['target'];
  delete args['t'];
```

**Review by barbados-clemens — APPROVED** [review]

**Review by FrozenPandaz — APPROVED** [review]

**Comment by Michsior14** [comment]
Looks like this will also resolve #14234
