### PR TITLE
fix(core): forward args provided to the nx add command to the invoked init generator

### LINKED ISSUE #22718: nx add @angular/localize fails with SchematicsException
### Current Behavior

I am trying to use `nx add` to add localization to an angular app that is part of an nx workspace but the command fails with error `SchematicsException [Error]: Option "project" is required.`

### Expected Behavior

The command should not fail and localization should be configured on the angular app.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Create a new nx workspace with an angular app: `npx create-nx-workspace@latest angular-monorepo --preset=angular-monorepo`
2. From the workspace root, issue the following command to add localization to the angular app: `nx add @angular/localize --project=angular-monorepo`

The command fails with error `SchematicsException [Error]: Option "project" is required.`

### Nx Report

```shell
Node   : 20.12.0
OS     : linux-x64
npm    : 10.5.0

nx (global)        : 18.2.1
nx                 : 18.2.3
@nx/js             : 18.2.3
@nx/jest           : 18.2.3
@nx/linter         : 18.2.3
@nx/eslint         : 18.2.3
@nx/workspace      : 18.2.3
@nx/angular        : 18.2.3
@nx/cypress        : 18.2.3
@nx/devkit         : 18.2.3
@nx/eslint-plugin  : 18.2.3
@nrwl/tao          : 18.2.3
@nx/web            : 18.2.3
@nx/webpack        : 18.2.3
typescript         : 5.4.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell
user@MEG-X570:~/Tmp/nx-bug/angular-monorepo$ nx add @angular/localize --project=angular-monorepo

✔ Installing @angular/localize@latest...
✖ Initializing @angular/localize...

Command failed: npx nx g @angular/localize:ng-add --keepExistingVersions
SchematicsException [Error]: Option "project" is required.
    at /home/user/Tmp/nx-bug/angular-monorepo/node_modules/@angular/localize/schematics/ng-add/ng_add_bundle.js:127:13
    at callRuleAsync (/home/user/Tmp/nx-bug/angular-monorepo/node_modules/@angular-devkit/schematics/src/rules/call.js:77:24)
    at /home/user/Tmp/nx-bug/angular-monorepo/node_modules/@angular-devkit/schematics/src/rules/call.js:72:40
    at Observable._subscribe (/home/user/Tmp/nx-bug/angular-monorepo/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:31)
    at Observable._trySubscribe (/home/user/Tmp/nx-bug/angular-monorepo/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
    at /home/user/Tmp/nx-bug/angular-monorepo/node_modules/rxjs/dist/cjs/internal/Observable.js:35:31
    at Object.errorContext (/home/user/Tmp/nx-bug/angular-monorepo/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at Observable.subscribe (/home/user/Tmp/nx-bug/angular-monorepo/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
    at /home/user/Tmp/nx-bug/angular-monorepo/node_modules/rxjs/dist/cjs/internal/operators/map.js:9:16
    at OperatorSubscriber.<anonymous> (/home/user/Tmp/nx-bug/angular-monorepo/node_modules/rxjs/dist/cjs/internal/util/lift.js:14:28)


 NX   Failed to initialize @angular/localize. Please check the error above for more details.
```

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I have reproduced this in a brand new nx workspace using the most recent version of nx.

### PR DESCRIPTION
**Pull request by leosvelperez**
## Related Issue(s)

Fixes #22718

### CODE REVIEW

**Review by AgentEnder — APPROVED** [review]

File: packages/nx/src/command-line/add/add.ts [hunk 1]
```diff
@@ -175,6 +176,21 @@ function parsePackageSpecifier(
...
 
+const knownCommandArgs = [
+  'packageSpecifier',
+  'updatePackageScripts',
+  'verbose',
+  '__overrides_unparsed__',
+  '$0',
+];
+function getExtraArgs(options: AddOptions): string[] {
+  const unknownOptions = Object.keys(options)
```
Comment (FrozenPandaz) [inline packages/nx/src/command-line/add/add.ts:187]: I believe if you set the yargs parser configuration like here then you won't see other options in `options`, only `__unparsed_options__`

https://github.com/nrwl/nx/blob/322ecf7a088eb195da289674224eccb9f3320075/packages/nx/src/command-line/yargs-utils/shared-options.ts#L141

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/nx/src/command-line/add/add.ts (hunk 1 above)
Comment (leosvelperez) [reply packages/nx/src/command-line/add/add.ts]: Nice! TIL

**Review by FrozenPandaz — APPROVED** [review]
