### PR TITLE
fix(core): project graph creation processes project dependencies correctly

### LINKED ISSUE #31454: New Versioning protocol incorrectly bumps downstream pinned versions
### Current Behavior

Picture three package.jsons:

```
{
  "name": "@company/upstream",
  "version": "8.1.0"
}

{
  "name": "@company/downstream-pinned",
  "version": "0.0.1"
  "dependencies": {
    "@company/upstream": "7.3.4"
  }
}

{
  "name": "@company/downstream-workspace",
  "version": "0.0.1"
  "dependencies": {
    "@company/upstream": "workspace:*"
  }
}
```

Currently, when we make a change to `upstream`, it will replace the dependency in `@company/downstream-pinned` with 8.1.0.

### Expected Behavior

In the legacy versioning implementation, bumping upstream would result in no dependencies being incremented in the example above, and pnpm would handle things via the workspace using `preserveLocalDependencyProtocols`.

We have a specific usage for pinning dependencies that also exist in the local workspace and need a way to control this. It helps us migrate packages from outside the repo into the repo (we use syncpack to allow exceptions and work our way through aligning them to current).

### GitHub Repo

_No response_

### Steps to Reproduce

1. Create a repo where a package depends on the pinned version of another in-workspace package
2. Update that package
3. Compare results with both sets of nx.json settings (see below)

### Nx Report

```shell
Node           : 20.19.1
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 10.11.0

nx                     : 21.2.0-beta.1
@nx/js                 : 21.1.2
@nx/jest               : 21.2.0-beta.1
@nx/eslint             : 21.2.0-beta.1
@nx/workspace          : 21.2.0-beta.1
@nx/cypress            : 21.2.0-beta.1
@nx/devkit             : 21.2.0-beta.1
@nx/eslint-plugin      : 21.2.0-beta.1
@nx/module-federation  : 21.2.0-beta.1
@nx/plugin             : 21.2.0-beta.1
@nx/react              : 21.2.0-beta.1
@nx/storybook          : 21.2.0-beta.1
@nx/vite               : 21.2.0-beta.1
@nx/web                : 21.2.0-beta.1
typescript             : 5.5.4

---------------------------------------
Nx key licensed packages
Licensed to Block Inc..

@nx/powerpack-s3-cache  : 2.0.3

---------------------------------------
Registered Plugins:
@nx/vite/plugin
@squareup/service-dashboard-web-runtime/nx-plugin
@nx/storybook/plugin
@squareup/nx-lint-plugin
@squareup/nx-stats-plugin
@squareup/service-i18n/nx-plugin
---------------------------------------
Community plugins:
@squareup/service-i18n : 0.94.1
---------------------------------------
Local workspace plugins:
         @squareup/service-i18n
         @squareup/migrate
---------------------------------------
Cache Usage: 1.35 GB / 92.64 GB
---------------------------------------
```

### Failure Logs

```shell

```

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

nx.json

```
    // New generator config
    "version": {
      "specifierSource": "conventional-commits",
      "currentVersionResolver": "git-tag",
      "fallbackCurrentVersionResolver": "disk",
      "versionActionsOptions": {
        "skipLockFileUpdate": true,
      },
      "preVersionCommand": "nx run-many -t build",
    },

    // Old generator
    "version": {
      "generatorOptions": {
        "specifierSource": "conventional-commits",
        "currentVersionResolver": "git-tag",
        "skipLockFileUpdate": true,
        "fallbackCurrentVersionResolver": "disk",
        "preserveLocalDependencyProtocols": true,
      },
      "preVersionCommand": "nx run-many -t build",
      "useLegacyVersioning": true,
    },
```

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

  The project graph build process incorrectly handles dependencies when workspace projects have
  different versions or are referenced via specific version ranges. This causes several issues:

  1. NPM lockfile parser crashes when encountering symlinked nested dependencies in workspaces
  (which don't have versions)
  2. Package.json dependencies that reference workspace projects with specific versions (e.g.,
  "proj4": "1.0.0" when workspace has "version": "2.0.0") incorrectly resolve to the workspace
  project instead of the installed npm package
  3. Version ranges and file references to workspace projects are not properly validated

 ## Expected Behavior

  The dependency resolution should:
  - Handle symlinked workspace packages in npm lockfiles without crashing
  - Correctly differentiate between workspace projects and npm packages when specific versions are
   referenced
  - Properly validate version ranges against workspace package versions using semver
  - Support file references (e.g., "file:../proj6") for workspace dependencies
  - Only resolve to workspace projects when the version constraint is satisfied or when using
  wildcards

## Notes
This has inadvertently caused issues when calculating which manifest files need to be updated in the JSVersionActions / Nx Release for Npm Packages

## Related Issues

Fixes #31454

### CODE REVIEW

File: packages/nx/src/plugins/js/project-graph/build-dependencies/target-project-locator.ts [hunk 1]
```diff
@@ -323,10 +323,47 @@ export class TargetProjectLocator {
...
+
+    if (!maybeDepMetadata?.isInPackageManagerWorkspaces) {
+      return null;
+    }
+
+    const normalizedRange = packageVersion.replace('workspace:', '');
+
+    if (normalizedRange === '*') {
+      return maybeDep?.name;
+    }
```
Comment (comp615) [inline packages/nx/src/plugins/js/project-graph/build-dependencies/target-project-locator.ts]: I think this is [pnpm](https://pnpm.io/workspaces#publishing-workspace-packages); fwiw we use `workspace:^` here, so might be good to check for more symbols

**Review by FrozenPandaz — APPROVED** [review]
