### PR TITLE
fix(vitest): prevent config double-merge causing array duplication

### LINKED ISSUE #33591: NX passes vitest config as cli options when starting vitest and breaks browser mode
### Current Behavior

Testing a project with browser mode doesn't work due to `browser.instances` being duplicated.
It's similar to this issue:
https://github.com/vitest-dev/vitest/issues/7284.

### Expected Behavior

Test runs without problems.

### GitHub Repo

_No response_

### Steps to Reproduce

`nx test my-project`

with the following `vite.config.ts`:

```ts
import { nxCopyAssetsPlugin } from "@nx/vite/plugins/nx-copy-assets.plugin";
import { nxViteTsPaths } from "@nx/vite/plugins/nx-tsconfig-paths.plugin";
import react from "@vitejs/plugin-react";
import { playwright } from "@vitest/browser-playwright";
import { isCI } from "ci-info";
import { defineConfig } from "vite";

export default defineConfig(() => ({
  root: __dirname,
  plugins: [react(), nxViteTsPaths(), nxCopyAssetsPlugin(["*.md"])],
  test: {
    bail: isCI ? 1 : undefined,
    browser: {
      enabled: true,
      provider: playwright({
        launchOptions: {
          executablePath: process.env.CI
            ? "/usr/bin/chromium-browser"
            : undefined,
        },
      }),
      viewport: {
        width: 1280,
        height: 720,
      },
      instances: [{ browser: "chromium" }],
    },
    watch: false,
    globals: true,
    environment: "jsdom",
    include: ["src/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    reporters: ["default"],
  },
}));
```

### Nx Report

```shell
Node           : 22.18.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 10.15.1

nx (global)        : 22.0.3
nx                 : 22.1.0
@nx/js             : 22.1.0
@nx/jest           : 22.1.0
@nx/eslint         : 22.1.0
@nx/workspace      : 22.1.0
@nx/devkit         : 22.1.0
@nx/eslint-plugin  : 22.1.0
@nx/next           : 22.1.0
@nx/playwright     : 22.1.0
@nx/plugin         : 22.1.0
@nx/react          : 22.1.0
@nx/rollup         : 22.1.0
@nx/vite           : 22.1.0
@nx/web            : 22.1.0
typescript         : 5.9.3
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
---------------------------------------
Community plugins:
@imc-trading/nx-helm   : 0.1.3
@imc-trading/nx-web    : 2.0.4
@imc-trading/webgui    : 1.0.4
@jscutlery/semver      : 5.7.1
@nx-tools/nx-container : 7.1.0
ngx-deploy-npm         : 9.0.0
---------------------------------------
Local workspace plugins:
@imc-trading/nx-quicktype
@imc-trading/nx-nexus
---------------------------------------
Cache Usage: 1.21 GB / 92.64 GB
```

### Failure Logs

```shell
NX   The browser configuration must have a "name" property. This is a bug in Vitest. Please, open a new issue with reproduction

Error: The browser configuration must have a "name" property. This is a bug in Vitest. Please, open a new issue with reproduction
    at file:///Users/me/code/frontend/node_modules/.pnpm/vitest@4.0.13_@opentelemetry+api@1.9.0_@types+debug@4.1.12_@types+node@22.19.0_@vitest+_e50cc80eb224781ae0acf429358564e6/node_modules/vitest/dist/chunks/cli-api.CdZ6wo9-.js:10085:28
    at Array.forEach (<anonymous>)
    at file:///Users/me/code/frontend/node_modules/.pnpm/vitest@4.0.13_@opentelemetry+api@1.9.0_@types+debug@4.1.12_@types+node@22.19.0_@vitest+_e50cc80eb224781ae0acf429358564e6/node_modules/vitest/dist/chunks/cli-api.CdZ6wo9-.js:10077:21
    at Array.forEach (<anonymous>)
    at resolveBrowserProjects (file:///Users/me/code/frontend/node_modules/.pnpm/vitest@4.0.13_@opentelemetry+api@1.9.0_@types+debug@4.1.12_@types+node@22.19.0_@vitest+_e50cc80eb224781ae0acf429358564e6/node_modules/vitest/dist/chunks/cli-api.CdZ6wo9-.js:10059:19)
    at Vitest.resolveProjects (file:///Users/me/code/frontend/node_modules/.pnpm/vitest@4.0.13_@opentelemetry+api@1.9.0_@types+debug@4.1.12_@types+node@22.19.0_@vitest+_e50cc80eb224781ae0acf429358564e6/node_modules/vitest/dist/chunks/cli-api.CdZ6wo9-.js:11972:10)
    at Vitest._setServer (file:///Users/me/code/frontend/node_modules/.pnpm/vitest@4.0.13_@opentelemetry+api@1.9.0_@types+debug@4.1.12_@types+node@22.19.0_@vitest+_e50cc80eb224781ae0acf429358564e6/node_modules/vitest/dist/chunks/cli-api.CdZ6wo9-.js:11845:31)
    at BasicMinimalPluginContext.handler (file:///Users/me/code/frontend/node_modules/.pnpm/vitest@4.0.13_@opentelemetry+api@1.9.0_@types+debug@4.1.12_@types+node@22.19.0_@vitest+_e50cc80eb224781ae0acf429358564e6/node_modules/vitest/dist/chunks/cli-api.CdZ6wo9-.js:12739:6)
    at _createServer (file:///Users/me/code/frontend/node_modules/.pnpm/vite@7.1.9_@types+node@22.19.0_jiti@2.4.2_less@4.1.3_sass-embedded@1.93.2_sass@1.93.2_s_407cc9ddc87518a5567552b802ce9211/node_modules/vite/dist/node/chunks/dep-Chhhsdoe.js:28282:86)
    at createViteServer (file:///Users/me/code/frontend/node_modules/.pnpm/vitest@4.0.13_@opentelemetry+api@1.9.0_@types+debug@4.1.12_@types+node@22.19.0_@vitest+_e50cc80eb224781ae0acf429358564e6/node_modules/vitest/dist/chunks/cli-api.CdZ6wo9-.js:9519:17)
```

### Package Manager Version

_No response_

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This used to work with vitest 3.1.3. Stopped working when updating from NX 21.0.4 to 22.1.0 where we also updating vitest to v4.

Where it goes wrong:
https://github.com/vitest-dev/vitest/blob/229b5b3b352b52b82aecf258bea7cb65670f2ae2/packages/vitest/src/node/config/resolveConfig.ts#L239-L250
(The config and cli options are merged.)

Vitest resolves the configuration from the `vite.config.ts` file already, so NX should not pass them as cli options.

I have solved for now on our side with this pnpm patch:

```diff
diff --git a/src/executors/test/vitest.impl.js b/src/executors/test/vitest.impl.js
index 55a72cfb1faa047f0f4bb8a9d2e612b6b48afdcc..bcb55071f4f5758b421d804e15525b32da512d79 100644
--- a/src/executors/test/vitest.impl.js
+++ b/src/executors/test/vitest.impl.js
@@ -23,6 +23,7 @@ async function* vitestExecutor(options, context) {
         resolvedOptions['reporters'] = [resolvedOptions['reporters']];
     }
     resolvedOptions['reporters'].push(nxReporter);
+    delete resolvedOptions["browser"];
     const cliFilters = options.testFiles ?? [];
     const ctx = await startVitest(resolvedOptions['mode'] ?? 'test', cliFilters, resolvedOptions);
     let hasErrors = false;
```

But probably not a long-term solution. It will probably be necessary to avoid passing the resolved config as the cli options argument.

### PR DESCRIPTION
**Pull request by leosvelperez**
## Current Behavior

Running `nx test` with Vitest browser mode fails with error:

> "The browser configuration must have a 'name' property"

Array configs like `browser.instances` and `reporters` get duplicated, breaking tests.

## Expected Behavior

Vitest browser mode and array configurations work correctly without duplication.

## Related Issue(s)

Fixes #33591

### CODE REVIEW

File: packages/vitest/src/executors/test/lib/utils.ts [hunk 1]
```diff
@@ -40,52 +35,56 @@ export async function getOptions(
 
   const resolved = await loadConfigFromFile(
     {
-      mode: options?.mode ?? 'production',
+      mode: options?.mode ?? 'test',
```
Comment (leosvelperez) [inline packages/vitest/src/executors/test/lib/utils.ts:43]: Changed the default from `production` to `test` since this is the mode used for loading the Vite config during test execution.

File: packages/vitest/src/executors/test/vitest.impl.ts [hunk 2]
```diff
@@ -35,7 +35,7 @@ export async function* vitestExecutor(
   const cliFilters = options.testFiles ?? [];
 
   const ctx = await startVitest(
-    resolvedOptions['mode'] ?? 'test',
+    options.runMode ?? 'test',
```
Comment (leosvelperez) [inline packages/vitest/src/executors/test/vitest.impl.ts:38]: Previously used `resolvedOptions['mode']` which conflates Vite mode with Vitest run mode. Now uses separate `runMode` option for the VitestRunMode parameter (`test` vs `benchmark`).

**Review by Coly010 — APPROVED** [review]
