### PR TITLE
 fix(core): find the most qualifying project for a changed file

### LINKED ISSUE #2466: affected:libs logic is sensitive to the project names and order
## Expected Behavior

`nx affected:libs` scripts should correctly identify libs affected by a change.

## Current Behavior
Under certain conditions `nx affected:libs` marks unrelated libs as affected and ignores the correct libs.

## Failure Information (for bugs)
`nx affected:libs` prints wrong lib names as the result

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. setup a Nx workspace (I cloned https://github.com/nrwl/nx-examples as due to #2465 I'm unable to generate a new workspace)
2. create a new lib with the name that partially matches an existing lib (important!)

```bash
npm run ng -- g lib cart-page-header --directory cart --style=scss
```
angular-cli created a new lib `cart-cart-page-header` that completely includes the name of the existing `cart-cart-page` library
3. commit the change (optional?)
4. make any change in the `cart-cart-page-header` alone.
5. run `npm run affected:libs`
6. observe the output

```
>  NX  Affected libs:

  - cart-cart-page
```

Expected:

```
>  NX  Affected libs:

  - cart-cart-page-header

```

### Context

Please provide any relevant information about your setup:
```
$ npm -v
6.4.0
$ node -v
v11.15.0
```
```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 8.12.0
  @nrwl/cli : 8.12.0
  @nrwl/cypress : 8.12.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.12.0
  @nrwl/linter : 8.12.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 8.12.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.12.0
  @nrwl/web : 8.12.0
  @nrwl/workspace : 8.12.0
  typescript : 3.5.3
```

## Other

a repro repo is here https://github.com/x87/nx-affected
switch to the `test` branch and run `npm run affected:libs`

### PR DESCRIPTION
**Pull request by x87**
Resolved #2466

### CODE REVIEW

File: packages/workspace/src/core/affected-project-graph/locators/workspace-projects.ts [hunk 1]
```diff
@@ -4,11 +4,17 @@ export const getTouchedProjects: TouchedProjectLocator = (
   touchedFiles,
   workspaceJson
 ): string[] => {
+  // sort project names with the most nested first,
+  // e.g. ['libs/a/b/c', 'libs/a/b', 'libs/a']
+  const projectKeys = Object.keys(workspaceJson.projects).sort((a, b) =>
+    b.localeCompare(a)
```
Comment (vsavkin) [inline packages/workspace/src/core/affected-project-graph/locators/workspace-projects.ts]: TargetProjectLocator does similar sorting, but uses project roots. I tink using project root seems more correct here. What do you think?

Comment (vsavkin) [reply packages/workspace/src/core/affected-project-graph/locators/workspace-projects.ts]: Can we have one function that does the sorting? Or maybe sort `workspaceJson.projects` when we read it?

Comment (x87) [reply packages/workspace/src/core/affected-project-graph/locators/workspace-projects.ts]: @vsavkin you're right, we should sort by the root value, not the project name (the example given in the comment implies that).

By "sorting when reading" you mean to modify the `readWorkspaceJson` function to return projects descendingly sorted by the root?

Comment (x87) [reply packages/workspace/src/core/affected-project-graph/locators/workspace-projects.ts]: I have updated the implementation to use the root path instead of the project name. I looked into  `TargetProjectLocator` but `workspaceJson.projects` object seems to be not compatible with `ProjectGraphNodeRecords` used there so I don't know how to re-use that code without extra mapping/refactoring.

Comment (vsavkin) [reply packages/workspace/src/core/affected-project-graph/locators/workspace-projects.ts]: Thank you very much! I'm going to merge this.
