### PR TITLE
fix(core): correctly move project and target strings

### LINKED ISSUE #19493: `nx serve` breaks after moving a project into a subdirectory.
### Current Behavior

After generating a React app using Vite, `nx serve foobar` works. After running `nx g mv` to move the app into `apps/foobar`, `nx serve foobar` breaks. If the project is moved out of a nested folder (e.g. moving it back from `apps/foobar` to just `foobar`), `nx serve` starts working again.

I'm assuming this is an issue specific to nx+Vite as the apps in the nx-examples repository are in an `apps` subfolder and don't exhibit the issue. The stack trace for the error ends with `@nx/devkit` and `@nx/vite`, so I figured I'd start here. If this issue would be better reported in the Vite repository, please let me know.

### Expected Behavior

`nx serve` should not break when the project is in a subfolder.

### GitHub Repo

_No response_

### Steps to Reproduce

This can be repro'd using a new workspace. I replicated the issue by running these commands:

1. `npx create-nx-workspace@latest foobar --preset=ts`
  a. Disable distributed caching
2. `cd` into the workspace folder
3. `npm i @nx/react`
4. `nx g @nx/react:app foo`
  a. Choose CSS
  b. Don't add React Router
  c. Choose Cypress
  d. Choose Vite
5. Run `nx serve foo` and confirm that it works
6. Run `nx g mv --project foo --destination apps/foo`
  a. Choose "as provided"
  b. Choose true for whether to configure nx to always take the project name and destination as provided
7. Run `nx serve foo`. It should fail.

As a bonus, after getting the failure described above:
1. Run `nx g mv --project foo --destination foo`
2. Run `nx serve foo`. It should be working again.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.8.0
   OS     : linux-x64
   npm    : 10.1.0
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/react          : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/vite           : 16.10.0
   @nx/web            : 16.10.0
   typescript         : 5.1.6
```


### Failure Logs

```shell
> nx run foo:serve:development                                                                                                                                                                               
                                                                                                                                                                                                             
                                                                                                                                                                                                             
 >  NX   Cannot read properties of undefined (reading 'executor')                                                                                                                                            
                                                                                                                                                                                                             
                                                                                                                                                                                                             
TypeError: Cannot read properties of undefined (reading 'executor')                                                                                                                                          
    at readTargetOptions (/tmp/bug/foobar/node_modules/@nx/devkit/src/executors/read-target-options.js:24:60)                                                                                                
    at getNxTargetOptions (/tmp/bug/foobar/node_modules/@nx/vite/src/utils/options-utils.js:137:42)                                                                                                          
    at viteDevServerExecutor (/tmp/bug/foobar/node_modules/@nx/vite/src/executors/dev-server/dev-server.impl.js:24:69)                                                                                       
    at viteDevServerExecutor.next (<anonymous>)
    at getLastValueFromAsyncIterableIterator (/tmp/bug/foobar/node_modules/nx/src/utils/async-iterator.js:13:27)
    at iteratorToProcessStatusCode (/tmp/bug/foobar/node_modules/nx/src/command-line/run/run.js:41:94) 
    at /tmp/bug/foobar/node_modules/nx/src/command-line/run/run.js:154:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/tmp/bug/foobar/node_modules/nx/src/utils/params.js:9:16)
    at async process.<anonymous> (/tmp/bug/foobar/node_modules/nx/bin/run-executor.js:59:28)
```


### Package Manager Version

npm v10.1.0

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The crash occurs in this function, which is in `@nx/devkit/src/executors/read-target-options.js`:
```
function readTargetOptions({ project, target, configuration }, context) {
    const projectConfiguration = (context.workspace || context.projectsConfigurations).projects[project];
    if (!projectConfiguration) {
        throw new Error(`Unable to find project ${project}`);
    }
    console.log(projectConfiguration);
    console.log(target);
    const targetConfiguration = projectConfiguration.targets[target];
    // TODO(v18): remove Workspaces.
    const ws = new Workspaces(context.root);
    const [nodeModule, executorName] = targetConfiguration.executor.split(':');
    const { schema } = getExecutorInformation
        ? getExecutorInformation(nodeModule, executorName, context.root)
        : // TODO(v18): remove readExecutor. This is to be backwards compatible with Nx 16.5 and below.
            ws.readExecutor(nodeModule, executorName);
    const defaultProject = calculateDefaultProjectName
        ? calculateDefaultProjectName(context.cwd, context.root, { version: 2, projects: context.projectsConfigurations.projects }, context.nxJsonConfiguration)
        : // TODO(v18): remove calculateDefaultProjectName. This is to be backwards compatible with Nx 16.5 and below.
            ws.calculateDefaultProjectName(context.cwd, { version: 2, projects: context.projectsConfigurations.projects }, context.nxJsonConfiguration);
    return combineOptionsForExecutor({}, configuration ?? targetConfiguration.defaultConfiguration ?? '', targetConfiguration, schema, defaultProject, (0, path_1.relative)(context.root, context.cwd));
}
```
I dumped `projectConfiguration`, which looked as expected:
```
{                                                                                                                                                                                                            
  name: 'foo',                                                                                                                                                                                               
  root: 'apps/foo',                                                                                                                                                                                          
  '$schema': '../../node_modules/nx/schemas/project-schema.json',                                                                                                                                            
  sourceRoot: 'apps/foo/src',                                                                                                                                                                                
  projectType: 'application',
  targets: {
    build: {
      dependsOn: [Array],
      inputs: [Array],
      executor: '@nx/vite:build',
      outputs: [Array],
      defaultConfiguration: 'production',
      options: [Object],
      configurations: [Object]
    },
    serve: {
      executor: '@nx/vite:dev-server',
      defaultConfiguration: 'development',
      options: [Object],
      configurations: [Object]
    },
    preview: {
      executor: '@nx/vite:preview-server',
      defaultConfiguration: 'development',
      options: [Object],
      configurations: [Object]
    },
    test: {
      inputs: [Array],
      executor: '@nx/vite:test',
      outputs: [Array],
      options: [Object],
      configurations: {}
    },
    lint: {
      inputs: [Array],
      executor: '@nx/linter:eslint',
      outputs: [Array],
      options: [Object],
      configurations: {}
    },
    'serve-static': {
      executor: '@nx/web:file-server',
      options: [Object],
      configurations: {}
    }
  },
  tags: [],
  implicitDependencies: []
}
```
However, `target` was set to `apps/foo` when the project was in `apps/foo` and was set to `build` when in `<ws_root>/foo`.

### PR DESCRIPTION
**Pull request by mandarini**
## Current Behavior
There's an issue with the `move` generator if `projectName === path`, where the target string (`my-app:build:production`) was being replaced and resulting in `my-destination/my-new-name:build:production` because of:

```
    newProjectString = newProjectString.replace(
      new RegExp(projectConfig.root, 'g'),
      schema.relativeToRootDestination
    );
```

## Expected Behavior

Target string should be `new-name:build:production` instead of `new-path:build:production`.
So we need to safeguard for this, and first replace the name in target strings and then replace any paths.

## Related Issue(s)

Fixes #19493

### CODE REVIEW

File: packages/workspace/src/generators/move/lib/create-project-configuration-in-new-destination.ts [hunk 1]
```diff
@@ -35,8 +36,23 @@ export function createProjectConfigurationInNewDestination(
...
   } else {
+    // There's another issue if project name === path, where the target
+    // string (my-app:build:production) was being replaced
+    // and resulting in my-destination/my-new-name:build:production
+
+    // So we need to safeguard for this, and first replace the name in target strings
+    // and then replace any paths.
+
+    // Only change the target strings (my-app:build:production)
+    newProjectString = newProjectString.replace(
```
Comment (jaysoo) [inline packages/workspace/src/generators/move/lib/create-project-configuration-in-new-destination.ts:47]: This is needed, the old and new names might be the same anyway.

Comment (mandarini) [reply packages/workspace/src/generators/move/lib/create-project-configuration-in-new-destination.ts:47]: If they are not, though?

Comment (jaysoo) [reply packages/workspace/src/generators/move/lib/create-project-configuration-in-new-destination.ts:47]: I look like we rename target string in subsequent functions like `updateBuildTargets`. So this would make those obsolete, worth taking a look at whether we can remove some of those logic?

**Review by jaysoo — APPROVED** [review]

**Review by JamesHenry — APPROVED** [review]
