### PR TITLE
fix(core): daemon client reconnection on server restart

### LINKED ISSUE #29118: NX   Daemon process terminated and closed the connection when reading env vars "process.env.var_name"
### Current Behavior

I tried to consume an environment variable from .env file inside my nestjs application

`import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  getData(): { message: string } {
    return { message: `Hello ${process.env.WELCOME_MESSAGE}` };
  }
}`

but I get 
_** NX   Daemon process terminated and closed the connection**_

### Expected Behavior

NX should load and read the env variables from .env file inside my application 

### GitHub Repo

_No response_

### Steps to Reproduce

1. create nx workspace
2. add nestjs applcation
3. add .env file with env vars
4. try to read them inside a service or a controller using process.env.var_name

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 19.6.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 9.4.0

nx (global)        : 20.1.2
nx                 : 20.1.2
@nx/js             : 20.1.4
@nx/jest           : 20.1.2
@nx/eslint         : 20.1.2
@nx/workspace      : 20.1.2
@nx/angular        : 20.1.4
@nx/devkit         : 20.1.4
@nx/eslint-plugin  : 20.1.2
@nx/nest           : 20.1.2
@nx/node           : 20.1.2
@nx/web            : 20.1.4
@nx/webpack        : 20.1.2
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
angular-eslint : 18.4.2
---------------------------------------
The following packages should match the installed version of nx
  - @nx/js@20.1.4
  - @nx/angular@20.1.4
  - @nx/devkit@20.1.4
  - @nx/web@20.1.4

To fix this, run `nx migrate nx@20.1.4`
```

### Failure Logs

```shell
NX   Daemon process terminated and closed the connection

Please rerun the command, which will restart the daemon.
If you get this error again, check for any errors in the daemon process logs found in: /Users/mohammedfateh/personal-projects/hireoverflow/hireoverflow/.nx/workspace-data/d/daemon.log


—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target serve for project hireoverflow-api and 1 task it depends on failed

Failed tasks:

- hireoverflow-api:serve:development

Hint: run the command with --verbose for more details.


 NX   Nx Cloud Error

Error: write EPIPE

Messages from the log:
[NX Daemon Server] - 2024-11-29T12:37:49.122Z - [WATCHER]: Stopping the watcher for /Users/mohammedfateh/personal-projects/hireoverflow/hireoverflow (sources)
[NX Daemon Server] - 2024-11-29T12:37:49.122Z - [WATCHER]: Stopping the watcher for /Users/mohammedfateh/personal-projects/hireoverflow/hireoverflow (outputs)
[NX Daemon Server] - 2024-11-29T12:37:49.122Z - Server stopped because: "this process is no longer the current daemon (native)"
[NX Daemon Server] - 2024-11-29T12:37:49.122Z - Started listening on: /var/folders/gp/yykpgzz93snf2t4ml9_p56yr0000gp/T/f41878eefe/d.sock
[NX Daemon Server] - 2024-11-29T12:37:49.125Z - [WATCHER]: Subscribed to changes within: /Users/mohammedfateh/personal-projects/hireoverflow/hireoverflow (native)
[NX Daemon Server] - 2024-11-29T12:37:49.126Z - Started listening on: /var/folders/gp/yykpgzz93snf2t4ml9_p56yr0000gp/T/f41878eefe/d.sock
[NX Daemon Server] - 2024-11-29T12:37:49.130Z - [WATCHER]: Subscribed to changes within: /Users/mohammedfateh/personal-projects/hireoverflow/hireoverflow (native)
[NX Daemon Server] - 2024-11-29T12:37:49.137Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-11-29T12:37:49.137Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-11-29T12:37:49.138Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-11-29T12:37:49.139Z - [REQUEST]: Responding to the client. recordOutputsHash
[NX Daemon Server] - 2024-11-29T12:37:49.139Z - Done responding to the client recordOutputsHash
[NX Daemon Server] - 2024-11-29T12:37:49.139Z - Handled RECORD_OUTPUTS_HASH. Handling time: 0. Response time: 0.
[NX Daemon Server] - 2024-11-29T12:37:49.140Z - Started listening on: /var/folders/gp/yykpgzz93snf2t4ml9_p56yr0000gp/T/f41878eefe/d.sock
[NX Daemon Server] - 2024-11-29T12:37:49.142Z - [WATCHER]: Subscribed to changes within: /Users/mohammedfateh/personal-projects/hireoverflow/hireoverflow (native)
[NX Daemon Server] - 2024-11-29T12:37:49.187Z - [WATCHER]: Stopping the watcher for /Users/mohammedfateh/personal-projects/hireoverflow/hireoverflow (sources)
[NX Daemon Server] - 2024-11-29T12:37:49.187Z - [WATCHER]: Stopping the watcher for /Users/mohammedfateh/personal-projects/hireoverflow/hireoverflow (outputs)
[NX Daemon Server] - 2024-11-29T12:37:49.196Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2024-11-29T12:37:49.196Z - [WATCHER]: Stopping the watcher for /Users/mohammedfateh/personal-projects/hireoverflow/hireoverflow (sources)
```

### Package Manager Version

_No response_

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

macos M1

### LINKED ISSUE #30514: Daemon process terminated and closed the connection
### Current Behavior

Very often, a command like `npm install` or `nx add` will throw an error related to the Daemon

```
 NX   Daemon process terminated and closed the connection

Please rerun the command, which will restart the daemon.
If you get this error again, check for any errors in the daemon process logs found in: D:\projects\nx-project\.nx\workspace-data\d\daemon.log
```

### Expected Behavior

I can run these commands without errors.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Run npm install

### Nx Report

```shell
Node           : 20.16.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.1

nx (global)            : 20.3.3
nx                     : 20.4.5
@nx/js                 : 20.4.5
@nx/jest               : 20.4.5
@nx/eslint             : 20.4.5
@nx/workspace          : 20.4.5
@nx/angular            : 20.5.0
@nx/cypress            : 20.4.5
@nx/devkit             : 20.3.0
@nx/eslint-plugin      : 20.4.5
@nx/module-federation  : 20.5.0
@nx/react              : 20.4.5
@nx/react-native       : 20.4.5
@nx/vite               : 20.4.5
@nx/web                : 20.4.5
@nx/webpack            : 20.5.0
nx-cloud               : 19.1.0
typescript             : 5.7.3
---------------------------------------
Registered Plugins:
@nx-dotnet/core
@nx/cypress/plugin
@nx/jest/plugin
@nx/react-native/plugin
@nx/eslint/plugin
@nx/vite/plugin
---------------------------------------
Community plugins:
@fortawesome/angular-fontawesome : 1.0.0
@jsverse/transloco               : 7.5.1
@nx-dotnet/core                  : 2.5.0
@testing-library/angular         : 17.3.6
angular-eslint                   : 19.2.1
ng2-charts                       : 8.0.0
---------------------------------------
The following packages should match the installed version of nx
  - @nx/angular@20.5.0
  - @nx/devkit@20.3.0
  - @nx/module-federation@20.5.0
  - @nx/webpack@20.5.0

To fix this, run `nx migrate nx@20.5.0`
```

### Failure Logs

```shell
from daemon.log:

[NX Daemon Server] - 2025-03-26T19:04:01.374Z - [WATCHER]: Stopping the watcher for D:\projects\nx (sources)
[NX Daemon Server] - 2025-03-26T19:04:01.374Z - [WATCHER]: Stopping the watcher for D:\projects\nx (sources)
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use \\.\pipe\nx\C:\Users\user\AppData\Local\Temp\e9c11d4d7f6b2ca94c86\d.sock
    at Server.setupListenHandle [as _listen2] (node:net:1882:21)
    at listenInCluster (node:net:1961:12)
    at Server.listen (node:net:2080:5)
    at d:\projects\nx\node_modules\nx\src\daemon\server\server.js:364:20
    at new Promise (<anonymous>)
    at startServer (d:\projects\nx\node_modules\nx\src\daemon\server\server.js:362:12)
    at async d:\projects\nx\node_modules\nx\src\daemon\server\start.js:8:9
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1940:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '\\\\.\\pipe\\nx\\C:\\Users\\user\\AppData\\Local\\Temp\\e9c11d4d7f6b2ca94c86\\d.sock',
  port: -1
}
```

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by FrozenPandaz**
## Current Behavior

The daemon currently depends on client requests failing with a `LOCK_FILES_CHANGED` error to trigger a restart. This creates several issues:
- The daemon may stay running with stale dependencies if no requests come in
- The client must wait for a request to fail to trigger reconnection
- Special-case error handling is scattered across the client code

## Expected Behavior

The daemon should proactively restart itself when lock files change, and the client should gracefully reconnect with exponential backoff for any server shutdown scenario.

### Client-Side: Exponential Backoff Reconnection
- Add `handleConnectionError()` method that retries with exponential backoff (10ms → 5000ms, 30 attempts max)
- Preserve pending messages during reconnection and resend them once the new daemon is available
- Remove special-case handling for `LOCK_FILES_CHANGED` and `NX_VERSION_CHANGED` errors
- Remove `retryMessageAfterNewDaemonStarts()` method as it's no longer needed

### Server-Side: Self-Restart on Lock File Changes  
- Add `startNewDaemonInBackground()` to spawn a replacement daemon before shutdown
- Add `handleServerProcessTerminationWithRestart()` for restartable shutdown scenarios
- Detect lock file changes and proactively start a new daemon before responding with an error
- Keep version change handling simple (just exit, no restart)

## Benefits
- **More Resilient**: Client recovers from any server shutdown, not just specific errors
- **Cleaner Architecture**: Server manages its own lifecycle, client doesn't need special cases
- **No Request Dependency**: Daemon doesn't wait for requests to detect changes
- **Reduced Error Spam**: Exponential backoff prevents connection error floods
- **Future-Proof**: Foundation for other restart scenarios (plugins, config changes)

## Related Issue(s)

Fixes https://github.com/nrwl/nx/issues/30514
Fixes https://github.com/nrwl/nx/issues/29118

### CODE REVIEW

File: packages/nx/src/daemon/server/server.ts [hunk 1]
```diff
@@ -251,6 +248,19 @@ async function handleMessage(socket: Socket, data: string) {
   }
   serverLogger.log(`Received ${mode} message of type ${payload.type}`);
 
+  // Handle version check handshake
+  if (payload.type === 'VERSION_CHECK') {
```
Comment (MaxKless) [inline packages/nx/src/daemon/server/server.ts]: is this dead code? Can't see a reference to it anywhere

File: packages/nx/src/daemon/client/client.ts [hunk 2]
```diff
@@ -380,16 +586,123 @@ export class DaemonClient {
...
+
+      // If no more callbacks, close the connection
+      if (this.projectGraphListenerCallbacks.size === 0) {
+        this.projectGraphListenerMessenger?.close();
+        this.projectGraphListenerMessenger = undefined;
+      }
     };
   }
 
+  private async reconnectProjectGraphListener() {
```
Comment (MaxKless) [inline packages/nx/src/daemon/client/client.ts:651]: this also seems like dead code? 
It's somewhat inconsistent - the regular `registerProjectGraphRecomputationListener` dies when the daemon dies but this unused function handles reconnects properly. Maybe `reconnectProjectGraphListener` should be the new `registerProjectGraphRecomputationListener`?

File: packages/nx/src/daemon/client/client.ts [hunk 3]
```diff
@@ -317,47 +368,202 @@ export class DaemonClient {
...
+
+    try {
+      // Try to reconnect
+      const socketPath = this.getSocketPath();
+      this.fileWatcherMessenger = new DaemonSocketMessenger(
+        connect(socketPath)
+      ).listen(
+        (message) => {
+          try {
+            const parsedMessage = isJsonMessage(message)
```
Comment (MaxKless) [inline packages/nx/src/daemon/client/client.ts]: very duplicated from the registration method, maybe something could be shared?

File: packages/nx/src/daemon/client/client.ts [hunk 4]
```diff
@@ -317,47 +368,202 @@ export class DaemonClient {
...
       data: {
         projectGraph: ProjectGraph;
         sourceMaps: ConfigurationSourceMaps;
       } | null
     ) => void
   ): Promise<UnregisterCallback> {
-    let messenger: DaemonSocketMessenger | undefined;
+    // Generate unique ID for this callback
+    const callbackId = Math.random().toString(36).substring(2, 11);
+    let messenger: DaemonSocketMessenger;
```
Comment (MaxKless) [inline packages/nx/src/daemon/client/client.ts]: similar to the comment about `reconnectProjectGraphListener`: why is this not a class-level var and handles reconnection like the regular file watcher does?

**Review by MaxKless — CHANGES_REQUESTED** [review]

File: packages/nx/src/daemon/client/client.ts (hunk 2 above)
Comment (FrozenPandaz) [reply packages/nx/src/daemon/client/client.ts:651]: This is being used now.

**Review by MaxKless — APPROVED** [review]
