### PR TITLE
fix(testing): correctly set task status for failed coverage reports

### LINKED ISSUE #13676: Running nx run project:test should fail when coverage is not met for vitest
### Current Behavior

Currently coverage is collected correctly
but `nx run project:test` returns 0 so CI treats it as pass even when coverage is not met

### Expected Behavior

this command should return 1 so that we can treat not met coverage as a failure.

### Github Repo

_No response_

### Steps to Reproduce

1. Setup project with vite
2. Setup coverage in vitest
3. run test

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.2.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.4
   @nrwl/js : 15.2.4
   @nrwl/linter : 15.2.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.2.4
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.2.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.4
   @nrwl/web : 15.2.4
   @nrwl/webpack : 15.2.4
   @nrwl/workspace : 15.2.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nrwl/vite: 15.2.4
   	 nx-stylelint: 14.0.2
```

### Failure Logs

```shell
% Coverage report from istanbul
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |   66.66 |       50 |     100 |   66.66 |                   
 index.ts |   66.66 |       50 |     100 |   66.66 | 6                 
----------|---------|----------|---------|---------|-------------------
ERROR: Coverage for branches (50%) does not meet global threshold (100%)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target test for project XXX (2s)
```

### Additional Information

_No response_

### LINKED ISSUE #14098: vitest `{workspaceRoot}/coverage/{projectRoot}` create a `{workspaceRoot}/coverage/{projectRoot}` folder in project folder
### Current Behavior

vitest `{workspaceRoot}/coverage/{projectRoot}` create a `{workspaceRoot}/coverage/{projectRoot}` folder in project folder 

image

### Expected Behavior

`{workspaceRoot}/coverage/{projectRoot}` create the `coverage/project-name` folder in directory root

### Github Repo

https://github.com/tylim88/nx-reproduce-error

### Steps to Reproduce

1. run `npx nx g @nrwl/js:lib my`
2. in `vite.config.ts`, set `test.coverage.enabled:true`:
```ts
import { defineConfig } from 'vite';

import viteTsConfigPaths from 'vite-tsconfig-paths';

export default defineConfig({
  plugins: [
    viteTsConfigPaths({
      root: '../../',
    }),
  ],

  test: {
    globals: true,
    cache: {
      dir: '../../node_modules/.vitest',
    },
    environment: 'jsdom',
    include: ['src/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
    coverage: {
      enabled: true,
    },
  },
});
```
3. run `npx nx run my:test --skip-nx-cache`

### Nx Report

```shell
Node : 16.17.1
   OS   : win32 x64
   npm  : 8.15.0
   
   nx : 15.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.2
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : Not Found
   @nrwl/next : 15.4.2
   @nrwl/node : 15.4.2
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.2
   @nrwl/webpack : 15.4.2
   @nrwl/workspace : 15.4.2
   @nrwl/vite : 15.4.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by barbados-clemens**
## Current Behavior

when coverage isn't met vitest shows error but nx says it was successful

## Expected Behavior

not met coverage limits should cause tasks to fail

## Related Issue(s)

Also noticed an incosistency with the coverage paths set by the vitest generator. 

basically using the `{workspaceRoot}` and `{projectRoot}` variables in the executor options which are not currently expanded so the folder structure results in the actual test `{workspaceRoot}` as the folder names. 

Also by default coverage reports are placed in the project root (where vitest runs). Should this line up with jest and be in the root /coverage/<projectRootPath> directory?

I initially thought so based on the standalone project (since project root is also the workspace root) but noticed in integrated repo it's actually the project root. Open to whatever makes sense just wanted to fix the paths but need to know where they should be for the generator and migration

Fixes #13676

### CODE REVIEW

File: packages/vite/src/utils/generator-utils.ts [hunk 1]
```diff
@@ -208,13 +209,21 @@ export function addOrChangeTestTarget(
...
+  // vitest coverage starts at the project root
+  // so this will output to projectRoot/coverage/*
+  // TODO: if we want workspaceRoot then we'd need to actually set it to the workspaceRoot path
+  // since those vars are not expected for executor options
+  // this is where jest outputs, but not required to do the same.
+  const coveragePath = joinPathFragments(
+    // workspaceRoot,
+    'coverage',
+    project.root === '.' ? options.project : project.root
+  );
```
Comment (barbados-clemens) [inline packages/vite/src/utils/generator-utils.ts:221]: if we want to put the coverage reports at the workspaceRoot, then we'll have to put the actual workspace root path into the option (or expand that value in the executor manually) otherwise it'll be the folder name. 

this is kind of ugly IMO so would make sense to leave the coverage reports in the project root and make sure they are included in the task inputs

**Comment by AgentEnder** [comment]
IMHO they should line up with paths from other executor options, which tend to be based on workspace root

File: packages/vite/src/utils/generator-utils.ts (hunk 1 above)
Comment (barbados-clemens) [reply packages/vite/src/utils/generator-utils.ts:221]: or it could just be a relative path instead of the full workspaceRoot. will go with that instead

**Review by mandarini — APPROVED** [review]
