### PR TITLE
fix(core): whitelist registries that support obtaining migration config via 'npm view'

### LINKED ISSUE #16387: Plugin migrations not detected for plugins published to GitLab package registry
### Current Behavior

I've been attempting to create a migration generator, for a custom internal plugin, according to https://nx.dev/recipes/advanced-plugins/migration-generators. Whenever I tried to test my migration by running `nx migrate <plugin name>@latest` the resulting output states "There are no migrations to run, so migrations.json has not been created."

Investigation into https://github.com/nrwl/nx/blob/15.9.x/packages/nx/src/command-line/migrate.ts led me to determine that this is caused by our plugin having been published to GitLabs package registry, rather than the main npm registry.

### Expected Behavior

Plugin migrations are detected and migrations.json is created accordingly

### GitHub Repo

_No response_

### Steps to Reproduce

1. Create a plugin containing a migration according to https://nx.dev/recipes/advanced-plugins/migration-generators
2. Publish the plugin to a GitLab package registry (or any other registry that only supports [abbreviated metadata format](https://github.com/npm/registry/blob/9e368cf6aaca608da5b2c378c0d53f475298b916/docs/responses/package-metadata.md#abbreviated-metadata-format)
3. Attempt to generate migrations.json using `nx migrate <plugin name>@latest`

### Nx Report

```shell
Node : 16.19.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/nx-plugin         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 4.0.3
```

### Failure Logs

_No response_

### Additional Information

I traced the issue down to the `getPackageMigrationsConfigFromRegistry` function within https://github.com/nrwl/nx/blob/15.9.x/packages/nx/src/command-line/migrate.ts. This function attempts to retrieve migration metadata, from the registry, using `npm view <package name>@<version> nx-migrations ng-update --json`. Unfortunately, according to the GitLab documentation (https://docs.gitlab.com/ee/user/packages/npm_registry/#npm-metadata) it only supports [abbreviated metadata format](https://github.com/npm/registry/blob/9e368cf6aaca608da5b2c378c0d53f475298b916/docs/responses/package-metadata.md#abbreviated-metadata-format). As result the requested fields aren't returned and the migrate command thinks that the plugin has no migrations defined. 

A potential way of fixing this would be to also retrieve the `dist` field. In the event that the migration metadata fields aren't returned then the registry, within `dist.tarball`, could be compared against a whitelist of registries that are known to support the full metadata format. If a match is not found then an error could be thrown, which would cause `fetchMigrations` to fall through to the catch block and fall back to using `getPackageMigrationsUsingInstall` to determine the migrations.

### PR DESCRIPTION
**Pull request by CNManning**
## Current Behavior
Determining migration config for plugins that are published to a different registry than npmjs.org doesn't work if the registry doesn't support full package metadata. Such registries return no results via 'npm view' which causes migrate to think that no migrations are necessary.

## Expected Behavior
Migrate will fallback to determining migration config via install in the event that no config is returned from 'npm view' for registries other then npmjs.org.

## Related Issue(s)

Fixes #16387, #10223

### CODE REVIEW

File: packages/nx/src/command-line/migrate.ts [hunk 1]
```diff
@@ -933,14 +934,29 @@ async function getPackageMigrationsConfigFromRegistry(
...
-  return readNxMigrateConfig(JSON.parse(result));
+  const json = JSON.parse(result);
+
+  if (!json['nx-migrations'] && !json['ng-update']) {
+    const registry = new URL('dist' in json ? json.dist.tarball : json.tarball)
+      .hostname;
+
+    // Registries other than npmjs and the local registry may not support full metadata via npm view
+    // so throw error so that fetcher falls back to getting config via install
+    if (!['registry.npmjs.org', 'localhost'].includes(registry)) {
```
Comment (AgentEnder) [inline packages/nx/src/command-line/migrate.ts:952]: Yarn's registry just redirects to npmjs, and can be in lock files, but still shows npm's url for the tarball 🤔 interesting.

I think this is fine.

**Review by AgentEnder — APPROVED** [review]
This looks good to me, I want to get 1 more opinion first.

**Review by FrozenPandaz — APPROVED** [review]
