### PR TITLE
fix(testing): deprecate cypress tsconfig option

### LINKED ISSUE #16963: [Cypress] TS5053: Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.
### Current Behavior

With NX 16 Cypress E2E throws the TypeScript error `TS5053: Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.`

### Expected Behavior

Cypress runs normaly as with NX 15

### GitHub Repo

_No response_

### Steps to Reproduce

1. Run cypress project that ran normaly with NX 15

**tsconfig.json**
```json
{
  "extends": "../../tsconfig.base.json",
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.e2e.json"
    }
  ]
}
```

**tsconfig.e2e.json**
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "sourceMap": false,
    "outDir": "../../dist/out-tsc",
    "allowJs": true,
    "types": ["cypress", "node"]
  },
  "include": ["src/**/*.ts", "src/**/*.js", "cypress.config.ts"]
}

```

**project.json** target configuration
```json
"executor": "@nx/cypress:cypress",
      "options": {
        "cypressConfig": "apps/…-e2e/cypress.config.ts",
        "tsConfig": "apps/…-e2e/tsconfig.e2e.json",
        "devServerTarget": "…:serve:e2e-local",
        "testingType": "e2e"
      },
```

From the failure logs it looks like the wrong tsconfig is used

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin x64
   npm    : 9.5.1
   Hasher : Native
   
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/angular        : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/esbuild        : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/nest           : 16.1.4
   @nx/node           : 16.1.4
   @nx/plugin         : 16.1.4
   @nx/rollup         : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/webpack        : 16.1.4
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc               : 1.1.19
   @fortawesome/angular-fontawesome : 0.12.1
   @ionic/angular                   : 6.7.4
   @jscutlery/semver                : 2.30.1
   @nestjs-fixed/ng-universal       : 7.0.1
   @ngneat/spectator                : 14.0.0
   @ngrx/component                  : 15.4.0
   @ngrx/component-store            : 15.4.0
   @ngrx/data                       : 15.4.0
   @ngrx/effects                    : 15.4.0
   @ngrx/entity                     : 15.4.0
   @ngrx/eslint-plugin              : 15.4.0
   @ngrx/router-store               : 15.4.0
   @ngrx/schematics                 : 15.4.0
   @ngrx/store                      : 15.4.0
   @ngrx/store-devtools             : 15.4.0
   @nguniversal/builders            : 16.0.0
   @nguniversal/common              : 16.0.0
   @nguniversal/express-engine      : 16.0.0
   @nx-tools/nx-container           : 4.0.3
   @nxext/capacitor                 : 15.7.0
   @nxext/ionic-angular             : 15.7.0
   @trellisorg/make-buildable       : 0.0.12
   @twittwer/compodoc               : 1.9.0
   apollo-angular                   : 4.2.1
   ng-mocks                         : 14.10.0
   ngx-build-plus                   : 15.0.0
   ngx-deploy-npm                   : 5.2.0
   nx-stylelint                     : 15.0.0
```

### Failure Logs

```shell
Error: Webpack Compilation Error
/Users/…/Projekte/frontend/apps/…-e2e/tsconfig.json
[tsl] ERROR
      TS5053: Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.
    at handle (/Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:231:23)
    at finalCallback (/Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:298:10
    at /Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:2818:7
    at done (/Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/…/Library/Caches/Cypress/12.2.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:198:23)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by barbados-clemens**
## Current Behavior

the tsconfig option for the cypress executor does not influence cypress ts compilation and so should be removed

## Expected Behavior

no tsconfig option 

## Related Issue(s)

TODO:
  - [x] migrate any existing custom tsconfig to the root tsconfig.json

Fixes #16963

### CODE REVIEW

File: packages/cypress/src/migrations/update-16-3-0/tsconfig-sourcemaps.ts [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+            ...(e2eConfig.exclude ?? []),
+          ];
+
+          const tsConfigFromProjRoot = relative(
+            projectConfig.root,
+            tsconfigToRemove
+          );
+
+          console.log(json);
+          console.log(tsConfigFromProjRoot);
```
Comment (FrozenPandaz) [inline packages/cypress/src/migrations/update-16-3-0/tsconfig-sourcemaps.ts:64]: rm

File: packages/cypress/src/migrations/update-16-3-0/tsconfig-sourcemaps.ts [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+          ];
+          json.exclude = [
+            ...(json.exclude ?? []),
+            ...(e2eConfig.exclude ?? []),
+          ];
+
+          const tsConfigFromProjRoot = relative(
+            projectConfig.root,
+            tsconfigToRemove
+          );
```
Comment (FrozenPandaz) [inline packages/cypress/src/migrations/update-16-3-0/tsconfig-sourcemaps.ts:61]: I think this needs to be normalized for windows

File: packages/cypress/src/migrations/update-16-3-0/tsconfig-sourcemaps.ts [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+        options.tsConfig ??
+        joinPathFragments(projectConfig.root, 'tsconfig.e2e.json');
+      const projectLevelConfigPath = joinPathFragments(
+        projectConfig.root,
+        'tsconfig.json'
+      );
+
+      if (
+        tree.exists(tsconfigToRemove) &&
+        tree.exists(projectLevelConfigPath)
```
Comment (FrozenPandaz) [inline packages/cypress/src/migrations/update-16-3-0/tsconfig-sourcemaps.ts:38]: You should check if these 2 are the same path and do almost nothing.

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
