### PR TITLE
fix(linter): tslint to eslint conversion should not override existing root config

### LINKED ISSUE #5912: `convert-tslint-to-eslint`: root `.eslintrc.json` gets reset each time
## Current Behavior

If I have a workspace with a bunch of tslint libs, and I want to convert them one by one, with the `ignoreExistingTslintConfig: false` option:
- for the first lib, it creates a root `.eslintrc` file based on the root `tslint.json` file, which is perfect 👍 
- I then change this root `.eslintrc` file and apply more of my custom rules for the workspace
- if I then convert any following libs, it's going to reset the changes I made to the root file

## Expected Behavior

Maybe I'm wrong, but if you pass the `ignoreExistingTslintConfig: false` option, should it maybe:
- if there is no root `.eslintrc.json` file, create it based on the root `tslint.json` file (it already does it)
- if there is a **pre-existing root** `.eslintrc.json`, ignore it, and only convert the lib's own `tslint.json` to the new `.eslintrc.json` file

## Steps to Reproduce

```bash
npx create-nx-workspace@12.2.0 eslint-override --linter=tslint --preset=angular --appName=store --style=css --no-nxCloud
cd eslint-override
nx g @nrwl/angular:app admin 
nx g @nrwl/angular:convert-tslint-to-eslint --project=store --ignoreExistingTslintConfig=false --removeTSLintIfNoMoreTSLintTargets=true
```

change `eslintrc.json`:
	`enforceBuildableLibDependency: false`

```bash
nx g @nrwl/angular:convert-tslint-to-eslint --project=admin --ignoreExistingTslintConfig=false --removeTSLintIfNoMoreTSLintTargets=true
```

you will see the value changed back to true
(this issue happens on latest Nx 12.3.6 as well)

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 14.15.4
  OS   : darwin x64
  npm  : 6.14.11

  nx : Not Found
  @nrwl/angular : 12.3.6
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

### PR DESCRIPTION
**Pull request by meeroslav**
If projects are being converted from `tslint` to `eslint` one at a time and user makes changes to root `.eslintrc.json` in the meantime, those changes should not be overridden by next project's conversion.

## Related Issue(s)
https://github.com/nrwl/nx/issues/5912

Fixes #5912

### CODE REVIEW

File: packages/angular/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts [hunk 1]
```diff
@@ -43,6 +43,12 @@ export async function conversionGenerator(
     },
   });
 
+  /**
+   * If root eslint configuration already exists it will not be recreated
+   * but we also don't want to re-run the tslint config conversion
+   * as it was likely already done
+   */
+  const rootEslintConfigExists = host.exists('.eslintrc.json');
```
Comment (JamesHenry) [inline packages/angular/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts:51]: Is there any reason why we wouldn't want this same logic applied to all conversion? (i.e. cypress and nest currently)

If we just move it into the implementation details of `projectConverter.convertRootTSLintConfig` all conversion generators will get it for free (which was the intention behind sharing as much logic as possible)

Comment (meeroslav) [reply packages/angular/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts:51]: IMHO it make sense to move the entire sequence to a wrapper `convert` function in `projectConverter` which would include most of the duplicated `conversionGenerator` code:
* initialize esLint (with check for existing root `eslintrc`)
* convert root TSLint
* convert project TSLint
* remove project TSLint
* set defaults
* format
* uninstall tslint

Was there a reason of having it duplicated in the first place?

**Comment by meeroslav** [comment]
Broken build is dependant on:
https://github.com/nrwl/nx/pull/6104 and https://github.com/nrwl/nx/pull/6068

File: packages/linter/src/utils/convert-tslint-to-eslint/project-converter.ts [hunk 2]
```diff
@@ -150,8 +150,23 @@ export class ProjectConverter {
...
   ): Promise<Exclude<GeneratorCallback, void>> {
+    /**
+     * If root eslint already exists, we will not override it with converted tslint
+     * as this might break existing configuration in place. This is the common scenario
+     * when large projects are migrating one project at a time and apply custom
+     * changes to root config in the meantime.
+     *
+     * We warn user of this action in case .eslintrc.json was created accidentally
+     */
+    if (rootEslintConfigExists) {
```
Comment (FrozenPandaz) [inline packages/linter/src/utils/convert-tslint-to-eslint/project-converter.ts:164]: Can the `host.exists('.eslintrc.json')` be inlined in here instead of passing it in?

And I think this should move under the next early bail which checks the flag to ignore the tslint config?

Comment (meeroslav) [reply packages/linter/src/utils/convert-tslint-to-eslint/project-converter.ts:164]: the `host.exists('.eslintrc.json')` cannot be inlined unfortunately since the previous step `initESLint` generates the file if it doesn't exist, so we wouldn't know if this is a fresh generic one or existing.
