### PR TITLE
fix(schematics): speed up the dry-run command

### LINKED ISSUE #706: `ng g app --dry-run` and `ng g lib --dry-run` are slow
They should be very fast, but instead takes many seconds.

### PR DESCRIPTION
**Pull request by bcabanes**
## Description

Currently the `dry-run` command speed is on an average of:
* `ng g app app_name --dry-run`: 7099.051ms to 7207.579ms;
* `ng g lib lib_name --dry-run`: 4015.622ms to 3881.893ms;

This is due to too many files in the tree. While performing the transformation required by the schematic, the tree includes files in the *node_modules, .git, .idea, .vscode* folders.
These files are not needed and impact the performance of the commandline.

This add a filter function on the tree, before anything is moved. With that filter function
the average speed is:
* `ng g app app_name --dry-run`: 1420.826ms to 1435.487ms;
* `ng g lib lib_name --dry-run`: 1382.279ms to 1413.042ms;

## Issue
close #706

### CODE REVIEW

File: packages/schematics/src/collection/application/index.ts [hunk 1]
```diff
@@ -268,6 +269,14 @@ export default function(schema: Schema): Rule {
         routing: false
       }),
 
+      filter(
```
Comment (FrozenPandaz) [inline packages/schematics/src/collection/application/index.ts]: I think having a function within `/packages/schematics/src/utils/rules` would help reuse it easily.

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
Awesome that this worked :+1:

We should also add this to the other schematics:
* ngrx
* workspace-schematic
