### PR TITLE
fix(web): dynamic default unitTestRunner based on bundler for @nrwl/web:app

### LINKED ISSUE #14167: @nrwl/web:application do not generate jest test for vite
### Current Behavior

```
❯ npx create-nx-workspace@latest myorg
success Install finished in 3.667s


 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Choose what to create                 · integrated
✔ What to create in the new workspace   · apps
jsh: command not found: git
✔ Enable distributed caching to make your CI faster · No

❯ npm install -D @nrwl/web

❯ nx g @nrwl/web:app vite-app --bundler=vite --unitTestRunner=jest

❯ nx g @nrwl/web:app webpack-app --bundler=webpack --unitTestRunner=jest
```

both apps should use jest but vite-app has:

```
// project.json
    "test": {
      "executor": "@nrwl/vite:test",
      "outputs": ["coverage/apps/vite-app"],
      "options": {
        "passWithNoTests": true,
        "reportsDirectory": "../../coverage/apps/vite-app"
      }
    },
```

the webpack app is fine

```
// project.json
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/{projectRoot}"],
      "options": {
        "jestConfig": "apps/webpack-app/jest.config.ts",
        "passWithNoTests": true
      }
    }
```

### Expected Behavior

The vite app should use jest

### Github Repo

_No response_

### Steps to Reproduce

See the current behavior,

Online workspace available at https://stackblitz.com/edit/node-d2vbud

### Nx Report

```shell
❯ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : linux x64
   npm  : 7.17.0
   
   nx : 15.4.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.4
   @nrwl/js : 15.4.4
   @nrwl/linter : 15.4.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.4
   @nrwl/webpack : 15.4.4
   @nrwl/workspace : 15.4.4
   @nrwl/vite : 15.4.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by barbados-clemens**
## Current Behavior

--bundler=vite --unitTestRunner=jest does not add jest. only vitest

## Expected Behavior

--unitTestRunner should be respected
## Related Issue(s)

Fixes #14167

### CODE REVIEW

**Review by bcabanes — APPROVED** [review]

File: packages/web/src/generators/application/application.ts [hunk 1]
```diff
@@ -298,7 +298,7 @@ function normalizeOptions(host: Tree, options: Schema): NormalizedSchema {
     ? options.tags.split(',').map((s) => s.trim())
     : [];
 
-  if (options.bundler === 'vite') {
+  if (options.bundler === 'vite' && !options.unitTestRunner) {
```
Comment (vicb) [inline packages/web/src/generators/application/application.ts:301]: Shouldn't `unitTestRunner` default to jest when the bundler is `webpack/none` ?
(As documented in schema.json below)

Comment (barbados-clemens) [reply packages/web/src/generators/application/application.ts:301]: that's technically a bad check as unitTestRunner will never be falsey, since it's always defaulted in normalizeOptions
https://github.com/nrwl/nx/blob/master/packages/web/src/generators/application/application.ts#L301-L307

also have test cases for the bundler options.
https://github.com/nrwl/nx/blob/master/packages/web/src/generators/application/application.spec.ts#L482

Comment (vicb) [reply packages/web/src/generators/application/application.ts:301]: I hadn't seen the already existing default value but now I guess my question is:

Should we replace
```
 if (options.bundler === 'vite' && !options.unitTestRunner) {
    options.unitTestRunner = 'vitest';
  }
 // ...
  options.unitTestRunner = options.unitTestRunner || 'jest';
```

with
```
if (!options.unitTestRunner) {
  options.unitTestRunner = options.bundler === 'vite' ? 'vitest' : 'jest';
}
```

Comment (barbados-clemens) [reply packages/web/src/generators/application/application.ts:301]: no because it can still be 'none' in which case it should not change to 'jest'

Comment (vicb) [reply packages/web/src/generators/application/application.ts:301]:
```js
if (!options.unitTestRunner) {
  options.unitTestRunner = options.bundler === 'vite' ? 'vitest' : 'jest';
}
```

has the same behavior as the current code. The only difference is that is "group" the normalization instead of having it handled at 2 different places.

> no because it can still be 'none' in which case it should not change to 'jest'

when it's 'none' the if clause would not execute.
