### PR TITLE
fix(node): use `host.delete` to delete files for the nest library schematic

### LINKED ISSUE #3905: create library nest using schematic take about 5 mintues
## Current Behavior

if it executes the create nestjs command, it takes about 5 minutes
command example:
nx generate @ nrwl / nest: library --name = main --buildable --directory = af / be / common --importPath = @ apr / af / be / common / main --no-interactive

## Expected Behavior

to make the command work like any other scheme, i.e. at normal speed

it was in the previous cli version (I don't know before, because I am
new nx user)

## Steps to Reproduce

hm it practically executes this command like any other cli
I was looking at processes, generally the node is laden
I don't know where I can look to help you

as long as you give directions, I'll try to do it all

### Failure Logs

there is no error

### Environment

windows 10, the newest nx installed globally,

### LINKED ISSUE #4377: @nrwl/nest:library dry-run is hanging extra long
## Current Behavior

Takes about 1 min+ for dry run results to show

## Expected Behavior

Can't recall which version has changed this behavior

## Steps to Reproduce

1. Create nx workspace
2. Install nrwl nest plugin
3. Run inside vscode `@nrwl/nest:library`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
  nx : 10.4.4
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.16
  @nrwl/cypress : 11.0.16
  @nrwl/devkit : 11.0.16
  @nrwl/eslint-plugin-nx : 11.0.16
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.16
  @nrwl/linter : 11.0.16
  @nrwl/nest : 11.0.16
  @nrwl/next : 11.0.16
  @nrwl/node : 11.0.16
  @nrwl/react : 11.0.16
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.16
  @nrwl/web : 11.0.16
  @nrwl/workspace : 11.0.16
  typescript : 4.1.2
```

### PR DESCRIPTION
**Pull request by Cammisuli**
## Expected Behavior
Creating a new nest library should happen quickly. 

## Related Issue(s)

Fixes #4377
Fixes #3905

### CODE REVIEW

**Comment by Cammisuli** [comment]
I still want to do some local testing with this change. I just put the PR up to make sure that all the tests and e2es pass 😋

File: packages/nest/src/schematics/library/library.ts [hunk 1]
```diff
@@ -16,7 +16,6 @@ import {
 } from '@angular-devkit/schematics';
 import {
   addGlobal,
-  deleteFile,
```
Comment (FrozenPandaz) [inline packages/nest/src/schematics/library/library.ts:19]: Yes, don't use this... but do rewrite the function to be sane.. and deprecate it... because it's currently exported from `@nrwl/workspace` so I assume someone out there is using it.

**Comment by vsavkin** [comment]
@Cammisuli could you rebase this PR?

**Review by Cammisuli — COMMENTED** [review]
Tested locally and it's good now!

File: packages/workspace/src/utils/rules/deleteFile.ts [hunk 2]
```diff
@@ -2,6 +2,7 @@ import { forEach, FileEntry, Rule } from '@angular-devkit/schematics';
 
 /**
  * Remove a file from the Virtual Schematic Tree
+ * @deprecated This function will run through your whole workspace to find the file to delete. Please use `host.delete` instead for better performance
```
Comment (Cammisuli) [inline packages/workspace/src/utils/rules/deleteFile.ts:5]: @FrozenPandaz  I couldn't think of a better way to change this implementation without changing the signature or introducing more problems. So I think the deprecation note should be enough.

**Comment by beeman** [comment]
Thanks a lot for fixing this @Cammisuli 🙏
