### PR TITLE
fix(angular): use sync host when generating code with angular cli schematics

### LINKED ISSUE #15124: cannot run "ng generate @angular/material:mdc-migration": Expected a synchronous delegate but got an asynchronous one
### Current Behavior

after running nx migrate and updating to version 15.7.2, when running the Angular Material MDC Migration the migration fails:

```
ng generate @angular/material:mdc-migration

SynchronousDelegateExpectedException [Error]: Expected a synchronous delegate but got an asynchronous one.                                         
    at SyncDelegateHost._doSyncCall (C:\[...]node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:39:19)                       
    at SyncDelegateHost.read (C:\[...]\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:57:21)                              
    at LazyFileEntry._load (C:\[...]\node_modules\@angular-devkit\schematics\src\tree\host-tree.js:252:80)                               
    at LazyFileEntry.get content [as content] (C:\[...]\node_modules\@angular-devkit\schematics\src\tree\entry.js:34:55)                 
    at HostTree.read (C:\[...]\node_modules\@angular-devkit\schematics\src\tree\host-tree.js:211:30)                                     
    at getWorkspaceConfigGracefully (C:\[...]\node_modules\@angular\cdk\schematics\utils\project-tsconfig-paths.js:24:31)                
    at SchematicImpl.<anonymous> (C:\[...]\node_modules\@angular\material\schematics\ng-generate\mdc-migration\index_bundled.js:23448:81)
    at Generator.next (<anonymous>)                                                                                                                
    at C:\[...]\node_modules\@angular\material\schematics\ng-generate\mdc-migration\index_bundled.js:73:61                               
    at new Promise (<anonymous>)                                                                                                                   

  > NX   Expected a synchronous delegate but got an asynchronous one.
```

### Expected Behavior

run the command successfull

### GitHub Repo

company repository, will try to reproduce on privat asap

### Steps to Reproduce

1. update a project with Angular Material from Angular/NX 14 to 15 (latest) with `nx migrate --run-migrations`
2. run `ng generate @angular/material:mdc-migration` 
3. 

### Nx Report

```shell
Node : 16.18.0
   OS   : win32 x64
   npm  : 8.19.2

   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
```

### Failure Logs

_No response_

### Additional Information

 "@angular/animations": "15.1.5",
    "@angular/cdk": "15.1.5",
    "@angular/common": "15.1.5",
    "@angular/compiler": "15.1.5",
    "@angular/core": "15.1.5",
    "@angular/forms": "15.1.5",
    "@angular/localize": "15.1.5",
    "@angular/material": "15.1.5",

mentioned in https://github.com/nrwl/nx/issues/14990

### PR DESCRIPTION
**Pull request by leosvelperez**
## Current Behavior

Generating code with Angular CLI schematics throw `Expected a synchronous delegate but got an asynchronous one`. That error is handled in some cases, but it's not reliable and can't handle all scenarios. The host provided by the Angular CLI adapter has some async methods while the Angular DevKit expects them to be synchronous. This is a regression introduced in 15.7.0.

## Expected Behavior

Generating code with Angular CLI schematics should work correctly.

## Related Issue(s)

Fixes #15124

### CODE REVIEW

**Review by DarshanaHettiarachchi — APPROVED** [review]

**Review by DarshanaHettiarachchi — APPROVED** [review]

File: packages/nx/src/adapter/ngcli-adapter.ts [hunk 1]
```diff
@@ -503,7 +503,10 @@ export async function generate(
   verbose: boolean
 ) {
   const logger = getLogger(verbose);
-  const fsHost = new NxScopedHost(root);
+  const fsHost = new NxScopeHostUsedForWrappedSchematics(
+    root,
+    new FsTree(root, verbose)
+  );
```
Comment (AgentEnder) [inline packages/nx/src/adapter/ngcli-adapter.ts:509]: Is the original NxScopedHost still used anywhere? Maybe we can remove it and only keep the sync implementation

**Review by AgentEnder — APPROVED** [review]
Seems fine, left a question

File: packages/nx/src/adapter/ngcli-adapter.ts (hunk 1 above)
Comment (leosvelperez) [reply packages/nx/src/adapter/ngcli-adapter.ts:509]: Yeah, it's used for executors. The `read` operation is faster using the project graph and executors don't write back. So there's no issue with the async write implementation. That said, I plan to refactor/rename our existing host implementations, so they better represent what they are for. I'll do it in a follow-up PR later.
