### PR TITLE
fix(testing): component testing generator should trust user to provide valid build target

### LINKED ISSUE #17316: Cannot use cypressComponentConfigGenerator within another generator on a newly created project
### Current Behavior

When I run a custom generator that runs `libraryGenerator` from `@nx/react`, I can read from the created library by name via `readProjectConfiguration`. However, I have noticed it does not update the project graph. If I use either `readCachedProjectGraph` or `createProjectGraphAsync` and read the given nodes in the graph, it does not show my created library.

If I were to check the project graph AFTER the generator is run, it does exist.

This becomes an issue if a chained generator depends on the existence of the library created. My specific case is when I wanted to combine `libraryGenerator` from `@nx/react` and then follow it up with `cypressComponentConfigGenerator` from `@nx/react` which fails to get the build target because it cannot find it in the project graph.

### Expected Behavior

I expect the project graph to reflect newly created libs before the generator is finished executing.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Create a custom generator and use `libraryGenerator` from `@nx/react`
2. Try to run `cypressComponentConfigGenerator` from `@nx/react` afterwards in the same custom generator.
3. Step 2 should fail.

### Nx Report

```shell
Node   : 16.14.2
   OS     : darwin arm64
   yarn   : 3.2.1
   Hasher : Native
   
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/detox          : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/next           : 16.2.2
   @nx/node           : 16.2.2
   @nx/plugin         : 16.2.2
   @nx/react          : 16.2.2
   @nx/react-native   : 16.2.2
   @nx/rollup         : 16.2.2
   @nx/storybook      : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/vite           : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @trumbitta/nx-plugin-unused-deps : 1.12.1
   ---------------------------------------
   Local workspace plugins:
         @arrived/nx
```

### Failure Logs

```shell
TypeError: Cannot read properties of undefined (reading 'targets')
    at readTargetOptions (/Users/kaceycleveland/Projects/my-proj/packages/devkit/src/executors/read-target-options.ts:19:52)
    at findInTarget (/Users/kaceycleveland/Projects/my-proj/packages/cypress/src/utils/find-target-options.ts:103:27)
    at /Users/kaceycleveland/Projects/my-proj/packages/cypress/src/utils/find-target-options.ts:45:17
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kaceycleveland/Projects/my-proj/node_modules/tslib/tslib.js:164:62)

 >  NX   Error trying to find build configuration. Try manually specifying the build target with the --build-target flag.

   Provided project? my-lib
   Provided build target? my-lib:build
   Provided Executors? @nx/webpack:webpack, @nx/vite:build, @nrwl/webpack:webpack, @nrwl/vite:build
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

Component Testing Configuration requires a build target to be passed or it tries to find one. This can cause errors to be thrown during the validation step of the build target.
It impacts using the generators in a programatic manner and blocks Remix Component Testing

## Expected Behavior

Trust that the developer has provided a valid build target

## Related Issue(s)

Fixes #

### CODE REVIEW

File: packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@ import {
 } from '@nx/devkit';
 import { nxVersion } from '../../utils/versions';
 import { addFiles } from './lib/add-files';
-import { FoundTarget, addCTTargetWithBuildTarget } from '../../utils/ct-utils';
+import { addCTTargetWithBuildTarget, FoundTarget } from '../../utils/ct-utils';
```
Comment (barbados-clemens) [inline packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.ts:9]: the `FoundTarget` interface must have been defined twice. on in react and one in cypress. probably just consolidate to the one in cypress instead?

**Review by barbados-clemens — APPROVED** [review]

File: packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.ts (hunk 1 above)
Comment (Coly010) [reply packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.ts]: yep!

**Review by leosvelperez — APPROVED** [review]

**Review by mandarini — APPROVED** [review]
