### PR TITLE
fix(core): do not use joinPathFragments for generating files

### LINKED ISSUE #18677: create-nx-workspace not compatible with windows filesystem
### Current Behavior

When attempting to run npx create-nx-workspace@latest test on a windows machine, in our case version `16.7.1`

It will eventually error out with this: 

Fetching @nx/nest...

 >  NX   generateFiles: No files found in "/Users/myusername/AppData/Local/Temp/tmp-13492-63PtD20hzABS/node_modules/@nx/js/src/generators/init/files". Are you sure you specified the correct path?
 
 In this case part of the `@nx/nest` executor, but I've seen reports of different plugins suffering from the same issue. Everything with the same exact versions works perfectly fine on macOS (tested it myself, I have both). 
 
 if I navigate to that file path all there is a `__filename__` file of 1kb, likely empty.
 
 My assumption is either the path is wrong for not including the drive letter `C:\` or by not adding the right files in there in the first place, don't know enough about the inner works of the `create-nx-workspace` command to comment further. 

### Expected Behavior

create-nx-workspace should be able to find the files required to fulfil its basic purpose on windows machines.

### GitHub Repo

_No response_

### Steps to Reproduce

1.install nx@16.7.1 globally
2. run `npx create-nx-workspace test`
3. choose node
4. choose nest
5. choose integrated monorepo
6. choose no dockerfile
7. choose yes cloud build
8. wait for the runner to install stuff
9. error

### Nx Report

```shell
Node   : 18.17.0
   OS     : win32-x64
   npm    : 9.8.1

   nx (global)    : 16.7.1
   nx             : 16.7.1
   @nx/js         : 16.7.1
   @nx/jest       : 16.7.1
   @nx/linter     : 16.7.1
   @nx/workspace  : 16.7.1
   @nx/devkit     : 16.7.1
   @nx/node       : 16.7.1
   @nrwl/tao      : 16.7.1
   nx-cloud       : 16.4.0-beta.1
```

### Failure Logs

```shell
added 508 packages, and audited 509 packages in 6s

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

>  NX  Generating @nx/workspace:preset

Fetching @nx/nest...

 >  NX   generateFiles: No files found in "/Users/Seb/AppData/Local/Temp/tmp-13492-63PtD20hzABS/node_modules/@nx/js/src/generators/init/files". Are you sure you specified the correct path?

   Pass --verbose to see the stacktrace.


 >  NX   Workspace creation failed, see above.

   Pass --verbose to see the stacktrace.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### LINKED ISSUE #18727: create-nx-workspace breaking in windows. again.
### Current Behavior

because nx just flat refuses to build new projects for windows outside of the hard drive the OS is on, im forced to create my workspace on my OS hdd then move it over to my hard drive of choice. that worked well until just recently when i started getting the same errors on the OS hdd as i did on secondary ones. It just exits with Error Code 1 and a path to a generated log file.

### Expected Behavior

creating a new project.

### GitHub Repo

_No response_

### Steps to Reproduce

1. using a windows OS `pnpm dlx create-nx-workspace --packageManager="pnpm"` with following settings

```
√ Where would you like to create your workspace? · org
√ Which stack do you want to use? · react
√ What framework would you like to use? · nextjs
√ Integrated monorepo, or standalone project? · integrated
√ Application name · web-app
√ Would you like to use the App Router (recommended)? · Yes
√ Test runner to use for end to end (E2E) tests · cypress
√ Default stylesheet format · css
√ Enable distributed caching to make your CI faster · No
```

### Nx Report

```shell
Node   : 18.15.0
   OS     : win32-x64
   pnpm   : 8.6.10

   nx               : 16.7.2
   @nx/js           : 16.7.2
   @nrwl/js         : 15.8.6
   @nx/jest         : 16.0.0
   @nrwl/jest       : 15.9.2
   @nx/linter       : 16.7.2
   @nrwl/linter     : 15.8.6
   @nx/workspace    : 16.7.2
   @nrwl/workspace  : 15.8.6
   @nx/cypress      : 16.0.0
   @nrwl/cypress    : 15.9.2
   @nx/devkit       : 16.7.2
   @nrwl/devkit     : 15.8.6
   @nx/next         : 16.7.2
   @nx/react        : 16.7.2
   @nrwl/tao        : 15.8.6
   @nrwl/vite       : 15.8.9
   @nx/web          : 16.7.2
   @nrwl/webpack    : 15.8.7
   typescript       : 5.1.6
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/js@15.8.6
     - @nx/jest@16.0.0
     - @nrwl/jest@15.9.2
     - @nrwl/linter@15.8.6
     - @nrwl/workspace@15.8.6
     - @nx/cypress@16.0.0
     - @nrwl/cypress@15.9.2
     - @nrwl/devkit@15.8.6
     - @nrwl/tao@15.8.6
     - @nrwl/vite@15.8.9
     - @nrwl/webpack@15.8.7
```

### Failure Logs

```shell
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 2, reused 2, downloaded 0, added 0
Progress: resolved 3, reused 2, downloaded 0, added 0
Progress: resolved 107, reused 97, downloaded 0, added 0
Progress: resolved 150, reused 141, downloaded 0, added 0
Progress: resolved 165, reused 156, downloaded 0, added 0
Progress: resolved 179, reused 170, downloaded 0, added 0
Progress: resolved 214, reused 205, downloaded 0, added 0
Progress: resolved 238, reused 229, downloaded 0, added 0
Progress: resolved 261, reused 252, downloaded 0, added 0
Progress: resolved 276, reused 267, downloaded 0, added 0
Progress: resolved 288, reused 279, downloaded 0, added 0
Progress: resolved 313, reused 304, downloaded 0, added 0
Progress: resolved 344, reused 334, downloaded 0, added 0
Progress: resolved 393, reused 383, downloaded 0, added 0
Progress: resolved 433, reused 423, downloaded 0, added 0
Progress: resolved 467, reused 457, downloaded 0, added 0
Progress: resolved 478, reused 468, downloaded 0, added 0
Progress: resolved 479, reused 469, downloaded 0, added 0
Progress: resolved 481, reused 471, downloaded 0, added 0
Progress: resolved 482, reused 472, downloaded 0, added 0
Progress: resolved 483, reused 472, downloaded 0, added 0
Progress: resolved 496, reused 486, downloaded 0, added 0
Progress: resolved 508, reused 491, downloaded 0, added 0
Progress: resolved 537, reused 518, downloaded 0, added 0
Progress: resolved 543, reused 524, downloaded 0, added 0
Progress: resolved 544, reused 524, downloaded 0, added 0
Progress: resolved 546, reused 527, downloaded 0, added 0
Progress: resolved 547, reused 527, downloaded 0, added 0
Packages: +529
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\[omitted]\AppData\Local\pnpm\store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 547, reused 528, downloaded 0, added 40
Progress: resolved 547, reused 528, downloaded 0, added 183
Progress: resolved 547, reused 528, downloaded 0, added 397
Progress: resolved 547, reused 528, downloaded 0, added 518
Progress: resolved 547, reused 528, downloaded 0, added 528
Progress: resolved 547, reused 528, downloaded 1, added 528
.../node_modules/@parcel/watcher install$ node-gyp-build
.../node_modules/@parcel/watcher install: Done
.../.pnpm/nx@16.7.2/node_modules/nx postinstall$ node ./bin/post-install
Progress: resolved 547, reused 528, downloaded 1, added 529, done
.../.pnpm/nx@16.7.2/node_modules/nx postinstall: Done

dependencies:
+ @nx/next 16.7.2

devDependencies:
+ @nx/workspace 16.7.2
+ nx 16.7.2

Done in 37.8s

>  NX  Generating @nx/workspace:preset


 >  NX   configurationGenerator is not a function

   Pass --verbose to see the stacktrace.


 >  NX   Workspace creation failed, see above.

   Pass --verbose to see the stacktrace.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Cammisuli**
## Current Behavior
When running `npx create-nx-workspace` on a drive that is not `C:`, the process fails because we strip out the drive letter before trying to gather file information. This failure happens during `create-nx-workspace` and `ensurePackage` because those two functions will create a temporary directory (usually in `%LOCALAPPDATA%`, ie - `C:\Users\user\AppData\Local`), and run nx generators from there. If we try to use `readdirSync` without the drive letter, it will default to looking at the current working directory. So if the working directory is `D:\dev`, and a generator file is in `C:\Users\user\AppData\Local\etc`, Nx will "normalize" the windows path and remove the drive letter, and node will try to look for the file in `D:\Users\user\AppData\Local\etc`.

## Expected Behavior
Generating files do not remove the drive letter, and we just use a regular `join`

## Related Issue(s)

Fixes #18677
fixes #18727

### CODE REVIEW

**Review by barbados-clemens — APPROVED** [review]

**Review by leosvelperez — APPROVED** [review]

File: packages/nx/src/utils/path.ts [hunk 1]
```diff
@@ -5,14 +5,16 @@ function removeWindowsDriveLetter(osSpecificPath: string): string {
 }
 
 /**
- * Coverts an os specific path to a unix style path
+ * Coverts an os specific path to a unix style path. Use this when writing paths to config files.
+ * This should not be used to read files on disk because of the removal of Windows drive letters.
```
Comment (AgentEnder) [inline packages/nx/src/utils/path.ts:9]: This messaging will show up on nx.dev as well as intellisense for devkit users, I think its probably fine as-is, but maybe it'd be worth phrasing it more in line with it being ok for relative paths but not absolute? I can't think of a time that it wouldn't work when given relative path args.

**Review by AgentEnder — APPROVED** [review]

**Review by mandarini — APPROVED** [review]
