### PR TITLE
fix(core): keep all explicit dependencies in the graph

### LINKED ISSUE #15964: Cache is not cleared when external package is removed or version changed
### Current Behavior

**A build uses the cache and passes** after a dependency package is removed from the project's root `package.json` via npm

### Expected Behavior

**A build does not use the cache and fails** after a dependency package is removed from the project's root `package.json` via npm

### GitHub Repo

https://github.com/jepstein-eagle/package-test

### Steps to Reproduce

1. `npx nx build buildable` (seed cache)
2. `npm rm date-fns` (remove dependent package used in `buildable/src/lib/date/date.component.ts`)
3.  `npx nx build buildable` (uses cache when should not)

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node : 16.19.0
   OS   : darwin x64
   npm  : 8.19.3

   nx                      : 15.8.9
   @nrwl/js                : 15.8.9
   @nrwl/jest              : 15.8.9
   @nrwl/linter            : 15.8.9
   @nrwl/workspace         : 15.8.9
   @nrwl/angular           : 15.8.9
   @nrwl/cli               : 15.8.9
   @nrwl/cypress           : 15.8.9
   @nrwl/devkit            : 15.8.9
   @nrwl/eslint-plugin-nx  : 15.8.9
   @nrwl/tao               : 15.8.9
   @nrwl/webpack           : 15.8.9
   typescript              : 4.9.5
```

### Failure Logs

_No response_

### Additional Information

This use case is essential to many users because a typical pattern is to change dependent external package versions, and this causes lib builds to pass when they should not if the cache was correctly cleared.

We can use the `implicitDependencies` in the `nx.json` with the following content to resolve:

```
 "implicitDependencies": {
    "package.json": {
      "dependencies": "*"
    }
  }
```

but this should not be required in nx 15 per the [docs](https://nx.dev/deprecated/global-implicit-dependencies#dependencies-on-sections-of-the-root-file) and causes any root `pacakge.json` change, even unrelated to the lib, to require a rebuild.

Thank you in advance for your help 😄

### PR DESCRIPTION
**Pull request by meeroslav**
## Current Behavior
Explicit dependencies not matched to internal or external nodes are ignored during the graph creation.
This leads to:
- inaccurate representation of the actual state
- broken graph when adding missing packages subsequently (see #15964)

## Expected Behavior
All explicit dependencies of a project should be presented in `dependencies` regardless whether we can map it to an actual node or not.

## Methodology

* File dependencies can be created to nodes which do not exist.
* When calculating the updated graph, we omit reporting file dependencies which point to nodes that do not exist so this has no impact on the `ProjectGraph` which is created.
* Once the npm package is installed, recalculating the updated project graph will yield the new dependencies as they can now be resolved.

## Related Issue(s)

Fixes #15964

### CODE REVIEW

File: packages/nx/src/plugins/js/project-graph/build-dependencies/explicit-project-dependencies.ts [hunk 1]
```diff
@@ -40,19 +40,28 @@ export function buildExplicitTypeScriptDependencies(
...
+            targetProjectName = target;
+          } else {
+            // treat all unknowns as npm packages, they can be eiher
+            // - mistyped local import, which has to be fixed manually
+            // - node internals, which should still be tracked as a dependency
+            // - npm packages, which are not yet installed but should be tracked
+            targetProjectName = `npm:${importExpr}`;
           }
+
+          res.push({
```
Comment (meeroslav) [inline packages/nx/src/plugins/js/project-graph/build-dependencies/explicit-project-dependencies.ts:59]: We are attaching all found explicit dependencies to the file.

File: packages/nx/src/project-graph/project-graph-builder.ts [hunk 2]
```diff
@@ -268,7 +274,8 @@ export class ProjectGraphBuilder {
     }
     if (
       !this.graph.nodes[targetProjectName] &&
-      !this.graph.externalNodes[targetProjectName]
+      !this.graph.externalNodes[targetProjectName] &&
+      !sourceProjectFile
```
Comment (meeroslav) [inline packages/nx/src/project-graph/project-graph-builder.ts:278]: Do not break if adding explicit dependency to a file could not be found. We will filter it later in the `getUpdatedProjectGraph` if not resolved by then

File: e2e/linter/src/linter.test.ts [hunk 3]
```diff
@@ -232,7 +232,7 @@ describe('Linter', () => {
         import '@${projScope}/${invalidtaglib}';
         import '@${projScope}/${validtaglib}';
 
-        const s = {loadChildren: '@${projScope}/${lazylib}'};
+        const s = {loadChildren: '@secondScope/${lazylib}'};
```
Comment (meeroslav) [inline e2e/linter/src/linter.test.ts:235]: This test was broken and it only worked so far because we ignored unknown deps

File: packages/nx/src/plugins/js/package-json/create-package-json.ts [hunk 4]
```diff
@@ -234,8 +234,6 @@ function findAllNpmDeps(
           seen,
           dependencyPatterns
         );
-      } else {
```
Comment (meeroslav) [inline packages/nx/src/plugins/js/package-json/create-package-json.ts:237]: We are collecting deps from files, so some of those might be missing

File: packages/nx/src/project-graph/project-graph-builder.spec.ts [hunk 5]
```diff
@@ -91,13 +93,6 @@ describe('ProjectGraphBuilder', () => {
         'target'
       )
     ).toThrowError();
-    expect(() =>
```
Comment (meeroslav) [inline packages/nx/src/project-graph/project-graph-builder.spec.ts:94]: This no longer breaks, but does not create dependency in `dependencies` either, only in `files`

File: packages/nx/src/project-graph/project-graph-builder.ts [hunk 6]
```diff
@@ -175,41 +175,11 @@ export class ProjectGraphBuilder {
...
-    if (
-      !this.graph.nodes[targetProjectName] &&
-      !this.graph.externalNodes[targetProjectName]
-    ) {
-      throw new Error(`Target project does not exist: ${targetProjectName}`);
-    }
-
-    const fileData = source.data.files.find(
-      (f) => f.file === sourceProjectFile
+    this.addStaticDependency(
```
Comment (meeroslav) [inline packages/nx/src/project-graph/project-graph-builder.ts:178]: The logic was already duplicated in `addDependency` so it's easier to make changes only in one place

File: packages/nx/src/project-graph/project-graph-builder.ts (hunk 2 above)
Comment (FrozenPandaz) [reply packages/nx/src/project-graph/project-graph-builder.ts:249]: This makes sense for this use case. I'm a bit concerned that this would make it somewhat confusing for legitimate mistakes without any feedback.

If dependencies were drawn to projects that did not exist and will never exist because of some legitimate issue, the plugin author would not be told that the dependency was incorrect right? They would just wonder why they don't see it in the graph?

I suppose we could add a flag or a new method which would allow plugin authors to be explicit that they are adding a dependency which they know does not exist... But I'm hesitant to expand the API.

**Review by FrozenPandaz — APPROVED** [review]
This looks good to me.. but don't merge it yet.

@vsavkin what do you think about this?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
@vsavkin could you also take a look?

File: packages/nx/src/plugins/js/project-graph/build-dependencies/explicit-project-dependencies.ts [hunk 7]
```diff
@@ -40,19 +40,28 @@ export function buildExplicitTypeScriptDependencies(
...
-              sourceProjectFile: f.file,
-              type,
-            });
+            targetProjectName = target;
+          } else {
+            // treat all unknowns as npm packages, they can be eiher
+            // - mistyped local import, which has to be fixed manually
+            // - node internals, which should still be tracked as a dependency
+            // - npm packages, which are not yet installed but should be tracked
+            targetProjectName = `npm:${importExpr}`;
```
[the remark this answers is not in the document]
Comment (meeroslav) [reply packages/nx/src/plugins/js/project-graph/build-dependencies/explicit-project-dependencies.ts:56]: We are simply saying, assume this to be an external (`npm`) package. If it is, this will be resolved once we install it. If it's not, that means it's a local package and will be resolved either by fixing this import or renaming the project (in which case the graph will be fixed).

File: packages/nx/src/project-graph/project-graph-builder.ts (hunk 2 above)
Comment (meeroslav) [reply packages/nx/src/project-graph/project-graph-builder.ts:249]: Please note that `move` is broken - tracking it in a separate issue https://github.com/nrwl/nx/issues/16879

File: packages/nx/src/plugins/js/project-graph/build-dependencies/explicit-project-dependencies.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (meeroslav) [reply packages/nx/src/plugins/js/project-graph/build-dependencies/explicit-project-dependencies.ts:56]: This code is only visible to `TS/JS` workspaces so it's safe to assume an `npm` package.

**Review by FrozenPandaz — APPROVED** [review]
