### PR TITLE
fix(core): display dynamic prompts in angular cli

### LINKED ISSUE #6452: Failed to format 'angular.json' when creating new Nest application with standalone config in React workspace
## Current Behavior
When trying to create a new Nest application in a workspace v2 with no Angular whatsoever, Nx console dry run fails with an odd message

## Expected Behavior
The dry run succeedes

## Steps to Reproduce

- Create empty 12.5.8 workspace, no Nx Cloud
- add `@nrwl/react` and `@nrwl/nest`
- start creating Nest application via Nx console, with standalone config

### Failure Logs

```
> Executing task: nx generate @nrwl/nest:application --name=backend-simulator --frontendProject=frontend --standaloneConfig --no-interactive <

Failed to format: /angular.json
Error: 'project.json' files are incompatible with version 1 workspace schemas.
    at /Users/w.ghelfi/dev/Iungo/frontend-demo/giant-robots/node_modules/@nrwl/tao/src/shared/workspace.js:208:19
    at Array.forEach (<anonymous>)
    at toOldFormatOrNull (/Users/w.ghelfi/dev/Iungo/frontend-demo/giant-robots/node_modules/@nrwl/tao/src/shared/workspace.js:206:37)
    at Object.reformattedWorkspaceJsonOrNull (/Users/w.ghelfi/dev/Iungo/frontend-demo/giant-robots/node_modules/@nrwl/tao/src/shared/workspace.js:167:53)
    at updateWorkspaceJsonToMatchFormatVersion (/Users/w.ghelfi/dev/Iungo/frontend-demo/giant-robots/node_modules/@nrwl/devkit/src/generators/format-files.js:59:41)
    at Object.<anonymous> (/Users/w.ghelfi/dev/Iungo/frontend-demo/giant-robots/node_modules/@nrwl/devkit/src/generators/format-files.js:21:9)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/w.ghelfi/dev/Iungo/frontend-demo/giant-robots/node_modules/tslib/tslib.js:114:62)
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 12.16.1
  OS   : darwin x64
  npm  : 7.6.2
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.8
  @nrwl/cypress : 12.5.8
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : 12.5.8
  @nrwl/next : Not Found
  @nrwl/node : 12.5.8
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.5.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : 12.5.8
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : 12.5.8
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

### LINKED ISSUE #6968: `nx g @nrwl/workspace:convert-to-nx-project --all` uses backslash path characters on a Windows platform
## Current Behavior

When running `nx g @nrwl/workspace:convert-to-nx-project --all` on a Windows platform, all project paths are added with backslash characters. This works fine when building on the Windows platform. When building on Linux platforms (e.g., an Azure DevOps Linux image) this causes the build to fail with the log below.

The `angular.json` file contains content like the following after conversion:

```json
{
    "version": 2,
    "projects": {
        "my-app": "apps\\my-app",
        "my-app-api": "apps\\my-app-api",
        "my-app-e2e": "apps\\my-app-e2e",
    }
    // other content
}
```

## Expected Behavior

I expected path strings to use forward slashes as this has been the behaviour for Nx with other paths. 

Updating the project paths in the `angular.json` file to use forward slashes fixes the build issues for both Windows and Linux platforms.

## Steps to Reproduce

On Windows:

- run `nx g @nrwl/workspace:convert-to-nx-project --all` on a project that uses a single angular.json workspace file.
- build the project on Windows - Will succeed.
- build the project on Linux - Will fail with file path errors.

### Failure Logs

```
Error: ENOENT: no such file or directory, open '/home/vsts/work/1/s/apps\my-app/project.json'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.readJsonFile (/home/vsts/work/1/s/node_modules/@nrwl/tao/src/utils/fileutils.js:16:26)
    at /home/vsts/work/1/s/node_modules/@nrwl/tao/src/shared/workspace.js:252:44
    at Array.forEach (<anonymous>)
    at inlineProjectConfigurations (/home/vsts/work/1/s/node_modules/@nrwl/tao/src/shared/workspace.js:249:38)
    at resolveNewFormatWithInlineProjects (/home/vsts/work/1/s/node_modules/@nrwl/tao/src/shared/workspace.js:245:24)
    at Workspaces.readWorkspaceConfiguration (/home/vsts/work/1/s/node_modules/@nrwl/tao/src/shared/workspace.js:39:16)
    at readWorkspaceConfig (/home/vsts/work/1/s/node_modules/@nrwl/workspace/src/core/file-utils.js:141:21)
    at Object.readWorkspaceJson (/home/vsts/work/1/s/node_modules/@nrwl/workspace/src/core/file-utils.js:133:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/vsts/work/1/s/apps\\my-app/project.json
```

### Environment

Node : 14.17.5
  OS   : win32 x64
  npm  : 6.14.14

  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : 12.9.0
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
- Angular schematics that include chain(externalSchematic('@nrwl/angular', 'app', opts)) with an incomplete options block fail.
- Certain combinations of project.json files and wrapped / converted schematics / generators results in an error message stating 'not allowed with v1 schemas'

## Expected Behavior
- Angular schematics that include chain(externalSchematic('@nrwl/angular', 'app', opts)) with an incomplete options block succeed, and prompt for any missing options that have x-prompt attributes.
- Error message not received during valid operations.

## Related Issue(s)

Fixes #6452
Fixes #6968

### CODE REVIEW

File: packages/tao/src/commands/ngcli-adapter.ts [hunk 1]
```diff
@@ -618,6 +630,69 @@ export async function generate(
   ).status;
 }
 
+function createPromptProvider() {
```
Comment (FrozenPandaz) [inline packages/tao/src/commands/ngcli-adapter.ts:633]: Can this be improted from `@angular-devkit`?

File: packages/tao/src/shared/workspace.ts [hunk 2]
```diff
@@ -572,9 +572,12 @@ export function toOldFormatOrNull(w: any) {
 
 export function resolveOldFormatWithInlineProjects(
   w: any,
-  root: string = appRootPath
+  root: string = appRootPath,
+  includeConfigFilePath = false
```
Comment (FrozenPandaz) [inline packages/tao/src/shared/workspace.ts:576]: Is this flag ever used?

File: packages/tao/src/shared/workspace.ts [hunk 3]
```diff
@@ -586,13 +589,17 @@ export function resolveNewFormatWithInlineProjects(
 
 export function inlineProjectConfigurations(
   w: any,
-  root: string = appRootPath
+  root: string = appRootPath,
+  includeConfigFilePath = false
```
Comment (FrozenPandaz) [inline packages/tao/src/shared/workspace.ts:593]: Is this flag ever used?

**Comment by yharaskrik** [comment]
Yes please! Fixes an issue we started having with our workspace schematics after upgrade to Nx 12.9.0! Thanks @AgentEnder!

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/tao/src/commands/ngcli-adapter.ts (hunk 1 above)
Comment (AgentEnder) [reply packages/tao/src/commands/ngcli-adapter.ts:633]: No, I really wish it could, but angular doesn't export it or something similar.

File: packages/tao/src/shared/workspace.ts (hunk 2 above)
Comment (AgentEnder) [reply packages/tao/src/shared/workspace.ts]: No, removed.

File: packages/tao/src/shared/workspace.ts (hunk 3 above)
Comment (AgentEnder) [reply packages/tao/src/shared/workspace.ts]: No, removed.
