### PR TITLE
fix(angular): collect secondary folders correctly for tailwind #11747

### LINKED ISSUE #11747: Tailwind  ignores classes used only in components from Secondary-entry-points (createGlobPatternsForDependencies doen't include secondary-entry-points ?)
## Current Behavior
When is the css class used only in the component from Secondary-entry-point, it is not included. 

I have followed this guide step by step:
https://blog.nrwl.io/set-up-tailwind-css-with-angular-in-an-nx-workspace-6f039a0f4479

only one difference is, i have components in Secondary-entry-point (shared/ui/  -> buttons...)

CSS class doesn't do anything when it is used only in the component - but it works when i use that class in a component, which is not inside secondary-entry-point.

## Expected Behavior
Tailwind in NX monorepo should not ignore used CSS classes in components from secondary-entry-points.

## Steps to Reproduce
1) Follow
https://blog.nrwl.io/set-up-tailwind-css-with-angular-in-an-nx-workspace-6f039a0f4479
2) Add angular library
3) Add secondary entry point
4) Add component
5) use css class (for the instance - bg-black) on the component in that secondary entry point.

### Environment
```
"dependencies": {
    "@angular/animations": "14.1.3",
    "@angular/common": "14.1.3",
    "@angular/compiler": "14.1.3",
    "@angular/core": "14.1.3",
    "@angular/forms": "14.1.3",
    "@angular/localize": "14.1.3",
    "@angular/platform-browser": "14.1.3",
    "@angular/platform-browser-dynamic": "14.1.3",
    "@angular/router": "14.1.3",
    "@tailwindcss/forms": "^0.5.2",
    "@tailwindcss/typography": "^0.5.4",
    "rxjs": "7.5.6",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "14.1.3",
    "@angular-eslint/eslint-plugin": "~14.0.0",
    "@angular-eslint/eslint-plugin-template": "~14.0.0",
    "@angular-eslint/template-parser": "~14.0.0",
    "@angular/cli": "~14.1.0",
    "@angular/compiler-cli": "14.1.3",
    "@angular/language-service": "14.1.3",
    "@nrwl/angular": "14.5.10",
    "@nrwl/cli": "14.5.10",
    "@nrwl/cypress": "14.5.10",
    "@nrwl/eslint-plugin-nx": "14.5.10",
    "@nrwl/jest": "14.5.10",
    "@nrwl/js": "14.5.10",
    "@nrwl/linter": "14.5.10",
    "@nrwl/nx-cloud": "14.5.4",
    "@nrwl/workspace": "14.5.10",
    "@types/jest": "27.4.1",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "^5.29.0",
    "@typescript-eslint/parser": "^5.29.0",
    "autoprefixer": "^10.4.0",
    "cypress": "^9.1.0",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "27.5.1",
    "jest-preset-angular": "~11.1.2",
    "ng-packagr": "14.1.0",
    "nx": "14.5.10",
    "postcss": "^8.4.5",
    "postcss-import": "~14.1.0",
    "postcss-preset-env": "~7.5.0",
    "postcss-url": "~10.1.3",
    "prettier": "^2.6.2",
    "tailwindcss": "^3.0.2",
    "ts-jest": "27.1.4",
    "ts-node": "10.9.1",
    "typescript": "~4.7.2"
  }
```

I guess createGlobPatternsForDependencies() ignores secondary entry points (and targets /src/lib folder) ?

```
content: [
    join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
```

Id i edit tailwind.config.js and add /libs/ folder, it works

```
module.exports = {
  presets: [sharedTailwindConfig],
  content: [
    join(__dirname, '../../libs/**/!(*.stories|*.spec).{ts,html}'),
    join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
};
```

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

For libraries, our glob creation function only checks under `src` for classes for tailwind.

## Expected Behavior

We should also check alternate folders for secondary entry points

## Related Issue(s)

Fixes #11747

### CODE REVIEW

File: packages/workspace/src/utilities/generate-globs.ts [hunk 1]
```diff
@@ -39,6 +40,26 @@ export function createGlobPatternsForDependencies(
...
+      const dirs = readdirSync(dirPath)
+        .map((d) => join(dirPath, d))
+        .filter((d) => lstatSync(d).isDirectory());
+      for (const dir of dirs) {
+        if (readdirSync(dir).includes('ng-package.json')) {
+          dirsToUse.push(dir);
+        } else {
+          recursiveScanDirs(dir);
+        }
+      }
```
Comment (leosvelperez) [inline packages/workspace/src/utilities/generate-globs.ts:54]: We need to make sure we only iterate over non-ignored files, so we should do something similar to what's in the `visitNotIgnoredFiles` helper (that's for generators).

Also, let's reduce the number of loops and array allocations (`map` and `filter` will loop and allocate new arrays). We could do everything in a single loop and avoid reading all children inside a directory to know if a file exists:

```suggestion
      const children = readdirSync(dirPath);
      for (const child of chlidren) {
        if (!lstatSync(child).isDirectory()) {
          continue;
        }
        const dir = join(dirPath, child);
        if (existsSync(join(dir, 'ng-package.json'))) {
          dirsToUse.push(dir);
        } else {
          recursiveScanDirs(dir);
        }
      }
```

Note the above doesn't include the non-ignored files filter I mentioned. It can be added to the already existing check for `!lstatSync(child).isDirectory()`.

**Review by leosvelperez — CHANGES_REQUESTED** [review]

File: packages/workspace/src/utilities/generate-globs.ts (hunk 1 above)
Comment (Coly010) [reply packages/workspace/src/utilities/generate-globs.ts:54]: We’ll still need the map here to build the path. 
```
const children = readdirSync(dirPath);
      for (const child of chlidren) {
        if (!lstatSync(child).isDirectory()) {
```

because `readdirSync` only returns the name of file or directory, not the full path, so lstatSync(child) will fallover.

but good point on the other optimisations and the ignored files

**Comment by montella1507** [comment]
Probably related to problem with Storybooks too (not found under secondary-entry-point libraries)

https://github.com/nrwl/nx/issues/11446#issue-1328716380

File: packages/workspace/src/utilities/generate-globs.ts (hunk 1 above)
Comment (leosvelperez) [reply packages/workspace/src/utilities/generate-globs.ts]: You don't need the `map`, you just need to `join` inside the loop. What I put in line 61, moves to line 58, before checking if it's a directory.

Comment (leosvelperez) [reply packages/workspace/src/utilities/generate-globs.ts]: The point is that while `map`, `filter` and the likes are easier to read, they come with a cost. That cost might not be too important in certain scenarios where the collections are finite and small, but in others, like traversing the filesystem (especially when running as part of a task where perf matters), it's important and we can always achieve the same without using them.

**Review by leosvelperez — APPROVED** [review]
LGTM! 🎉

**Comment by Coly010** [comment]
> LGTM! 🎉

Adding the gitignore feature :)
