### PR TITLE
fix(core): task graph needs to handle multiple cycles

### LINKED ISSUE #28788: 20.0.8 Maximum call stack size exceeded on run-many
### Current Behavior

I recently upgraded to 20.0.7 but then realized there was an issue with dependent projects, but then 20.0.8 was released the fix for that, just tried it this morning but now I am getting

```
$ nx run-many -t generate-schema --parallel

 NX   Maximum call stack size exceeded

Pass --verbose to see the stacktrace.

error: script "nx" exited with code 1

Exited with code exit status 1
```

I successfully ran another command prior to this in CI though so its not all commands (`nx run-many -t generate-prisma-client --parallel`).

Note: this ran find on 20.0.7 so the issue was introduced in 20.0.8

### Expected Behavior

Run-many works correctly.

### GitHub Repo

_No response_

### Steps to Reproduce

Unsure, would assume it has to do with the graph and possibly a circular dependency.

### Nx Report

```
 NX   Report complete - copy this into the issue template

Node           : 22.8.0
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 1.22.17

nx                      : 20.0.8
@nx/js                  : 20.0.8
@nrwl/js                : 19.8.3
@nx/jest                : 20.0.8
@nrwl/jest              : 19.8.3
@nx/linter              : 19.8.3
@nx/eslint              : 20.0.8
@nx/workspace           : 20.0.8
@nrwl/workspace         : 19.8.3
@nx/angular             : 20.0.8
@nrwl/angular           : 19.8.3
@nx/cypress             : 20.0.8
@nrwl/cypress           : 19.8.3
@nx/devkit              : 20.0.8
@nrwl/devkit            : 19.6.5
@nx/esbuild             : 20.0.8
@nrwl/esbuild           : 19.8.3
@nx/eslint-plugin       : 20.0.8
@nrwl/eslint-plugin-nx  : 19.8.3
@nx/express             : 20.0.8
@nrwl/express           : 19.8.3
@nx/nest                : 20.0.8
@nrwl/nest              : 19.8.3
@nx/node                : 20.0.8
@nrwl/node              : 19.8.3
@nx/plugin              : 20.0.8
@nrwl/nx-plugin         : 19.8.3
@nx/rspack              : 20.0.8
@nrwl/rspack            : 19.8.0
@nx/storybook           : 20.0.8
@nrwl/storybook         : 19.8.3
@nrwl/tao               : 19.6.5
@nx/vite                : 20.0.8
@nrwl/vite              : 19.8.3
@nx/web                 : 20.0.8
@nrwl/web               : 19.8.3
@nx/webpack             : 20.0.8
@nrwl/webpack           : 19.8.3
typescript              : 5.5.4
---------------------------------------
Registered Plugins:
./plugins/ci-test-targets.ts
./plugins/compile-css.plugin.ts
./plugins/dotenv-vault.plugin.ts
./plugins/fly.plugin.ts
---------------------------------------
Community plugins:
@ngneat/spectator        : 18.0.2
@ngrx/component          : 18.1.1
@ngrx/component-store    : 18.1.1
@ngrx/data               : 18.1.1
@ngrx/effects            : 18.1.1
@ngrx/entity             : 18.1.1
@ngrx/operators          : 18.1.1
@ngrx/router-store       : 18.1.1
@ngrx/store              : 18.1.1
@ngrx/store-devtools     : 18.1.1
@skyux/i18n              : 10.23.0
@skyux/packages          : 10.23.0
@storybook/angular       : 8.3.3
@testing-library/angular : 17.3.1
angular-calendar         : 0.31.0
apollo-angular           : 7.1.2
ngxtension               : 4.0.0
---------------------------------------
Local workspace plugins:
         @trellis/plugins/apollo-graphql
         @trellis/plugins/nest-graphql
         @trellis/plugins/aws-deploy
         @trellis/plugins/repository
         @trellis/plugins/angular
         @trellis/plugins/docker
         @trellis/plugins/dotenv
         @trellis/plugins/prisma
         @trellis/plugins/jest
         @trellis/plugins/node
         @trellis/plugins/fly
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/js@19.8.3
  - @nrwl/jest@19.8.3
  - @nx/linter@19.8.3
  - @nrwl/workspace@19.8.3
  - @nrwl/angular@19.8.3
  - @nrwl/cypress@19.8.3
  - @nrwl/devkit@19.6.5
  - @nrwl/esbuild@19.8.3
  - @nrwl/eslint-plugin-nx@19.8.3
  - @nrwl/express@19.8.3
  - @nrwl/nest@19.8.3
  - @nrwl/node@19.8.3
  - @nrwl/nx-plugin@19.8.3
  - @nrwl/rspack@19.8.0
  - @nrwl/storybook@19.8.3
  - @nrwl/tao@19.6.5
  - @nrwl/vite@19.8.3
  - @nrwl/web@19.8.3
  - @nrwl/webpack@19.8.3

To fix this, run `nx migrate nx@20.0.8`
```

### Failure Logs

```
$ nx run-many -t generate-schema --parallel

 NX   Maximum call stack size exceeded

Pass --verbose to see the stacktrace.

error: script "nx" exited with code 1

Exited with code exit status 1
```

### Package Manager Version

bun@latest

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Was working on 20.0.7, broke on 20.0.8

### PR DESCRIPTION
**Pull request by xiongemi**
## Current Behavior

- getNonDummyDeps is a recursive function. we pass in cycle arg to this function. currently we end the recursion when the task is in a cycle. however, currently there is an error "Maximum call stack size". i suspect this recursion is not being ended because the cycle is not detected when there are multiple cycles.
- add a function to get all cycles of the graph
- also, change getNonDummyDeps to track a list of seen tasks, even with no cycle detected, this function will not run into infinite recursion

## Related Issue(s)

Fixes https://github.com/nrwl/nx/issues/28788

### CODE REVIEW

File: packages/nx/src/tasks-runner/create-task-graph.ts [hunk 1]
```diff
@@ -490,3 +434,57 @@ function interpolateOverrides<T = any>(
   });
   return interpolatedArgs;
 }
+
+/**
+ * This function is used to filter out the dummy tasks from the dependencies
+ * It will manipulate the dependencies object in place
+ */
+export function filterDummyTasks(dependencies: { [k: string]: string[] }) {
+  const cycles = new Set(findCycles({ dependencies }).flat());
```
Comment (jaysoo) [inline packages/nx/src/tasks-runner/create-task-graph.ts:443]: Rather then creating `string[][]`, flattening, then creating a set, could we return an unique list from `findCycles`?

Comment (xiongemi) [reply packages/nx/src/tasks-runner/create-task-graph.ts:443]: change the return type to be Set<string>

File: packages/nx/src/tasks-runner/task-graph-utils.ts [hunk 2]
```diff
@@ -35,6 +39,29 @@ export function findCycle(graph: {
...
+  const visited = {};
+  const cycles = [];
+  for (const t of Object.keys(graph.dependencies)) {
+    visited[t] = false;
+  }
+
+  for (const t of Object.keys(graph.dependencies)) {
+    const cycle = _findCycle(graph, t, visited, [t]);
+    if (cycle) {
+      cycles.push(cycle);
```
Comment (jaysoo) [inline packages/nx/src/tasks-runner/task-graph-utils.ts:58]: I think it's better to just add to the set and avoid having to create the array and call `.flat()`.


```
cont cycles = new Set<string>();

// ...

  for (const t of Object.keys(graph.dependencies)) {
    const cycle = _findCycle(graph, t, visited, [t]);
    if (cycle) {
     cycles.add(cycle)
    }
}

// ...
```

And then return the set, I don't think you need to return `null`?

Comment (xiongemi) [reply packages/nx/src/tasks-runner/task-graph-utils.ts]: changed

**Review by Cammisuli — APPROVED** [review]
