### PR TITLE
fix(nx): wrap files inputted to prettier in quotes

### LINKED ISSUE #1473: Files with parentheses fails format.
# Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Files with parentheses in them should be formatted as normal

## Current Behavior

Files that contain parentheses e.g `some(file).json` cause formatting to fail. 

## Failure Information

Parentheses in a shell command throw a syntax error. The nx format scripts pass in the list of affected files to prettier via `execSync` without escaping parentheses or wrapping the file path in quotes. The error thrown is:
```
bash: syntax error near unexpected token `('
```

### Steps to Reproduce

1. `yarn create nx-workspace myworkspace`
2. `cd myworkspace`
3. `touch some\(file\).json`
4. `git add .`
5. `git commit -m "testing"`
6. `yarn format --base HEAD~1 --head HEAD`

### Context

Tested with Nx version 8:
```json
"devDependencies": {
    "@nrwl/workspace": "8.1.0",
    "@types/node": "~8.9.4",
    "dotenv": "6.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.4.5",
    "prettier": "1.16.4",
    "@angular/cli": "8.0.0"
  }
```

The relevant code can be found [here](https://github.com/nrwl/nx/blob/master/packages/workspace/src/command-line/format.ts).
I'd be happy to submit a PR to fix this so let me know.

### PR DESCRIPTION
**Pull request by ZachJW34**
Files that contained parentheses caused 'yarn format' to fail unless the files passed to the
prettier cli are wrapped in quotes

fix #1473

### CODE REVIEW

File: packages/workspace/src/command-line/format.ts [hunk 1]
```diff
@@ -96,17 +96,24 @@ function printError(command: string, e: any) {
 
 function write(patterns: string[]) {
   if (patterns.length > 0) {
-    execSync(`node "${prettierPath()}" --write ${patterns.join(' ')}`, {
-      stdio: [0, 1, 2]
-    });
+    execSync(
+      `node "${prettierPath()}" --write ${patterns
+        .map(pattern => (fileExists(pattern) ? `'${pattern}'` : pattern))
```
Comment (FrozenPandaz) [inline packages/workspace/src/command-line/format.ts]: Why do we need to check if the file exists before wrapping it in quotes? It should be filtered out higher above on https://github.com/nrwl/nx/pull/1485/files#diff-f8549c910ef16fe4ad9fa75fd90c4005R47

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
Thank you for your contribution!

File: packages/workspace/src/command-line/format.ts (hunk 1 above)
Comment (ZachJW34) [reply packages/workspace/src/command-line/format.ts]: I originally had it as
```
.map(pattern => `'${pattern}'`
```
but the e2e command-line test failed. This was due to patterns also being wrapped in quotes. The `fileExists` check is to determine whether an element of the patterns input is a pattern e.g. "${prefix}/**/*.{${PRETTIER_EXTENSIONS.join(',')}}" or an actual file. The `fileExists` could be replaced by a `isFile` function that could do some regex to determine whether it s a pattern or a file. What do you think?

Comment (FrozenPandaz) [reply packages/workspace/src/command-line/format.ts]: Right, so we can move this mapping up to https://github.com/nrwl/nx/blob/65ad548ed74f7903575138ed631cd5ff8bc7aacd/packages/workspace/src/command-line/format.ts#L59 which is the only time when it has actual file paths.

Comment (ZachJW34) [reply packages/workspace/src/command-line/format.ts]: Oh I see. I'll update the PR soon!

**Comment by ZachJW34** [comment]
Updated. I moved the mapping down to the return, and I only wrap the files if `libsAndApp` is false. Wrapping the files with quotes beforehand will cause `getPatternsFromApps` to incorrectly find touched projects.

**Review by FrozenPandaz — APPROVED** [review]
Perfect, LGTM!
