### PR TITLE
fix(core): call `pnpm run` without `--` for pnpm v7

### LINKED ISSUE #10111: run-many appends a "--" argument when invoking packages' scripts
## Current Behavior
In a monorepo where each package has a `tsc` script to run the Typescript checker, when I run `tsc` through Nx using this command:

```
nx run-many --target=tsc --all --skip-nx-cache
```

Nx appends `--` when it invokes the scripts, and that results in the following error:

```
> nx-bug@1.0.0 tsc /Users/pepicrft/Downloads/nx-bug
> nx run-many --target=tsc --all --skip-nx-cache



    ✖  nx run project:tsc
       > project@1.0.0 tsc /Users/pepicrft/Downloads/nx-bug/packages/project
       > tsc -p './tsconfig.json' "--"
       
       error TS5023: Unknown compiler option '--'.
 ```

## Expected Behavior
I'd expect Nx to invoke the script as it is declared in the `package` without appending additional arguments.

## Steps to Reproduce
1. Download this project [nx-bug.zip](https://github.com/nrwl/nx/files/8609378/nx-bug.zip)
2. Install dependencies `pnpm install`.
3. Run `pnpm run tsc`

### Failure Logs
The code is included above

### Environment
```
Node : 16.13.2
   OS   : darwin arm64
   pnpm : 7.0.0
   
   nx : 14.0.5
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : Not Found
   @nrwl/linter : 14.0.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.0.5
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
 ```

### PR DESCRIPTION
**Pull request by Methuselah96**
[Starting in pnpm v7](https://github.com/pnpm/pnpm/releases/tag/v7.0.0) all command line arguments after the script name are passed to a script's arguments when using `pnpm run <script>`, including `--`. This can cause problems when there are no command line arguments, because it will pass `--` without anything following, which some scripts can't handle. In order to preserve the old functionality, we check if the pnpm version is less than 7.0.0. If it is, we include `--` before the args, otherwise we don't.

Closes #10111

## Current Behavior

Appending `--` to `pnpm run <script>` when there are no arguments.

## Expected Behavior

Only include `--` for pnpm <7.0.0.

## Related Issue(s)

Fixes #10111

### CODE REVIEW

**Review by nartc — APPROVED** [review]

File: packages/nx/src/utils/package-manager.ts [hunk 1]
```diff
@@ -67,6 +67,7 @@ export function getPackageManagerCommand(
       if (gte(pnpmVersion, '6.13.0')) {
```
Comment (gioragutt) [inline packages/nx/src/utils/package-manager.ts:67]: Can you perhaps fix `useExec` to `const useExec = gte(pnpmVersion, '6.13.0');`?
You did it the right way and seeing the `useExec` above kinda hurts the eyes 😅

Comment (Methuselah96) [reply packages/nx/src/utils/package-manager.ts]: Haha, agreed. Updated.

File: packages/nx/src/utils/package-manager.ts [hunk 2]
```diff
@@ -75,7 +73,10 @@ export function getPackageManagerCommand(
         addGlobal: 'pnpm add -g',
         rm: 'pnpm rm',
         exec: useExec ? 'pnpm exec' : 'pnpx',
-        run: (script: string, args: string) => `pnpm run ${script} -- ${args}`,
+        run: (script: string, args: string) =>
+          includeDoubleDashBeforeArgs
+            ? `pnpm run ${script} -- ${args}`
+            : `pnpm run ${script} ${args}`,
```
Comment (ericbiewener) [inline packages/nx/src/utils/package-manager.ts:79]: In case anyone is looking to patch v13, I created this patch for `@nrwl/tao@13.8.0`:

```patch
diff --git a/src/shared/package-manager.js b/src/shared/package-manager.js
index b74ffe01bc7cb161ac46462d723d8f521ec5a849..2ced85a576ad95bc2d18b363529d721d471408b2 100644
--- a/src/shared/package-manager.js
+++ b/src/shared/package-manager.js
@@ -39,17 +39,25 @@ function getPackageManagerCommand(packageManager = detectPackageManager()) {
         }),
         pnpm: () => {
             const [major, minor] = getPackageManagerVersion('pnpm').split('.');
+            const majorVersion = +major
+
             let useExec = false;
-            if (+major >= 6 && +minor >= 13) {
+            if (majorVersion >= 6 && +minor >= 13) {
                 useExec = true;
             }
+
+            const includeDoubleDashBeforeArgs = majorVersion < 7;
+            
             return {
                 install: 'pnpm install --no-frozen-lockfile',
                 add: 'pnpm add',
                 addDev: 'pnpm add -D',
                 rm: 'pnpm rm',
                 exec: useExec ? 'pnpm exec' : 'pnpx',
-                run: (script, args) => `pnpm run ${script} -- ${args}`,
+                run: (script, args) =>
+                    includeDoubleDashBeforeArgs
+                        ? `pnpm run ${script} -- ${args}`
+                        : `pnpm run ${script} ${args}`,
                 list: 'pnpm ls --depth 100',
             };
         },
```
