### PR TITLE
fix(angular): export a default module for require calls

### LINKED ISSUE #15583: nx list @nrwl/angular (and other .mjs modules) doesn't work
### Current Behavior

Though `@nrwl/angular` is installed, the `nx list` doesn't work only for that package; the other packages are fine

```
PS C:\repo\toDelete\bg-hoard-raw-apps> cat .\package.json       
{
  "name": "bg-hoard-raw-apps",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {},
  "private": true,
  "devDependencies": {
    "@angular-devkit/build-angular": "~15.2.0",
    "@angular-devkit/core": "~15.2.0",
    "@angular-devkit/schematics": "~15.2.0",
    "@angular-eslint/eslint-plugin": "~15.0.0",
    "@angular-eslint/eslint-plugin-template": "~15.0.0",
    "@angular-eslint/template-parser": "~15.0.0",
    "@angular/cli": "~15.2.0",
    "@angular/compiler-cli": "~15.2.0",
    "@angular/language-service": "~15.2.0",
    "@nrwl/angular": "^15.8.5",
    "@nrwl/cypress": "15.8.5",
    "@nrwl/eslint-plugin-nx": "15.8.5",
    "@nrwl/jest": "15.8.5",
    "@nrwl/js": "15.8.5",
    "@nrwl/linter": "15.8.5",
    "@nrwl/nx-workshop": "^0.0.1",
    "@nrwl/workspace": "15.8.3",
    "@schematics/angular": "~15.2.0",
    "@types/jest": "^29.4.0",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "^5.36.1",
    "@typescript-eslint/parser": "^5.36.1",
    "cypress": "^12.2.0",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "^29.4.1",
    "jest-environment-jsdom": "^29.4.1",
    "jest-preset-angular": "~13.0.0",
    "nx": "15.8.3",
    "prettier": "^2.6.2",
    "ts-jest": "^29.0.5",
    "ts-node": "10.9.1",
    "typescript": "~4.9.5"
  },
  "dependencies": {
    "@angular/animations": "~15.2.0",
    "@angular/cdk": "^15.2.2",
    "@angular/common": "~15.2.0",
    "@angular/compiler": "~15.2.0",
    "@angular/core": "~15.2.0",
    "@angular/forms": "~15.2.0",
    "@angular/material": "^15.2.2",
    "@angular/platform-browser": "~15.2.0",
    "@angular/platform-browser-dynamic": "~15.2.0",
    "@angular/router": "~15.2.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  }
}
PS C:\repo\toDelete\bg-hoard-raw-apps> npx nx list @nrwl/js

 >  NX   Capabilities in @nrwl/js:

   GENERATORS
   
   library : Create a library
   init : Initialize a TS/JS workspace.
   convert-to-swc : Convert a TypeScript library to compile with SWC.
   
   EXECUTORS/BUILDERS
   
   tsc : Build a project using TypeScript.
   swc : Build a project using SWC.
   node : Execute a Node application.

PS C:\repo\toDelete\bg-hoard-raw-apps> npx nx list @nrwl/angular

 >  NX   @nrwl/angular is not currently installed

   Use "npm install -D @nrwl/angular" to install the plugin.
   After that, use "npx nx g @nrwl/angular:init" to add the required peer deps and initialize the plugin.
```

### Expected Behavior

show list of generatorss 

### GitHub Repo

_No response_

### Steps to Reproduce

1. `npx create-nx-workspace foldername --preset=apps --no-nx-cloud`
2.  `npm i -D @nrwl/angular` 
3.  `npx nx list @nrwl/angular`

### Nx Report

```shell
PS C:\repo\toDelete\bg-hoard-raw-apps> npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.14.2
   OS   : win32 x64
   npm  : 9.5.0
   
   nx                      : 15.8.3
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.3
   @nrwl/angular           : 15.8.5
   @nrwl/cli               : 15.8.3
   @nrwl/cypress           : 15.8.5
   @nrwl/devkit            : 15.8.3
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/nest              : 13.2.3
   @nrwl/node              : 13.2.3
   @nrwl/nx-plugin         : 13.2.3
   @nrwl/storybook         : 13.2.3
   @nrwl/tao               : 15.8.3
   @nrwl/webpack           : 15.8.5
   @nrwl/nx-cloud          : 15.1.1
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @nrwl/nx-workshop : 0.0.1
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/js@15.8.5
     - @nrwl/jest@15.8.5
     - @nrwl/linter@15.8.5
     - @nrwl/angular@15.8.5
     - @nrwl/cypress@15.8.5
     - @nrwl/eslint-plugin-nx@15.8.5
     - @nrwl/nest@13.2.3
     - @nrwl/node@13.2.3
     - @nrwl/nx-plugin@13.2.3
     - @nrwl/storybook@13.2.3
     - @nrwl/webpack@15.8.5

   To fix this, run `nx migrate nx@15.8.5`
```

### Failure Logs

```shell
available in the description
```

### Additional Information

_No response_

### LINKED ISSUE #16696: ensurePackage don't work with @nx/angular
### Current Behavior

I have a generator using the Angular app generator from @nx/angular. I add @nx/angular through the devkit function "ensurePackage". Adding other Nx packages worked well; with v15 @nrwl/angular, it was working as expected.
I tried different tsconfig options but couldn't find the one doing the trick.

One module of the @nx/angular package uses esnext, is that the reason?

### Expected Behavior

Generator can run

### GitHub Repo

https://github.com/nxext/nx-extensions/blob/update_nx_16/packages/ionic-angular/src/generators/application/lib/add-angular.ts

### Steps to Reproduce

1. Check out Nxext repo
2. Remove ionic-angular-e2e from .nxignore
3. Run the e2e test for ionic-angular

(Cloud run https://cloud.nx.app/runs/xKHVcwp700)

### Nx Report

```shell
Node   : 18.13.0
   OS     : darwin x64
   yarn   : 1.22.15
   Hasher : Native

   nx                 : 16.0.1
   @nx/js             : 16.0.1
   @nx/jest           : 16.0.1
   @nx/linter         : 16.0.1
   @nx/workspace      : 16.0.1
   @nx/angular        : 16.0.1
   @nx/cypress        : 16.0.1
   @nx/devkit         : 16.0.1
   @nx/eslint-plugin  : 16.0.1
   @nx/node           : 16.0.1
   @nx/plugin         : 16.0.1
   @nx/react          : 16.0.1
   @nx/storybook      : 16.0.1
   @nrwl/tao          : 16.0.1
   @nx/vite           : 16.0.1
   @nx/web            : 16.0.1
   @nx/webpack        : 16.0.1
   nx-cloud           : 16.0.5
   typescript         : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   	 @nxext/ionic-angular
   	 @nxext/ionic-react
   	 @nxext/capacitor
   	 @nxext/preact
   	 @nxext/svelte
   	 @nxext/vitest
   	 @nxext/vite
   	 @nxext/vue
   	 @nxext/e2e
```

### Failure Logs

```shell
require() of ES Module ~/nxext/node_modules/@nx/angular/fesm2015/nx-angular.mjs not supported.

   Instead change the require of ~/nxext/node_modules/@nx/angular/fesm2015/nx-angular.mjs to a dynamic import() which is available in all CommonJS modules.

Error [ERR_REQUIRE_ESM]: require() of ES Module ~/nxext/node_modules/@nx/angular/fesm2015/nx-angular.mjs not supported.
Instead change the require of ~/nxext/node_modules/@nx/angular/fesm2015/nx-angular.mjs to a dynamic import() which is available in all CommonJS modules.
    at Mod.require (~//nxext/tmp/nx-e2e/proj/node_modules/nx/bin/init-local.js:204:36)
    at require (~/nxext/tmp/nx-e2e/proj/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at ensurePackage (~/nxext/tmp/nx-e2e/proj/node_modules/@nx/devkit/src/utils/package-json.js:249:16)
    at ~/nxext/tmp/nx-e2e/proj/node_modules/@nxext/ionic-angular/src/generators/application/lib/add-angular.js:10:36
    at Generator.next (<anonymous>)
    at ~/nxext/tmp/nx-e2e/proj/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (~/nxext/tmp/nx-e2e/proj/node_modules/tslib/tslib.js:163:16)
    at addAngular (~/nxext/tmp/nx-e2e/proj/node_modules/@nxext/ionic-angular/src/generators/application/lib/add-angular.js:9:20)
    at ~/nxext/tmp/nx-e2e/proj/node_modules/@nxext/ionic-angular/src/generators/application/generator.js:17:64
    at Generator.next (<anonymous>)
    at ~/nxext/tmp/nx-e2e/proj/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (~/nxext/tmp/nx-e2e/proj/node_modules/tslib/tslib.js:163:16)
    at applicationGenerator (~/nxext/tmp/nx-e2e/proj/node_modules/@nxext/ionic-angular/src/generators/application/generator.js:14:20)
    at Object.<anonymous> ~/nxext/tmp/nx-e2e/proj/node_modules/nx/src/command-line/generate.js:249:36)
    at Generator.next (<anonymous>)
    at fulfilled (~/nxext/tmp/nx-e2e/proj/node_modules/tslib/tslib.js:164:62)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
Running `nx list @nx/angular` or `ensurePackage(@nx/angular)` both result in failures due to trying to require ESM

## Expected Behavior
@nx/angular exports a small entry point for cjs until Nx fully supports ESM plugins.

## Related Issue(s)

Fixes #16696
Fixes #15583
Fixes #

### CODE REVIEW

File: packages/nx/src/utils/plugins/plugin-capabilities.ts [hunk 1]
```diff
@@ -39,44 +40,41 @@ export async function getPluginCapabilities(
...
-          'generators'
-        ) ||
-        tryGetCollection(
+          packageJson.schematics,
+          'schematics'
+        ),
+        ...tryGetCollection(
           packageJsonPath,
           packageJson.schematics,
           'generators'
```
Comment (leosvelperez) [inline packages/nx/src/utils/plugins/plugin-capabilities.ts:55]: This call and the one below seem to be the same. I think we are missing the case where there's a `generators` entry in the `package.json` and an `schematics` entry in the collection.
```suggestion
          packageJson.generators,
          'schematics'
```

**Review by leosvelperez — APPROVED** [review]
