### PR TITLE
fix(nextjs): enable Next.js 13.4 support

### LINKED ISSUE #16692: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports"
### Current Behavior

Receiveing error

event - compiled client and server successfully in 2.8s (684 modules)
wait  - compiling...
[ ready ] on http://localhost:4200
event - compiled client and server successfully in 1296 ms (684 modules)
wait  - compiling /page (client and server)...
event - compiled client and server successfully in 18.8s (8718 modules)
wait  - compiling...
error - Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports" in /Users/m/Development/XX/Frontend/node_modules/react-dom/package.json

### Expected Behavior

run successfuly

### GitHub Repo

_No response_

### Steps to Reproduce

1. upgrade nextjs to 13.3.4

### Nx Report

```shell
Node   : 16.18.0
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.0.1
   @nx/js             : 16.0.1
   @nx/jest           : 16.0.1
   @nx/linter         : 16.0.1
   @nx/workspace      : 16.0.1
   @nx/cypress        : 16.0.1
   @nx/devkit         : 16.0.1
   @nx/eslint-plugin  : 16.0.1
   @nx/next           : 16.0.1
   @nx/react          : 16.0.1
   @nx/storybook      : 16.0.1
   @nrwl/tao          : 16.0.1
   @nx/web            : 16.0.1
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

### Failure Logs

```shell
error - Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports" in /Users/reza/Development/Legamart/Frontend/node_modules/react-dom/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:649:3)
    at resolveExports (node:internal/modules/cjs/loader:522:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:562:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
    at /Users/reza/Development/Legamart/Frontend/node_modules/next/dist/server/require-hook.js:180:36
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/reza/Development/Legamart/Frontend/node_modules/next/dist/server/app-render/app-render.js:24:60)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at DevServer.renderHTMLImpl (/Users/reza/Development/Legamart/Frontend/node_modules/next/dist/server/next-server.js:674:72)
    at /Users/reza/Development/Legamart/Frontend/node_modules/next/dist/server/next-server.js:664:105
    at NextTracerImpl.trace (/Users/reza/Development/Legamart/Frontend/node_modules/next/dist/server/lib/trace/tracer.js:86:20)
    at DevServer.renderHTML (/Users/reza/Development/Legamart/Frontend/node_modules/next/dist/server/next-server.js:664:41)
    at doRender (/Users/reza/Development/Legamart/Frontend/node_modules/next/dist/server/base-server.js:1022:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/Users/reza/Development/Legamart/Frontend/node_modules/next/dist/server/base-server.js:1145:28)
    at async /Users/reza/Development/Legamart/Frontend/node_modules/next/dist/server/response-cache/index.js:97:36 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED',
  page: '/'
}
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jaysoo**
Adds a missing environment variable needed to override `react` and `react-dom` to use the once bundled into Next.js itself. Note: This will not be needed once we invoke Next.js CLI directly.

## Related Issue(s)

Fixes #16692

### CODE REVIEW

**Review by ndcunningham — APPROVED** [review]

File: packages/next/plugins/with-nx.ts [hunk 1]
```diff
@@ -156,6 +156,15 @@ function withNx(
   _nextConfig = {} as WithNxOptions,
   context: WithNxContext = getWithNxContext()
 ): NextConfigFn {
+  // If this is not set user will see compile errors in Next.js 13.4.
+  // See: https://github.com/nrwl/nx/issues/16692, https://github.com/vercel/next.js/issues/49169
+  // TODO(jack): Remove this once Nx is refactored to invoke CLI directly.
+  forNextVersion('>=13.4.0', () => {
+    process.env['__NEXT_PRIVATE_PREBUNDLED_REACT'] =
+      // Not in Next 13.3 or earlier, so need to access config via string
+      _nextConfig.experimental['serverActions'] ? 'experimental' : 'next';
```
Comment (ruslanguns) [inline packages/next/plugins/with-nx.ts:165]: @jaysoo If `serverActions` is not specified on the experimental object, then it will throw an error because of undefined.

**Review by ruslanguns — COMMENTED** [review]
Not sure if closed Merged PRs are revisited but I leaved you a comment in a bug I found.

File: packages/next/plugins/with-nx.ts (hunk 1 above)
Comment (dpnolte) [reply packages/next/plugins/with-nx.ts:165]: Yes, I had the same error as @ruslanguns. It should be first checked if experimental object exists in the config, something like `_nextConfig.experimental && _nextConfig.experimental['serverActions']`

Comment (ruslanguns) [reply packages/next/plugins/with-nx.ts:165]: @dpnolte just dropped a PR with your suggested fix https://github.com/nrwl/nx/pull/16846

**Comment by aryobenholzner** [comment]
it seems #15796 is still an issue when enabling app directory
