### PR TITLE
fix(bundling): skip web-specific configuration when bundling for node

### LINKED ISSUE #12108: Environment variables from `.env` are not picked up by the Node process
## Current Behavior
With the latest version of nx, it seems like the env vars in `.env` are no longer picked up in Node/Nest apps (possibly others).

Some of the env vars do appear to be set:

```ts
console.log(Object.keys(process.env))
[
  'NODE_ENV',
  'NX_CLI_SET',
  'NX_INVOKED_BY_RUNNER',
  'NX_WORKSPACE_ROOT',
  'NX_TERMINAL_OUTPUT_PATH',
  'NX_STREAM_OUTPUT',
  'NX_TASK_TARGET_PROJECT',
  'NX_TASK_HASH'
]
```

## Expected Behavior
Env vars defined in `.env` should be available on `process.env` 

## Steps to Reproduce

Repro here: https://github.com/beeman/nx-env-vars-issue

- create a new repo
- add  @nrwl/nest or  @nrwl/node and create an app
- add an env var to `.env` 
- log out `process.env`
- see that the env var from `.env` is not there

### Failure Logs
No logs

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin arm64
   yarn : 1.22.19

   nx : 14.7.6
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.6
   @nrwl/eslint-plugin-nx : 14.7.6
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.6
   @nrwl/js : 14.7.6
   @nrwl/linter : 14.7.6
   @nrwl/nest : 14.7.6
   @nrwl/next : Not Found
   @nrwl/node : 14.7.6
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.6
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### PR DESCRIPTION
**Pull request by jaysoo**
## Related Issue(s)

Fixes #12108

### CODE REVIEW

File: packages/webpack/src/utils/config.ts [hunk 1]
```diff
@@ -149,36 +149,43 @@ export function getBaseWebpackPartial(
...
+            terserOptions: {
+              mangle: false,
+              keep_classnames: true,
+            },
+          }),
+        ],
+        concatenateModules: true,
+      };
+    }
+  } else {
```
Comment (Michsior14) [inline packages/webpack/src/utils/config.ts:168]: Could `DefinePlugin` from L132 be moved here and added to `extraPlugins` as well? It would resolve #12108 ;)
