### PR TITLE
fix(react): fix extracCss option for webpack 5

### LINKED ISSUE #6819: Styles bundle is not included when using Webpack 5
## Current Behavior

The `styles` bundle is not included in the `dist/.../index.html` when using Webpack 5. This happens if there is more than one file in `build.styles` config of `workspace.json`.

## Expected Behavior

All of the files listed in `build.styles` are bundled into a single `styles.[hash].css` and included in the `dist/.../index.html` file. It worked like this in webpack 4.

## Steps to Reproduce

I have created a project to reproduce the problem: https://github.com/markogresak/nx-styles-bug#reproducing-the-problem-with-missing-styles-bundle

It's a project where I've added only some randomly generated css to the output.

### Failure Logs

```sh
grep css dist/apps/nx-styles-bug/index.html
# <link rel="stylesheet" href="main.79da9420fe0c20301be7.css"></head>
```

It's missing the `591.f4af1e18666da591d76a.css`, which includes the stylesheets listed in `workspace.json` under `build.styles`. Also, the missing file should be named `styles.[hash].css`. 

### Environment

```
nx report

>  NX  Report complete - copy this into the issue template

  Node : 16.4.0
  OS   : darwin x64
  npm  : 7.19.0

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.8.0
  @nrwl/cypress : 12.8.0
  @nrwl/devkit : 12.8.0
  @nrwl/eslint-plugin-nx : 12.8.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.8.0
  @nrwl/linter : 12.8.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.8.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.8.0
  @nrwl/web : 12.8.0
  @nrwl/workspace : 12.8.0
  @nrwl/storybook : 12.8.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

### PR DESCRIPTION
**Pull request by jaysoo**
This PR fixes a configuration issue with CSS extraction. There shouldn't be a split chunks configuration since we want to keep it all in one file.

## Current Behavior

When using webpack 5 and the CSS gets too large it'll split into multiple chunks, and the generated `index.html` is missing styling.

## Expected Behavior

Everything should work the same as before in webpack 4.

## Related Issue(s)

Fixes #6819, #6664, #6558, #6816

### CODE REVIEW

File: packages/web/src/utils/third-party/cli-files/plugins/named-chunks-plugin.ts [hunk 1]
```diff
@@ -6,16 +6,16 @@
...
-// There doesn't seem to exist any ergonomic way to alter chunk names for non-context lazy chunks
-// (https://github.com/webpack/webpack/issues/9075) so this is the best alternative for now.
-const ImportDependency = require('webpack/lib/dependencies/ImportDependency');
-const ImportDependenciesBlock = require('webpack/lib/dependencies/ImportDependenciesBlock');
-const Template = require('webpack/lib/Template');
 
 export class NamedLazyChunksPlugin {
   constructor() {}
   apply(compiler: Compiler): void {
+    // Webpack doesn't export these so the deep imports can potentially break.
```
Comment (jaysoo) [inline packages/web/src/utils/third-party/cli-files/plugins/named-chunks-plugin.ts:13]: Had to move it here since later versions of webpack 5 doesn't have these modules anymore, causing the build to break.

**Comment by markogresak** [comment]
@jaysoo I have tested this change via the `@next` release (version `12.9.0-rc.0`) and it does fix #6819, but not #6816 (css minification).

`stylesOptimization` is ignored with `isWebpack5`. I think we need the changes from #6817 or something similar.
