### PR TITLE
fix(core): enforce fixed versions only for apps with createPackageJson

### LINKED ISSUE #16293: Allow for generated package.json to include dependency range from root package.json
One of my favorite features of Nx is that I don't have to think about managing my package.json for publishable packages because Nx will ensure the generated package.json will have all the dependencies I used and none that I didn't use. This is no longer the case in v15 as it's using the strict versions from my package-lock file, and it's making managing dependencies across my projects very difficult. I understand the position of the team (below), but I'm wondering if we can be provided with the _option_ to use the same version (range) from the root package.json.

> Also, the new generated pacakge json may have adverse impacts for publishable npm packages as the range specified is important and needs to be included in the generated package json. This also impacts any publishable package using the @nrwl/js:tsc executor.

For publishable packages we suggest creating manual package.json instead of using generated one, **because** it gives you the freedom to specify ranges as you see fit. For example my library could support `@angular/core: >= 10 < 15` but my root package.json would have probably something like `@angular/core: ^14.2.0`. Using root package json ranges for publishable libs is bad practice, as they tend to be more restrictive than needed.

_Originally posted by @meeroslav in https://github.com/nrwl/nx/issues/12675#issuecomment-1301366002_

### PR DESCRIPTION
**Pull request by meeroslav**
## Related Issue(s)

Fixes #16293

### CODE REVIEW

**Review by AgentEnder — APPROVED** [review]

File: packages/nx/src/plugins/js/package-json/create-package-json.ts [hunk 1]
```diff
@@ -103,44 +116,64 @@ export function createPackageJson(
...
     }
   });
-  Object.entries(npmDeps.peerDependencies).forEach(([packageName, version]) => {
-    if (!packageJson.peerDependencies?.[packageName]) {
-      if (rootPackageJson.dependencies?.[packageName]) {
-        packageJson.dependencies ??= {};
-        packageJson.dependencies[packageName] = version;
-        return;
-      }
+  if (!isLibrary) {
```
Comment (jaysoo) [inline packages/nx/src/plugins/js/package-json/create-package-json.ts:136]: I think it's fine for now, but if the app vs lib logic deviates more, we might consider separating them into two functions: `createAppPackageJson` and `createLibPackgeJson` so the consumer can choose which to call depending on use-case.

File: packages/nx/src/plugins/js/package-json/create-package-json.spec.ts [hunk 2]
```diff
@@ -499,4 +503,214 @@ describe('createPackageJson', () => {
...
+          tslib: '~2.4.0',
+          typescript: '^4.8.2',
+        },
+        name: 'lib1',
+        version: '0.0.1',
+      });
+    });
+
+    it('should override range versions with local ranges when creating package json for libs', () => {
+      spies.push(
```
Comment (jaysoo) [inline packages/nx/src/plugins/js/package-json/create-package-json.spec.ts:684]: Not a fan of having to mock these functions, but since it's used in existing tests let's go with it for now. Maybe something we can discuss later is testing strategies

**Review by jaysoo — APPROVED** [review]
