### PR TITLE
fix(nextjs): remove the need to install @nx/next for production builds

### LINKED ISSUE #15931: @nrwl/next: Cannot find module '@nrwl/next/plugins/with-nx'
### Documentation issue

- [ ] Reporting a typo
- [X] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[@nrwl/next -> Setting up Next.js](https://nx.dev/packages/next#setting-up-next.js)

### Additional context or description

With changes from https://github.com/nrwl/nx/pull/15824 package `@nrwl/next` needs to be included in `dependencies`, not in the `devDependencies`, otherwise generated `package.json` doesn't have `@nrwl/next` and it's not possible to run the Next's application because of error:

```
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Cannot find module '@nrwl/next/plugins/with-nx'
```

Workspace generated by command `npx create-nx-workspace@latest --preset=next` have `@nrwl/next` in the `dependencies`.

### PR DESCRIPTION
**Pull request by jaysoo**
This PR brings back the compiled version of the `withNx` function. This allows `@nx/next` to not be installed as a production dependency, which avoids pulling in `@nx/devkit` and other dev packages.

## Current Behavior
`@nx/next` or `@nrwl/next` must be installed as production dependency.

## Expected Behavior
`@nx/next` or `@nrwl/next` don't need to be installed for the compiled app to run.

## Related Issue(s)

Fixes #15931

### CODE REVIEW

File: packages/next/index.ts [hunk 1]
```diff
@@ -6,4 +6,4 @@ export { componentGenerator } from './src/generators/component/component';
 export { libraryGenerator } from './src/generators/library/library';
 export { pageGenerator } from './src/generators/page/page';
 export { withNx } from './plugins/with-nx';
-export { composePlugins } from './src/utils/config';
```
Comment (jaysoo) [inline packages/next/index.ts:9]: Moved `composePlugins` to its own file so we can copy the compiled version to dist during build.

File: packages/next/plugins/with-nx.ts [hunk 2]
```diff
@@ -130,21 +121,35 @@ async function determineDistDirForProdServer(
...
-    const { options, node: projectNode } = getNxContext(graph, originalTarget);
-    const outputDir = `${offsetFromRoot(projectNode.data.root)}${
-      options.outputPath
-    }`;
-    return nextConfig.distDir && nextConfig.distDir !== '.next'
-      ? joinPathFragments(outputDir, nextConfig.distDir)
-      : joinPathFragments(outputDir, '.next');
-  } else {
-    return '.next';
+  try {
```
Comment (jaysoo) [inline packages/next/plugins/with-nx.ts:124]: This logic will only be needed when running through Nx. i.e. `nx serve <app> --prod`

File: packages/next/plugins/with-nx.ts [hunk 3]
```diff
@@ -130,21 +121,35 @@ async function determineDistDirForProdServer(
...
+      }`;
+      return nextConfig.distDir && nextConfig.distDir !== '.next'
+        ? joinPathFragments(outputDir, nextConfig.distDir)
+        : joinPathFragments(outputDir, '.next');
+    }
+  } catch {
+    // ignored -- fallback to Next.js default of '.next'
   }
+
+  return '.next';
```
Comment (jaysoo) [inline packages/next/plugins/with-nx.ts]: For deployment platforms like Vercel, or a self-contained Docker image, the folder should just be `.next` (or whatever the user sets it to).

File: packages/next/plugins/with-nx.ts [hunk 4]
```diff
@@ -130,21 +121,35 @@ async function determineDistDirForProdServer(
...
+      }`;
+      return nextConfig.distDir && nextConfig.distDir !== '.next'
+        ? joinPathFragments(outputDir, nextConfig.distDir)
+        : joinPathFragments(outputDir, '.next');
+    }
+  } catch {
+    // ignored -- fallback to Next.js default of '.next'
   }
+
+  return nextConfig.distDir || '.next';
```
Comment (jaysoo) [inline packages/next/plugins/with-nx.ts:150]: For Vercel and other platforms (including self-contained Docker images), use `.next` or whatever the user sets in their `next.config.js`.

File: packages/next/plugins/with-nx.ts [hunk 5]
```diff
@@ -155,9 +160,16 @@ export function withNx(
       const { nx, ...validNextConfig } = _nextConfig;
       return {
         ...validNextConfig,
-        distDir: await determineDistDirForProdServer(validNextConfig),
+        distDir: await determineDistDirForProdServer(_nextConfig),
       };
     } else {
+      const {
```
Comment (jaysoo) [inline packages/next/plugins/with-nx.ts:166]: Inline all of the `require` to run only during build phase. We don't need these to production.

File: packages/next/src/executors/build/lib/create-next-config-file.ts [hunk 6]
```diff
@@ -13,7 +27,77 @@ export function createNextConfigFile(
...
-    copyFileSync(nextConfigPath, join(options.outputPath, 'next.config.js'));
+    const helpersPath = join(options.outputPath, '.nx-helpers');
+    mkdirSync(helpersPath, { recursive: true });
+    copyFileSync(
+      join(__dirname, '../../../utils/compose-plugins.js'),
+      join(helpersPath, 'compose-plugins.js')
+    );
+    writeFileSync(join(helpersPath, 'with-nx.js'), getWithNxContent());
+    writeFileSync(
+      join(helpersPath, 'compiled.js'),
```
Comment (jaysoo) [inline packages/next/src/executors/build/lib/create-next-config-file.ts:40]: A smaller version of `with-nx.js` that does not depend on Nx packages.

**Review by ndcunningham — APPROVED** [review]
