### PR TITLE
fix(core): remove invalid --plain flags from affected commands

### LINKED ISSUE #2720: nx commands: --plain is invalid for commands other than nx affected:(libs|apps)
## Current Behavior

Commands other than `nx affected:apps` and `nx affected:libs` have a `--plain` option which does nothing.

## Expected Behavior

Commands other than `nx affected:apps` and `nx affected:libs` do not have a `--plain` option.

<details><summary>Original Description</summary>
# nx commands: --plain doesn't work

# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

there is no difference between `--plain`  and no `--plain`

## Current Behavior

image

### Context
```
 @nrwl/angular : Not Found
  @nrwl/cli : 9.1.2
  @nrwl/cypress : 9.1.2
  @nrwl/eslint-plugin-nx : 9.1.2
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.2
  @nrwl/linter : 9.1.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.1.2
  @nrwl/react : 9.1.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.2
  @nrwl/web : 9.1.2
  @nrwl/workspace : 9.1.2
  typescript : 3.8.3
```
</details>

### PR DESCRIPTION
**Pull request by Hotell**
ISSUES CLOSED: #2720

## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by Hotell** [comment]
hmm so the CI is quite unstable TBH, dunno if the problem is nx cache/cloud or circle 

on local all tests are green
image

File: packages/workspace/src/command-line/affected.ts [hunk 1]
```diff
@@ -17,7 +17,10 @@ import { printAffected } from './print-affected';
 import { projectHasTarget } from '../utils/project-graph-utils';
 import { DefaultReporter } from '../tasks-runner/default-reporter';
 
-export function affected(command: string, parsedArgs: yargs.Arguments): void {
+export function affected(
```
Comment (Hotell) [inline packages/workspace/src/command-line/affected.ts:20]: I added explicit types to improve DX, hope that's ok
