### PR TITLE
chore(repo): fix resolution of @cypress/request until its deps are resolved

### LINKED ISSUE #7880: Error: Cannot find module 'har-validator'
i migrated a project to angular 13 which was created before some weeks from scretch new with `npx create-nx-workspace --preset=angular`  after this i was not able to `npm i`

```
npm ERR! code 1
npm ERR! path D:\mrm-store-kit\node_modules\cypress
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node index.js --exec install
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'har-validator'
npm ERR! Require stack:
npm ERR! - D:\mrm-store-kit\node_modules\@cypress\request\lib\har.js
npm ERR! - D:\mrm-store-kit\node_modules\@cypress\request\request.js
npm ERR! - D:\mrm-store-kit\node_modules\@cypress\request\index.js
npm ERR! - D:\mrm-store-kit\node_modules\cypress\lib\tasks\download.js
npm ERR! - D:\mrm-store-kit\node_modules\cypress\lib\tasks\install.js
npm ERR! - D:\mrm-store-kit\node_modules\cypress\index.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (D:\mrm-store-kit\node_modules\@cypress\request\lib\har.js:5:16)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (D:\mrm-store-kit\node_modules\@cypress\request\request.js:23:11)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'D:\\mrm-store-kit\\node_modules\\@cypress\\request\\lib\\har.js',
npm ERR!     'D:\\mrm-store-kit\\node_modules\\@cypress\\request\\request.js',
npm ERR!     'D:\\mrm-store-kit\\node_modules\\@cypress\\request\\index.js',
npm ERR!     'D:\\mrm-store-kit\\node_modules\\cypress\\lib\\tasks\\download.js',
npm ERR!     'D:\\mrm-store-kit\\node_modules\\cypress\\lib\\tasks\\install.js',
npm ERR!     'D:\\mrm-store-kit\\node_modules\\cypress\\index.js'
npm ERR!   ]
npm ERR! }
```

i also cant create anymore a new NX workspace

```
√ What to create in the new workspace · angular
√ Application name                    · sdf
√ Default stylesheet format           · scss
√ Use Nx Cloud? (It's free and doesn't require registration.) · No

>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.

√ Installing dependencies with npm
× Creating your workspace

>  NX   ERROR  Nx failed to create a workspace.

  Exit code: 1
  Log file: C:\Users\sven\AppData\Local\Temp\tmp-12540-J6SpNKoMcyJr\error.log
```

it seems that this project comes from cypress... so cypress is depricated?

### PR DESCRIPTION
**Pull request by meeroslav**
## Current Behavior
As of version `2.88.8` the `@cypress/request` has dropped the dependency to `har-validator` although the library still depends on it.

## Expected Behavior
Since cypress is targeting `^2.88.6` we should fix it to last good version - `2.88.7` until the issue is resolved.

More details on: https://github.com/cypress-io/cypress/issues/19097

## Related Issue(s)
https://github.com/nrwl/nx/issues/7880

Fixes #7880

### CODE REVIEW

File: packages/cypress/src/utils/versions.ts [hunk 1]
```diff
@@ -1,3 +1,4 @@
 export const nxVersion = '*';
 export const cypressVersion = '^8.3.0';
+export const cypressRequestVersion = '2.88.7'; // TODO: remove this as soon as the `har-validator` is fixed on cypress side
```
Comment (leosvelperez) [inline packages/cypress/src/utils/versions.ts:3]: @meeroslav could we add the Cypress repo issue link to the TODO so it's easier to follow up?
