### PR TITLE
fix(nextjs): add workspace dependencies to transpilePackages automatically

### LINKED ISSUE #16658: Module parse failed: Unexpected token (24:7)
### Current Behavior

when running nx serve or nx build on any project that relies on a nx lib package I get the same error.

```
Module parse failed: Unexpected token (24:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
``` 

### Expected Behavior

for the build or serve to work

### GitHub Repo

https://github.com/simonpeters/nx-bug-repo

### Steps to Reproduce

I have no idea what of my project is causing this issue so its hard to reproduce. I stripped down my own repo until I got the error with 2 projects and 1 component still in it.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.19.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/nx-cloud          : 16.0.2
   typescript              : 4.9.5
```

### Failure Logs

```shell
> nx run ronnie:serve:development

error - ../ui/src/icons/FacebookIcon.tsx
Module parse failed: Unexpected token (3:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { Icon, IconProps } from "@chakra-ui/react";
| 
> export const FacebookIcon = (props: IconProps) => (
|   <Icon viewBox='0 0 27 26' {...props}>
|     <path d="M26.475 13.0886C26.475 5.98911 20.7198 0.233873 13.6203 0.233873C6.52086 0.233873 0.765625 5.98911 0.765625 13.0886C0.765625 19.5047 5.4664 24.8228 11.6118 25.7871V16.8044H8.34789V13.0886H11.6118V10.2565C11.6118 7.03481 13.5309 5.25524 16.4672 5.25524C17.8736 5.25524 19.3447 5.50631 19.3447 5.50631V8.66977H17.7237C16.1269 8.66977 15.6289 9.66066 15.6289 10.6772V13.0886H19.194L18.6241 16.8044H15.6289V25.7871C21.7742 24.8228 26.475 19.5047 26.475 13.0886Z" fill="currentColor"/>

Import trace for requested module:
../ui/src/icons/FacebookIcon.tsx
../ui/src/icons/index.tsx
../ui/src/index.ts
[ ready ] on http://localhost:4200
```

### Additional Information

I'm creating a new issue because I was unable to re-open https://github.com/nrwl/nx/issues/16516 myself.

### PR DESCRIPTION
**Pull request by jaysoo**
There are issues with Next.js not transpiling workspace libraries (i.e. packages with aliases in tsconfig). You can see this problem even without Nx, where you have to manually specify `transpilePackages` if you use aliases.

See: https://github.com/jaysoo/next-with-libs/tree/no-nx

This PR adds a feature where we will automatically add those packages for the user since we know they need to be specified anyway.

Note: This only applies if the user is not using the apps/libs setup.

## Related Issue(s)

Fixes #16658

### CODE REVIEW

File: packages/next/plugins/with-nx.ts [hunk 1]
```diff
@@ -204,6 +207,22 @@ function withNx(
         dependencies = result.dependencies;
       }
 
+      // For Next.js 13.1 and greater, make sure workspace libs are transpiled.
+      forNextVersion('>=13.1.0', () => {
```
Comment (jaysoo) [inline packages/next/plugins/with-nx.ts:211]: Added a util function that will us to support different configuration that are introduced in different Next.js versions.

**Review by ndcunningham — APPROVED** [review]

**Review by nartc — APPROVED** [review]
