### PR TITLE
fix(testing): make sure NX_WORKSPACE_ROOT_PATH exists 

### LINKED ISSUE #7237: nx test workspace fails
## Current Behavior

1. clone @nrwl/nx repo
2. remove unit test workdir : `rmdir tmp/unit`
3. run `nx test workspace --testFile=packages/workspace/src/core/project-graph/daemon/server.spec.ts` 

this will fail as can bee seen below in failure logs

## Expected Behavior

All unit tests should pass

## Steps to Reproduce

1. clone @nrwl/nx repo
2. remove unit test workdir : `rmdir tmp/unit`
3. run `nx test workspace --testFile=packages/workspace/src/core/project-graph/daemon/server.spec.ts` 

### Failure Logs

```
% nx test workspace --testFile=packages/workspace/src/core/project-graph/daemon/server.spec.ts

> nx run workspace:test --testFile=packages/workspace/src/core/project-graph/daemon/server.spec.ts 
  console.error
    
     ERROR  Daemon Client - Error: The Daemon Server is not running
    

      11 |   error: (s) => {
      12 |     if (typeof s === 'string' && s.startsWith('NX ')) {
    > 13 |       console.error(`\n${NX_ERROR} ${chalk.bold(chalk.red(s.substr(3)))}\n`);
         |               ^
      14 |     } else {
      15 |       console.error(chalk.bold(chalk.red(s)));
      16 |     }

      at Object.error (../tao/src/shared/logger.ts:13:15)
      at Socket.<anonymous> (src/core/project-graph/daemon/server.ts:373:14)

 FAIL   workspace  packages/workspace/src/core/project-graph/daemon/server.spec.ts (121.262 s)
  Daemon Server
    ✕ should be startable and stoppable (30002 ms)
    ✕ should error if the server is started multiple times (30003 ms)
    isServerAvailable()
      ✕ should return true if the daemon server is available for connections (30001 ms)
    getProjectGraphFromServer()
      ✓ should error if the server is not running (31 ms)
      ✕ should return a Promise of the workspace's ProjectGraph from the server (30005 ms)

  ● Daemon Server › should be startable and stoppable

    listen EACCES: permission denied /Users/jha/github/jhanx/tmp/unit/nx-daemon.sock

      285 |   }
      286 |   return new Promise((resolve) => {
    > 287 |     server.listen(fullOSSocketPath, () => {
          |            ^
      288 |       serverLog(`Started listening on: ${fullOSSocketPath}`);
      289 |       return resolve(server);
      290 |     });

      at src/core/project-graph/daemon/server.ts:287:12
      at Object.<anonymous> (src/core/project-graph/daemon/server.ts:286:10)
      at ../../node_modules/tslib/tslib.js:117:75
      at Object.__awaiter (../../node_modules/tslib/tslib.js:113:16)

  ● Daemon Server › should be startable and stoppable

    thrown: "Exceeded timeout of 30000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      41 |   });
      42 |
    > 43 |   it('should be startable and stoppable', async () => {
         |   ^
      44 |     const server = await startServer({});
      45 |     expect(server.listening).toBe(true);
      46 |

      at src/core/project-graph/daemon/server.spec.ts:43:3
      at Object.<anonymous> (src/core/project-graph/daemon/server.spec.ts:38:1)

  ● Daemon Server › should error if the server is started multiple times

    listen EACCES: permission denied /Users/jha/github/jhanx/tmp/unit/nx-daemon.sock

      285 |   }
      286 |   return new Promise((resolve) => {
    > 287 |     server.listen(fullOSSocketPath, () => {
          |            ^
      288 |       serverLog(`Started listening on: ${fullOSSocketPath}`);
      289 |       return resolve(server);
      290 |     });

      at src/core/project-graph/daemon/server.ts:287:12
      at Object.<anonymous> (src/core/project-graph/daemon/server.ts:286:10)
      at ../../node_modules/tslib/tslib.js:117:75
      at Object.__awaiter (../../node_modules/tslib/tslib.js:113:16)

  ● Daemon Server › should error if the server is started multiple times

    thrown: "Exceeded timeout of 30000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      49 |   });
      50 |
    > 51 |   it('should error if the server is started multiple times', async () => {
         |   ^
      52 |     await startServer({});
      53 |     await expect(startServer({})).rejects.toThrowErrorMatchingInlineSnapshot(
      54 |       `"Listen method has been called more than once without closing."`

      at src/core/project-graph/daemon/server.spec.ts:51:3
      at Object.<anonymous> (src/core/project-graph/daemon/server.spec.ts:38:1)

  ● Daemon Server › isServerAvailable() › should return true if the daemon server is available for connections

    listen EACCES: permission denied /Users/jha/github/jhanx/tmp/unit/nx-daemon.sock

      285 |   }
      286 |   return new Promise((resolve) => {
    > 287 |     server.listen(fullOSSocketPath, () => {
          |            ^
      288 |       serverLog(`Started listening on: ${fullOSSocketPath}`);
      289 |       return resolve(server);
      290 |     });

      at src/core/project-graph/daemon/server.ts:287:12
      at Object.<anonymous> (src/core/project-graph/daemon/server.ts:286:10)
      at ../../node_modules/tslib/tslib.js:117:75
      at Object.__awaiter (../../node_modules/tslib/tslib.js:113:16)

  ● Daemon Server › isServerAvailable() › should return true if the daemon server is available for connections

    thrown: "Exceeded timeout of 30000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      59 |
      60 |   describe('isServerAvailable()', () => {
    > 61 |     it('should return true if the daemon server is available for connections', async () => {
         |     ^
      62 |       expect(await isServerAvailable()).toBe(false);
      63 |
      64 |       await startServer({});

      at src/core/project-graph/daemon/server.spec.ts:61:5
      at src/core/project-graph/daemon/server.spec.ts:60:3
      at Object.<anonymous> (src/core/project-graph/daemon/server.spec.ts:38:1)

  ● Daemon Server › getProjectGraphFromServer() › should return a Promise of the workspace's ProjectGraph from the server

    listen EACCES: permission denied /Users/jha/github/jhanx/tmp/unit/nx-daemon.sock

      285 |   }
      286 |   return new Promise((resolve) => {
    > 287 |     server.listen(fullOSSocketPath, () => {
          |            ^
      288 |       serverLog(`Started listening on: ${fullOSSocketPath}`);
      289 |       return resolve(server);
      290 |     });

      at src/core/project-graph/daemon/server.ts:287:12
      at Object.<anonymous> (src/core/project-graph/daemon/server.ts:286:10)
      at ../../node_modules/tslib/tslib.js:117:75
      at Object.__awaiter (../../node_modules/tslib/tslib.js:113:16)

  ● Daemon Server › getProjectGraphFromServer() › should return a Promise of the workspace's ProjectGraph from the server

    thrown: "Exceeded timeout of 30000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      77 |     });
      78 |
    > 79 |     it(`should return a Promise of the workspace's ProjectGraph from the server`, async () => {
         |     ^
      80 |       await startServer({});
      81 |
      82 |       const projectGraph = await getProjectGraphFromServer();

      at src/core/project-graph/daemon/server.spec.ts:79:5
      at src/core/project-graph/daemon/server.spec.ts:72:3
      at Object.<anonymous> (src/core/project-graph/daemon/server.spec.ts:38:1)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 1 passed, 5 total
Snapshots:   0 total
Time:        121.371 s
Ran all test suites matching /packages\/workspace\/src\/core\/project-graph\/daemon\/server.spec.ts/i.

———————————————————————————————————————————————

>  NX   ERROR  Running target "workspace:test" failed

  Failed tasks:
  
  - workspace:test
  
  Hint: run the command with --verbose for more details.


>  NX   CLOUD  See run details at https://nx.app/runs/mwUeKIPYQy7
```

### Environment

  Node : 14.16.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : 12.10.0-beta.3
  @nrwl/angular : Not Found
  @nrwl/cli : 12.10.0-beta.3
  @nrwl/cypress : 12.10.0-beta.3
  @nrwl/devkit : 12.10.0-beta.3
  @nrwl/eslint-plugin-nx : 12.10.0-beta.3
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.0-beta.3
  @nrwl/linter : 12.10.0-beta.3
  @nrwl/nest : Not Found
  @nrwl/next : 12.10.0-beta.3
  @nrwl/node : 12.10.0-beta.3
  @nrwl/nx-cloud : 12.3.13
  @nrwl/react : 12.10.0-beta.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.0-beta.3
  @nrwl/web : 12.10.0-beta.3
  @nrwl/workspace : 12.10.0-beta.3
  @nrwl/storybook : 12.10.0-beta.3
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

### PR DESCRIPTION
**Pull request by jonhamm**
in patched_jest_resolver.js the NX_WORKSPACE_ROOT_PATH is setup
and we must ensure that this
directory exists on disk
as otherwise startServer() will fail
as the socket cannot be created in a
non-existing directory

ISSUES CLOSED: #7237

## Current Behavior

clone @nrwl/nx repo
remove unit test workdir : rmdir tmp/unit
run nx test workspace --testFile=packages/workspace/src/core/project-graph/daemon/server.spec.ts
will fail

## Expected Behavior
clone @nrwl/nx repo
remove unit test workdir : rmdir tmp/unit
run nx test workspace --testFile=packages/workspace/src/core/project-graph/daemon/server.spec.ts
will succeed

## Related Issue(s)

Fixes #7237

### CODE REVIEW

File: scripts/patched-jest-resolver.js [hunk 1]
```diff
@@ -1,7 +1,9 @@
 'use strict';
 Object.defineProperty(exports, '__esModule', { value: true });
+const { fs } = require('memfs');
```
Comment (AgentEnder) [inline scripts/patched-jest-resolver.js:3]: Can this be removed? It doesn't appear to be used anywhere

Comment (jonhamm) [reply scripts/patched-jest-resolver.js]: Indeed, must have been some automatic import i overlooked
I added a fixup
fc0a44275 - (HEAD -> make-workspace-test-run, origin/make-workspace-test-run) fixup! fix(testing): make sure NX_WORKSPACE_ROOT_PATH exists before running tests (44 seconds ago) <Jon Hammerskov>
