### PR TITLE
fix(core): not load env files when NX_LOAD_DOT_ENV_FILES is false

### LINKED ISSUE #23090: Nx serve not loading .env variable changes with monorepo format (Vite/Vue)
### Current Behavior

Using a vite/vue scaffold, running the project through a monorepo architecture and using `nx serve myapp` with a .env.local file containing variables

when we change a variable from .env, the page will reload, but the variable will match the previous value. We have to restart the nx serve to make it use the new value.

Tested directly with `vite serve`, it does work : ` [vite] .env.local changed, restarting server...`; but not through nx.
I wonder if it's caused by the daemon ?  (https://github.com/nrwl/nx/pull/22786)

### Expected Behavior

Modifying the .env.local restart the nx/vite server.

### GitHub Repo

https://github.com/NitroG42/nxenv

### Steps to Reproduce

1. start the server npm run app
2. Test should be displayed
3. Change "Test" string in .env.local
4. The page should change after reload, it doesn't.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : darwin-arm64
npm    : 10.2.4

nx (global)        : 18.3.3
nx                 : 18.3.4
@nx/js             : 18.3.4
@nx/linter         : 18.3.4
@nx/eslint         : 18.3.4
@nx/workspace      : 18.3.4
@nx/devkit         : 18.3.4
@nx/eslint-plugin  : 18.3.4
@nrwl/tao          : 18.3.4
@nx/vite           : 18.3.4
@nx/vue            : 18.3.4
@nx/web            : 18.3.4
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/vite/plugin
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by xiongemi**
## Related Issue(s)

Fixes #23090

### CODE REVIEW

**Review by leosvelperez — APPROVED** [review]

**Comment by jaysoo** [comment]
Tested it locally using the repro from #23090. It is working.

**Review by jaysoo — APPROVED** [review]

File: packages/nx/src/command-line/run/run-one.ts [hunk 1]
```diff
@@ -27,7 +27,10 @@ export async function runOne(
     string,
     (TargetDependencyConfig | string)[]
   > = {},
-  extraOptions = { excludeTaskDependencies: false, loadDotEnvFiles: true } as {
+  extraOptions = {
```
Comment (FrozenPandaz) [inline packages/nx/src/command-line/run/run-one.ts:30]: Can you also update `run-many` and `affected` please?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
