### PR TITLE
fix(nextjs): add Next.js config enhancer for supporting css moduels in workspace libs

### LINKED ISSUE #3803: Global CSS cannot be imported from files other than your Custom <App>.
Screenshot 2020-09-24 at 15 14 39
## Current Behavior
Given a generated NextJs app that imports a generated shared react lib with 
a default component that uses either css or cssModule imports fails throwing an error.

## Expected Behavior
Given a default NextJs app that imports a shared react lib with a default component that uses either css or cssModule imports should just work, no need to adapt `next.config.js` as both imports are supported by default in NextJs.

Is this a regression? Not sure, I am able to reproduce with brand new workspace and latest version of every plugin.

## Steps to Reproduce

1. npx create-nx-workspace test-bug [choose empty setup]
2. npm i  -D @nrwl/next
3. nx generate @nrwl/next:application --name=test-bug
4. nx generate @nrwl/react:library --name=shared-library
5. in the generated nextjs app add the shared component to the render function
6. try run the app `nx serve test-bug`
7. try renaming components css file to => `xxx.module.css` and it's corresponding import

### Failure Logs
```
warn  - Detected next.config.js, no exported configuration found. https://err.sh/vercel/next.js/empty-configuration
info  - automatically enabled Fast Refresh for 1 custom loader
info  - Using external babel configuration from /Users/danielq/Projects/test-workspace/apps/test-bug/.babelrc
event - compiled successfully
[ ready ] on http://localhost:3000
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
error - /Users/danielq/Projects/test-workspace/libs/shared-components/src/lib/shared-components.css
Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.tsx. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://err.sh/next.js/css-global
Location: ../../libs/shared-components/src/lib/shared-components.tsx
```

### Environment
nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.2.1
  @nrwl/cypress : 10.2.1
  @nrwl/eslint-plugin-nx : 10.2.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.1
  @nrwl/linter : 10.2.1
  @nrwl/nest : Not Found
  @nrwl/next : 10.2.1
  @nrwl/node : Not Found
  @nrwl/react : 10.2.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.1
  @nrwl/web : 10.2.1
  @nrwl/workspace : 10.2.1
  typescript : 3.9.7

### PR DESCRIPTION
**Pull request by jaysoo**
Add a `withNx` function for `next.config.js` to use. This function will modify the webpack config to allow workspace libs to use CSS modules.

## Current Behavior

CSS modules don't work in workspace libs when importing them into next.js app.

## Expected Behavior

CSS modules should work in workspace libs when importing them into next.js app.

## Related Issue(s)

Fixes #3803

### CODE REVIEW

**Review by BigAB — APPROVED** [review]

File: packages/next/plugins/with-nx.ts [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+    x instanceof RegExp &&
+    y instanceof RegExp &&
+    x.source === y.source &&
+    x.global === y.global &&
+    x.ignoreCase === y.ignoreCase &&
+    x.multiline === y.multiline
+  );
+}
+
+function withNx(nextConfig = {} as any) {
```
Comment (BigAB) [inline packages/next/plugins/with-nx.ts:16]: Need to export this

**Comment by vinverdy** [comment]
i think i have an issue related to this, babel-plugin-macros not working on library. I am not familiar with webpack, is there any clue to solve my issue? 

i try use some code from [next-transpile-modules](https://github.com/martpie/next-transpile-modules/blob/master/src/next-transpile-modules.js), but cant find it working.
