### PR TITLE
fix(angular): upgrade karma and fix settings #8961

### LINKED ISSUE #8961: Upgrade Karma for @nrwl/angular
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
The generator for @nrwl/angular for karma has out-of-date versions. Some of the features are incompatible with NG13, like coverage reporting. Can we get these up to date?

## Motivation
I ran into an issue running unit tests for my angular components when I attempted to turn on coverage reporting. The fix was to upgrade `karma`, drop the use of `karma-coverage-istanbul`, add `karma-coverage` and update the karma.conf.js. It would probably be nice to include an upgrade generator as well.

## Suggested Implementation
Just updating the packages and updating the karma.conf template.
Creating an upgrade command to update workspaces

## Alternate Implementations
Got none

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

Karma with new projects fails when run with coverage reporting

## Expected Behavior

Coverage reporting should work fine

## Related Issue(s)

Fixes #8961

### CODE REVIEW

File: packages/angular/src/migrations/update-13-8-4/migrate-karma-conf.ts [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+  const installPackages = addDependenciesToPackageJson(
+    tree,
+    {},
+    {
+      karma: '~6.3.0',
+      'karma-coverage': '~2.2.0',
+      'karma-jasmine-html-reporter': '~1.7.0',
+      'jasmine-core': '~3.10.0',
+    }
+  );
```
Comment (leosvelperez) [inline packages/angular/src/migrations/update-13-8-4/migrate-karma-conf.ts:55]: It would be better to add these versions to the `migrations.json` instead.

File: packages/angular/src/migrations/update-13-8-4/migrate-karma-conf.ts [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+
+  const rootKarmaContents = tree.read(pathToRootKarmaConf, 'utf-8');
+  const updatedKarmaContents = rootKarmaContents
+    .replace(/coverageIstanbulReporter/g, 'coverageReporter')
+    .replace(/karma-coverage-istanbul-reporter/, 'karma-coverage')
+    .replace(
+      /reports: \['html', 'lcovonly'\]/,
+      `subdir: '.',\nreporters: [{ type: 'html' }, { type: 'text-summary' }]`
+    )
+    .replace(/'\.\.\/\.\.\/coverage'/, `'./coverage'`);
```
Comment (leosvelperez) [inline packages/angular/src/migrations/update-13-8-4/migrate-karma-conf.ts:42]: I think this can be problematic. Consider this scenario:

```js
coverageIstanbulReporter: {
  dir: join(__dirname, '../../coverage'),
  reports: ['html', 'lcovonly', 'text-summary'],
  fixWebpackSourcePaths: true,
},
```

The current logic will correctly replace `coverageIstanbulReporter` with `coverageReporter` but it won't replace the `reports` key as the dev had an additional reporter (or could have one less or the same number but changed). The `fixWebpackSourcePaths` also didn't get removed. The workspace ends up with a wrong config for the coverage.

Comment (Coly010) [reply packages/angular/src/migrations/update-13-8-4/migrate-karma-conf.ts:42]: True, i guess it would be better to just replace all the reporters in `reports` with the two we know for definite are supported. My fear was trying to migrate ones that weren't supported by `karma-coverage`

also, good catch
