### PR TITLE
fix(angular): allow creating an app named 'app' or lib named 'lib'

### LINKED ISSUE #1844: Creating an angular workspace with appName='app' breaks angular.json
## Expected Behavior
I should be able to create a workspace with an angular app named "app".

## Current Behavior
The workspace gets created, but the `angular.json` file gets incorrectly modified.

## Steps to Reproduce
1. Run `npx create-nx-workspace@8.5.0 nxrepo --preset=angular --cli=angular`
2. Use "app" as the "Application name"
3. Run `ng build`

This will fail with:
```
Schema validation failed with the following errors:
  Data path ".projects['app'].projectType" should be equal to one of the allowed values.
```

This is because the `angular.json` file now contains the following:
```
{
  "version": 1,
  "projects": {
    "app": {
      "projectType": "apps/application",   // <- this
      "schematics": {},
      ...
```

## Other
For what it's worth, I tracked it to the [replaceAppNameWithPath](
https://github.com/nrwl/nx/blob/2b646f8eb4839d7b3b47bf703016e33bf1dbd2fe/packages/workspace/src/utils/cli-config-utils.ts#L32) function.

### PR DESCRIPTION
**Pull request by getabetterpic**
Currently when trying to create an app named 'app' or a lib named 'lib', the schematics inject the
'projectType' as 'apps/application' or lib as 'libs/library', breaking the Angular build.

fix #1844

## Current Behavior (This is the behavior we have today, before the PR is merged)

When creating an Angular application with the name `app`, the `angular.json` is updated but the new application has a `projectType` of `apps/application`. This breaks when trying to `yarn build app` since the `projectType` should be `application`.

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

If creating an Angular application with the name `app`, `angular.json`'s `projectType` should be `application`.

## Issue

#1844

### CODE REVIEW

File: packages/workspace/src/utils/cli-config-utils.ts [hunk 1]
```diff
@@ -39,7 +39,11 @@ export function replaceAppNameWithPath(
       `([^a-z0-9]*(${appName}))|((${appName})[^a-z0-9:]*)`,
       'gi'
     );
-    if (!!node.match(matchPattern)) {
+    if (
+      !!node.match(matchPattern) &&
+      node !== 'application' &&
+      node !== 'library'
```
Comment (getabetterpic) [inline packages/workspace/src/utils/cli-config-utils.ts]: The problem with this is on line 47 where if the app name is included in the node, then we replace it with the root. For example, say the node was `application` and the appName was `app`; the `!!node.match(matchPattern)` would return true since `app` is included in `application`. Then on line 47 the `app` in `application` is replaced with the root (`apps/app`) and becomes `apps/application`.

Checking that the node is not equal to `application` (or `library`, since it has the same issue) gets around this issue. I think there might be an issue here still if someone names the app `application` but wasn't sure if I should take that rather edge case into consideration.

**Comment by vsavkin** [comment]
Thank you for your PR!
