### PR TITLE
fix(react): fix externals for buildable libraries

### LINKED ISSUE #5508: Buildable React library contains unexpected React & Emotion dependencies
## Current Behavior

The default build output for a buildable React library generated with `@nrwl/react:library` using `--style=@emotion/styled` contains unexpected code from React and Emotion resulting in a large bundle (~70KB). 

## Expected Behavior

The build output for a React library should include only the components exported from the react library's `src/index.ts` with all the React and Emotion dependencies excluded from bundle and resulting in a very small bundle. 

## Steps to Reproduce

```sh
npx create-nx-workspace --name=nx-react-emotion-externals --preset=react --appName=nx-react-emotion-app --style=@emotion/styled 
cd nx-react-emotion-externals
npx nx generate @nrwl/react:library --name my-react-lib --style=@emotion/styled --buildable
npx nx run my-react-lib:build

> nx run my-react-lib:build 
Bundling my-react-lib...
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                              │
│   Destination: <removed>/nx-react-emotion-externals/dist/libs/my-react-lib/my-react-lib.umd.js   │
│   Bundle Size:  74.02 KB                                                                                                     │
│   Minified Size:  29.54 KB                                                                                                   │
│   Gzipped Size:  11.55 KB                                                                                                    │
│                                                                                                                              │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Bundle complete: my-react-lib
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                              │
│   Destination: <removed>/nx-react-emotion-externals/dist/libs/my-react-lib/my-react-lib.esm.js   │
│   Bundle Size:  70.25 KB                                                                                                     │
│   Minified Size:  32.51 KB                                                                                                   │
│   Gzipped Size:  12.31 KB                                                                                                    │
│                                                                                                                              │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Bundle complete: my-react-lib
```

To get the expected output I had to modify `build.options.external` to the following: 

```json 
{
  "external": [
    "@emotion/hash",
    "@emotion/is-prop-valid",
    "@emotion/memoize",
    "@emotion/react",
    "@emotion/serialize",
    "@emotion/styled",
    "@emotion/styled/base",
    "@emotion/unitless",
    "@emotion/utils",
    "react-dom",
    "react",
    "react/jsx-runtime"
  ]
}
```

Which results in the following: 

```
> nx run my-react-lib:build 
Bundling my-react-lib...
No name was provided for external module '@emotion/styled/base' in output.globals – guessing '_styled'
No name was provided for external module 'react/jsx-runtime' in output.globals – guessing 'jsxRuntime'
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                              │
│   Destination: <removed>/nx-react-emotion-externals/dist/libs/my-react-lib/my-react-lib.umd.js   │
│   Bundle Size:  4.27 KB                                                                                                      │
│   Minified Size:  2.8 KB                                                                                                     │
│   Gzipped Size:  1.11 KB                                                                                                     │
│                                                                                                                              │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Bundle complete: my-react-lib
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                              │
│   Destination: <removed>/nx-react-emotion-externals/dist/libs/my-react-lib/my-react-lib.esm.js   │
│   Bundle Size:  3.58 KB                                                                                                      │
│   Minified Size:  3.39 KB                                                                                                    │
│   Gzipped Size:  1.4 KB                                                                                                      │
│                                                                                                                              │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Bundle complete: my-react-lib
```

### Environment

```
  Node : 16.0.0
  OS   : darwin x64
  npm  : 7.10.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.0.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : 12.0.8
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : 12.0.8
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

### PR DESCRIPTION
**Pull request by puku0x**
ISSUES CLOSED: #5508

## Current Behavior

React library generator adds wrong `external` configurations in `workspace.json`.

> The default build output for a buildable React library generated with @nrwl/react:library using --style=@emotion/styled contains unexpected code from React and Emotion resulting in a large bundle (~70KB).

I found following dependencies are not need to add to `external` because they are already added (in most cases) to `dependencies` in `package.json` which Nx uses by default. 

- `react`
- `react-dom`
- `react-is`
- `styled-components`
- `@emotion/react`
- `styled-jsx`

https://github.com/nrwl/nx/blob/master/packages/web/src/builders/package/package.impl.ts#L255-L258

## Expected Behavior

React library generator should add correct and necessary `external` configurations in `workspace.json`.

## Related Issue(s)

#5689
Fixes #5508

### CODE REVIEW

File: packages/react/src/generators/library/library.ts [hunk 1]
```diff
@@ -172,20 +172,12 @@ function addProject(host: Tree, options: NormalizedSchema) {
...
-      options.style !== 'scss' &&
-      options.style !== 'styl' &&
-      options.style !== 'less' &&
-      options.style !== 'none'
-    ) {
-      external.push(
-        ...Object.keys(CSS_IN_JS_DEPENDENCIES[options.style].dependencies)
-      );
+    if (options.style === '@emotion/styled') {
+      external.push('@emotion/styled/base');
```
Comment (puku0x) [inline packages/react/src/generators/library/library.ts:178]: Only we need is to modify the import path for `@emotion/styled`.

Comment (jaysoo) [reply packages/react/src/generators/library/library.ts:178]: Do we not need `styled-components` as well?  Their docs seem to indicate it is needed. https://styled-components.com/docs/faqs#with-rollupjs

**Review by jaysoo — DISMISSED** [review]

File: packages/react/src/generators/library/library.ts (hunk 1 above)
Comment (puku0x) [reply packages/react/src/generators/library/library.ts:178]: @jaysoo Actually, we don't need to add `styled-componetns` because `@nrwl/web:package` generates the Rollup's `external` option from:
- `dependencies`/`devDependencies` from the root `package.json`
- `external` of the project from `workspace.json`
- `dependencies` from `libs/[project]/package.json`

https://github.com/nrwl/nx/blob/bcdbb02aaf7596f92e5351d29496f87f3c6a17fd/packages/web/src/builders/package/package.impl.ts#L255-L258

This means `styled-components` is added automatically as following.

image
