### PR TITLE
fix(module-federation): ensure react deps are eagerly loaded #31612

### LINKED ISSUE #31612: Rspack Module-Federation blank page
### Current Behavior

Running the host app with `nx serve-static host` should render React but it doesn't seem to load React at all - It's showing blank page with no errors, no network errors, nothing. 
This is also causing issue in production as my Cloudflare Page is serving this host as static files.

While I was debugging, the entry file, `main.ts`, loaded fine.
```tsx
// app/main.ts
console.log("This console logs on the browser")

import('./bootstrap').catch((err) => console.error(err));

```
But the `bootstrap.tsx` doesn't seem to load
```tsx
import { StrictMode } from 'react';
import * as ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './app/app';
import './styles.css';

console.log("this doesn't work");

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>
);
```

This works fine when I use `nx serve`.
I noticed this issue when I deployed my app to Cloudflare pages and I got a blank page in production, so I tried to debug with `serve-static`.

I opened react-dev-tools and it said that React wasn't loaded.

I also tried to set `"eager": true` in `shared` but it did nothing.

I tried using `const { ModuleFederationPlugin } = require('@module-federation/enhanced/rspack');`
instead of the `NxModuleFederationPlugin` and that seems to work but I want to use the NX version for the dev x.

Something is happening that the vendor code aren't being included in the final output?

Image

### Expected Behavior

Running with `nx serve-static host` should render React app.

### GitHub Repo

https://github.com/dannyseo517/mfe-test

### Steps to Reproduce

1. npx create-nx-workspace@latest
 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]
✔ Where would you like to create your workspace? · mfe-test
✔ Which stack do you want to use? · none
✔ Would you like to use Prettier for code formatting? · Yes
✔ Which CI provider would you like to use? · skip
✔ Would you like remote caching to make your build faster? · skip
2. npm install @nx/react  
3. npx nx g @nx/react:host apps/host
✔ Which stylesheet format would you like to use? · css
✔ Which E2E test runner would you like to use? · none
✔ Which bundler do you want to use to build the application? · rspack
4. npx nx serve-static host

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 22.14.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.2

nx                     : 21.2.0
@nx/js                 : 21.2.0
@nx/jest               : 21.2.0
@nx/eslint             : 21.2.0
@nx/workspace          : 21.2.0
@nx/devkit             : 21.2.0
@nx/eslint-plugin      : 21.2.0
@nx/module-federation  : 21.2.0
@nx/react              : 21.2.0
@nx/rspack             : 21.2.0
@nx/web                : 21.2.0
typescript             : 5.8.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/react/router-plugin
@nx/rspack/plugin
@nx/eslint/plugin
@nx/jest/plugin
---------------------------------------
Cache Usage: 430.47 KB / 92.64 GB
```

### Failure Logs

```shell
no errors
```

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I remember this used to work in version 20 something then I upgraded to 21.0.0 for that sweet continuous tasks and it did the blank page. I upgraded to the latest 21.2 and it's still an issue.
I included the bare minimum git repository. You can just run `npm install` and `npx nx serve-static host`.

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior
The static build for a React Module Federation application can suffer from issues where react is not initialised on load.
This is caused by Module Federation trying to lazily instantiate the library.

## Expected Behavior
Ensure that React deps are marked as eager in the module federation config to allow them to be instantiated on load

## Related Issue(s)

Fixes #31612

### CODE REVIEW

File: packages/module-federation/src/utils/framework-detection.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
+import { ProjectGraph } from '@nx/devkit';
```
Comment (ndcunningham) [inline packages/module-federation/src/utils/framework-detection.ts]: nitpick: type import

File: packages/module-federation/src/with-module-federation/react/utils.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
+import { SharedLibraryConfig } from '../../utils';
```
Comment (ndcunningham) [inline packages/module-federation/src/with-module-federation/react/utils.ts]: same here

**Review by ndcunningham — APPROVED** [review]

**Comment by Coly010** [comment]
@claude can you make the suggested changes from the PR comments
