### PR TITLE
fix(core): stream without prefixes showing tui

### LINKED ISSUE #32535: Nx incorrectly displays the TUI when outputStyle stream-without-prefixes is specified
### Current Behavior

When running an nx target with `--outputStyle stream-without-prefixes` the Nx TUI is displayed, rather than just streaming the output of the task.

### Expected Behavior

The Nx TUI shouldn't be displayed when `--outputStyle stream-without-prefixes` specified, the same as it doesn't if `--outputStyle stream` is specified.

### GitHub Repo

_No response_

### Steps to Reproduce

1. `nx affected --target test --outputStyle stream-without-prefixes`

### Nx Report

```shell
Node           : 22.16.0
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 4.1.1

nx             : 21.4.1
@nx/js         : 21.4.1
@nx/workspace  : 21.4.1
@nx/node       : 21.4.1
typescript     : 5.6.2
---------------------------------------
Cache Usage: 68.61 KB / 46.04 GB
```

### Failure Logs

```shell

```

### Package Manager Version

_No response_

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hugs7**
## Current Behavior
When using `--output-style=stream-without-prefixes` nx incorrectly shows the TUI instead of streaming

## Expected Behavior
When using `--output-style=stream-without-prefixes`, nx should stream with no prefixes just like it does with `--output-style=stream`

## Related Issue(s)

Fixes #32535

### CODE REVIEW

**Review by AgentEnder — APPROVED** [review]

File: packages/nx/src/tasks-runner/run-command.ts [hunk 1]
```diff
@@ -916,6 +916,7 @@ export function setEnvVarsBasedOnArgs(
   }
   if (nxArgs.outputStyle == 'stream-without-prefixes') {
     process.env.NX_STREAM_OUTPUT = 'true';
+    process.env.NX_PREFIX_OUTPUT = 'false';
```
Comment (hugs7) [inline packages/nx/src/tasks-runner/run-command.ts:919]: Not strictly required but good to be explicit here

**Comment by FrozenPandaz** [comment]
Thank you for your contribution! :tada: LGTM

**Comment by hugs7** [comment]
No worries. Thanks for quick review @AgentEnder @FrozenPandaz
