### PR TITLE
fix(core): misc daemon fixes 

### LINKED ISSUE #15424: Unable to update nx on windows with native code
# Current behaviour
Updating Nx when the daemon is started causes issues with unlinking the .node file. 

# Expected behaviour
The daemon should stop itself and release the handle when it notices that node_modules are being changed. 

_Originally posted by @atsjo in https://github.com/nrwl/nx/issues/15377#issuecomment-1452460971_

### LINKED ISSUE #15480: createProjectGraphAsync() causes process to not complete
### Current Behavior

When running `createProjectGraphAsync` from within the code for a project inside of an existing Nx workspace, it spawns a process that hangs and prevents the command from finishing successfully.

This was first observed when trying to use `createProjectGraphAsync` from within Lerna. I was able to create a minimal reproduction here - https://github.com/fahslaj/nx-hanging-repro. The README.md has instructions on how to reproduce the issue.

### Expected Behavior

I would expect node processes that use `createProjectGraphAsync()` to complete as expected.

### GitHub Repo

https://github.com/fahslaj/nx-hanging-repro

### Steps to Reproduce

1. Import `createProjectGraphAsync()` from `@nrwl/devkit` in a ts/js file within a project in a Nx repo.
2. Run that file with node.
3. Observe the process hanging.

Note: Steps specific to the github repo provided above are in the README.md file in that repo.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.14.2
   OS   : darwin arm64
   npm  : 9.5.0

   nx               : 15.8.3
   @nrwl/js         : 15.8.3
   @nrwl/linter     : 15.8.3
   @nrwl/workspace  : 15.8.3
   @nrwl/cli        : 15.8.3
   @nrwl/devkit     : 15.8.3
   @nrwl/tao        : 15.8.3
   typescript       : 4.9.5
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Cammisuli**
## Current Behavior
* Daemon does not stop while doing migrations
* DaemonClient reset does not close the socket connection
* DaemonClient out and err file handlers are not closed
* The socket path was created with the workspace root, but didnt take case sensitivity into account, (ie. On Windows, Nx Console will send `c:\workspace\path`, but the daemon will have `C:\workspace\path`) causing multiple daemons to always respawn

## Expected Behavior
* The Daemon will now be reset when doing migrations
* DaemonClient will reset at the appropriate time
* The file handles for the out and err writes are closed by the client (but still kept for the daemon process)
* Daemon socket path is now case insensitive

## Related Issue(s)

Fixes #15424
Fixes #15480

### CODE REVIEW

File: packages/nx/src/command-line/migrate.ts [hunk 1]
```diff
@@ -1524,6 +1524,12 @@ export async function migrate(
     process.env.NX_VERBOSE_LOGGING = 'true';
   }
 
+  try {
+    execSync('nx daemon --stop', {
+      cwd: workspaceRoot,
+    });
+  } catch {}
+
```
Comment (AgentEnder) [inline packages/nx/src/command-line/migrate.ts:1532]: This should use the runNx helper from utils/child_process

**Review by AgentEnder — DISMISSED** [review]

File: packages/nx/src/daemon/client/client.ts [hunk 2]
```diff
@@ -191,9 +191,18 @@ export class DaemonClient {
   }
 
   private async sendToDaemonViaQueue(messageToDaemon: Message): Promise<any> {
-    return this.queue.sendToQueue(() =>
-      this.sendMessageToDaemon(messageToDaemon)
-    );
+    return this.queue
+      .sendToQueue(() => this.sendMessageToDaemon(messageToDaemon))
+      .then(() => {
```
Comment (FrozenPandaz) [inline packages/nx/src/daemon/client/client.ts:196]: You need to return the value resolved here right?

File: packages/nx/src/daemon/client/client.ts [hunk 3]
```diff
@@ -191,9 +191,18 @@ export class DaemonClient {
...
+        if (this.queue.isEmpty()) {
+          this.closeConnection();
+        }
+      });
+  }
+
+  private closeConnection() {
+    this.socketMessenger.close();
+    this._connected = false;
```
Comment (FrozenPandaz) [inline packages/nx/src/daemon/client/client.ts:205]: I think this will be handled in the `onClose` handler?

File: packages/nx/src/hasher/file-hasher.ts [hunk 4]
```diff
@@ -9,6 +9,11 @@ import { NativeFileHasher } from './native-file-hasher';
 
 function createFileHasher(): FileHasherBase {
   try {
+    const dotEnv: typeof import('dotenv') = require('dotenv');
+    try {
+      dotEnv.config();
+    } catch {}
+
```
Comment (FrozenPandaz) [inline packages/nx/src/hasher/file-hasher.ts:16]: Let's make this change separately... there's more env files we should read from.

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/nx/src/daemon/client/client.ts (hunk 2 above)
Comment (Cammisuli) [reply packages/nx/src/daemon/client/client.ts]: Yea you're right. I finally found the reason why it was "working" and thats because the daemon got disabled so it never actually got here 🙄

File: packages/nx/src/command-line/migrate.ts [hunk 5]
```diff
@@ -1524,6 +1524,12 @@ export async function migrate(
     process.env.NX_VERBOSE_LOGGING = 'true';
   }
 
+  try {
```
Comment (FrozenPandaz) [inline packages/nx/src/command-line/migrate.ts:1527]: Can you use the daemon client?

File: packages/nx/src/daemon/server/shutdown-utils.ts [hunk 6]
```diff
@@ -63,6 +62,7 @@ export async function handleServerProcessTermination({
       );
     }
     serverLogger.log(`Server stopped because: "${reason}"`);
+    deleteDaemonJsonProcessCache();
```
Comment (FrozenPandaz) [inline packages/nx/src/daemon/server/shutdown-utils.ts:65]: What was the significance of moving this? On second thought.. should this be here?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/nx/src/daemon/server/shutdown-utils.ts (hunk 6 above)
Comment (Cammisuli) [reply packages/nx/src/daemon/server/shutdown-utils.ts]: Nothing, I was thinking this was affecting Windows

**Review by FrozenPandaz — APPROVED** [review]
