### PR TITLE
fix(devkit): only install deps with higher version

### LINKED ISSUE #13687: Generating a new library in an existing workspace can cause a downgrade of dependency versions in `package.json`
### Current Behavior

If you have a modified `package.json` and generate a library, e.g. with `npx nx g @nrwl/nest:lib`, the generator can cause your dependencies to downgrade to a lower version.
We've observed this behavior when we remove `jest-environment-jsdom` that comes preinstalled with `--preset=nest`. Not only will it be readded (would be fine), but [other dependency versions are nudged downwards](https://github.com/swcm-mpilz/nx-outdated-dependencies-reproducer/commit/c0cbc7a54b52cebb0082b798b471463318c47f14#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), e.g. `@types/node 18.7.1 => 16.11.7`.
Our "workaround" right now is not removing preinstalled dependencies.

### Expected Behavior

I would expect dependency versions to only be adapted upwards, not downwards - as is already the case when we don't remove the `jest-environment-jsdom` dependency.

### Github Repo

https://github.com/swcm-mpilz/nx-outdated-dependencies-reproducer/commits/main

### Steps to Reproduce

1. Generate an nx project for nest `npx create-nx-workspace nx-outdated-dependencies-reproducer --preset=nest`
2. Remove the `jest-environment-jsdom` from `package.json`
3. Generate a library `npx nx g @nrwl/nest:lib --name new-library`
4. Observe changes in `package.json`

The commits in https://github.com/swcm-mpilz/nx-outdated-dependencies-reproducer/commits/main reflect these steps.

### Nx Report

```shell
Node : 18.12.1
   OS   : linux x64
   npm  : 8.19.2
   
   nx : 15.2.4
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.4
   @nrwl/js : 15.2.4
   @nrwl/linter : 15.2.4
   @nrwl/nest : 15.2.4
   @nrwl/next : Not Found
   @nrwl/node : 15.2.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.2.4
   @nrwl/workspace : 15.2.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

_No response_

### Additional Information

Looks like the logic for this is in https://github.com/nrwl/nx/blob/87eb79ec09f1ffc0727871a408a3e803f97467d6/packages/devkit/src/utils/package-json.ts#L84

### LINKED ISSUE #14196: Using library generator downgrades jest
### Current Behavior

- run `nx generate @nrwl/node:library mylibrary` on a project with `jest@28.1.3`
- your `package.json` will now have `jest@28.1.1`

### Expected Behavior

jest version is not changed when generating a library project

### Github Repo

_No response_

### Steps to Reproduce

1. add/upgrade to `jest@28.1.3` in your NX project
2. run `nx generate @nrwl/node:library mylibrary`
3. `package.json` will have downgraded to `jest@28.1.1`

### Nx Report

```shell
npm run nx report

> nx
> nx report


 >  NX   Report complete - copy this into the issue template

   Node : 16.18.1
   OS   : darwin x64
   npm  : 8.19.3

   nx : 15.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : 15.4.2
   @nrwl/jest : 15.4.2
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.2
   @nrwl/web : 15.4.2
   @nrwl/webpack : 15.4.2
   @nrwl/workspace : 15.4.2
   @nrwl/vite : 15.4.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

_No response_

### Additional Information

I'm not sure if this should be treated as a problem with the generator, or if nx's jest is support is currently pinned to 28.1.1 -- maybe im missing something here?

### PR DESCRIPTION
**Pull request by barbados-clemens**
## Current Behavior

When deps has a higher version, devDeps will also be installed causing an issue where devDeps might install lower versions than  was is already installed.

## Expected Behavior

only newer (higher version) deps are installed

## Related Issue(s)

Fixes #13687
Fixes: #14196

### CODE REVIEW

File: packages/devkit/src/utils/package-json.ts [hunk 1]
```diff
@@ -129,22 +137,43 @@ export function addDependenciesToPackageJson(
...
       installPackagesTask(tree);
     };
   }
   return () => {};
 }
 
+/**
+ * @returns The the incoming dependencies that are higher than the existing verions
+ **/
+function removeLowerVersions(
```
Comment (barbados-clemens) [inline packages/devkit/src/utils/package-json.ts:162]: Added a new function to do this, mainly because the `updateExistingDependenciesVersion` is checking for deps vs devDeps (and vice versa) instead of just making sure the incoming vs existing deps are trimmed correctly.

**Review by AgentEnder — APPROVED** [review]
