### PR TITLE
fix(vite): add paths plugin for worker

### LINKED ISSUE #14059: [Vite] worker build should use the viteTsConfigPaths plugin
### Current Behavior

My project has a few libs imported via aliases.

The aliases are resolved as expected for all the files but the workers.

### Expected Behavior

The aliases should also apply to the workers

### Github Repo

n/a

### Steps to Reproduce

1. Create a project with a web app using vite
2. Create a lib imported via `@alias`
3. Create a worker in your web app. Add an `import * from '@alias';` in the worker lib
4. Import the worker in your web app: `import MyWorker from 'worker?worker';`
5. Build in production mode
6.You should see an error:
```
file: /.../worker.ts?worker

 >  NX   [vite]: Rollup failed to resolve import "@alias" from "/.../worker.ts".
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.10.0
   OS   : linux x64
   npm  : 8.19.2
   
   nx : 15.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : 15.4.2
   @nrwl/jest : 15.4.2
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.2
   @nrwl/webpack : 15.4.2
   @nrwl/workspace : 15.4.2
   @nrwl/vite : 15.4.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
*  Executing task in folder [...]: npx nx build [...] --configuration=production 


> nx run [...]:build:production

vite v4.0.3 building for production...
✓ 54 modules transformed.
[vite:worker] [vite]: Rollup failed to resolve import "@[...]" from "[...].ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
file: [...].ts?worker

 >  NX   [vite]: Rollup failed to resolve import "@[...]" from "[...].ts".

   This is most likely unintended because it can break your application at runtime.
   If you do want to externalize this module explicitly add it to
   `build.rollupOptions.external`
   Pass --verbose to see the stacktrace.


 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target undefined for project [...] (2s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

### Additional Information

The issue is that the `viteTsConfigPaths` does not apply to workers.

It can be solved by explicitly adding it to the worker config in `vite.config.ts`:

```
// vite.config.ts
[...]

  // Existing
  plugins: [
    viteTsConfigPaths({
      root: '../../',
    }),
  ],

 // This needs to be added:
  worker: {
    plugins: [
      viteTsConfigPaths({
        root: '../../',
      }),
    ],
  },
```

### PR DESCRIPTION
**Pull request by mandarini**
## Related Issue(s)

Fixes #14059

### CODE REVIEW

File: packages/vite/src/utils/generator-utils.ts [hunk 1]
```diff
@@ -559,6 +559,14 @@ export function createOrEditViteConfig(
     ],
     `;
 
+  const workerOption = `
+    // Uncomment this if you are using workers.
```
Comment (vicb) [inline packages/vite/src/utils/generator-utils.ts:563]: I don't think the code needs to be commented out initially.

If you are not using worker the config is not used anyway.

**Review by jaysoo — APPROVED** [review]

File: packages/vite/src/utils/generator-utils.ts (hunk 1 above)
Comment (jaysoo) [reply packages/vite/src/utils/generator-utils.ts:563]: For now we just want to keep the config small, so users can choose to delete it if they don't need the entry.

We're discussing a future Nx plugin for Vite that can encapsulate this so the tsconfig paths don't need to be manually configured like this.

**Comment by vicb** [comment]
Thanks :)
