### PR TITLE
fix(core): fail fast when running commands in parallel

### LINKED ISSUE #28477: Parallel "run-commands" does not exit with an error code when a command fails
### Current Behavior

Using a project.json like this:

```json
"testTask": {
  "executor": "nx:run-commands",
  "options": {
    "commands": ["./scripts/some-failing-script.sh", "./run-my-server.js"],
    "parallel": true,
    "cwd": "{projectRoot}"
  }
}
```

When the `some-failing-script.sh` it does not fail the task and the task keeps running in bad state. e.g. we use this for setting up a proxy and a webserver for running tests. If the proxy fails, we want the whole task to fail immediately too (because none of the tests will pass now anyway).

I believe this is a bug because the code running the commands is written to handle errors (see: https://github.com/nrwl/nx/blob/c902036e160350cd2fb4a6edc746e5467a29be9c/packages/nx/src/executors/run-commands/run-commands.impl.ts#L173) but `r.result.success` is returned as true even when the command fails with a `1` exit code.

We tried a workaround of using a `readyWhen` entry set to the error message and whilst this does stop the task, it also exists the whole Nx task with a success error code.

### Expected Behavior

If a command being ran in parallel fails, the whole task should also fail immediately.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Add a task with a configuration as above
2. Call a failing script and a long running script (such as a server) in the parallel commands

### Nx Report

Node           : 20.18.0
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 4.5.0

nx                 : 19.5.6
@nx/js             : 19.5.6
@nx/jest           : 19.5.6
@nx/linter         : 19.5.6
@nx/eslint         : 19.5.6
@nx/workspace      : 19.5.6
@nx/cypress        : 19.5.6
@nx/devkit         : 19.5.6
@nx/esbuild        : 19.5.6
@nx/eslint-plugin  : 19.5.6
@nx/node           : 19.5.6
@nx/playwright     : 19.5.6
@nx/react          : 19.5.6
@nx/storybook      : 19.5.6
@nrwl/tao          : 19.5.6
@nx/web            : 19.5.6
@nx/webpack        : 19.5.6
typescript         : 5.3.3
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/storybook/plugin

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leosvelperez**
## Current Behavior

When running commands in parallel with `nx:run-commands`, if a command fails, others are not stopped, and the task continues until all commands finish. This means that if a long-running command is running, it won't be stopped when other commands have already failed.

## Expected Behavior

`nx:run-commands` should fail fast. In a parallel execution, the rest of the running commands should be terminated if a command fails.

## Related Issue(s)

Fixes #28477

### CODE REVIEW

File: packages/nx/src/executors/run-commands/running-tasks.ts [hunk 1]
```diff
@@ -122,33 +122,59 @@ export class ParallelRunningTasks implements RunningTask {
...
+      await Promise.allSettled(
         this.childProcesses.map(async (childProcess) => {
+          runningProcesses.add(childProcess);
+
           childProcess.onOutput((terminalOutput) => {
             for (const cb of this.outputCallbacks) {
               cb(terminalOutput);
             }
           });
-          const result = await childProcess.getResults();
```
Comment (FrozenPandaz) [inline packages/nx/src/executors/run-commands/running-tasks.ts:132]: `getResults` already waits for process exit..

Don't we just need to check the result to see if other processes should be terminated?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
