### PR TITLE
fix(core): ensure its file before reading

### LINKED ISSUE #17545: Error while converting CRA to Vite using "nx init": "Error: EISDIR: illegal operation on a directory, read"
### Current Behavior

Attempted to use NX to convert an app from Create-React-App (CRA) to Vite.
```
PS C:\Users\trist\GitHub\GDevelop\GDevelop\newIDE\app> npx nx@latest init

 >  NX   🐳 Nx initialization

√ Enable distributed caching to make your CI faster · No

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]


 >  NX   Creating your v16.3.2 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Successfully created the workspace: temp-workspace.

 >  NX   Directory is already under version control. Skipping initialization of git.


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 


 >  NX   First time using Nx? Check out this interactive Nx tutorial.

   https://nx.dev/react-tutorial/1-code-generation


 >  NX   👋 Welcome to Nx!


 >  NX   🧹 Clearing unused files


 >  NX   🚚 Moving your React app in your new Nx workspace


 >  NX   🧑‍🔧  Setting up Vite

nx init

Adds Nx to any type of workspace. It installs nx, creates an nx.json configuration file and optionally sets up distributed caching. For more info, check https://nx.dev/recipes/adopting-nx.

Options:
  --help         Show help                                                                                                                                                                     [boolean]
  --version      Show version number                                                                                                                                                           [boolean]
  --nxCloud      Set up distributed caching with Nx Cloud.                                                                                                                                     [boolean]
  --interactive  When false disables interactive input prompts for options.                                                                                                    [boolean] [default: true]
  --integrated   Migrate to an Nx integrated layout workspace. Only for Angular CLI workspaces and CRA projects.                                                              [boolean] [default: false]
  --addE2e       Set up Cypress E2E tests in integrated workspaces. Only for CRA projects.                                                                                    [boolean] [default: false]
  --force        Force the migration to continue and ignore custom webpack setup or uncommitted changes. Only for CRA projects.                                               [boolean] [default: false]
  --vite         Use Vite as the bundler. Only for CRA projects.                                                                                                               [boolean] [default: true]

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:738:3)
    at tryReadSync (node:fs:438:20)
    at readFileSync (node:fs:484:19)
    at C:\Users\trist\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\nx\src\command-line\init\implementation\react\rename-js-to-jsx.js:10:53
    at Array.forEach (<anonymous>)
    at renameJsToJsx (C:\Users\trist\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\nx\src\command-line\init\implementation\react\rename-js-to-jsx.js:9:11)
    at C:\Users\trist\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\nx\src\command-line\init\implementation\react\index.js:206:50
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\trist\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\tslib\tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}
```

### Expected Behavior

The NX conversion script will complete successfully.
My app will be converted from CRA to Vite, and run successfully.

### GitHub Repo

https://github.com/tristanbob/GDevelop/tree/testing-vite

### Steps to Reproduce

1. Use the `main` branch of `tristanbob/GDevelop`
2. Start in the directory `GDevelop\newIDE\app`
3. Run `npx nx@latest init`
4. Script crashes with error

### Nx Report

```shell
nx : The term 'nx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At line:1 char:1
+ nx report
+ ~~
    + CategoryInfo          : ObjectNotFound: (nx:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Failure Logs

```shell
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:738:3)
    at tryReadSync (node:fs:438:20)
    at readFileSync (node:fs:484:19)
    at C:\Users\trist\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\nx\src\command-line\init\implementation\react\rename-js-to-jsx.js:10:53
    at Array.forEach (<anonymous>)
    at renameJsToJsx (C:\Users\trist\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\nx\src\command-line\init\implementation\react\rename-js-to-jsx.js:9:11)
    at C:\Users\trist\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\nx\src\command-line\init\implementation\react\index.js:206:50
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\trist\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\tslib\tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mandarini**
Make sure glob match is file and not directory before attempting to read.

Fixes #17545

### CODE REVIEW

File: packages/nx/src/command-line/init/implementation/react/rename-js-to-jsx.ts [hunk 1]
```diff
@@ -8,11 +8,14 @@ export function renameJsToJsx(appName: string, isStandalone: boolean) {
   );
 
   files.forEach((file) => {
-    const content = readFileSync(file).toString();
-    // Try to detect JSX before renaming to .jsx
-    // Files like setupTests.js from CRA should not be renamed
-    if (/<[a-zA-Z0-9]+/.test(content)) {
-      renameSync(file, `${file}x`);
+    const fileStats = lstatSync(file);
```
Comment (jaysoo) [inline packages/nx/src/command-line/init/implementation/react/rename-js-to-jsx.ts:11]: We can use `fileExists` from fileutils here.

**Review by jaysoo — APPROVED** [review]

File: packages/nx/src/command-line/init/implementation/react/rename-js-to-jsx.ts (hunk 1 above)
Comment (mandarini) [reply packages/nx/src/command-line/init/implementation/react/rename-js-to-jsx.ts]: Done
