### PR TITLE
fix(nextjs): remove tsconfig.app.json

### LINKED ISSUE #4651: Next.js build doesn't error when there are TypeScript erros
## Current Behavior

Next.js doesn't fail when there is a TypeScript error during dev mode, but it fails when building the app (unless the `ignoreBuildErrors: true` is added to the `next.config.js`).

## Expected Behavior

Given `site` is a next.js app, then running `nx run site:build` should fail when there is a TypeScript error

## Steps to Reproduce

1. Generate a new Next.js app
2. open `index.tsx` and some lines that generate a typescript error. e.g. `let x = 'hi'; x = 3; console.log(x)`
3. run `nx run <appname>:build`

### Environment

```
  Node : 12.14.0
  OS   : darwin x64
  yarn : 1.22.4
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.6
  @nrwl/cypress : 11.2.6
  @nrwl/devkit : 11.2.6
  @nrwl/eslint-plugin-nx : 11.2.6
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.6
  @nrwl/linter : 11.2.6
  @nrwl/nest : Not Found
  @nrwl/next : 11.2.6
  @nrwl/node : Not Found
  @nrwl/react : 11.2.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.6
  @nrwl/web : 11.2.6
  @nrwl/workspace : 11.2.6
  typescript : 4.0.5
```

### PR DESCRIPTION
**Pull request by kirjai**
## Current Behavior

Running a build on a Next.js project succeeds even if there are TS errors in that application's code.

[Next.js looks for a tsconfig.json file exclusively, during the build](https://github.com/vercel/next.js/blob/master/packages/next/lib/verifyTypeScriptSetup.ts#L19). However, in our case, `tsconfig.json` at the root of a Next.js application is a solution-style config, so it doesn't have anything in the `"files"` or `"includes"`. This results in Next.js skipping type checking during the build, thus ignoring TS errors in the application source files.

## Expected Behavior

Running a `build` on a Next.js project with TS errors should fail with the TS errors.

## Related Issue(s)

Fixes #4651

### CODE REVIEW

**Comment by kirjai** [comment]
The fact that this PR solves a problem where TS errors went undetected by the `build` command - exposed what seems to be genuine TS errors in two e2e tests.
These were tests that test `less` support, and `styl` support. In both cases, TS was complaining about missing type declarations for `.module.less` and `module.styl` files. 

So what i've done to fix that is add generic type declarations for those import types. Next.js does the same for `.module.css` files under the hood, but doesn't do it for `module.less` nor `module.styl` files.

**Comment by kirjai** [comment]
Do we need a migration for this change?

File: packages/next/src/generators/application/lib/create-application-files.ts [hunk 1]
```diff
@@ -52,6 +52,5 @@ export function createApplicationFiles(host: Tree, options: NormalizedSchema) {
   if (options.js) {
     host.delete(`${options.appProjectRoot}/index.d.ts`);
     toJS(host);
-    updateTsConfigsToJs(host, { projectRoot: options.appProjectRoot });
```
Comment (kirjai) [inline packages/next/src/generators/application/lib/create-application-files.ts:55]: all changes that are done within this function are either already in place for Next.js apps, or we don't want to perform them, due to Next.js apps not following the `tsconfig.app.json` convention

**Review by FrozenPandaz — APPROVED** [review]
LGTM
