### PR TITLE
fix(storybook): ignore nx storybook plugin from sb eslint

### LINKED ISSUE #16629: @nx/react/plugins/storybook is not installed after migrating to 16.0.0
### Current Behavior

Screenshot 2023-04-28 at 08 40 07

I'm getting this eslint error after migrating to version 16. This got added `@nx/react/plugins/storybook` used to be named `@nrwl/react/plugins/storybook` and it didn't give me issues then.

### Expected Behavior

I expect this to not give any eslint errors. I've tried deleting my `node_modules` and reinstalling everything, restarting my ESLint server etc.

I've made sure that `@nx/react` is installed, but just none of it works.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Migrate from any version before 16 and you should see this issue

### Nx Report

```shell
Node   : 18.14.2
   OS     : linux arm64
   npm    : 9.5.0
   Hasher : Native
   
   nx                      : 16.0.0
   @nx/js                  : 16.0.0
   @nrwl/js                : 16.0.0
   @nx/jest                : 16.0.0
   @nrwl/jest              : 16.0.0
   @nx/linter              : 16.0.0
   @nrwl/linter            : 16.0.0
   @nx/workspace           : 16.0.0
   @nrwl/workspace         : 16.0.0
   @nx/cypress             : 16.0.0
   @nrwl/cypress           : 16.0.0
   @nx/devkit              : 16.0.0
   @nrwl/devkit            : 16.0.0
   @nx/eslint-plugin       : 16.0.0
   @nrwl/eslint-plugin-nx  : 16.0.0
   @nx/react               : 16.0.0
   @nrwl/react             : 16.0.0
   @nx/storybook           : 16.0.0
   @nrwl/storybook         : 16.0.0
   @nrwl/tao               : 16.0.0
   @nx/web                 : 16.0.0
   @nrwl/web               : 16.0.0
   @nx/webpack             : 16.0.0
   @nrwl/webpack           : 16.0.0
   @nrwl/nx-cloud          : 16.0.5
   nx-cloud                : 16.0.5
   typescript              : 4.9.5
```

### Failure Logs

_No response_

### Additional Information

Add you can see in the Nx Report, there seem to be `@nrwl` versions and `@nx` version which might be the cause of the conflict. I feel like the migration steps should have gotten rid of the `@nrwl` stuff.

### PR DESCRIPTION
**Pull request by mandarini**
## Current Behavior
If workspace uses `plugin:storybook/recommended` eslint plugin and `@nx/react/plugins/storybook` storybook addon, then a linting error is thrown, because it cannot see that the plugin is installed. Reference: https://github.com/storybookjs/eslint-plugin-storybook/pull/129

## Expected Behavior
If `@nx/react/plugins/storybook` and workspace uses the `plugin:storybook/recommended` eslint plugin, then ignore our package from the `no-uninstalled-addons` rule.

Also, add this rule to our `.eslintrc.json`.

## Related Issue(s)

https://github.com/nrwl/nx/issues/16629

### CODE REVIEW

**Review by Coly010 — APPROVED** [review]

**Review by AgentEnder — APPROVED** [review]

File: packages/storybook/src/migrations/update-16-1-0/eslint-ignore-react-plugin.ts [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    if (!tree.exists(sbConfigPath)) {
+      sbConfigPath = joinPathFragments(config.root, '.storybook/main.js');
+    }
+
+    if (!tree.exists(sbConfigPath)) {
+      continue;
+    }
+
+    const sbConfig = tree.read(sbConfigPath, 'utf-8');
+    console.log('sbConfig', sbConfig);
```
Comment (jaysoo) [inline packages/storybook/src/migrations/update-16-1-0/eslint-ignore-react-plugin.ts:26]: remove

**Review by jaysoo — CHANGES_REQUESTED** [review]

**Review by jaysoo — APPROVED** [review]

**Review by philipjfulcher — APPROVED** [review]

**Review by meeroslav — APPROVED** [review]
Apart from the leftover console.log, looks good
