### PR TITLE
fix(core): Fix issue when no scripts are found in package.json

### LINKED ISSUE #12893: add-nx-to-monorepo fails with confusing error for minimal package.json
I am trying to add nx to a monorepo I am trynig to create for my python packages
 - I am using nx for the first time
 - I am trying to structure my code in a monorepo for the first time (package based monorepo)

## Current Behavior
`npx add-nx-to-monorepo` fails with an unclear error

## Expected Behavior

I was expecting it to ask some questions or at the very least tell me why it can't ask me questions

## Steps to Reproduce

The `package.json` I have in my python project was added mainly for commitlint
```
{
  "devDependencies": {
    "@commitlint/cli": "^17.0.0",
    "@commitlint/config-conventional": "^17.0.0",
    "cz-conventional-changelog": "^3.3.0"
  },
  "config": {
    "commitizen": {
      "path": "./commitizen.js"
    }
  }
}
```
When I try to run `$ npx add-nx-to-monorepo` - it fails.

Easiest way to reproduce seems to be:
```
$ mkdir /tmp/test_nx
$ echo '{}' > package.json
$ npx add-nx-to-monorepo
```

### Failure Logs

```
$ npx add-nx-to-monorepo

 >  NX   🐳 Nx initialization


 >  NX   🧑‍🔧 Please answer the following questions about the scripts found in your workspace in order to generate task runner configuration

/home/abdealijk/.npm/_npx/dcff4b037c44fe4f/node_modules/enquirer/lib/types/array.js:38
      throw new Error('At least one choice must be selectable');
            ^

Error: At least one choice must be selectable
    at MultiSelect.reset (/home/abdealijk/.npm/_npx/dcff4b037c44fe4f/node_modules/enquirer/lib/types/array.js:38:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MultiSelect.initialize (/home/abdealijk/.npm/_npx/dcff4b037c44fe4f/node_modules/enquirer/lib/types/array.js:25:5)
    at async /home/abdealijk/.npm/_npx/dcff4b037c44fe4f/node_modules/enquirer/lib/prompt.js:236:7
```

### Environment

I am using Ubuntu 18.04 with WSL2 on Windows 10

### PR DESCRIPTION
**Pull request by ndcunningham**
Fixes #12893

### CODE REVIEW

File: packages/add-nx-to-monorepo/src/add-nx-to-monorepo.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ async function addNxToMonorepo() {
   let scriptOutputs = {} as { [script: string]: string };
   let useCloud: boolean;
 
-  if (parsedArgs.yes !== true) {
+  if (parsedArgs.yes !== true || scripts.length > 0) {
```
Comment (FrozenPandaz) [inline packages/add-nx-to-monorepo/src/add-nx-to-monorepo.ts:52]:
```suggestion
  if (parsedArgs.yes !== true && scripts.length > 0) {
```

If they said `yes` AND if they have scripts.. we do NOT want to prompt them.
If they did not say `yes` AND they have scripts... we DO want to prompt.
If they did not say `yes` AND they DO NOT have scripts.... we DO NOT want to prompt.

**Review by FrozenPandaz — DISMISSED** [review]

**Review by AgentEnder — APPROVED** [review]
