### PR TITLE
fix(linter): apply enforce-module-boundaries rule to import expressions

### LINKED ISSUE #3857: Dependency constrains are not announced when loading library lazily
## Current Behavior
When I'm trying to import Angular library with `loadChildren`, `nx-enforce-module-boundaries` rule doesn't announce any message, while the esm import works just fine
image

As you can see, no linting message
image

## Expected Behavior
When I import lib through `loadChildren` I expect to see the same message as it would be with importing through esm import

## Steps to Reproduce
Repo: https://github.com/chernodub/nx-acht
1. Create lib with `scope` different from `scope:shared` to make sure it doesn't match any constraints
2. Try to import with `loadChildren`

### Environment
```
  "dependencies": {
    "@angular/animations": "^10.0.0",
    "@angular/common": "^10.0.0",
    "@angular/compiler": "^10.0.0",
    "@angular/core": "^10.0.0",
    "@angular/forms": "^10.0.0",
    "@angular/platform-browser": "^10.0.0",
    "@angular/platform-browser-dynamic": "^10.0.0",
    "@angular/router": "^10.0.0",
    "@google-cloud/firestore": "^4.2.0",
    "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/platform-express": "^7.0.0",
    "@nrwl/angular": "10.0.7",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-ng-packagr": "~0.1000.5",
    "@angular/cli": "~10.0.0",
    "@nrwl/workspace": "10.0.7",
    "@types/node": "~8.9.4",
    "dotenv": "6.2.0",
    "ng-packagr": "^10.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "eslint": "6.8.0",
    "typescript": "~3.9.3",
    "prettier": "2.0.4",
    "@nrwl/nest": "10.0.7",
    "@angular/compiler-cli": "^10.0.0",
    "@angular/language-service": "^10.0.0",
    "@angular-devkit/build-angular": "~0.1000.0",
    "codelyzer": "~5.0.1",
    "jest-preset-angular": "8.1.2",
    "@nrwl/jest": "10.0.7",
    "jest": "25.2.3",
    "@types/jest": "25.1.4",
    "ts-jest": "25.2.1",
    "cypress": "^4.1.0",
    "@nrwl/cypress": "10.0.7",
    "@nrwl/node": "10.0.7",
    "@nestjs/schematics": "^7.0.0",
    "@nestjs/testing": "^7.0.0"
  }
```

### PR DESCRIPTION
**Pull request by puku0x**
## Current Behavior

`enforce-module-boundaries` rule is applied only import declarations.

## Expected Behavior

`enforce-module-boundaries` rule is applied both import declarations and expressions.

## Related Issue(s)

Fixes #3857

### CODE REVIEW

File: packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts [hunk 1]
```diff
@@ -119,173 +122,181 @@ export default createESLintRule<Options, MessageIds>({
...
-            messageId: 'noImportsOfApps',
+            messageId: 'noImportOfNonBuildableLibraries',
           });
           return;
         }
+      }
+
+      // if we import a library using loadChildren, we should not import it using es6imports
+      if (
+        node.type === AST_NODE_TYPES.ImportDeclaration &&
```
Comment (puku0x) [inline packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts:242]: I added this line because `TSESTree.ImportExpression` does not have `importKind`

**Comment by jaysoo** [comment]
Hey @puku0x, thanks for the PR! Can you also add a test case to the spec file so we capture this case and prevent regression?

**Comment by puku0x** [comment]
@jaysoo I added tests for import expressions.

**Review by JamesHenry — APPROVED** [review]
