### PR TITLE
fix(core): ensure external dependency hashes are resolved in a deterministic way

### LINKED ISSUE #17917: Cache Invalidation Issue in CI/CD Pipeline (Jenkins) - Inconsistent Hash Value
### Current Behavior

I am encountering an issue with cache invalidation while running tasks in my CI/CD pipeline using Jenkins with the Nx workspace. The problem specifically relates to the inconsistent hash value of the cache, leading to unexpected behavior during the pipeline execution. even after replaying the same pipeline-build without doing any single change, cache is invalidated as hash value is changing

### Expected Behavior

The cache should be utilized effectively during the pipeline run, allowing for faster execution times by reusing previously cached results where possible.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Configure Jenkins to run the Nx tasks in the CI/CD pipeline.
2. Execute the pipeline and observe the cache behavior.

### Nx Report

```shell
npm  : 9.5.1
   
   nx               : 15.7.0
   @nrwl/jest       : 15.9.4
   @nrwl/linter     : 15.9.4
   @nrwl/workspace  : 15.7.0
   @nrwl/angular    : 15.9.4
   @nrwl/cli        : 15.7.0
   @nrwl/cypress    : 15.9.4
   @nrwl/devkit     : 15.9.4
   @nrwl/js         : 15.9.4
   @nrwl/tao        : 15.7.0
   @nrwl/webpack    : 15.9.4
   typescript       : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/effects              : 15.3.0
   @ngrx/store                : 15.3.0
   @nx/webpack                : 16.2.1
   rxjs                       : 6.6.7
   @ng-bootstrap/ng-bootstrap : 14.0.1
   @ngrx/store-devtools       : 15.3.0
   @reef/fwk                  : 4.0.7
   ngx-build-plus             : 15.0.0
```

### Failure Logs

_No response_

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

1. I have observed that the cache behavior in my local development environment is working as expected, with consistent and 
 valid hash values.
2. The cache invalidation issue only arises when running the pipeline in the CI/CD environment using Jenkins.
3. The problem occurs consistently across multiple pipeline runs.

### PR DESCRIPTION
**Pull request by skrtheboss**
## Current Behavior

External dependency hashes are not deterministic and could cause cache misses, since the hash is dependent on which task was hashed when. 

## Expected Behavior

Task hashes should not depend on which task have been hashed earlier.

## Related Issue(s)

Fixes #17917

### CODE REVIEW

**Comment by skrtheboss** [comment]
The regression has been introduced by https://github.com/nrwl/nx/pull/16926.

This issue is preventing us to upgrade to 16.4.x, since our build cache no longer works correctly, and even without changing anything, the build needs to re-execute nearly all targets.

**Comment by skrtheboss** [comment]
Since @meeroslav is the author of the pull request, i am going to mention him.

**Review by meeroslav — APPROVED** [review]
Looks good to me

**Comment by meeroslav** [comment]
Have you pinpointed where (and why) exactly is the error happening on CI? The proposed PR looks ok, and I think it improves accuracy, but I don't see any evidence supporting that this would actually fix the linked problem.

**Comment by skrtheboss** [comment]
@meeroslav i have added a test which fails if the patch is not applied.

The hashed value of appB was dependent if appA was hashed prior to it.

File: packages/nx/src/hasher/task-hasher.ts [hunk 1]
```diff
@@ -429,13 +429,14 @@ class TaskHasherImpl {
...
-        this.projectGraph.dependencies[projectName].forEach((d) => {
-          if (!visited.has(d.target)) {
-            partialHashes.push(this.hashExternalDependency(d.target, visited));
-          }
-        });
-      }
+      this.projectGraph.dependencies[projectName]?.forEach((d) => {
+        if (!visited.has(d.target)) {
+          partialHashes.push(
+            this.hashExternalDependency(d.target, new Set(visited))
```
Comment (FrozenPandaz) [inline packages/nx/src/hasher/task-hasher.ts:435]: I don't like that a new `Set` is created each time. A lot more memory will be used.

When we hash an external dependency, there is always a `source` and a `target`.

As you noticed ,when `A -> C` and `B -> C`, these are two different dependencies which should both be visited. I think the `visited` Set should have both `source` and `target` as items. When C is hashed for A, it should record that `A -> C` has been visited. and when C is then visited to be hashed for `B -> C` it won't find it in the `Set` and it will hash.

So I think the signature here should change to:

```ts
  private hashExternalDependency(
    sourceProjectName: string,
    targetProjectName: string,
    visited = new Set<string>()
  ): string {
    visited.add(`${sourceProjectName}->${targetProjectName}`);
    ...
```

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/nx/src/hasher/task-hasher.ts (hunk 1 above)
Comment (skrtheboss) [reply packages/nx/src/hasher/task-hasher.ts]: I have changed the code accordingly, let me know if it is correct.

**Comment by skrtheboss** [comment]
Rebased and applied requested changes in the fixup commit.

File: packages/nx/src/hasher/task-hasher.ts [hunk 2]
```diff
@@ -332,7 +332,10 @@ class TaskHasherImpl {
                     visited
                   );
                 } else {
-                  const hash = this.hashExternalDependency(d.target);
+                  const hash = this.hashExternalDependency(
+                    task.target.target,
```
Comment (meeroslav) [inline packages/nx/src/hasher/task-hasher.ts:336]: This should be source from the dependency. Task target would not be accurate, as it's a name of the target not a package.
```suggestion
                    d.source,
```

File: packages/nx/src/hasher/task-hasher.ts [hunk 3]
```diff
@@ -429,22 +445,30 @@ class TaskHasherImpl {
...
       }
       // we want to calculate the hash of the entire dependency tree
-      if (this.projectGraph.dependencies[projectName]) {
-        this.projectGraph.dependencies[projectName].forEach((d) => {
-          if (!visited.has(d.target)) {
-            partialHashes.push(this.hashExternalDependency(d.target, visited));
-          }
-        });
-      }
+      this.projectGraph.dependencies[targetProjectName]?.forEach((d) => {
```
Comment (meeroslav) [inline packages/nx/src/hasher/task-hasher.ts:448]: Please keep the original format as optional chaining adds additional unnecessary checks when compiled to javascript. Also it's a bit more readable in my opinion.

File: packages/nx/src/hasher/task-hasher.ts [hunk 4]
```diff
@@ -470,7 +494,7 @@ class TaskHasherImpl {
       const executorPackage = target.executor.split(':')[0];
       const executorNodeName =
         this.findExternalDependencyNodeName(executorPackage);
-      hash = this.hashExternalDependency(executorNodeName);
+      hash = this.hashExternalDependency(targetName, executorNodeName);
```
Comment (meeroslav) [inline packages/nx/src/hasher/task-hasher.ts:497]: This is not correct. The source is the project name.
```suggestion
      hash = this.hashExternalDependency(projectName, executorNodeName);
```

File: packages/nx/src/hasher/task-hasher.ts [hunk 5]
```diff
@@ -482,7 +506,7 @@ class TaskHasherImpl {
           const externalDependencies = input['externalDependencies'];
           for (let dep of externalDependencies) {
             dep = this.findExternalDependencyNodeName(dep);
-            partialHashes.push(this.hashExternalDependency(dep));
+            partialHashes.push(this.hashExternalDependency(targetName, dep));
```
Comment (meeroslav) [inline packages/nx/src/hasher/task-hasher.ts:509]: Same here, source is the project name
```suggestion
            partialHashes.push(this.hashExternalDependency(projectName, dep));
```

**Review by meeroslav — CHANGES_REQUESTED** [review]

**Comment by skrtheboss** [comment]
Hi @meeroslav i have rebased again and applied requested changes in the 2nd fixup commit.

**Review by meeroslav — APPROVED** [review]
Looks good! Thank you!

**Review by meeroslav — APPROVED** [review]

**Review by FrozenPandaz — APPROVED** [review]

**Comment by FrozenPandaz** [comment]
Thank you for making the changes! LGTM :tada:

**Comment by atsjo** [comment]
Betting this will fix the caching problems I have observed as well since 16.2.x, and reported in https://github.com/nrwl/nx/issues/17081
Managed to make it work most of the time by restructuring one of the projects in my repo, but sometimes it still doesn't use the cache, and it seems non-deterministic.

**Comment by meeroslav** [comment]
@skrtheboss we are planning a patch today
