### PR TITLE
fix(core): nx migrate should accept tags other than latest and next for community packages

### LINKED ISSUE #15633: nx migrate should handle any tag of type string
### Current Behavior

Precondition 
 `
 {
 ...
 "dependencies": {
 @mycompany/example: 1.2.32
 }
 `

`npm view @mycompany/example@alpha version   `
**1.2.33**

`nx migrate @mycompany/example@alpha` alpha or any other string should be considered a valid tag and should not be normalized

 `
 {
 ...
 "dependencies": {
 @mycompany/example: 0.0.0
 }
 `

### Expected Behavior

 `
 {
 ...
 "dependencies": {
 @mycompany/example: 1.2.33
 }
 `

### GitHub Repo

_No response_

### Steps to Reproduce

1.
 `
 {
 ...
 "dependencies": {
 @mycompany/example: 1.2.32
 }
 `

2.`npm view @mycompany/example@alpha version   `
**1.2.33**

3.`nx migrate @mycompany/example@alpha` alpha or any other string should be considered a valid tag and should not be normalized

### Nx Report

```shell
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 14.21.2
   OS   : darwin arm64
   npm  : 6.14.17
   
   nx : 14.5.4
   @nrwl/angular : 14.5.4
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 14.5.4
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.4
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         @hyland/ui: 5.5.2
         @ngneat/transloco: 4.2.1
         @ngrx/data: 14.0.2
         @ngrx/effects: 14.0.2
         @ngrx/entity: 14.0.2
         @ngrx/router-store: 14.0.2
         @ngrx/store: 14.0.2
         @ngrx/store-devtools: 14.0.2
         apollo-angular: 4.0.1
         rxjs: 6.6.6
         @ngrx/schematics: 14.0.2
         ng-mocks: 14.1.3
         nx-stylelint: 11.2.1
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
`nx migrate mypackage@alpha` fails, resolves the version as 0.0.0 since the tag is not normalized properly.

## Expected Behavior
`nx migrate mypackage@alpha` fails, resolves the version as 0.0.0 since the tag is not normalized properly.

## Alt solutions:
Instead of resolving on the registry ahead of time, we could feasibly just inline a list of accepted tags. This wouldn't fix the issue in the general case, but realistically a list of `['prev', 'previous', 'next', 'latest', 'beta', 'alpha', 'rc', 'dev']` would likely hit most use cases.

## Related Issue(s)

Fixes #15633

### CODE REVIEW

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/nx/src/command-line/migrate.ts [hunk 1]
```diff
@@ -56,6 +56,7 @@ import { isCI } from '../utils/is-ci';
 import { getNxRequirePaths } from '../utils/installation-directory';
 import { readNxJson } from '../config/configuration';
 import { runNxSync } from '../utils/child-process';
+import { Console } from 'console';
```
Comment (FrozenPandaz) [inline packages/nx/src/command-line/migrate.ts:59]: remove?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/nx/src/command-line/migrate.ts [hunk 2]
```diff
@@ -614,14 +615,24 @@ const LEGACY_NRWL_PACKAGE_GROUP: ArrayPackageGroup = [
...
+    }
+  }
   return normalizeVersion(version);
 }
 
-function versionOverrides(overrides: string, param: string) {
+async function versionOverrides(overrides: string, param: string) {
   const res = {};
-  overrides.split(',').forEach((p) => {
+  for (const p of overrides.split(',')) {
```
Comment (FrozenPandaz) [inline packages/nx/src/command-line/migrate.ts:635]: Could you use `Promise.all`?

File: packages/nx/src/command-line/migrate.ts [hunk 3]
```diff
@@ -707,19 +728,21 @@ type RunMigrations = {
...
-}): GenerateMigrations | RunMigrations {
+}): Promise<GenerateMigrations | RunMigrations> {
   if (options.runMigrations === '') {
     options.runMigrations = 'migrations.json';
   }
 
   if (!options.runMigrations) {
     const from = options.from
-      ? versionOverrides(options.from as string, 'from')
+      ? await versionOverrides(options.from as string, 'from')
```
Comment (FrozenPandaz) [inline packages/nx/src/command-line/migrate.ts:740]: Could you use `Promise.all` here to get both of these at the same time?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
