### PR TITLE
fix(devkit): properly emit failures when converting nx executor

### LINKED ISSUE #4725: cypress e2e exit on status 0 even when there are failing tests
After updating my **NX** version from `11.0.15` to the latest one (cypress's version stayed the same), my e2e tests were starting to pass even when my tests were failing, after downgrading the version from the latest one back to `11.0.15` it got back to work as expected.

## Current Behavior
Cypress exit on status 0 even when there are failing tests.

## Expected Behavior
The e2e should exit with status 1 (or above) when there are failing tests according to the [cypress docs](https://docs.cypress.io/guides/guides/command-line.html#Exit-code)

## Steps to Reproduce
* create a new workspace
* create a failing e2e test
* run `$ npm run e2e -- --headless --exit`
* run `$ echo $?`

The output should be "1", but "0" is received (meaning the tests passed successfully).

### Environment
```
  Node : 14.15.0
  OS   : win32 x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : 11.0.4
  @nrwl/cli : 11.0.4
  @nrwl/cypress : 11.0.4
  @nrwl/devkit : 11.0.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.4
  @nrwl/linter : 11.0.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.4
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.4
  typescript : 4.0.5
```

### LINKED ISSUE #4860: Cannot determine cypress e2e result on CI
Command `npm run e2e --headless` that runs cypress e2e tests doesn't return non-zero exit code on test failure. If wecompare it to protractor then it returns exit code 1 in case of e2e test failure.

## Current Behavior
By running `npm run e2e && echo $?` the command returns exit code 0 in case of failed e2e test.

This looks like to be an issue with NX executor convertor that always maps the executor's output success flag to `true`:
https://github.com/nrwl/nx/blob/11.2.x/packages/devkit/src/utils/convert-nx-executor.ts#L39-L46

## Expected Behavior
By running `npm run e2e --headless` on a test with failure it will return non-zero exit code.
This exit code information can then be used to determine the e2e test phase result on CI, if it was success or not.

## Steps to Reproduce
* `npx create-nx-workspace --preset=angular`
* edit the pre-existing e2e test in a way it will fail
* `npm run e2e --headless && echo $?`
* exit code will be 0 (regardless of success or failure)

### Failure Logs
Exit code after a unsuccessful e2e test run returns 0
image

### Environment
```
  Node : 12.16.0
  OS   : linux x64
  npm  : 6.14.8
  
  nx : Not Found
  @nrwl/angular : 11.3.1
  @nrwl/cli : 11.3.1
  @nrwl/cypress : 11.3.1
  @nrwl/devkit : 11.3.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.3.1
  @nrwl/linter : 11.3.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.3.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.3.1
  typescript : 4.0.7
```

### PR DESCRIPTION
**Pull request by FrozenPandaz**
## Current Behavior

Converted Nx Executors always emit `{ success: true }`.

## Expected Behavior

Converted Nx Executors properly emit output events.

## Related Issue(s)

Fixes https://github.com/nrwl/nx/issues/4860
Fixes https://github.com/nrwl/nx/issues/4725

### CODE REVIEW

File: packages/devkit/src/utils/convert-nx-executor.ts [hunk 1]
```diff
@@ -36,29 +36,46 @@ export function convertNxExecutor(executor: Executor) {
...
+      let asyncIterator = promiseOrAsyncIterator as AsyncIterableIterator<T>;
+      let prev: IteratorResult<T>;
+
+      function recurse(iterator: AsyncIterableIterator<T>) {
+        iterator
+          .next()
+          .then((result) => {
+            if (!result.done) {
+              subscriber.next(result.value);
+              prev = result;
```
Comment (srnec) [inline packages/devkit/src/utils/convert-nx-executor.ts:60]: this `prev` variable looks like to be not used anywhere

Comment (FrozenPandaz) [reply packages/devkit/src/utils/convert-nx-executor.ts]: Thanks! :+1:

**Comment by jukben** [comment]
Thanks a lot for fix. This caused me us a quite a headache. Any idea when this gets released? 🙏
