### PR TITLE
fix(core): ignored directories should never contain projects

### LINKED ISSUE #13637: Nx is very slow in a large monorepo (>500k files) due to globbing of `**/project.json`
### Current Behavior

Reopening https://github.com/nrwl/nx/issues/9660

I'm trying to integrate nx in an existing large monorepo (>500k files), but it only has ~25 workspaces.
When nx initializes, it tries to get the list of workspaces by globbing both `**/project.json` and all the `workspaces` items from `package.json`:

https://github.com/nrwl/nx/blob/61d7d74378305ba96f9e94707aefeecb438328ca/packages/nx/src/config/workspaces.ts#L703

This `**/project.json` forces the glob to crawl every file, and that takes 5+s in my case, just the init phase of every command.

Dropping `**/project.json` from the glob makes the glob operation instantaneous.
A fix would be to have something similar to `getGlobPatternsFromPackageManagerWorkspaces` that only reads package path entries from package.json workspaces instead, and appends `project.json`.

https://github.com/nrwl/nx/blob/61d7d74378305ba96f9e94707aefeecb438328ca/packages/nx/src/config/workspaces.ts#L687

### Expected Behavior

To have a faster nx boot time.

### Github Repo

_No response_

### Steps to Reproduce

Any repo with hundreds of thousands of files should show the slowness.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : darwin arm64
   yarn : 3.2.4
   
   nx : 15.2.4
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.0
   @nrwl/js : Not Found
   @nrwl/linter : 14.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 14.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
Adding a directory to .nxignore doesn't stop project globbing from entering it

## Expected Behavior
Adding a directory to .nxignore stops project globbing from entering it

## Related Issue(s)

Related #13637

### CODE REVIEW

File: packages/nx/src/config/workspaces.ts [hunk 1]
```diff
@@ -615,35 +620,31 @@ export function globForProjectFiles(
...
+    ignore: staticIgnores,
     absolute: false,
     cwd: root,
     dot: true,
     suppressErrors: true,
-  });
+  };
+
+  const globResults = globSync(combinedProjectGlobPattern, opts);
+  console.log(opts);
```
Comment (FrozenPandaz) [inline packages/nx/src/config/workspaces.ts:645]: rm

**Review by FrozenPandaz — APPROVED** [review]
