### PR TITLE
fix(nextjs): fix .next folder linting

### LINKED ISSUE #11541: eslint is giving me many errors coming from .next folder
## Current Behavior
When I run eslint on my workspace that has an app that uses Next.js, I get so many errors and warnings coming from the `.next` folder.

## Expected Behavior

`.next` folder should be ignored by eslint.

## Steps to Reproduce

Have a workspace using Nx 14.5.4 with a Next.js application. I'm not sure if this happens to newly created workspaces, it happened to me when updating from a previous version.

The migration did not set the `.next` folder to be ignored by eslint. I can see that the [migration to 14.5.3](https://github.com/nrwl/nx/tree/master/packages/next/src/migrations/update-14-5-3) adds the `.next` folder to `.gitignore`, but it should set the folder to be ignored by eslint as well.

### Environment
```
   Node : 16.16.0
   OS   : darwin arm64
   npm  : 8.11.0
   
   nx : 14.5.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : 14.5.4
   @nrwl/next : 14.5.4
   @nrwl/node : 14.5.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.4
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

### PR DESCRIPTION
**Pull request by ndcunningham**
ISSUES CLOSED: #11541

## Related Issue(s)

Fixes #

### CODE REVIEW

File: packages/next/src/generators/application/lib/add-linting.ts [hunk 1]
```diff
@@ -36,6 +36,11 @@ export async function addLinting(
         // Turn off @next/next/no-html-link-for-pages since there is an issue with nextjs throwing linting errors
         // TODO(nicholas): remove after Vercel updates nextjs linter to only lint ["*.ts", "*.tsx", "*.js", "*.jsx"]
 
+        reactEslintJson.ignorePatterns = [
```
Comment (FrozenPandaz) [inline packages/next/src/generators/application/lib/add-linting.ts:39]: Could this go into a `.eslintignore` file at the root?

Comment (ndcunningham) [reply packages/next/src/generators/application/lib/add-linting.ts:39]: I don't think so since next uses the react `.eslintignore`  [here](https://github.com/nrwl/nx/blob/master/packages/next/src/generators/application/lib/add-linting.ts#L28).

Comment (ndcunningham) [reply packages/next/src/generators/application/lib/add-linting.ts:39]: I think the pattern `.next/` is project specific, so probably not

Comment (jaysoo) [reply packages/next/src/generators/application/lib/add-linting.ts:39]: I think since `.eslintignore` isn't always present ,we can keep this just in the app's ignore folder.

File: packages/next/src/migrations/update-14-5-7/update-next-eslint.ts [hunk 2]
```diff
@@ -0,0 +1,28 @@
+import { formatFiles, getProjects, Tree, updateJson } from '@nrwl/devkit';
+
+export async function updateNextEslint(host: Tree) {
+  const projects = getProjects(host);
+
+  projects.forEach((project) => {
+    if (project.targets?.build?.executor !== '@nrwl/next:build') return;
+
+    const eslintPath = `${project.root}/.eslintrc.json`;
+    debugger;
```
Comment (jaysoo) [inline packages/next/src/migrations/update-14-5-7/update-next-eslint.ts:10]: remove debugger

File: packages/next/src/migrations/update-14-5-7/update-next-eslint.spec.ts [hunk 3]
```diff
@@ -0,0 +1,88 @@
+import { readJson, Tree } from '@nrwl/devkit';
+import { createTreeWithEmptyV1Workspace } from '@nrwl/devkit/testing';
+import { updateNextEslint } from './update-next-eslint';
+
+describe('Add next eslint 14.5.7', () => {
+  let tree: Tree;
+
+  beforeEach(async () => {
+    tree = createTreeWithEmptyV1Workspace();
```
Comment (jaysoo) [inline packages/next/src/migrations/update-14-5-7/update-next-eslint.spec.ts:9]: I think we want to use `createTreeWithEmptyWorkspace` here, and `updateProjectConfiguration` so it's more future-proof.
