### PR TITLE
fix(core): load config util supports absolute paths on windows

### LINKED ISSUE #21936: Remix Crystal Plugin unable to create nodes on Windows
The nx-console extension for vscode is still crashing with the following error when trying to initialize when i have a squeaky clean fresh install of a remix app. I also already made the quick change that @Coly010 recommended.

Windows 11 OS, node 20 LTS, all latest versions as of 22 feb 2024

```bash
[Nxls] - 2024-02-22T09:29:03.532Z - Error: Unable to create nodes for apps/remix-app/remix.config.js using plugin @nx/remix/plugin. 

	 Inner Error: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'f:'
    at new NodeError (node:internal/errors:405:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:131:11)
    at defaultLoad (node:internal/modules/esm/load:82:3)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:603:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\project-graph\utils\project-configuration-utils.js:156:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async Promise.all (index 3)
    at async createProjectConfigurations (F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\project-graph\utils\retrieve-workspace-files.js:89:62)
    at async processFilesAndCreateAndSerializeProjectGraph (F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:140:28)
    at async getCachedSerializedProjectGraphPromise (F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:43:16)
    at async handleRequestProjectGraph (F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\daemon\server\handle-request-project-graph.js:12:24)
    at async handleResult (F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\daemon\server\server.js:110:16)
    at async handleMessage (F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\daemon\server\server.js:81:9)
```

_Originally posted by @binaryartifex in https://github.com/nrwl/nx/issues/21714#issuecomment-1959040096_

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

when a plugin attempts to load an ESM config file during graph creation with an absolute path on windows, it falls over as the protocol is unsupported.

## Expected Behavior

Use pathToFileURl to correctly form the path needed for ESM config files to be imported.

## Related Issue(s)

Fixes #21936

### CODE REVIEW

**Review by jaysoo — APPROVED** [review]

File: packages/devkit/src/utils/config-utils.ts [hunk 1]
```diff
@@ -71,7 +72,15 @@ async function load(path: string): Promise<any> {
   } catch (e: any) {
     if (e.code === 'ERR_REQUIRE_ESM') {
       // If `require` fails to load ESM, try dynamic `import()`.
-      return await dynamicImport(`${path}?t=${Date.now()}`);
+      try {
+        return await dynamicImport(`${path}?t=${Date.now()}`);
+      } catch (e) {
+        if (e.code === 'ERR_UNSUPPORTED_ESM_URL_SCHEME') {
```
Comment (FrozenPandaz) [inline packages/devkit/src/utils/config-utils.ts:78]: Why do we have to `try catch` this? Can't we ensure that the URL scheme is supported?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/devkit/src/utils/config-utils.ts (hunk 1 above)
Comment (Coly010) [reply packages/devkit/src/utils/config-utils.ts:78]: I will do some investigations

Comment (Coly010) [reply packages/devkit/src/utils/config-utils.ts]: Yes we can.

**Review by FrozenPandaz — APPROVED** [review]
