### PR TITLE
fix(react): add React dependencies to package.json when adding a library

### LINKED ISSUE #2188: bug: @nrwl/react - missing @babel/preset-react and react when running build on react publishable library
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

`nx build ui-button` should build react library

## Current Behavior

Build fails. 

image

when I explicitly install `yarn add -D @babel/preset-react`. Build starts working.

Although it will still fail because of missing `react`

image

On needs to manually install dependencies:

```
yarn add react react-dom @types/react @types/react-dom
```

After these manual steps build will work.

I expected that those dependencies would be added when running `react:lib` for first time (at least the `@babel/react-preset`

## Failure Information (for bugs)

- see above

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npx create-nx-workspace@latest my-workspace
2. choose empty workspace
3. yarn add -D @nrwl/react
4. yarn nx g @nrwl/react:lib ui-button --publishable

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

- version of Nx used:
```
  @nrwl/angular : Not Found
  @nrwl/cli : 8.9.0
  @nrwl/cypress : 8.9.0
  @nrwl/eslint-plugin-nx : 8.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 8.9.0
  @nrwl/linter : 8.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 8.9.0
  @nrwl/react : 8.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.9.0
  @nrwl/web : 8.9.0
  @nrwl/workspace : 8.9.0
  typescript : 3.5.3
```
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### PR DESCRIPTION
**Pull request by BigAB**
This PR:
 * adds `react` and `react-dom` to the `package.json`  `dependencies` when generating a react library project
* has the `react` `init` schematic use `addDepsToPackageJson` to modify the deps and dev deps
* no longer moves `@nrwl/react` from `dependencies` to `devDependencies` (as per Jacks suggestion 😄 )

Resolves #2188

### CODE REVIEW

File: packages/react/src/schematics/init/init.ts [hunk 1]
```diff
@@ -1,9 +1,11 @@
 import { chain, noop, Rule } from '@angular-devkit/schematics';
+import { JsonObject } from '@angular-devkit/core';
```
Comment (BigAB) [inline packages/react/src/schematics/init/init.ts:2]: This is just moved from below, an old habit of grouping external imports before internal ones

**Review by jaysoo — APPROVED** [review]
