### PR TITLE
fix(module-federation): restore support for relative URLs in module federation remotes

### LINKED ISSUE #31538: Relative URLs for Module Federation remotes no longer work after PR #30615
### Current Behavior

Hi Nx team 👋,

After upgrading Nx to latest (21) version, our builds are now failing when using relative URLs for Module Federation remotes.

MF config:

```
withModuleFederation({
  name: 'my-app,
  remotes: ['remote', 'remote@remote/remoteEntry.js'],
});
```

It was caused by fixing this bug: [#30615](https://github.com/nrwl/nx/pull/30615)

### Expected Behavior

The module federation remote can be specified also with a relative URL.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Clone nx monorepo
2. Setup module federation config
```
withModuleFederation({
  name: 'my-app,
  remotes: ['remote', 'remote@remote/remoteEntry.js'],
});
```
3. Try to build the app

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.13.1
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 4.8.1

nx                     : 21.1.3
@nx/js                 : 21.1.3
@nx/jest               : 21.1.3
@nx/eslint             : 21.1.3
@nx/workspace          : 21.1.3
@nx/cypress            : 21.1.3
@nx/devkit             : 21.1.3
@nx/eslint-plugin      : 21.1.3
@nx/module-federation  : 21.1.3
@nx/plugin             : 21.1.3
@nx/react              : 21.1.3
@nx/rollup             : 21.1.3
@nx/storybook          : 21.1.3
@nx/web                : 21.1.3
@nx/webpack            : 21.1.3
typescript             : 5.7.3
---------------------------------------
Cache Usage: 0.00 B / 22.83 GB
```

### Failure Logs

```shell
NX   Invalid URL

TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at handleArrayRemote (/Users/dejv/projects/prime-live/client/node_modules/@nx/module-federation/src/utils/remotes.js:36:25)
    at mapRemotes (/Users/dejv/projects/prime-live/client/node_modules/@nx/module-federation/src/utils/remotes.js:19:43)
    at getModuleFederationConfig (/Users/dejv/projects/prime-live/client/node_modules/@nx/module-federation/src/with-module-federation/webpack/utils.js:72:25)
    at withModuleFederation (/Users/dejv/projects/prime-live/client/node_modules/@nx/module-federation/src/with-module-federation/webpack/with-module-federation.js:14:112)
    at /Users/dejv/projects/prime-live/client/apps/lpp-fe/webpack.config.js:31:34
    at combined (/Users/dejv/projects/prime-live/client/node_modules/@nx/webpack/src/utils/config.js:26:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getWebpackConfigs (/Users/dejv/projects/prime-live/client/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:28:16)
    at async webpackExecutor (/Users/dejv/projects/prime-live/client/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:89:21)
```

### Package Manager Version

yarn 4.8.1

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

  Module federation configurations with relative URLs are broken due to PR
   #30615, which forced all remote URLs to be parsed as absolute URLs
  using `new URL()`. This breaking change prevents developers from using
  relative URLs in their module federation setups, causing runtime errors
  when the application tries to load remote modules.

  ## Expected Behavior

  Module federation should support both relative and absolute URLs
  seamlessly:
  - Relative URLs should work as they did before, maintaining backward
  compatibility
  - Absolute URLs should continue to work with enhanced query parameter
  support
  - The URL processing should be consistent across all module federation
  helpers (Angular and React)

  ## Related Issue(s)

  Fixes #31538

### CODE REVIEW

File: packages/angular/mf/url-helpers.ts [hunk 1]
```diff
@@ -0,0 +1,85 @@
+// Helper function to extract file extension from a path
+function extname(path: string): string {
```
Comment (jaysoo) [inline packages/angular/mf/url-helpers.ts:2]: How come we don't use the one from `@nx/module-federation` for Angular?

**Review by ndcunningham — APPROVED** [review]

**Review by jaysoo — APPROVED** [review]
