### PR TITLE
fix(js): postProcessInlinedDependencies throwing error on movePackage

### LINKED ISSUE #16125: @nrwl/js inline.ts `postProcessInlinedDependencies` tries to move the same inline library twice
### Current Behavior

If you want to export non buildable libraries inside a publishable libraries, the `postProcessInlinedDependencies` tries to move the same library multiple times.

As the library has already moved the first time, the 2nd time will fail and throw an error.

This is caused by the following line: https://github.com/nrwl/nx/blob/6f747f9a5cf125e9b1b5ae3570b773e49e4c1f54/packages/js/src/utils/inline.ts#L82

### Expected Behavior

Build does not error

### GitHub Repo

https://github.com/Itrulia/nrwl-js-postProcessInlinedDependencies-issue

### Steps to Reproduce

1. npm i
2. npx nx build website

### Nx Report

```shell
nrwl-js-postProcessInlinedDependencies-issue on  main via  v16.16.0 on ☁️  karl@wepublish.ch
❯ nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin arm64
   npm  : 8.11.0

   nx                      : 15.9.2
   lerna                   : 3.22.1
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 15.3.3
   typescript              : 4.6.4
```

### Failure Logs

```shell
Log of Object.values(inlineGraph.dependencies):

[
  [
    'page-website',
    'article-website',
    'navigation-website',
    'richtext-website',
    'membership-website',
    'block-content-website',
    'authentication-website',
    'website-builder',
    'website-api',
    'website-api-v2'
  ],
  [ 'website-api', 'website-builder', 'block-content-website' ],
  [
    'website-api', 'website-api',
    'website-api', 'website-api',
    'website-api', 'website-api',
    'website-api', 'website-api',
    'website-api', 'website-api',
    'website-api', 'website-api'
  ],
  [
    'website-builder',
    'website-api',
    'richtext-website',
    'website-builder',
    'website-api',
    'richtext-website',
    'website-builder',
    'website-api',
    'richtext-website'
  ],
  [
    'website-builder',
    'website-builder',
    'website-builder',
    'website-builder'
  ],
  [ 'website-api', 'website-builder', 'block-content-website' ],
  [ 'website-api', 'website-builder' ],
  [ 'website-builder', 'website-api', 'authentication-website' ],
  [ 'website-api', 'website-api' ]
]


Log of depOutputPath, destDepOutputPath:


/Users/itrulia/Documents/nrwl-js-postProcessInlinedDependencies-issue/dist/libs/website libs/page/website
/Users/itrulia/Documents/nrwl-js-postProcessInlinedDependencies-issue/dist/libs/website libs/article/website
/Users/itrulia/Documents/nrwl-js-postProcessInlinedDependencies-issue/dist/libs/website libs/navigation/website
/Users/itrulia/Documents/nrwl-js-postProcessInlinedDependencies-issue/dist/libs/website libs/richtext/website
/Users/itrulia/Documents/nrwl-js-postProcessInlinedDependencies-issue/dist/libs/website libs/membership/website
/Users/itrulia/Documents/nrwl-js-postProcessInlinedDependencies-issue/dist/libs/website libs/block-content/website
/Users/itrulia/Documents/nrwl-js-postProcessInlinedDependencies-issue/dist/libs/website libs/authentication/website
/Users/itrulia/Documents/nrwl-js-postProcessInlinedDependencies-issue/dist/libs/website libs/website-builder
/Users/itrulia/Documents/nrwl-js-postProcessInlinedDependencies-issue/dist/libs/website libs/website-api
/Users/itrulia/Documents/nrwl-js-postProcessInlinedDependencies-issue/dist/libs/website libs/website-api-v2
/Users/itrulia/Documents/nrwl-js-postProcessInlinedDependencies-issue/dist/libs/website libs/website-api
```

### Additional Information

This error is most likely happening because there are multiple libraries depending on the same library multiple times.

### PR DESCRIPTION
**Pull request by Itrulia**
Moved the deletion of the `libs` folder to a later stage, to avoid errors when multiple libraries depend on the same library.

closes https://github.com/nrwl/nx/issues/16125

### CODE REVIEW

File: packages/js/src/utils/inline.ts [hunk 1]
```diff
@@ -88,6 +88,8 @@ export function postProcessInlinedDependencies(
     }
   }
 
+  // TODO: hard-coded "libs"
```
Comment (Itrulia) [inline packages/js/src/utils/inline.ts:91]: Same as the `/src` above

Comment (nartc) [reply packages/js/src/utils/inline.ts:91]: let's use `libsDir()`?

Comment (Itrulia) [reply packages/js/src/utils/inline.ts:91]: @nartc i could not find a function called `libsDir`, I found `getWorkspaceLayout` but there's no access to a Tree there. Could you point me to the right function? I'm gonna update the PR asap then.

Thank you!

Comment (jaysoo) [reply packages/js/src/utils/inline.ts:91]: We should be handling this in a more generic way. FYI, the inline feature will be replaced in a future release but for now we should check if a package is already moved before attempting, rather than moving it here.

**Review by jaysoo — APPROVED** [review]

**Comment by Itrulia** [comment]
Amazing, thank you!
