### PR TITLE
fix(devkit): ensurePackage should obey npmrc and yarnrc.yml

### LINKED ISSUE #16644: Nx generate fails to run yarn install commands with Yarn 3 and custom registries.
### Current Behavior

When running a generator which is missing plugins, I.E. @nrwl/react:application without having cypress/webpack/web installed, Nx fails at the yarn add steps.

```
Fetching @nrwl/cypress...

 >  NX   Command failed: yarn add -D @nrwl/cypress@15.9.3
```

However, copy/pasting the command that it says failed, works perfectly fine.

### Expected Behavior

Nx should be able to run `yarn add` without problems.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Set project to use yarn 3.5
2. Use a yarnrc.yaml in the project which points to custom registries.
3. Run a generate command which requires additional plugins, such as `yarn nx g @nrwl/react:application` without having @nrwl/cypress installed.

### Nx Report

```shell
nx                      : 15.9.3
   @nrwl/js                : 15.9.3
   @nrwl/linter            : 15.9.3
   @nrwl/workspace         : 15.9.3
   @nrwl/eslint-plugin-nx  : 15.9.3
   @nrwl/react             : 15.9.3
   typescript              : 4.9.5
```

### Failure Logs

```shell
Fetching @nrwl/cypress...

 >  NX   Command failed: yarn add -D @nrwl/cypress@15.9.3

   Pass --verbose to see the stacktrace.
```

### Additional Information

We're pointing at internal registries in our corporate network which live in Artifactory npm mirrors. The registries are required to use the Artifactory API keys from the yarnrc.yaml file to authenticate.

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
`ensurePackage` does not know how to obey `.npmrc`, `.yarnrc`, or `.yarnrc.yml`

`nx migrate` only obeys `.npmrc`

## Expected Behavior
All package manager config files are obeyed

## Related Issue(s)

Fixes #16644

### CODE REVIEW

File: packages/nx/src/utils/package-manager.ts [hunk 1]
```diff
@@ -118,16 +119,30 @@ export function getPackageManagerVersion(
...
 
+export function copyPackageManagerConfigurationFiles(
+  root: string,
+  destination: string
+) {
+  for (const packageManagerConfigFile of ['.npmrc', '.yarnrc', '.yarnrc.yml']) {
+    const f = findFileInPackageJsonDirectory(packageManagerConfigFile, root);
+    if (f) {
+      // Copy config file if it exists, so that the package manager still follows it.
+      copyFileSync(f, `${destination}/.npmrc`);
```
Comment (FrozenPandaz) [inline packages/nx/src/utils/package-manager.ts:141]: Change this to be the file found

File: packages/devkit/src/utils/replace-package.spec.ts [hunk 2]
```diff
@@ -1,15 +1,19 @@
 import { replaceNrwlPackageWithNxPackage } from './replace-package';
 
-import { Tree } from 'nx/src/generators/tree';
-import { createTreeWithEmptyWorkspace } from 'nx/src/generators/testing-utils/create-tree-with-empty-workspace';
-import {
+import type { Tree } from 'nx/src/generators/tree';
```
Comment (FrozenPandaz) [inline packages/devkit/src/utils/replace-package.spec.ts:3]: Remove all changes to spec files

File: packages/devkit/.eslintrc.json [hunk 3]
```diff
@@ -39,7 +15,29 @@
     {
       "files": ["*.ts", "*.tsx"],
       "rules": {
-        "@typescript-eslint/explicit-module-boundary-types": ["error"]
+        "@typescript-eslint/explicit-module-boundary-types": ["error"],
+        "@typescript-eslint/no-restricted-imports": [
```
Comment (FrozenPandaz) [inline packages/devkit/.eslintrc.json:19]: Move these up to the previous .ts block

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
