### PR TITLE
fix(module-federation): ensure @nx/module-federation package is installed for users

### LINKED ISSUE #29269: NX 20.2.1, Newly created react-monorepo & module federation setup doesn't work
### Current Behavior

` npx create-nx-workspace react-monorepo --preset=react-monorepo --pm=pnpm`

then choose:
app name = my-app
bundler = rspack
test runner = none
stylesheet = CSS
CI = later
cacheing = no

`cd react-monorepo`

`pnpm nx g @nx/react:host shell --remotes=remote --bundler=rspack`

stylesheet = css
e2e = none

*succeeds*

`nx serve shell`

FAILS with error:

 NX   Remote failed to start. A complete log can be found in: /Volumes/Code/react-monorepo/.nx/workspace-data/2024-12-09T15_30_47_332Z-build.log

LOG

```

 NX   Running target build for project remote:

- remote



> nx run remote:build:production


 NX   Cannot find module '@nx/module-federation/rspack'

Require stack:
- /Volumes/Code/react-monorepo/remote/rspack.config.ts
- /Volumes/Code/react-monorepo/remote/rspack.config.prod.ts
- /Volumes/Code/react-monorepo/node_modules/.pnpm/@nx+rspack@20.2.1_@module-federation+enhanced@0.7.6_@module-federation+node@2.6.11_@swc-node+_vvolop54a2iqvroiphed6tvd2q/node_modules/@nx/rspack/src/utils/resolve-user-defined-rspack-config.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/@nx+rspack@20.2.1_@module-federation+enhanced@0.7.6_@module-federation+node@2.6.11_@swc-node+_vvolop54a2iqvroiphed6tvd2q/node_modules/@nx/rspack/src/executors/rspack/lib/config.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/@nx+rspack@20.2.1_@module-federation+enhanced@0.7.6_@module-federation+node@2.6.11_@swc-node+_vvolop54a2iqvroiphed6tvd2q/node_modules/@nx/rspack/src/utils/create-compiler.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/@nx+rspack@20.2.1_@module-federation+enhanced@0.7.6_@module-federation+node@2.6.11_@swc-node+_vvolop54a2iqvroiphed6tvd2q/node_modules/@nx/rspack/src/executors/rspack/rspack.impl.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/config/schema-utils.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/command-line/run/executor-utils.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/devkit-internals.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/utils/assert-workspace-validity.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/project-graph/build-project-graph.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/project-graph/project-graph.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/project-graph/file-utils.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/utils/package-manager.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/utils/package-json.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/utils/print-help.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/command-line/run/run.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/bin/run-executor.js
Pass --verbose to see the stacktrace.

 NX   Running target build for project remote failed

Failed tasks:

- remote:build:production
```

So it looks like it's just missing  '@nx/module-federation/rspack' package, so I triied to install it, but that didn't work. Realiized I need just @nx/module-federation so installed that, and now it works.

So I think the generators need to be updated to install this package.

### Expected Behavior

Shell app is served with remotes.

### GitHub Repo

_No response_

### Steps to Reproduce

1. ` npx create-nx-workspace react-monorepo --preset=react-monorepo --pm=pnpm`

then choose:
app name = my-app
bundler = rspack
test runner = none
stylesheet = CSS
CI = later
cacheing = no

`cd react-monorepo`

2. `pnpm nx g @nx/react:host shell --remotes=remote --bundler=rspack`

stylesheet = css
e2e = none

*succeeds*

3. `nx serve shell`

FAILS with error:

 NX   Remote failed to start. A complete log can be found in: /Volumes/Code/react-monorepo/.nx/workspace-data/2024-12-09T15_30_47_332Z-build.log

LOG

```

 NX   Running target build for project remote:

- remote



> nx run remote:build:production


 NX   Cannot find module '@nx/module-federation/rspack'

Require stack:
- /Volumes/Code/react-monorepo/remote/rspack.config.ts
- /Volumes/Code/react-monorepo/remote/rspack.config.prod.ts
- /Volumes/Code/react-monorepo/node_modules/.pnpm/@nx+rspack@20.2.1_@module-federation+enhanced@0.7.6_@module-federation+node@2.6.11_@swc-node+_vvolop54a2iqvroiphed6tvd2q/node_modules/@nx/rspack/src/utils/resolve-user-defined-rspack-config.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/@nx+rspack@20.2.1_@module-federation+enhanced@0.7.6_@module-federation+node@2.6.11_@swc-node+_vvolop54a2iqvroiphed6tvd2q/node_modules/@nx/rspack/src/executors/rspack/lib/config.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/@nx+rspack@20.2.1_@module-federation+enhanced@0.7.6_@module-federation+node@2.6.11_@swc-node+_vvolop54a2iqvroiphed6tvd2q/node_modules/@nx/rspack/src/utils/create-compiler.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/@nx+rspack@20.2.1_@module-federation+enhanced@0.7.6_@module-federation+node@2.6.11_@swc-node+_vvolop54a2iqvroiphed6tvd2q/node_modules/@nx/rspack/src/executors/rspack/rspack.impl.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/config/schema-utils.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/command-line/run/executor-utils.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/devkit-internals.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/utils/assert-workspace-validity.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/project-graph/build-project-graph.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/project-graph/project-graph.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/project-graph/file-utils.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/utils/package-manager.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/utils/package-json.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/utils/print-help.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/command-line/run/run.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/bin/run-executor.js
Pass --verbose to see the stacktrace.

 NX   Running target build for project remote failed

Failed tasks:

- remote:build:production
```

So it looks like it's just missing  '@nx/module-federation/rspack' package, so I triied to install it, but that didn't work. Realiized I need just @nx/module-federation so installed that, and now it works.

So I think the generators need to be updated to install this package.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 22.11.0
OS             : darwin-x64
Native Target  : x86_64-macos
pnpm           : 8.10.2

nx                 : 20.2.1
@nx/js             : 20.2.1
@nx/jest           : 20.2.1
@nx/eslint         : 20.2.1
@nx/workspace      : 20.2.1
@nx/devkit         : 20.2.1
@nx/eslint-plugin  : 20.2.1
@nx/react          : 20.2.1
@nx/rspack         : 20.2.1
@nx/web            : 20.2.1
typescript         : 5.6.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
@nx/module-federation : 20.2.1
```

### Failure Logs

```shell
NX   Cannot find module '@nx/module-federation/rspack'

Require stack:
- /Volumes/Code/react-monorepo/remote/rspack.config.ts
- /Volumes/Code/react-monorepo/remote/rspack.config.prod.ts
- /Volumes/Code/react-monorepo/node_modules/.pnpm/@nx+rspack@20.2.1_@module-federation+enhanced@0.7.6_@module-federation+node@2.6.11_@swc-node+_vvolop54a2iqvroiphed6tvd2q/node_modules/@nx/rspack/src/utils/resolve-user-defined-rspack-config.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/@nx+rspack@20.2.1_@module-federation+enhanced@0.7.6_@module-federation+node@2.6.11_@swc-node+_vvolop54a2iqvroiphed6tvd2q/node_modules/@nx/rspack/src/executors/rspack/lib/config.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/@nx+rspack@20.2.1_@module-federation+enhanced@0.7.6_@module-federation+node@2.6.11_@swc-node+_vvolop54a2iqvroiphed6tvd2q/node_modules/@nx/rspack/src/utils/create-compiler.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/@nx+rspack@20.2.1_@module-federation+enhanced@0.7.6_@module-federation+node@2.6.11_@swc-node+_vvolop54a2iqvroiphed6tvd2q/node_modules/@nx/rspack/src/executors/rspack/rspack.impl.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/config/schema-utils.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/command-line/run/executor-utils.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/devkit-internals.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/utils/assert-workspace-validity.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/project-graph/build-project-graph.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/project-graph/project-graph.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/project-graph/file-utils.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/utils/package-manager.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/utils/package-json.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/utils/print-help.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/src/command-line/run/run.js
- /Volumes/Code/react-monorepo/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.9.2_@swc+core@1.5.29/node_modules/nx/bin/run-executor.js
Pass --verbose to see the stacktrace.
```

### Package Manager Version

pnpm 8.10.2

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior
The `@nx/module-federation` package is a direct dependency of some of the other packages in the Nx Plugin ecosystem.
It should be resolved correctly by package managers such that it can be used when setting up MF projects.

However, some users are facing issues with module resolutions where the package is not found as expected.

## Expected Behavior
Install the package directly for the user to ensure module resolution works as expected.

## Related Issue(s)

Fixes #29269

### CODE REVIEW

File: packages/angular/src/migrations/update-20-2-0/migrate-with-mf-import-to-new-package.ts
Comment (leosvelperez) [inline packages/angular/src/migrations/update-20-2-0/migrate-with-mf-import-to-new-package.ts:1]: This is a change to an existing migration that wouldn't be run for users who are already past the target version of the migration. We should create a new one to ensure users who are already on 20.2.x get this change.

Comment (Coly010) [reply packages/angular/src/migrations/update-20-2-0/migrate-with-mf-import-to-new-package.ts:1]: Updated to add new migration

File: packages/rspack/migrations.json [hunk 1]
```diff
@@ -5,6 +5,12 @@
       "version": "20.2.0-beta.3",
       "description": "Update the withModuleFederation import use @nx/module-federation/rspack.",
       "factory": "./src/migrations/update-20-2-0/migrate-with-mf-import-to-new-package"
+    },
+    "ensure-nx-module-federation-package": {
```
Comment (jaysoo) [inline packages/rspack/migrations.json:9]: This is technically already handled by Angular and React plugins right? Is there a scenario where those aren't installed by Rspack is?

Comment (Coly010) [reply packages/rspack/migrations.json:9]: Each plugin is finding its own set of `module-federation-dev-server` executors to determine if MF projects exists. 

I could combine the rspack ones into the react one, i just had them separated based on location of the executor

**Review by leosvelperez — APPROVED** [review]

**Review by jaysoo — APPROVED** [review]
