### PR TITLE
Don't leak file descriptor in shared.ts/mtime. Fixes #403

### LINKED ISSUE #403: TSLint nx-enforce-module-boundaries rule leaks file handles via mtime function
[Here](https://github.com/nrwl/nx/blob/master/packages/schematics/src/command-line/shared.ts#L213) a file descriptor is opened, but not closed.

Originally reported in the WebStorm issue tracker as [WEB-32078](https://youtrack.jetbrains.com/issue/WEB-32078) when using TSLint with WebStorm.

This is a problem on Windows where it blocks users from saving files.
A project to reproduce the issue in the IDE is attached [here](https://youtrack.jetbrains.com/issue/WEB-32078#comment=27-2802393).

If you wanted a standalone repro, you could write a simple console app that invokes [`lastModifiedAmongProjectFiles`](https://github.com/nrwl/nx/blob/master/packages/schematics/src/command-line/shared.ts#L182), break in the debugger after the function completes, and inspect the process handles using `procexp` or `handle.exe`.

### PR DESCRIPTION
**Pull request by undeadcat**
Fixes #403

### CODE REVIEW

File: packages/schematics/src/command-line/shared.ts [hunk 1]
```diff
@@ -211,7 +211,12 @@ function recursiveMtime(dirName: string) {
 }
 
 function mtime(f: string): number {
-  return fs.fstatSync(fs.openSync(f, 'r')).mtime.getTime();
+  let fd = fs.openSync(f, 'r');
```
Comment (skydever) [inline packages/schematics/src/command-line/shared.ts]: did some tests, had some file lock issues too in vscode that are gone now (e.g. couldn't revert) 👍

... to be lint friendly, this should be:
```javascript
const fd = fs.openSync(f, 'r');
```

**Comment by vsavkin** [comment]
Thank you!
