### PR TITLE
fix(core): disallow `Vitest & Angular` unit test runner when bundler is not `esbuild` in cnw

### LINKED ISSUE #34014: Unable to create workspace with Vitest & Angular unit test runner
### Current Behavior

Fails to create workspace.

### Expected Behavior

Workspace created with Vitest & Angular as the unit test runner.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Run `npx create-nx-workspace@latest` (currently evaluating as v22.3.3)
2. Select `Custom` when prompted for `Which starter do you want to use?`
3. Select `Angular` when prompted for `Which stack do you want to use?`
4. Select `Vitest & Angular` when prompted for `Which unit test runner would you like to use?`

### Nx Report

```shell
Node           : 24.12.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 11.6.2

nx (global)            : 22.3.3
nx                     : 22.3.3
@nx/js                 : 22.3.3
@nx/eslint             : 22.3.3
@nx/workspace          : 22.3.3
@nx/angular            : 22.3.3
@nx/devkit             : 22.3.3
@nx/module-federation  : 22.3.3
@nx/rspack             : 22.3.3
@nx/web                : 22.3.3
@nx/webpack            : 22.3.3
typescript             : 5.9.3
---------------------------------------
Cache Usage: 0.00 B / 92.64 GB
```

### Failure Logs

```shell
npx create-nx-workspace@latest

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · org
✔ Which starter do you want to use? · custom
✔ Which stack do you want to use? · angular
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · org
✔ Which bundler would you like to use? · rspack
✔ Default stylesheet format · scss
✔ Do you want to enable Server-Side Rendering (SSR)? · Yes
✔ Which unit test runner would you like to use? · vitest-angular
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Try the full Nx platform? · yes

 NX   Creating your v22.3.3 workspace.

✔ Installing dependencies with npm
✖ Creating your workspace in org

 NX   Failed to create workspace

Failed to create a workspace: npm warn deprecated keygrip@1.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated whatwg-encoding@2.0.0: Use @exodus/bytes instead for a more spec-conformant and faster implementation
```

### Package Manager Version

_No response_

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Similar issue: https://github.com/nrwl/nx/issues/33602

### PR DESCRIPTION
**Pull request by leosvelperez**
## Current Behavior

The `create-nx-workspace` incorrectly offers `Vitest & Angular` as a valid unit test runner choice when the bundler is something other than `esbuild`.

## Expected Behavior

The `create-nx-workspace` should only offer `Vitest & Angular` as a valid unit test runner choice when the bundler is `esbuild`.

## Related Issue(s)

Fixes #34014

### CODE REVIEW

File: packages/create-nx-workspace/bin/create-nx-workspace.ts [hunk 1]
```diff
@@ -1294,11 +1294,13 @@ async function determineAngularOptions(
...
-              message:
-                'Vitest & Angular [ https://vitest.dev/ & https://angular.dev ]',
-            },
+            bundler === 'esbuild'
+              ? {
+                  name: 'vitest-angular',
+                  message:
+                    'Vitest & Angular [ https://vitest.dev/ & https://angular.dev ]',
+                }
+              : null,
```
Comment (AgentEnder) [inline packages/create-nx-workspace/bin/create-nx-workspace.ts]:
```suggestion
            ...(bundler === 'esbuild'
              ? [{
                  name: 'vitest-angular',
                  message:
                    'Vitest & Angular [ https://vitest.dev/ & https://angular.dev ]',
                }]
              : [],)
```

File: packages/create-nx-workspace/bin/create-nx-workspace.ts [hunk 2]
```diff
@@ -1312,7 +1314,7 @@ async function determineAngularOptions(
               name: 'none',
               message: 'None',
             },
-          ],
+          ].filter(Boolean) as Array<{ name: string; message: string }>,
```
Comment (AgentEnder) [inline packages/create-nx-workspace/bin/create-nx-workspace.ts]:
```suggestion
```

**Review by AgentEnder — APPROVED** [review]
Left a suggestion, but its a nit. I think its a bit nicer, but realistically it doesn't matter. Up to you 🤷‍♂️
