### PR TITLE
fix(core): ensure correct package name matching when parsing pnpm lock file

### LINKED ISSUE #17492: Broken generated pnpm lock file (ERR_PNPM_ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY)
### Current Behavior

I'm using `@nx/webpack:webpack` executor with `"generatePackageJson": true`.

When I'm building production build of app and deploying it I'm getting following error:

```
Lockfile is up to date, resolution step is skipped
 WARN  Broken lockfile: no entry for '/strip-ansi/6.0.1' in pnpm-lock.yaml
 ERR_PNPM_ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  The lockfile is broken! Resolution step will be performed to fix it.
```

### Expected Behavior

lock file shoud be correct and there should be no error.

### GitHub Repo

https://github.com/diginikkari/nx-next

### Steps to Reproduce

1. add app with webpack plugin `pnpm nx g @nx/react:app my-app --bundler=webpack`
2. enable 'generatePackageJson' in ´project.json´
3. install `glob` as dev dependency `pnpm install -d glob@10.2.6` (this will add `string-width@5.1.2` dependency)
4. install `msw` as dependency `pnpm install msw` (this will add `string-width@4.2.3` dependency)
5. add `import { rest } from 'msw';` to app to include msw as dependency for app
6. build app `pnpm nx run my-app:build:production`
7. copy generated `dist` folder to outside of workspace and run 'pnpm install' inside it.

### Nx Report

```shell
Node   : 20.2.0
   OS     : darwin-arm64
   pnpm   : 8.6.1
   
   nx                 : 16.4.0-beta.2
   @nx/js             : 16.4.0-beta.2
   @nx/jest           : 16.4.0-beta.2
   @nx/linter         : 16.4.0-beta.2
   @nx/workspace      : 16.4.0-beta.2
   @nx/cypress        : 16.4.0-beta.2
   @nx/devkit         : 16.4.0-beta.2
   @nx/esbuild        : 16.4.0-beta.2
   @nx/eslint-plugin  : 16.4.0-beta.2
   @nx/next           : 16.4.0-beta.2
   @nx/node           : 16.4.0-beta.2
   @nx/react          : 16.4.0-beta.2
   @nx/storybook      : 16.4.0-beta.2
   @nrwl/tao          : 16.4.0-beta.2
   @nx/vite           : 16.4.0-beta.2
   @nx/web            : 16.4.0-beta.2
   @nx/webpack        : 16.4.0-beta.2
   nx-cloud           : 16.0.5
   typescript         : 5.1.3
   ---------------------------------------
   Community plugins:
   @mands/nx-playwright : 0.6.2
   ---------------------------------------
```

### Failure Logs

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I tried it with `16.3.2` and with latest beta `16.4.0-beta.2`.

Lockfile generation seems to select `/string-width@5.1.2` entry into the generated lock file even though there is only `string-width: 4.2.3` dependency in app's dependencies.

### PR DESCRIPTION
**Pull request by meeroslav**
## Current Behavior
Package name matcher in the `pnpm-parser` will match key to alias name if found, and ignore the potential full name match.

```yaml
  # ...
  /@isaacs/cliui@8.0.2:
    dependencies:
      string-width: 5.1.2
      string-width-cjs: /string-width@4.2.3 # alias for string-width: 4.2.3  

  /cli-table3@0.6.3:
    dependencies:
      string-width: 4.2.3   
   # ...
 
  /string-width@4.2.3:
     # ...

  /string-width@5.1.2:
     # ...
 # ...
```

The above yaml would match 2 packages:
- string-width @ 5.1.2
- string-width-cjs @ 4.2.3
While skipping the:
- string-width @ 4.2.3

## Expected Behavior
If same package version is used in the original form and as an alias, both variants should be saved to graph, so that we can track them when finding dependency subgraph and pruning.

## Related Issue(s)

Fixes #17492

### CODE REVIEW

File: packages/nx/src/plugins/js/lock-file/pnpm-parser.ts [hunk 1]
```diff
@@ -18,7 +18,7 @@ import {
   ProjectGraph,
   ProjectGraphExternalNode,
 } from '../../../config/project-graph';
-import { fileHasher, hashArray } from '../../../hasher/file-hasher';
```
Comment (meeroslav) [inline packages/nx/src/plugins/js/lock-file/pnpm-parser.ts:21]: Unused import

File: packages/nx/src/plugins/js/lock-file/pnpm-parser.ts [hunk 2]
```diff
@@ -43,39 +43,40 @@ function addNodes(
   const nodes: Map<string, Map<string, ProjectGraphExternalNode>> = new Map();
 
   Object.entries(data.packages).forEach(([key, snapshot]) => {
-    const packageName = findPackageName(key, snapshot, data);
```
Comment (meeroslav) [inline packages/nx/src/plugins/js/lock-file/pnpm-parser.ts:46]: Instead of single value we return an array

File: packages/nx/src/plugins/js/lock-file/pnpm-parser.ts [hunk 3]
```diff
@@ -307,25 +318,28 @@ function findPackageName(
...
   for (let i = 0; i < snapshots.length; i++) {
     const dependencyName = matchedDependencyName(snapshots[i]);
     if (dependencyName) {
-      return dependencyName;
+      packageNames.add(dependencyName);
     }
   }
-  return extractNameFromKey(key);
+  if (packageNames.size === 0) {
+    packageNames.add(originalPackageName);
```
Comment (meeroslav) [inline packages/nx/src/plugins/js/lock-file/pnpm-parser.ts:340]: Package can be overridden in the version meta which we don't parse at the moment (version 5.x has this info hashed) so we add this explicitly if not found otherwise:

The following line says that despite dependency is typescript@4.8.2 we will use 4.8.4 so that would end up being the only installed version:
```
  /@phenomnomnominal/tsquery@4.1.1(typescript@4.8.4):
    resolution: {integrity: sha512-jjMmK1tnZbm1Jq5a7fBliM4gQwjxMU7TFoRNwIyzwlO+eHPRCFv/Nv+H/Gi1jc3WR7QURG8D5d0Tn12YGrUqBQ==}
    peerDependencies:
      typescript: ^3 || ^4
    dependencies:
      esquery: 1.5.0
      typescript: 4.8.2
```

**Review by FrozenPandaz — APPROVED** [review]
