### PR TITLE
fix(core): improve db connection initialization and error messages

### LINKED ISSUE #28640: Unable to set journal_mode: SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file"))
### Current Behavior

nx fails to run on my self-hosted github runners when trying to upgrade from 20.0.3 to 20.0.5 with the error in $SUBJECT. No additional information is printed into the console. Any nx command seems to trigger that, such as `nx run-many --target build`.

### Expected Behavior

Nx works, or at least prints a more useful message (eg. path to the database it's trying to access).

### GitHub Repo

_No response_

### Steps to Reproduce

It's a private repository, but I can try to reproduce if you think it'd help. I very much suspect it only affects certain type of self-hosted github runners, as the new version works on my local machine (macOS).

### Nx Report

```
Node           : 20.15.1
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 9.6.0

nx                 : 20.0.5
@nx/js             : 20.0.5
@nx/eslint         : 20.0.5
@nx/workspace      : 20.0.5
@nx/devkit         : 20.0.5
@nx/esbuild        : 20.0.5
@nx/eslint-plugin  : 20.0.5
@nx/next           : 20.0.5
@nx/react          : 20.0.5
@nx/web            : 20.0.5
@nx/webpack        : 20.0.5
typescript         : 5.6.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/next/plugin
```

### Failure Logs

Run npx nx run-many --target build

 NX   Unable to set journal_mode: SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file"))

Pass --verbose to see the stacktrace.

Error: Process completed with exit code 1.

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### LINKED ISSUE #30856: running project targets fail with a crashed daemon (SQLite "locking protocol")
### Current Behavior

Running any project target (ex  `nx serve <app>`) command  fails with a crashed daemon (when calculating the project graph). The logs contain an SQLite error as described below. This can be resolved by NX_DISABLE_DB=true.

I'm running WSL on windows 10; I haven't previously tried to use NX in the context. I tried cloning both in to the Linux filesystem and the windows filesystem with no difference. I tried `nx reset`. I get the same result on another machine running Windows 11/WSL.

### Expected Behavior

Commands run without crashing/disabling the DB

### GitHub Repo

https://github.com/thunder033/wayfinder

### Steps to Reproduce

1. clone repo
2. npm i
3. run a project target (ex `nx test wf-core`)

### Nx Report

```shell
Node           : 22.14.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.9.2

nx (global)            : 20.8.0
nx                     : 20.8.0
@nx/js                 : 20.8.0
@nx/eslint             : 20.8.0
@nx/workspace          : 20.8.0
@nx/angular            : 20.8.0
@nx/devkit             : 20.8.0
@nx/eslint-plugin      : 20.8.0
@nx/module-federation  : 20.8.0
@nx/rspack             : 20.8.0
@nx/vite               : 20.8.0
@nx/web                : 20.8.0
@nx/webpack            : 20.8.0
typescript             : 5.8.3
---------------------------------------
Community plugins:
@analogjs/vite-plugin-angular : 1.14.1
@analogjs/vitest-angular      : 1.14.1
@ngrx/store                   : 19.1.0
---------------------------------------
Cache Usage: 0.00 B / 97.76 GB
```

### Failure Logs

```shell
[NX v20.8.0 Daemon Server] - 2025-04-24T16:01:25.287Z - Started listening on: /tmp/bd29d515796152e2f914/d.sock
[NX v20.8.0 Daemon Server] - 2025-04-24T16:01:25.291Z - [WATCHER]: Subscribed to changes within: /home/thundercracker/wsl-project/wayfinder (native)
[NX v20.8.0 Daemon Server] - 2025-04-24T16:01:25.304Z - Established a connection. Number of open connections: 1
[NX v20.8.0 Daemon Server] - 2025-04-24T16:01:25.308Z - Established a connection. Number of open connections: 2
[NX v20.8.0 Daemon Server] - 2025-04-24T16:01:25.312Z - Closed a connection. Number of open connections: 1
[NX v20.8.0 Daemon Server] - 2025-04-24T16:01:25.317Z - [REQUEST]: Responding to the client. Shutdown initiated
[NX v20.8.0 Daemon Server] - 2025-04-24T16:01:25.317Z - Done responding to the client Shutdown initiated
[NX v20.8.0 Daemon Server] - 2025-04-24T16:01:25.318Z - Handled FORCE_SHUTDOWN. Handling time: 0. Response time: 2.
[NX v20.8.0 Daemon Server] - 2025-04-24T16:01:25.320Z - Closed a connection. Number of open connections: 0
[NX v20.8.0 Daemon Server] - 2025-04-24T16:01:25.325Z - [WATCHER]: Stopping the watcher for /home/thundercracker/wsl-project/wayfinder (sources)
[NX v20.8.0 Daemon Server] - 2025-04-24T16:01:25.327Z - [WATCHER]: Stopping the watcher for /home/thundercracker/wsl-project/wayfinder (outputs)
[NX v20.8.0 Daemon Server] - 2025-04-24T16:01:25.328Z - Server stopped because: "Request to shutdown"
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:07.785Z - Started listening on: /tmp/bd29d515796152e2f914/d.sock
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:07.790Z - [WATCHER]: Subscribed to changes within: /home/thundercracker/wsl-project/wayfinder (native)
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:07.796Z - Established a connection. Number of open connections: 1
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:07.797Z - Established a connection. Number of open connections: 2
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:07.799Z - Closed a connection. Number of open connections: 1
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:07.805Z - [REQUEST]: Client Request for Project Graph Received
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:07.869Z - Time taken for 'loadSpecifiedNxPlugins' 2.5061000000000035ms
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.366Z - Time taken for 'Load Nx Plugin: /home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/plugins/package-json' 558.0163ms
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.425Z - Time taken for 'Load Nx Plugin: /home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/plugins/project-json/build-nodes/project-json' 616.6799ms
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.457Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.458Z - [REQUEST]:
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.458Z - [REQUEST]:
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.470Z - Time taken for 'loadDefaultNxPlugins' 649.4702ms
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.578Z - Time taken for 'build-project-configs' 60.344100000000026ms
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.744Z - [SYNC]: collect registered sync generators
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.746Z - [REQUEST]: Responding to the client. project-graph
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.759Z - Done responding to the client project-graph
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.759Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 941. Response time: 13.
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.759Z - Time taken for 'total for creating and serializing project graph' 940.9917ms
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.787Z - [REQUEST]: Responding to the client. handleRunPreTasksExecution
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.787Z - Done responding to the client handleRunPreTasksExecution
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.787Z - Handled PRE_TASKS_EXECUTION. Handling time: 1. Response time: 0.
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:08.788Z - Time taken for 'preTasksExecution' 1.0588000000000193ms
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:09.046Z - [REQUEST]: Responding to the client. handleHashTasks
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:09.177Z - Done responding to the client handleHashTasks
[NX v20.8.0 Daemon Server] - 2025-04-24T16:02:09.177Z - Handled HASH_TASKS. Handling time: 22. Response time: 131.
/home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/utils/db-connection.js:12
    const connection = getEntryOrSet(dbConnectionMap, key, () => (0, native_1.connectToNxDb)(opts.directory, package_json_1.version, opts.dbName));
                                                                                            ^

Error: Unable to set journal_mode: DB pragma update error: SqliteFailure(Error { code: FileLockingProtocolFailed, extended_code: 15 }, Some("locking protocol"))
    at /home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/utils/db-connection.js:12:93
    at getEntryOrSet (/home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/utils/db-connection.js:26:17)
    at getDbConnection (/home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/utils/db-connection.js:12:24)
    at new TaskHistory (/home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/utils/task-history.js:11:91)
    at getTaskHistory (/home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/utils/task-history.js:48:23)
    at handleGetEstimatedTaskTimings (/home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/daemon/server/handle-task-history.js:24:59)
    at /home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/daemon/server/server.js:154:141
    at handleResult (/home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/daemon/server/server.js:186:22)
    at handleMessage (/home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/daemon/server/server.js:154:15)
    at /home/thundercracker/wsl-project/wayfinder/node_modules/nx/src/daemon/server/server.js:74:15 {
  code: 'GenericFailure'
}

Node.js v22.14.0
```

### Package Manager Version

npm 10.8.3

### Operating System

- [ ] macOS
- [x] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leosvelperez**
## Summary

Improved database initialization with better error handling, automatic recovery from stale files, and cache preservation during error recovery.

### 1. Iterative Retry Logic with Explicit State

Converted initialization from recursive calls to an iterative loop with a state flag (`cleaned_up_stale_files`) that limits retries to 2 attempts. This makes retry conditions explicit and self-documenting while preventing potential stack overflow.

### 2. Complete Auxiliary File Cleanup

Now removes all SQLite database files during cleanup (`.db`, `.db-wal`, `.db-shm`) instead of just the main `.db` file. This prevents stale Write-Ahead Logging auxiliary files from causing initialization failures after version upgrades.

### 3. Smart Compatible Database Handling

Compatible databases (matching version) are now reconfigured based on their current journal mode:

- **DELETE mode**: Attempts opportunistic upgrade to WAL for better performance, cleans up any orphaned WAL files from previous runs
- **WAL mode**: Verifies WAL still works; if it fails, removes only auxiliary files (preserving cache), retries, and falls back to DELETE mode if still failing
- **Unknown/query failed**: Full reconfiguration with complete cleanup on failure

This preserves cached build outputs when possible while recovering from stale file issues automatically.

### 4. WSL1 Proactive Detection

Detects WSL1 environments by reading `/proc/version` and automatically uses DELETE journal mode instead of attempting WAL (which WSL1 doesn't support), preventing initialization failures.

### 5. Enhanced Error Messages

Replaced generic error messages with context-specific, platform-agnostic guidance:

- Permission errors: Explains how to check file/directory permissions and ownership without platform-specific commands
- Disk full: Suggests freeing space or moving workspace
- Missing directories: Explains unexpected condition with troubleshooting steps
- All errors: Include debug instructions (`NX_NATIVE_LOGGING=trace`) and reporting link

Error messages work consistently across Windows, macOS, and Linux without suggesting commands that may not be available on the user's platform.

### 6. Code Quality Improvements

Extracted helper functions to reduce duplication:

- `query_journal_mode()` - Query database's current journal mode
- `set_busy_handler()` - Configure connection-level busy handler
- `remove_wal_files()` - Remove only WAL auxiliary files
- `remove_all_database_files()` - Complete database cleanup
- `create_io_error()` / `create_db_error()` - Generate helpful error messages

### Stale WAL Files After Version Upgrades

Leftover `.db-wal` and `.db-shm` files from previous versions no longer cause initialization to fail. These files are now cleaned up automatically during initialization.

### Cache Loss on Recoverable Errors

When WAL mode issues occur on otherwise healthy databases, only auxiliary files are removed, preserving the main database and all cached build outputs. Full wipes only happen for genuine corruption or version mismatches.

### WSL1 Compatibility

WSL1 environments now work without initialization failures by proactively detecting the environment and using DELETE mode instead of attempting WAL.

### Performance Optimization

Databases in DELETE mode automatically attempt upgrading to WAL when the environment supports it (e.g., after moving workspace from network drive to local disk), providing better performance without manual intervention.

### Poor Debugging Experience

Error messages now provide specific, actionable guidance based on the error type, helping users resolve issues without needing to ask for help.

## Impact

- ✅ Users no longer need manual `nx reset` for stale file issues
- ✅ Cache and build outputs preserved during error recovery
- ✅ WSL1 works out of the box
- ✅ Automatic performance improvements when environment changes
- ✅ Better error messages reduce support burden

## Related Issue(s)

Fixes #28640 
Fixes #30856
Fixes #32894

### CODE REVIEW

File: packages/nx/src/native/db/initialize.rs [hunk 1]
```diff
@@ -18,73 +19,374 @@ pub(super) fn unlock_file(lock_file: &LockFile) {
...
+                )
+            } else {
+                "The specified path does not exist or is inaccessible.\n\
+                \n\
+                Possible solutions:\n\
+                - Verify the workspace directory exists\n\
+                - Check that the path is not on a removed or unmounted drive"
+                    .to_string()
+            }
+        }
```
Comment (AgentEnder) [inline packages/nx/src/native/db/initialize.rs]: For these in particular does it maybe make more sense to just tell the user they likely should create an issue? It seems like a low chance they would have messed something up for the rust code to throw NotFound, and the current suggestions seem unlikely.

File: packages/nx/src/native/db/initialize.rs [hunk 2]
```diff
@@ -18,73 +19,374 @@ pub(super) fn unlock_file(lock_file: &LockFile) {
...
+                                set_busy_handler(&c, db_path)?;
+
+                                return Ok(c);
+                            }
+                            Some(mode) if mode.eq_ignore_ascii_case("WAL") => {
+                                trace!("Database already configured with WAL journal mode");
+                                trace!("Verifying WAL mode still works");
+
+                                // Verify WAL mode works
+                                match c.pragma_update(None, "journal_mode", "WAL") {
```
Comment (AgentEnder) [inline packages/nx/src/native/db/initialize.rs:211]: I'm a bit wishy-washy on this part, we'll chat over a call and look at it.

File: packages/nx/src/native/db/initialize.rs (hunk 1 above)
Comment (leosvelperez) [reply packages/nx/src/native/db/initialize.rs]: Yeah, 100%. I actually thought I had removed these 🤦🏻

**Review by FrozenPandaz — APPROVED** [review]
