### PR TITLE
fix(core): retry more db operations

### LINKED ISSUE #28608: Running multible instances of nx throw database locked error
### Current Behavior

If i run mutlible instances of nx in parallel on the same workspace some of them failing with the following error:

```console
 NX   DB execute error: "INSERT OR REPLACE INTO task_details  (hash, project, target, configuration)
 
                     VALUES (?1, ?2, ?3, ?4)", SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
 Error: DB execute error: "INSERT OR REPLACE INTO task_details  (hash, project, target, configuration)
                     VALUES (?1, ?2, ?3, ?4)", SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
     at hashTasksThatDoNotDependOnOutputsOfOtherTasks (/build/node_modules/nx/src/hasher/hash-task.js:46:22)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async invokeTasksRunner (/build/node_modules/nx/src/tasks-runner/run-command.js:373:5)
     at async runCommandForTasks (/build/node_modules/nx/src/tasks-runner/run-command.js:117:25)
     at async /build/node_modules/nx/src/tasks-runner/run-command.js:105:29
     at async handleErrors (/build/node_modules/nx/src/utils/handle-errors.js:9:24)
     at async runCommand (/build/node_modules/nx/src/tasks-runner/run-command.js:104:20)
     at async Object.runMany (/build/node_modules/nx/src/command-line/run-many/run-many.js:43:24)
     at async /build/node_modules/nx/src/command-line/run-many/command-object.js:13:13
     at async handleErrors (/build/node_modules/nx/src/utils/handle-errors.js:9:24)
```
This happens since the update to nx 20.x
Im also tried out to disable the new caching with useLegacyCache=true in nx.json.
But getting the same error.

We using this to run cypress tests in parallel with cypress-split on the same CI node.

### Expected Behavior

It should be possible to run multiple instances nx on the same workspace.

### GitHub Repo

_No response_

### Steps to Reproduce

1. create a new workspace with mutlible projects
2. run to 2 nx instances:
   nx run-many -t lint
   nx run-many -t test

### Nx Report

NX   Report complete - copy this into the issue template

Node           : 18.20.3
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.7.0

nx (global)        : 20.0.5
nx                 : 20.0.5
@nx/js             : 20.0.5
@nx/jest           : 20.0.5
@nx/eslint         : 20.0.5
@nx/workspace      : 20.0.5
@nx/angular        : 20.0.5
@nx/cypress        : 20.0.5
@nx/devkit         : 20.0.5
@nrwl/devkit       : 16.5.1
@nx/eslint-plugin  : 20.0.5
@nx/plugin         : 20.0.5
@nrwl/tao          : 16.5.1
@nx/web            : 20.0.5
@nx/webpack        : 20.0.5
typescript         : 5.1.6
---------------------------------------
Community plugins:
@jsverse/transloco   : 7.5.0
@ngrx/effects        : 16.3.0
@ngrx/eslint-plugin  : 16.3.0
@ngrx/router-store   : 16.3.0
@ngrx/schematics     : 16.3.0
@ngrx/store          : 16.3.0
@ngrx/store-devtools : 16.3.0
nx-stylelint         : 17.1.6
---------------------------------------
Local workspace plugins:
         @app/workspace-plugin
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/devkit@16.5.1
  - @nrwl/tao@16.5.1

To fix this, run `nx migrate nx@20.0.5`

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### LINKED ISSUE #28665: SqliteFailure Error "DatabaseBusy" running `nx run-many --target build`
### Current Behavior

After upgrading from Nx "18.3.5" to "20.0.6", my Jenkins build (running in docker on linux) started to fail running `nx run-many --target build` with a Sqlite **DatabaseBusy** error:

`Unable to set journal_mode: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))`

More specifically, the Jenkins build runs 3 commands in a row, the 3rd being `nx run-many --target build` which fails.

NOTE: I have `"useLegacyCache": true` in my "nx.conf" file, if that matters.

### Expected Behavior

I expect it to work the way Nx 18.3.5 worked, i.e. no error from  `nx run-many --target build`, 

### GitHub Repo

_No response_

### Steps to Reproduce

I have a docker instance with Jenkins, runs runs 3 tasks in a row... the last task `npx nx run-many -t build` gives the Sqlite error.

```
npx nx show projects --type lib --affected --base=6541ce36aee67873fcf457302a367368aed8678e --head=HEAD
npx nx release patch --skip-publish --projects=project-one,project-two,project-three,project-four,project-five,project-six
npx nx run-many -t build --configuration=production --projects=project-one,project-two,project-three,project-four,project-five,project-six
```
The first 2 commands works, the last gives:
```
Error: Unable to set journal_mode: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
10:12:36      at /jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:11:93
10:12:36      at getEntryOrSet (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:19:17)
10:12:36      at getDbConnection (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:11:24)
10:12:36      at getTaskDetails (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/hasher/hash-task.js:19:84)
10:12:36      at invokeTasksRunner (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:367:56)
10:12:36      at runCommandForTasks (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:117:31)
10:12:36      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:12:36      at async /jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:105:29
10:12:36      at async handleErrors (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/handle-errors.js:9:24)
10:12:36      at async runCommand (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:104:20)
```

### Nx Report

Node           : 18.19.0
10:26:42  OS             : linux-x64
10:26:42  Native Target  : x86_64-linux
10:26:42  npm            : 10.2.3
10:26:42  
10:26:42  nx                 : 20.0.6
10:26:42  @nx/js             : 20.0.6
10:26:42  @nx/jest           : 20.0.6
10:26:42  @nx/eslint         : 20.0.6
10:26:42  @nx/workspace      : 20.0.6
10:26:42  @nx/angular        : 20.0.6
10:26:42  @nx/devkit         : 20.0.6
10:26:42  @nx/eslint-plugin  : 20.0.6
10:26:42  @nx/web            : 20.0.6
10:26:42  @nx/webpack        : 20.0.6
10:26:42  typescript         : 5.4.5

### Failure Logs

Error: Unable to set journal_mode: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
10:12:36      at /jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:11:93
10:12:36      at getEntryOrSet (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:19:17)
10:12:36      at getDbConnection (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:11:24)
10:12:36      at getTaskDetails (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/hasher/hash-task.js:19:84)
10:12:36      at invokeTasksRunner (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:367:56)
10:12:36      at runCommandForTasks (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:117:31)
10:12:36      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:12:36      at async /jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:105:29
10:12:36      at async handleErrors (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/handle-errors.js:9:24)
10:12:36      at async runCommand (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:104:20)

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Cammisuli**
- Introduce new `transaction` and `pragma_update` methods in `NxDbConnection`
- Refactor `initialize_db` to handle new conditions
- Update `record_task_details` to use transactions
- Add unit tests for `initialize_db`

## Related Issue(s)

Fixes #

### CODE REVIEW

File: packages/nx/src/native/db/connection.rs [hunk 1]
```diff
@@ -1,40 +1,103 @@
...
+macro_rules! retry_db_operation_when_busy {
+    ($operation:expr) => {{
+        let connection = 'retry: {
+            for i in 0..MAX_RETRIES {
+                match $operation {
+                    r @ Ok(_) => break 'retry r,
+                    Err(Error::SqliteFailure(err, _))
+                        if err.code == rusqlite::ErrorCode::DatabaseBusy =>
+                    {
+                        trace!("Database busy. Retrying{}", ".".repeat(i as usize));
```
Comment (JamesHenry) [inline packages/nx/src/native/db/connection.rs:29]: Can we include the number of attempts and attempts remaining?

File: packages/nx/src/native/db/initialize.rs [hunk 2]
```diff
@@ -129,16 +125,83 @@ fn open_database_connection(db_path: &PathBuf) -> anyhow::Result<NxDbConnection>
...
     connection
-        .conn
-        .busy_handler(Some(|tries| tries < 6))
+        .busy_handler(Some(|tries| tries <= 12))
         .map_err(|e| anyhow::anyhow!("Unable to set busy handler: {:?}", e))?;
     Ok(())
 }
+
+#[cfg(test)]
+mod tests {
```
Comment (JamesHenry) [inline packages/nx/src/native/db/initialize.rs:140]: Shall we cover some important handled error cases?

File: packages/nx/src/native/tasks/task_history.rs [hunk 3]
```diff
@@ -54,24 +55,26 @@ impl NxTaskHistory {
...
-        }
+    pub fn record_task_runs(&mut self, task_runs: Vec<TaskRun>) -> anyhow::Result<()> {
+        trace!("Recording task runs");
+        self.db.transaction(|conn| {
+            let mut stmt = conn.prepare(
+                "INSERT OR REPLACE INTO task_history
+        (hash, status, code, start, end)
+        VALUES (?1, ?2, ?3, ?4, ?5)",
+            )?;
+            for task_run in task_runs.iter() {
```
Comment (JamesHenry) [inline packages/nx/src/native/tasks/task_history.rs:66]: Pinged on slack

**Review by JamesHenry — CHANGES_REQUESTED** [review]
See comments

**Review by JamesHenry — APPROVED** [review]

**Review by JamesHenry — APPROVED** [review]
