### PR TITLE
fix(testing): warn and default if sourceRoot isn't set for ng CT

### LINKED ISSUE #13883: Your configFile is invalid [Cypress]
## Command I ran
nx component-test ng-app --verbose

## Cypress Config file Content

import { defineConfig } from 'cypress';
import { nxComponentTestingPreset } from '@nrwl/angular/plugins/component-testing';

export default defineConfig({
  component: nxComponentTestingPreset(__filename),
});

### Expected Behavior

Expected to be able to run the component test

### Github Repo

_No response_

### Steps to Reproduce

1.

### Nx Report

```shell
Node : 16.15.1
   OS   : darwin x64
   npm  : 9.1.2
   
   nx : 15.3.0-rc.0
   @nrwl/angular : 15.3.3
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : 15.3.3
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : 15.3.3
   @nrwl/next : Not Found
   @nrwl/node : 15.3.3
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.3
   @nrwl/web : 15.3.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ng-bootstrap/ng-bootstrap: 12.1.2
         @nguniversal/builders: 15.0.0
         @nguniversal/common: 15.0.0
         @nguniversal/express-engine: 15.0.0
         @nxext/stencil: 14.0.6
         ngx-spinner: 10.0.1
```

### Failure Logs

```shell
Your configFile is invalid: /Users/me/Developer/monorepo/apps/ng-app/cypress.config.ts

It threw an error when required, check the stack trace below:

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:1172:7)
    at joinPathFragments (/Users/me/Developer/packages/nx/src/utils/path.ts:18:29)
    at normalizeBuildTargetOptions (/Users/me/Developer/monorepo/packages/angular/plugins/component-testing.ts:238:34)
    at nxComponentTestingPreset (/Users/me/Developer/monorepo/packages/angular/plugins/component-testing.ts:94:34)
    at Object.<anonymous> (/Users/me/Developer/monorepo/apps/ng-app/cypress.config.ts:5:38)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/Users/me/Library/Caches/Cypress/11.2.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:857:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/me/Library/Caches/Cypress/11.2.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:859:16)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadFile (/Users/me/Library/Caches/Cypress/11.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:89:14)
    at EventEmitter.<anonymous> (/Users/me/Library/Caches/Cypress/11.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at process.<anonymous> (/Users/me/Library/Caches/Cypress/11.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:527:28)
    at process.emit (node:domain:475:12)
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by barbados-clemens**
## Current Behavior

when sourceRoot is missing in the project.json angular CT errors out trying to join the paths

## Expected Behavior

does not error or provides helpful error

## Related Issue(s)

Fixes #13883

### CODE REVIEW

File: packages/angular/plugins/component-testing.ts [hunk 1]
```diff
@@ -231,11 +231,20 @@ function normalizeBuildTargetOptions(
...
   }
-  const { root, sourceRoot } =
+
+  const config =
     buildContext.projectGraph.nodes[buildContext.projectName]?.data;
+
+  if (!config.sourceRoot) {
+    logger.warn(stripIndents`Unable to find the 'sourceRoot' in the project configuration.
+                 You should set the value in the ${buildContext.projectName} project configuration.
+                 Setting the value to the project root - '${config.root}/src'`);
```
Comment (Coly010) [inline packages/angular/plugins/component-testing.ts:241]: I'd maybe replace this with: `attempting with the following value: - config.root/src. (Note: this may fail, setting the correct sourceRoot value in project.json will ensure correctness)`

**Review by Coly010 — APPROVED** [review]
LGTM! I left a minor comment about the warning
