### PR TITLE
fix(core): fix lock file parsing issues

### LINKED ISSUE #13930: 15 Migration: TypeError: Cannot read properties of undefined (reading 'data')
### Current Behavior

Running `nx build` after migrating from 14.2.0 to 15.3.3 produces an error. 

TypeError: Cannot read properties of undefined (reading 'data')
    at C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\lock-file\\utils\\hashing.js:43:37
    at Array.forEach (<anonymous>)
    at traverseExternalNodesDependencies (C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\lock-file\\utils\\hashing.js:41:37)
    at hashExternalNode (C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\lock-file\\utils\\hashing.js:36:9)
    at C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\lock-file\\utils\\hashing.js:23:13
    at Array.forEach (<anonymous>)
    at hashExternalNodes (C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\lock-file\\utils\\hashing.js:20:45)
    at mapLockFileDataToPartialGraph (C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\lock-file\\lock-file.js:95:41)
    at C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\project-graph\\build-project-graph.js:61:78
    at Generator.next (<anonymous>)
  message: "Cannot read properties of undefined (reading 'data')

Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
If the error persists, please run "nx reset".

### Expected Behavior

The project builds without errors.

### Github Repo

_No response_

### Steps to Reproduce

I don't exactly know what causes this behavior. I got this after migrating from 14.2.0 to 15.3.3 using `nx migrate latest`.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : win32 x64
   npm  : 8.11.0

   nx : 15.3.3
   @nrwl/angular : 15.3.3
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.3
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nebular/theme: 9.0.3
         angular-auth-oidc-client: 14.1.4
         @storybook/angular: 6.5.12
```

### Failure Logs

_No response_

### Additional Information

Reverting to 15.2.4 resolves the issue. Deleting `node_modules` and reinstalling the packages did not.

As per #7606 more people experience this behavior lately.

### LINKED ISSUE #15019: Segfault generating `package.json`
### Current Behavior

I have found an issue when (trying) to upgrade to 15.7.0, but unfortunately I cannot create a reproduceable environment nor a testcase for it so I will try to describe it and hopefully a ring bells on your brilliant minds.

The usecase is that when I compile with a configuration such it generates the `package.json` it will fail with the stacktrace shown below.

### Expected Behavior

Generate `package.json` without any troubles.

### GitHub Repo

_No response_

### Steps to Reproduce

1.  Build a project with the `"generatePackageJson": true` and with a weird combination of dependencies

### Nx Report

```shell
Node : 16.19.0
   OS   : darwin x64
   yarn : 3.4.1
   
   nx                      : 15.7.0
   @nrwl/jest              : 15.7.0
   @nrwl/linter            : 15.7.0
   @nrwl/workspace         : 15.7.0
   @nrwl/cli               : 15.7.0
   @nrwl/cypress           : 15.7.0
   @nrwl/devkit            : 15.7.0
   @nrwl/eslint-plugin-nx  : 15.7.0
   @nrwl/js                : 15.7.0
   @nrwl/nest              : 15.7.0
   @nrwl/next              : 15.7.0
   @nrwl/node              : 15.7.0
   @nrwl/react             : 15.7.0
   @nrwl/rollup            : 15.7.0
   @nrwl/storybook         : 15.7.0
   @nrwl/tao               : 15.7.0
   @nrwl/web               : 15.7.0
   @nrwl/webpack           : 15.7.0
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.9.5
```

### Failure Logs

```shell
TypeError: Cannot read properties of undefined (reading 'data')
    at pathLengthToIncoming (<redacted>/node_modules/nx/src/lock-file/project-graph-pruning.js:128:37)
    at <redacted>/node_modules/nx/src/lock-file/project-graph-pruning.js:97:34
    at Array.forEach (<anonymous>)
    at <redacted>/node_modules/nx/src/lock-file/project-graph-pruning.js:96:25
    at Map.forEach (<anonymous>)
    at rehoistNodes (<redacted>/node_modules/nx/src/lock-file/project-graph-pruning.js:87:23)
    at pruneProjectGraph (<redacted>/node_modules/nx/src/lock-file/project-graph-pruning.js:17:5)
    at createLockFile (<redacted>/node_modules/nx/src/lock-file/lock-file.js:112:75)
    at <redacted>/node_modules/@nrwl/webpack/src/plugins/generate-package-json-plugin.js:43:131
    at fn (<redacted>/node_modules/webpack/lib/Compilation.js:478:10)
```

### Additional Information

@meeroslav Did a quite amazing job on https://github.com/nrwl/nx/pull/13864 revamping how the optimised `package.json` is calculated.

I have traced the issue to the `rehoistNodes` method where it `switchNodeToHoisted` some of the nodes correctly and then breaks on the `pathLengthToIncoming`. The reason for this is that it `reverse`s using the [reverse method](https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/operators.ts#L15C4-L48) but this uses caching to speedup computation. Unfortunatelly the [cache key is done with the graph](https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/operators.ts#L45) object and this graph is (to my understanding) changed with the `switchNodeToHoisted` but we never invalidate the cache. This leads to using wrong versions of the `invertertedGraph` that leads to discrepancies between the [inverted](https://github.com/nrwl/nx/blob/master/packages/nx/src/lock-file/project-graph-pruning.ts#L212) and the [actual graph](https://github.com/nrwl/nx/blob/master/packages/nx/src/lock-file/project-graph-pruning.ts#L215), thus leading to an segfault as per the stacktrace.

I can confirm that the core issue is on the caching because if I comment [this line](https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/operators.ts#L45) then everything works as expected. 

I see three solutions but I don't know which one is better, that's why I write it in here rather an a PR. These are:
1. Remove caching
2. Invalidate the cache when a `hoist` operation happens
3. Change the cache key to something else.

To undestand the 3rd option is good to understand why this is failing which, if my JS knowledge is correct, is because they key is now the 'reference' of the object and not its internal values. [Check this out on the console](https://codesandbox.io/s/js-playground-forked-pd5gcc?file=/src/index.js) to see what I mean. This basically means that we have a false positive cache hit mainly because we are not using a key that depends on its internal values. [Something like this could](https://stackoverflow.com/questions/5559712/how-to-reliably-hash-javascript-objects) be a solution. Actually I have tried using the proposed lib of `object-hash` and works as expected, but it seems that generating the hash is hitting performance worse than not using caching at all.

Hope this helps finding the issue despite not having a reproduceable environment!

### LINKED ISSUE #15031: Building NestJs app fails with error message "Loop detected while pruning."
### Current Behavior

Building (some of the) nestjs apps fails with this error message: `Loop detected while pruning. Please report this issue.`

### Expected Behavior

build should work

### GitHub Repo

_No response_

### Steps to Reproduce

running affected:build on our (closed source) project.

### Nx Report

```shell
Node : 16.18.0
   OS   : linux x64
   npm  : 8.19.2
   
   nx                      : 15.7.0
   @nrwl/jest              : 15.7.0
   @nrwl/linter            : 15.7.0
   @nrwl/workspace         : 15.7.0
   @nrwl/angular           : 15.7.0
   @nrwl/cli               : 15.7.0
   @nrwl/cypress           : 15.7.0
   @nrwl/devkit            : 15.7.0
   @nrwl/eslint-plugin-nx  : 15.7.0
   @nrwl/js                : 15.7.0
   @nrwl/nest              : 15.7.0
   @nrwl/node              : 15.7.0
   @nrwl/storybook         : 15.7.0
   @nrwl/tao               : 15.7.0
   @nrwl/webpack           : 15.7.0
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @ionic/angular               : 6.5.2
   @nestjs/ng-universal         : 6.1.0
   @ngrx/component-store        : 15.0.0
   @ngrx/effects                : 15.0.0
   @ngrx/entity                 : 15.0.0
   @ngrx/router-store           : 15.0.0
   @ngrx/store                  : 15.0.0
   @mands/nx-playwright         : 0.2.1
   @ngrx/schematics             : 15.0.0
   @ngrx/store-devtools         : 15.0.0
   @nguniversal/builders        : 15.1.0
   @nxext/capacitor             : 15.2.0
   @nxext/ionic-angular         : 15.1.0
   @storybook/angular           : 6.5.15
   @testing-library/angular     : 13.1.0
   @trumbitta/nx-plugin-openapi : 1.12.1
```

### Failure Logs

```shell
>  NX   Loop detected while pruning. Please report this issue.


HookWebpackError: Loop detected while pruning. Please report this issue.
    at makeWebpackError (/closed-source-project/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /closed-source-project/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/closed-source-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at fn (/closed-source-project/node_modules/webpack/lib/Compilation.js:480:17)
    at _next0 (eval at create (/closed-source-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/closed-source-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (/closed-source-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /closed-source-project/node_modules/webpack/lib/Compilation.js:502:10
    at Hook.eval [as callAsync] (eval at create (/closed-source-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/closed-source-project/node_modules/tapable/lib/Hook.js:18:14)
-- inner error --
Error: Loop detected while pruning. Please report this issue.
    at nestMappedPackages (/closed-source-project/node_modules/nx/src/lock-file/npm-parser.js:307:15)
    at nestMappedPackages (/closed-source-project/node_modules/nx/src/lock-file/npm-parser.js:310:9)
    at nestMappedPackages (/closed-source-project/node_modules/nx/src/lock-file/npm-parser.js:310:9)
    at mapSnapshots (/closed-source-project/node_modules/nx/src/lock-file/npm-parser.js:256:9)
    at stringifyNpmLockfile (/closed-source-project/node_modules/nx/src/lock-file/npm-parser.js:187:28)
    at createLockFile (/closed-source-project/node_modules/nx/src/lock-file/lock-file.js:123:54)
    at /closed-source-project/node_modules/@nrwl/webpack/src/plugins/generate-package-json-plugin.js:43:131
    at fn (/closed-source-project/node_modules/webpack/lib/Compilation.js:478:10)
    at _next0 (eval at create (/closed-source-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/closed-source-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
```

### Additional Information

_No response_

### LINKED ISSUE #15093: Loop detected while pruning.
### Current Behavior

Hi there,

I've migrated my NX workspace from NX `15.4.2` to `15.7.1` but I have some errors.

First, I was unable to run `npm i`without the `--legacy-per-deps` argument.

Then one of my project (An API made with nest) crashes on build or on serve command with the following message :
```
Loop detected while pruning. Please report this issue.
```

So, here I am reporting the issue ^^

I think this happens here with webpack : 
https://github.com/nrwl/nx/blob/8d0c09fffab5e22fcbc64d976ab870697721cbef/packages/nx/src/lock-file/npm-parser.ts#L530

If in my package json I set `@nrwl/webpack` to `15.4.2` instead of `15.7.1` the error disappears. 

### Expected Behavior

Everything should be up to date and able tu run as usual :)

### GitHub Repo

_No response_

### Steps to Reproduce

1. Have an NX `15.4.2` repo with a Nest app
2. Run `nx migrate latest` that bring my repo to `15.7.1`
3. Build or serve your nest app => Crash

### Nx Report

```shell
Node : 18.13.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx                      : 15.7.1
   @nrwl/jest              : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/angular           : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/cypress           : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/express           : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/nest              : 15.7.1
   @nrwl/node              : 15.7.1
   @nrwl/tao               : 15.7.1
   @nrwl/webpack           : 15.7.1
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.12.1
   @nguniversal/express-engine      : 15.1.0
   @nguniversal/builders            : 15.1.0
   ng-extract-i18n-merge            : 2.4.0
```

### Failure Logs

_No response_

### Additional Information

_No response_

### LINKED ISSUE #15109: HookWebpackError: Loop detected while pruning
### Current Behavior

Can't build nestJS application with `--generatePackageJson` parameter if project is using `gm` import (`gm/apps/gm/src/main.ts`)

Verbose output is:

```
HookWebpackError: Loop detected while pruning. Please report this issue.
    at makeWebpackError (/Users/tmp/gm/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/tmp/gm/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:71:1)
    at fn (/Users/tmp/gm/node_modules/webpack/lib/Compilation.js:480:17)
    at _next0 (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:69:1)
    at eval (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:82:1)
    at eval (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
-- inner error --
Error: Loop detected while pruning. Please report this issue.
    at nestMappedPackages (/Users/tmp/gm/node_modules/nx/src/lock-file/npm-parser.js:307:15)
    at nestMappedPackages (/Users/tmp/gm/node_modules/nx/src/lock-file/npm-parser.js:310:9)
    at mapSnapshots (/Users/tmp/gm/node_modules/nx/src/lock-file/npm-parser.js:256:9)
    at stringifyNpmLockfile (/Users/tmp/gm/node_modules/nx/src/lock-file/npm-parser.js:187:28)
    at createLockFile (/Users/tmp/gm/node_modules/nx/src/lock-file/lock-file.js:123:54)
    at /Users/tmp/gm/node_modules/@nrwl/webpack/src/plugins/generate-package-json-plugin.js:43:131
    at fn (/Users/tmp/gm/node_modules/webpack/lib/Compilation.js:478:10)
    at _next0 (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:69:1)
    at eval (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:82:1)
    at eval (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
```

### Expected Behavior

Successful build of application

### GitHub Repo

https://github.com/jaqua/gm

### Steps to Reproduce

1. Clone repo
2. npm install
3. nx run gm:build:production --generatePackageJson

Build fails

### Nx Report

```shell
Node : 16.6.1
   OS   : darwin x64
   npm  : 7.20.3
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/nest              : 15.7.2
   @nrwl/node              : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.8.4
```

### PR DESCRIPTION
**Pull request by meeroslav**
This PR solves three open issues with lock file parsing and pruning:
- In `Npm`, the same package version can be hoisted and nested in the lock file at the same time. This would lead to the node randomly being set as hoisted or nested depending on what comes first in the lock file
- Sorting package versions with `semver.gte` was not accurate, leading to the wrong version being normalized for `package.json`
- Inverted graph (using `reverse`) keeps a reference to the original nodes and has caching implemented. Inverting the same graph retrieves stale dependencies from the cache.

### Solution:
- Collect nodes first, and then decide what is set as hoisted, similarly how it's done for Yarn and Pnpm
- Fix the sorting function and add an additional check if the version matches hoisted one
- Update the dependencies in the inverted graph when re-hoisting nodes in the pruned graph

## Related Issue(s)

Fixes #15031
Fixes #15093
Fixes #15019
Fixes #13930

Likely fixes also #14999

### CODE REVIEW

File: packages/nx/src/lock-file/npm-parser.ts [hunk 1]
```diff
@@ -119,6 +109,17 @@ function addNodes(
       }
     });
   }
+
+  // some packages can be both hoisted and nested
+  // so we need to run this check once we have all the nodes and paths
```
Comment (meeroslav) [inline packages/nx/src/lock-file/npm-parser.ts:114]: We are marking hoisted nodes and adding nodes to graph after all of them were collected. Same as it's done in Yarn and Pnpm.

File: packages/nx/src/lock-file/project-graph-pruning.ts [hunk 2]
```diff
@@ -77,12 +77,21 @@ function findNodeMatchingVersion(
   if (versionExpr === '*') {
     return graph.externalNodes[`npm:${packageName}`];
   }
-  const nodes = Object.values(graph.externalNodes).filter(
-    (n) => n.data.packageName === packageName
-  );
+  const nodes = Object.values(graph.externalNodes)
+    .filter((n) => n.data.packageName === packageName)
+    .sort((a, b) => (gte(b.data.version, a.data.version) ? 1 : -1));
```
Comment (meeroslav) [inline packages/nx/src/lock-file/project-graph-pruning.ts:82]: This function was incorrectly returning 0 when `gte` is not satisfied.

File: packages/nx/src/lock-file/project-graph-pruning.ts [hunk 3]
```diff
@@ -136,14 +145,15 @@ function rehoistNodes(
       }
     }
   });
+  // invert dependencies for easier traversal back
+  const invertedGraph = reverse(builder.graph);
```
Comment (meeroslav) [inline packages/nx/src/lock-file/project-graph-pruning.ts:149]: No need to rebuild the graph on each iteration.

File: packages/nx/src/lock-file/project-graph-pruning.ts [hunk 4]
```diff
@@ -136,14 +145,15 @@ function rehoistNodes(
...
+  const invBuilder = new ProjectGraphBuilder(invertedGraph);
```
Comment (meeroslav) [inline packages/nx/src/lock-file/project-graph-pruning.ts:150]: We need dedicated builder to be able to manipulate the invertedGraph

File: packages/nx/src/lock-file/project-graph-pruning.ts [hunk 5]
```diff
@@ -178,17 +189,22 @@ function switchNodeToHoisted(
   );
 
   builder.removeNode(node.name);
+  // node has already been removed in the inverted graph
+  // but we need to remove the dependencies
+  invBuilder.removeDependenciesWithNode(previousName);
```
Comment (meeroslav) [inline packages/nx/src/lock-file/project-graph-pruning.ts:194]: We need to cleanup inverted graph's deps and rebuild them as well

File: packages/nx/src/project-graph/project-graph-builder.ts [hunk 6]
```diff
@@ -233,7 +233,7 @@ export class ProjectGraphBuilder {
     return this.graph;
   }
 
-  private removeDependenciesWithNode(name: string) {
+  removeDependenciesWithNode(name: string) {
```
Comment (meeroslav) [inline packages/nx/src/project-graph/project-graph-builder.ts:236]: This was marked public so it can be used in the project-graph-pruning.

There is no harm in exposing this imho. 

Alternative is copy-pasting this code in pruning.

**Review by FrozenPandaz — APPROVED** [review]

**Comment by Nick-Lucas** [comment]
Hey @FrozenPandaz, is there any chance of getting this backported to a 15.7.3? I can see it's in the 15.8.0 beta already, but I'm assuming that's some time out?

**Comment by yharaskrik** [comment]
> Hey @FrozenPandaz & @meeroslav, is there any chance of getting this backported to a 15.7.3? I can see it's in the 15.8.0 beta already, but I'm assuming that's some time out?

Seconding this.

**Comment by meeroslav** [comment]
The 15.8.0 is out so you can try the latest version. Sorry for the wait
