### PR TITLE
fix(core): prevent overwriting nx.json options to undefined

### LINKED ISSUE #7886: Parallel option in nx.json is ignored
## Current Behavior
The `parallel` option in `nx.json` (`$.taskRunnerOptions.default.options.parallel`) appears to be ignored.

When setting this field to `1`, Nx tasks should not be run in parallel, but they are. 

I also logged the value of `this.options.parallel` inside `@nrwl/workspace/src/tasks-runner/task-orchestrator.js` inside the `run` function, and the value was `3`.

Note that I'm using the `affected` commands, in case that makes a difference (e.g. `nx affected:test`).

This issue only appeared when the project was upgraded from Nx 12 to Nx 13 (migrations were run as part of this upgrade).

Sample `nx.json` file:
```
{
  "npmScope": "foo",
  "affected": {
    "defaultBase": "master"
  },
  "implicitDependencies": {
    "workspace.json": "*",
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    "tsconfig.base.json": "*",
    "tslint.json": "*",
    ".eslintrc.json": "*",
    "nx.json": "*",
    "webpack.js": "*"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/nx-cloud",
      "options": {
        "cacheableOperations": [
          "build",
          "lint",
          "test",
          "e2e"
        ],
        "accessToken": "<access token>",
        "canTrackAnalytics": false,
        "showUsageWarnings": true,
        "parallel": 1
      }
    }
  },
  "targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  },
  "cli": {
    "defaultCollection": "@nrwl/nest"
  },
  "defaultProject": "project-foo"
}
```

## Expected Behavior
The `parallel` field should be taken into consideration when determining how many tasks to run in parallel

### Failure Logs
n/a

### Environment
```
  Node : 16.12.0
  OS   : win32 x64
  npm  : 8.1.0

  nx : 13.2.2
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.2
  @nrwl/cypress : undefined
  @nrwl/devkit : 13.2.2
  @nrwl/eslint-plugin-nx : 13.2.2
  @nrwl/express : undefined
  @nrwl/jest : 13.2.2
  @nrwl/linter : 13.2.2
  @nrwl/nest : 13.2.2
  @nrwl/next : undefined
  @nrwl/node : 13.2.2
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.2
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.2
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.3.5
  rxjs : 7.4.0
```

### PR DESCRIPTION
**Pull request by puku0x**
ISSUES CLOSED: #7886

## Current Behavior

Some options in `nx.json` are overwritten to `undefined` during executing task runners.
For example, the `parallel` option is ignored. https://github.com/nrwl/nx/issues/7886#issuecomment-979153646

## Expected Behavior

The options in `nx.json` should work.

## Related Issue(s)

Fixes #7886

### CODE REVIEW

File: packages/workspace/src/command-line/utils.ts [hunk 1]
```diff
@@ -202,8 +202,6 @@ export function splitArgsIntoNxArgsAndOverrides(
     );
   } else if (args['parallel'] !== undefined) {
     nxArgs['parallel'] = Number(args['parallel']);
-  } else {
-    nxArgs['parallel'] = undefined;
   }
 
   return { nxArgs, overrides };
```
Comment (puku0x) [inline packages/workspace/src/command-line/utils.ts:207]:
```
npx nx affected --target=build --skip-nx-cache
```
- Before
image
- After
image

**Review by AgentEnder — APPROVED** [review]
Thanks for the contribution 🎉
