### PR TITLE
fix(angular): prevent init generator to bump versions and consider installed core packages versions

### LINKED ISSUE #14324: `nx generate @nwrl/angular:library` changes dependencies versions in root package.son
### Current Behavior

Dependency version identifiers in root package.json are updated after running `nx generate` with Angular schematics (reproduced with `@nwrl/angular:library` and `@nwrl/angular:ngrx`)
Example
```
- "@angular/common": "14.2.2",
+ "@angular/common": "~14.2.0",
```

### Expected Behavior

Dependencies in package.json and yarn.lock left intact

### Github Repo

_No response_

### Steps to Reproduce

- Initial root `package.json` content:
```
...
"@angular/common": "14.2.2",
"@angular/compiler": "14.2.2",
"@angular/core": "14.2.2",
...
```
- run `yarn nx generate @nrwl/angular:library --name=test-lib`
- observe changes in `package.json`:
```
"@angular/common": "~14.2.0",
"@angular/compiler": "~14.2.0",
"@angular/core": "~14.2.0",
```
It's also reflected in yarn.lock. However, the effective resolved versions (in yarnl.lock and node_modules) remain the same

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin arm64
   yarn : 3.2.3

   nx : 15.1.1
   @nrwl/angular : 15.1.1
   @nrwl/cypress : 15.1.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.1.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.1.1
   @nrwl/js : 15.1.1
   @nrwl/linter : 15.1.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.1.1
   @nrwl/web : Not Found
   @nrwl/webpack : 15.1.1
   @nrwl/workspace : 15.1.1
   typescript : 4.6.2
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ngrx/component-store: 14.0.2
   	 @ngrx/effects: 14.0.2
   	 @ngrx/router-store: 14.0.2
   	 @ngrx/store: 14.0.2
   	 @ngrx/store-devtools: 14.0.2
   	 @nguniversal/builders: 14.2.0
   	 @nguniversal/express-engine: 14.2.0
   	 apollo-angular: 3.0.0
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leosvelperez**
## Current Behavior

The init generator sometimes overrides the versions of installed packages. This is a bigger issue with the added support for multiple versions because it overrides the Angular-related package versions the workspace has installed with the latest minor version of the major currently installed.

## Expected Behavior

The init generator shouldn't bump any version of installed packages, it should only add packages that are not present. Bumping versions is a task for migrations. Also, installing any Angular-related package should consider the versions of Angular core packages and use them if present.

## Related Issue(s)

Fixes #14324

### CODE REVIEW

File: packages/angular/src/generators/utils/version-utils.ts [hunk 1]
```diff
@@ -46,14 +46,48 @@ export function getInstalledAngularVersionInfo(tree: Tree) {
   };
 }
 
+export function getInstalledPackageVersion(
```
Comment (Coly010) [inline packages/angular/src/generators/utils/version-utils.ts:49]: Should we instead read this information from either the installed package in the node_modules or from the lock files?

I’m concerned about scenarios where someone has “^14.0.0”, but their actual installed version is “14.1.0”.

if we installed “^14.0.0” it would install “14.2.x”.

it may not be a big deal, but just something that I have thought of

**Review by Coly010 — APPROVED** [review]
Left one question, looks good otherwise
