### PR TITLE
fix(angular): ng-add migration should set default project

### LINKED ISSUE #12332: Converting angular workspace to nrwl while preserving layout fails to set default project
## Current Behavior

When converting angular workspace to nrwl workspace while preserving layout using '--preserve-angular-cli-layout', the defaultProject property in nx.json is not set to existing angular project.

## Expected Behavior

defaultProject property of nx.json should be set to existing angular project in the workspace.

## Steps to Reproduce

1. ng new TourOfHeroes
2. ng add @nrwl/angular@14.5.10 --preserve-angular-cli-layout
3. Check nx.json
4. Unable to run 'npm start' without explicitly mentioning '--project' parameter

Git URL: https://github.com/mazhar-fis/nx-issue-1.git

### Failure Logs

Error: Both project and target have to be specified
    at parseRunOneOptions (C:\Projects\npx\temp\node_modules\nx\src\command-line\run-one.js:76:15)
    at Object.<anonymous> (C:\Projects\npx\temp\node_modules\nx\src\command-line\run-one.js:20:22)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Projects\npx\temp\node_modules\tslib\tslib.js:115:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! temp@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the temp@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\someone\AppData\Roaming\npm-cache\_logs\2022-09-30T05_11_33_802Z-debug.log

### Environment

  NX   Report complete - copy this into the issue template

   Node : 14.19.3
   OS   : win32 x64
   npm  : 6.14.17

   nx : 14.5.10
   @nrwl/angular : 14.5.10
   @nrwl/cypress : 14.5.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

Migration doesn't set the default project

## Expected Behavior

Migration should set the default project

## Related Issue(s)

Fixes #12332

### CODE REVIEW

File: packages/angular/src/generators/ng-add/migrate-from-angular-cli.ts [hunk 1]
```diff
@@ -36,6 +38,10 @@ export async function migrateFromAngularCli(
   const projects = getAllProjects(tree);
   const options = normalizeOptions(tree, rawOptions, projects);
 
+  const defaultProject = projects.apps.find((app) =>
+    app.config.sourceRoot?.startsWith('src')
```
Comment (leosvelperez) [inline packages/angular/src/generators/ng-add/migrate-from-angular-cli.ts:42]: nit: I think it's more intuitive to assert whether the project is in the root of the Angular CLI workspace. That's the check done inside the app migrator for other tasks.
```suggestion
    app.config.root === ''
```

File: packages/angular/src/generators/ng-add/migrate-from-angular-cli.spec.ts [hunk 2]
```diff
@@ -241,6 +241,13 @@ describe('workspace', () => {
       ).not.toBeDefined();
     });
 
+    it('should set the default project correctly', async () => {
+      await migrateFromAngularCli(tree, {});
+      expect(readJson(tree, 'nx.json').defaultProject).toMatchInlineSnapshot(
+        `"myApp"`
+      );
```
Comment (leosvelperez) [inline packages/angular/src/generators/ng-add/migrate-from-angular-cli.spec.ts:248]: nit:
```suggestion
      expect(readJson(tree, 'nx.json').defaultProject).toBe('myApp');
```

**Review by leosvelperez — APPROVED** [review]
LGTM! 🎉
