### PR TITLE
fix(linter): fixes usages of lintProjectGenerator without eslintFilePatterns provided

### LINKED ISSUE #18740: Using lintProjectGenerator fails without an options.eslintFilePatterns param
### Current Behavior

When using a custom generator we build, it fails on the call to `lintProjectGenerator` with the following parameters:
```
const initLint = await lintProjectGenerator(tree, {
    project: projectConfig.name,
    linter: Linter.EsLint,
    skipFormat: false,
  });
```

The resulting failure is: ` >  NX   Cannot read properties of undefined (reading 'push')`

### Expected Behavior

Call to `lintProjectGenerator` does not fail.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Create a generator that uses `lintProjectGenerator`
2. Do not provide a `eslintFilePatterns` param to the options of the generator call
3. Use the created generator

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 19.6.0
   OS     : darwin-arm64
   yarn   : 3.2.1
   
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/detox          : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/expo           : 16.6.0
   @nx/next           : 16.6.0
   @nx/node           : 16.6.0
   @nx/plugin         : 16.6.0
   @nx/react          : 16.6.0
   @nx/react-native   : 16.6.0
   @nx/rollup         : 16.6.0
   @nx/storybook      : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/vite           : 16.6.0
   @nx/web            : 16.6.0
   @nx/webpack        : 16.6.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @trumbitta/nx-plugin-unused-deps : 1.12.1
   ---------------------------------------
   Local workspace plugins:
         @arrived/features-verification-stepper
         @arrived/features-property-details
         @arrived/features-cash-accounts
         @arrived/features-questionnaire
         @arrived/features-checkout
         @arrived/features-tooltips
         @arrived/features-webinar
         @arrived/features-invest
         @arrived/city-pages-app
         @arrived/error-pages
         @arrived/mobile-app
         @arrived/public-app
         @arrived/bricks
         @arrived/admin-app
         @arrived/theme
         @arrived/learn-app
         @arrived/web-app
         @arrived/nx
```

### Failure Logs

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jbean96**
Previous change broke usages of the lintProjectGenerator which did not include an eslintFilePatterns array option. This resolves by first checking for the arrays existence before pushing to it

closed #18740

## Related Issue(s)

Fixes #18740

### CODE REVIEW

**Review by AgentEnder — DISMISSED** [review]

File: packages/linter/src/generators/lint-project/lint-project.ts [hunk 1]
```diff
@@ -51,7 +51,7 @@ export async function lintProjectGenerator(
   const projectConfig = readProjectConfiguration(tree, options.project);
 
   const lintFilePatterns = options.eslintFilePatterns;
```
Comment (meeroslav) [inline packages/linter/src/generators/lint-project/lint-project.ts:53]: This would be the accepted solution since the option **is marked** as optional

```suggestion
  const lintFilePatterns = options.eslintFilePatterns ?? [];
```

File: packages/linter/src/generators/lint-project/lint-project.ts [hunk 2]
```diff
@@ -51,7 +51,7 @@ export async function lintProjectGenerator(
...
-  if (isBuildableLibraryProject(projectConfig)) {
+  if (lintFilePatterns && isBuildableLibraryProject(projectConfig)) {
```
Comment (meeroslav) [inline packages/linter/src/generators/lint-project/lint-project.ts:54]: This would break the existing functionality

**Review by meeroslav — CHANGES_REQUESTED** [review]
This generator is internal and is meant to be used with caution. 

We **do not guarantee** there won't be any breaking changes in the future.

File: packages/linter/src/generators/lint-project/lint-project.ts (hunk 2 above)
Comment (jbean96) [reply packages/linter/src/generators/lint-project/lint-project.ts:54]: Sounds good, the `?? []` solution is fine by me.

**Review by meeroslav — APPROVED** [review]
