### PR TITLE
fix(misc): parse args for format command

### LINKED ISSUE #1890: format: Can no longer format just app & lib files
## Expected Behavior

Before version 8.5.0 I could run format --all to format all my files inside of apps & libs & tools. 

## Current Behavior

The above behaviour no longer works as of #1776, as this functionality has been removed to instead make -all format all files in the workspace. (Does NX aim to follow SemVer?)

This causes many issues where there are auto-generated files contained in the workspace that I do not want to check for formatting, e.g. angular /dist/ folder, unit test results, etc.

For now I've had to revert to the previous version, as this stops both the developer experience and the CI builds.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Build an angular app using NX >= 8.5.0
2. Run format script
3. See errors regarding files in the /dist/ folder

### Failure Logs

image

### LINKED ISSUE #2284: Should not format the dist folder
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

`yarn format` or `nx format` command should not format the files in `dist` folder.

Please describe the behavior you are expecting

## Current Behavior

With the latest update `yarn format` commands formats the dist folder. previously it did not happen.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

```bash
# on the previous version
ng build --prod --vendor-chunk
# to update
yarn update
# to format
yarn format
```

### Context

I just updated the nx workspace and the format command formatted the dist directory.

```
  @nrwl/angular : 8.10.1
  @nrwl/cli : 8.10.1
  @nrwl/cypress : 8.10.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.10.1
  @nrwl/linter : 8.10.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 8.10.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.10.1
  @nrwl/web : 8.10.1
  @nrwl/workspace : 8.10.1
  typescript : 3.5.3
```

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

### LINKED ISSUE #2471: default affected criteria are not set while formatting
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

When using `npm run format:write` it should only format the affected files.

## Current Behavior

Because of an exception the script formats all files.

## Failure Information (for bugs)

Even though the console prints `Affected criteria defaulted to --base=master --head=HEAD` the arguments are not set while calling parseFiles() within getPatterns() in format.js. The result is undefined which results in an exception. The catch handler returns a list of all possible files which could be formatted (everything except node_modules and patterns defined in prettierignore).

When I run `npm run format -- --base=master --head=HEAD` explicity only the affected files will be formatted.

### Context

I use NX 9

### Failure Logs

There are no logs since the error is handled silently.

## Other

This is relataed to the issue https://github.com/nrwl/nx/issues/2284 and comment https://github.com/nrwl/nx/issues/2284#issuecomment-573463164

### LINKED ISSUE #2541: Disable format dist folder
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites
No prerequisites.

- [X ] I am running the latest version
- [ X] I checked the documentation (nx.dev) and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

image

image

## Expected Behavior
Does not format **dist** folder.

image

## Current Behavior
Now **dist** folder is formatted.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

1. ng build
2. npm run format

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

- version of Nx used (_Please run `nx report` at the root of your workspace and copy the results here if you are using Nx 8.6.1 or greater_)
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

### PR DESCRIPTION
**Pull request by FrozenPandaz**
## Current Behavior (This is the behavior we have today, before the PR is merged)

Args are not parsed for the format command thus not setting default values for base

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

Args are parsed for the format command, setting values for base, and not formatting all files for `yarn format`

## Issue
Fixes #2284
Fixes #2471 
Fixes #2541

### CODE REVIEW

File: packages/workspace/src/command-line/format.ts [hunk 1]
```diff
@@ -26,8 +26,10 @@ const PRETTIER_EXTENSIONS = [
 export function format(command: 'check' | 'write', args: yargs.Arguments) {
   let patterns: string[];
 
+  const { nxArgs } = splitArgsIntoNxArgsAndOverrides(args);
+
   try {
-    patterns = getPatterns(args as any);
+    patterns = getPatterns(nxArgs as any);
```
Comment (vsavkin) [inline packages/workspace/src/command-line/format.ts]: @FrozenPandaz I'm not sure how this fixes the issue. `args` is a super set of `nxArgs`.

Comment (FrozenPandaz) [reply packages/workspace/src/command-line/format.ts]: `args` doesn't have the default values processing that `splitArgsIntoNxArgsAndOverrides` provides.

`yarn format` used to be equal to `yarn format --base master --head HEAD` but without that parsing, it was not the case. This makes it the case again.
