### PR TITLE
fix(nextjs): Moving a library using @nx/workspace:move should update …

### LINKED ISSUE #20821: Renaming/Moving NextJS library with `@nx/workspace:move` doesn't work for the server import path
### Current Behavior

When renaming/moving NextJS library with `@nx/workspace:move` only `@org/library-1` import path is changed. 

The `@org/library-1/server` stays the same.

### Expected Behavior

When renaming/moving NextJS library with `@nx/workspace:move` both import paths `@org/library-1` and `@org/library-1/server` should be changed.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Generate NextJS library `nx g @nx/next:library library-1 --directory=libs/library-1`
2. Rename it `nx g move --projectName library-1 --newProjectName library-2 --destination libs/library-2`

### Nx Report

```shell
Node   : 20.10.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx (global)        : 17.2.3
   nx                 : 17.2.3
   @nx/js             : 17.2.3
   @nx/jest           : 17.2.3
   @nx/linter         : 17.2.3
   @nx/eslint         : 17.2.3
   @nx/workspace      : 17.2.3
   @nx/devkit         : 17.2.3
   @nx/eslint-plugin  : 17.2.3
   @nx/next           : 17.2.3
   @nx/playwright     : 17.2.3
   @nx/react          : 17.2.3
   @nrwl/tao          : 17.2.3
   @nx/web            : 17.2.3
   typescript         : 5.2.2
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ndcunningham**
## Current
When you using `@nx/workspace:move` after create a Next.js library the server path remains unchanged.

## Expected
The server path is changed as well as the main entry point for the library path.

Fixes: #20821

### CODE REVIEW

**Review by jaysoo — APPROVED** [review]

File: packages/workspace/src/generators/move/lib/update-imports.ts [hunk 1]
```diff
@@ -77,7 +91,7 @@ export function updateImports(
     )
   );
 
-  const projectRefs = [
+  let projectRefs = [
```
Comment (jaysoo) [inline packages/workspace/src/generators/move/lib/update-imports.ts:94]: Since this isn't reassigned, we don't need to change to `let`.

**Review by xiongemi — APPROVED** [review]
