### PR TITLE
fix(nextjs): update babel setup to better support next apps

### LINKED ISSUE #4611: NextJS - decorators do not work in libs
## Current Behavior
I cannot import files with decorators from libs when using NextJS application.

## Expected Behavior
I should be able to import files using decorators from libs when using NextJS application.

## Steps to Reproduce

1. Create new NX repository

2. Create NextJS app (call it "desktop")

3. Create React lib (call it "utils")

4. Update `apps/desktop/.babelrc`:
```json
{
  "presets": ["next/babel"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ]
}
```

5. Install `@wikia/dependency-injection` (or any other decorators based library you feel comfortable using).

6. Create following file inside:
* `apps/desktop/utils/sample-service.ts`
* `libs/utils/src/lib/sample-service.ts` (and export it in `libs/utils/src/index.ts`)
```ts
import { Injectable } from '@wikia/dependency-injection';

@Injectable()
export class SampleService {
  print() {
    console.log('works');
  }
}
```

7. At the begging of `apps/desktop/pages/index.ts` `Index` function paste:
```ts
  useEffect(() => {
    const container = new Container();
    const service = container.get(SampleService);

    service.print();
  }, []);
```

8. Test

If you import `SampleService` from 
```ts
import { SampleService } from '../utils/sample-service';
```
✅  It works with no problems.

If you import `SampleService` from
```ts
import { SampleService } from '@repo-name/utils';
```
or
```ts
import { SampleService } from '../../libs/utils/src/lib/sample-service';
```

❌  You get the error from "Failure Logs".

### Failure Logs
```
Syntax error: Support for the experimental syntax 'decorators-legacy' isn't currently enabled:

  1 | import { Injectable } from '@wikia/dependency-injection';
  2 | 
> 3 | @Injectable()
    | ^
  4 | export class SampleService {
  5 |   print() {
  6 |     console.log('works');
```

### Environment
```
  Node : 12.18.3
  OS   : darwin x64
  npm  : 6.14.6

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : 11.1.5
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : 11.1.5
  @nrwl/node : 11.1.5
  @nrwl/react : 11.1.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : 11.1.5
  @nrwl/workspace : 11.1.5
  typescript : 4.0.3
```

## My insight

My idea is that NextJS doesn't handle well files outside of **its** root folder, which is in our `apps/**`. They work well with paths so the problem is not there. I am not sure if this issue should land here or in NextJS repository, still it is more nx/monorepo specific than NextJS.

May be related: https://github.com/nrwl/nx/issues/4552

### PR DESCRIPTION
**Pull request by jaysoo**
This PR removes `@nrwl/web/babel` preset from the root `babel.config.json` file. The web preset conflicts with Next.js (and potentially other babel presets), so we should scope it to individual projects instead.

**Major Changes**

1. Remove presets from root `babel.config.json` so each project can provide their own config without worrying about conflicts.
2. Remove `babel-jest.config.json` from jest generator -- we only use `.babelrc` now.
3. Update generated `jest.config.js` file to not set `cwd: __dirname` so monorepo support is used and individual `.babelrc` files are used for each project.
4. Add migration for removing presets from root `babel.config.json` and adding `@nrwl/web/babel` preset to projects that need it.

## Current Behavior
Web babel preset is applied at hte root.

## Expected Behavior
Web babel preset is only used in web, react, gatsby projects.

---

Fixes #4611, #4573, #2573

### CODE REVIEW

File: packages/next/babel.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+/*
+ * Babel preset to provide Gatsby support for Nx.
```
Comment (kirjai) [inline packages/next/babel.ts:2]: should this say "Gatsby"? seeing how it's in the `next` directory, i assume this needs to say "Next"?

**Review by kirjai — APPROVED** [review]

File: packages/next/babel.ts (hunk 1 above)
Comment (jaysoo) [reply packages/next/babel.ts:2]: Yes it should say Next.js

**Review by kirjai — APPROVED** [review]

File: packages/web/src/migrations/update-11-5-0/update-babel-config.ts [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+        updateJsonInTree('babel.config.json', (json) => {
+          if (Array.isArray(json.presets)) {
+            json.presets = json.presets.filter((x) => x !== '@nrwl/web/babel');
+          }
+          return json;
+        })
+      );
+    }
+
+    Object.keys(projectGraph.nodes).forEach((name) => {
```
Comment (FrozenPandaz) [inline packages/web/src/migrations/update-11-5-0/update-babel-config.ts:21]: If we write this as a `@nrwl/devkit` generator then you can use `getProjects()` to get a list of the projects in the workspace. which is cheaper than getting the project graph because it won't calculate dependencies.

File: packages/next/src/migrations/update-11-5-0/update-babel-config.ts [hunk 3]
```diff
@@ -0,0 +1,31 @@
+import { chain, Rule, Tree } from '@angular-devkit/schematics';
+import { getFullProjectGraphFromHost } from '@nrwl/workspace/src/utils/ast-utils';
+import { formatFiles, updateJsonInTree } from '@nrwl/workspace';
+
+export default function update(): Rule {
+  return (host: Tree) => {
+    const updates = [];
+    const projectGraph = getFullProjectGraphFromHost(host);
+
+    Object.keys(projectGraph.nodes).forEach((name) => {
```
Comment (FrozenPandaz) [inline packages/next/src/migrations/update-11-5-0/update-babel-config.ts:10]: If we write this as a `@nrwl/devkit` generator then you can use `getProjects()` to get a list of the projects in the workspace. which is cheaper than getting the project graph because it won't calculate dependencies.

File: workspace.json [hunk 4]
```diff
@@ -285,6 +285,11 @@
                 "glob": "**/*.json",
                 "output": "/"
               },
+              {
```
Comment (FrozenPandaz) [inline workspace.json:288]: This is necessary because of the `.` right?

Usually we name the file `__dot__babelrc` and then replace with `{ dot: '.' }`

File: packages/web/src/migrations/update-11-5-0/update-babel-config.ts (hunk 2 above)
Comment (vsavkin) [reply packages/web/src/migrations/update-11-5-0/update-babel-config.ts:21]: Yup, all migrations scripts have to be written using Nx Devkit.

File: packages/web/migrations.json [hunk 5]
```diff
@@ -1,4 +1,5 @@
 {
+  "cli": "nx",
```
Comment (FrozenPandaz) [inline packages/web/migrations.json:2]: This is inconsistent but... this needs to move down to inside `update-babel-config-11.5.0`
