### PR TITLE
fix(core): resolve nx against command root if workspace not provided

### LINKED ISSUE #16603: Nx commands stop working when using Yarn classic with nohoist
### Current Behavior

The Nx tool does nothing anymore. It doesn't log anything or attempt to run any commands/scripts. Even `nx reset` doesn't do anything.

Running via npx (installed in workspace root package):

```shell
npx nx affected --target=build
# no output
```

Via Yarn (installed in workspace root package):

```shell
yarn nx affected --target=build
yarn run v1.22.19
$ /Users/ian/code/project-backend/node_modules/.bin/nx affected --target=build
✨  Done in 0.40s.
```

The same behaviour is observed when the script is written in the `package.json` as in: `"build": "nx affected --target=build"`

Installed globally by Yarn or NPM (only stopped working since I started using Yarn):

```shell
nx affected --target=build
# no output
```

I've confirmed that the Nx command is definitely being run by manually adding debug logging to the script.

### Expected Behavior

The Nx tool should log something and perform some actions based on its CLI arguments.

### GitHub Repo

[igilham/nx-yarn-nohoist-repro](https://github.com/igilham/nx-yarn-nohoist-repro)

### Steps to Reproduce

It's not clear if this is reproducible or not yet, but I will attempt to provide what information I can.

**package.json**

```json
"dependencies": {
  "@nrwl/nx-cloud": "^15.3.5",
  "lerna": "^6.6.1",
   "nx": "15.8.9",
},
"workspaces": {
  "packages": [ "REDACTED..." ],
  "nohoist": [ "*", "**" ]
}
```

Note that due to some legacy build scripts and terrible dependencies, I'm making heavy use of `resolutions` and `nohoist`.

**lerna.json**

```json
{
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "useNx": true,
  "command": {
    "init": {
      "exact": true
    }
  }
}
```

**nx.json**

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "affected": {
    "defaultBase": "develop"
  },
  "cli": {
    "packageManager": "yarn"
  },
  "namedInputs": {
    "sharedGlobals": [
      "{workspaceRoot}/.node-version",
      "{workspaceRoot}/package.json",
      "{workspaceRoot}/tsconfig.json"
    ],
    "sharedLinter": ["{workspaceRoot}/.eslintrc.json", "sharedGlobals"],
    "packageConfigs": [
      "{projectRoot}/package.json",
      "{projectRoot}/tsconfig.json",
      "{projectRoot}/tsconfig-build.json",
      "{projectRoot}/jest.config.js",
      "{projectRoot}/jest.config.all.js",
      "{projectRoot}/jest.config.integration.js",
      "{projectRoot}/.mocharc.json"
    ],
    "packageLinter": [
      "{projectRoot}/.eslintrc.json",
      "{projectRoot}/.prettierrc.cjs",
      "{projectRoot}/.prettierrc.js",
      "{projectRoot}/.prettierignore",
      "sharedLinter"
    ],
    "default": [
      "{projectRoot}/src/**/*.ts",
      "{projectRoot}/src/**/*.tsx",
      "{projectRoot}/src/**/*.js",
      "{projectRoot}/src/**/*.jsx",
      "{projectRoot}/src/**/*.json",
      "sharedGlobals",
      "packageConfigs"
    ],
    "linter": ["default", "packageLinter"],
    "production": ["default"]
  },
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["default", "^default"],
      "outputs": ["{projectRoot}/lib"]
    },
    "tsc-check": {
      "dependsOn": ["^build"],
      "inputs": ["default", "^default"]
    },
    "test": {
      "dependsOn": ["^build", "tsc-check"],
      "inputs": ["default", "^default"]
    },
    "test:int": {
      "dependsOn": ["^build", "tsc-check"],
      "inputs": ["default", "^default"]
    },
    "test:all": {
      "dependsOn": ["^build", "tsc-check"],
      "inputs": ["default", "^default"]
    },
    "test:cover": {
      "dependsOn": ["^build", "tsc-check"],
      "inputs": ["default", "^default"],
      "outputs": ["{projectRoot}/coverage"]
    },
    "lint": {
      "inputs": ["linter", "^linter"]
    },
    "lint:fix": {
      "inputs": ["linter", "^linter"]
    },
    "prettier": {
      "inputs": ["linter", "^linter"]
    },
    "prettier:check": {
      "inputs": ["linter", "^linter"]
    }
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/nx-cloud",
      "options": {
        "cacheableOperations": [
          "build",
          "tsc-check",
          "test",
          "test:cover",
          "lint",
          "lint:fix",
          "prettier",
          "prettier:check"
        ],
        "accessToken": "REDACTED"
      }
    }
  }
}

```

### Nx Report

```shell
Does not print anything due to the described issue.

Tested with Nx 15.8.9 and 15.9.2 with the same results.

I added some manual logging to debug the CLI as run via Yarn. You can see some of the data collected in the tool here:

nx start
getting compile cache
observable polyfill
resolved localNx /Users/ian/code/newsletter-backend/node_modules/nx/bin/nx.js
isLocalInstall: false
local version 15.9.2
global version 15.9.2
nx global hand-off
require local
require local done

Notably, it ends up in the bottom `else` statement as


else {
  console.log('require local');
  require(localNx);
  console.log('require local done');
}
```

### Failure Logs

```shell
Nothing is logged
```

### Additional Information

I'm migrating a small monorepo from NPM/Lerna/Nx (without workspaces) to Yarn with workspaces. Somewhere along the way, the Nx CLI stopped working. It doesn't produce any output and exits immediately. I guess my installation is messed up somehow but I'm having difficulty finding the cause.

It seems that when Nx is installed by Yarn either globally or in the monorepo root, it does not run any commands at all.

I can work around this issue for now by using the Lerna CLI to run the scripts but longer-term I'm hoping to drop the Lerna dependency when Nx can be relied upon enough to simply work.

I've tried removing all my local node_modules and running `yarn cache clean` then reinstalling but it hasn't helped.

### PR DESCRIPTION
**Pull request by meeroslav**
## Current Behavior
`resolveNx` wrongfully detects nested `nx` as the base one in the workspace with aggressive `no-hoist` setup

## Expected Behavior
`resolveNx` should look for `nx` from the command run location and properly detect local nx location

## Related Issue(s)

Fixes #16603

cc @AgentEnder

### CODE REVIEW

File: packages/nx/bin/nx.ts [hunk 1]
```diff
@@ -99,23 +100,26 @@ function main() {
 }
 
 function resolveNx(workspace: WorkspaceTypeAndRoot | null) {
+  // root relative to node_modules/nx/bin/nx,
+  const commandRoot = join(__dirname, '../../..');
```
Comment (FrozenPandaz) [inline packages/nx/bin/nx.ts:104]:
```suggestion
  const workingDirectory = process.cwd();
```

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by AgentEnder — APPROVED** [review]

File: packages/nx/bin/nx.ts (hunk 1 above)
Comment (meeroslav) [reply packages/nx/bin/nx.ts]: Unfortunately that does not work, since it detects the working directory of the command invocation, but we are looking for globals root, which is completely different folder.

`__dirname` gives us path to `nx.js` being invoked. From there on we need to start searching from the root for `nx` installations.

**Review by FrozenPandaz — APPROVED** [review]
