### PR TITLE
fix(core): clean up tmp directories during migrate

### LINKED ISSUE #5947: nx migrate causes Windows login to slow down
## Current Behavior

A few days ago Windows on my brand new machine suddenly needed minutes instead of seconds to login. Right after entering my credentials, the login process seemed to be stuck at the "Welcome" screen. I have noticed the same behavior several times before on my previous machine and at some point the problem always disappeared. But this time, it spoiled the fun of having a new laptop, so I started to investigate 🕵️‍♂️

Enabling [verbose status messages](https://tweaks.com/windows/39215/enable-detailed-logon-logoff-and-shutdown-status-messages/) revealed that it was actually the User Profile service that slowed down the login process: "Please wait for the User Profile Service."

Next, I did some [performance profiling using XPerf](https://superuser.com/a/1012442) to see what was going on during login. First, this confirmed that it was indeed the User Profile Service that was running amok:

image

Some more digging revealed that in addition to the high CPU usage, there was also a lot of file I/O activity caused by that same process (`svchost.exe (2184)`, the host process of the `profsvc.dll`):

image

Most of that activity happened in directories named `tmp-{something}` in my user profile's temp directory.

There were 153 of these folders, containing 547,852 files amounting to 2.81 GB in total. All created between 13:00 and 14:00 on Saturday. Looking at the contents of those folders revealed that they somehow seemed to be related to npm packages and my development stuff:

image

image

So I deleted all these directories and sure enough, the login time was back to seconds. I solved the problem, now I wanted to know what caused the creation of all these files in the first place.

Thanks to [WakaTime](https://wakatime.com/) I could reconstruct that I was indeed working on a project around the time all those directories had been created:

image

Among the things I did on Saturday was an Angular update (10 to 11, then to 12) using `nx migrate`.

So I reverted to the Angular 10 commit of the project, ran `./node_modules/.bin/nx migrate latest` again and sure enough: new `tmp-{something}` directories were showing up while Nx was fetching various packages:

image

## Expected Behavior

First of all, the expected behavior of the Windows User Profile service is that it should not be slowed down by temp directory full of garbage. But I guess that's something for [microsoft/Windows-Dev-Performance](https://github.com/microsoft/Windows-Dev-Performance/issues) ;-)

In the meantime, it would be great if `nx migrate` could clean up after itself.

## Steps to Reproduce
1. buy an expensive, high-end Windows notebook
2. have an outdated Nx Workspace (e.g. `@nrwl/workspace@10`)
3. run `./node_modules/.bin/nx migrate latest`

### Environment

```

>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.1.0
  @nrwl/cli : 10.4.4
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.1.0
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.4
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.4
  typescript : 3.9.7
```

### PR DESCRIPTION
**Pull request by FrozenPandaz**
## Current Behavior

`nx migrate` leaves a lot of tmp directories around. Usually the operating system cleans these up. But they can collect and cause a lot of storage to be used.

## Expected Behavior

`nx migrate` cleans up tmp directories when things are successful. When things fail though, tmp directories stay around to help debug the issue.

## Related Issue(s)

Fixes #5947

### CODE REVIEW

File: packages/tao/src/commands/migrate.ts [hunk 1]
```diff
@@ -459,6 +460,8 @@ function createFetcher(packageManager: PackageManager) {
           version: resolvedVersion,
         };
       }
+      console.log('cleaning up', dir);
+      rmdirSync(dir, { recursive: true });
```
Comment (Phillip9587) [inline packages/tao/src/commands/migrate.ts:464]: I suggest using `removeSync` from 'fs-extra' because the `recursive` option of `rmdirSync` is deprecated see `https://nodejs.org/api/fs.html#fs_fs_rmdirsync_path_options`.

Comment (FrozenPandaz) [reply packages/tao/src/commands/migrate.ts]: Good idea. I'll use `rmSync` instead as recommended there

Comment (Phillip9587) [reply packages/tao/src/commands/migrate.ts]: @FrozenPandaz rmSync is not safe to use because it is not supported in Node 12. I think #5896 is related...
