### PR TITLE
fix(linter): do not break migration if eslint file is missing

### LINKED ISSUE #18377: Generate fails when app does not have .eslintrc.json
### Current Behavior

Generating a new library using @nx/react within a workspace that has an app of nx/go backend and an app of nx/react frontend.

Generating a new nx react lib fails with 
`TypeError: Cannot read properties of undefined (reading 'eslintConfig')`

Comes from this function in @nx/linter/src/generators/init/init-migration.js
```js
function migrateConfigToMonorepoStyle(projects, tree, unitTestRunner) {
    (0, devkit_1.writeJson)(tree, '.eslintrc.base.json', (0, global_eslint_config_1.getGlobalEsLintConfiguration)(unitTestRunner));
    // update extens in all projects' eslint configs
    console.log("HERE PROJECT", JSON.stringify(projects))
    projects.forEach((project) => {
        const lintTarget = findLintTarget(project);
        if (lintTarget) {
            console.log("HERE", JSON.stringify(lintTarget))
                const projectEslintPath = (0, devkit_1.joinPathFragments)(project.root, **lintTarget.options.eslintConfig** || (0, eslint_file_1.findEslintFile)(tree, project.root));
                migrateEslintFile(projectEslintPath, tree);
}});}
```

able to solve by adding a .eslintrc.json file into apps/backend directory; however I think there should be some sort of check here as not all project's contain eslint if considering managing multiple languages in a monorepo.

### Expected Behavior

Should generate the react lib without regard to whether go has a lint config

### GitHub Repo

_No response_

### Steps to Reproduce

1. Generate a @nx/react frontend app
2. Generate a @nx/go backend app
3. Attempt to generate a @nx/react lib

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.1
   OS     : linux-x64
   npm    : 9.5.1
   
   nx (global)        : 16.4.0
   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/cypress        : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nx/react          : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/vite           : 16.5.5
   @nx/web            : 16.5.5
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx-go/nx-go : 2.7.0
```

### Failure Logs

```shell
HERE {"executor":"nx:run-commands","options":{"commands":["nx run-many -t lint --projects=frontend,pages,ui,store,backend,db,handler,router"]}}
HERE {"executor":"@nx-go/nx-go:lint"}

 >  NX   Cannot read properties of undefined (reading 'eslintConfig')


TypeError: Cannot read properties of undefined (reading 'eslintConfig')
    at /home/jared/pipes/node_modules/@nx/linter/src/generators/init/init-migration.js:16:108
    at Array.forEach (<anonymous>)
    at migrateConfigToMonorepoStyle (/home/jared/pipes/node_modules/@nx/linter/src/generators/init/init-migration.js:12:14)
    at /home/jared/pipes/node_modules/@nx/linter/src/generators/lint-project/lint-project.js:92:67
    at Generator.next (<anonymous>)
    at /home/jared/pipes/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/jared/pipes/node_modules/tslib/tslib.js:165:16)
    at lintProjectGenerator (/home/jared/pipes/node_modules/@nx/linter/src/generators/lint-project/lint-project.js:63:20)


    at /home/jared/pipes/node_modules/@nx/react/src/generators/library/lib/add-linting.js:13:70
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### LINKED ISSUE #18544: Generate fails when there is a lint target without `eslintConfig` option at a root `project.json`
### Current Behavior

When creating a new NX plugin, if the `project.json` at the root of the repository contains a `lint` target that doesn't contain the option `eslintConfig`, and there is no `.eslintrc.base.json` at the root, then generation of a new plugin fails.

In other words, running:
```
nx g plugin my-plugin --directory=plugins --importPath=@myorg/my-plugin
```

Leads to an error (see failure logs below).

When looking at the code (function `findLintTarget`), I saw that NX is looking for targets called `lint` or targets with executor `@nx/linter:eslint`. This breaks the assumption that we can call targets however we want, and add whatever executors we want to them.

### Expected Behavior

Running the `nx g plugin my-plugin ...` command simply generates a new NX plugin without checking so many details about the structure of my repo.

I unfortunately don't know the NX codebase well enough to suggest a change, but I would avoid mixing migration with plugin generation. They seem two very different topics from a high level perspective.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Create an NX project with a `project.json` at the root
2. Add a toy-example `lint` target to it, such as: `"lint": { "executor": "nx:noop" }`
3. Make sure there is no `.eslintrc.base.json` at root level
4. Generate a plugin with `nx g @nx/plugin:plugin my-plugin`

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/plugin         : 16.6.0
   @nx/react          : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/vite           : 16.6.0
   @nx/web            : 16.6.0
   typescript         : 5.1.3
   ---------------------------------------
   Community plugins:
   @jnxplus/nx-boot-maven : 7.3.0
   @jscutlery/semver      : 3.0.0
   @nx-tools/nx-container : 5.0.2
   ngx-deploy-npm         : 5.2.0

[...]
```

### Failure Logs

```shell
>  NX   Cannot read properties of undefined (reading 'eslintConfig')


TypeError: Cannot read properties of undefined (reading 'eslintConfig')
    at /my/repo/path/node_modules/@nx/linter/src/generators/init/init-migration.js:14:104
    at Array.forEach (<anonymous>)
    at migrateConfigToMonorepoStyle (/my/repo/path/node_modules/@nx/linter/src/generators/init/init-migration.js:11:14)
    at /my/repo/path/node_modules/@nx/linter/src/generators/lint-project/lint-project.js:50:67
    at Generator.next (<anonymous>)
    at /my/repo/path/node_modules/@nx/linter/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/my/repo/path/node_modules/@nx/linter/node_modules/tslib/tslib.js:165:16)
    at lintProjectGenerator (/my/repo/path/node_modules/@nx/linter/src/generators/lint-project/lint-project.js:17:20)
    at /my/repo/path/node_modules/@nx/js/src/generators/library/library.js:154:22
```
```


### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

For those looking for a quick fix, having a `.eslintrc.base.json` at the root solves the issue.

### PR DESCRIPTION
**Pull request by meeroslav**
## Related Issue(s)

Fixes #18544
Fixes #18377

### CODE REVIEW

File: packages/linter/src/generators/init/init-migration.ts [hunk 1]
```diff
@@ -38,9 +40,8 @@ export function migrateConfigToMonorepoStyle(
 export function findLintTarget(
   project: ProjectConfiguration
 ): TargetConfiguration {
-  return Object.entries(project.targets ?? {}).find(
-    ([name, target]) =>
-      name === 'lint' ||
```
Comment (meeroslav) [inline packages/linter/src/generators/init/init-migration.ts:43]: This is very prone to misuse and does not guarantee that the lint uses the ESLint config.

File: packages/linter/src/generators/init/init-migration.ts [hunk 2]
```diff
@@ -26,10 +26,12 @@ export function migrateConfigToMonorepoStyle(
   projects.forEach((project) => {
     const lintTarget = findLintTarget(project);
     if (lintTarget) {
-      const projectEslintPath = joinPathFragments(
-        project.root,
-        lintTarget.options.eslintConfig || findEslintFile(tree, project.root)
-      );
+      const eslintFile =
+        lintTarget.options.eslintConfig || findEslintFile(tree, project.root);
+      if (!eslintFile) {
```
Comment (meeroslav) [inline packages/linter/src/generators/init/init-migration.ts:31]: Of config does not exist, we should silently continue migrating other projects

**Review by JamesHenry — APPROVED** [review]
