### PR TITLE
fix(release): support workspace root as a subdirectory of git root

### LINKED ISSUE #27995: Nx release fails to detect changes if the workspace directory is not the monorepo root directory
### Current Behavior

Given a monorepo with a set of packages, each with its own `project.json` file.

The `nx.json` file resides in a repo subdirectory called `typescript`, along with `package.json`

The path to each package is `typescript/packages/<project_name>`

`nx.json` is set up to use Conventional commits and independent packages:

```
    "release": {
        "version": { "conventionalCommits": true },
        "projectsRelationship": "independent"
    }
```

I have created a commit that changes some file belonging to a package, with a "fix:" prefix in the commit header.

When I run `npx nx release version --dry-run` it fails to detect any changes, ie. `🚫 No changes were detected using git history and the conventional commits standard.`

### Expected Behavior

I expect NX release to be able to detect changes if the NX workspace directory is not the root directory of the monorepo

### GitHub Repo

https://github.com/hkfb/webviz-subsurface-components/tree/nx_release

### Steps to Reproduce

1. Clone the repo and check out the `nx_release` tag
2. In the `typescript` directory run `npx nx release version --dry-run  -p subsurface-viewer`

### Nx Report

```shell
Node   : 20.10.0
OS     : linux-x64
npm    : 8.19.4

nx             : 19.2.3
@nx/js         : 19.2.3
@nx/jest       : 19.2.3
@nx/workspace  : 19.2.3
@nx/devkit     : 19.2.3
@nrwl/tao      : 19.2.3
typescript     : 5.4.3
---------------------------------------
Community plugins:
@theunderscorer/nx-semantic-release : 2.11.0
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by shantanu1227**
closed #27995

## Current Behavior

If workspace root is a subdirectory of git root, then running always shows 
> No changes were detected using git history and the conventional commits standard
```
.
├── .git
├── workspace/
│   └── packages
├── docs
└── others
```

## Expected Behavior

Changes made inside the workspace should be considered for release.

## Related Issue(s)

Fixes #27995

### CODE REVIEW

File: packages/nx/src/command-line/release/utils/git.ts [hunk 1]
```diff
@@ -558,3 +564,16 @@ export async function getFirstGitCommit() {
     throw new Error(`Unable to find first commit in git history`);
   }
 }
+
+export async function getGitRoot() {
```
Comment (JamesHenry) [inline packages/nx/src/command-line/release/utils/git.ts:568]:
```suggestion
async function getGitRoot() {
```

File: packages/nx/src/command-line/release/utils/git.ts [hunk 2]
```diff
@@ -2,6 +2,7 @@
  * Special thanks to changelogen for the original inspiration for many of these utilities:
  * https://github.com/unjs/changelogen
  */
+import { relative } from 'path';
```
Comment (JamesHenry) [inline packages/nx/src/command-line/release/utils/git.ts:5]:
```suggestion
import { relative } from 'node:path';
```

File: packages/nx/src/command-line/release/utils/git.ts [hunk 3]
```diff
@@ -124,15 +125,20 @@ export async function getGitDiff(
...
     `--pretty="----%n%s${separator}%h${separator}%an${separator}%ae%n%b"`,
     '--name-status',
-  ]);
+  ];
+  const relativePath = await getWorkspaceRelativePath();
+  if (relativePath) {
+    args.push(`--relative=${relativePath}`);
+  }
+
+  // https://git-scm.com/docs/pretty-formats
```
Comment (JamesHenry) [inline packages/nx/src/command-line/release/utils/git.ts:140]:
```suggestion
```

File: packages/nx/src/command-line/release/utils/git.ts [hunk 4]
```diff
@@ -124,15 +125,20 @@ export async function getGitDiff(
 
   // Use a unique enough separator that we can be relatively certain will not occur within the commit message itself
   const separator = '§§§';
-
-  // https://git-scm.com/docs/pretty-formats
-  const r = await execCommand('git', [
+  const args = [
```
Comment (JamesHenry) [inline packages/nx/src/command-line/release/utils/git.ts:128]:
```suggestion
  // https://git-scm.com/docs/pretty-formats
  const args = [
```

File: packages/nx/src/command-line/release/utils/git.ts [hunk 5]
```diff
@@ -124,15 +125,20 @@ export async function getGitDiff(
...
     '--no-pager',
     'log',
     range,
     `--pretty="----%n%s${separator}%h${separator}%an${separator}%ae%n%b"`,
     '--name-status',
-  ]);
+  ];
+  const relativePath = await getWorkspaceRelativePath();
```
Comment (JamesHenry) [inline packages/nx/src/command-line/release/utils/git.ts:135]:
```suggestion
  // Support cases where the nx workspace root is located at a nested path within the git repo
  const relativePath = await getGitRootRelativePath();
```

File: packages/nx/src/command-line/release/utils/git.ts [hunk 6]
```diff
@@ -558,3 +564,16 @@ export async function getFirstGitCommit() {
...
+    return (await execCommand('git', ['rev-parse', '--show-toplevel'])).trim();
+  } catch (e) {
+    throw new Error('Unable to find git root');
+  }
+}
+
+async function getWorkspaceRelativePath() {
+  const gitRoot = await getGitRoot();
+  return relative(gitRoot, workspaceRoot);
+}
```
Comment (JamesHenry) [inline packages/nx/src/command-line/release/utils/git.ts:579]: The git root is as constant as the workspaceRoot for the lifecycle of the program, let's avoid recomputing this (and running the child process) every time the getGitDiff function is called.

```suggestion
let gitRootRelativePath: string;
async function getGitRootRelativePath() {
  if (!gitRootRelativePath) {
    const gitRoot = await getGitRoot();
    gitRootRelativePath = relative(gitRoot, workspaceRoot);
  }
  return gitRootRelativePath;
}
```

**Review by JamesHenry — CHANGES_REQUESTED** [review]
Thank you! Using `--relative` is a good suggestion

**Comment by JamesHenry** [comment]
I applied my suggestions via the github UI and synced with the latest

**Review by JamesHenry — APPROVED** [review]
