### PR TITLE
fix(core): use version range check for yarn tarball packages

### LINKED ISSUE #17026: Invalid Version error while creating pruned lockfile
### Current Behavior

Hello !

I hope you're having a marvellous day 🌴 

I am experiencing an issue with version resolution whereby package versions get resolved as their '_resolved_' URL instead of the proper semver string. Eventually the URL is pasted to `semver` which chokes on it and the command errors (see below)

I have looked in context at #16886 and decided to play with the `findVersion` function in `yarn-parser.ts` and after returning `snapshot.version` instead of `snapshot.resolved` the Invalid version error disappears down the line but a new problem shows in `findOriginalKeys`.

More investigation is needed I will see to provide more information if I find the time to dig into it further.

Thank you in advance for any help addressing this 🚀 

https://github.com/nrwl/nx/blob/d26f26a98b679c056109325dabce7a0cb757f3a5/packages/nx/src/plugins/js/lock-file/yarn-parser.ts#L144-L150

image

```
 >  NX   An error occured while creating pruned lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   To prevent the build from breaking we are returning the root lock file.

Original error: Invalid Version: https://registry.yarnpkg.com/@octokit/rest/-/rest-19.0.7.tgz#d2e21b4995ab96ae5bfae50b4969da7e04e0bb70

```

### Expected Behavior

Version is resolved properly and the lockfile is generated correctly.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Configure a project to build using `@nx/webpack:webpack` with `generateLockfile` and `generatePackageJson` set to `true`
2. Run `nx build project`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.14.0
   OS     : win32 x64
   yarn   : 1.22.19
   Hasher : Native

   nx                 : 16.1.0
   @nx/js             : 16.1.0
   @nx/jest           : 16.1.0
   @nx/linter         : 16.1.0
   @nx/workspace      : 16.1.0
   @nx/cypress        : 16.1.0
   @nx/detox          : 16.1.0
   @nx/devkit         : 16.1.0
   @nx/esbuild        : 16.1.0
   @nx/eslint-plugin  : 16.1.0
   @nx/expo           : 16.1.0
   @nx/express        : 16.1.0
   @nx/next           : 16.1.0
   @nx/node           : 16.1.0
   @nx/react          : 16.1.0
   @nrwl/tao          : 16.1.0
   @nx/web            : 16.1.0
   @nx/webpack        : 16.1.0
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 3.0.0
```

### Failure Logs

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

At this point I am unable to move to Nx 16.1 as is has seemingly breaking changes having to do with ESM modules.

### PR DESCRIPTION
**Pull request by meeroslav**
## Current Behavior
Yarn parser is comparing version range with snapshot's version using `satisfies` to ensure the version is not a tarball link description. This unfortunately gives false negatives when versions are overridden with `resolves`.

## Expected Behavior
The tarball check should check if given range is a valid version range and disregard the version matching since we do not have that information at this point.

## Related Issue(s)

Fixes #17026

### CODE REVIEW

File: packages/nx/src/plugins/js/lock-file/yarn-parser.ts [hunk 1]
```diff
@@ -2,13 +2,13 @@ import { parseSyml, stringifySyml } from '@yarnpkg/parsers';
...
 import { getHoistedPackageVersion } from './utils/package-json';
 import { ProjectGraphBuilder } from '../../../project-graph/project-graph-builder';
-import { satisfies } from 'semver';
+import { satisfies, Range } from 'semver';
 import { NormalizedPackageJson } from './utils/package-json';
 import {
   ProjectGraph,
   ProjectGraphExternalNode,
 } from '../../../config/project-graph';
-import { fileHasher, hashArray } from '../../../hasher/impl';
```
Comment (meeroslav) [inline packages/nx/src/plugins/js/lock-file/yarn-parser.ts:11]: This import was unused
