### PR TITLE
fix(nextjs): add project deps to package.json when building nextjs apps

### LINKED ISSUE #3062: Next package.json does not include all required dependencies
## Expected Behavior

I create a Next app. This app uses `styled-components` for styling. I run `nx build myapp` build the app. I copy from `dist/apps/myapp` to a separate directory to test that the app is ready to be deployed. When I test the app by running `npm start`, I can run the app by going to `localhost:3000`. 

## Current Behavior

I get an error: `Error: Cannot find module 'styled-components'` when going to `localhost:3000`. 

When running the app locally using `nx serve myapp`, everything works as expected. 

## Failure Information (for bugs)

Looking at the generated `package.json`, it looks like `styled-components` are a missing dependency. 

```
{
  "name": "myapp",
  "version": "0.0.1",
  "scripts": {
    "start": "next start"
  },
  "dependencies": {
    "next": "9.3.3",
    "react": "16.12.0",
    "react-dom": "16.12.0"
  },
  "devDependencies": {}
}
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Generate a Next app that uses styled-components.
2. Build the app.
3. Move the built app to a different directory and run it. 

### Context

Please provide any relevant information about your setup:

```
  @nrwl/angular : Not Found
  @nrwl/cli : 9.3.0
  @nrwl/cypress : 9.3.0
  @nrwl/eslint-plugin-nx : 9.3.0
  @nrwl/express : Not Found
  @nrwl/jest : 9.3.0
  @nrwl/linter : 9.3.0
  @nrwl/nest : 9.3.0
  @nrwl/next : 9.3.0
  @nrwl/node : 9.3.0
  @nrwl/react : 9.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.3.0
  @nrwl/web : 9.3.0
  @nrwl/workspace : 9.3.0
  typescript : 3.8.3
```
`"styled-components": "5.0.1"`

### Failure Logs

```
Error: Cannot find module 'styled-components'
Require stack:
- /Users/olya777/Projects/myapp/.next/server/static/_qz_WuDsra8FGG8QTZZg3/pages/_document.js
- /Users/olya777/Projects/myapp/node_modules/next/dist/next-server/server/load-components.js
- /Users/olya777/Projects/myapp/node_modules/next/dist/next-server/server/api-utils.js
- /Users/olya777/Projects/myapp/node_modules/next/dist/next-server/server/next-server.js
- /Users/olya777/Projects/myapp/node_modules/next/dist/server/next.js
- /Users/olya777/Projects/myapp/node_modules/next/dist/server/lib/start-server.js
- /Users/olya777/Projects/myapp/node_modules/next/dist/cli/next-start.js
- /Users/olya777/Projects/myapp/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.Dtiu (/Users/olya777/Projects/myapp/.next/server/static/_qz_WuDsra8FGG8QTZZg3/pages/_document.js:780:18)
    at __webpack_require__ (/Users/olya777/Projects/myapp/.next/server/static/_qz_WuDsra8FGG8QTZZg3/pages/_document.js:23:31)
    at Module.Y7Z2 (/Users/olya777/Projects/myapp/.next/server/static/_qz_WuDsra8FGG8QTZZg3/pages/_document.js:917:75)
    at __webpack_require__ (/Users/olya777/Projects/myapp/.next/server/static/_qz_WuDsra8FGG8QTZZg3/pages/_document.js:23:31)
    at Object.1 (/Users/olya777/Projects/myapp/.next/server/static/_qz_WuDsra8FGG8QTZZg3/pages/_document.js:99:18)
    at __webpack_require__ (/Users/olya777/Projects/myapp/.next/server/static/_qz_WuDsra8FGG8QTZZg3/pages/_document.js:23:31) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/olya777/Projects/myapp/.next/server/static/_qz_WuDsra8FGG8QTZZg3/pages/_document.js',
    '/Users/olya777/Projects/myapp/node_modules/next/dist/next-server/server/load-components.js',
    '/Users/olya777/Projects/myapp/node_modules/next/dist/next-server/server/api-utils.js',
    '/Users/olya777/Projects/myapp/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/olya777/Projects/myapp/node_modules/next/dist/server/next.js',
    '/Users/olya777/Projects/myapp/node_modules/next/dist/server/lib/start-server.js',
    '/Users/olya777/Projects/myapp/node_modules/next/dist/cli/next-start.js',
    '/Users/olya777/Projects/myapp/node_modules/next/dist/bin/next'
  ]
}
```

### PR DESCRIPTION
**Pull request by BigAB**
The fix makes the nextjs builder add the project dependencies to the dist package.json file

## Current Behavior
The nextjs project get's built with only next, react and react-dom in the dist `package.json` file, and then fails after deployment because of the missing packages.

## Expected Behavior
The application dependencies are added to the dist `package.json`

## Related Issue(s)

Fixes #3062

### CODE REVIEW

**Comment by BigAB** [comment]
Question, is there anyway to separate out the `devDependencies` from a project in the `ProjectGraph`?

**Comment by jaysoo** [comment]
@BigAB We currently don't but we can extend the finder to store this info. https://github.com/nrwl/nx/blob/master/packages/workspace/src/core/project-graph/build-nodes/npm-packages.ts#L18-L22

File: packages/next/src/builders/build/lib/create-package-json.ts [hunk 1]
```diff
@@ -2,13 +2,41 @@ import { BuilderContext } from '@angular-devkit/architect';
...
+
 export async function createPackageJson(
   options: NextBuildBuilderOptions,
   context: BuilderContext
 ) {
+  const graph = createProjectGraph();
+  const projectDependencies = graph.dependencies[context.target.project].map(
+    (dep) => dep.target
+  );
+  const projectNpmDependencies = Object.values(graph.nodes).reduce(
```
Comment (FrozenPandaz) [inline packages/next/src/builders/build/lib/create-package-json.ts:24]: I think it's simpler and more performant to keep mapping the above array to get to the npm projects?

```ts
const projectDependencies = graph.dependencies[context.target.project]
  .map(dep => dep.target)
  .map(nodeName => graph.nodes[nodeName])
  .filter(node => node.type === 'npm')
  .reduce(...)
```

File: packages/next/src/builders/build/lib/create-package-json.ts [hunk 2]
```diff
@@ -28,10 +56,19 @@ export async function createPackageJson(
...
+      ...projectNpmDependencies.deps,
+    },
+    devDependencies: {
+      ...projectNpmDependencies.devDeps,
     },
-    devDependencies: {},
   };
 
+  if (Object.keys(projectNpmDependencies.peerDeps).length > 0) {
+    outPackageJson.peerDependencies = {
```
Comment (FrozenPandaz) [inline packages/next/src/builders/build/lib/create-package-json.ts:67]: Are there any cases where the `peerDependencies` for 1 application should not be the `peerDependencies` for another application?

File: packages/next/src/builders/build/lib/create-package-json.ts [hunk 3]
```diff
@@ -2,13 +2,41 @@ import { BuilderContext } from '@angular-devkit/architect';
...
   context: BuilderContext
 ) {
+  const graph = createProjectGraph();
+  const projectDependencies = graph.dependencies[context.target.project].map(
+    (dep) => dep.target
+  );
+  const projectNpmDependencies = Object.values(graph.nodes).reduce(
+    (acc, node) => {
+      if (node.type === 'npm' && projectDependencies.includes(node.name)) {
+        if (node.data.isDevDependency) {
```
Comment (jaysoo) [inline packages/next/src/builders/build/lib/create-package-json.ts:27]: I think we can ignore dev and peer dependencies. Peer shouldn't be used for apps so we should just ignore.

Dev dependencies should all go into the root `package.json` so I think they can be ignored as well. Unless there's something I am missing.

**Review by jaysoo — CHANGES_REQUESTED** [review]

**Comment by BigAB** [comment]
After some discussion, we decided to go with the simpler solution of providing all dependencies to the app, even if the app doesn't specifically use those dependencies.

File: packages/next/src/builders/build/lib/create-package-json.ts [hunk 4]
```diff
@@ -25,6 +25,7 @@ export async function createPackageJson(
       start: 'next start',
     },
     dependencies: {
+      ...rootPackageJson.dependencies,
       next: allWorkspaceDeps.next,
```
Comment (jaysoo) [inline packages/next/src/builders/build/lib/create-package-json.ts:29]: We can remove these deps here since they should already be in the root `package.json`. :)

**Comment by mvdpoel** [comment]
waiting for this one! 👼

**Review by jaysoo — APPROVED** [review]
