### PR TITLE
fix(testing) generated jest ts configs mismatch

### LINKED ISSUE #7263: Mismatch between generated jest config test name pattern and Typescript configs
## Current Behavior
When generating a new Nest project or lib, the generated jest.config and tsconfig.json do not agree on what the naming format for test files should be.
The jest.config will pick up any files ending in either `test.ts` or `spec.ts` as seen here:
https://github.com/nrwl/nx/blob/master/packages/jest/preset/jest-preset.ts#L2

However, the generated tsconfig.spec.json only allow test files to end in `spec.ts`:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "module": "commonjs",
    "types": ["jest", "node"]
  },
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

## Expected Behavior
I think these two systems should agree on what tests should be called. Personally I use `.test.ts` and would prefer to have the option for either spec or test. Either way, I think it should be consistent between the two configs.

## Steps to Reproduce
Generate a new NestJs project
Create a test file ending in `.test.ts`
Observe that it does not have correct typings for Jest
Modify `tsconfig.spec` and `tsconfig.app` to include / exclude `.test.ts` files
Run Jest and observe that it is picking up the .test file.

### Environment

```
  Node : 14.15.0
  OS   : darwin x64
  yarn : 3.0.2

  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : 12.9.0
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
  ```

### PR DESCRIPTION
**Pull request by barbados-clemens**
## Current Behavior
`tsconfig.spec.json` only includes `*.spec.ts` files, therefore ignoring any files with marked as `*.test.ts`

## Expected Behavior
`.test.{ts|js|tsx|jsx}` are includes in the `tsconfig.spec.json` file and are ignored in any `tsconfig.{lib|app}.json` created by other generators

## Related Issue(s)

Fixes #7263 

Note: this issue also fixes a problem where the jest.impl.ts tests would fail locally because of a file system issue of `/root` not existing on the local system. 

TODO:
- [x] Migrations

### CODE REVIEW

**Review by Coly010 — APPROVED** [review]
Looks fine from an Angular perspective

**Review by Cammisuli — APPROVED** [review]

File: packages/jest/src/migrations/update-13-1-2/update-tsconfigs-for-tests.ts [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+
+      switch (projectConfig.projectType) {
+        case 'library':
+          const tsConfigLibPath = joinPathFragments(
+            projectConfig.root,
+            'tsconfig.lib.json'
+          );
+          updateTsConfigExclude(tree, tsConfigLibPath);
+          break;
+        case 'application':
```
Comment (FrozenPandaz) [inline packages/jest/src/migrations/update-13-1-2/update-tsconfigs-for-tests.ts:38]: There's going to be a bunch of `applications` that do not have `tsconfig.app.json` because it is an e2e project. Could you please account for this in your logic or... don't `logger.error` when you can't find a tsconfig?
