### PR TITLE
fix(storybook): only match exact component name for Storybook

### LINKED ISSUE #7175: Component Object Name Bug
## Current Behavior
We have component object files (think page objects but for components) that have a declaration of <componentName>Object. This line of code in node_modules\@nrwl\angular\src\generators\stories\lib\component-info.js 

```if (content.indexOf(`class ${componentName}`) > -1) { ```
matches those files even though they aren't actually components and throws this error: 

**No @Component decorator in libs/some/dashboard/src/lib/some-panel/some-panel.co.ts.** 

## Possible Fixes
There should be a space in the "indexOf" code after the component name in order to make sure matches don't happen against the wrong file: 

```if (content.indexOf(`class ${componentName} `) > -1) { ```

## Expected Behavior

We want this fix to properly generate a Cypress e2e folder without throwing an error for things that are not actually components. 

## Steps to Reproduce

npx nx g @nrwl/angular:storybook-configuration some-dashboard --configureCypress --generateCypressSpecs --generateStories 

Where some-dashboard includes a file with `export class AbcComponentOneTwoThree {}` and another file includes an actual component named AbcComponent 

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

Node : 12.22.0 

OS : Windows 10 x64  
npm : 6.14.11 

nx : Not Found 
@nrwl/angular : 12.5.7 
@nrwl/cli : 12.5.7 
@nrwl/cypress : 12.5.7 
@nrwl/devkit : Not Found 
@nrwl/eslint-plugin-nx : 12.5.7 
@nrwl/express : 12.5.7 
@nrwl/jest : 12.5.7 
@nrwl/linter : Not Found 
@nrwl/nest : 12.5.7 
@nrwl/next : Not Found 
@nrwl/node : 12.5.7 
@nrwl/react : Not Found 
@nrwl/schematics : Not Found 
@nrwl/tao : 12.5.7 
@nrwl/web : Not Found 
@nrwl/workspace : 12.5.7 
@nrwl/storybook : 12.5.7 
@nrwl/gatsby : Not Found 
typescript : 4.2.4

### PR DESCRIPTION
**Pull request by mandarini**
ISSUES CLOSED: #7175

## Current Behavior
In Storybook/Angular, when looking for component classes, it matches both of the following:

```
class KaterinasComponent {
   ...
```
and

```
class KaterinasComponentSomeOtherThing {
   ...
```

## Expected Behavior
Only match exact name of component.

## Related Issue(s)
#7175

Fixes #
#7175

### CODE REVIEW

**Review by juristr — CHANGES_REQUESTED** [review]

File: packages/angular/src/generators/stories/lib/component-info.ts [hunk 1]
```diff
@@ -125,7 +125,15 @@ function getComponentInfoFromDir(
...
-      if (content.indexOf(`class ${componentName}`) > -1) {
+      const classAndComponentRegex = new RegExp(
+        `\\bclass ${componentName}\\b`,
+        'g'
+      );
+      if (
+        content.indexOf(`class ${componentName}`) > -1 &&
+        content.match(classAndComponentRegex)
+      ) {
+        console.log(`Found ${classAndComponentRegex} in ${candidateFile}`);
```
Comment (mandarini) [inline packages/angular/src/generators/stories/lib/component-info.ts:136]: Remove this console.log

Comment (mandarini) [reply packages/angular/src/generators/stories/lib/component-info.ts:136]: Done

File: packages/angular/src/generators/stories/lib/component-info.ts [hunk 2]
```diff
@@ -125,7 +125,15 @@ function getComponentInfoFromDir(
   for (const candidateFile of componentImportPathChildren) {
     if (candidateFile.endsWith('.ts')) {
       const content = tree.read(candidateFile, 'utf-8');
-      if (content.indexOf(`class ${componentName}`) > -1) {
+      const classAndComponentRegex = new RegExp(
```
[the remark this answers is not in the document]
Comment (mandarini) [reply packages/angular/src/generators/stories/lib/component-info.ts:128]: We have the component exact names from parsing the NgModule. Let's keep it like that ,maybe, and once we have the script that takes the import paths from index.js we can use that?

**Review by juristr — APPROVED** [review]
LGTM 👍
