### PR TITLE
fix(js): ignore dependencies from non-index root files for create-package-json

### LINKED ISSUE #17905: Builder helper files (vite.config.ts etc.) influence the package dependencies on create package json
### Current Behavior

The executor used for the specified build target causes the `@nx/dependency-checks` ESLint rule to output false positives.

### Expected Behavior

The executor used to build a library should not cause any peer dependencies to be added to the library's `package.json` file.

### GitHub Repo

https://github.com/LayZeeDK/nx-dependency-checks-executor-dependency-issue

### Steps to Reproduce

1. Configure the `@nx/dependency-checks` ESLint rule for a publishable library.
    project.json:
    ```json
    {
      "targets": [
        "lint": {
          "executor": "@nx/linter:eslint",
          "outputs": ["{options.outputFile}"],
          "options": {
            "lintFilePatterns": [
              "libs/angular-design-system/**/*.ts",
              "libs/angular-design-system/**/*.html",
              "libs/angular-design-system/package.json",
              "libs/angular-design-system/project.json"
            ]
          }
        }
      ]
    }
    ```
    .eslintrc.json:
    ```json
    {
      "overrides": [
        {
          "files": ["*.json"],
          "parser": "jsonc-eslint-parser",
          "rules": {
            "@nx/dependency-checks": [
              "error",
              {
                "buildTargets": ["build"],
                "checkMissingDependencies": true,
                "checkObsoleteDependencies": true,
                "checkVersionMismatches": true,
                "ignoredDependencies": []
              }
            ]
          }
        }
      ]
    }
    ```
2. Run a lint task
    ```shell
    nx run-many --targets=lint
    ```

### Nx Report

```shell
Node   : 18.16.1
   OS     : win32-x64
   npm    : 9.5.1
   
   nx                 : 16.5.0-beta.2
   @nx/js             : 16.5.0-beta.2
   @nx/jest           : 16.5.0-beta.2
   @nx/linter         : 16.5.0-beta.2
   @nx/workspace      : 16.5.0-beta.2
   @nx/angular        : 16.5.0-beta.2
   @nx/cypress        : 16.5.0-beta.2
   @nx/devkit         : 16.5.0-beta.2
   @nx/eslint-plugin  : 16.5.0-beta.2
   @nx/react          : 16.5.0-beta.2
   @nrwl/tao          : 16.5.0-beta.2
   @nx/vite           : 16.5.0-beta.2
   @nx/web            : 16.5.0-beta.2
   @nx/webpack        : 16.5.0-beta.2
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
         @myorg/angular-design-system
         @myorg/react-design-system
```


### Failure Logs

```shell
√  nx run angular-app:lint  [existing outputs match the cache, left as is]
    √  nx run angular-app-e2e:lint  [existing outputs match the cache, left as is]                                              

    ×  nx run angular-design-system:lint
       Linting "angular-design-system"...
=============ing target lint for 4 projects

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
    ⠏    nx run angular-design-system:lint
You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0

YOUR TYPESCRIPT VERSION: 5.1.6

Please only submit bug reports when using the officially supported version.

=============

C:\projects\github\LayZeeDK\nx-dependency-checks-executor-dependency-issue\libs\angular-design-system\package.json
  4:3  error  The "angular-design-system" uses the package "jest-preset-angular", but it is missing from the project's "package.json"                @nx/dependency-checks
  4:3  error  The "angular-design-system" uses the package "@angular-devkit/build-angular", but it is missing from the project's "package.json"      @nx/dependency-checks
  4:3  error  The "angular-design-system" uses the package "@angular/compiler-cli", but it is missing from the project's "package.json"              @nx/dependency-checks
  4:3  error  The "angular-design-system" uses the package "@angular/compiler", but it is missing from the project's "package.json"                  @nx/dependency-checks
  4:3  error  The "angular-design-system" uses the package "rxjs", but it is missing from the project's "package.json"          
                     @nx/dependency-checks
  4:3  error  The "angular-design-system" uses the package "zone.js", but it is missing from the project's "package.json"       
                     @nx/dependency-checks
  4:3  error  The "angular-design-system" uses the package "typescript", but it is missing from the project's "package.json"    
                     @nx/dependency-checks
  4:3  error  The "angular-design-system" uses the package "jest", but it is missing from the project's "package.json"          
                     @nx/dependency-checks
  4:3  error  The "angular-design-system" uses the package "jest-environment-jsdom", but it is missing from the project's "package.json"             @nx/dependency-checks
  4:3  error  The "angular-design-system" uses the package "ng-packagr", but it is missing from the project's "package.json"    
                     @nx/dependency-checks
  4:3  error  The "angular-design-system" uses the package "@angular/platform-browser-dynamic", but it is missing from the project's "package.json"  @nx/dependency-checks
  4:3  error  The "angular-design-system" uses the package "@angular/platform-browser", but it is missing from the project's "package.json"          @nx/dependency-checks
  4:3  error  The "angular-design-system" uses the package "@angular/animations", but it is missing from the project's "package.json"                @nx/dependency-checks

✖ 13 problems (13 errors, 0 warnings)
  13 errors and 0 warnings potentially fixable with the `--fix` option.

Lint errors found in the listed files.




    ×  nx run react-design-system:lint
       Linting "react-design-system"...
=============ing target lint for 4 projects

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
    ⠹    nx run react-design-system:lint
You may find that it works just fine, or you may not.
    √    2/3 succeeded [2 read from cache]
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0

YOUR TYPESCRIPT VERSION: 5.1.6

Please only submit bug reports when using the officially supported version.

=============

C:\projects\github\LayZeeDK\nx-dependency-checks-executor-dependency-issue\libs\react-design-system\package.json
  12:3  error  The "react-design-system" uses the package "vite", but it is missing from the project's "package.json"           
           @nx/dependency-checks
  12:3  error  The "react-design-system" uses the package "@vitejs/plugin-react-swc", but it is missing from the project's "package.json"  @nx/dependency-checks
  12:3  error  The "react-design-system" uses the package "vite-tsconfig-paths", but it is missing from the project's "package.json"       @nx/dependency-checks
  12:3  error  The "react-design-system" uses the package "vite-plugin-dts", but it is missing from the project's "package.json"
           @nx/dependency-checks
  12:3  error  The "react-design-system" uses the package "@types/node", but it is missing from the project's "package.json"    
           @nx/dependency-checks
  12:3  error  The "react-design-system" uses the package "less", but it is missing from the project's "package.json"           
           @nx/dependency-checks
  12:3  error  The "react-design-system" uses the package "sass", but it is missing from the project's "package.json"           
           @nx/dependency-checks
  12:3  error  The "react-design-system" uses the package "stylus", but it is missing from the project's "package.json"         
           @nx/dependency-checks
  12:3  error  The "react-design-system" uses the package "terser", but it is missing from the project's "package.json"         
           @nx/dependency-checks

✖ 9 problems (9 errors, 0 warnings)
  9 errors and 0 warnings potentially fixable with the `--fix` option.

Lint errors found in the listed files.



                                                                                                                                
 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 
                                                                                                                                
 >  NX   Ran target lint for 4 projects (2s)                                                                                    
                                                                                                                                
    √    2/4 succeeded [2 read from cache]                                                                                      
                                                                                                                                
    ×    2/4 targets failed, including the following:                                                                           
         - nx run angular-design-system:lint
         - nx run react-design-system:lint
```


### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Assign to @meeroslav.

### PR DESCRIPTION
**Pull request by meeroslav**
## Current Behavior
The package json generation (and `dependency checks` linter rule) reads all the `production` files' dependencies, including files relevant only at the compile time - vite.config.ts, webpack.config.js etc. which includes dev packages in the resulting package.json

## Expected Behavior
Only non-dev dependencies should be taken into account when constructing dependencies list if `isProduction` is set.

## Related Issue(s)

Fixes #17905

### CODE REVIEW

File: packages/nx/src/plugins/js/package-json/create-package-json.ts [hunk 1]
```diff
@@ -222,6 +223,17 @@ export function findProjectsNpmDependencies(
   return npmDeps;
 }
 
+// this function checks if the file path in in the root and not index.ts file
+// these files are likely configuration files
+function isIndexOrNonRoot(filePath: string, root: string): boolean {
+  if (filePath.slice(root.length + 1).includes('/')) {
+    return true;
+  }
+  return ['index.ts', 'index.js', 'index.jsx', 'index.tsx'].some(
```
Comment (LayZeeDK) [inline packages/nx/src/plugins/js/package-json/create-package-json.ts:232]: question: What if the entry point is named `main.ts`, `public_api.ts` or `public-api.ts`? Shouldn't this information be read from a configuration file like `ng-package.json#lib.entryFile` or `vite.config.ts#build.entry`?

Comment (meeroslav) [reply packages/nx/src/plugins/js/package-json/create-package-json.ts:232]: That's a valid question. Unfortunately, the possibilities are unknown - one can use Vite, Webpack, Rollup, NgPackgr, or any known and unknown builder/bundler. We don't have a way to know how that configuration might expose the `main` file.

That being said, I considered adding `main.js/ts` to the list.

The `public api` files generally only reexport functionality living in a subfolder. 

Although this solution is again not perfect and would not work in 100% of the cases, we believe it's more accurate than the existing one, and being used in the linter rule it's not critical if it's off by a few deps.

The alternative would be to split buildtime and runtime file sets, but that would make things very complicated and would require major changes in our graph handling.

File: docs/generated/devkit/nx_devkit.md [hunk 2]
```diff
@@ -311,6 +312,14 @@ A plugin for Nx
 
 ---
 
+### PackageJson
```
Comment (FrozenPandaz) [inline docs/generated/devkit/nx_devkit.md:315]: Don't expose this.

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]

**Review by AgentEnder — APPROVED** [review]

File: packages/nx/src/plugins/js/package-json/create-package-json.ts (hunk 1 above)
Comment (LayZeeDK) [reply packages/nx/src/plugins/js/package-json/create-package-json.ts]: `public-api.ts` is the default entry point generated by Angular CLI (`@schematics/angular:library`).
