### PR TITLE
fix(core): fix custom workspace-generator options

### LINKED ISSUE #12677: Local workspace-generator does not work after update to nx@15.0.0
## Current Behavior
`npx nx workspace-generator <name> <options>` fails with 
> Not enough non-option arguments: got 0, need at least 1

The error happens due to a recent change in `nx`, where `(option)` is appended to the command if there are options specified.

Converting https://github.com/nrwl/nx/blob/master/packages/nx/src/command-line/nx-commands.ts#L841 
from `if(options.length)` to `if(!options.length)` seems to fix the issue.
I can try creating a PR if that helps.

## Expected Behavior
`npx nx workspace-generator <name> <options>` should launch the generator and generate the required code.

## Steps to Reproduce
Reproduction in https://github.com/bridzius/workspace-generator-repro
Clone, `npm ci`, run `npx nx workspace-generator generato --all`. Should run the generator, but fails with said error.

### Failure Logs
```
npx nx workspace-generator generato --all
nx workspace-generator generato [name] (options)

Positionals:
  name  Library name                                                                                              [string]

Options:
  --help     Show help                                                                                           [boolean]
  --version  Show version number                                                                                 [boolean]
  --all      All for testing                                                                                     [boolean]

Find more information and examples at https://nx.dev/nx/workspace-generator

Not enough non-option arguments: got 0, need at least 1
```

### Environment
```
   Node : 16.17.1
   OS   : darwin arm64
   npm  : 8.15.0
   nx : 15.0.0
   @nrwl/angular : 15.0.0
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### PR DESCRIPTION
**Pull request by Roozenboom**
After PR #12258 the custom options for local workspace-generators did not work anymore because if any
options are defined in the schema it added (options) to the command and if no properties were
defined it also throwed an error

ISSUES CLOSED: #12677

## Related Issue(s)

Fixes #

### CODE REVIEW

File: packages/nx/src/command-line/nx-commands.ts [hunk 1]
```diff
@@ -810,37 +810,35 @@ async function withCustomGeneratorOptions(
...
-          describe: prop.description,
-          type: prop.type,
-          default: prop.default,
-          choices: prop.enum,
-        },
-      });
-      if (isPositionalProperty(prop)) {
-        positionals.push({
+  if (schema.properties) {
+    Object.entries(schema.properties as WorkspaceGeneratorProperties).forEach(
```
Comment (AgentEnder) [inline packages/nx/src/command-line/nx-commands.ts:814]: Rather than wrapping whole block in if statement, can we do `schema.properties ?? {}`?

**Review by AgentEnder — CHANGES_REQUESTED** [review]

**Comment by AgentEnder** [comment]
Since #12955 included most of the fix, can this PR be updated to only add the null safety?

**Comment by Roozenboom** [comment]
PR is updated to only add the null safety, because if prettier the change looks bigger than it actually is :)

**Review by AgentEnder — APPROVED** [review]
