### PR TITLE
fix(storybook): generating stories without an existing e2e project

### LINKED ISSUE #5743: Error creating stories for libraries without e2e
## Steps to Reproduce
1. Create a storybook configuration without e2e:
`$ ng g @nrwl/angular:storybook-configuration libraryXyz`
✔ Configure a cypress e2e app to run against the storybook instance? (Y/n) · false
✔ Automatically generate *.stories.ts files for components declared in this project? (Y/n) · false
✔ Automatically generate *.spec.ts files in the cypress e2e app generated by the cypress-configure generator? (Y/n) · false

2. generate stories:
`$ ng g @nrwl/angular:stories --name=libraryXyz`

## Current Behavior
Error: Cannot find project 'libraryXyz-e2e'

## Expected Behavior
Stories will be created

### Environment
  Node : 14.17.0
  OS   : linux x64 (Ubuntu 20.04)
  npm  : 6.14.13
  
  @nrwl/angular : 12.1.1
  @nrwl/cli : 12.1.1
  @nrwl/cypress : 12.1.1
  @nrwl/devkit : 12.1.1
  @nrwl/eslint-plugin-nx : 12.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.1.1
  @nrwl/linter : 12.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.1.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.1.1
  @nrwl/storybook : 12.3.4
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

### PR DESCRIPTION
**Pull request by mandarini**
- I fixed the `stories` generator schema for both React and Angular to remove the `generateCypressSpecs: true` by default, which sort of stealthily broke the `stories` generator for Angular
- I added the prompt to the `stories` Angular schematic, just to keep consistency between the Angular and the React `stories` schematic/generator
- In case a user accidentally says `generateCypressSpecs: true` and they don't have an `e2e` project for that project, then don't fail. Check before firing the `generate-cypress-...` schematic if there is indeed an existing `cypress` project.
- Another side-fix: If you say "don't generate an e2e project" for a library when adding Storybook, it would get confused and would show a message saying "e2e project exists so I will not create one". I fixed that.

ISSUES CLOSED: #5743

Fixes #5743

### CODE REVIEW

File: packages/angular/src/schematics/stories/stories.ts [hunk 1]
```diff
@@ -215,6 +231,12 @@ export function createAllStories(
           }
         });
 
+        if (generateCypressSpecs && !e2eProject) {
+          context.logger.info(
+            'There was no e2e project configured, so cypress specs will not be generated.'
```
Comment (juristr) [inline packages/angular/src/schematics/stories/stories.ts:236]: Can we add the `e2eProject` to the console output? Like 

```
context.logger.info(
  `There was no e2e project "${e2eProjectName}" found, so cypress specs will not be generated. Pass "--cypressProject" to specify a different e2e project name`
)
```

Or something similar. This should help people understand what went wrong if they forgot the flag or something.

File: packages/react/src/generators/stories/stories.ts [hunk 2]
```diff
@@ -79,6 +80,15 @@ export async function createAllStories(
     }
   });
 
+  const e2eProject =
+    projects.get(cypressProject) || projects.get(`${projectName}-e2e`);
+
+  if (generateCypressSpecs && !e2eProject) {
+    logger.info(
+      'There was no e2e project configured, so cypress specs will not be generated.'
```
Comment (juristr) [inline packages/react/src/generators/stories/stories.ts:88]: Same as above

**Review by juristr — CHANGES_REQUESTED** [review]

File: packages/angular/src/schematics/stories/stories.ts (hunk 1 above)
Comment (mandarini) [reply packages/angular/src/schematics/stories/stories.ts:236]: Oh sure!!

File: packages/angular/src/schematics/stories/stories.ts [hunk 3]
```diff
@@ -10,13 +10,15 @@ import {
 import { SyntaxKind } from 'typescript';
 import { getDecoratorMetadata, getTsSourceFile } from '../../utils/ast-utils';
 import { projectRootPath } from '@nrwl/workspace/src/utils/project-type';
-import { findNodes } from '@nrwl/workspace/src/utils/ast-utils';
+import {
+  findNodes,
+  getProjectConfig,
+} from '@nrwl/workspace/src/utils/ast-utils';
```
Comment (juristr) [inline packages/angular/src/schematics/stories/stories.ts:16]: sorry didn't catch these the first round. Can we import them from `@nrwl/workspace` directly rather than having the deep import? I think they're both exposed

Comment (mandarini) [reply packages/angular/src/schematics/stories/stories.ts:16]: Ohh sure!

**Review by juristr — APPROVED** [review]
