### PR TITLE
fix(core): batch calls to git hash-object to avoid E2BIG error

### LINKED ISSUE #8646: Jest & lint fails with the following ERROR: NX   ERROR  spawn E2BIG
Both my jest & lint fails with the following ERROR: NX   ERROR  spawn E2BIG

this is happening only on the CI pipeline. but the same works well in my local machine. 

```
$ yarn affected:test 

yarn run v1.22.5
$ ./node_modules/.bin/nx affected:test --base=origin/test-code --parallel --detectOpenHandles --forceExit
>  NX   ERROR  spawn E2BIG
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
We hash all files at once, using `git hash-object ...allFiles`, resulting in an E2BIG error when passing too many files.

## Expected Behavior
We batch these calls, avoiding the E2BIG error.  Actual limits vary heavily based on host computer, but 4000 seems safe on non-windows machines. See the result table here: https://www.in-ulm.de/~mascheck/various/argmax/#results. For windows, rather than a limit on the number of arguments, it is a limit on the overall commands length. This limit results in a smaller set, which I believe should be safe at 500.

## Related Issue(s)

Fixes #8646

### CODE REVIEW

File: packages/workspace/src/core/hasher/git-hasher.ts [hunk 1]
```diff
@@ -6,6 +6,59 @@ export async function getGitHashForFiles(
...
+    // the overall comand, rather than the number of individual
+    // arguments. Since file paths are large and rather variable,
+    // we use a smaller batchSize.
+    const batchSize = process.platform === 'win32' ? 500 : 4000;
+    for (
+      let startIndex = 0;
+      startIndex < filesToHash.length;
+      startIndex += batchSize
+    ) {
+      const batch = await getGitHashForBatch(
```
Comment (sorin-davidoi) [inline packages/workspace/src/core/hasher/git-hasher.ts:26]: Could we use `Promise.all` instead of a for loop to parallelize the hashing?

**Comment by clementguillot** [comment]
Hello, any news about this PR? The issue it tries to fix is highly blocking when upgrading to the latest Nx version.
In our case, we build apps inside a Docker container and `.dockerignore` creates every time too many git differences.
