### PR TITLE
fix(angular): adjust ngcc postinstall command

### LINKED ISSUE #2601: Not able to enable ivy on Storybook
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Support ivy on storybook.

## Current Behavior

Ivy is not enabled for storybook projects.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone this repository `https://github.com/maxigimenez/nx-angular-storybook`
2. Run `npm install`
3. Run `npx ng run my-lib:storybook`
4. Inspect angular element and run `$0.__ngContext__` in the browser console, will return `undefined` but when ivy is enable it returns more information.

### Context

Please provide any relevant information about your setup:

- Using latests angular
- Tried with latests storybook and also with `next` branch of storybok

Use the repository mentioned above to fully reproduce the issue.

## Other
I forked storybook and run their `angular-cli` project with the latest version of angular and work as expected.

### PR DESCRIPTION
**Pull request by juristr**
## Current Behavior

Nx adds the following `postinstall` command:

```
ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points
```

This causes some libraries such as Jest and Storybook to not run with Ivy but rather use ViewEngine.

For instance, omitting `--create-ivy-entry-points` fixes the Storybook issue of not running in Ivy mode. Jests still apparently uses ViewEngine though.

When also omitting `--first-only`, then also Jest uses Ivy.

## Expected Behavior

Storybook as well as Jest should use Ivy just as the application itself does to prevent a different behavior when running a component inside a test case / storybook setup.

## Details

The command line args are processed being [taken here](https://github.com/angular/angular-cli/blob/eb313f7dc25bf99813452ce0ed8c9e5120d16a62/packages/ngtools/webpack/src/ngcc_processor.ts#L130-L144) and forwarded to the ngcc which lives in the Angular repo.

Some attempt to explain the params:

- `--create-ivy-entry-points`  
Creates dedicated Ivy compiled entry points that can be used to execute the library in "Ivy mode". Omitting this compiles the existing files to Ivy and replaces them. That might cause issues if you want to use ViewEngine with the given package as the ViewEngine code would no more be there.

Using the `--create-ivy-entry-points` is explicitly discouraged by the [Angular docs](https://angular.io/guide/ivy#ivy-and-universalapp-shell) when using SSR or App Shell.

- `--first-only` - transforms only the first format (main, module,...)

## Migration

While we could totally migrate the postinstall arguments I prefer not to as it might break people's codebase. Tests that passed easily with ViewEngine might no more pass with Ivy as it is stricter in some scenarios. It would definitely unveil inappropriate HTML bindings etc, but still potentially break a lot of Jest tests.

## Related Issue(s)

Fixes #2601 #2752 #2667

### CODE REVIEW

File: packages/angular/src/schematics/init/init.ts [hunk 1]
```diff
@@ -153,8 +153,7 @@ export function setDefaults(options: Schema): Rule {
 function addPostinstall(): Rule {
   return updateJsonInTree('package.json', (json, context) => {
     json.scripts = json.scripts || {};
-    const command =
-      'ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points';
```
Comment (FrozenPandaz) [inline packages/angular/src/schematics/init/init.ts:157]: Please make sure to check how this changes how long this takes to execute on repos with many dependencies.

We may want to only remove the `--create-ivy-entry-points`. I passed the other flags to try and keep the execution time down since this happens after every install.

Comment (juristr) [reply packages/angular/src/schematics/init/init.ts:157]: yep, I'm exactly currently testing those things. I just have to find out why Jest tests still don't use Ivy when I leave the `--properties ...` in.

Comment (juristr) [reply packages/angular/src/schematics/init/init.ts:152]: So this is interesting:

- `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`: Jest & Storybook use ViewEngine
- `ngcc --properties es2015 browser module main --first-only`: Jest runs in ViewEngine, Storybook runs in Ivy
- `ngcc --properties es2015 browser module main`: Jest and Storybook run in Ivy mode

🤔

Comment (ahnpnl) [reply packages/angular/src/schematics/init/init.ts:152]: If you pass `--first-only`, it won't generate `umd` bundles which are required for Jest to work with Ivy

**Review by FrozenPandaz — APPROVED** [review]
