### PR TITLE
fix(core): handle empty root path in angular.json

### LINKED ISSUE #7008: Dep graph does not work correctly if application has root as "" in angular.json
## Current Behavior

nx dep-graph is wrong in default angular project structure

## Steps to Reproduce

- create angular cli app starting with letter z, where app has `root: ""` in angular.json
- migrate it to nx preserving the layout
- generate a library starting with letter a, the projects in angular.json will get sorted alphabetically and app will move down

## Cause of the issue
Issue is in https://github.com/nrwl/nx/blob/ac218c6f46a03591b4088dc092a93d0535d685cc/packages/workspace/src/core/file-graph/project-file-map.ts#L26

If `p.root` is `""`, it will always pass, and all the files will pass this logic

## Solution
```
if (f.file.startsWith(p.root || p.sourceRoot)) {
    fileMap[projectName].push(f);
    seen.add(f.file);
}
```

### PR DESCRIPTION
**Pull request by gmfun**
dep-graph may fail for default angular cli project due to empty root path in angular.json, this MR handles with case by falling back to use sourceRoot

Fixes #7008

### CODE REVIEW

File: packages/workspace/src/core/file-graph/project-file-map.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ export function createProjectFileMap(
         if (seen.has(f.file)) {
           return;
         }
-        if (f.file.startsWith(p.root)) {
+        if (f.file.startsWith(p.root || p.sourceRoot)) {
```
Comment (edbzn) [inline packages/workspace/src/core/file-graph/project-file-map.ts:26]: Would it be safer to use `?? p.sourceRoot` to avoid undesired matching of the root defined as an empty string `""`?

Comment (gmfun) [reply packages/workspace/src/core/file-graph/project-file-map.ts:26]: @edbzn No, that exactly the case that needs to be handled. If p.root is `""`, then this if condition will always be truthy.

Comment (edbzn) [reply packages/workspace/src/core/file-graph/project-file-map.ts:26]: Nevermind! I thought it was for an undefined root. :+1:

**Review by FrozenPandaz — APPROVED** [review]
Thank you for your contribution! LGTM :tada:
