### PR TITLE
fix(core): obey nx.json package manager property

### LINKED ISSUE #10480: nx@14.1.9 migrate --run-migrations does not respect cli.packageManager setting
## Current Behavior

Nx 14.1.9 does not respect `cli.packageManager` config option, instead detects from yarn.lock. This is a problem because my yarn.lock file is not in the same directory as the nx workspace root.

```
❯ ../node_modules/.bin/nx --version
14.1.9

❯ cat nx.json | jq .cli
{
  "defaultCollection": "@nrwl/angular",
  "packageManager": "yarn"
}

❯ ls .. | grep yarn.lock
yarn.lock
```

## Expected Behavior

If `cli.packageManager` is set to `"yarn"`, it will always use yarn for package management

## Steps to Reproduce

- Monorepo root dir is a yarn workspace root, but is not a Nx workspace root
- Nx workspace is a subdirectory of the monorepo root dir

     ```
     project/
         package.json
         yarn.lock
         other-stuff/
         nx-workspace/
          nx-project1/
          nx-project2/
          nx.json
          workspace.json
     ``` 

Running the below command will cause npm to be in use:

```
nx migrate --run-migrations
```

**Note** the reason why I was running nx migrate was related to moving Nx 13 -> 14. 

The issue can be worked around by creating a temporary `yarn.lock` file in the current directory, running the migration, removing the yarn.lock file, and then running yarn again just in case.

### Environment

```
❯ ../node_modules/.bin/nx report
 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin x64
   npm  : 8.5.0

   nx : 14.1.9
   @nrwl/angular : 14.1.9
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.2.2
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.1.9
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.1.4
   @nrwl/web : 14.1.9
   @nrwl/workspace : 14.1.9
   typescript : 4.6.4
   ---------------------------------------
   Community plugins:
```

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
`nx.json` has a property, `cli.packageManager`, that we never read. It is documented, but we don't use it opting to instead detect the package manager based on the lock files present.

This is generally safe, and mostly works, but can cause the incorrect package manager to be used in the cases where:
 - There is no lock file
 - There are multiple lock files
 - The lock file is located in a parent directory (the case for #10480)

## Expected Behavior
If `cli.packageManager` is set, we use it. If not (which is the case for **_most_** repos), we use our current detection logic.

## Related Issue(s)

Fixes #10480

### CODE REVIEW

File: packages/nx/src/utils/package-manager.ts [hunk 1]
```diff
@@ -27,8 +28,11 @@ export interface PackageManagerCommands {
 /**
  * Detects which package manager is used in the workspace based on the lock file.
  */
-export function detectPackageManager(dir: string = ''): PackageManager {
-  return existsSync(join(dir, 'yarn.lock'))
+export function detectPackageManager(
+  dir: string = '',
+  nxJson = readNxJson()
```
Comment (FrozenPandaz) [inline packages/nx/src/utils/package-manager.ts:33]: Just read the file, don't allow for a param to be passed in.

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
