### PR TITLE
fix(angular): expand extends property when reading nx.json in the angular cli adapter

### LINKED ISSUE #10138: Blank Nx core workspace fails to create an angular app
## Current Behavior

`@nrwl/angular` fails to create an initial project in a fresh Nx core workspace.

## Expected Behavior

`@nrwl/angular` should be able to create a new app in a fresh Nx core workspace.

## Steps to Reproduce

Run the following commands to reproduce the behavior:

1. `npx create-nx-workspace@latest --preset=core --name=test --nxCloud=false`
2. `cd test`
3. `npm i @nrwl/angular`
4. `nx g @nrwl/angular:app --name=ng-app --style=css --routing=false`

**NOTE:** _The issue does not occur when using `@nrwl/react` instead of `@nrwl/angular` above._  The app is successfully created and added as the `defaultProject` in `nx.json`.

### Failure Logs

```bash
SchematicsException [Error]: Project "ng-app" does not exist.
    at /Users/user/test/node_modules/@schematics/angular/component/index.js:104:19
Project "ng-app" does not exist.
```

### Environment

```bash
Node : 16.15.0
OS   : darwin x64
npm  : 8.8.0

nx : 14.1.1
@nrwl/angular : 14.1.1
@nrwl/workspace : 14.1.1
```

### PR DESCRIPTION
**Pull request by leosvelperez**
## Related Issue(s)

Fixes #10138

### CODE REVIEW

File: packages/nx/src/adapter/ngcli-adapter.ts [hunk 1]
```diff
@@ -599,9 +607,7 @@ export class NxScopeHostUsedForWrappedSchematics extends NxScopedHost {
         // we have to add them into the file.
         const createdProjectFiles = findCreatedProjects(this.host);
         const deletedProjectFiles = findDeletedProjects(this.host);
-        const nxJsonInTree = nxJsonChange
-          ? parseJson(nxJsonChange.content.toString())
-          : parseJson(this.host.read('nx.json').toString());
+        const nxJsonInTree = readNxJson(this.host);
```
Comment (AgentEnder) [inline packages/nx/src/adapter/ngcli-adapter.ts:610]: @leosvelperez and I discussed this morning, since this.host **_is_** our tree, not angular's, and findMatchingChange **_is_** using our tree, we can just use the devkit util.

**Review by AgentEnder — APPROVED** [review]
LGTM 🎉
