### PR TITLE
fix(js): show lifecycle script contents in publish executor, scrub version in dry-run

### LINKED ISSUE #22925: `nx release` fails when publishing packages that have a `prepublishOnly` step that produces console output
### Current Behavior

When running the `nx release` command for packages that have a `prepublishOnly` script that e.g. builds the package, the command fails since it cannot parse the console output as a JSON

### Expected Behavior

It should be possible to publish packages that have a `prepublishOnly` script attached

### GitHub Repo

_No response_

### Steps to Reproduce

Since this step involves actually publishing to npm, you need to create your own package on npm for this.

1. Create a npm library that is publishable
2. Add the `"prepublishOnly": "echo 'This is only a test'"`
3. Run the `nx release` command
4. Selecte `yes` when it asks to publish the package

### Nx Report

```shell
Node   : 18.20.2
   OS     : win32-x64
   pnpm   : 8.15.6

   nx             : 18.0.2
   @nx/js         : 18.0.2
   @nx/workspace  : 18.0.2
   @nx/devkit     : 18.0.2
   @nrwl/tao      : 18.0.2
   typescript     : 5.4.3
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

I already have a local patch for this and would be willing to open a PR for this.

The issue is [here](https://github.com/nrwl/nx/blob/master/packages/js/src/executors/release-publish/release-publish.impl.ts#L101), there the output of the publish command is parsed without stripping it of previous output.

### PR DESCRIPTION
**Pull request by JamesHenry**
## Current Behavior

Lifecycle scripts related to publishing change the output of `npm publish`, which mixes JSON with non-JSON content despite the `--json` flag being set. Currently, we will error when attempting to parse the whole thing as JSON.

The lifecycle scripts contents themselves are not shown to the user.

Additionally, during dry-run we have no choice but to print the version that currently exists on disk, which can be confusing.

## Expected Behavior

We extract and parse the JSON from the `npm publish` output, even when it is mixed with other output. We also show the lifecycle script outputs to the user, where applicable.

During dry-run, we replace the version in the publish output with a placeholder to avoid confusion around what would be published.

## Related Issue(s)

Fixes https://github.com/nrwl/nx/issues/22925

### CODE REVIEW

**Review by fahslaj — APPROVED** [review]

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/js/src/executors/release-publish/extract-json-data-from-string.ts [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+      };
+    } catch {
+      // Ignore invalid JSON strings
+    }
+  } else {
+    let jsonStartLine = 0;
+    let jsonEndLine = 0;
+
+    for (let line of lines) {
+      if (line.startsWith('{') && !insideJson) {
```
[the remark this answers is not in the document]
Comment (JamesHenry) [reply packages/js/src/executors/release-publish/extract-json-data-from-string.ts]: I have made it resilient to this now https://github.com/nrwl/nx/pull/23850/commits/120e6f19574cda19da314d3056444b2d6113d37f

File: packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+          !expectedNpmPublishJsonKeys.every(
+            (key) => parsedJson[key] !== undefined
+          )
+        ) {
+          continue;
+        }
+        jsonData = parsedJson;
+        jsonStartIndex = str.indexOf(match);
+        jsonEndIndex = jsonStartIndex + match.length;
+        break;
```
Comment (FrozenPandaz) [inline packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts:39]: Seems like we can `return` here?

File: packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts [hunk 3]
```diff
@@ -0,0 +1,62 @@
+const expectedNpmPublishJsonKeys = [
+  'id',
+  'name',
+  'version',
+  'size',
+  'filename',
```
Comment (FrozenPandaz) [inline packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts:6]: To confirm, ALL of these keys are present in EVERY version of NPM?

File: packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+      afterJsonData,
+    };
+  }
+
+  // No jsonData detected, the whole contents is the beforeJsonData
+  return {
+    beforeJsonData: str,
+    jsonData: null,
+    afterJsonData: '',
+  };
```
Comment (FrozenPandaz) [inline packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts:61]: I think we should throw an error here instead.

File: packages/js/src/executors/release-publish/release-publish.impl.ts [hunk 5]
```diff
@@ -220,12 +221,54 @@ export default async function runExecutor(
       stdio: ['ignore', 'pipe', 'pipe'],
     });
 
-    const stdoutData = JSON.parse(output.toString());
+    /**
+     * We cannot JSON.parse the output directly because if the user is using lifecycle scripts, npm will mix its publish output with the JSON output all on stdout.
+     * Additionally, we want to capture and show the lifecycle script outputs as beforeJsonData and afterJsonData and print them accordingly below.
+     */
+    const extractJsonData = extractNpmPublishJsonData(output.toString());
+    if (!extractJsonData.jsonData) {
```
Comment (FrozenPandaz) [inline packages/js/src/executors/release-publish/release-publish.impl.ts:229]: If we throw an error from the function, we won't need this block.

File: packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts [hunk 6]
```diff
@@ -0,0 +1,62 @@
...
+  'size',
+  'filename',
+];
+
+export function extractNpmPublishJsonData(str: string): {
+  beforeJsonData: string;
+  jsonData: Record<string, unknown> | null;
+  afterJsonData: string;
+} {
+  const jsonRegex = /{(?:[^{}]|{[^{}]*})*}/g;
```
Comment (FrozenPandaz) [inline packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts:14]: Could you leave a comment with exactly what this regex matches?

Does it match nested JSON objects such as `{ "key": "value" }` in `{ "a": { "key": "value" } }`.

File: packages/js/src/executors/release-publish/release-publish.impl.ts [hunk 7]
```diff
@@ -220,12 +221,54 @@ export default async function runExecutor(
...
+      );
+      return {
+        success: false,
+      };
+    }
 
     // If npm workspaces are in use, the publish output will nest the data under the package name, so we normalize it first
-    const normalizedStdoutData = stdoutData[packageName] ?? stdoutData;
+    const normalizedStdoutData =
+      extractJsonData.jsonData[packageName] ?? extractJsonData.jsonData;
```
Comment (FrozenPandaz) [inline packages/js/src/executors/release-publish/release-publish.impl.ts:240]: I can't easily tell. Is the nested `packageName` specific form handled by the function above?

Can you ensure unit tests exist for both cases please?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
This solution is much better and more robust :+1: 

Some cleanup and I think it's good to go.

File: packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts (hunk 4 above)
Comment (JamesHenry) [reply packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts:61]: I don’t think I agree, because we would then need dedicated handling within the existing try catch that this code executes within to get it to ignore this specific error only, it would currently blow up. That catch is already relatively involved for handling errors from npm and that would suddenly bloat its purpose to handle known “errors” from us as well. It’s either that or wrap it in another nested try catch which seems equally undesirable…

File: packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts (hunk 2 above)
Comment (JamesHenry) [reply packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts:39]: Sure

File: packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts (hunk 3 above)
Comment (JamesHenry) [reply packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts:6]: We don’t support anywhere close to every version of npm anywhere else in the codebase 😅 I will manually verify against all versions we do support

File: packages/js/src/executors/release-publish/release-publish.impl.ts (hunk 7 above)
Comment (JamesHenry) [reply packages/js/src/executors/release-publish/release-publish.impl.ts:240]: It’s not related to this PR at all

File: packages/js/src/executors/release-publish/release-publish.impl.ts (hunk 5 above)
Comment (JamesHenry) [reply packages/js/src/executors/release-publish/release-publish.impl.ts:229]: Please see comment

File: packages/js/src/executors/release-publish/release-publish.impl.ts (hunk 7 above)
Comment (JamesHenry) [reply packages/js/src/executors/release-publish/release-publish.impl.ts:240]: I understand your question more now in the context of the question above about the regexp, I will clarify in the code

File: packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts (hunk 3 above)
Comment (JamesHenry) [reply packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts:6]: Manually tested all the way back to npm v7 (which is from before the range of node that we support), we are all good

File: packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts (hunk 6 above)
Comment (JamesHenry) [reply packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts]: Added a detailed explainer comment

File: packages/js/src/executors/release-publish/release-publish.impl.ts (hunk 7 above)
Comment (JamesHenry) [reply packages/js/src/executors/release-publish/release-publish.impl.ts:240]: Added a unit test for the nested format and updated the logic to ensure there is no spill over

Comment (JamesHenry) [reply packages/js/src/executors/release-publish/release-publish.impl.ts]: As part of my testing of npm to ensure that the required keys are present in all supported versions (and beyond), I (re)discovered the fundamental change that we made to this executor a little while ago.

In order to improve the npm config resolution (and in taking advice from Luke from NPM) we stopped running `npm publish` from the package root and began running it from the workspace root, pointing it to the package root instead.

Well it turns out the nesting behaviour that I handled on this line a long time ago (and the comment I wrote above it) are only _ever_ applicable when running with workspaces AND when executing the command from the package root. So this nesting never occurs in our executor any more and I therefore removed it entirely. This also lets us keep the new JSON extraction logic as simple as possible.

So that this knowledge is not lost I have added a comment above the npm publish command construction: https://github.com/nrwl/nx/pull/23850/commits/21b243d445a47becd8637debfebc9ba5b05ae476#diff-1c2ebfe42e321fc6f4a8c99988807e45610b304f4685123906741b0260fc5472R204-R211

File: packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts (hunk 4 above)
Comment (JamesHenry) [reply packages/js/src/executors/release-publish/extract-npm-publish-json-data.ts:60]: Ultimately, it's subjective, with zero consequences to the user experience either way (assuming you agree with me that it shouldn't end up in the "something unexpected went wrong" section, so hopefully we don't need to block the PR over it

**Review by FrozenPandaz — APPROVED** [review]
