### PR TITLE
fix(react): remove outdated packages

### LINKED ISSUE #11882: Potentially redundant dependencies in Next.js template
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
When generating a simple Next.js project with `npx create-nx-workspace --preset=next`, I see at least three dependencies where I don't know why they come installed out of the box:

```
"core-js": "^3.6.5",
"regenerator-runtime": "0.13.7",
"react-test-renderer": "18.0.0"
```

`core-js` and `regenerator-runtime` seem to be compatibility layers which shouldn't be necessary in a modern project.

jest tests also work without `react-test-renderer`.

All three of these dependencies are never references in a freshly installed project.

## Motivation
Get rid of redundant dependencies

### PR DESCRIPTION
**Pull request by ndcunningham**
The features should be available by default or they are available via a different library.
Example
`react-test-renderer` -> `@testing-library`

closed #11882

### CODE REVIEW

File: packages/react/src/generators/init/init.ts [hunk 1]
```diff
@@ -63,7 +63,6 @@ function updateDependencies(host: Tree, schema: InitSchema) {
     '@types/react': typesReactVersion,
     '@types/react-dom': typesReactDomVersion,
     '@testing-library/react': testingLibraryReactVersion,
-    'react-test-renderer': reactTestRendererVersion,
```
Comment (xiongemi) [inline packages/react/src/generators/init/init.ts:66]: is reactTestRendererVersion still being used?

**Comment by xiongemi** [comment]
do we need a migration script to remove these libraries in package.json?

File: packages/react/src/generators/init/init.ts (hunk 1 above)
Comment (ndcunningham) [reply packages/react/src/generators/init/init.ts:66]: I don't think so.

**Review by jaysoo — APPROVED** [review]
