### PR TITLE
fix(js): refactor ensurePackage

### LINKED ISSUE #14933: Default generated js libraries cannot be dynamically installed & required.
### Current Behavior

The current generated `@nrwl/nx-plugin` plugins contain the package's index file in the `src/index.ts` directory. A bug with NodeJS nodejs/node#44663 prevents from a running process to install and invoke a package if it's index file is not in the package's root. Read more in qwikifiers/qwik-nx#44.

### Expected Behavior

Generated projects should contain the `index.ts` located at the package's root. That way plugins can be invoked in scenarios like this one:

```typescript
await ensurePackage(tree, '@nxkit/playwright', nxKitVersion);
const { projectGenerator } = await import('@nxkit/playwright'); // <= throws
```

### GitHub Repo

_No response_

### Steps to Reproduce

Run the `qwik-nx` plugin preset generator from version 0.9.0

`pnpx create-nx-workspace --preset qwik-nx`

### Nx Report

```shell
N/A as error happens in the workspace creation.
```

### Failure Logs

```shell
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn pnpm ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn pnpm',
  path: 'pnpm',
  spawnargs: [
    'exec',
    'nx',
    '--nxWorkspaceRoot="C:/dev/workspace/open-source"',
    'g',
    'qwik-nx:preset',
    '--no-a',
    '--no-g',
    '--$0=C:\\Users\\MyUser\\AppData\\Local\\pnpm\\store\\v3\\tmp\\dlx-19560\\node_modules\\create-nx-workspace\\bin\\index.js',
    '--packageManager=pnpm',
    '--defaultBase=main'
  ]
}

Node.js v18.7.0
 ERROR  Command failed with exit code 1: C:\Users\MyUser\AppData\Local\pnpm\store\v3\tmp\dlx-19560\node_modules\.bin\create-nx-workspace.CMD --preset qwik-nx

pnpm: Command failed with exit code 1: C:\Users\MyUser\AppData\Local\pnpm\store\v3\tmp\dlx-19560\node_modules\.bin\create-nx-workspace.CMD --preset qwik-nx
    at makeError (C:\Users\MyUser\AppData\Roaming\nvm\v18.7.0\node_modules\pnpm\dist\pnpm.cjs:22852:17)
    at handlePromise (C:\Users\MyUser\AppData\Roaming\nvm\v18.7.0\node_modules\pnpm\dist\pnpm.cjs:23423:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (C:\Users\MyUser\AppData\Roaming\nvm\v18.7.0\node_modules\pnpm\dist\pnpm.cjs:202440:7)
    at async C:\Users\MyUser\AppData\Roaming\nvm\v18.7.0\node_modules\pnpm\dist\pnpm.cjs:209882:21
    at async main (C:\Users\MyUser\AppData\Roaming\nvm\v18.7.0\node_modules\pnpm\dist\pnpm.cjs:209853:34)
    at async runPnpm (C:\Users\MyUser\AppData\Roaming\nvm\v18.7.0\node_modules\pnpm\dist\pnpm.cjs:210079:5)
    at async C:\Users\MyUser\AppData\Roaming\nvm\v18.7.0\node_modules\pnpm\dist\pnpm.cjs:210071:7
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by FrozenPandaz**
## Current Behavior

`ensurePackage` does not work with `pnpm` as the files that are currently executing may get moved entirely.

`ensurePackage` does more of its fair share:
1. Installs the package into the workspace
2. Allows requiring later on
3. Doesn't update the `Tree` with the updated `package.json` yet appears after the generate command.

## Expected Behavior

`ensurePackage` will work with `pnpm`.

1. Installs the package into a tmp directory
2. Allows requiring later on
3. Will not accept a Tree anymore
4. Will not update the Tree. That should be done via `addDependenciesToPackageJson`

## Breaking Changes

`ensurePackage` will no longer install directly into the workspace. This must be done via the normal tools.

## Related Issue(s)

Fixes #14933

### CODE REVIEW

File: packages/devkit/src/utils/package-json.ts [hunk 1]
```diff
@@ -368,89 +372,109 @@ function requiresRemovingOfPackages(
...
+    if (e.code !== 'MODULE_NOT_FOUND') {
+      throw e;
+    }
   }
+
+  if (process.env.NX_DRY_RUN && process.env.NX_DRY_RUN !== 'false') {
+    throw new Error(
+      'NOTE: This generator does not support --dry-run. If you are running this in Nx Console, it should execute fine once you hit the "Run" button.\n'
+    );
+  }
```
Comment (AgentEnder) [inline packages/devkit/src/utils/package-json.ts:445]: Do we still need this? It  seems like this part should actually work in dry run with the new mode since its not installing in the repo.

File: packages/devkit/src/utils/package-json.ts [hunk 2]
```diff
@@ -368,89 +372,109 @@ function requiresRemovingOfPackages(
...
+
+  const tempDir = dirSync().name;
+  console.log('Installing', pkg);
```
Comment (AgentEnder) [inline packages/devkit/src/utils/package-json.ts:448]: Remove

File: packages/devkit/src/utils/package-json.ts [hunk 3]
```diff
@@ -368,89 +372,109 @@ function requiresRemovingOfPackages(
...
+  execSync(`${getPackageManagerCommand().addDev} ${pkg}@${requiredVersion}`, {
+    cwd: tempDir,
+    stdio: [0, 1, 2],
+  });
+  console.log('after install');
```
Comment (AgentEnder) [inline packages/devkit/src/utils/package-json.ts:453]: Remove

File: packages/devkit/src/utils/package-json.ts [hunk 4]
```diff
@@ -368,89 +372,109 @@ function requiresRemovingOfPackages(
...
+ * Use a package that has not been installed as a dependency.
  *
  * For example:
  * ```typescript
  * ensurePackage(tree, '@nrwl/jest', nxVersion)
  * ```
- * This will check that @nrwl/jest@<nxVersion> exists in devDependencies.
- * If it exists then function returns, otherwise it will install the package before continuing.
+ * This install the @nrwl/jest@<nxVersion> and return the module
  * When running with --dryRun, the function will throw when dependencies are missing.
```
Comment (AgentEnder) [inline packages/devkit/src/utils/package-json.ts:384]: I don't think this part has to be true anymore.

File: packages/nx/src/utils/nx-plugin.ts [hunk 5]
```diff
@@ -23,6 +23,7 @@ import {
 } from '../project-graph/utils/find-project-for-path';
 import { normalizePath } from './path';
 import { join } from 'path';
+import { ensureTypescript } from '@nrwl/js/src/utils/typescript/ensure-typescript';
```
Comment (AgentEnder) [inline packages/nx/src/utils/nx-plugin.ts:26]: This probably needs to actually be used, or removed more likely. nx shouldn't import from @nrwl/js right?

**Review by AgentEnder — DISMISSED** [review]

**Review by nartc — APPROVED** [review]
LGTM on `nrwl/js` side

File: packages/angular/src/generators/change-storybook-targets/change-storybook-targets.ts [hunk 6]
```diff
@@ -8,13 +12,20 @@ export async function angularChangeStorybookTargestGenerator(
...
   await changeStorybookTargetsGenerator(tree);
 
   if (!schema.skipFormat) {
     await formatFiles(tree);
   }
+  return addDependenciesToPackageJson(
+    tree,
+    {},
+    { '@nrwl/storybook': nxVersion }
+  );
```
Comment (leosvelperez) [inline packages/angular/src/generators/change-storybook-targets/change-storybook-targets.ts:28]: I'm unsure whether it is an issue, but better to leave formatting as the last thing to do. We don't have to double-guess or rely on whether the `addDependenciesToPackageJson` make changes with the right formatting:
```suggestion
  const installTask = addDependenciesToPackageJson(
    tree,
    {},
    { '@nrwl/storybook': nxVersion }
  );

  if (!schema.skipFormat) {
    await formatFiles(tree);
  }

  return installTask;
```

File: packages/angular/src/generators/init/angular-v14/init.ts [hunk 7]
```diff
@@ -47,10 +43,28 @@ export async function angularInitGenerator(
...
+
+      try {
+        ensurePackage(pkg, devkitVersion);
+      } catch {
+        // @schematics/angular cannot be required so this fails but that's we will still be ble to wrap the schematic later on
+      }
+
+      if (!options.skipPackageJson) {
+        tasks.push(
+          addDependenciesToPackageJson(host, {}, { pkg: devkitVersion })
```
Comment (leosvelperez) [inline packages/angular/src/generators/init/angular-v14/init.ts:55]:
```suggestion
          addDependenciesToPackageJson(host, {}, { [pkg]: devkitVersion })
```

File: packages/angular/src/generators/init/init.ts [hunk 8]
```diff
@@ -63,18 +67,27 @@ export async function angularInitGenerator(
...
+
+      try {
+        ensurePackage(pkg, devkitVersion);
+      } catch {
+        // @schematics/angular cannot be required so this fails but that's we will still be ble to wrap the schematic later on
+      }
+
+      if (!options.skipPackageJson) {
+        tasks.push(
+          addDependenciesToPackageJson(tree, {}, { pkg: devkitVersion })
```
Comment (leosvelperez) [inline packages/angular/src/generators/init/init.ts:79]:
```suggestion
          addDependenciesToPackageJson(tree, {}, { [pkg]: devkitVersion })
```

File: packages/angular/src/generators/init/angular-v14/init.ts [hunk 9]
```diff
@@ -47,10 +43,28 @@ export async function angularInitGenerator(
       devkitVersion ??=
         getInstalledPackageVersion(host, '@angular-devkit/build-angular') ??
         backwardCompatibleVersions.angularV14.angularDevkitVersion;
-      ensurePackage(host, pkg, devkitVersion);
+
+      try {
+        ensurePackage(pkg, devkitVersion);
+      } catch {
+        // @schematics/angular cannot be required so this fails but that's we will still be ble to wrap the schematic later on
```
Comment (leosvelperez) [inline packages/angular/src/generators/init/angular-v14/init.ts:50]: nit:
```suggestion
        // @schematics/angular cannot be required so this fails but this will still allow us to wrap the schematic later on
```

File: packages/angular/src/generators/init/init.ts [hunk 10]
```diff
@@ -63,18 +67,27 @@ export async function angularInitGenerator(
       devkitVersion ??=
         getInstalledPackageVersion(tree, '@angular-devkit/build-angular') ??
         angularDevkitVersion;
-      ensurePackage(tree, pkg, devkitVersion);
+
+      try {
+        ensurePackage(pkg, devkitVersion);
+      } catch {
+        // @schematics/angular cannot be required so this fails but that's we will still be ble to wrap the schematic later on
```
Comment (leosvelperez) [inline packages/angular/src/generators/init/init.ts:74]: nit:
```suggestion
        // @schematics/angular cannot be required so this fails but this will still allow us to wrap the schematic later on
```

**Review by leosvelperez — CHANGES_REQUESTED** [review]

**Review by mandarini — APPROVED** [review]

**Review by barbados-clemens — APPROVED** [review]
Looks good from jest/cypress side

**Review by xiongemi — APPROVED** [review]

**Review by leosvelperez — APPROVED** [review]

**Review by meeroslav — APPROVED** [review]
Linter part looks good!

File: packages/cypress/src/generators/init/schema.d.ts [hunk 11]
```diff
@@ -1,3 +1,5 @@
 export interface Schema {
   skipPackageJson?: boolean;
+
```
Comment (barbados-clemens) [inline packages/cypress/src/generators/init/schema.d.ts:3]: nitpick: extra space. nx format will probably catch it.

**Review by barbados-clemens — APPROVED** [review]
cypress/jest look fine. just had a non-blocking question on if jest/cypress really need to call the jsInitGenerator.

File: packages/jest/src/generators/init/init.ts [hunk 12]
```diff
@@ -191,12 +191,15 @@ export async function jestInitGenerator(
...
-    js: schema.js,
-    skipFormat: true,
-  });
   const tasks: GeneratorCallback[] = [];
 
+  tasks.push(
+    await jsInitGenerator(tree, {
+      ...schema,
+      skipFormat: true,
+    })
```
[the remark this answers is not in the document]
Comment (FrozenPandaz) [reply packages/jest/src/generators/init/init.ts:200]: Okay, we can investigate removing it.

I think jest needs it for `tsconfig.spec.json`?

**Review by AgentEnder — APPROVED** [review]
