### PR TITLE
fix(expo): remove deprecated webpack.

### LINKED ISSUE #26118: Unable to combine Expo and React applications in the same workspace
### Current Behavior

Workspace with only Expo application works fine but after React app is generated, neither Expo nor React apps can be launched due to project graph error.

### Expected Behavior

Both Expo and React apps launched successfully

### GitHub Repo

https://github.com/vaagnavanesyan/nx-expo-react-repro

### Steps to Reproduce

1. Create empty workspace: `yarn create nx-workspace expo-and-react`  with following answers:
```
✔ Which stack do you want to use? · none
✔ Package-based monorepo, integrated monorepo, or standalone project? · integrated
✔ Do you want Nx Cloud to make your CI fast? · skip
```

2. Add Expo plugin: `nx add @nx/expo`
3. Generate Expo app: `yarn nx generate @nx/expo:application --name=my-expo-app --directory=apps/my-expo-app --e2eTestRunner=none --projectNameAndRootFormat=as-provided --no-interactive`
4. Ensure that app is starting successfully: `nx start my-expo-app`
5. Add React plugin: `nx add @nx/react`
6. Generate React app: `yarn nx generate @nx/react:application --name=my-react-app --directory=apps/my-react-app --e2eTestRunner=none --projectNameAndRootFormat=as-provided --no-interactive`
7. Find out that Expo app couldn't be started: `nx start my-expo-app`

Attached [repo](https://github.com/vaagnavanesyan/nx-expo-react-repro) contains commits for each step to make it more easy to reproduce

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.9.0
OS     : linux-x64
yarn   : 1.22.22

nx (global)        : 19.0.4
nx                 : 19.1.0
@nx/js             : 19.1.0
@nx/jest           : 19.1.0
@nx/linter         : 19.1.0
@nx/eslint         : 19.1.0
@nx/workspace      : 19.1.0
@nx/devkit         : 19.1.0
@nx/eslint-plugin  : 19.1.0
@nx/expo           : 19.1.0
@nx/react          : 19.1.0
@nrwl/tao          : 19.1.0
@nx/web            : 19.1.0
@nx/webpack        : 19.1.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/expo/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Failure Logs

```shell
➜  expo-and-react git:(main) nx start my-expo-app --verbose

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  The "@nx/webpack/plugin" plugin threw an error while creating nodes from apps/my-expo-app/webpack.config.js:
    Error: Cannot find module '@expo/webpack-config'
    Require stack:
    - /home/vaagn/Work/expo-and-react/apps/my-expo-app/webpack.config.js
    - /home/vaagn/Work/expo-and-react/node_modules/@nx/webpack/src/utils/webpack/resolve-user-defined-webpack-config.js
    - /home/vaagn/Work/expo-and-react/node_modules/@nx/webpack/src/plugins/plugin.js
    - /home/vaagn/Work/expo-and-react/node_modules/@nx/webpack/plugin.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/project-graph/plugins/loader.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/project-graph/plugins/internal-api.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/project-graph/file-utils.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/utils/package-manager.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/devkit-internals.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/utils/assert-workspace-validity.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/project-graph/build-project-graph.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/project-graph/project-graph.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/utils/project-graph-utils.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/daemon/server/file-watching/file-watcher-sockets.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/daemon/server/server.js
    - /home/vaagn/Work/expo-and-react/node_modules/nx/src/daemon/server/start.js
        at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
        at Module._load (node:internal/modules/cjs/loader:929:27)
        at c._load (node:electron/js2c/node_init:2:13672)
        at Module.require (node:internal/modules/cjs/loader:1150:19)
        at require (node:internal/modules/cjs/helpers:119:18)
        at Object.<anonymous> (/home/vaagn/Work/expo-and-react/apps/my-expo-app/webpack.config.js:1:38)
        at Module._compile (node:internal/modules/cjs/loader:1271:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
        at Module.load (node:internal/modules/cjs/loader:1126:32)
        at Module._load (node:internal/modules/cjs/loader:967:12)
```

### Package Manager Version

yarn@1.22.22

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

**WORKAROUND**
1. Delete `apps/my-expo-app/webpack.config.js`
2. Ensure that app is starting successfully: `nx start my-expo-app`

**POSSIBLE REASON**
`@nx/expo:application` generator uses `metro` as bundler for web. See [`app.json`](https://github.com/nrwl/nx/blob/master/packages/expo/src/generators/application/files/app.json.template#L30) template. But at the same time the generator creates [`webpack.config.js`](https://github.com/nrwl/nx/blob/master/packages/expo/src/generators/application/files/webpack.config.js.template#L6) with deprecation warning. It's unclear for me why do we need that config if we don't use Webpack, or we use it? :thinking:

### PR DESCRIPTION
**Pull request by xiongemi**
config.js

## Related Issue(s)

Fixes https://github.com/nrwl/nx/issues/26118 https://github.com/nrwl/nx/issues/25291 https://github.com/nrwl/nx/issues/23233

### CODE REVIEW

**Comment by vaagnavanesyan** [comment]
@jaysoo could you please pay attention to this PR? It would fix at least 3 issues, some of them for new NX workspaces which will improve DX for new users

File: packages/expo/src/migrations/update-19-2-0/remove-deprecated-webpack-config.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import { Tree, getProjects } from '@nx/devkit';
+import { removeSync } from 'fs-extra';
+import { join } from 'path';
+
+/**
+ * This funciton removes the deprecated webpack.config.js file from projects that use the expo:start executor
```
Comment (hassankhan) [inline packages/expo/src/migrations/update-19-2-0/remove-deprecated-webpack-config.ts:6]:
```suggestion
 * This function removes the deprecated webpack.config.js file from projects that use the expo:start executor
```

Comment (xiongemi) [reply packages/expo/src/migrations/update-19-2-0/remove-deprecated-webpack-config.ts:6]: updated the typo

**Review by ndcunningham — APPROVED** [review]
