### PR TITLE
fix(core): ensure stale dependencies are pruned in graph

### LINKED ISSUE #16321: After Upgrade to 15.9.2 Circuclar Dependency Error
### Current Behavior

When linting the project, I get the message, that there is a circular dependency between an app and a library.

`/Users/xxx/apps/jpi/src/pages/p/[page].tsx
   7:1   error    Circular dependency between "jpi" and "ui" detected: jpi -> ui -> jpi

Circular file chain:
- apps/jpi/src/pages/p/[page].tsx
- undefined  @nrwl/nx/enforce-module-boundaries
`

However it is nowhere stated where that circular dependency should come from.

The dep-graph does **not** show any imports from "lib" into "jpi". There is a arrow, but the file list is empty.

### Expected Behavior

I wish it would just work like before the update to 15.9.2

### GitHub Repo

_No response_

### Steps to Reproduce

1. run lint
2. see error

### Nx Report

```shell
Node : 16.15.1
   OS   : darwin arm64
   pnpm : 7.5.0
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.4
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by meeroslav**
## Current Behavior
Old dependencies are not being removed from the graph

## Expected Behavior
Dependencies should be pruned every time we rebuild the graph

## Related Issue(s)

Fixes #16321

### CODE REVIEW

File: packages/nx/src/project-graph/project-graph-builder.ts [hunk 1]
```diff
@@ -385,6 +389,24 @@ export class ProjectGraphBuilder {
...
       }
     }
+    // cleanup stale dependencies
+    for (const [targetProject, types] of alreadySetTargetProjects.entries()) {
+      const node = this.graph.nodes[sourceProject];
+      if (node) {
+        for (const depType of types.keys()) {
+          if (
+            depType !== 'implicit' &&
+            !node.data.files.some((f) =>
```
Comment (meeroslav) [inline packages/nx/src/project-graph/project-graph-builder.ts:399]: All explicit dependencies should be pruned away if there's no file to which they belong anymore.

File: packages/nx/src/project-graph/build-project-graph.spec.ts [hunk 2]
```diff
@@ -232,6 +232,7 @@ describe('project graph', () => {
     expect(graph.dependencies).toEqual({
       api: [{ source: 'api', target: 'npm:express', type: 'static' }],
       demo: [
+        { source: 'demo', target: 'api', type: 'implicit' },
```
Comment (meeroslav) [inline packages/nx/src/project-graph/build-project-graph.spec.ts:235]: Ordering is different. After cleanup implicit will always go first

**Review by FrozenPandaz — APPROVED** [review]
