### PR TITLE
Honour browserslist on libraries using babel

### LINKED ISSUE #10304: Browserslist config seems does not work for @nrwl/web:rollup executor
## Current Behavior

I'm using `@nrwl/web:rollup` to build my react library, and I my target is only for last 2 Chrome versions. So I add a `browserslist` field in the `package.json` file:
```json
{
  "name": "@my-lib/ui",
  "version": "0.0.1",
  "browserslist": ["last 2 Chrome versions"]
}
```

and my  `project.json` for this library is looks like the following:
```json
{
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "packages/ui/src",
  "projectType": "library",
  "tags": [],
  "targets": {
    "build": {
      "executor": "@nrwl/web:rollup",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/packages/ui",
        "tsConfig": "packages/ui/tsconfig.lib.json",
        "project": "packages/ui/package.json",
        "entryFile": "packages/ui/src/index.ts",
        "external": ["react/jsx-runtime"],
        "rollupConfig": ["@nrwl/react/plugins/bundle-rollup", "packages/ui/custom-rollup-swc"],
        "compiler": "babel",
        "assets": [
          {
            "glob": "packages/ui/README.md",
            "input": ".",
            "output": "."
          }
        ]
      }
    }  
  }
}
```
When I run `nx build ui`, I found that the built js file `dist/packages/ui/index.esm.js` contains some code imported from `core-js`, which should not be included in the build file, as I only target last 2 Chrome version (and the library content is just the initial template `@nrwl/react:library` generated).

I found that the `.babelrc` presets include`@nrwl/react/babel`, which include preset `@nrwl/web/babel` . And `@nrwl/web/babel` eventually config `@babel/preset-env`, but I notice that the `targets` option for `@babel/preset-env` will be a object:
```js
targets: isModern ? { esmodules: true } : undefined
```
when `isModern` is truthy.

So I digged into `@babel/preset-env`, and it looks like `@babel/preset-env` will ignore browserslist config when `targets` is already configured.

## Expected Behavior

The build system should respect browserslist config, and in this case, output js files should not contain `core-js` code.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
   Node : 16.15.0
   OS   : linux x64
   yarn : 1.22.18

   nx : 14.1.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.5
   @nrwl/eslint-plugin-nx : 14.1.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.5
   @nrwl/js : 14.1.5
   @nrwl/linter : 14.1.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.5
   @nrwl/web : 14.1.5
   @nrwl/workspace : 14.1.5
   typescript : 4.6.4
   rxjs : 6.6.7
```

### PR DESCRIPTION
**Pull request by ianldgs**
## Current Behavior
Libraries include unnecessary polyfills, even when configured for modern browsers on browserslist.

## Expected Behavior
Respect the browserslist and only generate necessary polyfills.

## Related Issue(s)

Fixes #10304

---

`du -sh dist/libs/**/index.js`

`esmodules: true`:

```
136K    dist/libs/redacted/index.js
 48K    dist/libs/redacted/index.js
4.0K    dist/libs/redacted/index.js
 84K    dist/libs/redacted/index.js
4.0K    dist/libs/redacted/index.js <-- this one was using swc instead, which respects browserslistrc
 36K    dist/libs/redacted/index.js
108K    dist/libs/redacted/index.js
 48K    dist/libs/redacted/index.js
 88K    dist/libs/redacted/index.js
 48K    dist/libs/redacted/index.js
 20K    dist/libs/redacted/index.js
```

`esmodules: "intersect"` + browserslistrc:

```
8.0K    dist/libs/redacted/index.js
4.0K    dist/libs/redacted/index.js
4.0K    dist/libs/redacted/index.js
8.0K    dist/libs/redacted/index.js
4.0K    dist/libs/redacted/index.js
4.0K    dist/libs/redacted/index.js
4.0K    dist/libs/redacted/index.js
4.0K    dist/libs/redacted/index.js
4.0K    dist/libs/redacted/index.js
4.0K    dist/libs/redacted/index.js
4.0K    dist/libs/redacted/index.js
```

### CODE REVIEW

**Comment by ianldgs** [comment]
@vsavkin / @FrozenPandaz could I get a review please? Not sure what was up with CI before, I just rebased.

**Comment by ianldgs** [comment]
Or maybe @mandarini can review pls? I see you reviewed a related PR from @jaysoo recently.
This is a one-line change with a huge benefit.
Not sure if this is being ignored because of the PR title not being a conventional commit, but I did make the actual commit message according to the [contributing](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#commit-message-guidelines) guide.

**Comment by mandarini** [comment]
Hi there! Thanks for contributing! Your PR is not getting ignored, it's just that some of us were on holiday break! :) 

I am not working today, but I can review on Monday. 

Thanks again!

**Review by mandarini — APPROVED** [review]

File: packages/web/babel.ts [hunk 1]
```diff
@@ -48,7 +48,7 @@ module.exports = function (api: any, options: NxWebBabelPresetOptions = {}) {
               corejs: 3,
               // Do not transform modules to CJS
               modules: false,
-              targets: isModern ? { esmodules: true } : undefined,
+              targets: isModern ? { esmodules: 'intersect' } : undefined,
```
Comment (dosentmatter) [inline packages/web/babel.ts:51]: Hmm is `{ esmodules: 'intersect' }` a valid `targets`? It doesn't seem like it according to the docs. Please correct me if I am wrong.

`@babel/preset-env` says [`targets` follows the same usage](https://babeljs.io/docs/en/babel-preset-env#targets) as the [top-level `targets`](https://babeljs.io/docs/en/options#targets):

> Type: `string | Array<string> | { [string]: string }`
> Default: `{}`
> ...
> Or an object of minimum environment versions to support:
> ```json
> {
>   "targets": {
>     "chrome": "58",
>     "ie": "11"
>   }
> }
> ```
> Supported environments: `android`, `chrome`, `deno`, `edge`, `electron`, `firefox`, `ie`, `ios`, `node`, `opera`, `rhino`, `safari`, `samsung`.

For [`targets.esmodules`](https://babeljs.io/docs/en/options#targetsesmodules), it says
> Type: `boolean`
> ...
> When the esmodules target is specified, it will intersect with the browsers target and browserslist's targets.

So this PR changed `esmodules` from `true` to `intersect`, which is another truthy value. Did it actually make a difference?

Comment (ianldgs) [reply packages/web/babel.ts:51]: Hey! Good question. It's a bit of a hidden option. Had to dig through the source of code of Babel to find it.

I linked and quoted the docs in the commit message, but I see it got squashed. Here is it again:

https://babeljs.io/docs/en/babel-helper-compilation-targets#gettargets
```ts
type InputTargets = { ...Targets, browsers?: Browsers, // When `true`, this completely replaces the `browsers` option. // When `intersect`, this is intersected with the `browsers` // option (giving the higher browsers as the result). esmodules?: boolean | "intersect", };
```

Comment (ianldgs) [reply packages/web/babel.ts:51]: (And yes, it makes a difference. I have tested by manually changing the file in `node_modules`. Result in PR description)
