### PR TITLE
fix(core): fix plugin exclude option

### LINKED ISSUE #22737: Nx.json option `plugins.[].exclude` crashes
### Current Behavior

When using the `exclude` option, the following error happens:

```
TypeError: Cannot read properties of undefined (reading 'some')
 at createProjectConfigurations (node_modules/nx/src/project-graph/utils/project-configuration-utils.js:240:46)
```

The problem comes from a typo here:
https://github.com/nrwl/nx/blob/32144bb702b07eddf29ed70055dfbcbcc0f4b11c/packages/nx/src/project-graph/utils/project-configuration-utils.ts#L347

which should be:
```ts
const excluded = exclude.some(...)
```

_I guess that this would be worth a test 😇_

### Expected Behavior

exclude option should work as documented 😊

### GitHub Repo

_No response_

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 21.7.2
OS     : darwin-arm64
yarn   : 3.5.1

nx                 : 18.2.3
@nx/js             : 18.2.3
@nx/jest           : 18.2.3
@nx/linter         : 18.2.3
@nx/eslint         : 18.2.3
@nx/workspace      : 18.2.3
@nx/angular        : 18.2.3
@nx/cypress        : 18.2.3
@nx/devkit         : 18.2.3
@nrwl/devkit       : 18.1.0-beta.2
@nx/eslint-plugin  : 18.2.3
@nx/node           : 18.2.3
@nx/plugin         : 18.2.3
@nx/rollup         : 18.2.3
@nrwl/tao          : 18.1.0-beta.2
@nx/vite           : 18.2.3
@nx/web            : 18.2.3
@nx/webpack        : 18.2.3
typescript         : 5.4.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
---------------------------------------
Community plugins:
@analogjs/vite-plugin-angular : 1.1.2
@monodon/rust                 : 1.4.0
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/devkit@18.1.0-beta.2
  - @nrwl/tao@18.1.0-beta.2
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by yjaaidi**
## Current Behavior
Using plugins' `exclude` option crashes.

## Expected Behavior
Plugins' `exclude` option should exclude files matching given patterns.

## Related Issue(s)
Fixes #22737

### CODE REVIEW

File: packages/nx/src/project-graph/utils/project-configuration-utils.ts [hunk 1]
```diff
@@ -344,7 +344,7 @@ export function createProjectConfigurations(
         }
 
         if (exclude) {
-          const excluded = include.some((excludedPattern) =>
+          const excluded = exclude.some((excludedPattern) =>
```
Comment (xiongemi) [inline packages/nx/src/project-graph/utils/project-configuration-utils.ts:347]: 👍  nice catch

File: packages/nx/src/project-graph/utils/project-configuration-utils.spec.ts [hunk 2]
```diff
@@ -5,12 +5,14 @@ import {
...
 import {
   ConfigurationSourceMaps,
+  createProjectConfigurations,
   isCompatibleTarget,
   mergeProjectConfigurationIntoRootMap,
   mergeTargetConfigurations,
   readProjectConfigurationsFromRootMap,
   readTargetDefaultsForTarget,
 } from './project-configuration-utils';
+import { CreateNodes, NxPluginV2 } from 'nx/src/utils/nx-plugin';
```
Comment (xiongemi) [inline packages/nx/src/project-graph/utils/project-configuration-utils.spec.ts:15]: ci failed due to lint. could you change this import to a relative path?

Comment (yjaaidi) [reply packages/nx/src/project-graph/utils/project-configuration-utils.spec.ts]: Indeed! Just noticed and fixed it 😊.
Still surprised that WebStorm didn't prefer the relative path 🤔

**Review by FrozenPandaz — APPROVED** [review]

**Review by FrozenPandaz — APPROVED** [review]
Thanks for the fix! LGTM :tada: 

Can you get CI to pass please?
