### PR TITLE
fix(react): add migration to install @nrwl/webpack if needed by Story…

### LINKED ISSUE #14453: Fresh setup for Storybook gives "Cannot find module 'webpack/lib/util/makeSerializable.js'" error
### Current Behavior

Getting the error after running `npx nx run <libName>:build-storybook` following a fresh test setup on NX v15.5.2:

```
 >  NX   Cannot find module 'webpack/lib/util/makeSerializable.js'

   Require stack:
   - /Users/mauris/test/node_modules/@storybook/react-docgen-typescript-plugin/dist/dependency.js
   - /Users/mauris/test/node_modules/@storybook/react-docgen-typescript-plugin/dist/plugin.js
   - /Users/mauris/test/node_modules/@storybook/react-docgen-typescript-plugin/dist/index.js
   - /Users/mauris/test/node_modules/@storybook/react/dist/cjs/server/framework-preset-react-docs.js
   - /Users/mauris/test/node_modules/@storybook/core-common/dist/cjs/presets.js
   - /Users/mauris/test/node_modules/@storybook/core-common/dist/cjs/index.js
   - /Users/mauris/test/node_modules/@storybook/core-server/dist/cjs/index.js
   - /Users/mauris/test/node_modules/@nrwl/storybook/src/executors/build-storybook/build-storybook.impl.js
   - /Users/mauris/test/node_modules/nx/src/config/workspaces.js
   - /Users/mauris/test/node_modules/nx/src/command-line/run.js
   - /Users/mauris/test/node_modules/nx/bin/run-executor.js
   Pass --verbose to see the stacktrace.
```

Steps:

1. Created new workspace named `test` using `npx create-nx-workspace --preset=react` 
2. Installed `@nrwl/storybook` using `npm install -D @nrwl/storybook`
3. Generated React library named `mode` using `npx nx g @nrwl/react:library`
4. Initialized `mode` with `npx nx g @nrwl/storybook:configuration mode`
5. Ran the Storybook build target with `npx nx run mode:build-storybook`
6. Got the error above. 

If I ran `npm ls webpack`, I get the following

```
├─┬ @storybook/builder-webpack5@6.5.15
│ └── UNMET PEER DEPENDENCY webpack@5.75.0 
```

### Expected Behavior

I should be able to run `build-storybook` target successfully. 

### Github Repo

_No response_

### Steps to Reproduce

Steps:

1. Created new workspace named `test` using `npx create-nx-workspace --preset=react` 
2. Installed `@nrwl/storybook` using `npm install -D @nrwl/storybook`
3. Generated React library named `mode` using `npx nx g @nrwl/react:library`
4. Initialized `mode` with `npx nx g @nrwl/storybook:configuration mode`
5. Ran the Storybook build target with `npx nx run mode:build-storybook`
6. Got the error above. 

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 14.21.2
   OS   : darwin arm64
   npm  : 6.14.17
   
   nx : 15.5.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.2
   @nrwl/js : 15.5.2
   @nrwl/linter : 15.5.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.5.2
   @nrwl/web : 15.5.2
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.5.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

_No response_

### Additional Information

_No response_

### LINKED ISSUE #14455: Fresh setup `build-storybook` shows error "Cannot find module  '@nrwl/webpack/src/utils/config'"
### Current Behavior

After running `npx nx run <libName>:build-storybook`, I got the following error output:

```

>  NX  Storybook builder starting ...

info => Cleaning outputDir: /Users/mauris/work/test/dist/storybook/mode
info => Loading presets
WARN   Failed to load preset: {"type":"presets","name":"/Users/mauris/work/test/node_modules/@nrwl/react/plugins/storybook/index.js"} on level 1
ERR! Error: Cannot find module '@nrwl/webpack/src/utils/config'
ERR! Require stack:
ERR! - /Users/mauris/work/test/node_modules/@nrwl/react/plugins/storybook/index.js
ERR! - /Users/mauris/work/test/node_modules/@storybook/core-common/dist/cjs/presets.js
ERR! - /Users/mauris/work/test/node_modules/@storybook/core-common/dist/cjs/index.js
ERR! - /Users/mauris/work/test/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /Users/mauris/work/test/node_modules/@nrwl/storybook/src/executors/build-storybook/build-storybook.impl.js
ERR! - /Users/mauris/work/test/node_modules/nx/src/config/workspaces.js
ERR! - /Users/mauris/work/test/node_modules/nx/src/command-line/run.js
ERR! - /Users/mauris/work/test/node_modules/nx/bin/run-executor.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:101:18)
ERR!     at Object.<anonymous> (/Users/mauris/work/test/node_modules/@nrwl/react/plugins/storybook/index.js:6:18)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!  Error: Cannot find module '@nrwl/webpack/src/utils/config'
ERR! Require stack:
ERR! - /Users/mauris/work/test/node_modules/@nrwl/react/plugins/storybook/index.js
ERR! - /Users/mauris/work/test/node_modules/@storybook/core-common/dist/cjs/presets.js
ERR! - /Users/mauris/work/test/node_modules/@storybook/core-common/dist/cjs/index.js
ERR! - /Users/mauris/work/test/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /Users/mauris/work/test/node_modules/@nrwl/storybook/src/executors/build-storybook/build-storybook.impl.js
ERR! - /Users/mauris/work/test/node_modules/nx/src/config/workspaces.js
ERR! - /Users/mauris/work/test/node_modules/nx/src/command-line/run.js
ERR! - /Users/mauris/work/test/node_modules/nx/bin/run-executor.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:101:18)
ERR!     at Object.<anonymous> (/Users/mauris/work/test/node_modules/@nrwl/react/plugins/storybook/index.js:6:18)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/Users/mauris/work/test/node_modules/@nrwl/react/plugins/storybook/index.js',
ERR!     '/Users/mauris/work/test/node_modules/@storybook/core-common/dist/cjs/presets.js',
ERR!     '/Users/mauris/work/test/node_modules/@storybook/core-common/dist/cjs/index.js',
ERR!     '/Users/mauris/work/test/node_modules/@storybook/core-server/dist/cjs/index.js',
ERR!     '/Users/mauris/work/test/node_modules/@nrwl/storybook/src/executors/build-storybook/build-storybook.impl.js',
ERR!     '/Users/mauris/work/test/node_modules/nx/src/config/workspaces.js',
ERR!     '/Users/mauris/work/test/node_modules/nx/src/command-line/run.js',
ERR!     '/Users/mauris/work/test/node_modules/nx/bin/run-executor.js'
ERR!   ]
ERR! }
```

### Expected Behavior

No error should be shown

### Github Repo

_No response_

### Steps to Reproduce

1. Run `npx nx run <libName>:build-storybook` on a newly setup workspace.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 14.21.2
   OS   : darwin arm64
   npm  : 6.14.17
   
   nx : 15.5.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.2
   @nrwl/js : 15.5.2
   @nrwl/linter : 15.5.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.5.2
   @nrwl/web : 15.5.2
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.5.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jaysoo**
…book

## Related Issue(s)

Fixes #14455

### CODE REVIEW

**Comment by mauris** [comment]
Great one @jaysoo - any idea if we should also patch the generators to add webpack if required? Especially during Storybook configuration generator

File: packages/storybook/src/migrations/update-15-5-3/ensure-webpack-package.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+// Add @nrwl/webpack as needed.
+// See: https://github.com/nrwl/nx/issues/14455
+export default async function update(tree: Tree) {
+  const projects = getProjects(tree);
+  const reactPlugin = '@nrwl/react/plugins/storybook';
+  let shouldInstall = false;
+
+  for (const [, config] of projects) {
+    let sbConfigPath = joinPathFragments(config.root, '.storybook/main.ts');
```
Comment (mandarini) [inline packages/storybook/src/migrations/update-15-5-3/ensure-webpack-package.ts:18]: Ideally, instead of `joinPathFragments(config.root, '.storybook/main.ts')` it should look for the storybook target (by searching for the `@nrwl/storybook:storybook` executor) and get the `configDir`, but I guess it's overengineering in this case. So I think it looks good.

**Review by mandarini — APPROVED** [review]
Looks good to me! Added a small comment, but maybe it's overengineering in this case.
