### PR TITLE
fix(core): wrapped angular schematics should be able to update newly created standalone projects

### LINKED ISSUE #6342: workspace generators + project generation + wrapAngularDevkitSchematic = incompatible
## Current Behavior

It is not possible to create workspace generators which create projects and update them within the same run, if that update is coming via a wrapped schematic and the workspace is leveraging distributed configuration (`project.json`).

## Expected Behavior

Leveraging `project.json` instead of centralized `workspace.json` should not have any impact on workspace generators.

## Steps to Reproduce

Create a workspace generator which attempts to create a new component library _and_ a component within it:

```ts
import { strings } from "@angular-devkit/core";
import { libraryGenerator } from "@nrwl/angular/generators";
import { UnitTestRunner } from "@nrwl/angular/src/utils/test-runners";
import { normalizePath, Tree } from "@nrwl/devkit";
import { Linter } from "@nrwl/linter";
import { wrapAngularDevkitSchematic } from "@nrwl/tao/src/commands/ngcli-adapter";
import { join } from "path";

interface Schema {
  name: string;
}

export default async function (tree: Tree, options: Schema) {
  const { name } = options;
  const sharedComponentsDir = "shared/components";

  await libraryGenerator(tree, {
    name,
    directory: sharedComponentsDir,
    strict: true,
    linter: Linter.EsLint,
    unitTestRunner: UnitTestRunner.Jest,
    standaloneConfig: true, // <------------------------- key config for repro, use project.json
  });

  const createdProjectName = normalizePath(
    join(sharedComponentsDir, strings.dasherize(name))
  ).replace(/\//g, "-");

  const schematicsAngularComponentGenerator = wrapAngularDevkitSchematic(
    "@schematics/angular",
    "component"
  );
  await schematicsAngularComponentGenerator(tree, {
    name,
    module: `${createdProjectName}.module.ts`,
    project: createdProjectName,
    style: "scss",
    changeDetection: "OnPush",
    displayBlock: true,
    export: true,
  });
}
```

Run it and you will get an exception that the new project's `project.json` does not exist:

```sh
ENOENT: no such file or directory, open 'PATH/TO/project.json'
```

### PR DESCRIPTION
**Pull request by AgentEnder**
Wrapped angular schematics inside of generators should be able to update a newly created standalone
project configuration. This is currently something that fails (see workspace schematic in linked issue).

Fixes #6342

### CODE REVIEW

**Review by FrozenPandaz — APPROVED** [review]

File: packages/tao/src/commands/ngcli-adapter.ts [hunk 1]
```diff
@@ -472,9 +472,20 @@ export class NxScopeHostUsedForWrappedSchematics extends NxScopedHost {
...
+        return of(Buffer.from(match.content));
+      } else if (
+        // found a change to workspace config, and reading a project config file
+        basename(path) === 'project.json' &&
+        findWorkspaceConfigFileChange(this.host)
+      ) {
+        return of(this.host.read(path));
+      } else {
+        // found neither, use default read method
+        super.read(path);
```
Comment (JamesHenry) [inline packages/tao/src/commands/ngcli-adapter.ts:487]: @AgentEnder @FrozenPandaz doesn't this code path also need a return statement?

Comment (AgentEnder) [reply packages/tao/src/commands/ngcli-adapter.ts:487]: Thanks @JamesHenry... It definitely does. I'll put in a cleanup pr and get it merged.
