### PR TITLE
fix(misc): ensure workspace directory is normalized correctly

### LINKED ISSUE #16841: Creating a workspace with '_' underscore character fails
### Current Behavior

Creating a new workspace whose name contains "_" character fails because at some places the underscore is replaced with a dash '-' and the dash is used to locate files in the filesystem that does not exists.

### Expected Behavior

A new project shall be created, either with '-' or with '_' but it should be created.

### GitHub Repo

_No response_

### Steps to Reproduce

1. open terminal and launch `npx create-nx-workspace@latest`
2. when asked for the Repository name type `da_frontend`
3. an error is raised

### Nx Report

```shell
No specific report is generated at this time see failure logs
```

### Failure Logs

```shell
ihr@mbp-de-ignacio rust % npx create-nx-workspace@latest

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Choose what to create                 · package-based
✔ Repository name                       · da_frontend
✔ Enable distributed caching to make your CI faster · Yes

 >  NX   Creating your v16.1.1 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Successfully created the workspace: da-frontend.
⠋ Setting up NxCloudnode:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/ihr/rust/da-frontend/error.log'
    at Object.openSync (node:fs:590:3)
    at writeFileSync (node:fs:2202:35)
    at /Users/ihr/.npm/_npx/505743838affa773/node_modules/create-nx-workspace/src/utils/child-process-utils.js:36:40
    at exithandler (node:child_process:410:5)
    at ChildProcess.errorhandler (node:child_process:422:5)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/ihr/rust/da-frontend/error.log'
}
```
```


### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leosvelperez**
## Current Behavior

When creating a new workspace a providing a repo name with `_` in it, an error is thrown due to a mismatch in the directory name used by the `new` generator vs the `create-nx-workspace` functionality. This mainly happens because the `new` generator is invoked with the non-normalized name and this generator wrongly sets the `directory` to that value instead of setting it with the normalized name.

## Expected Behavior

Creating a new workspace providing a repo name with `_` should not throw an error.

## Related Issue(s)

Fixes #16841

### CODE REVIEW

File: packages/create-nx-workspace/src/create-empty-workspace.ts [hunk 1]
```diff
@@ -32,15 +32,16 @@ export async function createEmptyWorkspace<T extends CreateWorkspaceOptions>(
...
+  const directory = options.name;
 
   const args = unparse({
     ...options,
   }).join(' ');
 
   const pmc = getPackageManagerCommand(packageManager);
 
-  const command = `new ${directory} ${args}`;
+  const command = `new ${args}`;
```
Comment (leosvelperez) [inline packages/create-nx-workspace/src/create-empty-workspace.ts:44]: The `${directory}` here was useless. The `name` arg takes precedence over the positional arg and overwrites it.

I'm normalizing the `name` option above, which is a known and required option, so we don't rely on the `new` generator rederiving it. We could also pass the `directory` option directly, but that option is not in the `new` generator schema for some reason.

**Review by AgentEnder — APPROVED** [review]
