### PR TITLE
fix(nextjs): include peer dependencies in built package.json

### LINKED ISSUE #4506: Peer dependencies are missing in next.js build package.json
## Current Behavior

When building next.js applications, peer dependencies of dependencies that are installed are missing in the generated package.json file. Two examples:

To use `@apollo/client`, one need to also install `graphql` as it is a peerDependency of `@apollo/client`
```shell
yarn add @apollo/client graphql
```

In the code, `graphql` will never be required, resulting in it not being added to `package.json` in the build.

The same goes for `@emotion/styled`, it requires a peer dependency of `@emotion/react`, which is never required in the code and thus, is missing in the package.json.

Those are only two examples that I have in my app but there are countless others.

## Expected Behavior

I expect the `package.json` to include peerDependencies or to allow me to specify which extra dependencies I want.

## Steps to Reproduce

```shell
npx create-nx-workspace depexample --preset empty --nx-cloud 0
cd depexample
yarn remove @nrwl/workspace --dev
yarn add @nrwl/next @nrwl/workspace
nx g @nrwl/next:application --name nextapp --style @emotion/styled
yarn add @apollo/client graphql
echo "import '@apollo/client'" >> apps/nextapp/pages/_app.tsx
nx build nextapp
```

To mimic running in a container, just move the build folder to outside the Monorepo and do a yarn install.

### Failure Logs

And when you run the application:

```
yarn start
```

```
Error: Cannot find module 'graphql'
Require stack:
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 14.4.0
  OS   : darwin x64
  yarn : 1.22.4
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.2
  @nrwl/cypress : 11.1.2
  @nrwl/devkit : 11.1.2
  @nrwl/eslint-plugin-nx : 11.1.2
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.2
  @nrwl/linter : 11.1.2
  @nrwl/nest : Not Found
  @nrwl/next : 11.1.2
  @nrwl/node : Not Found
  @nrwl/react : 11.1.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.2
  @nrwl/web : 11.1.2
  @nrwl/workspace : 11.1.2
  typescript : 4.0.5
```

### PR DESCRIPTION
**Pull request by kirjai**
## Current Behavior

For Next.js apps - we generate a `package.json` file during the `build`. The dependencies are populated from the dependency graph. However, that misses out on peer dependencies of the "direct" dependencies.

Example from #4506 is `@apollo/client` and `graphql` dependencies. `graphql` is a peer dependency of `@apollo/client`. Developers don't usually need to import `graphql` in their application code, however it's used by `@apollo/client` dependency.

## Expected Behavior

Peer dependencies of dependencies should be included in the generated `package.json`

## Related Issue(s)

Fixes #4506 #4867

### CODE REVIEW

File: packages/next/src/executors/build/lib/create-package-json.ts [hunk 1]
```diff
@@ -58,13 +94,7 @@ export function createPackageJson(
     scripts: {
       start: 'next start',
     },
-    dependencies: {
-      ...dependencies,
-      // peer deps of next, so we need to add them here
-      react: rootPackageJson.dependencies['react'],
-      'react-dom': rootPackageJson.dependencies['react-dom'],
-      next: rootPackageJson.dependencies['next'],
```
Comment (kirjai) [inline packages/next/src/executors/build/lib/create-package-json.ts:66]: these peer dependencies are now detected automatically

**Comment by kirjai** [comment]
There's no dedicated e2e test for this change, but it is [tested across multiple tests](https://github.com/nrwl/nx/blob/master/e2e/next/src/next.test.ts#L373)

**Comment by vsavkin** [comment]
Currently we have two places (at least two places I know of :) ) where we genereate the list of deps:

1. packages/node/src/utils/generate-package-json.ts
2. packages/next/src/executors/build/lib/create-package-json.ts

There is no reason for them to be different, right? Can we move this generatePackageJson utility into @nrwl/workspace so both node and next (and other things in the future) can use it?

Maybe we can create workspace/src/utilities/generate-package-json?

File: e2e/node/src/node.test.ts [hunk 2]
```diff
@@ -185,6 +185,9 @@ describe('Build Node apps', () => {
         dependencies: {
           '@nestjs/common': '^7.0.0',
           '@nestjs/core': '^7.0.0',
+          '@nestjs/platform-express': '^7.0.0',
+          'reflect-metadata': '^0.1.13',
+          rxjs: '~6.6.3',
```
Comment (kirjai) [inline e2e/node/src/node.test.ts:190]: these dependencies are now detected, as they're peer dependencies of dependencies that are used by the application code

**Comment by slinkardbrandon** [comment]
I believe this may be the cause of the weirdness I'm seeing today, I have `peerDependencies` that have their own `peerDependencies`, I'm publishing a library for these and I expect that the peer dependencies would _not_ be included in the second library.

Here's an example:

1. @scoped/lib1 - `peerDependencies` - `npmLib1, npmLib2`
2. @scoped/lib2 - `peerDependencies` - `@scoped/lib1`

Today:

`@scoped/lib2` has dependencies of `npmLib1, npmLib2` and peer deps of `@scoped/lib1`.

I believe it should not have these `npmLib` dependencies at all as its inferred as a requirement of using `scoped/lib1` and installing them again here is unnecessary duplication from my understanding. 

Is it possible to turn this feature off?
