### PR TITLE
fix(core): provide better error message if we cannot read a file when finding imports

### LINKED ISSUE #19615: NX   Daemon process terminated and closed the connection
### Current Behavior

Is any idea about how to resolved  (NX   Daemon process terminated and closed the connection error). i have tried lot . reset, restore, clear cache, reinstall, migrate, etc. and i have mallualy start the daemon. daemon was started but while run the nx serve command again got the same error. its dosen't work for me. it was totally blocking

 >  NX   Daemon process terminated and closed the connection

   Please rerun the command, which will restart the daemon.
   If you get this error again, check for any errors in the daemon process logs found in: D:\Partnersoft\Dev\Workspace\Thronex\MicroFrontend-NX-Monorepo\thronex\node_modules\.cache\nx\d\daemon.log

Daemon.log

[NX Daemon Server] - 2023-10-14T08:59:49.121Z - Started listening on: \\.\pipe\nx\C:\Users\sunil\AppData\Local\Temp\d4b9ff6fc420976aea65\d.sock
[NX Daemon Server] - 2023-10-14T08:59:49.126Z - [WATCHER]: Subscribed to changes within: d:\Partnersoft\Dev\Workspace\Thronex\MicroFrontend-NX-Monorepo\thronex (native)
[NX Daemon Server] - 2023-10-14T08:59:49.138Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-10-14T08:59:49.142Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2023-10-14T08:59:49.143Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-10-14T08:59:49.146Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-10-14T08:59:49.242Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-10-14T08:59:49.244Z - [REQUEST]: 
[NX Daemon Server] - 2023-10-14T08:59:49.244Z - [REQUEST]: 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', packages\nx\src\native\plugins\js\ts_import_locators.rs:450:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[NX Daemon Server] - 2023-10-14T09:00:11.943Z - Started listening on: \\.\pipe\nx\C:\Users\sunil\AppData\Local\Temp\d4b9ff6fc420976aea65\d.sock
[NX Daemon Server] - 2023-10-14T09:00:11.945Z - [WATCHER]: Subscribed to changes within: D:\Partnersoft\Dev\Workspace\Thronex\MicroFrontend-NX-Monorepo\thronex (native)
[NX Daemon Server] - 2023-10-14T09:00:11.954Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-10-14T09:00:11.958Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-10-14T09:00:11.960Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-10-14T09:00:12.023Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-10-14T09:00:12.023Z - [REQUEST]: 
[NX Daemon Server] - 2023-10-14T09:00:12.023Z - [REQUEST]: 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', packages\nx\src\native\plugins\js\ts_import_locators.rs:450:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[NX Daemon Server] - 2023-10-14T09:01:59.435Z - Started listening on: \\.\pipe\nx\C:\Users\sunil\AppData\Local\Temp\d4b9ff6fc420976aea65\d.sock
[NX Daemon Server] - 2023-10-14T09:01:59.447Z - [WATCHER]: Subscribed to changes within: D:\Partnersoft\Dev\Workspace\Thronex\MicroFrontend-NX-Monorepo\thronex (native)
[NX Daemon Server] - 2023-10-14T09:01:59.449Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-10-14T09:01:59.450Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-10-14T09:01:59.453Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-10-14T09:01:59.510Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-10-14T09:01:59.510Z - [REQUEST]: 
[NX Daemon Server] - 2023-10-14T09:01:59.510Z - [REQUEST]: 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', packages\nx\src\native\plugins\js\ts_import_locators.rs:450:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[NX Daemon Server] - 2023-10-14T09:18:48.103Z - Started listening on: \\.\pipe\nx\C:\Users\sunil\AppData\Local\Temp\d4b9ff6fc420976aea65\d.sock
[NX Daemon Server] - 2023-10-14T09:18:48.105Z - [WATCHER]: Subscribed to changes within: D:\Partnersoft\Dev\Workspace\Thronex\MicroFrontend-NX-Monorepo\thronex (native)
[NX Daemon Server] - 2023-10-14T09:18:48.112Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-10-14T09:18:48.114Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-10-14T09:18:48.116Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-10-14T09:18:48.120Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-10-14T09:18:48.188Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-10-14T09:18:48.188Z - [REQUEST]: 
[NX Daemon Server] - 2023-10-14T09:18:48.188Z - [REQUEST]: 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', packages\nx\src\native\plugins\js\ts_import_locators.rs:450:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

NX version :16.10.0

### Expected Behavior
Run or Serve the host or remote application

NX version :16.10.0

### GitHub Repo

_No response_

### Steps to Reproduce

While running the project we got the error (NX   Daemon process terminated and closed the connection error).

NX version :16.10.0

### Nx Report

```shell
Not able to generate. while running the nx report also getting some error (NX   Daemon process terminated and closed the connection error).
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Cammisuli**
## Current Behavior

When trying to read files that are not valid utf-8, Nx panics without giving more information on which file is invalid

## Expected Behavior

Invalid files are included in the error message

## Related Issue(s)

Fixes #19615

### CODE REVIEW

File: packages/nx/src/native/plugins/js/ts_import_locators.rs [hunk 1]
```diff
@@ -592,7 +597,7 @@ fn find_imports(project_file_map: HashMap<String, Vec<String>>) -> Vec<ImportRes
 
     files_to_process
         .into_par_iter()
-        .filter_map(process_file)
+        .filter_map(|file| process_file(file).transpose())
         .collect()
```
Comment (FrozenPandaz) [inline packages/nx/src/native/plugins/js/ts_import_locators.rs:601]: Can we return 1 error with a list of all the failed files?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
