### PR TITLE
fix(angular): show a nicer error when running nx in an angular workspace

### LINKED ISSUE #2021: Nx errors when run in a workspace generated by the Angular CLI
## Expected Behavior

Some kind of output which indicates that Nx is aware it can't be used in the current workspace. Possibly even a message which tells the user how to upgrade the current workspace to an Nx workspace?

At the very least, _not_ an error.

## Current Behavior

```bash
▶ nx
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '<cut for brevity>/node_modules/@nrwl/cli/bin/nx.js'
```

### Steps to Reproduce

Run `nx` in a workspace generated by the Angular CLI.

e.g. 

`ng generate new-workspace --create-application=false`
`cd new-workspace`
`nx`

This is far too easily done if you're playing with Angular CLI and Nx workspaces side by side :)

### PR DESCRIPTION
**Pull request by catfireparty**
Adds a slightly nicer error when we run in an Angular workspace by accident:

Screenshot 2020-07-24 at 10 11 57

Fixes #2021

### CODE REVIEW

File: packages/cli/lib/init-global.ts [hunk 1]
```diff
@@ -11,14 +12,26 @@ export function initGlobal() {
...
+      require(localNx);
+    } else {
+      output.log({
+        title: `The current directory isn't part of an Nx workspace.`,
+        bodyLines: [
+          `To convert an Angular workspace to Nx run:`,
+          chalk.bold.white(`ng add @nrwl/workspace`),
+        ],
+      });
+      process.exit(0);
```
Comment (FrozenPandaz) [inline packages/cli/lib/init-global.ts:33]: I think this should be non-zero since it didn't actually do the thing the user wanted to do :thinking:?

File: packages/cli/lib/init-global.ts [hunk 2]
```diff
@@ -11,14 +12,26 @@ export function initGlobal() {
...
+    const localNx = path.join(
       workspace.dir,
       'node_modules',
       '@nrwl',
       'cli',
       'bin',
       'nx.js'
-    ));
+    );
+    if (fs.existsSync(localNx)) {
```
Comment (FrozenPandaz) [inline packages/cli/lib/init-global.ts:23]: Is this also going to show when user forgets to npm install? If so, the message should say that as a possible cause.

Comment (jdpearce) [reply packages/cli/lib/init-global.ts:23]: Good point. I'll update the message.

File: packages/cli/lib/init-global.ts (hunk 1 above)
Comment (jdpearce) [reply packages/cli/lib/init-global.ts:33]: Yup, fair enough. Might change this to an error message then.

**Review by brandonroberts — APPROVED** [review]
