### PR TITLE
fix(core): add timeouts to GitHub push flow to prevent CLI hangs

### LINKED ISSUE #34482: `npx create-nx-workspace` produces `error.log` file
### Current Behavior

`npx create-nx-workspace` produces error.log file with `'gh' is not recognized` error

### Expected Behavior

No `error.log` files must be present in generated project 

### GitHub Repo

_No response_

### Steps to Reproduce

1. `npx create-nx-workspace@22.5.1 nx2251emptytemplate --template nrwl/empty-template`
2. `cat nx2251emptytemplate/error.log`

### Nx Report

```shell
Node           : 22.21.1
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.9.4
daemon         : Available

nx (global)    : 22.5.1
nx             : 22.5.0
@nx/js         : 22.5.0
@nx/workspace  : 22.5.0
@nx/devkit     : 22.5.0
typescript     : 5.9.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
---------------------------------------
Cache Usage: 0.00 B / 47.41 GB
```

### Failure Logs

```shell
> npx create-nx-workspace@22.5.1 nx2251emptytemplate --template nrwl/empty-template

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]


 NX   Creating your v22.5.1 workspace.

✔ Successfully created the workspace: C:\temp\nx2251emptytemplate

 NX   Could not push.


+----------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                    |
|   Finish your set up here: https://cloud.nx.app/setup/connect-workspace/manual?accessToken=undefined&source=create-nx-workspace-success-ci-setup   |
|                                                                                                                                                    |
+----------------------------------------------------------------------------------------------------------------------------------------------------+



> cat nx2251emptytemplate/error.log

'gh' is not recognized as an internal or external command,
operable program or batch file.
```

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jaysoo**
## Current Behavior

The `pushToGitHub` flow in create-nx-workspace calls `gh api user` and `gh repo create --push` with no timeout. When `gh` CLI is wrapped by 1Password SSH agent, credential managers with GUI prompts, SSH keys with passphrases, or corporate SSO, these calls hang indefinitely — freezing the CLI after workspace creation with no indication of what's happening.

YTD data shows a **96.3% failure rate** (16,426 failures out of 17,058 push attempts).

## Expected Behavior

- The initial `gh` auth check (`gh api user`) has a **2-second timeout**. If `gh` is slow to respond (hung on credential prompt), the push flow is skipped gracefully instead of freezing.
- The `gh repo create --push` command has a **15-second timeout**. If the push hangs, the process is killed and a helpful message is shown.
- If `gh` CLI is not installed, the push flow is skipped immediately without attempting any network calls.
- Error messages now include actionable fallback: *"You can push manually with: git push -u origin main"*.

The error is now captured in `recordStat` as well, so when users see this we'll also see it in our stats.

image

## Related Issue(s)

Fixes #34482, NXC-4141

### CODE REVIEW

File: packages/create-nx-workspace/src/utils/git/git.ts [hunk 1]
```diff
@@ -289,16 +313,28 @@ export async function pushToGitHub(
...
+    } else if (isTimedOut) {
+      failReason = 'gh push timed out';
+      output.log({ title: pushManuallyMsg });
+    } else {
+      const msg = e instanceof Error ? e.message : String(e);
+      failReason = msg.split('\n')[0].slice(0, 200);
+      output.log({ title: pushManuallyMsg });
+    }
+
+    return { status: VcsPushStatus.FailedToPushToVcs, failReason };
```
Comment (FrozenPandaz) [inline packages/create-nx-workspace/src/utils/git/git.ts]: Can this throw an Error instead of returning `FailedToPushToVcs`? I think that would be better?

File: packages/create-nx-workspace/src/utils/git/git.ts [hunk 2]
```diff
@@ -190,6 +202,11 @@ ${options.connectUrl}
   }
 }
 
+export interface PushToGitHubResult {
+  status: VcsPushStatus;
+  failReason?: string;
+}
+
 export async function pushToGitHub(
```
Comment (FrozenPandaz) [inline packages/create-nx-workspace/src/utils/git/git.ts:229]: Also, while you're in here... there's this github issue that I think is related to errors from pushing to github here: https://github.com/nrwl/nx/issues/34482 could you take a look please?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

File: packages/create-nx-workspace/src/utils/git/git.ts (hunk 1 above)
Comment (jaysoo) [reply packages/create-nx-workspace/src/utils/git/git.ts]: I'm wary of failing CNW due to push errors, because right now we still mark it as success/complete but just with a message that need to push manually. If we throw `CnwError` then we would mark it as failed.

Comment (FrozenPandaz) [reply packages/create-nx-workspace/src/utils/git/git.ts]: Yeah, not CnwError.. we have other error types for Github which are handled.. so it would follow the existing pattern

**Review by FrozenPandaz — APPROVED** [review]
