### PR TITLE
fix(web): ensure file server works on windows

### LINKED ISSUE #9444: Web file server halts on Windows
## Current Behavior
Running serve with file-server halts on Windows

## Expected Behavior
Running serve with file-server on Windows should be successful

## Steps to Reproduce
1. Generate default `web components` workspace
2. Change app's serve executor to `@nrwl/web:file-server`
3. Run serve

### Root cause
Possibly https://github.com/nrwl/nx/pull/9330

cc @FrozenPandaz 

## Logs
```
Error: spawnSync npx ENOENT
    at Object.spawnSync (node:internal/child_process:1111:20)
    at spawnSync (node:child_process:814:24)
    at execFileSync (node:child_process:860:15)
    at run (C:\Users\miro\Dev\web-test\node_modules\@nrwl\web\src\executors\file-server\file-server.impl.js:107:44)
    at fileServerExecutor_1 (C:\Users\miro\Dev\web-test\node_modules\@nrwl\web\src\executors\file-server\file-server.impl.js:121:5)
    at fileServerExecutor_1.next (<anonymous>)
    at resume (C:\Users\miro\Dev\web-test\node_modules\tslib\tslib.js:225:48)
    at C:\Users\miro\Dev\web-test\node_modules\tslib\tslib.js:224:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (C:\Users\miro\Dev\web-test\node_modules\tslib\tslib.js:224:67) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync npx',
  path: 'npx',
  spawnargs: [ 'nx', 'run', 'web-app:build', '--parallel' ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```

### Environment
   Node : 16.14.0
   OS   : win32 x64
   npm  : 8.5.0
   
   nx : 13.9.4
   @nrwl/angular : undefined
   @nrwl/cypress : 13.9.4
   @nrwl/detox : undefined
   @nrwl/devkit : 13.9.4
   @nrwl/eslint-plugin-nx : 13.9.4
   @nrwl/express : undefined
   @nrwl/jest : 13.9.4
   @nrwl/js : 13.9.4
   @nrwl/linter : 13.9.4
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.6
   @nrwl/nx-plugin : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/web : 13.9.4
   @nrwl/workspace : 13.9.4
   typescript : 4.5.5
   rxjs : 6.5.5

### PR DESCRIPTION
**Pull request by meeroslav**
In https://github.com/nrwl/nx/pull/9330 we replaced `exec` with `execFile` which requires explicit shell property set on Windows otherwise commands fail with `ENOENT`.

## Related Issue(s)

Fixes #9444 and nightly build on Windows

### CODE REVIEW

File: packages/workspace/src/tasks-runner/cache.ts [hunk 1]
```diff
@@ -190,14 +190,19 @@ export class Cache {
     }
 
     return new Promise((res, rej) => {
-      execFile('cp', ['-a', src, dirname(directory)], (error) => {
-        if (!error) {
-          res();
-        } else {
-          this.useFsExtraToCopyAndRemove = true;
-          copy(src, directory).then(res, rej);
+      execFile(
```
Comment (sorin-davidoi) [inline packages/workspace/src/tasks-runner/cache.ts:193]: This will basically reintroduce code execution, as outputPath is not sanitized.

From https://nodejs.org/api/child_process.html#child_processexecfilesyncfile-args-options:

> If the `shell` option is enabled, do not pass unsanitized user input to this function. Any input containing shell metacharacters may be used to trigger arbitrary command execution.

Comment (meeroslav) [reply packages/workspace/src/tasks-runner/cache.ts:193]: What alternative would you suggest? The current solution does not work on Windows.

We can perhaps try something like https://www.npmjs.com/package/cross-spawn that only targets Windows environment.

Comment (sorin-davidoi) [reply packages/workspace/src/tasks-runner/cache.ts:193]: I'm not sure I understand why this is failing on Windows, and I don't have that OS at hand debug. Is it expecting a full path to the file?

Comment (sorin-davidoi) [reply packages/workspace/src/tasks-runner/cache.ts:193]: Absent that, maybe at the least we can set `shell: true` only when running in Windows? That would at least limit the code execution to that operating system.

Comment (meeroslav) [reply packages/workspace/src/tasks-runner/cache.ts:193]: It's expecting full file name e.g. `npx.cmd` if `shell` option is not set.

Comment (meeroslav) [reply packages/workspace/src/tasks-runner/cache.ts]: Copy and remove can stay as they are, but web file server still needs a fix

Comment (sorin-davidoi) [reply packages/workspace/src/tasks-runner/cache.ts]: Alright, as long as it's clear that this is introducing the vulnerability back.
