### PR TITLE
fix(linter): avoid secondary entrypoints flagging as circular dependencies

### LINKED ISSUE #8059: Rule 'enforce-module-boundaries' should not error 'noSelfCircularDependencies' for angular libs with secondary entrypoints
## Current Behavior
When using angular libraries with secondary entrypoints and importing things from another secondary entrypoint of the same library, the eslint rule 'enforce-module-boundaries' errors with the violation 'noSelfCircularDependencies'.

## Expected Behavior
The rule 'enforce-module-boundaries' should not get violated by a secondary entrypoint importing another entrypoints exports, because those are complete independant modules, in theory.

## Steps to Reproduce
See PR [in https://github.com/nrwl/nx-examples.](https://github.com/nrwl/nx-examples/pull/179)

Basic steps for reproduction:
1. Generate angular library (Note that it has to generate a package.json and allow secondary entrypoints)
nx generate @nrwl/angular:library --name=example-lib --importPath=@example/lib --publishable

2. Generate two secondary entrypoints for library (models/abstract and models/implementations)
nx generate @nrwl/angular:library-secondary-entry-point --name=models/abstract --library=example-lib --skipModule
nx generate @nrwl/angular:library-secondary-entry-point --name=models/implementations --library=example-lib --skipModule

3. Create some exported file in first entrypoint. Example example-model.ts:

```typescript
export interface ExampleModel {
  someField: string;
}
```

4. Use exported file in second entrypoint:

```typescript
import {ExampleModel as IExampleModel} from '@example/lib/models/abstract';

export class ExampleModel implements IExampleModel {
  someField!: string;
}
```

5. Second file in secondary entrypoint should get a linting error

### Failure Logs
ESLint: Projects should use relative imports to import from other files within the same project. Use &quot;./path/to/file&quot; instead of import from &quot;@example/lib/models/abstract&quot; (@nrwl/nx/enforce-module-boundaries)

image

### Environment
```

>  NX  Report complete - copy this into the issue template

  Node : 14.17.6
  OS   : win32 x64
  yarn : 1.22.15

  nx : 13.2.0-rc.4
  @nrwl/angular : 13.2.0-rc.4
  @nrwl/cli : 13.2.0-rc.4
  @nrwl/cypress : 13.2.0-rc.4
  @nrwl/devkit : 13.2.0-rc.4
  @nrwl/eslint-plugin-nx : 13.2.0-rc.4
  @nrwl/express : undefined
  @nrwl/jest : 13.2.0-rc.4
  @nrwl/linter : 13.2.0-rc.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : 13.2.0-rc.4
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.0-rc.4
  @nrwl/web : 13.2.0-rc.4
  @nrwl/workspace : 13.2.0-rc.4
  @nrwl/storybook : 13.2.0-rc.4
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.5.5
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.2
         @angular/common: 13.0.2
         @angular/compiler: 13.0.2
         @angular/core: 13.0.2
         @angular/forms: 13.0.2
         @angular/platform-browser: 13.0.2
         @angular/platform-browser-dynamic: 13.0.2
         @angular/router: 13.0.2
         @ngrx/component-store: 13.0.1
         @ngrx/effects: 13.0.1
         @ngrx/entity: 13.0.1
         @ngrx/router-store: 13.0.1
         @ngrx/store: 13.0.1
         @angular-devkit/build-angular: 13.0.3
         @angular/cli: 13.0.3
         @angular/compiler-cli: 13.0.2
         @angular/language-service: 13.0.2
         @ngrx/store-devtools: 13.0.1
```

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

Importing from secondary entry points is flagging as a circular dependency by eslint-module-boundaries
## Expected Behavior

Importing from secondary entry points should not flag as a circular dependency by eslint-module-boundaries

## Related Issue(s)

ISSUES CLOSED: #8059

### CODE REVIEW

File: packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts [hunk 1]
```diff
@@ -232,7 +233,19 @@ export default createESLintRule<Options, MessageIds>({
       // same project => allow
       if (sourceProject === targetProject) {
         // we only allow relative paths within the same project
-        if (!allowCircularSelfDependency && !isRelativePath(imp)) {
+        // and if it's not a secondary entrypoint in an angular lib
+        const ngPackageExistsForSecondaryEntry = sourceFilePath.endsWith(
```
Comment (Coly010) [inline packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts:237]: @meeroslav @leosvelperez This is a very specific fix for Angular. I'm not sure if the same problem exists with standard libraries as their secondary entry points are likely defined in the package.json. It might still exist.

There also may be a better way to solve this. Using a glob would be safer. I'm open to suggestions!

Comment (meeroslav) [reply packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts:237]: I don't think check for src/index.ts is necessary. Project config might override this so it wouldn't work in every scenario anyway.

**Review by meeroslav — CHANGES_REQUESTED** [review]
Please check my comment

File: packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts (hunk 1 above)
Comment (Coly010) [reply packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts:237]: Part of the problem is that project config knows nothing about the secondary entrypoint, so some assumptions have to be made. I'm making the assumption that the entry file is index.ts because that is what is generated by the secondary endpoint generator.

I'll move the logic into a util! :)

Comment (Coly010) [reply packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts:237]: I also cannot move it into util in `linter` package as it creates a circular dependency. 
I'll place it in `eslint-plugin-nx`
