### PR TITLE
fix(core): fix handling of simple dependsOn target string

### LINKED ISSUE #16931: `dependsOn` shorthand broken when target name matches name of a project in the same repo.
### Current Behavior

Noticed this after the Nx v16 update - a number of our `dependsOn` configurations in various projects in our Nx monorepo were failing to run.

Example: A given repo has two projects: `a` and `core`. Project `a` has a `build` target and a `core` target. The `build` target has `"dependsOn": ["core"]` set, however whenever `nx build a` is run, the `core` target is not invoked. Caching isn't the cause here as far as I can tell, given that the `core` target is not listed under cacheableOperations in nx.json.

Using the slightly more explicit configuration of `"dependsOn": [{ "target": "core" }]` works as expected.

### Expected Behavior

Prior to the Nx v16 update, the `core` target in the above example would be correctly invoked before the `build` target.

### GitHub Repo

https://github.com/acburdine/nx-dependson-repro

### Steps to Reproduce

1. Clone the above repo
2. Run `nx build test`, see that the `core` target is not invoked, though the `core-2` target _is_ invoked.
3. Run `nx build test-2`, see that both the `core` and `core-2` targets are invoked.

### Nx Report

```shell
Node   : 18.15.0
OS     : darwin x64
npm    : 9.6.3
Hasher : Native

nx (global)    : 16.1.3
nx             : 16.1.4
@nx/js         : 16.1.4
@nx/workspace  : 16.1.4
@nx/devkit     : 16.1.4
@nrwl/tao      : 16.1.4
typescript     : 5.0.4
```

### Failure Logs

_No response_

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

If I had to guess, this may be related to the changes in v16 allowing for dependsOn configurations to specify explicit projects, rather than just `dependencies` or `self`.

### PR DESCRIPTION
**Pull request by acburdine**
Fixes #16931
- if a project has a `dependsOn` string with only a target that has the same name as another project, it is now treated correctly as a reference to a target in the same project

This was the simplest approach I could think of to fix the issue and ensure the functionality remains the same as is currently documented.

### CODE REVIEW

File: packages/nx/src/tasks-runner/utils.ts [hunk 1]
```diff
@@ -69,6 +69,13 @@ export function expandDependencyConfigSyntaxSugar(
 
   // Support for both `project:target` and `target:with:colons` syntax
   const [maybeProject, ...segments] = splitByColons(targetString);
+
+  // if no additional segments are provided, then the string references
+  // a target of the same project
+  if (!segments.length) {
+    return { target: maybeProject };
+  }
```
Comment (AgentEnder) [inline packages/nx/src/tasks-runner/utils.ts:77]:
```suggestion
  if (segments.length == 1) {
    return { target: maybeProject };
  }
```

This condition as written would never be hit, since there is always at least 1 segment (that just happens to be the target name most of the time). 

It's OK IMHO to assume it's a target name when only one segment is present, so updating the condition like above should suffice.

**Review by AgentEnder — CHANGES_REQUESTED** [review]
This makes sense to me, thanks for the contribution 🎉

Can you add a unit test and address the change I requested?

File: packages/nx/src/tasks-runner/utils.ts (hunk 1 above)
Comment (acburdine) [reply packages/nx/src/tasks-runner/utils.ts:77]: Also for what it's worth - I tested the change as I originally wrote it in my monorepo (via `patch-package`) and it did fix the issue I was experiencing.

**Review by AgentEnder — APPROVED** [review]
