### PR TITLE
fix(storybook): read package version from node_modules

### LINKED ISSUE #5100: Problem running Storybook on mixed workspaces
## Current Behavior
On a mixed workspace, when Storybook is added on a different framework it does not run.
eg. 
Workspace with Angular and React libs/apps
Add Storybook in React lib or app
Works/runs
Add Storybook in Angular lib or app
Storybook is generated
Storybook does not run

## Expected Behavior
Storybook works on mixed workspaces.

## Steps to Reproduce
Scenario 1:
1. `create-nx-workspace` with react app
2. Generate react lib as well, and one component in react lib, one component in react app
3. `@nrwl/react:storybook-configuration` schematic for react lib and react app
4. `nx run <app and lib>:storybook`
5. SUCCESS!!

Scenario 2:
1. In same workspace, generate ANGULAR lib
2. generate angular component inside angular lib
3. `@nrwl/angular:storybook-configuration` for angular lib
4. `nx run <angular lib>:storybook`
5. `ERROR: Cannot find module '@storybook/angular/dist/server/options'`

And vice-versa

### PR DESCRIPTION
**Pull request by FrozenPandaz**
## Current Behavior

The version of `@storybook` framework is read from `package.json` in the workspace  and strips out `^` which could cause the version to go above `6.2`.

## Expected Behavior

The version of `@storybook` framework is read from the `package.json` in the installed `node_module`.

## Related Issue(s)

Fixes https://github.com/nrwl/nx/issues/5100

### CODE REVIEW

**Review by juristr — APPROVED** [review]
Makes sense 👍

File: packages/storybook/src/executors/utils.ts [hunk 1]
```diff
@@ -21,19 +21,10 @@ export function getStorybookFrameworkPath(uiFramework) {
...
 
-  const storybookPackageVersion =
-    packageJsonContents.dependencies[uiFramework] ||
-    packageJsonContents.devDependencies[uiFramework];
-
-  return gte(
-    (storybookPackageVersion || '').replace('~', '').replace('^', ''),
-    '6.2.0-rc.4'
-  );
+  return gte(storybookPackageVersion, '6.2.0-rc.4');
```
Comment (juristr) [inline packages/storybook/src/executors/utils.ts:27]: > strips out ^ which could cause the version to go above 6.2.
