### PR TITLE
fix(angular): consider app-routing.module.ts when setting up module federation host routes

### LINKED ISSUE #14075: Cannot read properties of null (reading 'length') while generating @nrwl/angular:setup-mf
@Coly010 Help!!!
### Current Behavior
Getting error
'Cannot read properties of null (reading 'length')' while trying to implement mf with below command
nx generate @nrwl/angular:setup-mf mf-app --mf-type=host --routing

### Expected Behavior

Adding MF to the existing monorepo nx angular application v15

### Github Repo

https://github.com/ishanoj/mf-app-2023/tree/feature/mf-app
### Steps to Reproduce

1. npx create-nx-workspace@latest (done)
2. Creation of host and remote applications (done)
3. Trying to set-up mf(error) :(

### Nx Report

Node : 18.12.1
   OS   : win32 x64
   npm  : 9.2.0

   nx : 15.4.5
   @nrwl/angular : 15.4.5
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : Not Found
   typescript : 4.8.4

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by aliataf**
## Current Behavior

Getting `Cannot read properties of null (reading 'length')` when running:
`npx nx g @nrwl/angular:setup-mf appName --mfType=host`

## Expected Behavior

It should generate the module federation config regardless of whether you use `app.routes.ts` or `app-routing.module.ts`

## Related Issue(s)

Fixes #14075

### CODE REVIEW

File: packages/angular/src/generators/setup-mf/lib/update-host-app-routes.ts [hunk 1]
```diff
@@ -34,12 +34,17 @@ export function updateHostAppRoutes(tree: Tree, options: Schema) {
...
+  let pathToHostRootRoutingFile = joinPathFragments(
     sourceRoot,
     'app/app.routes.ts'
   );
 
-  const hostRootRoutingFile = tree.read(pathToHostRootRoutingFile, 'utf-8');
+  let hostRootRoutingFile = tree.read(pathToHostRootRoutingFile, 'utf-8');
+
+  if (!hostRootRoutingFile) {
+    pathToHostRootRoutingFile = (0, devkit_1.joinPathFragments)(sourceRoot, 'app/app-routing.module.ts');
```
Comment (leosvelperez) [inline packages/angular/src/generators/setup-mf/lib/update-host-app-routes.ts:45]: Please import `joinPathFragments` from `@nrwl/devkit`.

**Review by leosvelperez — CHANGES_REQUESTED** [review]
Thanks for the contribution!

I think this is a reasonable thing to support. There's only one issue with the changes. Once addressed, it should be good to go 🚀

File: packages/angular/src/generators/setup-mf/lib/update-host-app-routes.ts (hunk 1 above)
Comment (aliataf) [reply packages/angular/src/generators/setup-mf/lib/update-host-app-routes.ts:45]: It is already imported

Comment (leosvelperez) [reply packages/angular/src/generators/setup-mf/lib/update-host-app-routes.ts:45]: It might be imported, but you're not using the imported symbol. You're invoking `(0, devkit_1.joinPathFragments)(...)`. It seems like a copy and paste from a compiled output and it should fail the build. Instead, you should have:

```suggestion
    pathToHostRootRoutingFile = joinPathFragments(sourceRoot, 'app/app-routing.module.ts');
```

Comment (aliataf) [reply packages/angular/src/generators/setup-mf/lib/update-host-app-routes.ts]: Ah yes, was testing on a compiled code :), my bad, resolved!

**Comment by leosvelperez** [comment]
@aliataf there was an issue with CircleCI not kicking the pipeline. I had to rebase the PR to unblock it.

**Review by leosvelperez — APPROVED** [review]
