### PR TITLE
fix(core): custom schematic windows path normalization

### LINKED ISSUE #3233: Getting 'Collection "@nrwl/angular" cannot be resolved' when running workspace-schematic
## Current Behavior
When running `npm run workspace-schematic -- {{ my-schematic-name }}` the following error is appearing:

```
Error: Collection "@nrwl/angular" cannot be resolved.
```

## Expected Behavior
The schematic should run through successfully.

## Steps to Reproduce
I created a simple [GitHub repository](https://github.com/decline/nrwl-schematics-demo) so you can reproduce this:

```
git clone git@github.com:decline/nrwl-schematics-demo.git
```

```
cd nrwl-schematics-demo && npm install
```

```
npm run workspace-schematic -- test
```

Then in the interactive dialog just select "ui" for example and use "foobar" as the directory name

### Failure Logs
```
Error: Collection "@nrwl/angular" cannot be resolved.
    at NodeModulesEngineHost.resolve (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:74:19)
    at NodeModulesEngineHost._resolveCollectionPath (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:79:37)
    at NodeModulesEngineHost.createCollectionDescription (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:109:27)
    at SchematicEngine._createCollectionDescription (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
    at SchematicEngine.createCollection (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
    at /Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/src/rules/schematic.js:23:43
    at MergeMapSubscriber.project (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/src/rules/call.js:74:24)
    at MergeMapSubscriber._tryNext (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/rxjs/internal/Subscriber.js:66:18)
```

### Environment
  @nrwl/angular : 9.4.5
  @nrwl/cli : 9.4.5
  @nrwl/cypress : 9.4.5
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.4.5
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.4.5
  @nrwl/web : Not Found
  @nrwl/workspace : 9.4.5
  typescript : 3.8.3

### PR DESCRIPTION
**Pull request by rarmatei**
## Issue: 

Running a workspace schematic under Windows fails with `Error: Collection "@nrwl/angular" cannot be resolved.`

## Explanation: 

Related PR: https://github.com/nrwl/nx/pull/3252

[We normalize the appRoot before creating the NodeWorkflow](https://github.com/nrwl/nx/blob/master/packages/workspace/src/command-line/workspace-schematic.ts#L131) which breaks some paths on Windows machines.

`normalize(...)` comes from the angular-cli devkit, and has a bug where it converts windows path to unix. For example:

`C:\Users\matei\repo` turns to --> `/C/Users/matei/repo`

So part of this fix:
- I am sending the app root directly to the `NodeWorkflow`
- I am also sending `process.cwd()` and `__dirname`, as per [the Angular CLI's source](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/models/schematic-command.ts#L257)

---

Fixes #3233

### CODE REVIEW

File: packages/workspace/src/command-line/workspace-schematic.ts [hunk 1]
```diff
@@ -135,7 +135,7 @@ function createWorkflow(dryRun: boolean) {
     root,
     dryRun,
     registry: new schema.CoreSchemaRegistry(formats.standardFormats),
-    resolvePaths: [root],
+    resolvePaths: [process.cwd(), rootDirectory, root, __dirname],
```
Comment (rarmatei) [inline packages/workspace/src/command-line/workspace-schematic.ts:138]: - `process.cwd()` and `__dirname` were added as per [Angular Devkit's source](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/models/schematic-command.ts#L257)
- `rootDirectory` should be the correct, un-normalized route
- we also send the normalized `root` (which was there before) just in case it's different from the original one
