### PR TITLE
fix(angular-rspack): ensure assets extracted from stylesheets correctly #32487

### LINKED ISSUE #32487: @nx/angular-rspack: Component stylesheet assets not extracted and copied to output directory
### Current Behavior

When Angular components reference assets in their stylesheets using `url()` (e.g., `background-image: url('../assets/test-pattern.svg')`), the Nx Angular Rspack plugin processes the CSS but fails to extract and copy the referenced asset files to the output directory. This results in:

1. CSS is processed and may be rewritten to reference output paths (e.g., `url('./media/test-pattern.svg')`)
2. The actual asset files are never copied to the output directory
3. Browser shows 404 errors for missing asset files when the application runs
4. No `media` directory is created in the build output

### Expected Behavior

- Asset files referenced in component stylesheets should be extracted and copied to the output directory
- CSS URLs should be rewritten to point to the copied assets 
- No 404 errors should occur for asset files
- A `media` directory should be created in the output with the extracted assets

### GitHub Repo

https://github.com/miluoshi/angular-rspack-repro

### Steps to Reproduce

1. Create a new Nx workspace with Angular Rspack:
```bash
npx create-nx-workspace@latest repro --preset=angular-standalone --bundler=rspack --style=css --unitTestRunner=jest --e2eTestRunner=playwright --ssr=false --interactive=false
cd repro
```

2. Create an asset file:
```bash
mkdir -p src/assets
# Create src/assets/test-pattern.svg (any SVG/image file)
```

3. Add CSS rule in component stylesheet (`src/app/app.css`):
```css
.pattern-background {
  background-image: url('../assets/test-pattern.svg');
  /* other styles... */
}
```

4. Build the application:
```bash
npx nx build
```

5. Check output directory:
```bash
ls -la dist/repro/browser/
ls -la dist/repro/browser/media/  # Should exist but doesn't
```

Image

**Quick reproduction steps:**
```bash
git clone https://github.com/miluoshi/angular-rspack-repro.git
cd angular-rspack-repro
npm install
npx nx build
ls -la dist/repro/browser/media/  # Expected: media directory with test-pattern.svg, Actual: directory doesn't exist
```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 22.16.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.2

nx (global)            : 21.3.11
nx                     : 21.4.0
@nx/js                 : 21.4.0
@nx/jest               : 21.4.0
@nx/eslint             : 21.4.0
@nx/workspace          : 21.4.0
@nx/angular            : 21.4.0
@nx/devkit             : 21.4.0
@nx/eslint-plugin      : 21.4.0
@nx/module-federation  : 21.4.0
@nx/rspack             : 21.4.0
@nx/web                : 21.4.0
@nx/webpack            : 21.4.0
typescript             : 5.8.3
---------------------------------------
Registered Plugins:
@nx/angular/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/rspack/plugin
---------------------------------------
```

### Failure Logs

```shell
# Relevant source files
https://github.com/nrwl/nx/blob/master/packages/angular-rspack-compiler/src/compilation/setup-compilation.ts
https://github.com/nrwl/nx/blob/master/packages/angular-rspack-compiler/src/compilation/setup-with-angular-compilation.ts
https://github.com/nrwl/nx/blob/master/packages/angular-rspack/src/lib/plugins/angular-rspack-plugin.ts
```

### Package Manager Version

_No response_

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The issue appears to be in the Nx Angular Rspack compilation process where the `ComponentStylesheetBundler` from Angular's build system correctly processes assets and generates `outputFiles`, but these files are never emitted using `compilation.emitAsset()` in the Rspack plugin.

Technical details:
- The bug occurs in the interaction between Angular's `ComponentStylesheetBundler` and the Nx Angular Rspack plugin
- `ComponentStylesheetBundler.bundleFile()` and `ComponentStylesheetBundler.bundleInline()` return `outputFiles` containing asset data
- These `outputFiles` are currently ignored and never processed by the Rspack build pipeline
- Assets need to be emitted using `compilation.emitAsset()` during the build process

Files likely involved:
- `@nx/angular-rspack-compiler/dist/compilation/setup-compilation.js`
- `@nx/angular-rspack-compiler/dist/compilation/setup-with-angular-compilation.js` 
- `@nx/angular-rspack/dist/lib/plugins/angular-rspack-plugin.js`

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

When Angular components reference assets in their stylesheets using `url()` (e.g., `background-image: url('../assets/test-pattern.svg')`), the Nx Angular Rspack plugin processes the CSS but fails to extract and copy the referenced asset files to the output directory. This results in:

- CSS is processed and URLs may be rewritten to reference output paths (e.g., `url('./media/test-pattern.svg')`)
- The actual asset files are never copied to the output directory
- Browser shows 404 errors for missing asset files when the application runs
- No `media` directory is created in the build output

## Expected Behavior

With this fix, assets referenced in component stylesheets are now properly extracted and emitted to the output directory:

- Asset files referenced in component stylesheets are extracted and copied to the output directory
- CSS URLs are correctly rewritten to point to the copied assets
- No 404 errors occur for asset files
- A `media` directory is created in the output with the extracted assets
- Both inline and external component styles properly handle asset extraction

## Related Issue(s)

Fixes #32487

### Core Fix
- Modified the Angular Rspack plugin to properly collect and emit stylesheet assets during the compilation process
- Added asset collection during both bundle file and inline style processing in `setup-compilation.ts` and `setup-with-angular-compilation.ts`
- Implemented asset emission in the `processAssets` hook of the Angular Rspack plugin

### Test Coverage
- Added comprehensive example application (`examples/angular-rspack/csr-css-assets`) that demonstrates:
  - External component stylesheets with asset references
  - Inline component styles with asset references
  - Various asset types (SVG, images)
  - Proper asset extraction and URL rewriting

### Technical Details
The fix addresses the gap between Angular's `ComponentStylesheetBundler` which correctly processes assets and generates `outputFiles`, and the Nx Angular Rspack plugin which now properly emits these files using `compilation.emitAsset()` during the build process.

### CODE REVIEW

File: packages/angular-rspack-compiler/src/compilation/setup-with-angular-compilation.ts [hunk 1]
```diff
@@ -32,14 +33,35 @@ export async function setupCompilationWithAngularCompilation(
...
+    const result = await transformFn(styles, containingFile, stylesheetFile);
+
+    // Collect outputFiles if present
+    if (result.outputFiles && result.outputFiles.length > 0) {
+      collectedStylesheetAssets.push(...result.outputFiles);
+    }
+
+    // Return just the contents string as expected by Angular compilation
+    return result.contents;
+  };
```
Comment (leosvelperez) [inline packages/angular-rspack-compiler/src/compilation/setup-with-angular-compilation.ts:55]: We should probably have this inside the `try/catch` below.

**Review by leosvelperez — APPROVED** [review]

File: packages/angular-rspack-compiler/src/compilation/setup-with-angular-compilation.ts (hunk 1 above)
Comment (Coly010) [reply packages/angular-rspack-compiler/src/compilation/setup-with-angular-compilation.ts:55]: This will still operate under the try catch below. It's just a function that returns a function definition. The function is executed within the `angularCompilation.initialize` which is inside the try/catch
