### PR TITLE
fix(core): tree should not be changed after committed to disk in migrations

### LINKED ISSUE #17064: "Tree modified after commit to disk." during migration from v14.8.6 to v16.1.4
### Current Behavior

During the execution of `nx migrate --run-migrations`, I saw the following message:

```
  UPDATE nx.json
---------------------------------------------------------

 >  NX   Tree modified after commit to disk.

   The tree has already been committed to disk. It can no longer be modified. Do not modify the tree during a GeneratorCallback and ensure that Promises have resolved before the generator returns or resolves.
   This will be an error in version 16. Please open an issue on the Nx repo if experiencing this with a first-party plugin, or the plugin's repo if using a community plugin.

Ran update-16-0-0-add-nx-packages from @nrwl/workspace
```

The rest of the script finished successfully, and I'm not able to tell if any changes were lost or not.

The only change to `nx.json` after the migration was:

```
-    "@nrwl/react": {
+    "@nx/react": {
```

In my test repo for reproduction, I noticed some whitespace changes in the `nx.json` that didn't appear in my original repo:

For example, part of the diff in the test repo after migration:
```
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
-        "cacheableOperations": ["build", "lint", "test", "e2e"]
+        "cacheableOperations": [
+          "build",
+          "lint",
+          "test",
+          "e2e"
+        ]
      }
    }
  },
```

In my real repo, after the migration:

```
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e"]
      }
    }
  },
```

(I don't know if this is significant or not.)

### Expected Behavior

No errors/warnings during migration.

### GitHub Repo

_No response_

### Steps to Reproduce

I'm afraid I can't share my repo as it is proprietary code. However, I was able to reproduce this with a brand new repo, following the steps "Create a New Workspace" and "Create a Package" from https://nx.dev/tutorials/integrated-repo-tutorial

I had to slightly modify the commands for the older version: `latest` -> `14.8.6`, `@nx` -> `@nrwl`

1. `npx create-nx-workspace@14.8.6 myorg --preset=ts`
2. `npx nx generate @nrwl/js:library is-even --publishable --importPath @myorg/is-even`
3. `npx nx migrate latest`
4. `npx nx migrate --run-migrations`

### Nx Report

```shell
Before Migration:

>  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : linux x64
   yarn : 3.5.1
   
   nx : 14.8.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.1.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.13
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.6
   @nrwl/expo : Not Found
   @nrwl/express : 15.0.13
   @nrwl/jest : 15.0.13
   @nrwl/js : 15.0.13
   @nrwl/linter : 14.8.6
   @nrwl/nest : 15.0.13
   @nrwl/next : Not Found
   @nrwl/node : 15.0.13
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.13
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.13
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.13
   @nrwl/web : 15.0.13
   @nrwl/webpack : 15.0.13
   @nrwl/workspace : 14.8.6
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:


After Migration:

>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.13.0
   OS     : linux x64
   yarn   : 3.5.1
   Hasher : Native
   
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/express        : 16.1.4
   @nx/nest           : 16.1.4
   @nx/node           : 16.1.4
   @nx/react          : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/web            : 16.1.4
   @nx/webpack        : 16.1.4
   typescript         : 5.0.4
```

### Failure Logs

```shell
>  NX   Running 'yarn' to make sure necessary packages are installed

➤ YN0000: ┌ Resolution step
<snipping out ~2000 lines of yarn not having new files cached, etc.>


 >  NX   Running migrations from 'migrations.json'

Ran 15.0.0-prefix-outputs from nx
  Prefix outputs with {workspaceRoot}/{projectRoot} if needed

  UPDATE apps/cortex-app/project.json
  UPDATE apps/crtx-nest/project.json
  UPDATE apps/migrator/project.json
  UPDATE libs/db-orm/project.json
---------------------------------------------------------
Ran 16.0.0-remove-nrwl-cli from nx
  Remove @nrwl/cli.

  UPDATE package.json
---------------------------------------------------------
Ran 16.0.0-tokens-for-depends-on from nx
  Replace `dependsOn.projects` and `inputs` definitions with new configuration format.

  UPDATE apps/crtx-nest/project.json
---------------------------------------------------------
Ran 16.0.0-update-nx-cloud-runner from nx
  Replace @nrwl/nx-cloud with nx-cloud

  UPDATE nx.json
---------------------------------------------------------

 >  NX   Tree modified after commit to disk.

   The tree has already been committed to disk. It can no longer be modified. Do not modify the tree during a GeneratorCallback and ensure that Promises have resolved before the generator returns or resolves.
   This will be an error in version 16. Please open an issue on the Nx repo if experiencing this with a first-party plugin, or the plugin's repo if using a community plugin.

\0\0\0\0\0\0\0\0\0\0Ran update-16-0-0-add-nx-packages from @nrwl/workspace
  Replace @nrwl/workspace with @nx/workspace

  UPDATE package.json
  UPDATE apps/cortex-app/project.json
  UPDATE migrations.json
  UPDATE nx-migrate--run-migrations.log
  UPDATE nx-migrate-latest.log
---------------------------------------------------------
Ran add-eslint-ignore from @nx/linter
  Add node_modules to root eslint ignore

  CREATE .eslintignore
---------------------------------------------------------
\0\0\0\0\0\0\0\0\0\0\0\0Ran update-16-0-0-add-nx-packages from @nrwl/linter
  Replace @nrwl/linter with @nx/linter

  UPDATE package.json
  UPDATE apps/cortex-app/project.json
  UPDATE apps/cortex-app-e2e/project.json
  UPDATE apps/crtx-nest/project.json
  UPDATE apps/data-seeder/project.json
  UPDATE apps/factory-configuration/project.json
  UPDATE apps/migrator/project.json
  UPDATE libs/crtx-protos/project.json
  UPDATE libs/crtx-protos-web/project.json
  UPDATE libs/db-orm/project.json
  UPDATE libs/grpc-utils/project.json
  UPDATE libs/i18n/project.json
  UPDATE libs/labels/project.json
  UPDATE libs/pb-entity-conversion/project.json
  UPDATE libs/proto-loader-wrapper/project.json
  UPDATE libs/sheet-utils/project.json
  UPDATE libs/utils/project.json
  UPDATE migrations.json
  UPDATE nx-migrate--run-migrations.log
  UPDATE nx-migrate-latest.log
---------------------------------------------------------
Ran update-to-cypress-12 from @nx/cypress
  Update to Cypress v12. Cypress 12 contains a handful of breaking changes that might causes tests to start failing that nx cannot directly fix. Read more Cypress 12 changes: https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-12-0.This migration will only run if you are already using Cypress v11.

  UPDATE apps/cortex-app-e2e/cypress.config.ts
  UPDATE package.json
---------------------------------------------------------
\0\0\0\0\0\0\0\0\0\0\0\0Ran update-16-0-0-add-nx-packages from @nrwl/cypress
  Replace @nrwl/cypress with @nx/cypress

  UPDATE package.json
  UPDATE apps/cortex-app-e2e/project.json
  UPDATE apps/cortex-app-e2e/cypress.config.ts
  UPDATE migrations.json
  UPDATE nx-migrate--run-migrations.log
  UPDATE nx-migrate-latest.log
---------------------------------------------------------
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0Ran update-16-0-0-add-nx-packages from @nrwl/eslint-plugin-nx
  Replace @nrwl/eslint-plugin-nx with @nx/eslint-plugin

  UPDATE package.json
  UPDATE migrations.json
  UPDATE nx-migrate--run-migrations.log
  UPDATE nx-migrate-latest.log
  UPDATE .eslintrc.json
  UPDATE apps/cortex-app/.eslintrc.json
  UPDATE apps/data-seeder/src/main.ts
  UPDATE apps/factory-configuration/src/main.ts
  UPDATE libs/db-orm/src/pg-migrations/Migration20230509144212.ts
  UPDATE libs/i18n/.eslintrc.json
  UPDATE libs/labels/.eslintrc.json
  UPDATE libs/sheet-utils/src/lib/flow.ts
---------------------------------------------------------
Ran update-babel-preset from @nx/web
  Update `@nx/web/babel` preset to `@nrwl/js/babel` for projects that have a .babelrc file.

  UPDATE package.json
  UPDATE libs/crtx-protos/.babelrc
  UPDATE libs/crtx-protos-web/.babelrc
  UPDATE libs/db-orm/.babelrc
  UPDATE libs/grpc-utils/.babelrc
  UPDATE libs/pb-entity-conversion/.babelrc
  UPDATE libs/proto-loader-wrapper/.babelrc
  UPDATE libs/sheet-utils/.babelrc
  UPDATE libs/utils/.babelrc
---------------------------------------------------------
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0Ran update-16-0-0-add-nx-packages from @nrwl/web
  Replace @nrwl/web with @nx/web

  UPDATE package.json
  UPDATE apps/cortex-app/project.json
  UPDATE apps/crtx-nest/project.json
  UPDATE apps/data-seeder/project.json
  UPDATE apps/factory-configuration/project.json
  UPDATE apps/migrator/project.json
  UPDATE migrations.json
  UPDATE nx-migrate--run-migrations.log
  UPDATE nx-migrate-latest.log
---------------------------------------------------------
\0\0\0\0\0\0\0\0\0\0Ran update-16-0-0-add-nx-packages from @nrwl/react
  Replace @nrwl/react with @nx/react

  UPDATE package.json
  UPDATE nx.json
  UPDATE apps/cortex-app/.babelrc
  UPDATE apps/cortex-app/jest.config.ts
  UPDATE apps/cortex-app/tsconfig.app.json
  UPDATE apps/cortex-app/tsconfig.spec.json
  UPDATE apps/cortex-app/webpack.config.js
  UPDATE apps/cortex-app/webpack_pdfkitFEapp_config_js
  UPDATE libs/i18n/.babelrc
  UPDATE libs/i18n/jest.config.ts
  UPDATE libs/i18n/tsconfig.lib.json
  UPDATE libs/labels/.babelrc
  UPDATE libs/labels/tsconfig.lib.json
  UPDATE migrations.json
  UPDATE nx-migrate--run-migrations.log
  UPDATE nx-migrate-latest.log
---------------------------------------------------------

>  NX  Jest Snapshot format changed in v29.
By default Nx kept the older style to prevent breaking of existing tests with snapshots.
It's recommend you update to the latest format.
You can do this in your project's jest config file.
Remove the snapshotFormat property and re-run tests with the --update-snapshot flag.
More info: https://jestjs.io/docs/upgrading-to-jest29#snapshot-format

Ran update-configs-jest-29 from @nx/jest
  Update jest configs to support jest 29 changes (https://jestjs.io/docs/upgrading-to-jest29)

  UPDATE apps/factory-configuration/jest.config.ts
  UPDATE libs/pb-entity-conversion/jest.config.ts
  UPDATE libs/proto-loader-wrapper/jest.config.ts
  UPDATE libs/crtx-protos-web/jest.config.ts
  UPDATE apps/data-seeder/jest.config.ts
  UPDATE libs/crtx-protos/jest.config.ts
  UPDATE libs/sheet-utils/jest.config.ts
  UPDATE libs/grpc-utils/jest.config.ts
  UPDATE apps/crtx-nest/jest.config.ts
  UPDATE apps/migrator/jest.config.ts
  UPDATE libs/db-orm/jest.config.ts
  UPDATE libs/utils/jest.config.ts
  UPDATE jest.preset.js
---------------------------------------------------------
\0\0\0\0\0\0\0\0\0\0\0\0Ran update-16-0-0-add-nx-packages from @nrwl/jest
  Replace @nrwl/jest with @nx/jest

  UPDATE package.json
  UPDATE apps/cortex-app/project.json
  UPDATE apps/crtx-nest/project.json
  UPDATE apps/data-seeder/project.json
  UPDATE apps/factory-configuration/project.json
  UPDATE apps/migrator/project.json
  UPDATE libs/crtx-protos/project.json
  UPDATE libs/crtx-protos-web/project.json
  UPDATE libs/db-orm/project.json
  UPDATE libs/grpc-utils/project.json
  UPDATE libs/i18n/project.json
  UPDATE libs/labels/project.json
  UPDATE libs/pb-entity-conversion/project.json
  UPDATE libs/proto-loader-wrapper/project.json
  UPDATE libs/sheet-utils/project.json
  UPDATE libs/utils/project.json
  UPDATE jest.config.ts
  UPDATE jest.preset.js
  UPDATE migrations.json
  UPDATE nx-migrate--run-migrations.log
  UPDATE nx-migrate-latest.log
---------------------------------------------------------
\0\0\0\0\0\0\0\0\0\0Ran update-16-0-0-add-nx-packages from @nrwl/node
  Replace @nrwl/node with @nx/node

  UPDATE package.json
  UPDATE migrations.json
  UPDATE nx-migrate--run-migrations.log
  UPDATE nx-migrate-latest.log
---------------------------------------------------------
\0\0\0\0\0\0\0\0\0\0Ran update-16-0-0-add-nx-packages from @nrwl/express
  Replace @nrwl/express with @nx/express

  UPDATE package.json
  UPDATE migrations.json
  UPDATE nx-migrate--run-migrations.log
  UPDATE nx-migrate-latest.log
---------------------------------------------------------
\0\0\0\0\0\0\0\0\0\0Ran update-16-0-0-add-nx-packages from @nrwl/nest
  Replace @nrwl/nest with @nx/nest

  UPDATE package.json
  UPDATE migrations.json
  UPDATE nx-migrate--run-migrations.log
  UPDATE nx-migrate-latest.log
---------------------------------------------------------

 >  NX   Running 'yarn' to make sure necessary packages are installed

➤ YN0000: ┌ Resolution step
➤ YN0002: │ @antv/layout@npm:0.3.16 doesn't provide dagre (p00bff), requested by dagre-compound
➤ YN0002: │ @nrwl/devkit@npm:16.1.4 doesn't provide nx (p364b9), requested by @nx/devkit
➤ YN0002: │ @nrwl/eslint-plugin-nx@npm:16.1.4 doesn't provide @typescript-eslint/parser (pfb2a6), requested by @nx/eslint-plugin
➤ YN0002: │ @nx/cypress@npm:16.1.4 [38870] doesn't provide nx (pb9f52), requested by @nx/devkit
➤ YN0002: │ @nx/cypress@npm:16.1.4 [38870] doesn't provide typescript (p260bc), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/cypress@npm:16.1.4 [cd40e] doesn't provide nx (pb22e2), requested by @nx/devkit
➤ YN0002: │ @nx/cypress@npm:16.1.4 [cd40e] doesn't provide typescript (p2896d), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/eslint-plugin@npm:16.1.4 [45323] doesn't provide eslint (p291db), requested by @typescript-eslint/utils
➤ YN0002: │ @nx/eslint-plugin@npm:16.1.4 [45323] doesn't provide eslint (p04bb2), requested by @typescript-eslint/type-utils
➤ YN0002: │ @nx/eslint-plugin@npm:16.1.4 [45323] doesn't provide nx (pfa141), requested by @nx/devkit
➤ YN0002: │ @nx/eslint-plugin@npm:16.1.4 [cd40e] doesn't provide eslint (pb12cc), requested by @typescript-eslint/utils
➤ YN0002: │ @nx/eslint-plugin@npm:16.1.4 [cd40e] doesn't provide eslint (pb209f), requested by @typescript-eslint/type-utils
➤ YN0002: │ @nx/eslint-plugin@npm:16.1.4 [cd40e] doesn't provide nx (pdbb8e), requested by @nx/devkit
➤ YN0002: │ @nx/express@npm:16.1.4 [296f8] doesn't provide nx (p450b2), requested by @nx/devkit
➤ YN0002: │ @nx/express@npm:16.1.4 [cd40e] doesn't provide nx (p08ba1), requested by @nx/devkit
➤ YN0002: │ @nx/jest@npm:16.1.4 doesn't provide nx (p5aeee), requested by @nx/devkit
➤ YN0002: │ @nx/jest@npm:16.1.4 doesn't provide typescript (paa1f5), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/js@npm:16.1.4 doesn't provide nx (p76e8e), requested by @nx/devkit
➤ YN0002: │ @nx/js@npm:16.1.4 doesn't provide typescript (pf37cc), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/linter@npm:16.1.4 [3fde8] doesn't provide nx (peea99), requested by @nx/devkit
➤ YN0002: │ @nx/linter@npm:16.1.4 [3fde8] doesn't provide typescript (p1bf3c), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/linter@npm:16.1.4 [cd40e] doesn't provide nx (pe10bf), requested by @nx/devkit
➤ YN0002: │ @nx/linter@npm:16.1.4 [cd40e] doesn't provide typescript (pde2f7), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/nest@npm:16.1.4 doesn't provide nx (pdb7f4), requested by @nx/devkit
➤ YN0002: │ @nx/nest@npm:16.1.4 doesn't provide typescript (p935f4), requested by @nestjs/schematics
➤ YN0002: │ @nx/node@npm:16.1.4 doesn't provide nx (p7b554), requested by @nx/devkit
➤ YN0002: │ @nx/react@npm:16.1.4 doesn't provide nx (p123b3), requested by @nx/devkit
➤ YN0002: │ @nx/react@npm:16.1.4 doesn't provide typescript (p7b2b0), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/react@npm:16.1.4 doesn't provide webpack (pc8c3e), requested by file-loader
➤ YN0002: │ @nx/web@npm:16.1.4 doesn't provide nx (p3c492), requested by @nx/devkit
➤ YN0002: │ @nx/webpack@npm:16.1.4 doesn't provide @types/node (p12159), requested by ts-node
➤ YN0002: │ @nx/webpack@npm:16.1.4 doesn't provide nx (p806eb), requested by @nx/devkit
➤ YN0002: │ @nx/webpack@npm:16.1.4 doesn't provide typescript (p19f58), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ @nx/webpack@npm:16.1.4 doesn't provide typescript (pd91ec), requested by ts-loader
➤ YN0002: │ @nx/webpack@npm:16.1.4 doesn't provide typescript (pc8e6c), requested by ts-node
➤ YN0002: │ crtx@workspace:. doesn't provide @babel/core (p19b57), requested by babel-jest
➤ YN0002: │ crtx@workspace:. doesn't provide @mui/system (pcefdf), requested by @mui/x-data-grid
➤ YN0002: │ crtx@workspace:. doesn't provide @mui/system (pcbc1f), requested by @mui/x-date-pickers
➤ YN0002: │ crtx@workspace:. doesn't provide prop-types (pb9dca), requested by react-csv-reader
➤ YN0002: │ crtx@workspace:. doesn't provide prop-types (pa04cd), requested by react-moment
➤ YN0060: │ crtx@workspace:. provides react (pc6873) with version 18.2.0, which doesn't satisfy what react-csv-reader requests
➤ YN0060: │ crtx@workspace:. provides react-dom (pb25e5) with version 18.2.0, which doesn't satisfy what react-csv-reader requests
➤ YN0002: │ crtx@workspace:. doesn't provide react-scripts (pece75), requested by next-barcode
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 1s 93ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ commander@npm:6.2.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ cypress@npm:12.12.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ minimist@npm:1.2.8 can't be found in the cache and will be fetched from the remote registry
➤ YN0019: │ @nrwl-cli-npm-14.8.6-89ca937db1-62d8bcf31e.zip appears to be unused - removing
➤ YN0019: │ @nrwl-tao-npm-14.8.6-be436a771d-ea9b3fcce8.zip appears to be unused - removing
➤ YN0013: │ cypress@npm:12.12.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ minimist@npm:1.2.8 can't be found in the cache and will be fetched from the remote registry
➤ YN0019: │ @nrwl-cli-npm-14.8.6-89ca937db1-62d8bcf31e.zip appears to be unused - removing
➤ YN0019: │ @nrwl-tao-npm-14.8.6-be436a771d-ea9b3fcce8.zip appears to be unused - removing
➤ YN0019: │ commander-npm-5.1.0-7e939e7832-0b7fec1712.zip appears to be unused - removing
➤ YN0013: │ minimist@npm:1.2.8 can't be found in the cache and will be fetched from the remote registry
➤ YN0019: │ @nrwl-cli-npm-14.8.6-89ca937db1-62d8bcf31e.zip appears to be unused - removing
➤ YN0019: │ @nrwl-tao-npm-14.8.6-be436a771d-ea9b3fcce8.zip appears to be unused - removing
➤ YN0019: │ commander-npm-5.1.0-7e939e7832-0b7fec1712.zip appears to be unused - removing
➤ YN0019: │ cypress-npm-11.2.0-2547cc03bc-e13649fb4b.zip appears to be unused - removing
➤ YN0019: │ @nrwl-cli-npm-14.8.6-89ca937db1-62d8bcf31e.zip appears to be unused - removing
➤ YN0019: │ @nrwl-tao-npm-14.8.6-be436a771d-ea9b3fcce8.zip appears to be unused - removing
➤ YN0019: │ commander-npm-5.1.0-7e939e7832-0b7fec1712.zip appears to be unused - removing
➤ YN0019: │ cypress-npm-11.2.0-2547cc03bc-e13649fb4b.zip appears to be unused - removing
➤ YN0019: │ nx-npm-14.8.6-807dcc2c25-cfb6360cec.zip appears to be unused - removing
➤ YN0000: └ Completed in 0s 419ms
➤ YN0000: ┌ Link step
➤ YN0008: │ argon2@npm:0.30.3 must be rebuilt because its dependency tree changed
➤ YN0007: │ cypress@npm:12.12.0 must be built because it never has been before or the last one failed
➤ YN0008: │ @parcel/watcher@npm:2.0.4 must be rebuilt because its dependency tree changed
➤ YN0008: │ sqlite3@npm:5.1.2 [7996d] must be rebuilt because its dependency tree changed
➤ YN0008: │ nx@npm:16.1.4 [a9460] must be rebuilt because its dependency tree changed
➤ YN0000: └ Completed in 2s 636ms
➤ YN0000: Done with warnings in 4s 555ms

 >  NX   Successfully finished running migrations from 'migrations.json'. This workspace is up to date!
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
It is hard to debug when a migration writes to the tree after it has been committed. This only occurs when an async statement is not awaited or similar issues with promises, and the migration is assumed to be complete. As such, the warning that you get is in the middle of other migrations and its hard to track down which migration actually has the issue.

This changes how the logs are created to include more context to make the experience nicer.

## Expected Behavior

"Changed after committed" warnings include the reason the tree was created.

## Related Issue(s)

Fixes #17064

### CODE REVIEW

**Comment by rcfox** [comment]
Maybe it would be worth adding eslint rules to catch these improperly-handled promises as well? :)

```
    ...
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "rules": {
        ...
        "@typescript-eslint/no-floating-promises": "error",
        "@typescript-eslint/no-misused-promises": ["error"],
        ...
```

* https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md
* https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-misused-promises.md

File: packages/nx/src/generators/tree.ts [hunk 1]
```diff
@@ -360,14 +364,20 @@ export class FsTree implements Tree {
       // TODO (v17): Remove condition
       if (gt(nxVersion, '17.0.0')) {
         throw new Error(
-          'The tree has already been committed to disk. It can no longer be modified. Do not modify the tree during a GeneratorCallback and ensure that Promises have resolved before the generator returns or resolves.'
+          `The tree has already been committed to disk ${
```
Comment (AgentEnder) [inline packages/nx/src/generators/tree.ts:367]: File changes have already been written to disk... 

Go ahead and make this an error.

File: packages/nx/src/generators/tree.ts [hunk 2]
```diff
@@ -357,20 +361,16 @@ export class FsTree implements Tree {
...
-          bodyLines: [
-            'The tree has already been committed to disk. It can no longer be modified. Do not modify the tree during a GeneratorCallback and ensure that Promises have resolved before the generator returns or resolves.',
-            `This will be an error in version 16. Please open an issue on the Nx repo if experiencing this with a first-party plugin, or the plugin's repo if using a community plugin.`,
-          ],
-        });
-      }
+      output.error({
+        title: `File changes have already been written to disk. Further changes were attempted ${
+          this.logOperationId ? `while running ${this.logOperationId}.` : '.'
+        }`,
```
Comment (leosvelperez) [inline packages/nx/src/generators/tree.ts:367]: nit:
```suggestion
        title: `File changes have already been written to disk. Further changes were attempted${
          this.logOperationId ? ` while running ${this.logOperationId}.` : '.'
        }`,
```

File: packages/nx/src/generators/tree.ts [hunk 3]
```diff
@@ -357,20 +361,16 @@ export class FsTree implements Tree {
...
+        bodyLines: [
+          'It can no longer be modified. This commonly happens when a generator attempts to make further ',
```
Comment (leosvelperez) [inline packages/nx/src/generators/tree.ts:369]: Now there's no previous mention of the tree. I think the `It` here lacks context about what it's referring to.
```suggestion
          'The tree can no longer be modified. This commonly happens when a generator attempts to make further ',
```

File: packages/nx/src/generators/tree.ts [hunk 4]
```diff
@@ -357,20 +361,16 @@ export class FsTree implements Tree {
...
+          'changes in its callback, or an asynchronous operation is still running after the generator completes.',
```
Comment (leosvelperez) [inline packages/nx/src/generators/tree.ts:370]: Splitting a single sentence into multiple lines can make the sentence split weirdly in the terminal when the terminal is narrower than the parts. I think it's better not to break a sentence into various lines.

**Review by leosvelperez — CHANGES_REQUESTED** [review]

File: packages/nx/src/generators/tree.ts (hunk 4 above)
Comment (AgentEnder) [reply packages/nx/src/generators/tree.ts:370]: Sure, that makes sense.
