### PR TITLE
fix(core): validate native file cache size before applying it

### LINKED ISSUE #31300: 21.1.1 postinstall hangs on Windows 11
### Current Behavior

When trying to install nx globally the postinstall step hangs forever.  When breaking an error is printed about not being able to remove certain directories.  I've tried both admin and non-admin mode running the console.

```json
Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     '\\\\?\\C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\nx',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\<user>\AppData\Roaming\npm\node_modules\nx\node_modules\axios\lib\platform\browser\classes'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\nx\\node_modules\\axios\\lib\\platform\\browser\\classes'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     '\\\\?\\C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\nx\\node_modules',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\<user>\AppData\Roaming\npm\node_modules\nx\node_modules\@tybys'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\nx\\node_modules\\@tybys'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
```

### Expected Behavior

Expected to install

### GitHub Repo

_No response_

### Steps to Reproduce

1. run `npm add --global nx@latest --verbose`

```
npm verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@10.9.2
npm info using node@v22.15.1
npm verbose title npm add nx@latest
npm verbose argv "add" "--global" "nx@latest" "--loglevel" "verbose"
...
...
npm http cache brace-expansion@https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz 0ms (cache hit)
npm http cache ansi-colors@https://registry.npmjs.org/ansi-colors/-/ansi-colors-4.1.3.tgz 0ms (cache hit)
npm http cache ansi-regex@https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz 0ms (cache hit)
npm http cache balanced-match@https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz 0ms (cache hit)
npm http cache ansi-styles@https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz 0ms (cache hit)
npm info run nx@21.1.1 postinstall node_modules/nx node ./bin/post-install
```

### Nx Report

```shell
Unable
```

### Failure Logs

```shell
851 warn cleanup Failed to remove some directories [
851 warn cleanup   [
851 warn cleanup     '\\\\?\\C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\nx\\node_modules',
851 warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\<user>\AppData\Roaming\npm\node_modules\nx\node_modules\@tybys'] {
851 warn cleanup       errno: -4048,
851 warn cleanup       code: 'EPERM',
851 warn cleanup       syscall: 'rmdir',
851 warn cleanup       path: 'C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\nx\\node_modules\\@tybys'
851 warn cleanup     }
851 warn cleanup   ]
851 warn cleanup ]
852 verbose stack Error: command failed
852 verbose stack     at promiseSpawn (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:22:22)
852 verbose stack     at spawnWithShell (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:124:10)
852 verbose stack     at promiseSpawn (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:12:12)
852 verbose stack     at runScriptPkg (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script-pkg.js:77:13)
852 verbose stack     at runScript (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script.js:9:12)
852 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\rebuild.js:329:17
852 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:67:22)
852 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:84:9
852 verbose stack     at new Promise (<anonymous>)
852 verbose stack     at callLimit (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:35:69)
853 verbose pkgid nx@21.1.1
854 error code 3221225786
855 error path C:\Users\<user>\AppData\Roaming\npm\node_modules\nx
856 error command failed
857 error command C:\WINDOWS\system32\cmd.exe /d /s /c node ./bin/post-install
858 error ^C
```

### Package Manager Version

npm@10.9.2

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

I've tried deleting the @tybys directory referenced manually but on next install it gets recreated again and can't be deleted by the installer.

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
We dont validate the size of the native file cache after copying it, which sometimes fails and corrupts the data. This failure results in a different size, so we can detect it. In certain situations, the corruption causes node to hang instead of throw.

## Expected Behavior
We detect the corruption

## Related Issue(s)

Fixes #30653
Fixes #31300

### CODE REVIEW

File: packages/nx/src/native/index.js [hunk 1]
```diff
@@ -83,22 +98,51 @@ Module._load = function (request, parent, isMain) {
...
+        unlinkSync(tmpTmpFile);
+      } catch {
+        // Ignore cleanup errors
+      }
 
-    // Load from the final location
-    return originalLoad.apply(this, [tmpFile, parent, isMain]);
+      if (attempt < maxRetries) {
+        // Will retry
+        continue;
```
Comment (FrozenPandaz) [inline packages/nx/src/native/index.js]: Remove the continue

File: packages/nx/src/native/index.js [hunk 2]
```diff
@@ -83,22 +98,51 @@ Module._load = function (request, parent, isMain) {
...
     if (!existsSync(nativeFileCacheLocation)) {
       mkdirSync(nativeFileCacheLocation, { recursive: true });
     }
-    // First copy to a unique location for each process
-    copyFileSync(nativeLocation, tmpTmpFile);
 
-    // Then rename to the final location
-    renameSync(tmpTmpFile, tmpFile);
+    // Retry copying up to 3 times, validating after each copy
+    const maxRetries = 3;
```
Comment (FrozenPandaz) [inline packages/nx/src/native/index.js]: move this to the module level

**Review by FrozenPandaz — APPROVED** [review]
