### PR TITLE
fix(core): migrate old invalid glob syntax in target outputs

### LINKED ISSUE #18075: 16.5.1: outputs glob with extensions stoped working
### Current Behavior

```json
        "outputs": [
          "{projectRoot}/.build/**/*.(js|map|ts)"
        ]
```

Cache is empty for my task. If I remove the extensions, it caches everything but other undesirable files are also cached.

### Expected Behavior

nx should cache all files in the `.build` folder with `js`, `map` or `ts` extension. It is working fine on nx 16.4.x but it stoped working after upgrading to 16.5.1.

### GitHub Repo

_No response_

### Steps to Reproduce

1. add file extension to outputs glob
2. execute task
3. remove outputs folder
4. run task again, nx should restore from cache and not reexecute the task
5. verify that output folder is empty

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.1
   OS     : darwin-arm64
   npm    : 9.5.1
   
   nx             : 16.5.1
   @nx/js         : 16.5.1
   @nx/jest       : 16.5.1
   @nx/linter     : 16.5.1
   @nx/workspace  : 16.5.1
   @nx/devkit     : 16.5.1
   @nx/plugin     : 16.5.1
   @nrwl/tao      : 16.5.1
   nx-cloud       : 16.0.5
   typescript     : 5.1.3
```

### Failure Logs

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Cammisuli**
## Current Behavior

Invalid glob syntax in target outputs do not work (ie. `dist/*.(js|map|ts)`. This was because our older glob utility allowed this.

## Expected Behavior

This migrates outputs that have the invalid syntax to `dist/*.{js,map,ts}`. 

## Related Issue(s)

Fixes #18075

### CODE REVIEW

**Review by AgentEnder — APPROVED** [review]

File: packages/nx/src/migrations/update-16-5-4/update-output-globs.ts [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+  }
+  return outputs;
+}
+
+export default async function updateOutputsGlobs(tree: Tree) {
+  for (const [projectName, projectConfiguration] of getProjects(
+    tree
+  ).entries()) {
+    for (const [targetName, targetConfiguration] of Object.entries(
+      projectConfiguration.targets
```
Comment (FrozenPandaz) [inline packages/nx/src/migrations/update-16-5-4/update-output-globs.ts:31]:
```suggestion
      projectConfiguration.targets ?? {}
```

File: packages/nx/src/migrations/update-16-5-4/update-output-globs.ts [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+    )) {
+      if (!Array.isArray(targetConfiguration.outputs)) {
+        continue;
+      }
+
+      targetConfiguration.outputs = replaceOutputs(targetConfiguration);
```
Comment (FrozenPandaz) [inline packages/nx/src/migrations/update-16-5-4/update-output-globs.ts:37]:
```suggestion
      targetConfiguration.outputs =  targetConfiguration.outputs.map(() => { ... })
```

File: packages/nx/src/migrations/update-16-5-4/update-output-globs.ts [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+  if (tree.exists('nx.json')) {
+    updateJson<NxJsonConfiguration>(tree, 'nx.json', (json) => {
+      for (const [, targetConfiguration] of Object.entries(
+        json.targetDefaults ?? {}
+      )) {
+        if (!Array.isArray(targetConfiguration.outputs)) {
+          continue;
+        }
+
+        targetConfiguration.outputs = replaceOutputs(targetConfiguration);
```
Comment (FrozenPandaz) [inline packages/nx/src/migrations/update-16-5-4/update-output-globs.ts:51]:
```suggestion
      targetConfiguration.outputs =  targetConfiguration.outputs.map(() => { ... })
```

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
