### PR TITLE
fix(nextjs): Add missing support swc for custom server

### LINKED ISSUE #21217: [Next] @nx/next:custom-server with --compiler=swc still use @nx/js:tsc as executor
### Current Behavior

Install next custom server with @nx/next:custom-server along with --compiler=swc option still use @nx/js:tsc as executor of the `build-custom-server` target.

### Expected Behavior

Should use @nx/js:swc

### GitHub Repo

_No response_

### Steps to Reproduce

npx create-nx-workspace test --preset=next --appName=www --nextAppDir=true --nxCloud=false --style=scss --e2eTestRunner=cypress \
cd test
npx nx g @nx/next:custom-server --project=www --compiler=swc

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-arm64
   npm    : 10.2.3

   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/next           : 17.2.8
   @nx/react          : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   typescript         : 5.2.2
```

### Failure Logs

_No response_

### Package Manager Version

10.2.3

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ndcunningham**
## Current Behavior

When you generate a custom server with `--swc` enabled it uses `@nx/jsc:tsc` as the executor for building the server

## Expected Behavior

1. It should use `@nx/js:swc` for building the custom server.
2. It should install swc dependencies if missing.
3. It should generate a `.swcrc` file

## Related Issue(s)

Fixes #21217

### CODE REVIEW

File: packages/next/src/utils/add-swc-to-custom-server.ts [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+    {},
+    {
+      '@swc-node/register': swcNodeVersion,
+      '@swc/cli': swcCliVersion,
+      '@swc/core': swcCoreVersion,
+    }
+  );
+}
+
+export function addSwcConfigFile(tree: Tree, swcConfigPath: string) {
```
Comment (jaysoo) [inline packages/next/src/utils/add-swc-to-custom-server.ts:44]: Instead of this we could use `addSwcConfig` from `@nx/js`?

**Review by jaysoo — APPROVED** [review]
