### PR TITLE
fix(angular): use path property correctly when generating scams #8083

### LINKED ISSUE #8083: Couldn't find component at path to add SCAM setup.
## Current Behavior

When I try to create a new scam component I got an error:
```
Couldn't find component at path libs/ng-lib/src/lib/foo/foo.component.ts to add SCAM setup.
error Command failed with exit code 1.
```

Also, I get the capital letter "C" in the schematics field:  
in type Adds a developer-defined type to the filename, in the format "name.type.ts".

## Expected Behavior
I would expect to generate a new component.

## Steps to Reproduce

```
npx create-nx-workspace (empty)
yarn add -D @nrwl/angular @nrwl/node
yarn nx g @nrwl/node,angular:app ...
yarn nx g @nrwl/angular:lib ng-lib ...

yarn nx generate @nrwl/angular:scam --name=foo --project=ng-lib --path=apps/nx-ui/src/app --type=component 
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
>  NX  Report complete - copy this into the issue template

  Node : 16.13.0
  OS   : darwin arm64
  yarn : 1.22.11

  nx : 13.3.0
  @nrwl/angular : 13.3.0
  @nrwl/cli : 13.3.0
  @nrwl/cypress : 13.3.0
  @nrwl/devkit : 13.3.0
  @nrwl/eslint-plugin-nx : 13.3.0
  @nrwl/express : undefined
  @nrwl/jest : 13.3.0
  @nrwl/linter : 13.3.0
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.3.0
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.0
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.0
  @nrwl/storybook : 13.3.0
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
  	 @angular/animations: 13.1.0
  	 @angular/common: 13.1.0
  	 @angular/compiler: 13.1.0
  	 @angular/core: 13.1.0
  	 @angular/forms: 13.1.0
  	 @angular/platform-browser: 13.1.0
  	 @angular/platform-browser-dynamic: 13.1.0
  	 @angular/router: 13.1.0
  	 @angular-devkit/build-angular: 13.0.4
  	 @angular/cli: 13.0.4
  	 @angular/compiler-cli: 13.1.0
  	 @angular/language-service: 13.1.0
  	 @nrwl/js: 13.3.0

```

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior
Using the `--path` property causes an error because the generator does not consider it.

## Expected Behavior
Use the `--path` property correctly to resolve the new component correctly.

## Related Issue(s)

Fixes #8083

### CODE REVIEW

File: packages/angular/src/generators/scam/scam.ts [hunk 1]
```diff
@@ -21,4 +29,20 @@ export async function scamGenerator(tree: Tree, schema: Schema) {
   await formatFiles(tree);
 }
 
+function checkPathUnderProjectRoot(tree: Tree, options: Partial<Schema>) {
+  const project =
+    options.project ?? readWorkspaceConfiguration(tree).defaultProject;
+  const { sourceRoot } = readProjectConfiguration(tree, project);
+
+  if (!options.path) {
```
Comment (leosvelperez) [inline packages/angular/src/generators/scam/scam.ts:37]: Not a big deal, but it's probably better to move this to the top to bailout earlier and avoid reading configuration if not needed.

File: packages/angular/src/generators/scam/scam.ts [hunk 2]
```diff
@@ -21,4 +29,20 @@ export async function scamGenerator(tree: Tree, schema: Schema) {
...
+    return;
+  }
+
+  if (!normalize(options.path).startsWith(normalize(sourceRoot))) {
```
Comment (leosvelperez) [inline packages/angular/src/generators/scam/scam.ts:41]: I think we shouldn't restrict to `sourceRoot` and instead use `root`, it's ok as long as it is inside the root of the project. Also, `sourceRoot` is nullable, it might not be set.

Another things is that we need to use normalize the path differently, just using `normalize` from `path` won't solve the scenario where:

- `project.root` is `apps/app1`
- the provided path is `/apps/app1`

Or vice-versa.

The paths won't match even though they should.

Test cases for these scenarios would be great.

File: packages/angular/src/generators/scam/lib/create-module.ts [hunk 3]
```diff
@@ -31,6 +32,28 @@ export function createScam(tree: Tree, schema: Schema) {
...
+          projectConfig.sourceRoot,
+          projectConfig.projectType === 'application' ? 'app' : 'lib',
+          folderToPlaceIn
+        )
+      : joinPathFragments(
+          projectConfig.sourceRoot,
+          projectConfig.projectType === 'application' ? 'app' : 'lib',
+          folderToPlaceIn,
+          componentNames.fileName
+        );
```
Comment (leosvelperez) [inline packages/angular/src/generators/scam/lib/create-module.ts:54]: We shouldn't need to do this if we already have validated the provided path starts with the `sourceRoot` (though we should change it to `root`). We should just use the provided path as the folder where to place the component.

I think this whole block can be simplified to:

```typescript
componentDirectory = schema.flat
  ? normalizePath(schema.path)
  : joinPathFragments(schema.path, componentNames.fileName);
```

> **Note**: `normalizePath` can be imported from `@nrwl/devkit`.

File: docs/angular/api-angular/generators/scam.md [hunk 4]
```diff
@@ -1,6 +1,6 @@
 # @nrwl/angular:scam
 
-Generate a component with an accompanying Single Angular Module Component (SCAM).
+Generate a component with an accompanying Single Component Angular Module (SCAM).
```
Comment (leosvelperez) [inline docs/angular/api-angular/generators/scam.md:3]: How did we miss this? 🤦🏻

**Review by leosvelperez — CHANGES_REQUESTED** [review]

File: packages/angular/src/generators/scam/lib/create-module.ts (hunk 3 above)
Comment (Coly010) [reply packages/angular/src/generators/scam/lib/create-module.ts:54]: I feel like i overthought this for some reason and. I'm not sure why

File: packages/angular/src/generators/scam/scam.ts (hunk 2 above)
Comment (Coly010) [reply packages/angular/src/generators/scam/scam.ts:41]: that makes sense

File: packages/angular/src/generators/scam/scam.ts (hunk 1 above)
Comment (Coly010) [reply packages/angular/src/generators/scam/scam.ts:37]: good idea!

File: docs/angular/api-angular/generators/scam.md (hunk 4 above)
Comment (Coly010) [reply docs/angular/api-angular/generators/scam.md:3]: I have no idea lol noticed it yesterday when I read the deployed docs page

**Review by leosvelperez — APPROVED** [review]
LGTM! 🎉
