### PR TITLE
fix(angular): allow boolean usage of the prompts

### LINKED ISSUE #15058: New flags (`--routing` & `--standaloneApi`) on `angular-standalone` create-nx-workspace preset cause errors
### Current Behavior

Doing the command from the [blog](https://blog.nrwl.io/nx-15-7-node-support-angular-lts-lockfile-pruning-46f067090711) `npx create-nx-workspace@latest ngapp --preset=angular-standalone --standaloneApi` throws an error log file that states:

```
 >  NX   Property 'standaloneApi' does not match the schema. '' should be a 'boolean'.
```

If I run `npx create-nx-workspace@latest ngapp --preset=angular-standalone --standaloneApi=true` it works.

---

Also, when adding the `--routing` flag the process still prompts whether you want to add routing or not...

Running `npx create-nx-workspace@latest ngapp --preset=angular-standalone --standaloneApi --routing`

Immediately prompts for:
```
? Would you like to add routing? ...
Yes
No
```

If I run `npx create-nx-workspace@latest ngapp --preset=angular-standalone --standaloneApi --routing=true`
I am not prompted to add routing.

### Expected Behavior

Using just the shorthand `--standaloneApi` flag should work without being forced to give it a boolean value.

I am not prompted to add routing to my standalone-preset workspace when I add the shorthand `--routing` flag/argument.

### GitHub Repo

_No response_

### Steps to Reproduce

Run `npx create-nx-workspace@latest ngapp --preset=angular-standalone --standaloneApi --routing`

### Nx Report

```shell
Created via v15.7.1
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Coly010**
## Current Behavior

Usage of the new `--standaloneApi` and `--routing` flags in CNW cannot be used unless given the values true or false
## Expected Behavior

Allow the flags to be used on their own

## Related Issue(s)

Fixes #15058, #15118

### CODE REVIEW

**Review by AgentEnder — APPROVED** [review]

File: packages/create-nx-workspace/bin/create-nx-workspace.ts [hunk 1]
```diff
@@ -1128,7 +1133,11 @@ async function createApp(
     restArgs.packageManager = packageManager;
   }
 
-  const args = unparse(restArgs).join(' ');
+  const args = unparse({
+    ...restArgs,
+    standaloneApi: restArgs['standaloneApi'] ? 'true' : 'false',
+    routing: restArgs['routing'] ? 'true' : 'false',
```
Comment (FrozenPandaz) [inline packages/create-nx-workspace/bin/create-nx-workspace.ts:1139]: How come these 2 flags need special treatment here? Should they actually be in `restArgs`?

Comment (Coly010) [reply packages/create-nx-workspace/bin/create-nx-workspace.ts:1139]: The `unparse` function treats booleans differently to strings. 

It will convert a falsey arg to `--no-routing`. If the type is instead a string, it keeps the value as is `--routing=false`.

It may have been a caching issue (since upgrading to node 18, I've been facing a lot of them) but I was getting unexpected behaviour when the `--routing=false` was converted to `--no-routing` and handled by the `new` generator. A routing setup was still being created.

Comment (FrozenPandaz) [reply packages/create-nx-workspace/bin/create-nx-workspace.ts:1139]: Oh.. let's look into the weird handling of `--no-routing` separately? Not giving them special treatment here should work... There are plenty of other `boolean` flags so if `--no-` isn't being handled correctly, then that would be a larger issue.

Comment (Coly010) [reply packages/create-nx-workspace/bin/create-nx-workspace.ts:1139]: Sure thing!

**Review by FrozenPandaz — APPROVED** [review]
