### PR TITLE
fix(core): handle blocking stdin

### LINKED ISSUE #21523: Cannot stop (Ctrl + C) nx serve command after upgrade from 17.2.8 -> 17.3.1
### Current Behavior

CTRL + C does not do anything, seems to be ignored

### Expected Behavior

CTRL + C stopping the running process

### GitHub Repo

_No response_

### Steps to Reproduce

1. run nx serve app-name

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.19.0
   OS     : linux-x64
   npm    : 10.2.5
   
   nx (global)        : 17.3.1
   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/linter         : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/angular        : 17.3.1
   @nx/cypress        : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nx/node           : 17.3.1
   @nx/storybook      : 17.3.1
   @nrwl/tao          : 17.3.1
   @nx/vite           : 17.3.1
   @nx/web            : 17.3.1
   @nx/webpack        : 17.3.1
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc               : 1.1.23
   @fortawesome/angular-fontawesome : 0.14.1
   @ngneat/spectator                : 16.0.0
   @storybook/angular               : 7.6.12
   @twittwer/compodoc               : 1.12.0
   ng-mocks                         : 14.12.1
   ngx-extended-pdf-viewer          : 18.1.14
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Build, serve, test, linting config in project.json

Other command's do not seem to be affected.

```
"targets": {
    "build": {
      "executor": "@nx/angular:webpack-browser",
      "outputs": ["{options.outputPath}"],
      "options": {
        "buildLibsFromSource": false,
        "outputPath": "dist/apps/docs",
        "index": "apps/docs/src/index.html",
        "main": "apps/docs/src/main.ts",
        "polyfills": "apps/docs/src/polyfills.ts",
        "tsConfig": "apps/docs/tsconfig.app.json",
        "inlineStyleLanguage": "scss",
        "assets": [
          "apps/docs/src/favicon.ico",
          "apps/docs/src/assets",
          ...
        ],
        "styles": ["apps/docs/src/styles.scss"],
        "scripts": []
      },
      "configurations": {
        "production": {
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "500kb",
              "maximumError": "2mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "2kb",
              "maximumError": "4kb"
            }
          ],
          "fileReplacements": [
            {
              "replace": "apps/docs/src/environments/environment.ts",
              "with": "apps/docs/src/environments/environment.prod.ts"
            }
          ],
          "outputHashing": "all"
        },
        "development": {
          "buildOptimizer": false,
          "optimization": false,
          "vendorChunk": true,
          "extractLicenses": false,
          "sourceMap": true,
          "namedChunks": true
        }
      },
      "defaultConfiguration": "production"
    },
    "serve": {
      "executor": "@nx/angular:dev-server",
      "options": {
        "buildLibsFromSource": false
      },
      "configurations": {
        "production": {
          "buildTarget": "docs:build:production"
        },
        "development": {
          "buildTarget": "docs:build:development"
        }
      },
      "defaultConfiguration": "development"
    },
    "extract-i18n": {
      "executor": "@angular-devkit/build-angular:extract-i18n",
      "options": {
        "buildTarget": "docs:build"
      }
    },
    "lint": {
      "executor": "@nx/eslint:lint"
    },
    "test": {
      "executor": "@nx/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/apps/docs"],
      "options": {
        "jestConfig": "apps/docs/jest.config.ts"
      }
    },
```

### PR DESCRIPTION
**Pull request by Cammisuli**
## Current Behavior

When stdin is being used by another process, we silently fail and all stdin will be ignored

## Expected Behavior

We now register with a polling system that will allow us to check when stdin is available and used. 

## Related Issue(s)

Fixes https://github.com/nrwl/nx/issues/21523

### CODE REVIEW

File: packages/nx/src/native/command/unix.rs [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+        format!("'{}'", path)
+    } else {
+        path
+    }
+}
+
+pub fn write_to_pty(stdin: &mut Stdin, writer: &mut impl Write) -> anyhow::Result<()> {
+    let mut buffer = [0; 1024];
+
+    let mut poll = mio::Poll::new().unwrap();
```
Comment (Cammisuli) [inline packages/nx/src/native/command/unix.rs:20]: Don't unwrap

**Review by FrozenPandaz — APPROVED** [review]
