### PR TITLE
fix(nextjs): copy the next.config.js file to the dist when building

### LINKED ISSUE #3961: Problem with configuration of next.js projects
# Bug report
Disabling x-powered-by does not work in projects with next.js

## Describe the bug
After adding `poweredByHeader: false` to `<app>/next.config.js`, 'X-Powered-By' response header changes its value from 'Nest.js' to 'Express' instead of being deleted.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
A repository has been prepared in which the problem can be reproduced:
https://github.com/DarekTechTailorCo/nxdev-nextjs-config-issue

configuration:
https://github.com/DarekTechTailorCo/nxdev-nextjs-config-issue/blob/master/apps/my-app/next.config.js#L7

Application with the above configuration is launched via `yarn start`.

## Expected behavior
The 'X-Powered-By' response header should stop being sent.

## System information
- OS: [Windows]
- Browser: Chrome 86.0.4240.111 64-bit
- Version of Next.js: 
- Version of Node.js: 12.0.0

$ nx report

>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.1
  @nrwl/cypress : 10.3.1
  @nrwl/eslint-plugin-nx : 10.3.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.1
  @nrwl/linter : 10.3.1
  @nrwl/nest : Not Found
  @nrwl/next : 10.3.1
  @nrwl/node : Not Found
  @nrwl/react : 10.3.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.1
  @nrwl/web : 10.3.1
  @nrwl/workspace : 10.3.1
  typescript : 4.0.3

### LINKED ISSUE #4048: @nrwl/next does not pickup new v10 Internationalized Routing (i18n object in next.config.js)
## Current Behavior

@nrwl/next does not pickup new v10 Internationalized Routing (i18n object in next.config.js) 

## Expected Behavior

Vercel added Internationalized Routing (i18n object in next.config.js) in Next v10. 
When I add an i18n configuration object in next.config.js I excpect that the Next app in Nx is picking it up and activates v10 Internationalized Routing.

## Steps to Reproduce

1. In an empty Nx workspace create a Next app :
``` 
nx g @nrwl/next:app web

```

2. in /apps/web/next.config.js add the i18n configuration object as per the official docs
```
 module.exports = {
  i18n: {
    locales: ['en', 'fr', 'nl'],
    defaultLocale: 'en',
  },
};

```
3. launch the Next app and try to navigate to /nl or /fr : This should display the Index Page, but it renders 404 instead.
``` 
nx serve web

```

### Environment

>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 10.3.0
  @nrwl/eslint-plugin-nx : 10.3.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.0
  @nrwl/linter : 10.3.0
  @nrwl/nest : Not Found
  @nrwl/next : 10.3.2
  @nrwl/node : Not Found
  @nrwl/react : 10.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.0
  @nrwl/web : 10.3.0
  @nrwl/workspace : 10.3.0
  typescript : 4.0.3

### PR DESCRIPTION
**Pull request by BigAB**
This is necessary for the next server to respect config options

## Current Behavior
The `next.config.js` file is working in dev, but when building for a prod environment, the file is not copied into the dist directory and doesn't work.

## Expected Behavior
The `dist` directory for the built Next.js app, should have the `next.config.js` file and it's `package.json` should include any dependencies needed for the configuration and application to work.

## Related Issue(s)

May resolve #3961 
May resolve #4048

### CODE REVIEW

File: packages/next/src/builders/build/lib/create-next-config-file.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+import { promisify } from 'util';
+import { join } from 'path';
+import { NextBuildBuilderOptions } from '../../../utils/types';
+
+const asyncCopyFile = promisify(copyFile);
+
+export async function createNextConfigFile(options: NextBuildBuilderOptions) {
+  const nextConfigPath = join(
+    options.root,
+    options.nextConfig || 'next.config.js'
```
Comment (BigAB) [inline packages/next/src/builders/build/lib/create-next-config-file.ts:11]: This is relative to the project root right?

Comment (jaysoo) [reply packages/next/src/builders/build/lib/create-next-config-file.ts:11]: No, you want the context to be passed in so you can  do this: `join(context.workspaceRoot, options.root);`

File: packages/next/src/builders/build/lib/create-next-config-file.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+  );
+  try {
+    return await asyncCopyFile(
```
Comment (jaysoo) [inline packages/next/src/builders/build/lib/create-next-config-file.ts:14]: I think we can just use `copyFileSync` since we do that in other places.

File: packages/next/src/builders/build/lib/create-package-json.ts [hunk 3]
```diff
@@ -2,23 +2,63 @@ import { BuilderContext } from '@angular-devkit/architect';
...
+function getProjectDeps(context: BuilderContext, rootPackageJson: any) {
+  const projGraph = createProjectGraph();
+  const { dependencies: deps } = calculateProjectDependencies(
+    projGraph,
+    context
+  );
+  const depNames = deps
+    .map((d) => d.node)
+    .filter((node) => node.type === 'npm')
+    .map((node) => node.name.replace('npm:', ''));
```
Comment (jaysoo) [inline packages/next/src/builders/build/lib/create-package-json.ts:18]: You can read from `node.data.packageName` which is safer in case we do change the naming convention later.

**Review by jaysoo — CHANGES_REQUESTED** [review]

File: packages/next/src/builders/build/lib/create-package-json.ts [hunk 4]
```diff
@@ -2,23 +2,63 @@ import { BuilderContext } from '@angular-devkit/architect';
...
+  const dependencies = depNames
+    .filter((packageName) => packageName in rootPackageJson.dependencies)
+    .reduce((deps, pkgName) => {
+      return { ...deps, [pkgName]: rootPackageJson.dependencies[pkgName] };
+    }, {});
+  const devDependencies = depNames
```
Comment (jaysoo) [inline packages/next/src/builders/build/lib/create-package-json.ts:24]: Do we need the `devDependencies`? Only the dependencies needed at runtime should be added right?

Comment (BigAB) [reply packages/next/src/builders/build/lib/create-package-json.ts:24]: Because the `next.config.js` may import packages from the `devDependencies` (such as `@nrwl/next` by default) we need any `devDependencies` imported as well, but it should still only be any found in the `calculateProjectDependencies()` call.

**Review by jaysoo — APPROVED** [review]
